souffle: souffle::ram::Call Class Reference
souffle::ram::Call Class Reference
Call a subroutine.
#include <Call.h>
Public Member Functions
Call (std::string name)
Call * clone () const override
Create a clone (i.e.
const std::string & getName () const
Get call name.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::string name
name of subroutine
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Call a subroutine.
Calls a subroutine
The following example shows how subroutine A is invoked
CALL A
Definition at line 38 of file Call.h.
Constructor & Destructor Documentation
Call()
souffle::ram::Call::Call (std::string name) inline
Definition at line 40 of file Call.h.
Referenced by clone().
 : name(std::move(name)) {}
Member Function Documentation
clone()
Call* souffle::ram::Call::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 47 of file Call.h.
References Call(), and name.
{
         return new Call(name);
     }
equal()
bool souffle::ram::Call::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 56 of file Call.h.
References name.
{
         const auto& other = static_cast<const Call&>(node);
         return name == other.name;
     }
getName()
const std::string& souffle::ram::Call::getName () const inline
Get call name.
Definition at line 43 of file Call.h.
References name.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::NodeGenerator::visitCall().
{
         return name;
     }
print()
void souffle::ram::Call::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 52 of file Call.h.
References name, and souffle::times().
{
         os << times(" ", tabpos) << "CALL " << name << std::endl;
     }
Field Documentation
name
std::string souffle::ram::Call::name protected
name of subroutine
Definition at line 62 of file Call.h.
Referenced by clone(), equal(), getName(), and print().
The documentation for this class was generated from the following file:
ram/Call.h