souffle: souffle::ast::analysis::SCCGraphAnalysis Class Reference
souffle::ast::analysis::SCCGraphAnalysis Class Reference
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
#include <SCCGraph.h>
Public Member Functions
std::set< const Relation * > getExternalNonOutputPredecessorRelations (const size_t scc) const
Get all external non-output predecessor relations of a given SCC.
std::set< const Relation * > getExternalOutputPredecessorRelations (const size_t scc) const
Get all external output predecessor relations of a given SCC.
std::set< const Relation * > getExternalPredecessorRelations (const size_t scc) const
Get all external predecessor relations of a given SCC.
std::set< const Relation * > getInternalInputRelations (const size_t scc) const
Get all internal input relations of a given SCC.
std::set< const Relation * > getInternalNonOutputRelationsWithExternalSuccessors (const size_t scc) const
Get all internal non-output relations of a given SCC with external successors.
std::set< const Relation * > getInternalOutputRelations (const size_t scc) const
Get all internal output relations of a given SCC.
const std::set< const Relation * > & getInternalRelations (const size_t scc) const
Get all internal relations of a given SCC.
std::set< const Relation * > getInternalRelationsWithExternalSuccessors (const size_t scc) const
Get all internal relations of a given SCC with external successors.
size_t getNumberOfSCCs () const
Get the number of SCCs in the graph.
const std::set< size_t > & getPredecessorSCCs (const size_t scc) const
Get all predecessor SCCs of a given SCC.
std::set< size_t > getPredecessorSCCs (const Relation *relation) const
Get all SCCs containing a predecessor of a given relation.
size_t getSCC (const Relation *rel) const
Get the SCC of the given relation.
const std::set< size_t > & getSuccessorSCCs (const size_t scc) const
Get all successor SCCs of a given SCC.
std::set< size_t > getSuccessorSCCs (const Relation *relation) const
Get all SCCs containing a successor of a given relation.
bool isRecursive (const size_t scc) const
Return if the given SCC is recursive.
void print (std::ostream &os) const override
Print the SCC graph.
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
SCCGraphAnalysis ()
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "scc-graph"
Private Member Functions
void scR (const Relation *relation, std::map< const Relation *, size_t > &preOrder, size_t &counter, std::stack< const Relation *> &S, std::stack< const Relation *> &P, size_t &numSCCs)
Recursive scR method for computing SCC.
Private Attributes
IOTypeAnalysis * ioType = nullptr
PrecedenceGraphAnalysis * precedenceGraph = nullptr
std::vector< std::set< size_t > > predecessors
Predecessor set for the SCC graph.
std::map< const Relation *, size_t > relationToScc
Map from node number to SCC number.
std::vector< std::set< const Relation * > > sccToRelation
Relations contained in a SCC.
std::vector< std::set< size_t > > successors
Adjacency lists for the SCC graph.
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
Definition at line 42 of file SCCGraph.h.
Constructor & Destructor Documentation
SCCGraphAnalysis()
souffle::ast::analysis::SCCGraphAnalysis::SCCGraphAnalysis () inline
Definition at line 46 of file SCCGraph.h.
References run().
 : Analysis(name) {}
Member Function Documentation
getExternalNonOutputPredecessorRelations()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getExternalNonOutputPredecessorRelations (const size_t scc) const inline
Get all external non-output predecessor relations of a given SCC.
Definition at line 115 of file SCCGraph.h.
References getInternalRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), ioType, souffle::ast::analysis::IOTypeAnalysis::isOutput(), precedenceGraph, relation, and relationToScc.
{
         std::set<const Relation*> externNonOutPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc && !ioType->isOutput(predecessor)) {
                     externNonOutPreds.insert(predecessor);
                 }
             }
         }
         return externNonOutPreds;
     }
getExternalOutputPredecessorRelations()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getExternalOutputPredecessorRelations (const size_t scc) const inline
Get all external output predecessor relations of a given SCC.
Definition at line 102 of file SCCGraph.h.
References getInternalRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), ioType, souffle::ast::analysis::IOTypeAnalysis::isOutput(), precedenceGraph, relation, and relationToScc.
{
         std::set<const Relation*> externOutPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc && ioType->isOutput(predecessor)) {
                     externOutPreds.insert(predecessor);
                 }
             }
         }
         return externOutPreds;
     }
getExternalPredecessorRelations()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getExternalPredecessorRelations (const size_t scc) const inline
Get all external predecessor relations of a given SCC.
Definition at line 128 of file SCCGraph.h.
References getInternalRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, relation, and relationToScc.
{
         std::set<const Relation*> externPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc) {
                     externPreds.insert(predecessor);
                 }
             }
         }
         return externPreds;
     }
getInternalInputRelations()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getInternalInputRelations (const size_t scc) const inline
Get all internal input relations of a given SCC.
Definition at line 182 of file SCCGraph.h.
References getInternalRelations(), ioType, souffle::ast::analysis::IOTypeAnalysis::isInput(), and relation.
{
         std::set<const Relation*> internIns;
         for (const auto& relation : getInternalRelations(scc)) {
             if (ioType->isInput(relation)) {
                 internIns.insert(relation);
             }
         }
         return internIns;
     }
getInternalNonOutputRelationsWithExternalSuccessors()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getInternalNonOutputRelationsWithExternalSuccessors (const size_t scc) const inline
Get all internal non-output relations of a given SCC with external successors.
Definition at line 166 of file SCCGraph.h.
References getInternalRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), ioType, souffle::ast::analysis::IOTypeAnalysis::isOutput(), precedenceGraph, relation, and relationToScc.
{
         std::set<const Relation*> internNonOutsWithExternSuccs;
         for (const auto& relation : getInternalRelations(scc)) {
             if (!ioType->isOutput(relation)) {
                 for (const auto& successor : precedenceGraph->graph().successors(relation)) {
                     if (relationToScc.at(successor) != scc) {
                         internNonOutsWithExternSuccs.insert(relation);
                         break;
                     }
                 }
             }
         }
         return internNonOutsWithExternSuccs;
     }
getInternalOutputRelations()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getInternalOutputRelations (const size_t scc) const inline
Get all internal output relations of a given SCC.
Definition at line 141 of file SCCGraph.h.
References getInternalRelations(), ioType, souffle::ast::analysis::IOTypeAnalysis::isOutput(), and relation.
{
         std::set<const Relation*> internOuts;
         for (const auto& relation : getInternalRelations(scc)) {
             if (ioType->isOutput(relation)) {
                 internOuts.insert(relation);
             }
         }
         return internOuts;
     }
getInternalRelations()
const std::set<const Relation*>& souffle::ast::analysis::SCCGraphAnalysis::getInternalRelations (const size_t scc) const inline
Get all internal relations of a given SCC.
Definition at line 97 of file SCCGraph.h.
References sccToRelation.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getExternalPredecessorRelations(), getInternalInputRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalOutputRelations(), getInternalRelationsWithExternalSuccessors(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::print(), print(), and souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
         return sccToRelation.at(scc);
     }
getInternalRelationsWithExternalSuccessors()
std::set<const Relation*> souffle::ast::analysis::SCCGraphAnalysis::getInternalRelationsWithExternalSuccessors (const size_t scc) const inline
Get all internal relations of a given SCC with external successors.
Definition at line 152 of file SCCGraph.h.
References getInternalRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, relation, and relationToScc.
{
         std::set<const Relation*> internsWithExternSuccs;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& successor : precedenceGraph->graph().successors(relation)) {
                 if (relationToScc.at(successor) != scc) {
                     internsWithExternSuccs.insert(relation);
                     break;
                 }
             }
         }
         return internsWithExternSuccs;
     }
getNumberOfSCCs()
size_t souffle::ast::analysis::SCCGraphAnalysis::getNumberOfSCCs () const inline
Get the number of SCCs in the graph.
Definition at line 51 of file SCCGraph.h.
References sccToRelation.
Referenced by print(), and souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::run().
{
         return sccToRelation.size();
     }
getPredecessorSCCs() [1/2]
const std::set<size_t>& souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs (const size_t scc) const inline
Get all predecessor SCCs of a given SCC.
Definition at line 66 of file SCCGraph.h.
References predecessors.
Referenced by souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::computeTopologicalOrdering(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::print(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::run(), and souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::topologicalOrderingCost().
{
         return predecessors.at(scc);
     }
getPredecessorSCCs() [2/2]
std::set<size_t> souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs (const Relation * relation) const inline
Get all SCCs containing a predecessor of a given relation.
Definition at line 84 of file SCCGraph.h.
References souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, and relationToScc.
{
         std::set<size_t> predecessorSccs;
         const auto scc = relationToScc.at(relation);
         for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
             const auto predecessorScc = relationToScc.at(predecessor);
             if (predecessorScc != scc) {
                 predecessorSccs.insert(predecessorScc);
             }
         }
         return predecessorSccs;
     }
getSCC()
size_t souffle::ast::analysis::SCCGraphAnalysis::getSCC (const Relation * rel) const inline
Get the SCC of the given relation.
Definition at line 56 of file SCCGraph.h.
References relationToScc.
Referenced by souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
         return relationToScc.at(rel);
     }
getSuccessorSCCs() [1/2]
const std::set<size_t>& souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs (const size_t scc) const inline
Get all successor SCCs of a given SCC.
Definition at line 61 of file SCCGraph.h.
References successors.
Referenced by souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::computeTopologicalOrdering(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::print(), print(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::run(), and souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::topologicalOrderingCost().
{
         return successors.at(scc);
     }
getSuccessorSCCs() [2/2]
std::set<size_t> souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs (const Relation * relation) const inline
Get all SCCs containing a successor of a given relation.
Definition at line 71 of file SCCGraph.h.
References souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, and relationToScc.
{
         std::set<size_t> successorSccs;
         const auto scc = relationToScc.at(relation);
         for (const auto& successor : precedenceGraph->graph().successors(relation)) {
             const auto successorScc = relationToScc.at(successor);
             if (successorScc != scc) {
                 successorSccs.insert(successorScc);
             }
         }
         return successorSccs;
     }
isRecursive()
bool souffle::ast::analysis::SCCGraphAnalysis::isRecursive (const size_t scc) const inline
Return if the given SCC is recursive.
Definition at line 193 of file SCCGraph.h.
References souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, print(), and sccToRelation.
Referenced by souffle::ast::analysis::RelationScheduleAnalysis::run(), and souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
         const std::set<const Relation*>& sccRelations = sccToRelation.at(scc);
         if (sccRelations.size() == 1) {
             const Relation* singleRelation = *sccRelations.begin();
             if (precedenceGraph->graph().predecessors(singleRelation).count(singleRelation) == 0u) {
                 return false;
             }
         }
         return true;
     }
print()
void souffle::ast::analysis::SCCGraphAnalysis::print (std::ostream & os) const override virtual
Print the SCC graph.
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 116 of file SCCGraph.cpp.
References souffle::Global::config(), getInternalRelations(), souffle::ast::analysis::Analysis::getName(), getNumberOfSCCs(), souffle::ast::Relation::getQualifiedName(), getSuccessorSCCs(), souffle::join(), name, souffle::printHTMLGraph(), and souffle::profile::ss.
Referenced by isRecursive().
{
     const std::string& name = Global::config().get("name");
     std::stringstream ss;
     /* Print SCC graph */
     ss << "digraph {" << std::endl;
     /* Print nodes of SCC graph */
     for (size_t scc = 0; scc < getNumberOfSCCs(); scc++) {
         ss << "\t" << name << "_" << scc << "[label = \"";
         ss << join(getInternalRelations(scc), ",\\n",
                 [](std::ostream& out, const Relation* rel) { out << rel->getQualifiedName(); });
         ss << "\" ];" << std::endl;
     }
     for (size_t scc = 0; scc < getNumberOfSCCs(); scc++) {
         for (auto succ : getSuccessorSCCs(scc)) {
             ss << "\t" << name << "_" << scc << " -> " << name << "_" << succ << ";" << std::endl;
         }
     }
     ss << "}";
     printHTMLGraph(os, ss.str(), getName());
 }
run()
void souffle::ast::analysis::SCCGraphAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 36 of file SCCGraph.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), ioType, precedenceGraph, predecessors, relation, relations, relationToScc, S, sccToRelation, scR(), and successors.
Referenced by SCCGraphAnalysis().
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraphAnalysis>();
     ioType = translationUnit.getAnalysis<IOTypeAnalysis>();
     sccToRelation.clear();
     relationToScc.clear();
     predecessors.clear();
     successors.clear();
     /* Compute SCC */
     Program& program = translationUnit.getProgram();
     std::vector<Relation*> relations = program.getRelations();
     size_t counter = 0;
     size_t numSCCs = 0;
     std::stack<const Relation*> S;
     std::stack<const Relation*> P;
     std::map<const Relation*, size_t> preOrder;  // Pre-order number of a node (for Gabow's Algo)
     for (const Relation* relation : relations) {
         relationToScc[relation] = preOrder[relation] = (size_t)-1;
     }
     for (const Relation* relation : relations) {
         if (preOrder[relation] == (size_t)-1) {
             scR(relation, preOrder, counter, S, P, numSCCs);
         }
     }
     /* Build SCC graph */
     successors.resize(numSCCs);
     predecessors.resize(numSCCs);
     for (const Relation* u : relations) {
         for (const Relation* v : precedenceGraph->graph().predecessors(u)) {
             auto scc_u = relationToScc[u];
             auto scc_v = relationToScc[v];
             assert(scc_u < numSCCs && "Wrong range");
             assert(scc_v < numSCCs && "Wrong range");
             if (scc_u != scc_v) {
                 predecessors[scc_u].insert(scc_v);
                 successors[scc_v].insert(scc_u);
             }
         }
     }
     /* Store the relations for each SCC */
     sccToRelation.resize(numSCCs);
     for (const Relation* relation : relations) {
         sccToRelation[relationToScc[relation]].insert(relation);
     }
 }
scR()
void souffle::ast::analysis::SCCGraphAnalysis::scR (const Relation * relation, std::map< const Relation *, size_t > & preOrder, size_t & counter, std::stack< const Relation *> & S, std::stack< const Relation *> & P, size_t & numSCCs) private
Recursive scR method for computing SCC.
Definition at line 87 of file SCCGraph.cpp.
References souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, and relationToScc.
Referenced by run().
{
     preOrder[w] = counter++;
     S.push(w);
     P.push(w);
     for (const Relation* t : precedenceGraph->graph().predecessors(w)) {
         if (preOrder[t] == (size_t)-1) {
             scR(t, preOrder, counter, S, P, numSCCs);
         } else if (relationToScc[t] == (size_t)-1) {
             while (preOrder[P.top()] > preOrder[t]) {
                 P.pop();
             }
         }
     }
     if (P.top() == w) {
         P.pop();
     } else {
         return;
     }
     const Relation* v;
     do {
         v = S.top();
         S.pop();
         relationToScc[v] = numSCCs;
     } while (v != w);
     numSCCs++;
 }
Field Documentation
ioType
IOTypeAnalysis* souffle::ast::analysis::SCCGraphAnalysis::ioType = nullptr private
Definition at line 226 of file SCCGraph.h.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getInternalInputRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalOutputRelations(), and run().
name
constexpr const char* souffle::ast::analysis::SCCGraphAnalysis::name = "scc-graph" static
Definition at line 44 of file SCCGraph.h.
Referenced by print().
precedenceGraph
PrecedenceGraphAnalysis* souffle::ast::analysis::SCCGraphAnalysis::precedenceGraph = nullptr private
Definition at line 208 of file SCCGraph.h.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getExternalPredecessorRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalRelationsWithExternalSuccessors(), getPredecessorSCCs(), getSuccessorSCCs(), isRecursive(), run(), and scR().
predecessors
std::vector<std::set<size_t> > souffle::ast::analysis::SCCGraphAnalysis::predecessors private
Predecessor set for the SCC graph.
Definition at line 217 of file SCCGraph.h.
Referenced by getPredecessorSCCs(), and run().
relationToScc
std::map<const Relation*, size_t> souffle::ast::analysis::SCCGraphAnalysis::relationToScc private
Map from node number to SCC number.
Definition at line 211 of file SCCGraph.h.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getExternalPredecessorRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalRelationsWithExternalSuccessors(), getPredecessorSCCs(), getSCC(), getSuccessorSCCs(), run(), and scR().
sccToRelation
std::vector<std::set<const Relation*> > souffle::ast::analysis::SCCGraphAnalysis::sccToRelation private
Relations contained in a SCC.
Definition at line 220 of file SCCGraph.h.
Referenced by getInternalRelations(), getNumberOfSCCs(), isRecursive(), and run().
successors
std::vector<std::set<size_t> > souffle::ast::analysis::SCCGraphAnalysis::successors private
Adjacency lists for the SCC graph.
Definition at line 214 of file SCCGraph.h.
Referenced by getSuccessorSCCs(), and run().
The documentation for this class was generated from the following files:
ast/analysis/SCCGraph.h
ast/analysis/SCCGraph.cpp