souffle: souffle::ast::IntrinsicFunctor Class Reference
souffle::ast::IntrinsicFunctor Class Reference
Intrinsic Functor class for functors are in-built.
#include <IntrinsicFunctor.h>
Public Member Functions
IntrinsicFunctor * clone () const override
Create clone.
TypeAttribute getArgType (const size_t arg) const override
Get type of the functor argument.
const std::string & getFunction () const
Get function.
const IntrinsicFunctorInfo * getFunctionInfo () const
Get function information.
TypeAttribute getReturnType () const override
Get the return type of the functor.
template<typename... Operands>
IntrinsicFunctor (std::string op, Operands &&... operands)
template<typename... Operands>
IntrinsicFunctor (SrcLocation loc, std::string op, Operands &&... operands)
IntrinsicFunctor (std::string op, VecOwn< Argument > args, SrcLocation loc={})
void setFunction (std::string functor)
Set function.
void setFunctionInfo (const IntrinsicFunctorInfo &info)
Set function information.
Public Member Functions inherited from souffle::ast::Term
void addArgument (Own< Argument > arg)
Add argument to argument list.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Argument * > getArguments () const
Get arguments.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
IntrinsicFunctor (std::string op, const IntrinsicFunctorInfo *info, VecOwn< Argument > args, SrcLocation loc={})
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::ast::Term
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
template<typename... Operands>
Term (Operands &&... operands)
template<typename... Operands>
Term (SrcLocation loc, Operands &&... operands)
Term (VecOwn< Argument > operands, SrcLocation loc={})
Protected Attributes
std::string function
Function.
const IntrinsicFunctorInfo * info = nullptr
Functor information.
Protected Attributes inherited from souffle::ast::Term
VecOwn< Argument > args
Arguments.
Detailed Description
Intrinsic Functor class for functors are in-built.
Definition at line 40 of file IntrinsicFunctor.h.
Constructor & Destructor Documentation
IntrinsicFunctor() [1/4]
template<typename... Operands> souffle::ast::IntrinsicFunctor::IntrinsicFunctor (std::string op, Operands &&... operands) inline
Definition at line 43 of file IntrinsicFunctor.h.
Referenced by clone().
             : Functor(std::forward<Operands>(operands)...), function(std::move(op)) {}
IntrinsicFunctor() [2/4]
template<typename... Operands> souffle::ast::IntrinsicFunctor::IntrinsicFunctor (SrcLocation loc, std::string op, Operands &&... operands) inline
Definition at line 47 of file IntrinsicFunctor.h.
             : Functor(std::move(loc), std::forward<Operands>(operands)...), function(std::move(op)) {}
IntrinsicFunctor() [3/4]
souffle::ast::IntrinsicFunctor::IntrinsicFunctor (std::string op, VecOwn< Argument > args, SrcLocation loc = {}) inline
Definition at line 50 of file IntrinsicFunctor.h.
                                                                             {})
             : Functor(std::move(args), std::move(loc)), function(std::move(op)) {}
IntrinsicFunctor() [4/4]
souffle::ast::IntrinsicFunctor::IntrinsicFunctor (std::string op, const IntrinsicFunctorInfo * info, VecOwn< Argument > args, SrcLocation loc = {}) inline protected
Definition at line 90 of file IntrinsicFunctor.h.
References info, and souffle::IntrinsicFunctorInfo::symbol.
                                                                                                      {})
             : Functor(std::move(args), std::move(loc)), function(std::move(op)), info(info) {
         assert((!info || info->symbol == function) && "functor info must match symbol");
     }
Member Function Documentation
clone()
IntrinsicFunctor* souffle::ast::IntrinsicFunctor::clone () const inline override virtual
Create clone.
Implements souffle::ast::Functor.
Definition at line 85 of file IntrinsicFunctor.h.
References souffle::clone(), souffle::ast::Node::getSrcLoc(), info, and IntrinsicFunctor().
{
         return new IntrinsicFunctor(function, info, souffle::clone(args), getSrcLoc());
     }
equal()
bool souffle::ast::IntrinsicFunctor::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 105 of file IntrinsicFunctor.h.
References souffle::ast::Term::equal(), and function.
{
         const auto& other = static_cast<const IntrinsicFunctor&>(node);
         return function == other.function && info == other.info && Functor::equal(node);
     }
getArgType()
TypeAttribute souffle::ast::IntrinsicFunctor::getArgType (const size_t arg) const inline override virtual
Get type of the functor argument.
Implements souffle::ast::Functor.
Definition at line 80 of file IntrinsicFunctor.h.
References info, souffle::IntrinsicFunctorInfo::params, and souffle::IntrinsicFunctorInfo::variadic.
{
         assert(info && "functor info not yet available");
         return info->params.at(info->variadic ? 0 : arg);
     }
getFunction()
const std::string& souffle::ast::IntrinsicFunctor::getFunction () const inline
Get function.
Definition at line 54 of file IntrinsicFunctor.h.
Referenced by souffle::ast::validOverloads(), and souffle::ast::transform::TypeChecker::visitIntrinsicFunctor().
{
         return function;
     }
getFunctionInfo()
const IntrinsicFunctorInfo* souffle::ast::IntrinsicFunctor::getFunctionInfo () const inline
Get function information.
Definition at line 64 of file IntrinsicFunctor.h.
References info.
Referenced by souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::isFact(), souffle::AstToRamTranslator::translateValue(), and souffle::ast::transform::TypeChecker::visitIntrinsicFunctor().
{
         return info;
     }
getReturnType()
TypeAttribute souffle::ast::IntrinsicFunctor::getReturnType () const inline override virtual
Get the return type of the functor.
Implements souffle::ast::Functor.
Definition at line 74 of file IntrinsicFunctor.h.
References info, and souffle::IntrinsicFunctorInfo::result.
{
         assert(info && "functor info not yet available");
         return info->result;
     }
print()
void souffle::ast::IntrinsicFunctor::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 96 of file IntrinsicFunctor.h.
References souffle::isInfixFunctorOp(), and souffle::join().
{
         if (isInfixFunctorOp(function)) {
             os << "(" << join(args, function) << ")";
         } else {
             os << function;
             os << "(" << join(args) << ")";
         }
     }
setFunction()
void souffle::ast::IntrinsicFunctor::setFunction (std::string functor) inline
Set function.
Definition at line 59 of file IntrinsicFunctor.h.
{
         function = std::move(functor);
     }
setFunctionInfo()
void souffle::ast::IntrinsicFunctor::setFunctionInfo (const IntrinsicFunctorInfo & info) inline
Set function information.
Definition at line 69 of file IntrinsicFunctor.h.
References info.
{
         this->info = &info;
     }
Field Documentation
function
std::string souffle::ast::IntrinsicFunctor::function protected
Function.
Definition at line 111 of file IntrinsicFunctor.h.
Referenced by equal().
info
const IntrinsicFunctorInfo* souffle::ast::IntrinsicFunctor::info = nullptr protected
Functor information.
Definition at line 114 of file IntrinsicFunctor.h.
Referenced by clone(), getArgType(), getFunctionInfo(), getReturnType(), IntrinsicFunctor(), and setFunctionInfo().
The documentation for this class was generated from the following file:
ast/IntrinsicFunctor.h