souffle: souffle::ram::Loop Class Reference
souffle::ram::Loop Class Reference
Execute statement until statement terminates loop via an exit statement.
#include <Loop.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Loop * clone () const override
Create a clone (i.e.
const Statement & getBody () const
Get loop body.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Loop (Own< Statement > b)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Statement > body
loop body
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Execute statement until statement terminates loop via an exit statement.
For example:
LOOP
  PARALLEL
    ...
  END PARALLEL
END LOOP
Definition at line 44 of file Loop.h.
Constructor & Destructor Documentation
Loop()
souffle::ram::Loop::Loop (Own< Statement > b) inline
Definition at line 46 of file Loop.h.
References body.
Referenced by clone().
                            : body(std::move(b)) {
         assert(body != nullptr && "Loop body is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::Loop::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 63 of file Loop.h.
References body, and souffle::map().
{
         body = map(std::move(body));
     }
clone()
Loop* souffle::ram::Loop::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 59 of file Loop.h.
References body, souffle::clone(), and Loop().
Referenced by souffle::ram::test::TEST().
{
         return new Loop(souffle::clone(body));
     }
equal()
bool souffle::ram::Loop::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 74 of file Loop.h.
References body, and souffle::equal_ptr().
{
         const auto& other = static_cast<const Loop&>(node);
         return equal_ptr(body, other.body);
     }
getBody()
const Statement& souffle::ram::Loop::getBody () const inline
Get loop body.
Definition at line 51 of file Loop.h.
References body.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return *body;
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Loop::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 55 of file Loop.h.
References body.
{
         return {body.get()};
     }
print()
void souffle::ram::Loop::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 68 of file Loop.h.
References body, souffle::ram::Statement::print(), and souffle::times().
{
         os << times(" ", tabpos) << "LOOP" << std::endl;
         Statement::print(body.get(), os, tabpos + 1);
         os << times(" ", tabpos) << "END LOOP" << std::endl;
     }
Field Documentation
body
Own<Statement> souffle::ram::Loop::body protected
loop body
Definition at line 80 of file Loop.h.
Referenced by apply(), clone(), equal(), getBody(), getChildNodes(), Loop(), and print().
The documentation for this class was generated from the following file:
ram/Loop.h