souffle: souffle::ast::analysis::TypeEnvironment Class Reference
souffle::ast::analysis::TypeEnvironment Class Reference
A type environment is a set of types.
#include <TypeSystem.h>
Public Member Functions
template<typename T , typename... Args>
T & createType (const QualifiedName &name, Args &&... args)
create type in this environment
const TypeSet & getConstantNumericTypes () const
const Type & getConstantType (TypeAttribute type) const
const TypeSet & getConstantTypes () const
const TypeSet & getPrimitiveTypes () const
const Type & getType (const QualifiedName &) const
const Type & getType (const ast::Type &) const
TypeSet getTypes () const
bool isPrimitiveType (const QualifiedName &identifier) const
bool isPrimitiveType (const Type &type) const
bool isType (const QualifiedName &) const
bool isType (const Type &type) const
void print (std::ostream &out) const
TypeEnvironment ()=default
TypeEnvironment (const TypeEnvironment &)=delete
virtual ~TypeEnvironment ()=default
Private Member Functions
TypeSet initializeConstantTypes ()
TypeSet initializePrimitiveTypes ()
Private Attributes
const TypeSet constantNumericTypes
const TypeSet constantTypes = initializeConstantTypes()
const TypeSet primitiveTypes = initializePrimitiveTypes()
std::map< QualifiedName, Own< Type > > types
The list of covered types.
Friends
std::ostream & operator<< (std::ostream &out, const TypeEnvironment &environment)
Detailed Description
A type environment is a set of types.
It's main purpose is to provide an enumeration of all all types within a given program. Additionally, it manages the life cycle of type instances.
Definition at line 418 of file TypeSystem.h.
Constructor & Destructor Documentation
TypeEnvironment() [1/2]
souffle::ast::analysis::TypeEnvironment::TypeEnvironment () default
TypeEnvironment() [2/2]
souffle::ast::analysis::TypeEnvironment::TypeEnvironment (const TypeEnvironment &) delete
~TypeEnvironment()
virtual souffle::ast::analysis::TypeEnvironment::~TypeEnvironment () virtual default
Member Function Documentation
createType()
template<typename T , typename... Args> T& souffle::ast::analysis::TypeEnvironment::createType (const QualifiedName & name, Args &&... args) inline
create type in this environment
Definition at line 428 of file TypeSystem.h.
References souffle::ast::analysis::Type::name, and types.
Referenced by souffle::ast::test::TEST().
{
         assert(types.find(name) == types.end() && "Error: registering present type!");
         auto* newType = new T(*this, name, std::forward<Args>(args)...);
         types[name] = Own<Type>(newType);
         return *newType;
     }
getConstantNumericTypes()
const TypeSet& souffle::ast::analysis::TypeEnvironment::getConstantNumericTypes () const inline
Definition at line 473 of file TypeSystem.h.
References souffle::ast::analysis::Type::print().
Referenced by souffle::ast::analysis::TypeConstraintsAnalysis::visitAggregator().
{
         return constantNumericTypes;
     }
getConstantType()
const Type& souffle::ast::analysis::TypeEnvironment::getConstantType (TypeAttribute type) const inline
Definition at line 441 of file TypeSystem.h.
References souffle::ADT, souffle::fatal(), souffle::Float, souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by souffle::ast::analysis::isOfKind(), souffle::ast::analysis::TypeConstraintsAnalysis::visitAggregator(), souffle::ast::analysis::TypeConstraintsAnalysis::visitCounter(), souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor(), souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitStringConstant().
{
         switch (type) {
             case TypeAttribute::Signed: return getType("__numberConstant");
             case TypeAttribute::Unsigned: return getType("__unsignedConstant");
             case TypeAttribute::Float: return getType("__floatConstant");
             case TypeAttribute::Symbol: return getType("__symbolConstant");
             case TypeAttribute::Record: break;
             case TypeAttribute::ADT: break;
         }
         fatal("There is no constant record type");
     }
getConstantTypes()
const TypeSet& souffle::ast::analysis::TypeEnvironment::getConstantTypes () const inline
Definition at line 465 of file TypeSystem.h.
Referenced by souffle::ast::analysis::TypeConstraintsAnalysis::visitSink().
{
         return constantTypes;
     }
getPrimitiveTypes()
const TypeSet& souffle::ast::analysis::TypeEnvironment::getPrimitiveTypes () const inline
Definition at line 469 of file TypeSystem.h.
{
         return primitiveTypes;
     }
getType() [1/2]
const Type & souffle::ast::analysis::TypeEnvironment::getType (const QualifiedName & ident) const
Definition at line 75 of file TypeSystem.cpp.
References types.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkSubsetType(), souffle::ast::analysis::TypeConstraintsAnalysis::iterateOverAtom(), souffle::ast::analysis::SumTypeBranchesAnalysis::run(), souffle::ast::test::TEST(), souffle::ast::transform::TypeChecker::visitAtom(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitTypeCast().
{
     return *types.at(ident);
 }
getType() [2/2]
const Type & souffle::ast::analysis::TypeEnvironment::getType (const ast::Type & astTypeDeclaration) const
Definition at line 79 of file TypeSystem.cpp.
{
     return getType(astTypeDeclaration.getQualifiedName());
 }
getTypes()
TypeSet souffle::ast::analysis::TypeEnvironment::getTypes () const inline
Definition at line 484 of file TypeSystem.h.
References types.
Referenced by souffle::ast::analysis::haveCommonSupertype().
{
         TypeSet types;
         for (auto& type : types) {
             types.insert(type);
         }
         return types;
     }
initializeConstantTypes()
TypeSet souffle::ast::analysis::TypeEnvironment::initializeConstantTypes () private
Definition at line 43 of file TypeSystem.cpp.
{
     auto& signedConstant = createType<ConstantType>("__numberConstant");
     auto& floatConstant = createType<ConstantType>("__floatConstant");
     auto& symbolConstant = createType<ConstantType>("__symbolConstant");
     auto& unsignedConstant = createType<ConstantType>("__unsignedConstant");
     return TypeSet(signedConstant, floatConstant, symbolConstant, unsignedConstant);
 }
initializePrimitiveTypes()
TypeSet souffle::ast::analysis::TypeEnvironment::initializePrimitiveTypes () private
Definition at line 52 of file TypeSystem.cpp.
References CREATE_PRIMITIVE.
{
 #define CREATE_PRIMITIVE(TYPE)                    \
     auto& TYPE##Type = createType<PrimitiveType>( \
             #TYPE, static_cast<const ConstantType&>(getType("__" #TYPE "Constant")));
     CREATE_PRIMITIVE(number);
     CREATE_PRIMITIVE(float);
     CREATE_PRIMITIVE(symbol);
     CREATE_PRIMITIVE(unsigned);
     return TypeSet(numberType, floatType, symbolType, unsignedType);
 #undef CREATE_PRIMITIVE
 }
isPrimitiveType() [1/2]
bool souffle::ast::analysis::TypeEnvironment::isPrimitiveType (const QualifiedName & identifier) const inline
Definition at line 454 of file TypeSystem.h.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration(), souffle::ast::transform::SemanticCheckerImpl::checkTypesDeclarations(), and souffle::ast::transform::SemanticCheckerImpl::checkUnionType().
{
         if (isType(identifier)) {
             return isPrimitiveType(getType(identifier));
         }
         return false;
     }
isPrimitiveType() [2/2]
bool souffle::ast::analysis::TypeEnvironment::isPrimitiveType (const Type & type) const inline
Definition at line 461 of file TypeSystem.h.
{
         return primitiveTypes.contains(type);
     }
isType() [1/2]
bool souffle::ast::analysis::TypeEnvironment::isType (const QualifiedName & ident) const
Definition at line 67 of file TypeSystem.cpp.
References types.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkADT(), souffle::ast::transform::SemanticCheckerImpl::checkRecordType(), souffle::ast::transform::SemanticCheckerImpl::checkSubsetType(), souffle::ast::analysis::TypeConstraintsAnalysis::iterateOverAtom(), souffle::ast::analysis::SumTypeBranchesAnalysis::run(), souffle::ast::transform::TypeChecker::visitAtom(), souffle::ast::transform::TypeChecker::visitTypeCast(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitTypeCast().
{
     return types.find(ident) != types.end();
 }
isType() [2/2]
bool souffle::ast::analysis::TypeEnvironment::isType (const Type & type) const
Definition at line 71 of file TypeSystem.cpp.
References souffle::ast::analysis::Type::getTypeEnvironment().
{
     return this == &type.getTypeEnvironment();
 }
print()
void souffle::ast::analysis::TypeEnvironment::print (std::ostream & out) const
Definition at line 262 of file TypeSystem.cpp.
References types.
{
     out << "Types:\n";
     for (const auto& cur : types) {
         out << "\t" << *cur.second << "\n";
     }
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const TypeEnvironment & environment) friend
Definition at line 479 of file TypeSystem.h.
{
         environment.print(out);
         return out;
     }
Field Documentation
constantNumericTypes
const TypeSet souffle::ast::analysis::TypeEnvironment::constantNumericTypes private
Initial value:
=
            TypeSet(getType("__numberConstant"), getType("__unsignedConstant"), getType("__floatConstant"))
Definition at line 500 of file TypeSystem.h.
constantTypes
const TypeSet souffle::ast::analysis::TypeEnvironment::constantTypes = initializeConstantTypes() private
Definition at line 499 of file TypeSystem.h.
primitiveTypes
const TypeSet souffle::ast::analysis::TypeEnvironment::primitiveTypes = initializePrimitiveTypes() private
Definition at line 503 of file TypeSystem.h.
types
std::map<QualifiedName, Own<Type> > souffle::ast::analysis::TypeEnvironment::types private
The list of covered types.
Definition at line 497 of file TypeSystem.h.
The documentation for this class was generated from the following files:
ast/analysis/TypeSystem.h
ast/analysis/TypeSystem.cpp