souffle: souffle::ast::transform::MetaTransformer Class Reference
souffle::ast::transform::MetaTransformer Class Reference abstract
Transformer that coordinates other sub-transformations.
#include <Meta.h>
Public Member Functions
bool applySubtransformer (TranslationUnit &translationUnit, Transformer *transformer)
MetaTransformer * clone () const override=0
virtual void disableTransformers (const std::set< std::string > &transforms)=0
virtual std::vector< Transformer * > getSubtransformers () const =0
virtual void setDebugReport ()=0
virtual void setVerbosity (bool verbose)=0
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual std::string getName () const =0
virtual ~Transformer ()=default
Protected Attributes
bool verbose = false
Detailed Description
Transformer that coordinates other sub-transformations.
Definition at line 30 of file Meta.h.
Member Function Documentation
applySubtransformer()
bool souffle::ast::transform::MetaTransformer::applySubtransformer (TranslationUnit & translationUnit, Transformer * transformer)
Definition at line 24 of file Meta.cpp.
References souffle::ast::transform::Transformer::apply(), souffle::test::count(), souffle::ast::transform::Transformer::getName(), souffle::now(), and verbose.
Referenced by souffle::ast::transform::DebugReporter::transform(), souffle::ast::transform::FixpointTransformer::transform(), souffle::ast::transform::WhileTransformer::transform(), souffle::ast::transform::ConditionalTransformer::transform(), and souffle::ast::transform::PipelineTransformer::transform().
{
     auto start = std::chrono::high_resolution_clock::now();
     bool changed = transformer->apply(translationUnit);
     auto end = std::chrono::high_resolution_clock::now();
     if (verbose && (!isA<MetaTransformer>(transformer))) {
         std::string changedString = changed ? "changed" : "unchanged";
         std::cout << transformer->getName() << " time: " << std::chrono::duration<double>(end - start).count()
                   << "sec [" << changedString << "]" << std::endl;
     }
     return changed;
 }
clone()
MetaTransformer* souffle::ast::transform::MetaTransformer::clone () const override pure virtual
Implements souffle::ast::transform::Transformer.
Implemented in souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer, souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::DebugReporter, souffle::ast::transform::MagicSetTransformer, and souffle::ast::transform::NullTransformer.
disableTransformers()
virtual void souffle::ast::transform::MetaTransformer::disableTransformers (const std::set< std::string > & transforms) pure virtual
Implemented in souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::DebugReporter, and souffle::ast::transform::NullTransformer.
getSubtransformers()
virtual std::vector<Transformer*> souffle::ast::transform::MetaTransformer::getSubtransformers () const pure virtual
Implemented in souffle::ast::transform::PipelineTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::DebugReporter, and souffle::ast::transform::NullTransformer.
setDebugReport()
virtual void souffle::ast::transform::MetaTransformer::setDebugReport () pure virtual
Implemented in souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::DebugReporter, souffle::ast::transform::NullTransformer, and souffle::ast::transform::FixpointTransformer.
setVerbosity()
virtual void souffle::ast::transform::MetaTransformer::setVerbosity (bool verbose) pure virtual
Implemented in souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::DebugReporter, and souffle::ast::transform::NullTransformer.
Field Documentation
verbose
bool souffle::ast::transform::MetaTransformer::verbose = false protected
Definition at line 32 of file Meta.h.
Referenced by applySubtransformer(), souffle::ast::transform::DebugReporter::setVerbosity(), souffle::ast::transform::FixpointTransformer::setVerbosity(), souffle::ast::transform::WhileTransformer::setVerbosity(), souffle::ast::transform::ConditionalTransformer::setVerbosity(), and souffle::ast::transform::PipelineTransformer::setVerbosity().
The documentation for this class was generated from the following files:
ast/transform/Meta.h
ast/transform/Meta.cpp