souffle: souffle::ram::IntrinsicOperator Class Reference
souffle::ram::IntrinsicOperator Class Reference
Operator that represents an intrinsic (built-in) functor.
#include <IntrinsicOperator.h>
Public Member Functions
IntrinsicOperator * clone () const override
Create a clone (i.e.
FunctorOp getOperator () const
Get operator symbol.
template<typename... Args>
IntrinsicOperator (FunctorOp op, Args... args)
IntrinsicOperator (FunctorOp op, VecOwn< Expression > args)
Public Member Functions inherited from souffle::ram::AbstractOperator
AbstractOperator (VecOwn< Expression > args)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Expression * > getArguments () const
Get argument values.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const FunctorOp operation
Operation symbol.
Protected Attributes inherited from souffle::ram::AbstractOperator
VecOwn< Expression > arguments
Arguments of user defined operator.
Detailed Description
Operator that represents an intrinsic (built-in) functor.
Definition at line 36 of file IntrinsicOperator.h.
Constructor & Destructor Documentation
IntrinsicOperator() [1/2]
template<typename... Args> souffle::ram::IntrinsicOperator::IntrinsicOperator (FunctorOp op, Args... args) inline
Definition at line 39 of file IntrinsicOperator.h.
Referenced by clone().
 : AbstractOperator({std::move(args)...}), operation(op) {}
IntrinsicOperator() [2/2]
souffle::ram::IntrinsicOperator::IntrinsicOperator (FunctorOp op, VecOwn< Expression > args) inline
Definition at line 41 of file IntrinsicOperator.h.
             : AbstractOperator(std::move(args)), operation(op) {}
Member Function Documentation
clone()
IntrinsicOperator* souffle::ram::IntrinsicOperator::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Expression.
Definition at line 49 of file IntrinsicOperator.h.
References souffle::ram::AbstractOperator::arguments, IntrinsicOperator(), and operation.
Referenced by souffle::ram::test::TEST().
{
         VecOwn<Expression> argsCopy;
         for (auto& arg : arguments) {
             argsCopy.emplace_back(arg->clone());
         }
         return new IntrinsicOperator(operation, std::move(argsCopy));
     }
equal()
bool souffle::ram::IntrinsicOperator::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::AbstractOperator.
Definition at line 66 of file IntrinsicOperator.h.
References souffle::ram::AbstractOperator::equal(), and operation.
{
         const auto& other = static_cast<const IntrinsicOperator&>(node);
         return AbstractOperator::equal(node) && operation == other.operation;
     }
getOperator()
FunctorOp souffle::ram::IntrinsicOperator::getOperator () const inline
Get operator symbol.
Definition at line 45 of file IntrinsicOperator.h.
References operation.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return operation;
     }
print()
void souffle::ram::IntrinsicOperator::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 58 of file IntrinsicOperator.h.
References souffle::ram::AbstractOperator::arguments, tinyformat::format(), souffle::isInfixFunctorOp(), souffle::join(), and operation.
{
         if (isInfixFunctorOp(operation)) {
             os << "(" << join(arguments, tfm::format("%s", operation)) << ")";
         } else {
             os << operation << "(" << join(arguments) << ")";
         }
     }
Field Documentation
operation
const FunctorOp souffle::ram::IntrinsicOperator::operation protected
Operation symbol.
Definition at line 72 of file IntrinsicOperator.h.
Referenced by clone(), equal(), getOperator(), and print().
The documentation for this class was generated from the following file:
ram/IntrinsicOperator.h