souffle: souffle::ast::QualifiedName Class Reference
souffle::ast::QualifiedName Class Reference
Qualified Name class defines fully/partially qualified names to identify objects in components.
#include <QualifiedName.h>
Public Member Functions
void append (std::string name)
append qualifiers
bool empty () const
check for emptiness
const std::vector< std::string > & getQualifiers () const
get qualifiers
bool operator!= (const QualifiedName &other) const
bool operator< (const QualifiedName &other) const
QualifiedName & operator= (const QualifiedName &)=default
QualifiedName & operator= (QualifiedName &&)=default
bool operator== (const QualifiedName &other) const
void prepend (std::string name)
prepend qualifiers
void print (std::ostream &out) const
print qualified name
QualifiedName ()
QualifiedName (const std::string &name)
QualifiedName (const char *name)
QualifiedName (const std::vector< std::string > qualifiers)
QualifiedName (const QualifiedName &)=default
QualifiedName (QualifiedName &&)=default
std::string toString () const
convert to a string separated by fullstop
Private Attributes
std::vector< std::string > qualifiers
Friends
std::ostream & operator<< (std::ostream &out, const QualifiedName &id)
Detailed Description
Qualified Name class defines fully/partially qualified names to identify objects in components.
Definition at line 33 of file QualifiedName.h.
Constructor & Destructor Documentation
QualifiedName() [1/6]
souffle::ast::QualifiedName::QualifiedName () inline
Definition at line 35 of file QualifiedName.h.
Referenced by QualifiedName().
 : qualifiers() {}
QualifiedName() [2/6]
souffle::ast::QualifiedName::QualifiedName (const std::string & name) inline
Definition at line 36 of file QualifiedName.h.
 : qualifiers({name}) {}
QualifiedName() [3/6]
souffle::ast::QualifiedName::QualifiedName (const char * name) inline
Definition at line 37 of file QualifiedName.h.
 : QualifiedName(std::string(name)) {}
QualifiedName() [4/6]
souffle::ast::QualifiedName::QualifiedName (const std::vector< std::string > qualifiers) inline
Definition at line 38 of file QualifiedName.h.
References operator=(), and QualifiedName().
 : qualifiers(qualifiers) {}
QualifiedName() [5/6]
souffle::ast::QualifiedName::QualifiedName (const QualifiedName &) default
QualifiedName() [6/6]
souffle::ast::QualifiedName::QualifiedName (QualifiedName &&) default
Member Function Documentation
append()
void souffle::ast::QualifiedName::append (std::string name) inline
append qualifiers
Definition at line 45 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::getAdornmentID(), souffle::ast::transform::makeRelationName(), and souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
         qualifiers.push_back(std::move(name));
     }
empty()
bool souffle::ast::QualifiedName::empty () const inline
check for emptiness
Definition at line 55 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::ast::transform::ComponentChecker::checkComponentNameReference(), and souffle::ast::analysis::ComponentLookupAnalysis::getComponent().
{
         return qualifiers.empty();
     }
getQualifiers()
const std::vector<std::string>& souffle::ast::QualifiedName::getQualifiers () const inline
get qualifiers
Definition at line 60 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::getAdornment(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::IODefaultsTransformer::getRelationName(), souffle::ast::transform::IOAttributesTransformer::getRelationName(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::isAdorned(), and souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::isNegativelyLabelled().
{
         return qualifiers;
     }
operator!=()
bool souffle::ast::QualifiedName::operator!= (const QualifiedName & other) const inline
Definition at line 75 of file QualifiedName.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::ast::QualifiedName::operator< (const QualifiedName & other) const inline
Definition at line 79 of file QualifiedName.h.
References qualifiers.
{
         return std::lexicographical_compare(
                 qualifiers.begin(), qualifiers.end(), other.qualifiers.begin(), other.qualifiers.end());
     }
operator=() [1/2]
QualifiedName& souffle::ast::QualifiedName::operator= (const QualifiedName &) default
Referenced by QualifiedName().
operator=() [2/2]
QualifiedName& souffle::ast::QualifiedName::operator= (QualifiedName &&) default
operator==()
bool souffle::ast::QualifiedName::operator== (const QualifiedName & other) const inline
Definition at line 71 of file QualifiedName.h.
References qualifiers.
{
         return qualifiers == other.qualifiers;
     }
prepend()
void souffle::ast::QualifiedName::prepend (std::string name) inline
prepend qualifiers
Definition at line 50 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::ast::analysis::NormalisedClause::addClauseAtom(), souffle::ast::analysis::NormalisedClause::addClauseBodyLiteral(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::getMagicName(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::getNegativeLabel(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::getPositiveLabel(), souffle::ast::operator+(), and souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations().
{
         qualifiers.insert(qualifiers.begin(), std::move(name));
     }
print()
void souffle::ast::QualifiedName::print (std::ostream & out) const inline
print qualified name
Definition at line 85 of file QualifiedName.h.
References souffle::join(), and qualifiers.
{
         out << join(qualifiers, ".");
     }
toString()
std::string souffle::ast::QualifiedName::toString () const inline
convert to a string separated by fullstop
Definition at line 65 of file QualifiedName.h.
References souffle::join(), qualifiers, and souffle::profile::ss.
Referenced by souffle::AstToRamTranslator::getEvaluationArity(), souffle::ast::analysis::ProfileUseAnalysis::getRelationSize(), and souffle::ast::analysis::ProfileUseAnalysis::hasRelationSize().
{
         std::stringstream ss;
         ss << join(qualifiers, ".");
         return ss.str();
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const QualifiedName & id) friend
Definition at line 89 of file QualifiedName.h.
{
         id.print(out);
         return out;
     }
Field Documentation
qualifiers
std::vector<std::string> souffle::ast::QualifiedName::qualifiers private
Definition at line 96 of file QualifiedName.h.
Referenced by append(), empty(), getQualifiers(), operator<(), operator==(), prepend(), print(), and toString().
The documentation for this class was generated from the following file:
ast/QualifiedName.h