souffle: souffle::ram::LogSize Class Reference
souffle::ram::LogSize Class Reference
Log relation size and a logging message.
#include <LogSize.h>
Public Member Functions
LogSize * clone () const override
Create a clone (i.e.
const std::string & getMessage () const
Get logging message.
LogSize (Own< RelationReference > relRef, std::string message)
Public Member Functions inherited from souffle::ram::RelationStatement
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get RAM relation.
RelationStatement (Own< RelationReference > relRef)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::string message
logging message
Protected Attributes inherited from souffle::ram::RelationStatement
Own< RelationReference > relationRef
Relation reference.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Log relation size and a logging message.
Definition at line 34 of file LogSize.h.
Constructor & Destructor Documentation
LogSize()
souffle::ram::LogSize::LogSize (Own< RelationReference > relRef, std::string message) inline
Definition at line 36 of file LogSize.h.
Referenced by clone().
             : RelationStatement(std::move(relRef)), message(std::move(message)) {}
Member Function Documentation
clone()
LogSize* souffle::ram::LogSize::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 44 of file LogSize.h.
References souffle::clone(), LogSize(), message, and souffle::ram::RelationStatement::relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new LogSize(souffle::clone(relationRef), message);
     }
equal()
bool souffle::ram::LogSize::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 56 of file LogSize.h.
References souffle::ram::RelationStatement::equal(), and message.
{
         const auto& other = static_cast<const LogSize&>(node);
         return RelationStatement::equal(other) && message == other.message;
     }
getMessage()
const std::string& souffle::ram::LogSize::getMessage () const inline
Get logging message.
Definition at line 40 of file LogSize.h.
References message.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return message;
     }
print()
void souffle::ram::LogSize::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 49 of file LogSize.h.
References souffle::ram::Relation::getName(), souffle::ram::RelationStatement::getRelation(), message, souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "LOGSIZE " << getRelation().getName();
         os << " TEXT "
            << "\"" << stringify(message) << "\"";
         os << std::endl;
     }
Field Documentation
message
std::string souffle::ram::LogSize::message protected
logging message
Definition at line 62 of file LogSize.h.
Referenced by clone(), equal(), getMessage(), and print().
The documentation for this class was generated from the following file:
ram/LogSize.h