souffle: souffle::ast::transform::NormaliseConstraintsTransformer Class Reference
souffle::ast::transform::NormaliseConstraintsTransformer Class Reference
Transformation pass to normalise constraints.
#include <NormaliseConstraints.h>
Public Member Functions
NormaliseConstraintsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to normalise constraints.
E.g.: a(x) :- b(x, 1). -> a(x) :- b(x, tmp0), tmp0=1.
Definition at line 30 of file NormaliseConstraints.h.
Member Function Documentation
clone()
NormaliseConstraintsTransformer* souffle::ast::transform::NormaliseConstraintsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file NormaliseConstraints.h.
References transform().
{
         return new NormaliseConstraintsTransformer();
     }
getName()
std::string souffle::ast::transform::NormaliseConstraintsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 32 of file NormaliseConstraints.h.
{
         return "NormaliseConstraintsTransformer";
     }
transform()
bool souffle::ast::transform::NormaliseConstraintsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 41 of file NormaliseConstraints.cpp.
References souffle::clone(), souffle::EQ, souffle::FEQ, souffle::ast::NumericConstant::Float, souffle::ast::getClauses(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getRelations(), and souffle::ast::isFact().
Referenced by clone().
{
     bool changed = false;
     // set a prefix for variables bound by magic-set for identification later
     // prepended by + to avoid conflict with user-defined variables
     static constexpr const char* boundPrefix = "+abdul";
     Program& program = translationUnit.getProgram();
     /* Create a node mapper that recursively replaces all constants and underscores
      * with named variables.
      *
      * The mapper keeps track of constraints that should be added to the original
      * clause it is being applied on in a given constraint set.
      */
     struct constraintNormaliser : public NodeMapper {
         std::set<BinaryConstraint*>& constraints;
         mutable int changeCount;
         constraintNormaliser(std::set<BinaryConstraint*>& constraints, int changeCount)
                 : constraints(constraints), changeCount(changeCount) {}
         bool hasChanged() const {
             return changeCount > 0;
         }
         int getChangeCount() const {
             return changeCount;
         }
         Own<Node> operator()(Own<Node> node) const override {
             if (auto* stringConstant = dynamic_cast<StringConstant*>(node.get())) {
                 // string constant found
                 changeCount++;
                 // create new variable name (with appropriate suffix)
                 std::string constantValue = stringConstant->getConstant();
                 std::stringstream newVariableName;
                 newVariableName << boundPrefix << changeCount << "_" << constantValue << "_s";
                 // create new constraint (+abdulX = constant)
                 auto newVariable = mk<ast::Variable>(newVariableName.str());
                 constraints.insert(new BinaryConstraint(
                         BinaryConstraintOp::EQ, souffle::clone(newVariable), souffle::clone(stringConstant)));
                 // update constant to be the variable created
                 return newVariable;
             } else if (auto* numberConstant = dynamic_cast<NumericConstant*>(node.get())) {
                 // number constant found
                 changeCount++;
                 // create new variable name (with appropriate suffix)
                 std::stringstream newVariableName;
                 newVariableName << boundPrefix << changeCount << "_" << numberConstant->getConstant() << "_n";
                 assert(numberConstant->getType() && "numeric constant hasn't been poly-constrained");
                 auto opEq = *numberConstant->getType() == NumericConstant::Type::Float
                                     ? BinaryConstraintOp::FEQ
                                     : BinaryConstraintOp::EQ;
                 // create new constraint (+abdulX = constant)
                 auto newVariable = mk<ast::Variable>(newVariableName.str());
                 constraints.insert(new BinaryConstraint(
                         opEq, souffle::clone(newVariable), souffle::clone(numberConstant)));
                 // update constant to be the variable created
                 return newVariable;
             } else if (isA<UnnamedVariable>(node.get())) {
                 // underscore found
                 changeCount++;
                 // create new variable name
                 std::stringstream newVariableName;
                 newVariableName << "+underscore" << changeCount;
                 return mk<ast::Variable>(newVariableName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     int changeCount = 0;  // number of constants and underscores seen so far
     // apply the change to all clauses in the program
     for (Relation* rel : program.getRelations()) {
         for (Clause* clause : getClauses(program, *rel)) {
             if (isFact(*clause)) {
                 continue;  // don't normalise facts
             }
             std::set<BinaryConstraint*> constraints;
             constraintNormaliser update(constraints, changeCount);
             clause->apply(update);
             changeCount = update.getChangeCount();
             changed = changed || update.hasChanged();
             for (BinaryConstraint* constraint : constraints) {
                 clause->addToBody(Own<BinaryConstraint>(constraint));
             }
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/NormaliseConstraints.h
ast/transform/NormaliseConstraints.cpp