souffle: souffle::ram::Exit Class Reference
souffle::ram::Exit Class Reference
Exit statement for a loop.
#include <Exit.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Exit * clone () const override
Create a clone (i.e.
Exit (Own< Condition > c)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Condition & getCondition () const
Get exit condition.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Condition > condition
exit condition
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Exit statement for a loop.
Exits a loop if exit condition holds.
The following example will exit the loop given that A is the empty set:
EXIT (A = ∅)
Definition at line 44 of file Exit.h.
Constructor & Destructor Documentation
Exit()
souffle::ram::Exit::Exit (Own< Condition > c) inline
Definition at line 46 of file Exit.h.
References condition.
Referenced by clone().
                            : condition(std::move(c)) {
         assert(condition && "condition is a nullptr");
     }
Member Function Documentation
apply()
void souffle::ram::Exit::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 63 of file Exit.h.
References condition, and souffle::map().
{
         condition = map(std::move(condition));
     }
clone()
Exit* souffle::ram::Exit::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 59 of file Exit.h.
References souffle::clone(), condition, and Exit().
Referenced by souffle::ram::test::TEST().
{
         return new Exit(souffle::clone(condition));
     }
equal()
bool souffle::ram::Exit::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 72 of file Exit.h.
References condition, and souffle::equal_ptr().
{
         const auto& other = static_cast<const Exit&>(node);
         return equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Exit::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 55 of file Exit.h.
References condition.
{
         return {condition.get()};
     }
getCondition()
const Condition& souffle::ram::Exit::getCondition () const inline
Get exit condition.
Definition at line 51 of file Exit.h.
References condition.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and print().
{
         return *condition;
     }
print()
void souffle::ram::Exit::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 68 of file Exit.h.
References getCondition(), and souffle::times().
{
         os << times(" ", tabpos) << "EXIT " << getCondition() << std::endl;
     }
Field Documentation
condition
Own<Condition> souffle::ram::Exit::condition protected
exit condition
Definition at line 78 of file Exit.h.
Referenced by apply(), clone(), equal(), Exit(), getChildNodes(), and getCondition().
The documentation for this class was generated from the following file:
ram/Exit.h