souffle: souffle::ast::ExecutionOrder Class Reference
souffle::ast::ExecutionOrder Class Reference
An execution order for atoms within a clause; one or more execution orders form a plan.
#include <ExecutionOrder.h>
Public Types
using ExecOrder = std::vector< unsigned int >
Public Member Functions
ExecutionOrder * clone () const override
Create a clone (i.e.
ExecutionOrder (ExecOrder order={}, SrcLocation loc={})
const ExecOrder & getOrder () const
Get order.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &out) const override
Output to a given output stream.
Private Attributes
ExecOrder order
Literal order of body (starting from 1)
Detailed Description
An execution order for atoms within a clause; one or more execution orders form a plan.
Definition at line 34 of file ExecutionOrder.h.
Member Typedef Documentation
ExecOrder
using souffle::ast::ExecutionOrder::ExecOrder = std::vector<unsigned int>
Definition at line 36 of file ExecutionOrder.h.
Constructor & Destructor Documentation
ExecutionOrder()
souffle::ast::ExecutionOrder::ExecutionOrder (ExecOrder order = {}, SrcLocation loc = {}) inline
Definition at line 38 of file ExecutionOrder.h.
References order, and souffle::ast::Node::setSrcLoc().
Referenced by clone().
                                      {}, SrcLocation loc = {}) : order(std::move(order)) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
clone()
ExecutionOrder* souffle::ast::ExecutionOrder::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 47 of file ExecutionOrder.h.
References ExecutionOrder(), souffle::ast::Node::getSrcLoc(), and order.
{
         return new ExecutionOrder(order, getSrcLoc());
     }
equal()
bool souffle::ast::ExecutionOrder::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 56 of file ExecutionOrder.h.
References order.
{
         const auto& other = static_cast<const ExecutionOrder&>(node);
         return order == other.order;
     }
getOrder()
const ExecOrder& souffle::ast::ExecutionOrder::getOrder () const inline
Get order.
Definition at line 43 of file ExecutionOrder.h.
References order.
{
         return order;
     }
print()
void souffle::ast::ExecutionOrder::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 52 of file ExecutionOrder.h.
References souffle::join(), and order.
{
         out << "(" << join(order) << ")";
     }
Field Documentation
order
ExecOrder souffle::ast::ExecutionOrder::order private
Literal order of body (starting from 1)
Definition at line 63 of file ExecutionOrder.h.
Referenced by clone(), equal(), ExecutionOrder(), getOrder(), and print().
The documentation for this class was generated from the following file:
ast/ExecutionOrder.h