souffle: souffle::ram::PackRecord Class Reference
souffle::ram::PackRecord Class Reference
Packs a record's arguments into a reference.
#include <PackRecord.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
PackRecord * clone () const override
Create a clone (i.e.
std::vector< Expression * > getArguments () const
Get record arguments.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
PackRecord (VecOwn< Expression > args)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
VecOwn< Expression > arguments
Arguments.
Detailed Description
Packs a record's arguments into a reference.
Definition at line 36 of file PackRecord.h.
Constructor & Destructor Documentation
PackRecord()
souffle::ram::PackRecord::PackRecord (VecOwn< Expression > args) inline
Definition at line 38 of file PackRecord.h.
References arguments.
Referenced by clone().
                                         : arguments(std::move(args)) {
         for (const auto& arg : arguments) {
             assert(arg != nullptr && "argument is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::ram::PackRecord::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 65 of file PackRecord.h.
References arguments, and souffle::map().
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
clone()
PackRecord* souffle::ram::PackRecord::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Expression.
Definition at line 57 of file PackRecord.h.
References arguments, and PackRecord().
Referenced by souffle::ram::test::TEST().
{
         auto* res = new PackRecord({});
         for (auto& cur : arguments) {
             res->arguments.emplace_back(cur->clone());
         }
         return res;
     }
equal()
bool souffle::ram::PackRecord::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 77 of file PackRecord.h.
References arguments, and souffle::equal_targets().
{
         const auto& other = static_cast<const PackRecord&>(node);
         return equal_targets(arguments, other.arguments);
     }
getArguments()
std::vector<Expression*> souffle::ram::PackRecord::getArguments () const inline
Get record arguments.
Definition at line 45 of file PackRecord.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), and souffle::NodeGenerator::visitPackRecord().
{
         return toPtrVector(arguments);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::PackRecord::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 49 of file PackRecord.h.
References arguments.
{
         std::vector<const Node*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
print()
void souffle::ram::PackRecord::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 72 of file PackRecord.h.
References arguments, and souffle::join().
{
         os << "[" << join(arguments, ",", [](std::ostream& out, const Own<Expression>& arg) { out << *arg; })
            << "]";
     }
Field Documentation
arguments
VecOwn<Expression> souffle::ram::PackRecord::arguments protected
Arguments.
Definition at line 83 of file PackRecord.h.
Referenced by apply(), clone(), equal(), getArguments(), getChildNodes(), PackRecord(), and print().
The documentation for this class was generated from the following file:
ram/PackRecord.h