souffle: souffle::ast::analysis::ClauseNormalisationAnalysis Class Reference
souffle::ast::analysis::ClauseNormalisationAnalysis Class Reference
#include <ClauseNormalisation.h>
Public Member Functions
ClauseNormalisationAnalysis ()
const NormalisedClause & getNormalisation (const Clause *clause) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "clause-normalisation"
Private Attributes
std::map< const Clause *, NormalisedClause > normalisations
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 89 of file ClauseNormalisation.h.
Constructor & Destructor Documentation
ClauseNormalisationAnalysis()
souffle::ast::analysis::ClauseNormalisationAnalysis::ClauseNormalisationAnalysis () inline
Definition at line 93 of file ClauseNormalisation.h.
 : Analysis(name) {}
Member Function Documentation
getNormalisation()
const NormalisedClause & souffle::ast::analysis::ClauseNormalisationAnalysis::getNormalisation (const Clause * clause) const
Definition at line 182 of file ClauseNormalisation.cpp.
References souffle::contains().
Referenced by souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses().
{
     assert(contains(normalisations, clause) && "clause not normalised");
     return normalisations.at(clause);
 }
print()
void souffle::ast::analysis::ClauseNormalisationAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 168 of file ClauseNormalisation.cpp.
References i.
{
     for (const auto& [clause, norm] : normalisations) {
         os << "Normalise(" << *clause << ") = {";
         const auto& els = norm.getElements();
         for (size_t i = 0; i < els.size(); i++) {
             if (i != 0) {
                 os << ", ";
             }
             os << els[i].name << ":" << els[i].params;
         }
         os << "}" << std::endl;
     }
 }
run()
void souffle::ast::analysis::ClauseNormalisationAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 160 of file ClauseNormalisation.cpp.
References souffle::contains(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::analysis::NormalisedClause::NormalisedClause().
{
     const auto& program = translationUnit.getProgram();
     for (const auto* clause : program.getClauses()) {
         assert(!contains(normalisations, clause) && "clause already processed");
         normalisations[clause] = NormalisedClause(clause);
     }
 }
Field Documentation
name
constexpr const char* souffle::ast::analysis::ClauseNormalisationAnalysis::name = "clause-normalisation" static
Definition at line 91 of file ClauseNormalisation.h.
normalisations
std::map<const Clause*, NormalisedClause> souffle::ast::analysis::ClauseNormalisationAnalysis::normalisations private
Definition at line 102 of file ClauseNormalisation.h.
The documentation for this class was generated from the following files:
ast/analysis/ClauseNormalisation.h
ast/analysis/ClauseNormalisation.cpp