souffle: souffle::ram::DebugInfo Class Reference
souffle::ram::DebugInfo Class Reference
Debug statement.
#include <DebugInfo.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
DebugInfo * clone () const override
Create a clone (i.e.
DebugInfo (Own< Statement > stmt, std::string msg)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractLog
AbstractLog (Own< Statement > stmt, std::string msg)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const std::string & getMessage () const
Get logging message.
const Statement & getStatement () const
Get logging statement.
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::Node
virtual bool equal (const Node &) const
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::AbstractLog
bool equal (const Node &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::AbstractLog
std::string message
logging message
Own< Statement > statement
logging statement
Detailed Description
Debug statement.
For example:
BEGIN_DEBUG "gen(1) \nin file /file.dl [7:7-7:10]\;"
  ...
END_DEBUG
Definition at line 43 of file DebugInfo.h.
Constructor & Destructor Documentation
DebugInfo()
souffle::ram::DebugInfo::DebugInfo (Own< Statement > stmt, std::string msg) inline
Definition at line 45 of file DebugInfo.h.
Referenced by clone().
 : AbstractLog(std::move(stmt), std::move(msg)) {}
Member Function Documentation
apply()
void souffle::ram::DebugInfo::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 55 of file DebugInfo.h.
References souffle::ram::AbstractLog::apply().
{
         AbstractLog::apply(map);
     }
clone()
DebugInfo* souffle::ram::DebugInfo::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 51 of file DebugInfo.h.
References souffle::clone(), DebugInfo(), souffle::ram::AbstractLog::message, and souffle::ram::AbstractLog::statement.
Referenced by souffle::ram::test::TEST().
{
         return new DebugInfo(souffle::clone(statement), message);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::DebugInfo::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 47 of file DebugInfo.h.
References souffle::ram::AbstractLog::getChildNodes().
{
         return AbstractLog::getChildNodes();
     }
print()
void souffle::ram::DebugInfo::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 60 of file DebugInfo.h.
References souffle::ram::AbstractLog::message, souffle::ram::Statement::print(), souffle::ram::AbstractLog::statement, souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "BEGIN_DEBUG \"" << stringify(message) << "\"" << std::endl;
         Statement::print(statement.get(), os, tabpos + 1);
         os << times(" ", tabpos) << "END_DEBUG" << std::endl;
     }
The documentation for this class was generated from the following file:
ram/DebugInfo.h