souffle: souffle::ast::analysis::ProfileUseAnalysis Class Reference
souffle::ast::analysis::ProfileUseAnalysis Class Reference
Analysis that loads profile data and has a profile query interface.
#include <ProfileUse.h>
Public Member Functions
size_t getRelationSize (const QualifiedName &rel) const
Return size of relation in the profile.
bool hasRelationSize (const QualifiedName &rel) const
Check whether the relation size exists in profile.
void print (std::ostream &os) const override
Output some profile information.
ProfileUseAnalysis ()
void run (const TranslationUnit &translationUnit) override
Run analysis.
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "profile-use"
Name of analysis.
Private Attributes
std::shared_ptr< profile::ProgramRun > programRun
performance model of profile run
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis that loads profile data and has a profile query interface.
Definition at line 36 of file ProfileUse.h.
Constructor & Destructor Documentation
ProfileUseAnalysis()
souffle::ast::analysis::ProfileUseAnalysis::ProfileUseAnalysis () inline
Definition at line 41 of file ProfileUse.h.
References getRelationSize(), hasRelationSize(), print(), and run().
             : Analysis(name), programRun(std::make_shared<profile::ProgramRun>(profile::ProgramRun())) {}
Member Function Documentation
getRelationSize()
size_t souffle::ast::analysis::ProfileUseAnalysis::getRelationSize (const QualifiedName & rel) const
Return size of relation in the profile.
Get relation size from profile.
Definition at line 54 of file ProfileUse.cpp.
References programRun, and souffle::ast::QualifiedName::toString().
Referenced by ProfileUseAnalysis().
{
     if (const auto* profRel = programRun->getRelation(rel.toString())) {
         return profRel->size();
     } else {
         return std::numeric_limits<size_t>::max();
     }
 }
hasRelationSize()
bool souffle::ast::analysis::ProfileUseAnalysis::hasRelationSize (const QualifiedName & rel) const
Check whether the relation size exists in profile.
Check whether relation size is defined in profile.
Definition at line 47 of file ProfileUse.cpp.
References programRun, and souffle::ast::QualifiedName::toString().
Referenced by ProfileUseAnalysis().
{
     return programRun->getRelation(rel.toString()) != nullptr;
 }
print()
void souffle::ast::analysis::ProfileUseAnalysis::print (std::ostream & os) const override virtual
Output some profile information.
Print analysis.
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 42 of file ProfileUse.cpp.
Referenced by ProfileUseAnalysis().
 {}
run()
void souffle::ast::analysis::ProfileUseAnalysis::run (const TranslationUnit & translationUnit) override virtual
Run analysis.
Run analysis, i.e., retrieve profile information.
Implements souffle::ast::analysis::Analysis.
Definition at line 32 of file ProfileUse.cpp.
References souffle::Global::config(), souffle::profile::Reader::processFile(), and programRun.
Referenced by ProfileUseAnalysis().
{
     if (Global::config().has("profile-use")) {
         std::string filename = Global::config().get("profile-use");
         profile::Reader(filename, programRun).processFile();
     }
 }
Field Documentation
name
constexpr const char* souffle::ast::analysis::ProfileUseAnalysis::name = "profile-use" static
Name of analysis.
Definition at line 39 of file ProfileUse.h.
programRun
std::shared_ptr<profile::ProgramRun> souffle::ast::analysis::ProfileUseAnalysis::programRun private
performance model of profile run
Definition at line 58 of file ProfileUse.h.
Referenced by getRelationSize(), hasRelationSize(), and run().
The documentation for this class was generated from the following files:
ast/analysis/ProfileUse.h
ast/analysis/ProfileUse.cpp