souffle: souffle::ram::transform::ReorderFilterBreak Class Reference
souffle::ram::transform::ReorderFilterBreak Class Reference
#include <ReorderFilterBreak.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool reorderFilterBreak (Program &program)
reorder filter-break nesting to break-filter nesting
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Definition at line 49 of file ReorderFilterBreak.h.
Member Function Documentation
getName()
std::string souffle::ram::transform::ReorderFilterBreak::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 51 of file ReorderFilterBreak.h.
References reorderFilterBreak().
{
         return "ReorderFilterBreak";
     }
reorderFilterBreak()
bool souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak (Program & program)
reorder filter-break nesting to break-filter nesting
Parameters
program Program that is transform
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 29 of file ReorderFilterBreak.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::ram::Program::apply(), souffle::clone(), souffle::filter(), souffle::ram::makeLambdaRamMapper(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> filterRewriter = [&](Own<Node> node) -> Own<Node> {
             // find filter-break nesting
             if (const Filter* filter = dynamic_cast<Filter*>(node.get())) {
                 if (const Break* br = dynamic_cast<Break*>(&filter->getOperation())) {
                     changed = true;
                     // convert to break-filter nesting
                     node = mk<Break>(souffle::clone(&br->getCondition()),
                             mk<Filter>(souffle::clone(&filter->getCondition()),
                                     souffle::clone(&br->getOperation())));
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
transform()
bool souffle::ram::transform::ReorderFilterBreak::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 63 of file ReorderFilterBreak.h.
References souffle::ram::TranslationUnit::getProgram(), and reorderFilterBreak().
{
         return reorderFilterBreak(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/ReorderFilterBreak.h
ram/transform/ReorderFilterBreak.cpp