souffle: souffle::ram::Conjunction Class Reference
souffle::ram::Conjunction Class Reference
A conjunction of conditions.
#include <Conjunction.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Conjunction * clone () const override
Create a clone (i.e.
Conjunction (Own< Condition > l, Own< Condition > r)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Condition & getLHS () const
Get left-hand side of conjunction.
const Condition & getRHS () const
Get right-hand side of conjunction.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Condition > lhs
Left-hand side of conjunction.
Own< Condition > rhs
Right-hand side of conjunction.
Detailed Description
A conjunction of conditions.
Condition of the form "LHS and RHS", where LHS and RHS are conditions
For example:
C1 AND C2 AND C3
Is a Conjunction, which may have LHS "C1" and RHS "C2 AND C3"
Definition at line 47 of file Conjunction.h.
Constructor & Destructor Documentation
Conjunction()
souffle::ram::Conjunction::Conjunction (Own< Condition > l, Own< Condition > r) inline
Definition at line 49 of file Conjunction.h.
References lhs, and rhs.
Referenced by clone().
                                                     : lhs(std::move(l)), rhs(std::move(r)) {
         assert(lhs != nullptr && "left-hand side of conjunction is a nullptr");
         assert(rhs != nullptr && "right-hand side of conjunction is a nullptr");
     }
Member Function Documentation
apply()
void souffle::ram::Conjunction::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 72 of file Conjunction.h.
References lhs, souffle::map(), and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
clone()
Conjunction* souffle::ram::Conjunction::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Condition.
Definition at line 68 of file Conjunction.h.
References souffle::clone(), Conjunction(), lhs, and rhs.
{
         return new Conjunction(souffle::clone(lhs), souffle::clone(rhs));
     }
equal()
bool souffle::ram::Conjunction::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 82 of file Conjunction.h.
References souffle::equal_ptr(), lhs, and rhs.
{
         const auto& other = static_cast<const Conjunction&>(node);
         return equal_ptr(lhs, other.lhs) && equal_ptr(rhs, other.rhs);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Conjunction::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 64 of file Conjunction.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
getLHS()
const Condition& souffle::ram::Conjunction::getLHS () const inline
Get left-hand side of conjunction.
Definition at line 55 of file Conjunction.h.
References lhs.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::ComplexityAnalysis::getComplexity(), and souffle::ram::analysis::LevelAnalysis::getLevel().
{
         return *lhs;
     }
getRHS()
const Condition& souffle::ram::Conjunction::getRHS () const inline
Get right-hand side of conjunction.
Definition at line 60 of file Conjunction.h.
References rhs.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::ComplexityAnalysis::getComplexity(), and souffle::ram::analysis::LevelAnalysis::getLevel().
{
         return *rhs;
     }
print()
void souffle::ram::Conjunction::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 78 of file Conjunction.h.
References lhs, and rhs.
{
         os << "(" << *lhs << " AND " << *rhs << ")";
     }
Field Documentation
lhs
Own<Condition> souffle::ram::Conjunction::lhs protected
Left-hand side of conjunction.
Definition at line 88 of file Conjunction.h.
Referenced by apply(), clone(), Conjunction(), equal(), getChildNodes(), getLHS(), and print().
rhs
Own<Condition> souffle::ram::Conjunction::rhs protected
Right-hand side of conjunction.
Definition at line 91 of file Conjunction.h.
Referenced by apply(), clone(), Conjunction(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
ram/Conjunction.h