souffle: souffle::ram::analysis::SearchSignature Class Reference
souffle::ram::analysis::SearchSignature Class Reference
search signature of a RAM operation; each bit represents an attribute of a relation.
#include <Index.h>
Data Structures
class Hasher
Public Member Functions
size_t arity () const
bool containsEquality () const
bool empty () const
bool operator!= (const SearchSignature &other) const
bool operator< (const SearchSignature &other) const
bool operator== (const SearchSignature &other) const
AttributeConstraint & operator[] (std::size_t pos)
const AttributeConstraint & operator[] (std::size_t pos) const
SearchSignature (size_t arity)
Static Public Member Functions
static SearchSignature getDelta (const SearchSignature &lhs, const SearchSignature &rhs)
static SearchSignature getDischarged (const SearchSignature &signature)
static SearchSignature getFullSearchSignature (size_t arity)
static bool isComparable (const SearchSignature &lhs, const SearchSignature &rhs)
static bool isSubset (const SearchSignature &lhs, const SearchSignature &rhs)
Private Attributes
std::vector< AttributeConstraint > constraints
Friends
std::ostream & operator<< (std::ostream &out, const SearchSignature &signature)
Detailed Description
search signature of a RAM operation; each bit represents an attribute of a relation.
A one represents that the attribute has an assigned value; a zero represents that no value exists (i.e. attribute is unbounded) in the search.
Definition at line 51 of file Index.h.
Constructor & Destructor Documentation
SearchSignature()
souffle::ram::analysis::SearchSignature::SearchSignature (size_t arity) explicit
Definition at line 38 of file Index.cpp.
References souffle::ram::analysis::None.
 : constraints(arity, AttributeConstraint::None) {}
Member Function Documentation
arity()
size_t souffle::ram::analysis::SearchSignature::arity () const
Definition at line 40 of file Index.cpp.
References constraints.
Referenced by souffle::ram::analysis::MinIndexSelection::card(), souffle::NodeGenerator::encodeIndexPos(), souffle::ram::analysis::MinIndexSelection::getAttributesToDischarge(), getDelta(), getDischarged(), getFullSearchSignature(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), souffle::ram::analysis::MinIndexSelection::insertIndex(), isComparable(), isSubset(), souffle::ram::analysis::SearchSignature::Hasher::operator()(), and souffle::ram::analysis::IndexAnalysis::print().
{
     return constraints.size();
 }
containsEquality()
bool souffle::ram::analysis::SearchSignature::containsEquality () const
Definition at line 80 of file Index.cpp.
References constraints, souffle::ram::analysis::Equal, and i.
{
     for (size_t i = 0; i < constraints.size(); ++i) {
         if (constraints[i] == AttributeConstraint::Equal) {
             return true;
         }
     }
     return false;
 }
empty()
bool souffle::ram::analysis::SearchSignature::empty () const
Definition at line 70 of file Index.cpp.
References constraints, i, and souffle::ram::analysis::None.
Referenced by souffle::ram::analysis::MinIndexSelection::addSearch(), and souffle::NodeGenerator::encodeIndexPos().
{
     size_t len = constraints.size();
     for (size_t i = 0; i < len; ++i) {
         if (constraints[i] != AttributeConstraint::None) {
             return false;
         }
     }
     return true;
 }
getDelta()
SearchSignature souffle::ram::analysis::SearchSignature::getDelta (const SearchSignature & lhs, const SearchSignature & rhs) static
Definition at line 119 of file Index.cpp.
References arity(), constraints, i, and souffle::ram::analysis::None.
Referenced by souffle::ram::analysis::MinIndexSelection::solve(), and souffle::ram::analysis::MinIndexSelection::updateSearch().
{
     assert(lhs.arity() == rhs.arity());
     SearchSignature delta(lhs.arity());
     for (size_t i = 0; i < lhs.arity(); ++i) {
         // if constraints are the same then delta is nothing
         if (rhs[i] == AttributeConstraint::None) {
             delta.constraints[i] = lhs[i];
         } else {
             delta.constraints[i] = AttributeConstraint::None;
         }
     }
     return delta;
 }
getDischarged()
SearchSignature souffle::ram::analysis::SearchSignature::getDischarged (const SearchSignature & signature) static
Definition at line 141 of file Index.cpp.
References arity(), i, souffle::ram::analysis::Inequal, and souffle::ram::analysis::None.
{
     SearchSignature res = signature;  // copy original
     for (size_t i = 0; i < res.arity(); ++i) {
         if (res[i] == AttributeConstraint::Inequal) {
             res[i] = AttributeConstraint::None;
         }
     }
     return res;
 }
getFullSearchSignature()
SearchSignature souffle::ram::analysis::SearchSignature::getFullSearchSignature (size_t arity) static
Definition at line 133 of file Index.cpp.
References arity(), constraints, souffle::ram::analysis::Equal, and i.
Referenced by souffle::NodeGenerator::encodeIndexPos(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
{
     SearchSignature res(arity);
     for (size_t i = 0; i < arity; ++i) {
         res.constraints[i] = AttributeConstraint::Equal;
     }
     return res;
 }
isComparable()
bool souffle::ram::analysis::SearchSignature::isComparable (const SearchSignature & lhs, const SearchSignature & rhs) static
Definition at line 91 of file Index.cpp.
References arity(), i, souffle::ram::analysis::Inequal, and souffle::ram::analysis::None.
Referenced by operator<().
{
     assert(lhs.arity() == rhs.arity());
     if (lhs == rhs) {
         return true;
     }
     bool withinDelta = true;
     for (size_t i = 0; i < rhs.arity(); ++i) {
         if (rhs[i] == AttributeConstraint::Inequal) {
             if (lhs[i] != AttributeConstraint::None) {
                 withinDelta = false;
             }
         }
     }
     return withinDelta;
 }
isSubset()
bool souffle::ram::analysis::SearchSignature::isSubset (const SearchSignature & lhs, const SearchSignature & rhs) static
Definition at line 108 of file Index.cpp.
References arity(), i, and souffle::ram::analysis::None.
Referenced by operator<().
{
     assert(lhs.arity() == rhs.arity());
     size_t len = lhs.arity();
     for (size_t i = 0; i < len; ++i) {
         if (lhs[i] != AttributeConstraint::None && rhs[i] == AttributeConstraint::None) {
             return false;
         }
     }
     return true;
 }
operator!=()
bool souffle::ram::analysis::SearchSignature::operator!= (const SearchSignature & other) const
Definition at line 66 of file Index.cpp.
{
     return !(*this == other);
 }
operator<()
bool souffle::ram::analysis::SearchSignature::operator< (const SearchSignature & other) const
Definition at line 56 of file Index.cpp.
References constraints, isComparable(), and isSubset().
{
     assert(constraints.size() == other.constraints.size());
     return isComparable(*this, other) && isSubset(*this, other);
 }
operator==()
bool souffle::ram::analysis::SearchSignature::operator== (const SearchSignature & other) const
Definition at line 61 of file Index.cpp.
References constraints.
{
     assert(constraints.size() == other.constraints.size());
     return constraints == other.constraints;
 }
operator[]() [1/2]
AttributeConstraint & souffle::ram::analysis::SearchSignature::operator[] (std::size_t pos)
Definition at line 45 of file Index.cpp.
References constraints.
{
     assert(pos < constraints.size());
     return constraints[pos];
 }
operator[]() [2/2]
const AttributeConstraint & souffle::ram::analysis::SearchSignature::operator[] (std::size_t pos) const
Definition at line 50 of file Index.cpp.
References constraints.
{
     assert(pos < constraints.size());
     return constraints[pos];
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const SearchSignature & signature) friend
Definition at line 151 of file Index.cpp.
{
     size_t len = signature.constraints.size();
     for (size_t i = 0; i < len; ++i) {
         switch (signature.constraints[i]) {
             case AttributeConstraint::None: out << 0; break;
             case AttributeConstraint::Equal: out << 1; break;
             case AttributeConstraint::Inequal: out << 2; break;
         }
     }
     return out;
 }
Field Documentation
constraints
std::vector<AttributeConstraint> souffle::ram::analysis::SearchSignature::constraints private
Definition at line 89 of file Index.h.
Referenced by arity(), containsEquality(), empty(), getDelta(), getFullSearchSignature(), souffle::ram::analysis::SearchSignature::Hasher::operator()(), operator<(), souffle::ram::analysis::operator<<(), operator==(), and operator[]().
The documentation for this class was generated from the following files:
ram/analysis/Index.h
ram/analysis/Index.cpp