souffle: souffle::ast::AlgebraicDataType Class Reference
souffle::ast::AlgebraicDataType Class Reference
Combination of types using sums and products.
#include <AlgebraicDataType.h>
Public Member Functions
AlgebraicDataType (QualifiedName name, VecOwn< BranchDeclaration > branches, SrcLocation loc={})
AlgebraicDataType * clone () const override
std::vector< BranchDeclaration * > getBranches () const
void print (std::ostream &os) const override
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
bool equal (const Node &node) const override
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Private Attributes
VecOwn< BranchDeclaration > branches
The list of branches for this sum type.
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Detailed Description
Combination of types using sums and products.
ADT combines a simpler types using product types and sum types.
Example: .type Nat = S {n : Nat} | Zero {}
The type Nat has two branches, S which takes element of type Nat and Zero which doesn't take any arguments.
Definition at line 49 of file AlgebraicDataType.h.
Constructor & Destructor Documentation
AlgebraicDataType()
souffle::ast::AlgebraicDataType::AlgebraicDataType (QualifiedName name, VecOwn< BranchDeclaration > branches, SrcLocation loc = {}) inline
Definition at line 51 of file AlgebraicDataType.h.
References branches, and souffle::ast::analysis::Type::Type().
Referenced by clone().
                                                                                                 {})
             : Type(std::move(name), std::move(loc)), branches(std::move(branches)) {
         assert(!this->branches.empty());
     };
Member Function Documentation
clone()
AlgebraicDataType* souffle::ast::AlgebraicDataType::clone () const inline override
Definition at line 64 of file AlgebraicDataType.h.
References AlgebraicDataType(), and souffle::clone().
{
         return new AlgebraicDataType(getQualifiedName(), souffle::clone(branches), getSrcLoc());
     }
equal()
bool souffle::ast::AlgebraicDataType::equal (const Node & node) const inline override protected
Definition at line 69 of file AlgebraicDataType.h.
References branches.
{
         const auto& other = dynamic_cast<const AlgebraicDataType&>(node);
         return getQualifiedName() == other.getQualifiedName() && branches == other.branches;
     }
getBranches()
std::vector<BranchDeclaration*> souffle::ast::AlgebraicDataType::getBranches () const inline
Definition at line 56 of file AlgebraicDataType.h.
References souffle::toPtrVector().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkADT().
{
         return toPtrVector(branches);
     }
print()
void souffle::ast::AlgebraicDataType::print (std::ostream & os) const inline override virtual
Reimplemented from souffle::ast::analysis::Type.
Definition at line 60 of file AlgebraicDataType.h.
References tinyformat::format(), and souffle::join().
{
         os << tfm::format(".type %s = %s", getQualifiedName(), join(branches, " | "));
     }
Field Documentation
branches
VecOwn<BranchDeclaration> souffle::ast::AlgebraicDataType::branches private
The list of branches for this sum type.
Definition at line 76 of file AlgebraicDataType.h.
Referenced by AlgebraicDataType(), and equal().
The documentation for this class was generated from the following file:
ast/AlgebraicDataType.h