souffle: souffle::ram::analysis::ComplexityAnalysis Class Reference
souffle::ram::analysis::ComplexityAnalysis Class Reference
A Ram Analysis for determining the number of relational operations in a condition / expression.
#include <Complexity.h>
Public Member Functions
ComplexityAnalysis (const char *id)
int getComplexity (const Node *value) const
Get complexity of a RAM expression/condition.
void run (const TranslationUnit &) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::ram::analysis::Analysis
Analysis (const char *id)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "complexity-analysis"
Additional Inherited Members
Protected Attributes inherited from souffle::ram::analysis::Analysis
std::string identifier
name of analysis instance
Detailed Description
A Ram Analysis for determining the number of relational operations in a condition / expression.
Definition at line 33 of file Complexity.h.
Constructor & Destructor Documentation
ComplexityAnalysis()
souffle::ram::analysis::ComplexityAnalysis::ComplexityAnalysis (const char * id) inline
Definition at line 35 of file Complexity.h.
 : Analysis(id) {}
Member Function Documentation
getComplexity()
int souffle::ram::analysis::ComplexityAnalysis::getComplexity (const Node * value) const
Get complexity of a RAM expression/condition.
Definition at line 32 of file Complexity.cpp.
References souffle::ram::Relation::getArity(), souffle::ram::Conjunction::getLHS(), souffle::ram::Negation::getOperand(), souffle::ram::EmptinessCheck::getRelation(), and souffle::ram::Conjunction::getRHS().
Referenced by souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), and run().
{
     // visitor
     class ValueComplexityVisitor : public Visitor<int> {
     public:
         // conjunction
         int visitConjunction(const Conjunction& conj) override {
             return visit(conj.getLHS()) + visit(conj.getRHS());
         }
         // negation
         int visitNegation(const Negation& neg) override {
             return visit(neg.getOperand());
         }
         // existence check
         int visitExistenceCheck(const ExistenceCheck&) override {
             return 2;
         }
         // provenance existence check
         int visitProvenanceExistenceCheck(const ProvenanceExistenceCheck&) override {
             return 2;
         }
         // emptiness check
         int visitEmptinessCheck(const EmptinessCheck& emptiness) override {
             // emptiness check for nullary relations is for free; others have weight one
             return (emptiness.getRelation().getArity() > 0) ? 1 : 0;
         }
         // default rule
         int visitNode(const Node&) override {
             return 0;
         }
     };
     assert((isA<Expression>(node) || isA<Condition>(node)) && "not an expression/condition/operation");
     return ValueComplexityVisitor().visit(node);
 }
run()
void souffle::ram::analysis::ComplexityAnalysis::run (const TranslationUnit & translationUnit) inline override virtual
Run analysis for a RAM translation unit.
Implements souffle::ram::analysis::Analysis.
Definition at line 39 of file Complexity.h.
References getComplexity().
 {}
Field Documentation
name
constexpr const char* souffle::ram::analysis::ComplexityAnalysis::name = "complexity-analysis" static
Definition at line 37 of file Complexity.h.
The documentation for this class was generated from the following files:
ram/analysis/Complexity.h
ram/analysis/Complexity.cpp