souffle: souffle::ram::AbstractExistenceCheck Class Reference
souffle::ram::AbstractExistenceCheck Class Reference
Abstract existence check for a tuple in a relation.
#include <AbstractExistenceCheck.h>
Public Member Functions
AbstractExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get relation.
const std::vector< Expression * > getValues () const
Get arguments of the tuple/pattern A null pointer element in the vector denotes an unspecified pattern for a tuple element.
Public Member Functions inherited from souffle::ram::Condition
Condition * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< RelationReference > relationRef
Relation.
VecOwn< Expression > values
Pattern – nullptr if undefined.
Detailed Description
Abstract existence check for a tuple in a relation.
Definition at line 40 of file AbstractExistenceCheck.h.
Constructor & Destructor Documentation
AbstractExistenceCheck()
souffle::ram::AbstractExistenceCheck::AbstractExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals) inline
Definition at line 42 of file AbstractExistenceCheck.h.
References relationRef, and values.
             : relationRef(std::move(relRef)), values(std::move(vals)) {
         assert(relationRef != nullptr && "Relation reference is a nullptr");
         for (const auto& v : values) {
             assert(v != nullptr && "value is a nullptr");
         }
     }
Member Function Documentation
apply()
void souffle::ram::AbstractExistenceCheck::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 72 of file AbstractExistenceCheck.h.
References souffle::map(), relationRef, and values.
{
         relationRef = map(std::move(relationRef));
         for (auto& val : values) {
             val = map(std::move(val));
         }
     }
equal()
bool souffle::ram::AbstractExistenceCheck::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 93 of file AbstractExistenceCheck.h.
References souffle::equal_ptr(), souffle::equal_targets(), relationRef, and values.
{
         const auto& other = static_cast<const AbstractExistenceCheck&>(node);
         return equal_ptr(relationRef, other.relationRef) && equal_targets(values, other.values);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::AbstractExistenceCheck::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 64 of file AbstractExistenceCheck.h.
References relationRef, and values.
{
         std::vector<const Node*> res = {relationRef.get()};
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
getRelation()
const Relation& souffle::ram::AbstractExistenceCheck::getRelation () const inline
Get relation.
Definition at line 51 of file AbstractExistenceCheck.h.
References relationRef.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), and print().
{
         return *relationRef->get();
     }
getValues()
const std::vector<Expression*> souffle::ram::AbstractExistenceCheck::getValues () const inline
Get arguments of the tuple/pattern A null pointer element in the vector denotes an unspecified pattern for a tuple element.
Definition at line 60 of file AbstractExistenceCheck.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), souffle::ram::analysis::IndexAnalysis::isTotalSignature(), and souffle::NodeGenerator::visitExistenceCheck().
{
         return toPtrVector(values);
     }
print()
void souffle::ram::AbstractExistenceCheck::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Reimplemented in souffle::ram::ProvenanceExistenceCheck.
Definition at line 80 of file AbstractExistenceCheck.h.
References souffle::ram::Relation::getName(), getRelation(), souffle::join(), and values.
Referenced by souffle::ram::ProvenanceExistenceCheck::print().
{
         os << "("
            << join(values, ",",
                       [](std::ostream& out, const Own<Expression>& value) {
                           if (!value) {
                               out << "_";
                           } else {
                               out << *value;
                           }
                       })
            << ") ∈ " << getRelation().getName();
     }
Field Documentation
relationRef
Own<RelationReference> souffle::ram::AbstractExistenceCheck::relationRef protected
Relation.
Definition at line 99 of file AbstractExistenceCheck.h.
Referenced by AbstractExistenceCheck(), apply(), souffle::ram::ProvenanceExistenceCheck::clone(), souffle::ram::ExistenceCheck::clone(), equal(), getChildNodes(), and getRelation().
values
VecOwn<Expression> souffle::ram::AbstractExistenceCheck::values protected
Pattern – nullptr if undefined.
Definition at line 102 of file AbstractExistenceCheck.h.
Referenced by AbstractExistenceCheck(), apply(), souffle::ram::ProvenanceExistenceCheck::clone(), souffle::ram::ExistenceCheck::clone(), equal(), getChildNodes(), getValues(), and print().
The documentation for this class was generated from the following file:
ram/AbstractExistenceCheck.h