souffle: souffle::ram::NestedOperation Class Reference
souffle::ram::NestedOperation Class Reference abstract
Abstract class for a nesting operations in a loop-nest.
#include <NestedOperation.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
NestedOperation * clone () const override=0
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for a nesting operations in a loop-nest.
In the following example, the nested operation of "IF C1" is "IF C2":
QUERY
 ...
  IF C1
   IF C2
    ...
TODO (b-scholz): profile text is awkward; perhaps there is a better way of storing profile information for RAM operations since it is not always used for all RAM operations.
Definition at line 48 of file NestedOperation.h.
Constructor & Destructor Documentation
NestedOperation()
souffle::ram::NestedOperation::NestedOperation (Own< Operation > nested, std::string profileText = "") inline
Definition at line 50 of file NestedOperation.h.
References clone(), and nestedOperation.
             : nestedOperation(std::move(nested)), profileText(std::move(profileText)) {
         assert(nestedOperation != nullptr);
     }
Member Function Documentation
apply()
void souffle::ram::NestedOperation::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Reimplemented in souffle::ram::UnpackRecord, and souffle::ram::RelationOperation.
Definition at line 71 of file NestedOperation.h.
References souffle::map(), and nestedOperation.
Referenced by souffle::ram::RelationOperation::apply(), souffle::ram::AbstractConditional::apply(), souffle::ram::UnpackRecord::apply(), souffle::ram::NestedIntrinsicOperator::apply(), and souffle::ram::transform::HoistConditionsTransformer::hoistConditions().
{
         nestedOperation = map(std::move(nestedOperation));
     }
clone()
NestedOperation* souffle::ram::NestedOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Operation.
Implemented in souffle::ram::IndexOperation, souffle::ram::IndexChoice, souffle::ram::NestedIntrinsicOperator, souffle::ram::UnpackRecord, souffle::ram::Choice, souffle::ram::Aggregate, souffle::ram::ParallelIndexChoice, souffle::ram::IndexAggregate, souffle::ram::ParallelIndexScan, souffle::ram::ParallelAggregate, souffle::ram::IndexScan, souffle::ram::ParallelIndexAggregate, souffle::ram::ParallelChoice, souffle::ram::ParallelScan, souffle::ram::Break, souffle::ram::Filter, souffle::ram::Scan, souffle::ram::RelationOperation, souffle::ram::AbstractConditional, and souffle::ram::TupleOperation.
Referenced by NestedOperation().
equal()
bool souffle::ram::NestedOperation::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Reimplemented in souffle::ram::UnpackRecord, souffle::ram::RelationOperation, and souffle::ram::TupleOperation.
Definition at line 80 of file NestedOperation.h.
References souffle::equal_ptr(), nestedOperation, and profileText.
Referenced by souffle::ram::TupleOperation::equal(), and souffle::ram::AbstractConditional::equal().
{
         const auto& other = static_cast<const NestedOperation&>(node);
         return equal_ptr(nestedOperation, other.nestedOperation) && profileText == other.profileText;
     }
getChildNodes()
std::vector<const Node*> souffle::ram::NestedOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Reimplemented in souffle::ram::UnpackRecord, souffle::ram::RelationOperation, and souffle::ram::TupleOperation.
Definition at line 67 of file NestedOperation.h.
References nestedOperation.
Referenced by souffle::ram::TupleOperation::getChildNodes(), and souffle::ram::AbstractConditional::getChildNodes().
{
         return {nestedOperation.get()};
     }
getOperation()
Operation& souffle::ram::NestedOperation::getOperation () const inline
Get nested operation.
Definition at line 58 of file NestedOperation.h.
References nestedOperation.
Referenced by souffle::ram::Scan::clone(), souffle::ram::Break::clone(), souffle::ram::Filter::clone(), souffle::ram::ParallelScan::clone(), souffle::ram::ParallelChoice::clone(), souffle::ram::IndexScan::clone(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::ParallelAggregate::clone(), souffle::ram::ParallelIndexScan::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::Aggregate::clone(), souffle::ram::Choice::clone(), souffle::ram::UnpackRecord::clone(), souffle::ram::IndexChoice::clone(), souffle::ram::IndexOperation::clone(), souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), souffle::ram::transform::MakeIndexTransformer::rewriteScan(), souffle::NodeGenerator::visitNestedOperation(), and souffle::NodeGenerator::visitTupleOperation().
{
         return *nestedOperation;
     }
getProfileText()
const std::string& souffle::ram::NestedOperation::getProfileText () const inline
Get profile text.
Definition at line 63 of file NestedOperation.h.
References profileText.
Referenced by souffle::ram::Scan::clone(), souffle::ram::Filter::clone(), souffle::ram::Break::clone(), souffle::ram::ParallelScan::clone(), souffle::ram::ParallelChoice::clone(), souffle::ram::IndexScan::clone(), souffle::ram::ParallelIndexScan::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::Choice::clone(), souffle::ram::IndexChoice::clone(), souffle::ram::IndexOperation::clone(), souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::synthesiser::Synthesiser::emitCode(), souffle::InterpreterEngine::executeMain(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteScan().
{
         return profileText;
     }
print()
void souffle::ram::NestedOperation::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Reimplemented in souffle::ram::UnpackRecord, souffle::ram::ParallelIndexChoice, souffle::ram::ParallelIndexScan, souffle::ram::ParallelIndexAggregate, souffle::ram::ParallelAggregate, souffle::ram::ParallelChoice, souffle::ram::ParallelScan, and souffle::ram::Scan.
Definition at line 76 of file NestedOperation.h.
References nestedOperation, and souffle::ram::Operation::print().
Referenced by souffle::ram::Scan::print(), souffle::ram::Filter::print(), souffle::ram::Break::print(), souffle::ram::ParallelScan::print(), souffle::ram::ParallelChoice::print(), souffle::ram::ParallelAggregate::print(), souffle::ram::IndexScan::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::ParallelIndexScan::print(), souffle::ram::Aggregate::print(), souffle::ram::Choice::print(), souffle::ram::ParallelIndexChoice::print(), souffle::ram::IndexAggregate::print(), souffle::ram::UnpackRecord::print(), souffle::ram::NestedIntrinsicOperator::print(), and souffle::ram::IndexChoice::print().
{
         Operation::print(nestedOperation.get(), os, tabpos);
     }
Field Documentation
nestedOperation
Own<Operation> souffle::ram::NestedOperation::nestedOperation protected
Nested operation.
Definition at line 86 of file NestedOperation.h.
Referenced by apply(), equal(), getChildNodes(), souffle::ram::Choice::getChildNodes(), getOperation(), NestedOperation(), and print().
profileText
const std::string souffle::ram::NestedOperation::profileText protected
Text used by the profiler.
Definition at line 89 of file NestedOperation.h.
Referenced by equal(), and getProfileText().
The documentation for this class was generated from the following file:
ram/NestedOperation.h