souffle: souffle::ast::transform::ComponentChecker Class Reference
souffle::ast::transform::ComponentChecker Class Reference
#include <ComponentChecker.h>
Public Member Functions
ComponentChecker * clone () const override
std::string getName () const override
~ComponentChecker () override=default
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static void checkComponent (ErrorReport &report, const Component *enclosingComponent, const analysis::ComponentLookupAnalysis &componentLookup, const Component &component, const analysis::TypeBinding &binding)
static void checkComponentInit (ErrorReport &report, const Component *enclosingComponent, const analysis::ComponentLookupAnalysis &componentLookup, const ComponentInit &init, const analysis::TypeBinding &binding)
static const Component * checkComponentNameReference (ErrorReport &report, const Component *enclosingComponent, const analysis::ComponentLookupAnalysis &componentLookup, const std::string &name, const SrcLocation &loc, const analysis::TypeBinding &binding)
static void checkComponentNamespaces (ErrorReport &report, const Program &program)
static void checkComponentReference (ErrorReport &report, const Component *enclosingComponent, const analysis::ComponentLookupAnalysis &componentLookup, const ast::ComponentType &type, const SrcLocation &loc, const analysis::TypeBinding &binding)
static void checkComponents (ErrorReport &report, const Program &program, const analysis::ComponentLookupAnalysis &componentLookup)
Detailed Description
Definition at line 32 of file ComponentChecker.h.
Constructor & Destructor Documentation
~ComponentChecker()
souffle::ast::transform::ComponentChecker::~ComponentChecker () override default
Member Function Documentation
checkComponent()
void souffle::ast::transform::ComponentChecker::checkComponent (ErrorReport & report, const Component * enclosingComponent, const analysis::ComponentLookupAnalysis & componentLookup, const Component & component, const analysis::TypeBinding & binding) static private
Definition at line 102 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), base, souffle::ast::analysis::TypeBinding::extend(), souffle::ast::Component::getBaseComponents(), souffle::ast::analysis::ComponentLookupAnalysis::getComponent(), souffle::ast::Component::getComponents(), souffle::ast::Component::getComponentType(), souffle::ast::Component::getInstantiations(), souffle::ast::ComponentType::getName(), souffle::ast::Component::getOverridden(), souffle::ast::Component::getRelations(), souffle::ast::Node::getSrcLoc(), souffle::ast::ComponentType::getTypeParameters(), souffle::OVERRIDABLE, and relation.
Referenced by clone().
{
     // -- inheritance --
     // Update type binding:
     // Since we are not compiling, i.e. creating concrete instance of the
     // components with type parameters, we are only interested in whether
     // component references refer to existing components or some type parameter.
     // Type parameter for us here is unknown type that will be bound at the template
     // instantiation time.
     auto parentTypeParameters = component.getComponentType()->getTypeParameters();
     std::vector<QualifiedName> actualParams(parentTypeParameters.size(), "<type parameter>");
     TypeBinding activeBinding = binding.extend(parentTypeParameters, actualParams);
     // check parents of component
     for (const auto& cur : component.getBaseComponents()) {
         checkComponentReference(
                 report, enclosingComponent, componentLookup, *cur, component.getSrcLoc(), activeBinding);
         // Note: type parameters can also be atomic types like number, or anything defined through .type
         // The original semantic check permitted any identifier (existing or non-existing) to be actual
         // parameter
         // In order to maintain the compatibility, we do not check the actual parameters
         // for (const std::string& param : cur.getTypeParameters()) {
         //    checkComponentNameReference(report, scope, param, component.getSrcLoc(), activeBinding);
         //}
     }
     // get all parents
     std::set<const Component*> parents;
     std::function<void(const Component&)> collectParents = [&](const Component& cur) {
         for (const auto& base : cur.getBaseComponents()) {
             auto c = componentLookup.getComponent(enclosingComponent, base->getName(), binding);
             if (c == nullptr) {
                 continue;
             }
             if (parents.insert(c).second) {
                 collectParents(*c);
             }
         }
     };
     collectParents(component);
     // check overrides
     for (const Relation* relation : component.getRelations()) {
         if (component.getOverridden().count(relation->getQualifiedName().getQualifiers()[0]) != 0u) {
             report.addError("Override of non-inherited relation " +
                                     relation->getQualifiedName().getQualifiers()[0] + " in component " +
                                     component.getComponentType()->getName(),
                     component.getSrcLoc());
         }
     }
     for (const Component* parent : parents) {
         for (const Relation* relation : parent->getRelations()) {
             if ((component.getOverridden().count(relation->getQualifiedName().getQualifiers()[0]) != 0u) &&
                     !relation->hasQualifier(RelationQualifier::OVERRIDABLE)) {
                 report.addError("Override of non-overridable relation " +
                                         relation->getQualifiedName().getQualifiers()[0] + " in component " +
                                         component.getComponentType()->getName(),
                         component.getSrcLoc());
             }
         }
     }
     // check for a cycle
     if (parents.find(&component) != parents.end()) {
         report.addError(
                 "Invalid cycle in inheritance for component " + component.getComponentType()->getName(),
                 component.getSrcLoc());
     }
     // -- nested components --
     // check nested components
     for (const auto& cur : component.getComponents()) {
         checkComponent(report, &component, componentLookup, *cur, activeBinding);
     }
     // check nested instantiations
     for (const auto& cur : component.getInstantiations()) {
         checkComponentInit(report, &component, componentLookup, *cur, activeBinding);
     }
 }
checkComponentInit()
void souffle::ast::transform::ComponentChecker::checkComponentInit (ErrorReport & report, const Component * enclosingComponent, const analysis::ComponentLookupAnalysis & componentLookup, const ComponentInit & init, const analysis::TypeBinding & binding) static private
Definition at line 85 of file ComponentChecker.cpp.
References souffle::ast::ComponentInit::getComponentType(), and souffle::ast::Node::getSrcLoc().
Referenced by clone().
{
     checkComponentReference(
             report, enclosingComponent, componentLookup, *init.getComponentType(), init.getSrcLoc(), binding);
     // Note: actual parameters can be atomic types like number, or anything declared with .type
     // The original semantic check permitted any identifier (existing or non-existing) to be actual parameter
     // In order to maintain the compatibility, we do not check the actual parameters
     // check the actual parameters:
     // const auto& actualParams = init.getComponentType().getTypeParameters();
     // for (const auto& param : actualParams) {
     //    checkComponentNameReference(report, scope, param, init.getSrcLoc(), binding);
     //}
 }
checkComponentNameReference()
const Component * souffle::ast::transform::ComponentChecker::checkComponentNameReference (ErrorReport & report, const Component * enclosingComponent, const analysis::ComponentLookupAnalysis & componentLookup, const std::string & name, const SrcLocation & loc, const analysis::TypeBinding & binding) static private
Definition at line 50 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::QualifiedName::empty(), souffle::ast::analysis::TypeBinding::find(), and souffle::ast::analysis::ComponentLookupAnalysis::getComponent().
Referenced by clone().
{
     const QualifiedName& forwarded = binding.find(name);
     if (!forwarded.empty()) {
         // for forwarded types we do not check anything, because we do not know
         // what the actual type will be
         return nullptr;
     }
     const Component* c = componentLookup.getComponent(enclosingComponent, name, binding);
     if (c == nullptr) {
         report.addError("Referencing undefined component " + name, loc);
         return nullptr;
     }
     return c;
 }
checkComponentNamespaces()
void souffle::ast::transform::ComponentChecker::checkComponentNamespaces (ErrorReport & report, const Program & program) static private
Definition at line 200 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Program::getComponentInstantiations(), souffle::ast::Program::getComponents(), souffle::ast::Program::getRelations(), souffle::ast::Program::getTypes(), and souffle::toString().
Referenced by clone().
{
     std::map<std::string, SrcLocation> names;
     // Type and relation name error reporting performed by the SemanticChecker instead
     // Find all names and report redeclarations as we go.
     for (const auto& type : program.getTypes()) {
         const std::string name = toString(type->getQualifiedName());
         if (names.count(name) == 0u) {
             names[name] = type->getSrcLoc();
         }
     }
     for (const auto& rel : program.getRelations()) {
         const std::string name = toString(rel->getQualifiedName());
         if (names.count(name) == 0u) {
             names[name] = rel->getSrcLoc();
         }
     }
     // Note: Nested component and instance names are not obtained.
     for (const auto& comp : program.getComponents()) {
         const std::string name = toString(comp->getComponentType()->getName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on component " + name, comp->getSrcLoc());
         } else {
             names[name] = comp->getSrcLoc();
         }
     }
     for (const auto& inst : program.getComponentInstantiations()) {
         const std::string name = toString(inst->getInstanceName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on instantiation " + name, inst->getSrcLoc());
         } else {
             names[name] = inst->getSrcLoc();
         }
     }
 }
checkComponentReference()
void souffle::ast::transform::ComponentChecker::checkComponentReference (ErrorReport & report, const Component * enclosingComponent, const analysis::ComponentLookupAnalysis & componentLookup, const ast::ComponentType & type, const SrcLocation & loc, const analysis::TypeBinding & binding) static private
Definition at line 69 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Component::getComponentType(), souffle::ast::ComponentType::getName(), and souffle::ast::ComponentType::getTypeParameters().
Referenced by clone().
{
     // check whether targeted component exists
     const Component* c = checkComponentNameReference(
             report, enclosingComponent, componentLookup, type.getName(), loc, binding);
     if (c == nullptr) {
         return;
     }
     // check number of type parameters
     if (c->getComponentType()->getTypeParameters().size() != type.getTypeParameters().size()) {
         report.addError("Invalid number of type parameters for component " + type.getName(), loc);
     }
 }
checkComponents()
void souffle::ast::transform::ComponentChecker::checkComponents (ErrorReport & report, const Program & program, const analysis::ComponentLookupAnalysis & componentLookup) static private
Definition at line 188 of file ComponentChecker.cpp.
References souffle::ast::Program::getComponentInstantiations(), and souffle::ast::Program::getComponents().
Referenced by clone().
{
     for (Component* cur : program.getComponents()) {
         checkComponent(report, nullptr, componentLookup, *cur, TypeBinding());
     }
     for (ComponentInit* cur : program.getComponentInstantiations()) {
         checkComponentInit(report, nullptr, componentLookup, *cur, TypeBinding());
     }
 }
clone()
ComponentChecker* souffle::ast::transform::ComponentChecker::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 40 of file ComponentChecker.h.
References checkComponent(), checkComponentInit(), checkComponentNameReference(), checkComponentNamespaces(), checkComponentReference(), checkComponents(), and transform().
{
         return new ComponentChecker();
     }
getName()
std::string souffle::ast::transform::ComponentChecker::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file ComponentChecker.h.
{
         return "ComponentChecker";
     }
transform()
bool souffle::ast::transform::ComponentChecker::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 41 of file ComponentChecker.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getErrorReport(), and souffle::ast::TranslationUnit::getProgram().
Referenced by clone().
{
     Program& program = translationUnit.getProgram();
     ComponentLookupAnalysis& componentLookup = *translationUnit.getAnalysis<ComponentLookupAnalysis>();
     ErrorReport& report = translationUnit.getErrorReport();
     checkComponents(report, program, componentLookup);
     checkComponentNamespaces(report, program);
     return false;
 }
The documentation for this class was generated from the following files:
ast/transform/ComponentChecker.h
ast/transform/ComponentChecker.cpp