souffle: souffle::ram::Statement Class Reference
souffle::ram::Statement Class Reference abstract
Abstract class for RAM statements.
#include <Statement.h>
Public Member Functions
Statement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Node
virtual bool equal (const Node &) const
Equality check for two RAM nodes.
Static Protected Member Functions
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Friends
class Program
Detailed Description
Abstract class for RAM statements.
Definition at line 30 of file Statement.h.
Member Function Documentation
clone()
Statement* souffle::ram::Statement::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Node.
Implemented in souffle::ram::LogRelationTimer, souffle::ram::Query, souffle::ram::Exit, souffle::ram::LogTimer, souffle::ram::Loop, souffle::ram::IO, souffle::ram::Parallel, souffle::ram::Extend, souffle::ram::DebugInfo, souffle::ram::Call, souffle::ram::Clear, souffle::ram::LogSize, souffle::ram::Swap, and souffle::ram::Sequence.
print() [1/3]
void souffle::ram::Statement::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 35 of file Statement.h.
Referenced by print(), souffle::ram::Sequence::print(), souffle::ram::DebugInfo::print(), souffle::ram::Parallel::print(), souffle::ram::Loop::print(), souffle::ram::LogTimer::print(), and souffle::ram::LogRelationTimer::print().
{
         print(os, 0);
     }
print() [2/3]
virtual void souffle::ram::Statement::print (std::ostream & os, int tabpos) const protected pure virtual
Pretty print with indentation.
Implemented in souffle::ram::LogRelationTimer, souffle::ram::Query, souffle::ram::Exit, souffle::ram::LogTimer, souffle::ram::Loop, souffle::ram::Parallel, souffle::ram::DebugInfo, souffle::ram::Extend, souffle::ram::IO, souffle::ram::Call, souffle::ram::Clear, souffle::ram::Sequence, souffle::ram::LogSize, and souffle::ram::Swap.
print() [3/3]
static void souffle::ram::Statement::print (const Statement * statement, std::ostream & os, int tabpos) inline static protected
Pretty print jump-bed.
Definition at line 42 of file Statement.h.
References print().
{
         assert(statement != nullptr && "statement is a null-pointer");
         statement->print(os, tabpos);
     }
Friends And Related Function Documentation
Program
friend class Program friend
Definition at line 47 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h