souffle: souffle::ram::Operation Class Reference
souffle::ram::Operation Class Reference abstract
Abstract class for a relational algebra operation.
#include <Operation.h>
Public Member Functions
Operation * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Node
virtual bool equal (const Node &) const
Equality check for two RAM nodes.
Static Protected Member Functions
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Friends
class Query
Detailed Description
Abstract class for a relational algebra operation.
Definition at line 28 of file Operation.h.
Member Function Documentation
clone()
Operation* souffle::ram::Operation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Node.
Implemented in souffle::ram::IndexOperation, souffle::ram::IndexChoice, souffle::ram::NestedIntrinsicOperator, souffle::ram::Project, souffle::ram::UnpackRecord, souffle::ram::Choice, souffle::ram::Aggregate, souffle::ram::SubroutineReturn, souffle::ram::ParallelIndexChoice, souffle::ram::IndexAggregate, souffle::ram::ParallelIndexScan, souffle::ram::ParallelAggregate, souffle::ram::IndexScan, souffle::ram::NestedOperation, souffle::ram::ParallelIndexAggregate, souffle::ram::ParallelChoice, souffle::ram::ParallelScan, souffle::ram::Break, souffle::ram::Filter, souffle::ram::Scan, souffle::ram::RelationOperation, souffle::ram::AbstractConditional, and souffle::ram::TupleOperation.
Referenced by souffle::ram::transform::IfConversionTransformer::rewriteIndexScan().
print() [1/3]
void souffle::ram::Operation::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 33 of file Operation.h.
Referenced by print(), and souffle::ram::NestedOperation::print().
{
         print(os, 0);
     }
print() [2/3]
virtual void souffle::ram::Operation::print (std::ostream & os, int tabpos) const protected pure virtual
Pretty print with indentation.
Implemented in souffle::ram::IndexChoice, souffle::ram::NestedIntrinsicOperator, souffle::ram::Project, souffle::ram::UnpackRecord, souffle::ram::IndexAggregate, souffle::ram::SubroutineReturn, souffle::ram::ParallelIndexChoice, souffle::ram::NestedOperation, souffle::ram::Aggregate, souffle::ram::Choice, souffle::ram::ParallelIndexScan, souffle::ram::ParallelIndexAggregate, souffle::ram::IndexScan, souffle::ram::ParallelAggregate, souffle::ram::ParallelChoice, souffle::ram::ParallelScan, souffle::ram::Break, souffle::ram::Filter, and souffle::ram::Scan.
print() [3/3]
static void souffle::ram::Operation::print (const Operation * operation, std::ostream & os, int tabpos) inline static protected
Pretty print jump-bed.
Definition at line 40 of file Operation.h.
References print().
{
         operation->print(os, tabpos);
     }
Friends And Related Function Documentation
Query
friend class Query friend
Definition at line 44 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h