souffle: souffle::ram::transform::ExpandFilterTransformer Class Reference
souffle::ram::transform::ExpandFilterTransformer Class Reference
Transforms Conjunctions into consecutive filter operations.
#include <ExpandFilter.h>
Public Member Functions
bool expandFilters (Program &program)
Expand filter operations.
std::string getName () const override
get name of the transformer
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transforms Conjunctions into consecutive filter operations.
For example ..
QUERY
 ...
  IF C1 /\ C2 then
   ...
will be rewritten to
QUERY
 ...
  IF C1
   IF C2
    ...
Definition at line 48 of file ExpandFilter.h.
Member Function Documentation
expandFilters()
bool souffle::ram::transform::ExpandFilterTransformer::expandFilters (Program & program)
Expand filter operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 33 of file ExpandFilter.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::clone(), souffle::filter(), souffle::ram::makeLambdaRamMapper(), souffle::ram::toConjunctionList(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> filterRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const Filter* filter = dynamic_cast<Filter*>(node.get())) {
                 const Condition* condition = &filter->getCondition();
                 VecOwn<Condition> conditionList = toConjunctionList(condition);
                 if (conditionList.size() > 1) {
                     changed = true;
                     VecOwn<Filter> filters;
                     for (auto& cond : conditionList) {
                         if (filters.empty()) {
                             filters.emplace_back(mk<Filter>(
                                     souffle::clone(cond), souffle::clone(&filter->getOperation())));
                         } else {
                             filters.emplace_back(mk<Filter>(souffle::clone(cond), std::move(filters.back())));
                         }
                     }
                     node = std::move(filters.back());
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ram::transform::ExpandFilterTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 50 of file ExpandFilter.h.
References expandFilters().
{
         return "ExpandFilterTransformer";
     }
transform()
bool souffle::ram::transform::ExpandFilterTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 62 of file ExpandFilter.h.
References expandFilters(), and souffle::ram::TranslationUnit::getProgram().
{
         return expandFilters(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/ExpandFilter.h
ram/transform/ExpandFilter.cpp