souffle: souffle::ast::Pragma Class Reference
souffle::ast::Pragma Class Reference
Representation of a global option.
#include <Pragma.h>
Public Member Functions
Pragma * clone () const override
Create a clone (i.e.
std::pair< std::string, std::string > getkvp () const
Pragma (std::string key, std::string value, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::string key
Name of the key.
std::string value
Value.
Detailed Description
Representation of a global option.
Definition at line 31 of file Pragma.h.
Constructor & Destructor Documentation
Pragma()
souffle::ast::Pragma::Pragma (std::string key, std::string value, SrcLocation loc = {}) inline
Definition at line 33 of file Pragma.h.
References key, souffle::ast::Node::Node(), and value.
Referenced by clone().
                                                              {})
             : Node(std::move(loc)), key(std::move(key)), value(std::move(value)) {}
Member Function Documentation
clone()
Pragma* souffle::ast::Pragma::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 36 of file Pragma.h.
References souffle::ast::Node::getSrcLoc(), and Pragma().
{
         return new Pragma(key, value, getSrcLoc());
     }
equal()
bool souffle::ast::Pragma::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 50 of file Pragma.h.
References key, and value.
{
         const auto& other = static_cast<const Pragma&>(node);
         return other.key == key && other.value == value;
     }
getkvp()
std::pair<std::string, std::string> souffle::ast::Pragma::getkvp () const inline
Definition at line 41 of file Pragma.h.
References key, and value.
Referenced by souffle::ast::transform::PragmaChecker::transform().
{
         return std::pair<std::string, std::string>(key, value);
     }
print()
void souffle::ast::Pragma::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 46 of file Pragma.h.
{
         os << ".pragma " << key << " " << value << "\n";
     }
Field Documentation
key
std::string souffle::ast::Pragma::key protected
Name of the key.
Definition at line 56 of file Pragma.h.
Referenced by equal(), getkvp(), and Pragma().
value
std::string souffle::ast::Pragma::value protected
Value.
Definition at line 59 of file Pragma.h.
Referenced by equal(), getkvp(), and Pragma().
The documentation for this class was generated from the following file:
ast/Pragma.h