souffle: souffle::ram::Aggregate Class Reference
souffle::ram::Aggregate Class Reference
Aggregation function applied on some relation.
#include <Aggregate.h>
Public Member Functions
Aggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, int ident)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Aggregate * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractAggregate
AbstractAggregate (AggregateOp fun, Own< Expression > expr, Own< Condition > cond)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Get condition.
const Expression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
virtual ~AbstractAggregate ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractAggregate
bool equal (const Node &node) const
void print (std::ostream &os, int) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractAggregate
Own< Condition > condition
Aggregation tuple condition.
Own< Expression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Aggregation function applied on some relation.
For example:
t0.0 = COUNT FOR ALL t0 IN A
Applies the function COUNT to determine the number of elements in A.
Definition at line 49 of file Aggregate.h.
Constructor & Destructor Documentation
Aggregate()
souffle::ram::Aggregate::Aggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, int ident) inline
Definition at line 51 of file Aggregate.h.
Referenced by clone().
             : RelationOperation(std::move(relRef), ident, std::move(nested)),
               AbstractAggregate(fun, std::move(expression), std::move(condition)) {}
Member Function Documentation
apply()
void souffle::ram::Aggregate::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 68 of file Aggregate.h.
References souffle::ram::RelationOperation::apply(), souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::expression, and souffle::map().
{
         RelationOperation::apply(map);
         condition = map(std::move(condition));
         expression = map(std::move(expression));
     }
clone()
Aggregate* souffle::ram::Aggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::RelationOperation.
Reimplemented in souffle::ram::ParallelAggregate.
Definition at line 63 of file Aggregate.h.
References Aggregate(), souffle::clone(), souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::expression, souffle::ram::NestedOperation::getOperation(), souffle::ram::TupleOperation::getTupleId(), and souffle::ram::RelationOperation::relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new Aggregate(souffle::clone(&getOperation()), function, souffle::clone(relationRef),
                 souffle::clone(expression), souffle::clone(condition), getTupleId());
     }
equal()
bool souffle::ram::Aggregate::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 87 of file Aggregate.h.
References souffle::ram::RelationOperation::equal(), and souffle::ram::AbstractAggregate::equal().
{
         const auto& other = static_cast<const Aggregate&>(node);
         return RelationOperation::equal(other) && AbstractAggregate::equal(node);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Aggregate::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 56 of file Aggregate.h.
References souffle::ram::RelationOperation::getChildNodes(), and souffle::ram::AbstractAggregate::getChildNodes().
{
         auto res = RelationOperation::getChildNodes();
         auto children = AbstractAggregate::getChildNodes();
         res.insert(res.end(), children.begin(), children.end());
         return res;
     }
print()
void souffle::ram::Aggregate::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Reimplemented in souffle::ram::ParallelAggregate.
Definition at line 75 of file Aggregate.h.
References souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::getCondition(), souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::isTrue(), souffle::ram::AbstractAggregate::print(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "t" << getTupleId() << ".0=";
         AbstractAggregate::print(os, tabpos);
         os << "FOR ALL t" << getTupleId() << "  " << getRelation().getName();
         if (!isTrue(condition.get())) {
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         RelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Aggregate.h