souffle: souffle::ram::AbstractAggregate Class Reference
souffle::ram::AbstractAggregate Class Reference
Abstract class for aggregation.
#include <AbstractAggregate.h>
Public Member Functions
AbstractAggregate (AggregateOp fun, Own< Expression > expr, Own< Condition > cond)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Get condition.
const Expression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
virtual ~AbstractAggregate ()=default
Protected Member Functions
bool equal (const Node &node) const
void print (std::ostream &os, int) const
Protected Attributes
Own< Condition > condition
Aggregation tuple condition.
Own< Expression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Abstract class for aggregation.
A particular function (e.g. MIN) is applied given a that a condition holds
Definition at line 38 of file AbstractAggregate.h.
Constructor & Destructor Documentation
AbstractAggregate()
souffle::ram::AbstractAggregate::AbstractAggregate (AggregateOp fun, Own< Expression > expr, Own< Condition > cond) inline
Definition at line 40 of file AbstractAggregate.h.
References condition, expression, and ~AbstractAggregate().
             : function(fun), expression(std::move(expr)), condition(std::move(cond)) {
         assert(condition != nullptr && "Condition is a null-pointer");
         assert(expression != nullptr && "Expression is a null-pointer");
     }
~AbstractAggregate()
virtual souffle::ram::AbstractAggregate::~AbstractAggregate () virtual default
Referenced by AbstractAggregate().
Member Function Documentation
equal()
bool souffle::ram::AbstractAggregate::equal (const Node & node) const inline protected
Definition at line 90 of file AbstractAggregate.h.
References condition, souffle::equal_ptr(), expression, and function.
Referenced by souffle::ram::Aggregate::equal(), and souffle::ram::IndexAggregate::equal().
{
         const auto& other = dynamic_cast<const AbstractAggregate&>(node);
         return function == other.function && equal_ptr(expression, other.expression) &&
                equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::AbstractAggregate::getChildNodes () const inline
Definition at line 65 of file AbstractAggregate.h.
References condition, and expression.
Referenced by souffle::ram::IndexAggregate::getChildNodes(), and souffle::ram::Aggregate::getChildNodes().
{
         return {expression.get(), condition.get()};
     }
getCondition()
const Condition& souffle::ram::AbstractAggregate::getCondition () const inline
Get condition.
Definition at line 49 of file AbstractAggregate.h.
References condition.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::ParallelAggregate::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::Aggregate::print(), souffle::ram::IndexAggregate::print(), and souffle::ram::transform::MakeIndexTransformer::rewriteAggregate().
{
         assert(condition != nullptr && "Condition of aggregate is a null-pointer");
         return *condition;
     }
getExpression()
const Expression& souffle::ram::AbstractAggregate::getExpression () const inline
Get target expression.
Definition at line 60 of file AbstractAggregate.h.
References expression.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), and souffle::ram::transform::MakeIndexTransformer::rewriteAggregate().
{
         assert(expression != nullptr && "Expression of aggregate is a null-pointer");
         return *expression;
     }
getFunction()
AggregateOp souffle::ram::AbstractAggregate::getFunction () const inline
Get aggregation function.
Definition at line 55 of file AbstractAggregate.h.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::InterpreterEngine::executeAggregate(), and souffle::ram::transform::MakeIndexTransformer::rewriteAggregate().
{
         return function;
     }
print()
void souffle::ram::AbstractAggregate::print (std::ostream & os, int) const inline protected
Definition at line 70 of file AbstractAggregate.h.
References souffle::COUNT, expression, souffle::FMAX, souffle::FMIN, souffle::FSUM, souffle::MAX, souffle::MEAN, souffle::MIN, souffle::SUM, souffle::UMAX, souffle::UMIN, and souffle::USUM.
Referenced by souffle::ram::ParallelAggregate::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::Aggregate::print(), and souffle::ram::IndexAggregate::print().
{
         switch (function) {
             case AggregateOp::MIN:
             case AggregateOp::FMIN:
             case AggregateOp::UMIN: os << "min "; break;
             case AggregateOp::MAX:
             case AggregateOp::UMAX:
             case AggregateOp::FMAX: os << "max "; break;
             case AggregateOp::SUM:
             case AggregateOp::FSUM:
             case AggregateOp::USUM: os << "sum "; break;
             case AggregateOp::COUNT: os << "count "; break;
             case AggregateOp::MEAN: os << "mean "; break;
         }
         if (function != AggregateOp::COUNT) {
             os << *expression << " ";
         }
     }
Field Documentation
condition
Own<Condition> souffle::ram::AbstractAggregate::condition protected
Aggregation tuple condition.
Definition at line 103 of file AbstractAggregate.h.
Referenced by AbstractAggregate(), souffle::ram::Aggregate::apply(), souffle::ram::IndexAggregate::apply(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::ParallelAggregate::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::Aggregate::clone(), equal(), getChildNodes(), getCondition(), souffle::ram::ParallelAggregate::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::Aggregate::print(), and souffle::ram::IndexAggregate::print().
expression
Own<Expression> souffle::ram::AbstractAggregate::expression protected
Aggregation expression.
Definition at line 100 of file AbstractAggregate.h.
Referenced by AbstractAggregate(), souffle::ram::Aggregate::apply(), souffle::ram::IndexAggregate::apply(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::ParallelAggregate::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::Aggregate::clone(), equal(), getChildNodes(), getExpression(), and print().
function
AggregateOp souffle::ram::AbstractAggregate::function protected
Aggregation function.
Definition at line 97 of file AbstractAggregate.h.
Referenced by equal().
The documentation for this class was generated from the following file:
ram/AbstractAggregate.h