souffle: souffle::ast::analysis::SumTypeBranchesAnalysis Class Reference
souffle::ast::analysis::SumTypeBranchesAnalysis Class Reference
#include <SumTypeBranches.h>
Public Member Functions
const Type * getType (const std::string &branch) const
A type can be nullptr in case of a malformed program.
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
SumTypeBranchesAnalysis ()
const Type & unsafeGetType (const std::string &branch) const
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "sum-type-branches"
Private Attributes
std::map< std::string, const Type * > branchToType
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 28 of file SumTypeBranches.h.
Constructor & Destructor Documentation
SumTypeBranchesAnalysis()
souffle::ast::analysis::SumTypeBranchesAnalysis::SumTypeBranchesAnalysis () inline
Definition at line 32 of file SumTypeBranches.h.
References run().
 : Analysis(name) {}
Member Function Documentation
getType()
const Type* souffle::ast::analysis::SumTypeBranchesAnalysis::getType (const std::string & branch) const inline
A type can be nullptr in case of a malformed program.
Definition at line 39 of file SumTypeBranches.h.
References branchToType, and souffle::contains().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkBranchInits(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitBranchInit().
{
         if (contains(branchToType, branch)) {
             return branchToType.at(branch);
         } else {
             return nullptr;
         }
     }
run()
void souffle::ast::analysis::SumTypeBranchesAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 30 of file SumTypeBranches.cpp.
References branchToType, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::analysis::TypeEnvironment::getType(), souffle::ast::Program::getTypes(), souffle::ast::analysis::TypeEnvironment::isType(), and souffle::ast::visitDepthFirst().
Referenced by SumTypeBranchesAnalysis().
{
     const TypeEnvironment& env = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
     Program& program = tu.getProgram();
     visitDepthFirst(program.getTypes(), [&](const ast::AlgebraicDataType& adt) {
         auto typeName = adt.getQualifiedName();
         if (!env.isType(typeName)) return;
         for (auto& branch : adt.getBranches()) {
             branchToType[branch->getConstructor()] = &env.getType(typeName);
         }
     });
 }
unsafeGetType()
const Type& souffle::ast::analysis::SumTypeBranchesAnalysis::unsafeGetType (const std::string & branch) const inline
Definition at line 47 of file SumTypeBranches.h.
References branchToType.
Referenced by souffle::ast::transform::ADTtoRecordsTransformer::transform().
{
         return *branchToType.at(branch);
     }
Field Documentation
branchToType
std::map<std::string, const Type*> souffle::ast::analysis::SumTypeBranchesAnalysis::branchToType private
Definition at line 52 of file SumTypeBranches.h.
Referenced by getType(), run(), and unsafeGetType().
name
constexpr const char* souffle::ast::analysis::SumTypeBranchesAnalysis::name = "sum-type-branches" static
Definition at line 30 of file SumTypeBranches.h.
The documentation for this class was generated from the following files:
ast/analysis/SumTypeBranches.h
ast/analysis/SumTypeBranches.cpp