souffle: souffle::ast::analysis::TypeBinding Class Reference
souffle::ast::analysis::TypeBinding Class Reference
Class that encapsulates std::map of types binding that comes from .init c = Comp<MyType> Type binding in this example would be T->MyType if the component code is .comp Comp<T> ...
#include <ComponentLookup.h>
Public Member Functions
TypeBinding extend (const std::vector< QualifiedName > &formalParams, const std::vector< QualifiedName > &actualParams) const
const QualifiedName & find (const QualifiedName &name) const
Returns binding for given name or empty string if such binding does not exist.
Private Attributes
std::map< QualifiedName, QualifiedName > binding
Key value pair.
Detailed Description
Class that encapsulates std::map of types binding that comes from .init c = Comp<MyType> Type binding in this example would be T->MyType if the component code is .comp Comp<T> ...
Definition at line 33 of file ComponentLookup.h.
Member Function Documentation
extend()
TypeBinding souffle::ast::analysis::TypeBinding::extend (const std::vector< QualifiedName > & formalParams, const std::vector< QualifiedName > & actualParams) const inline
Definition at line 47 of file ComponentLookup.h.
References binding, and i.
Referenced by souffle::ast::transform::ComponentChecker::checkComponent().
{
         TypeBinding result;
         if (formalParams.size() != actualParams.size()) {
             return *this;  // invalid init => will trigger a semantic error
         }
         for (std::size_t i = 0; i < formalParams.size(); i++) {
             auto pos = binding.find(actualParams[i]);
             if (pos != binding.end()) {
                 result.binding[formalParams[i]] = pos->second;
             } else {
                 result.binding[formalParams[i]] = actualParams[i];
             }
         }
         return result;
     }
find()
const QualifiedName& souffle::ast::analysis::TypeBinding::find (const QualifiedName & name) const inline
Returns binding for given name or empty string if such binding does not exist.
Definition at line 38 of file ComponentLookup.h.
References binding.
Referenced by souffle::ast::transform::ComponentChecker::checkComponentNameReference(), and souffle::ast::analysis::ComponentLookupAnalysis::getComponent().
{
         const static QualifiedName unknown;
         auto pos = binding.find(name);
         if (pos == binding.end()) {
             return unknown;
         }
         return pos->second;
     }
Field Documentation
binding
std::map<QualifiedName, QualifiedName> souffle::ast::analysis::TypeBinding::binding private
Key value pair.
Keys are names that should be forwarded to value, which is the actual name. Example T->MyImplementation.
Definition at line 71 of file ComponentLookup.h.
Referenced by extend(), and find().
The documentation for this class was generated from the following file:
ast/analysis/ComponentLookup.h