souffle: souffle::ast::transform::ADTtoRecordsTransformer Class Reference
souffle::ast::transform::ADTtoRecordsTransformer Class Reference
#include <ADTtoRecords.h>
Public Member Functions
ADTtoRecordsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Definition at line 31 of file ADTtoRecords.h.
Member Function Documentation
clone()
ADTtoRecordsTransformer* souffle::ast::transform::ADTtoRecordsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 37 of file ADTtoRecords.h.
References transform().
{
         return new ADTtoRecordsTransformer();
     }
getName()
std::string souffle::ast::transform::ADTtoRecordsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 33 of file ADTtoRecords.h.
{
         return "ADTtoRecords";
     }
transform()
bool souffle::ast::transform::ADTtoRecordsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file ADTtoRecords.cpp.
References souffle::ast::Program::apply(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::analysis::SumTypeBranchesAnalysis::unsafeGetType().
Referenced by clone().
{
     struct ADTsFuneral : public NodeMapper {
         mutable bool changed{false};
         TranslationUnit& tu;
         const analysis::SumTypeBranchesAnalysis& sumTypesBranches =
                 *tu.getAnalysis<analysis::SumTypeBranchesAnalysis>();
         ADTsFuneral(TranslationUnit& tu) : tu(tu){};
         Own<Node> operator()(Own<Node> node) const override {
             // Rewrite sub-expressions first
             node->apply(*this);
             if (!isA<BranchInit>(node)) {
                 return node;
             }
             changed = true;
             auto& adt = *as<BranchInit>(node);
             auto& type = sumTypesBranches.unsafeGetType(adt.getConstructor());
             assert(isA<analysis::AlgebraicDataType>(type));
             auto& branches = as<analysis::AlgebraicDataType>(type)->getBranches();
             // Find branch ID.
             analysis::AlgebraicDataType::Branch searchDummy{adt.getConstructor(), {}};
             auto iterToBranch = std::lower_bound(branches.begin(), branches.end(), searchDummy,
                     [](const analysis::AlgebraicDataType::Branch& left,
                             const analysis::AlgebraicDataType::Branch& right) {
                         return left.name < right.name;
                     });
             // Branch id corresponds to the position in lexicographical ordering.
             auto branchID = std::distance(std::begin(branches), iterToBranch);
             // Collect branch arguments
             VecOwn<Argument> branchArguments;
             for (auto* arg : adt.getArguments()) {
                 branchArguments.emplace_back(arg->clone());
             }
             // Branch is stored either as [branch_id, [arguments]]
             // or [branch_id, argument] in case of a single argument.
             auto branchArgs = [&]() -> Own<ast::Argument> {
                 if (branchArguments.size() != 1) {
                     return mk<Argument, RecordInit>(std::move(branchArguments));
                 } else {
                     return std::move(branchArguments.at(0));
                 }
             }();
             // Arguments for the resulting record [branch_id, branch_args].
             VecOwn<Argument> finalRecordArgs;
             finalRecordArgs.push_back(mk<Argument, NumericConstant>(branchID));
             finalRecordArgs.push_back(std::move(branchArgs));
             return mk<RecordInit>(std::move(finalRecordArgs), adt.getSrcLoc());
         }
     };
     ADTsFuneral mapper(tu);
     tu.getProgram().apply(mapper);
     return mapper.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ADTtoRecords.h
ast/transform/ADTtoRecords.cpp