souffle: souffle::ast::transform::ExecutionPlanChecker Class Reference
souffle::ast::transform::ExecutionPlanChecker Class Reference
#include <ExecutionPlanChecker.h>
Public Member Functions
ExecutionPlanChecker * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Definition at line 25 of file ExecutionPlanChecker.h.
Member Function Documentation
clone()
ExecutionPlanChecker* souffle::ast::transform::ExecutionPlanChecker::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 31 of file ExecutionPlanChecker.h.
References transform().
{
         return new ExecutionPlanChecker();
     }
getName()
std::string souffle::ast::transform::ExecutionPlanChecker::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 27 of file ExecutionPlanChecker.h.
{
         return "ExecutionPlanChecker";
     }
transform()
bool souffle::ast::transform::ExecutionPlanChecker::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file ExecutionPlanChecker.cpp.
References souffle::Diagnostic::ERROR, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::getAtomRelation(), souffle::ast::getClauses(), souffle::ast::TranslationUnit::getErrorReport(), and souffle::ast::TranslationUnit::getProgram().
Referenced by clone().
{
     auto* relationSchedule = translationUnit.getAnalysis<analysis::RelationScheduleAnalysis>();
     auto* recursiveClauses = translationUnit.getAnalysis<analysis::RecursiveClausesAnalysis>();
     auto&& report = translationUnit.getErrorReport();
     Program& program = translationUnit.getProgram();
     for (const analysis::RelationScheduleAnalysisStep& step : relationSchedule->schedule()) {
         const std::set<const Relation*>& scc = step.computed();
         for (const Relation* rel : scc) {
             for (const Clause* clause : getClauses(program, *rel)) {
                 if (!recursiveClauses->recursive(clause)) {
                     continue;
                 }
                 if (clause->getExecutionPlan() == nullptr) {
                     continue;
                 }
                 int version = 0;
                 for (const auto* atom : getBodyLiterals<Atom>(*clause)) {
                     if (scc.count(getAtomRelation(atom, &program)) != 0u) {
                         version++;
                     }
                 }
                 int maxVersion = -1;
                 for (auto const& cur : clause->getExecutionPlan()->getOrders()) {
                     maxVersion = std::max(cur.first, maxVersion);
                 }
                 if (version <= maxVersion) {
                     for (const auto& cur : clause->getExecutionPlan()->getOrders()) {
                         if (cur.first >= version) {
                             report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR,
                                     DiagnosticMessage(
                                             "execution plan for version " + std::to_string(cur.first),
                                             cur.second->getSrcLoc()),
                                     {DiagnosticMessage("only versions 0.." + std::to_string(version - 1) +
                                                        " permitted")}));
                         }
                     }
                 }
             }
         }
     }
     return false;
 }
The documentation for this class was generated from the following files:
ast/transform/ExecutionPlanChecker.h
ast/transform/ExecutionPlanChecker.cpp