souffle: souffle::ram::Clear Class Reference
souffle::ram::Clear Class Reference
Delete tuples of a relation.
#include <Clear.h>
Public Member Functions
Clear (Own< RelationReference > relRef)
Clear * clone () const override
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::RelationStatement
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get RAM relation.
RelationStatement (Own< RelationReference > relRef)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationStatement
Own< RelationReference > relationRef
Relation reference.
Detailed Description
Delete tuples of a relation.
This retains the target relation, but cleans its content
For example:
CLEAR A
Definition at line 42 of file Clear.h.
Constructor & Destructor Documentation
Clear()
souffle::ram::Clear::Clear (Own< RelationReference > relRef) inline
Definition at line 44 of file Clear.h.
Referenced by clone().
 : RelationStatement(std::move(relRef)) {}
Member Function Documentation
clone()
Clear* souffle::ram::Clear::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 46 of file Clear.h.
References Clear(), souffle::clone(), and souffle::ram::RelationStatement::relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new Clear(souffle::clone(relationRef));
     }
print()
void souffle::ram::Clear::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 51 of file Clear.h.
References souffle::ram::Relation::getName(), souffle::ram::RelationStatement::getRelation(), and souffle::times().
{
         const Relation& rel = getRelation();
         os << times(" ", tabpos);
         os << "CLEAR ";
         os << rel.getName();
         os << std::endl;
     }
The documentation for this class was generated from the following file:
ram/Clear.h