souffle: souffle::ast::TranslationUnit Class Reference
souffle::ast::TranslationUnit Class Reference
Translation unit class for the translation pipeline.
#include <TranslationUnit.h>
Public Member Functions
template<class Analysis >
Analysis * getAnalysis () const
get analysis: analysis is generated on the fly if not present
DebugReport & getDebugReport ()
Return debug report.
ErrorReport & getErrorReport ()
Return error report.
Program & getProgram () const
Return the program.
void invalidateAnalyses ()
Destroy all cached analyses of translation unit.
TranslationUnit (Own< Program > program, ErrorReport &e, DebugReport &d)
virtual ~TranslationUnit ()=default
Private Attributes
std::map< std::string, Own< analysis::Analysis > > analyses
Cached analyses.
DebugReport & debugReport
HTML debug report.
ErrorReport & errorReport
Error report capturing errors while compiling.
Own< Program > program
AST program.
Detailed Description
Translation unit class for the translation pipeline.
The translation unit class consisting of an symbol table, AST program, error reports, and cached analysis results.
Definition at line 45 of file TranslationUnit.h.
Constructor & Destructor Documentation
TranslationUnit()
souffle::ast::TranslationUnit::TranslationUnit (Own< Program > program, ErrorReport & e, DebugReport & d) inline
Definition at line 47 of file TranslationUnit.h.
References ~TranslationUnit().
             : program(std::move(program)), errorReport(e), debugReport(d) {}
~TranslationUnit()
virtual souffle::ast::TranslationUnit::~TranslationUnit () virtual default
Referenced by TranslationUnit().
Member Function Documentation
getAnalysis()
template<class Analysis > Analysis* souffle::ast::TranslationUnit::getAnalysis () const inline
get analysis: analysis is generated on the fly if not present
Definition at line 54 of file TranslationUnit.h.
References souffle::DebugReport::addSection(), analyses, souffle::Global::config(), debugReport, and souffle::profile::ss.
Referenced by souffle::ast::analysis::RecursiveClausesAnalysis::computeIsRecursive(), souffle::ast::analysis::RelationScheduleAnalysis::computeRelationExpirySchedule(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::findVariablesRecordMapping(), souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::IOAttributesTransformer::getRecordsTypes(), souffle::ast::transform::ReorderLiteralsTransformer::getSipsFunction(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::removeRelationClauses(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::analysis::SumTypeBranchesAnalysis::run(), souffle::ast::analysis::PrecedenceGraphAnalysis::run(), souffle::ast::analysis::RedundantRelationsAnalysis::run(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::run(), souffle::ast::analysis::SCCGraphAnalysis::run(), souffle::ast::analysis::RelationScheduleAnalysis::run(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::transform::IOAttributesTransformer::setAttributeParams(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), souffle::ast::transform::ComponentInstantiationTransformer::transform(), souffle::ast::transform::ExecutionPlanChecker::transform(), souffle::ast::transform::RemoveRedundantRelationsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), souffle::ast::transform::ADTtoRecordsTransformer::transform(), souffle::ast::transform::ComponentChecker::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), and souffle::AstToRamTranslator::translateProgram().
{
         static const bool debug = Global::config().has("debug-report");
         std::string name = Analysis::name;
         auto it = analyses.find(name);
         if (it == analyses.end()) {
             // analysis does not exist yet, create instance and run it.
             analyses[name] = mk<Analysis>();
             analyses[name]->run(*this);
             if (debug) {
                 std::stringstream ss;
                 analyses[name]->print(ss);
                 if (!isA<analysis::PrecedenceGraphAnalysis>(analyses[name].get()) &&
                         !isA<analysis::SCCGraphAnalysis>(analyses[name].get())) {
                     debugReport.addSection(name, "Ast Analysis [" + name + "]", ss.str());
                 } else {
                     debugReport.addSection(
                             DebugReportSection(name, "Ast Analysis [" + name + "]", {}, ss.str()));
                 }
             }
         }
         return dynamic_cast<Analysis*>(analyses[name].get());
     }
getDebugReport()
DebugReport& souffle::ast::TranslationUnit::getDebugReport () inline
Return debug report.
Definition at line 94 of file TranslationUnit.h.
References debugReport.
Referenced by souffle::ast::transform::DebugReporter::generateDebugReport(), souffle::ast::transform::DebugReporter::transform(), and souffle::AstToRamTranslator::translateUnit().
{
         return debugReport;
     }
getErrorReport()
ErrorReport& souffle::ast::TranslationUnit::getErrorReport () inline
Return error report.
Definition at line 84 of file TranslationUnit.h.
References errorReport.
Referenced by souffle::ast::transform::Transformer::apply(), souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::transform::ComponentInstantiationTransformer::transform(), souffle::ast::transform::ExecutionPlanChecker::transform(), souffle::ast::transform::UserDefinedFunctorsTransformer::transform(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), souffle::ast::transform::ComponentChecker::transform(), souffle::AstToRamTranslator::translateUnit(), and souffle::ast::transform::GroundedTermsChecker::verify().
{
         return errorReport;
     }
getProgram()
Program& souffle::ast::TranslationUnit::getProgram () const inline
Return the program.
Definition at line 78 of file TranslationUnit.h.
References program.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::analysis::RecursiveClausesAnalysis::computeIsRecursive(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::DebugReporter::generateDebugReport(), souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::IOAttributesTransformer::getRecordsParams(), souffle::ast::transform::IOAttributesTransformer::getRecordsTypes(), souffle::ast::transform::makeInfoRelation(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::normaliseArguments(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceClauseBodies(), souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ast::transform::MinimiseProgramTransformer::removeRedundantClauses(), souffle::ast::removeRelation(), souffle::ast::removeRelationClauses(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::removeRelationIOs(), souffle::ast::analysis::SumTypeBranchesAnalysis::run(), souffle::ast::analysis::TypeAnalysis::run(), souffle::ast::analysis::AuxiliaryArityAnalysis::run(), souffle::ast::analysis::TypeEnvironmentAnalysis::run(), souffle::ast::analysis::IOTypeAnalysis::run(), souffle::ast::analysis::PrecedenceGraphAnalysis::run(), souffle::ast::analysis::RedundantRelationsAnalysis::run(), souffle::ast::analysis::RecursiveClausesAnalysis::run(), souffle::ast::analysis::RelationDetailCacheAnalysis::run(), souffle::ast::analysis::SCCGraphAnalysis::run(), souffle::ast::analysis::ComponentLookupAnalysis::run(), souffle::ast::analysis::ClauseNormalisationAnalysis::run(), souffle::ast::transform::TypeChecker::run(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::transform::IOAttributesTransformer::setAttributeParams(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), souffle::ast::transform::IODefaultsTransformer::setDefaults(), souffle::ast::transform::MagicSetTransformer::shouldRun(), souffle::ast::transform::RemoveTypecastsTransformer::transform(), souffle::ast::transform::ComponentInstantiationTransformer::transform(), souffle::ast::transform::PragmaChecker::transform(), souffle::ast::transform::ExecutionPlanChecker::transform(), souffle::ast::transform::UniqueAggregationVariablesTransformer::transform(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::ReplaceSingletonVariablesTransformer::transform(), souffle::ast::transform::InlineRelationsTransformer::transform(), souffle::ast::transform::RemoveRedundantSumsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::NormaliseConstraintsTransformer::transform(), souffle::ast::transform::UserDefinedFunctorsTransformer::transform(), souffle::ast::transform::ADTtoRecordsTransformer::transform(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), souffle::ast::transform::NameUnnamedVariablesTransformer::transform(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform(), souffle::ast::transform::ComponentChecker::transform(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::ReorderLiteralsTransformer::transform(), souffle::ast::transform::FoldAnonymousRecords::transform(), souffle::ast::transform::ResolveAliasesTransformer::transform(), souffle::ast::transform::DebugReporter::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform(), souffle::ast::transform::ProvenanceTransformer::transformMaxHeight(), souffle::AstToRamTranslator::translateUnit(), and souffle::ast::transform::GroundedTermsChecker::verify().
{
         assert(program && "NULL program");
         return *program.get();
     }
invalidateAnalyses()
void souffle::ast::TranslationUnit::invalidateAnalyses () inline
Destroy all cached analyses of translation unit.
Definition at line 89 of file TranslationUnit.h.
References analyses.
Referenced by souffle::ast::transform::Transformer::apply(), souffle::ast::transform::MinimiseProgramTransformer::transform(), and souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::transform().
{
         analyses.clear();
     }
Field Documentation
analyses
std::map<std::string, Own<analysis::Analysis> > souffle::ast::TranslationUnit::analyses mutable private
Cached analyses.
Definition at line 100 of file TranslationUnit.h.
Referenced by getAnalysis(), and invalidateAnalyses().
debugReport
DebugReport& souffle::ast::TranslationUnit::debugReport private
HTML debug report.
Definition at line 109 of file TranslationUnit.h.
Referenced by getAnalysis(), and getDebugReport().
errorReport
ErrorReport& souffle::ast::TranslationUnit::errorReport private
Error report capturing errors while compiling.
Definition at line 106 of file TranslationUnit.h.
Referenced by getErrorReport().
program
Own<Program> souffle::ast::TranslationUnit::program private
AST program.
Definition at line 103 of file TranslationUnit.h.
Referenced by getProgram().
The documentation for this class was generated from the following file:
ast/TranslationUnit.h