souffle: souffle::ast::FunctorDeclaration Class Reference
souffle::ast::FunctorDeclaration Class Reference
User-defined functor declaration.
#include <FunctorDeclaration.h>
Public Member Functions
FunctorDeclaration * clone () const override
Create a clone (i.e.
FunctorDeclaration (std::string name, std::vector< TypeAttribute > argsTypes, TypeAttribute returnType, bool stateful, SrcLocation loc={})
const std::vector< TypeAttribute > & getArgsTypes () const
Return type.
size_t getArity () const
Return number of arguments.
const std::string & getName () const
Return name.
TypeAttribute getReturnType () const
Get return type.
bool isStateful () const
Check whether functor is stateful.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &out) const override
Output to a given output stream.
Protected Attributes
const std::vector< TypeAttribute > argsTypes
Types of arguments.
const std::string name
Name of functor.
const TypeAttribute returnType
Type of the return value.
const bool stateful
Stateful flag.
Detailed Description
User-defined functor declaration.
Example: .declfun foo(x:number, y:number):number
Definition at line 43 of file FunctorDeclaration.h.
Constructor & Destructor Documentation
FunctorDeclaration()
souffle::ast::FunctorDeclaration::FunctorDeclaration (std::string name, std::vector< TypeAttribute > argsTypes, TypeAttribute returnType, bool stateful, SrcLocation loc = {}) inline
Definition at line 45 of file FunctorDeclaration.h.
References argsTypes, name, souffle::ast::Node::Node(), returnType, and stateful.
Referenced by clone().
                                              {})
             : Node(std::move(loc)), name(std::move(name)), argsTypes(std::move(argsTypes)),
               returnType(returnType), stateful(stateful) {
         assert(this->name.length() > 0 && "functor name is empty");
     }
Member Function Documentation
clone()
FunctorDeclaration* souffle::ast::FunctorDeclaration::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 77 of file FunctorDeclaration.h.
References FunctorDeclaration(), and souffle::ast::Node::getSrcLoc().
{
         return new FunctorDeclaration(name, argsTypes, returnType, stateful, getSrcLoc());
     }
equal()
bool souffle::ast::FunctorDeclaration::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 103 of file FunctorDeclaration.h.
References name.
{
         const auto& other = static_cast<const FunctorDeclaration&>(node);
         return name == other.name && argsTypes == other.argsTypes && returnType == other.returnType &&
                stateful == other.stateful;
     }
getArgsTypes()
const std::vector<TypeAttribute>& souffle::ast::FunctorDeclaration::getArgsTypes () const inline
Return type.
Definition at line 58 of file FunctorDeclaration.h.
References argsTypes.
Referenced by souffle::ast::transform::UserDefinedFunctorsTransformer::transform().
{
         return argsTypes;
     }
getArity()
size_t souffle::ast::FunctorDeclaration::getArity () const inline
Return number of arguments.
Definition at line 68 of file FunctorDeclaration.h.
Referenced by souffle::ast::transform::UserDefinedFunctorsTransformer::transform().
{
         return argsTypes.size();
     }
getName()
const std::string& souffle::ast::FunctorDeclaration::getName () const inline
Return name.
Definition at line 53 of file FunctorDeclaration.h.
References name.
Referenced by souffle::ast::Program::addFunctorDeclaration().
{
         return name;
     }
getReturnType()
TypeAttribute souffle::ast::FunctorDeclaration::getReturnType () const inline
Get return type.
Definition at line 63 of file FunctorDeclaration.h.
References returnType.
Referenced by souffle::ast::transform::UserDefinedFunctorsTransformer::transform().
{
         return returnType;
     }
isStateful()
bool souffle::ast::FunctorDeclaration::isStateful () const inline
Check whether functor is stateful.
Definition at line 73 of file FunctorDeclaration.h.
References stateful.
Referenced by souffle::ast::transform::UserDefinedFunctorsTransformer::transform().
{
         return stateful;
     }
print()
void souffle::ast::FunctorDeclaration::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 82 of file FunctorDeclaration.h.
References souffle::ADT, souffle::fatal(), souffle::Float, tinyformat::format(), souffle::join(), souffle::map(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
{
         auto convert = [&](TypeAttribute type) {
             switch (type) {
                 case TypeAttribute::Signed: return "number";
                 case TypeAttribute::Symbol: return "symbol";
                 case TypeAttribute::Float: return "float";
                 case TypeAttribute::Unsigned: return "unsigned";
                 case TypeAttribute::Record: break;
                 case TypeAttribute::ADT: break;
             }
             fatal("unhandled `TypeAttribute`");
         };
         tfm::format(
                 out, ".declfun %s(%s): %s", name, join(map(argsTypes, convert), ","), convert(returnType));
         if (stateful) {
             out << " stateful";
         }
         out << std::endl;
     }
Field Documentation
argsTypes
const std::vector<TypeAttribute> souffle::ast::FunctorDeclaration::argsTypes protected
Types of arguments.
Definition at line 113 of file FunctorDeclaration.h.
Referenced by FunctorDeclaration(), and getArgsTypes().
name
const std::string souffle::ast::FunctorDeclaration::name protected
Name of functor.
Definition at line 110 of file FunctorDeclaration.h.
Referenced by equal(), FunctorDeclaration(), and getName().
returnType
const TypeAttribute souffle::ast::FunctorDeclaration::returnType protected
Type of the return value.
Definition at line 116 of file FunctorDeclaration.h.
Referenced by FunctorDeclaration(), and getReturnType().
stateful
const bool souffle::ast::FunctorDeclaration::stateful protected
Stateful flag.
Definition at line 119 of file FunctorDeclaration.h.
Referenced by FunctorDeclaration(), and isStateful().
The documentation for this class was generated from the following file:
ast/FunctorDeclaration.h