souffle: tinyformat::detail::FormatArg Class Reference
tinyformat::detail::FormatArg Class Reference
#include <tinyformat.h>
Public Member Functions
void format (std::ostream &out, const char *fmtBegin, const char *fmtEnd, int ntrunc) const
FormatArg ()=default
template<typename T >
FormatArg (const T &value)
int toInt () const
Static Private Member Functions
template<typename T >
static TINYFORMAT_HIDDEN void formatImpl (std::ostream &out, const char *fmtBegin, const char *fmtEnd, int ntrunc, const void *value)
template<typename T >
static TINYFORMAT_HIDDEN int toIntImpl (const void *value)
Private Attributes
void(* m_formatImpl)(std::ostream &out, const char *fmtBegin, const char *fmtEnd, int ntrunc, const void *value) = nullptr
int(* m_toIntImpl)(const void *value) = nullptr
const void * m_value = nullptr
Detailed Description
Definition at line 506 of file tinyformat.h.
Constructor & Destructor Documentation
FormatArg() [1/2]
tinyformat::detail::FormatArg::FormatArg () default
FormatArg() [2/2]
template<typename T > tinyformat::detail::FormatArg::FormatArg (const T & value) inline
Definition at line 512 of file tinyformat.h.
             : m_value(static_cast<const void*>(&value)),
             m_formatImpl(&formatImpl<T>),
             m_toIntImpl(&toIntImpl<T>)
         { }
Member Function Documentation
format()
void tinyformat::detail::FormatArg::format (std::ostream & out, const char * fmtBegin, const char * fmtEnd, int ntrunc) const inline
Definition at line 518 of file tinyformat.h.
References TINYFORMAT_ASSERT.
Referenced by tinyformat::detail::formatImpl().
         {
             TINYFORMAT_ASSERT(m_value);
             TINYFORMAT_ASSERT(m_formatImpl);
             m_formatImpl(out, fmtBegin, fmtEnd, ntrunc, m_value);
         }
formatImpl()
template<typename T > static TINYFORMAT_HIDDEN void tinyformat::detail::FormatArg::formatImpl (std::ostream & out, const char * fmtBegin, const char * fmtEnd, int ntrunc, const void * value) inline static private
Definition at line 535 of file tinyformat.h.
References tinyformat::formatValue().
         {
             formatValue(out, fmtBegin, fmtEnd, ntrunc, *static_cast<const T*>(value));
         }
toInt()
int tinyformat::detail::FormatArg::toInt () const inline
Definition at line 526 of file tinyformat.h.
References TINYFORMAT_ASSERT.
Referenced by tinyformat::detail::parseWidthOrPrecision().
         {
             TINYFORMAT_ASSERT(m_value);
             TINYFORMAT_ASSERT(m_toIntImpl);
             return m_toIntImpl(m_value);
         }
toIntImpl()
template<typename T > static TINYFORMAT_HIDDEN int tinyformat::detail::FormatArg::toIntImpl (const void * value) inline static private
Definition at line 542 of file tinyformat.h.
References tinyformat::detail::convertToInt< T, convertible >::invoke().
         {
             return convertToInt<T>::invoke(*static_cast<const T*>(value));
         }
Field Documentation
m_formatImpl
void(* tinyformat::detail::FormatArg::m_formatImpl) (std::ostream &out, const char *fmtBegin, const char *fmtEnd, int ntrunc, const void *value) = nullptr private
Definition at line 548 of file tinyformat.h.
m_toIntImpl
int(* tinyformat::detail::FormatArg::m_toIntImpl) (const void *value) = nullptr private
Definition at line 550 of file tinyformat.h.
m_value
const void* tinyformat::detail::FormatArg::m_value = nullptr private
Definition at line 547 of file tinyformat.h.
The documentation for this class was generated from the following file:
include/souffle/utility/tinyformat.h