souffle: souffle::ram::RelationOperation Class Reference
souffle::ram::RelationOperation Class Reference abstract
Abstract class for operations on relations.
#include <RelationOperation.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
RelationOperation * clone () const override=0
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for operations on relations.
One such operation is a for loop
Definition at line 37 of file RelationOperation.h.
Constructor & Destructor Documentation
RelationOperation()
souffle::ram::RelationOperation::RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText = "") inline
Definition at line 39 of file RelationOperation.h.
References clone(), and relationRef.
             : TupleOperation(ident, std::move(nested), std::move(profileText)),
               relationRef(std::move(relRef)) {
         assert(relationRef != nullptr && "relation reference is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::RelationOperation::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::NestedOperation.
Definition at line 53 of file RelationOperation.h.
References souffle::ram::NestedOperation::apply(), souffle::map(), and relationRef.
Referenced by souffle::ram::Choice::apply(), souffle::ram::IndexChoice::apply(), souffle::ram::Aggregate::apply(), and souffle::ram::IndexOperation::apply().
{
         TupleOperation::apply(map);
         relationRef = map(std::move(relationRef));
     }
clone()
RelationOperation* souffle::ram::RelationOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::TupleOperation.
Implemented in souffle::ram::IndexOperation, souffle::ram::IndexChoice, souffle::ram::Choice, souffle::ram::Aggregate, souffle::ram::ParallelIndexChoice, souffle::ram::IndexAggregate, souffle::ram::ParallelIndexScan, souffle::ram::ParallelAggregate, souffle::ram::IndexScan, souffle::ram::ParallelIndexAggregate, souffle::ram::ParallelChoice, souffle::ram::ParallelScan, and souffle::ram::Scan.
Referenced by RelationOperation().
equal()
bool souffle::ram::RelationOperation::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::NestedOperation.
Definition at line 65 of file RelationOperation.h.
References souffle::ram::TupleOperation::equal(), souffle::equal_ptr(), and relationRef.
Referenced by souffle::ram::Choice::equal(), souffle::ram::Aggregate::equal(), and souffle::ram::IndexOperation::equal().
{
         const auto& other = static_cast<const RelationOperation&>(node);
         return TupleOperation::equal(other) && equal_ptr(relationRef, other.relationRef);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::RelationOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::NestedOperation.
Definition at line 58 of file RelationOperation.h.
References souffle::ram::TupleOperation::getChildNodes(), and relationRef.
Referenced by souffle::ram::Aggregate::getChildNodes(), and souffle::ram::IndexOperation::getChildNodes().
{
         auto res = TupleOperation::getChildNodes();
         res.push_back(relationRef.get());
         return res;
     }
getRelation()
const Relation& souffle::ram::RelationOperation::getRelation () const inline
Get search relation.
Definition at line 49 of file RelationOperation.h.
References relationRef.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), souffle::ram::IndexChoice::IndexChoice(), souffle::ram::IndexOperation::IndexOperation(), souffle::ram::Scan::print(), souffle::ram::ParallelScan::print(), souffle::ram::ParallelChoice::print(), souffle::ram::ParallelAggregate::print(), souffle::ram::IndexScan::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::ParallelIndexScan::print(), souffle::ram::Aggregate::print(), souffle::ram::Choice::print(), souffle::ram::ParallelIndexChoice::print(), souffle::ram::IndexAggregate::print(), souffle::ram::IndexChoice::print(), souffle::ram::IndexOperation::printIndex(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), souffle::ram::transform::MakeIndexTransformer::rewriteScan(), souffle::NodeGenerator::visitAggregate(), souffle::NodeGenerator::visitChoice(), souffle::NodeGenerator::visitIndexAggregate(), souffle::NodeGenerator::visitParallelAggregate(), souffle::NodeGenerator::visitParallelChoice(), souffle::NodeGenerator::visitParallelIndexAggregate(), souffle::NodeGenerator::visitParallelIndexChoice(), souffle::NodeGenerator::visitParallelIndexScan(), souffle::NodeGenerator::visitParallelScan(), and souffle::NodeGenerator::visitScan().
{
         return *relationRef->get();
     }
Field Documentation
relationRef
Own<RelationReference> souffle::ram::RelationOperation::relationRef protected
Search relation.
Definition at line 71 of file RelationOperation.h.
Referenced by apply(), souffle::ram::Scan::clone(), souffle::ram::ParallelScan::clone(), souffle::ram::ParallelChoice::clone(), souffle::ram::IndexScan::clone(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::ParallelAggregate::clone(), souffle::ram::ParallelIndexScan::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::Aggregate::clone(), souffle::ram::Choice::clone(), souffle::ram::IndexChoice::clone(), souffle::ram::IndexOperation::clone(), equal(), getChildNodes(), souffle::ram::Choice::getChildNodes(), getRelation(), and RelationOperation().
The documentation for this class was generated from the following file:
ram/RelationOperation.h