souffle: souffle::ast::RecordType Class Reference
souffle::ast::RecordType Class Reference
Record type class for record type declarations.
#include <RecordType.h>
Public Member Functions
void add (std::string name, QualifiedName type)
Add field to record type.
RecordType * clone () const override
std::vector< Attribute * > getFields () const
Get fields of record.
RecordType (QualifiedName name, VecOwn< Attribute > fields, SrcLocation loc={})
void setFieldType (size_t idx, QualifiedName type)
Set field type.
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
bool equal (const Node &node) const override
void print (std::ostream &os) const override
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Private Attributes
VecOwn< Attribute > fields
record fields
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Detailed Description
Record type class for record type declarations.
A record type aggregates a list of fields (i.e. name & type) into a new type. Each record type has a name making the record type unique.
Definition at line 44 of file RecordType.h.
Constructor & Destructor Documentation
RecordType()
souffle::ast::RecordType::RecordType (QualifiedName name, VecOwn< Attribute > fields, SrcLocation loc = {}) inline
Definition at line 46 of file RecordType.h.
References souffle::ast::analysis::RecordType::fields, and souffle::ast::analysis::Type::Type().
                                                                                {})
             : Type(std::move(name), std::move(loc)), fields(std::move(fields)) {}
Member Function Documentation
add()
void souffle::ast::RecordType::add (std::string name, QualifiedName type) inline
Add field to record type.
Definition at line 50 of file RecordType.h.
{
         fields.push_back(mk<Attribute>(std::move(name), std::move(type)));
     }
clone()
RecordType* souffle::ast::RecordType::clone () const inline override
Definition at line 64 of file RecordType.h.
References souffle::clone(), and souffle::ast::analysis::RecordType::RecordType().
{
         return new RecordType(getQualifiedName(), souffle::clone(fields), getSrcLoc());
     }
equal()
bool souffle::ast::RecordType::equal (const Node & node) const inline override protected
Definition at line 73 of file RecordType.h.
References souffle::equal_targets().
{
         const auto& other = dynamic_cast<const RecordType&>(node);
         return getQualifiedName() == other.getQualifiedName() && equal_targets(fields, other.fields);
     }
getFields()
std::vector<Attribute*> souffle::ast::RecordType::getFields () const inline
Get fields of record.
Definition at line 55 of file RecordType.h.
References souffle::toPtrVector().
{
         return toPtrVector(fields);
     }
print()
void souffle::ast::RecordType::print (std::ostream & os) const inline override protected virtual
Reimplemented from souffle::ast::analysis::Type.
Definition at line 69 of file RecordType.h.
References tinyformat::format(), and souffle::join().
{
         os << tfm::format(".type %s = [%s]", getQualifiedName(), join(fields, ", "));
     }
setFieldType()
void souffle::ast::RecordType::setFieldType (size_t idx, QualifiedName type) inline
Set field type.
Definition at line 60 of file RecordType.h.
{
         fields.at(idx)->setTypeName(std::move(type));
     }
Field Documentation
fields
VecOwn<Attribute> souffle::ast::RecordType::fields private
record fields
Definition at line 80 of file RecordType.h.
The documentation for this class was generated from the following file:
ast/RecordType.h