souffle: souffle::ram::transform::IfConversionTransformer Class Reference
souffle::ram::transform::IfConversionTransformer Class Reference
Convert IndexScan operations to Filter/Existence Checks.
#include <IfConversion.h>
Public Member Functions
bool convertIndexScans (Program &program)
Apply if-conversion to the whole program.
std::string getName () const override
get name of the transformer
Own< Operation > rewriteIndexScan (const IndexScan *indexScan)
Rewrite IndexScan operations.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Convert IndexScan operations to Filter/Existence Checks.
If there exists IndexScan operations in the RAM, and their tuples are not further used in subsequent operations, the IndexScan operations will be rewritten to Filter/Existence Checks.
For example,
QUERY
 ...
 FOR t1 IN X ON INDEX t1.x = 10 AND t1.y = 20
   ... // no occurrence of t1
will be rewritten to
QUERY
 ...
  IF (10,20) NOT IN A
    ...
Definition at line 54 of file IfConversion.h.
Member Function Documentation
convertIndexScans()
bool souffle::ram::transform::IfConversionTransformer::convertIndexScans (Program & program)
Apply if-conversion to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Search for queries and rewrite their IndexScan operations if possible.
Definition at line 77 of file IfConversion.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::ram::makeLambdaRamMapper(), rewriteIndexScan(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> scanRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const IndexScan* scan = dynamic_cast<IndexScan*>(node.get())) {
                 if (Own<Operation> op = rewriteIndexScan(scan)) {
                     changed = true;
                     node = std::move(op);
                 }
             }
             node->apply(makeLambdaRamMapper(scanRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(scanRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ram::transform::IfConversionTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 56 of file IfConversion.h.
References convertIndexScans(), and rewriteIndexScan().
{
         return "IfConversionTransformer";
     }
rewriteIndexScan()
Own< Operation > souffle::ram::transform::IfConversionTransformer::rewriteIndexScan (const IndexScan * indexScan)
Rewrite IndexScan operations.
Parameters
indexScan An index operation
Returns
The old operation if the if-conversion fails; otherwise the filter/existence check
Rewrites IndexScan operations to a filter/existence check if the IndexScan's tuple is not used in a consecutive RAM operation
Definition at line 33 of file IfConversion.cpp.
References souffle::ram::Expression::clone(), souffle::ram::Operation::clone(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::IndexOperation::getRangePattern(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::TupleElement::getTupleId(), i, and souffle::ram::visitDepthFirst().
Referenced by convertIndexScans(), and getName().
{
     // check whether tuple is used in subsequent operations
     bool tupleNotUsed = true;
     visitDepthFirst(*indexScan, [&](const TupleElement& element) {
         if (element.getTupleId() == indexScan->getTupleId()) {
             tupleNotUsed = false;
         }
     });
     // if not used, transform the IndexScan operation to an existence check
     if (tupleNotUsed) {
         // replace IndexScan with an Filter/Existence check
         VecOwn<Expression> newValues;
         size_t arity = indexScan->getRangePattern().first.size();
         for (size_t i = 0; i < arity; ++i) {
             if (*(indexScan->getRangePattern().first[i]) != *(indexScan->getRangePattern().second[i])) {
                 return nullptr;
             }
         }
         for (auto& cur : indexScan->getRangePattern().second) {
             Expression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.emplace_back(val);
         }
         // check if there is a break statement nested in the Scan - if so, remove it
         Operation* newOp;
         if (const auto* breakOp = dynamic_cast<const Break*>(&indexScan->getOperation())) {
             newOp = breakOp->getOperation().clone();
         } else {
             newOp = indexScan->getOperation().clone();
         }
         return mk<Filter>(
                 mk<ExistenceCheck>(mk<RelationReference>(&indexScan->getRelation()), std::move(newValues)),
                 Own<Operation>(newOp), indexScan->getProfileText());
     }
     return nullptr;
 }
transform()
bool souffle::ram::transform::IfConversionTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 80 of file IfConversion.h.
References convertIndexScans(), and souffle::ram::TranslationUnit::getProgram().
{
         return convertIndexScans(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/IfConversion.h
ram/transform/IfConversion.cpp