souffle: souffle::ram::SignedConstant Class Reference
souffle::ram::SignedConstant Class Reference
Represents a signed constant.
#include <SignedConstant.h>
Public Member Functions
SignedConstant * clone () const override
Create clone.
RamDomain getValue () const
Get value of the constant.
SignedConstant (RamDomain val)
Public Member Functions inherited from souffle::ram::Constant
RamDomain getConstant () const
Get constant.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::Constant
Constant (RamDomain constant)
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::ram::Constant
const RamDomain constant
Constant value.
Detailed Description
Represents a signed constant.
For example:
number(5)
Definition at line 34 of file SignedConstant.h.
Constructor & Destructor Documentation
SignedConstant()
souffle::ram::SignedConstant::SignedConstant (RamDomain val) inline explicit
Definition at line 36 of file SignedConstant.h.
Referenced by clone().
 : Constant(val) {}
Member Function Documentation
clone()
SignedConstant* souffle::ram::SignedConstant::clone () const inline override virtual
Create clone.
Implements souffle::ram::Expression.
Definition at line 44 of file SignedConstant.h.
References getValue(), and SignedConstant().
Referenced by souffle::ram::test::TEST().
{
         return new SignedConstant(getValue());
     }
getValue()
RamDomain souffle::ram::SignedConstant::getValue () const inline
Get value of the constant.
Definition at line 39 of file SignedConstant.h.
References souffle::ram::Constant::constant.
Referenced by clone().
{
         return constant;
     }
print()
void souffle::ram::SignedConstant::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 49 of file SignedConstant.h.
References souffle::ram::Constant::constant.
{
         os << "number(" << constant << ")";
     }
The documentation for this class was generated from the following file:
ram/SignedConstant.h