souffle: souffle::ram::Choice Class Reference
souffle::ram::Choice Class Reference
Find a tuple in a relation such that a given condition holds.
#include <Choice.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Choice (Own< RelationReference > rel, size_t ident, Own< Condition > cond, Own< Operation > nested, std::string profileText="")
Choice * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractChoice
AbstractChoice (Own< Condition > cond)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Getter for the condition.
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractChoice
bool equal (const Node &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractChoice
Own< Condition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Find a tuple in a relation such that a given condition holds.
Only one tuple is returned (if one exists), even if multiple tuples satisfying the condition exist.
For example:
QUERY
 ...
  CHOICE t1 IN A WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 53 of file Choice.h.
Constructor & Destructor Documentation
Choice()
souffle::ram::Choice::Choice (Own< RelationReference > rel, size_t ident, Own< Condition > cond, Own< Operation > nested, std::string profileText = "") inline
Definition at line 55 of file Choice.h.
Referenced by clone().
             : RelationOperation(std::move(rel), ident, std::move(nested), std::move(profileText)),
               AbstractChoice(std::move(cond)) {}
Member Function Documentation
apply()
void souffle::ram::Choice::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 60 of file Choice.h.
References souffle::ram::AbstractChoice::apply(), and souffle::ram::RelationOperation::apply().
{
         RelationOperation::apply(map);
         AbstractChoice::apply(map);
     }
clone()
Choice* souffle::ram::Choice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::RelationOperation.
Reimplemented in souffle::ram::ParallelChoice.
Definition at line 65 of file Choice.h.
References Choice(), souffle::clone(), souffle::ram::AbstractChoice::condition, souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::TupleOperation::getTupleId(), and souffle::ram::RelationOperation::relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new Choice(souffle::clone(relationRef), getTupleId(), souffle::clone(condition),
                 souffle::clone(&getOperation()), getProfileText());
     }
equal()
bool souffle::ram::Choice::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 84 of file Choice.h.
References souffle::ram::AbstractChoice::equal(), and souffle::ram::RelationOperation::equal().
{
         const auto& other = static_cast<const Choice&>(node);
         return RelationOperation::equal(other) && AbstractChoice::equal(other);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Choice::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 70 of file Choice.h.
References souffle::ram::AbstractChoice::getChildNodes(), souffle::ram::NestedOperation::nestedOperation, and souffle::ram::RelationOperation::relationRef.
{
         return {nestedOperation.get(), relationRef.get(), AbstractChoice::getChildNodes().at(0)};
     }
print()
void souffle::ram::Choice::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Reimplemented in souffle::ram::ParallelChoice.
Definition at line 75 of file Choice.h.
References souffle::ram::AbstractChoice::getCondition(), souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "CHOICE t" << getTupleId();
         os << " IN " << getRelation().getName();
         os << " WHERE " << getCondition();
         os << std::endl;
         RelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Choice.h