souffle: souffle::ram::IndexAggregate Class Reference
souffle::ram::IndexAggregate Class Reference
Indexed aggregation on a relation.
#include <IndexAggregate.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
IndexAggregate * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
IndexAggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, RamPattern queryPattern, int ident)
Public Member Functions inherited from souffle::ram::IndexOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
IndexOperation * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< Expression * >, std::vector< Expression * > > getRangePattern () const
Get range pattern.
IndexOperation (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
void printIndex (std::ostream &os) const
Helper method for printing.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractAggregate
AbstractAggregate (AggregateOp fun, Own< Expression > expr, Own< Condition > cond)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Get condition.
const Expression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
virtual ~AbstractAggregate ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::IndexOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractAggregate
bool equal (const Node &node) const
void print (std::ostream &os, int) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::IndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractAggregate
Own< Condition > condition
Aggregation tuple condition.
Own< Expression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Indexed aggregation on a relation.
The index allows us to iterate over a restricted range
For example:
t0.0=sum t0.1 SEARCH t0  S ON INDEX t0.0 = number(1)
Definition at line 47 of file IndexAggregate.h.
Constructor & Destructor Documentation
IndexAggregate()
souffle::ram::IndexAggregate::IndexAggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, RamPattern queryPattern, int ident) inline
Definition at line 49 of file IndexAggregate.h.
Referenced by clone().
             : IndexOperation(std::move(relRef), ident, std::move(queryPattern), std::move(nested)),
               AbstractAggregate(fun, std::move(expression), std::move(condition)) {}
Member Function Documentation
apply()
void souffle::ram::IndexAggregate::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 73 of file IndexAggregate.h.
References souffle::ram::IndexOperation::apply(), souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::expression, and souffle::map().
{
         IndexOperation::apply(map);
         condition = map(std::move(condition));
         expression = map(std::move(expression));
     }
clone()
IndexAggregate* souffle::ram::IndexAggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::RelationOperation.
Reimplemented in souffle::ram::ParallelIndexAggregate.
Definition at line 61 of file IndexAggregate.h.
References souffle::clone(), souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::expression, souffle::ram::NestedOperation::getOperation(), souffle::ram::TupleOperation::getTupleId(), i, IndexAggregate(), souffle::ram::IndexOperation::queryPattern, and souffle::ram::RelationOperation::relationRef.
Referenced by souffle::ram::test::TEST().
{
         RamPattern pattern;
         for (const auto& i : queryPattern.first) {
             pattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             pattern.second.emplace_back(i->clone());
         }
         return new IndexAggregate(souffle::clone(&getOperation()), function, souffle::clone(relationRef),
                 souffle::clone(expression), souffle::clone(condition), std::move(pattern), getTupleId());
     }
equal()
bool souffle::ram::IndexAggregate::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 93 of file IndexAggregate.h.
References souffle::ram::AbstractAggregate::equal(), and souffle::ram::IndexOperation::equal().
{
         const auto& other = static_cast<const IndexAggregate&>(node);
         return IndexOperation::equal(other) && AbstractAggregate::equal(other);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::IndexAggregate::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 54 of file IndexAggregate.h.
References souffle::ram::AbstractAggregate::getChildNodes(), and souffle::ram::IndexOperation::getChildNodes().
{
         auto res = IndexOperation::getChildNodes();
         auto children = AbstractAggregate::getChildNodes();
         res.insert(res.end(), children.begin(), children.end());
         return res;
     }
print()
void souffle::ram::IndexAggregate::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Reimplemented in souffle::ram::ParallelIndexAggregate.
Definition at line 80 of file IndexAggregate.h.
References souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::getCondition(), souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::isTrue(), souffle::ram::AbstractAggregate::print(), souffle::ram::NestedOperation::print(), souffle::ram::IndexOperation::printIndex(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "t" << getTupleId() << ".0=";
         AbstractAggregate::print(os, tabpos);
         os << "SEARCH t" << getTupleId() << "  " << getRelation().getName();
         printIndex(os);
         if (!isTrue(condition.get())) {
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         IndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/IndexAggregate.h