souffle: souffle::ast::analysis::TypeAnalysis Class Reference
souffle::ast::analysis::TypeAnalysis Class Reference
#include <Type.h>
Public Member Functions
TypeSet const & getTypes (const Argument *argument) const
Get the computed types for the given argument.
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeAnalysis ()
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Member Functions
static std::map< const Argument *, TypeSet > analyseTypes (const TranslationUnit &, const Clause &, std::ostream *=nullptr)
Analyse the given clause and computes for each contained argument a set of potential types.
Static Public Attributes
static constexpr const char * name = "type-analysis"
Private Attributes
std::stringstream analysisLogs
VecOwn< Clause > annotatedClauses
std::map< const Argument *, TypeSet > argumentTypes
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 30 of file Type.h.
Constructor & Destructor Documentation
TypeAnalysis()
souffle::ast::analysis::TypeAnalysis::TypeAnalysis () inline
Definition at line 34 of file Type.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
analyseTypes()
std::map< const Argument *, TypeSet > souffle::ast::analysis::TypeAnalysis::analyseTypes (const TranslationUnit & tu, const Clause & clause, std::ostream * logs = nullptr) static
Analyse the given clause and computes for each contained argument a set of potential types.
If the set associated to an argument is empty, no consistent typing can be found and the rule can not be properly typed.
Parameters
env a typing environment describing the set of available types
clause the clause to be typed
program the program
Returns
a map mapping each contained argument to a a set of types
Definition at line 802 of file Type.cpp.
References souffle::ast::analysis::ConstraintAnalysis< AnalysisVar >::analyse().
Referenced by getTypes(), and souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries().
{
     return TypeConstraintsAnalysis(tu).analyse(clause, logs);
 }
getTypes()
TypeSet const& souffle::ast::analysis::TypeAnalysis::getTypes (const Argument * argument) const inline
Get the computed types for the given argument.
Definition at line 43 of file Type.h.
References analyseTypes(), and argumentTypes.
Referenced by souffle::ast::transform::PolymorphicObjectsTransformer::transform(), souffle::ast::validOverloads(), souffle::ast::transform::TypeChecker::visitAggregator(), souffle::ast::transform::TypeChecker::visitAtom(), souffle::ast::transform::TypeChecker::visitBinaryConstraint(), souffle::ast::transform::TypeChecker::visitBranchInit(), souffle::ast::transform::TypeChecker::visitNilConstant(), souffle::ast::transform::TypeChecker::visitNumericConstant(), souffle::ast::transform::TypeChecker::visitRecordInit(), souffle::ast::transform::TypeChecker::visitStringConstant(), souffle::ast::transform::TypeChecker::visitTypeCast(), souffle::ast::transform::TypeChecker::visitUserDefinedFunctor(), and souffle::ast::transform::TypeChecker::visitVariable().
{
         return argumentTypes.at(argument);
     }
print()
void souffle::ast::analysis::TypeAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 807 of file Type.cpp.
Referenced by TypeAnalysis().
{
     os << "-- Analysis logs --" << std::endl;
     os << analysisLogs.str() << std::endl;
     os << "-- Result --" << std::endl;
     for (auto& cur : annotatedClauses) {
         os << *cur << std::endl;
     }
 }
run()
void souffle::ast::analysis::TypeAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 816 of file Type.cpp.
References souffle::Global::config(), souffle::ast::analysis::createAnnotatedClause(), souffle::ast::Program::getClauses(), and souffle::ast::TranslationUnit::getProgram().
Referenced by TypeAnalysis().
{
     // Check if debugging information is being generated
     std::ostream* debugStream = nullptr;
     if (Global::config().has("debug-report") || Global::config().has("show", "type-analysis")) {
         debugStream = &analysisLogs;
     }
     // Analyse types, clause by clause.
     const Program& program = translationUnit.getProgram();
     for (const Clause* clause : program.getClauses()) {
         auto clauseArgumentTypes = analyseTypes(translationUnit, *clause, debugStream);
         argumentTypes.insert(clauseArgumentTypes.begin(), clauseArgumentTypes.end());
         if (debugStream != nullptr) {
             // Store an annotated clause for printing purposes
             annotatedClauses.emplace_back(createAnnotatedClause(clause, clauseArgumentTypes));
         }
     }
 }
Field Documentation
analysisLogs
std::stringstream souffle::ast::analysis::TypeAnalysis::analysisLogs private
Definition at line 63 of file Type.h.
annotatedClauses
VecOwn<Clause> souffle::ast::analysis::TypeAnalysis::annotatedClauses private
Definition at line 62 of file Type.h.
argumentTypes
std::map<const Argument*, TypeSet> souffle::ast::analysis::TypeAnalysis::argumentTypes private
Definition at line 61 of file Type.h.
Referenced by getTypes().
name
constexpr const char* souffle::ast::analysis::TypeAnalysis::name = "type-analysis" static
Definition at line 32 of file Type.h.
The documentation for this class was generated from the following files:
ast/analysis/Type.h
ast/analysis/Type.cpp