souffle: souffle::ast::analysis::RelationScheduleAnalysis Class Reference
souffle::ast::analysis::RelationScheduleAnalysis Class Reference
Analysis pass computing a schedule for computing relations.
#include <RelationSchedule.h>
Public Member Functions
void print (std::ostream &os) const override
Dump this relation schedule to standard error.
RelationScheduleAnalysis ()
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
const std::vector< RelationScheduleAnalysisStep > & schedule () const
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "relation-schedule"
Private Member Functions
std::vector< std::set< const Relation * > > computeRelationExpirySchedule (const TranslationUnit &translationUnit)
Private Attributes
PrecedenceGraphAnalysis * precedenceGraph = nullptr
std::vector< RelationScheduleAnalysisStep > relationSchedule
Relations computed and expired relations at each step.
TopologicallySortedSCCGraphAnalysis * topsortSCCGraphAnalysis = nullptr
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass computing a schedule for computing relations.
Definition at line 74 of file RelationSchedule.h.
Constructor & Destructor Documentation
RelationScheduleAnalysis()
souffle::ast::analysis::RelationScheduleAnalysis::RelationScheduleAnalysis () inline
Definition at line 78 of file RelationSchedule.h.
 : Analysis(name) {}
Member Function Documentation
computeRelationExpirySchedule()
std::vector< std::set< const Relation * > > souffle::ast::analysis::RelationScheduleAnalysis::computeRelationExpirySchedule (const TranslationUnit & translationUnit) private
Definition at line 71 of file RelationSchedule.cpp.
References souffle::ast::TranslationUnit::getAnalysis().
{
     std::vector<std::set<const Relation*>> relationExpirySchedule;
     /* Compute for each step in the reverse topological order
        of evaluating the SCC the set of alive relations. */
     size_t numSCCs = topsortSCCGraphAnalysis->order().size();
     /* Alive set for each step */
     std::vector<std::set<const Relation*>> alive(numSCCs);
     /* Resize expired relations sets */
     relationExpirySchedule.resize(numSCCs);
     const auto& sccGraph = translationUnit.getAnalysis<SCCGraphAnalysis>();
     /* Compute all alive relations by iterating over all steps in reverse order
        determine the dependencies */
     for (size_t orderedSCC = 1; orderedSCC < numSCCs; orderedSCC++) {
         /* Add alive set of previous step */
         alive[orderedSCC].insert(alive[orderedSCC - 1].begin(), alive[orderedSCC - 1].end());
         /* Add predecessors of relations computed in this step */
         auto scc = topsortSCCGraphAnalysis->order()[numSCCs - orderedSCC];
         for (const Relation* r : sccGraph->getInternalRelations(scc)) {
             for (const Relation* predecessor : precedenceGraph->graph().predecessors(r)) {
                 alive[orderedSCC].insert(predecessor);
             }
         }
         /* Compute expired relations in reverse topological order using the set difference of the alive sets
            between steps. */
         std::set_difference(alive[orderedSCC].begin(), alive[orderedSCC].end(), alive[orderedSCC - 1].begin(),
                 alive[orderedSCC - 1].end(),
                 std::inserter(relationExpirySchedule[numSCCs - orderedSCC],
                         relationExpirySchedule[numSCCs - orderedSCC].end()));
     }
     return relationExpirySchedule;
 }
print()
void souffle::ast::analysis::RelationScheduleAnalysis::print (std::ostream & os) const override virtual
Dump this relation schedule to standard error.
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 109 of file RelationSchedule.cpp.
{
     os << "begin schedule\n";
     for (const RelationScheduleAnalysisStep& step : relationSchedule) {
         os << step;
         os << "computed: ";
         for (const Relation* compRel : step.computed()) {
             os << compRel->getQualifiedName() << ", ";
         }
         os << "\nexpired: ";
         for (const Relation* compRel : step.expired()) {
             os << compRel->getQualifiedName() << ", ";
         }
         os << "\n";
         if (step.recursive()) {
             os << "recursive";
         } else {
             os << "not recursive";
         }
         os << "\n";
     }
     os << "end schedule\n";
 }
run()
void souffle::ast::analysis::RelationScheduleAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 53 of file RelationSchedule.cpp.
References souffle::ast::analysis::RelationScheduleAnalysisStep::computedRelations, souffle::ast::TranslationUnit::getAnalysis(), i, and souffle::ast::analysis::SCCGraphAnalysis::isRecursive().
{
     topsortSCCGraphAnalysis = translationUnit.getAnalysis<TopologicallySortedSCCGraphAnalysis>();
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraphAnalysis>();
     size_t numSCCs = translationUnit.getAnalysis<SCCGraphAnalysis>()->getNumberOfSCCs();
     std::vector<std::set<const Relation*>> relationExpirySchedule =
             computeRelationExpirySchedule(translationUnit);
     relationSchedule.clear();
     for (size_t i = 0; i < numSCCs; i++) {
         auto scc = topsortSCCGraphAnalysis->order()[i];
         const std::set<const Relation*> computedRelations =
                 translationUnit.getAnalysis<SCCGraphAnalysis>()->getInternalRelations(scc);
         relationSchedule.emplace_back(computedRelations, relationExpirySchedule[i],
                 translationUnit.getAnalysis<SCCGraphAnalysis>()->isRecursive(scc));
     }
 }
schedule()
const std::vector<RelationScheduleAnalysisStep>& souffle::ast::analysis::RelationScheduleAnalysis::schedule () const inline
Definition at line 82 of file RelationSchedule.h.
References souffle::ast::analysis::RelationScheduleAnalysisStep::print().
{
         return relationSchedule;
     }
Field Documentation
name
constexpr const char* souffle::ast::analysis::RelationScheduleAnalysis::name = "relation-schedule" static
Definition at line 76 of file RelationSchedule.h.
precedenceGraph
PrecedenceGraphAnalysis* souffle::ast::analysis::RelationScheduleAnalysis::precedenceGraph = nullptr private
Definition at line 91 of file RelationSchedule.h.
relationSchedule
std::vector<RelationScheduleAnalysisStep> souffle::ast::analysis::RelationScheduleAnalysis::relationSchedule private
Relations computed and expired relations at each step.
Definition at line 94 of file RelationSchedule.h.
topsortSCCGraphAnalysis
TopologicallySortedSCCGraphAnalysis* souffle::ast::analysis::RelationScheduleAnalysis::topsortSCCGraphAnalysis = nullptr private
Definition at line 90 of file RelationSchedule.h.
The documentation for this class was generated from the following files:
ast/analysis/RelationSchedule.h
ast/analysis/RelationSchedule.cpp