souffle: souffle::ram::analysis::MaxMatching Class Reference
souffle::ram::analysis::MaxMatching Class Reference
Computes a maximum matching with Hopcroft-Karp algorithm
#include <Index.h>
Public Types
using Distance = int
using Matchings = std::unordered_map< Node, Node >
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
using Node = uint32_t
using Nodes = std::unordered_set< Node >
Public Member Functions
void addEdge (Node u, Node v)
add an edge to the bi-partite graph
int getNumMatchings () const
get number of matches in the solution
const Matchings & solve ()
solve the maximum matching problem
Data Fields
const Distance InfiniteDistance = -1
const Node NullVertex = 0
Protected Member Functions
bool bfSearch ()
perform a breadth first search in the graph
bool dfSearch (Node u)
perform a depth first search in the graph
Distance getDistance (Node v)
get distance of a node
Node getMatch (Node v)
get match for a search signature
Private Types
using DistanceMap = std::map< Node, Distance >
distance function of nodes
using Edges = std::unordered_set< Node >
Edges in the bi-partite graph.
using Graph = std::unordered_map< Node, Edges >
Bi-partite graph of instance.
Private Attributes
DistanceMap distance
Graph graph
Matchings match
Detailed Description
Computes a maximum matching with Hopcroft-Karp algorithm
This class is a helper class for RamIndex.
This implements a standard maximum matching algorithm for a bi-partite graph also known as a marriage problem. Given a set of edges in a bi-partite graph select a subset of edges that each node in the bi-partite graph has at most one adjacent edge associated with.
The nodes of the bi-partite graph represent index-signatures stemming from RAM operations and RAM existence checks for a relation. A relation between two nodes represent whether an index operation subsumes another operation.
Source: http://en.wikipedia.org/wiki/Hopcroft%E2%80%93Karp_algorithm#Pseudocode
Definition at line 111 of file Index.h.
Member Typedef Documentation
Distance
using souffle::ram::analysis::MaxMatching::Distance = int
Definition at line 117 of file Index.h.
DistanceMap
using souffle::ram::analysis::MaxMatching::DistanceMap = std::map<Node, Distance> private
distance function of nodes
Definition at line 187 of file Index.h.
Edges
using souffle::ram::analysis::MaxMatching::Edges = std::unordered_set<Node> private
Edges in the bi-partite graph.
Definition at line 179 of file Index.h.
Graph
using souffle::ram::analysis::MaxMatching::Graph = std::unordered_map<Node, Edges> private
Bi-partite graph of instance.
Definition at line 183 of file Index.h.
Matchings
using souffle::ram::analysis::MaxMatching::Matchings = std::unordered_map<Node, Node>
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
If no map exist for a node, there is no adjacent edge exists for that node.
Definition at line 123 of file Index.h.
Node
using souffle::ram::analysis::MaxMatching::Node = uint32_t
Definition at line 113 of file Index.h.
Nodes
using souffle::ram::analysis::MaxMatching::Nodes = std::unordered_set<Node>
Definition at line 115 of file Index.h.
Member Function Documentation
addEdge()
void souffle::ram::analysis::MaxMatching::addEdge (Node u, Node v)
add an edge to the bi-partite graph
Parameters
u search signature
v subsuming search signature
Definition at line 163 of file Index.cpp.
Referenced by souffle::TEST().
{
     assert(u >= 1 && v >= 1 && "Nodes must be greater than or equal to 1");
     if (graph.find(u) == graph.end()) {
         Edges vals;
         vals.insert(v);
         graph.insert(make_pair(u, vals));
     } else {
         graph[u].insert(v);
     }
 }
bfSearch()
bool souffle::ram::analysis::MaxMatching::bfSearch () protected
perform a breadth first search in the graph
Definition at line 190 of file Index.cpp.
{
     Node u;
     std::queue<Node> bfQueue;
     // Build layers
     for (auto& it : graph) {
         if (getMatch(it.first) == NullVertex) {
             distance[it.first] = 0;
             bfQueue.push(it.first);
         } else {
             distance[it.first] = InfiniteDistance;
         }
     }
     distance[NullVertex] = InfiniteDistance;
     while (!bfQueue.empty()) {
         u = bfQueue.front();
         bfQueue.pop();
         assert(u != NullVertex);
         const Edges& children = graph[u];
         for (auto it : children) {
             Node mv = getMatch(it);
             if (getDistance(mv) == InfiniteDistance) {
                 distance[mv] = getDistance(u) + 1;
                 if (mv != NullVertex) {
                     bfQueue.push(mv);
                 }
             }
         }
     }
     return (getDistance(NullVertex) != InfiniteDistance);
 }
dfSearch()
bool souffle::ram::analysis::MaxMatching::dfSearch (Node u) protected
perform a depth first search in the graph
Parameters
u search signature
Definition at line 222 of file Index.cpp.
{
     if (u != 0) {
         Edges& children = graph[u];
         for (auto v : children) {
             if (getDistance(getMatch(v)) == getDistance(u) + 1) {
                 if (dfSearch(getMatch(v))) {
                     match[u] = v;
                     match[v] = u;
                     return true;
                 }
             }
         }
         distance[u] = InfiniteDistance;
         return false;
     }
     return true;
 }
getDistance()
MaxMatching::Distance souffle::ram::analysis::MaxMatching::getDistance (Node v) protected
get distance of a node
Definition at line 182 of file Index.cpp.
{
     auto it = distance.find(v);
     if (it == distance.end()) {
         return InfiniteDistance;
     }
     return it->second;
 }
getMatch()
MaxMatching::Node souffle::ram::analysis::MaxMatching::getMatch (Node v) protected
get match for a search signature
Parameters
v search signature
Definition at line 174 of file Index.cpp.
{
     auto it = match.find(v);
     if (it == match.end()) {
         return NullVertex;
     }
     return it->second;
 }
getNumMatchings()
int souffle::ram::analysis::MaxMatching::getNumMatchings () const inline
get number of matches in the solution
Returns
number of matches
Definition at line 141 of file Index.h.
Referenced by souffle::TEST().
{
         return match.size() / 2;
     }
solve()
const MaxMatching::Matchings & souffle::ram::analysis::MaxMatching::solve ()
solve the maximum matching problem
Returns
returns the matching
Definition at line 241 of file Index.cpp.
Referenced by souffle::TEST().
{
     while (bfSearch()) {
         std::vector<Node> keys(graph.size());
         for (auto& it : graph) {
             keys.push_back(it.first);
         }
         for (auto node : keys) {
             if (getMatch(node) == NullVertex) {
                 dfSearch(node);
             }
         }
     }
     return match;
 }
Field Documentation
distance
DistanceMap souffle::ram::analysis::MaxMatching::distance private
Definition at line 191 of file Index.h.
graph
Graph souffle::ram::analysis::MaxMatching::graph private
Definition at line 190 of file Index.h.
InfiniteDistance
const Distance souffle::ram::analysis::MaxMatching::InfiniteDistance = -1
Definition at line 129 of file Index.h.
match
Matchings souffle::ram::analysis::MaxMatching::match private
Definition at line 189 of file Index.h.
Referenced by souffle::TEST().
NullVertex
const Node souffle::ram::analysis::MaxMatching::NullVertex = 0
Definition at line 126 of file Index.h.
The documentation for this class was generated from the following files:
ram/analysis/Index.h
ram/analysis/Index.cpp