souffle: souffle::ram::TupleOperation Class Reference
souffle::ram::TupleOperation Class Reference abstract
Abstract class for relation searches and lookups.
#include <TupleOperation.h>
Public Member Functions
TupleOperation * clone () const override=0
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for relation searches and lookups.
Definition at line 31 of file TupleOperation.h.
Constructor & Destructor Documentation
TupleOperation()
souffle::ram::TupleOperation::TupleOperation (int ident, Own< Operation > nested, std::string profileText = "") inline
Definition at line 33 of file TupleOperation.h.
References clone().
             : NestedOperation(std::move(nested), std::move(profileText)), identifier(ident) {}
Member Function Documentation
clone()
TupleOperation* souffle::ram::TupleOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::NestedOperation.
Implemented in souffle::ram::IndexOperation, souffle::ram::IndexChoice, souffle::ram::NestedIntrinsicOperator, souffle::ram::UnpackRecord, souffle::ram::Choice, souffle::ram::Aggregate, souffle::ram::ParallelIndexChoice, souffle::ram::IndexAggregate, souffle::ram::ParallelIndexScan, souffle::ram::ParallelAggregate, souffle::ram::IndexScan, souffle::ram::ParallelIndexAggregate, souffle::ram::ParallelChoice, souffle::ram::ParallelScan, souffle::ram::Scan, and souffle::ram::RelationOperation.
Referenced by TupleOperation().
equal()
bool souffle::ram::TupleOperation::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::NestedOperation.
Reimplemented in souffle::ram::UnpackRecord.
Definition at line 53 of file TupleOperation.h.
References souffle::ram::NestedOperation::equal(), and identifier.
Referenced by souffle::ram::RelationOperation::equal(), souffle::ram::UnpackRecord::equal(), and souffle::ram::NestedIntrinsicOperator::equal().
{
         const auto& other = static_cast<const TupleOperation&>(node);
         return NestedOperation::equal(other) && identifier == other.identifier;
     }
getChildNodes()
std::vector<const Node*> souffle::ram::TupleOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::NestedOperation.
Reimplemented in souffle::ram::UnpackRecord.
Definition at line 48 of file TupleOperation.h.
References souffle::ram::NestedOperation::getChildNodes().
Referenced by souffle::ram::RelationOperation::getChildNodes(), souffle::ram::UnpackRecord::getChildNodes(), and souffle::ram::NestedIntrinsicOperator::getChildNodes().
{
         return NestedOperation::getChildNodes();
     }
getTupleId()
int souffle::ram::TupleOperation::getTupleId () const inline
Get identifier.
Definition at line 39 of file TupleOperation.h.
References identifier.
Referenced by souffle::ram::Scan::clone(), souffle::ram::ParallelScan::clone(), souffle::ram::ParallelChoice::clone(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::IndexScan::clone(), souffle::ram::ParallelIndexScan::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::Aggregate::clone(), souffle::ram::Choice::clone(), souffle::ram::UnpackRecord::clone(), souffle::ram::IndexChoice::clone(), souffle::ram::IndexOperation::clone(), souffle::synthesiser::Synthesiser::emitCode(), souffle::InterpreterEngine::executeAggregate(), souffle::ram::transform::HoistConditionsTransformer::hoistConditions(), souffle::ram::Scan::print(), souffle::ram::ParallelScan::print(), souffle::ram::ParallelChoice::print(), souffle::ram::ParallelAggregate::print(), souffle::ram::IndexScan::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::ParallelIndexScan::print(), souffle::ram::Aggregate::print(), souffle::ram::Choice::print(), souffle::ram::ParallelIndexChoice::print(), souffle::ram::IndexAggregate::print(), souffle::ram::UnpackRecord::print(), souffle::ram::IndexChoice::print(), souffle::ram::IndexOperation::printIndex(), souffle::ram::transform::TupleIdTransformer::reorderOperations(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteScan().
{
         return identifier;
     }
setTupleId()
void souffle::ram::TupleOperation::setTupleId (int id) inline
Set identifier.
Definition at line 44 of file TupleOperation.h.
References identifier.
{
         identifier = id;
     }
Field Documentation
identifier
int souffle::ram::TupleOperation::identifier protected
Identifier for the tuple, corresponding to its position in the loop nest.
Definition at line 62 of file TupleOperation.h.
Referenced by souffle::ram::ParallelAggregate::clone(), equal(), getTupleId(), and setTupleId().
The documentation for this class was generated from the following file:
ram/TupleOperation.h