souffle: souffle::ram::transform::ReorderConditionsTransformer Class Reference
souffle::ram::transform::ReorderConditionsTransformer Class Reference
Reorders conjunctive terms depending on cost, i.e., cheap terms should be executed first.
#include <ReorderConditions.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool reorderConditions (Program &program)
Reorder conjunctive terms in filter operations.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
analysis::ComplexityAnalysis * rca {nullptr}
Detailed Description
Reorders conjunctive terms depending on cost, i.e., cheap terms should be executed first.
For example ..
QUERY
 ...
  IF C(1) /\ C(2) /\ ... /\ C(N) then
   ...
will be rewritten to
QUERY
 ...
  IF C(i(1)) /\ C(i(2)) /\ ... /\ C(i(N)) then
    ...
where C(i(1)) <= C(i(2)) <= .... <= C(i(N)).
The terms are sorted according to their complexity class.
Definition at line 54 of file ReorderConditions.h.
Member Function Documentation
getName()
std::string souffle::ram::transform::ReorderConditionsTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 56 of file ReorderConditions.h.
References reorderConditions().
{
         return "ReorderConditionsTransformer";
     }
reorderConditions()
bool souffle::ram::transform::ReorderConditionsTransformer::reorderConditions (Program & program)
Reorder conjunctive terms in filter operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 32 of file ReorderConditions.cpp.
References souffle::ram::transform::Transformer::apply(), b, souffle::clone(), souffle::filter(), souffle::ram::analysis::ComplexityAnalysis::getComplexity(), souffle::ram::makeLambdaRamMapper(), rca, souffle::ram::toCondition(), souffle::ram::toConjunctionList(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> filterRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const Filter* filter = dynamic_cast<Filter*>(node.get())) {
                 const Condition* condition = &filter->getCondition();
                 VecOwn<Condition> sortedConds;
                 VecOwn<Condition> condList = toConjunctionList(condition);
                 for (auto& cond : condList) {
                     sortedConds.emplace_back(cond->clone());
                 }
                 std::sort(sortedConds.begin(), sortedConds.end(), [&](Own<Condition>& a, Own<Condition>& b) {
                     return rca->getComplexity(a.get()) < rca->getComplexity(b.get());
                 });
                 if (!std::equal(sortedConds.begin(), sortedConds.end(), condList.begin(),
                             [](Own<Condition>& a, Own<Condition>& b) { return *a == *b; })) {
                     changed = true;
                     node = mk<Filter>(Own<Condition>(toCondition(sortedConds)),
                             souffle::clone(&filter->getOperation()));
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
transform()
bool souffle::ram::transform::ReorderConditionsTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 71 of file ReorderConditions.h.
References souffle::ram::TranslationUnit::getAnalysis(), souffle::ram::TranslationUnit::getProgram(), rca, and reorderConditions().
{
         rca = translationUnit.getAnalysis<analysis::ComplexityAnalysis>();
         return reorderConditions(translationUnit.getProgram());
     }
Field Documentation
rca
analysis::ComplexityAnalysis* souffle::ram::transform::ReorderConditionsTransformer::rca {nullptr} protected
Definition at line 69 of file ReorderConditions.h.
Referenced by reorderConditions(), and transform().
The documentation for this class was generated from the following files:
ram/transform/ReorderConditions.h
ram/transform/ReorderConditions.cpp