souffle: souffle::ram::AbstractChoice Class Reference
souffle::ram::AbstractChoice Class Reference
Abstract class for a choice operation.
#include <AbstractChoice.h>
Public Member Functions
AbstractChoice (Own< Condition > cond)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Getter for the condition.
Protected Member Functions
bool equal (const Node &node) const
Protected Attributes
Own< Condition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Abstract class for a choice operation.
Finding a single tuple, if it exists, such that a condition holds.
Definition at line 34 of file AbstractChoice.h.
Constructor & Destructor Documentation
AbstractChoice()
souffle::ram::AbstractChoice::AbstractChoice (Own< Condition > cond) inline
Definition at line 36 of file AbstractChoice.h.
References condition.
                                         : condition(std::move(cond)) {
         assert(condition != nullptr && "Condition is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::AbstractChoice::apply (const NodeMapper & map) inline
Definition at line 46 of file AbstractChoice.h.
References condition, and souffle::map().
Referenced by souffle::ram::Choice::apply(), and souffle::ram::IndexChoice::apply().
{
         condition = map(std::move(condition));
     }
equal()
bool souffle::ram::AbstractChoice::equal (const Node & node) const inline protected
Definition at line 55 of file AbstractChoice.h.
References condition, and souffle::equal_ptr().
Referenced by souffle::ram::Choice::equal(), and souffle::ram::IndexChoice::equal().
{
         const auto& other = dynamic_cast<const AbstractChoice&>(node);
         return equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::AbstractChoice::getChildNodes () const inline
Definition at line 50 of file AbstractChoice.h.
References condition.
Referenced by souffle::ram::Choice::getChildNodes(), and souffle::ram::IndexChoice::getChildNodes().
{
         return {condition.get()};
     }
getCondition()
const Condition& souffle::ram::AbstractChoice::getCondition () const inline
Getter for the condition.
Definition at line 41 of file AbstractChoice.h.
References condition.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::ParallelChoice::print(), souffle::ram::Choice::print(), souffle::ram::ParallelIndexChoice::print(), and souffle::ram::IndexChoice::print().
{
         assert(condition != nullptr && "condition of choice is a null-pointer");
         return *condition;
     }
Field Documentation
condition
Own<Condition> souffle::ram::AbstractChoice::condition protected
Condition for which a tuple in the relation may hold.
Definition at line 61 of file AbstractChoice.h.
Referenced by AbstractChoice(), apply(), souffle::ram::ParallelChoice::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::Choice::clone(), souffle::ram::IndexChoice::clone(), equal(), getChildNodes(), and getCondition().
The documentation for this class was generated from the following file:
ram/AbstractChoice.h