souffle: souffle::ram::ProvenanceExistenceCheck Class Reference
souffle::ram::ProvenanceExistenceCheck Class Reference
Provenance Existence check for a relation.
#include <ProvenanceExistenceCheck.h>
Public Member Functions
ProvenanceExistenceCheck * clone () const override
Create a clone (i.e.
ProvenanceExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals)
Public Member Functions inherited from souffle::ram::AbstractExistenceCheck
AbstractExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get relation.
const std::vector< Expression * > getValues () const
Get arguments of the tuple/pattern A null pointer element in the vector denotes an unspecified pattern for a tuple element.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractExistenceCheck
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::ram::AbstractExistenceCheck
Own< RelationReference > relationRef
Relation.
VecOwn< Expression > values
Pattern – nullptr if undefined.
Detailed Description
Provenance Existence check for a relation.
Definition at line 35 of file ProvenanceExistenceCheck.h.
Constructor & Destructor Documentation
ProvenanceExistenceCheck()
souffle::ram::ProvenanceExistenceCheck::ProvenanceExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals) inline
Definition at line 37 of file ProvenanceExistenceCheck.h.
Referenced by clone().
             : AbstractExistenceCheck(std::move(relRef), std::move(vals)) {}
Member Function Documentation
clone()
ProvenanceExistenceCheck* souffle::ram::ProvenanceExistenceCheck::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Condition.
Definition at line 40 of file ProvenanceExistenceCheck.h.
References souffle::clone(), ProvenanceExistenceCheck(), souffle::ram::AbstractExistenceCheck::relationRef, and souffle::ram::AbstractExistenceCheck::values.
Referenced by souffle::ram::test::TEST().
{
         VecOwn<Expression> newValues;
         for (auto& cur : values) {
             newValues.emplace_back(cur->clone());
         }
         return new ProvenanceExistenceCheck(souffle::clone(relationRef), std::move(newValues));
     }
print()
void souffle::ram::ProvenanceExistenceCheck::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Reimplemented from souffle::ram::AbstractExistenceCheck.
Definition at line 49 of file ProvenanceExistenceCheck.h.
References souffle::ram::AbstractExistenceCheck::print().
{
         os << "prov";
         AbstractExistenceCheck::print(os);
     }
The documentation for this class was generated from the following file:
ram/ProvenanceExistenceCheck.h