souffle: souffle::ast::BranchInit Class Reference
souffle::ast::BranchInit Class Reference
Initialization of ADT instance.
#include <BranchInit.h>
Public Member Functions
BranchInit (std::string constructor, VecOwn< Argument > args, SrcLocation loc={})
BranchInit * clone () const override
Create clone.
const std::string & getConstructor () const
Public Member Functions inherited from souffle::ast::Term
void addArgument (Own< Argument > arg)
Add argument to argument list.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Argument * > getArguments () const
Get arguments.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Implements the node comparison for this node type.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::ast::Term
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
template<typename... Operands>
Term (Operands &&... operands)
template<typename... Operands>
Term (SrcLocation loc, Operands &&... operands)
Term (VecOwn< Argument > operands, SrcLocation loc={})
Private Attributes
std::string constructor
The adt branch constructor.
Additional Inherited Members
Protected Attributes inherited from souffle::ast::Term
VecOwn< Argument > args
Arguments.
Detailed Description
Initialization of ADT instance.
Parameters
constructor An entity used to create a variant type. Can be though of as a name of the branch.
Initializes one of the branches of ADT. The syntax for branches initialization is $Constructor(args...) In case of the branch with no arguments it is simplified to $Constructor.
Definition at line 43 of file BranchInit.h.
Constructor & Destructor Documentation
BranchInit()
souffle::ast::BranchInit::BranchInit (std::string constructor, VecOwn< Argument > args, SrcLocation loc = {}) inline
Definition at line 45 of file BranchInit.h.
References constructor, and souffle::ast::Term::Term().
Referenced by clone().
                                                                                {})
             : Term(std::move(args), std::move(loc)), constructor(std::move(constructor)) {}
Member Function Documentation
clone()
BranchInit* souffle::ast::BranchInit::clone () const inline override virtual
Create clone.
Implements souffle::ast::Argument.
Definition at line 52 of file BranchInit.h.
References BranchInit(), souffle::clone(), and souffle::ast::Node::getSrcLoc().
{
         return new BranchInit(constructor, souffle::clone(args), getSrcLoc());
     }
equal()
bool souffle::ast::BranchInit::equal (const Node & node) const inline override protected virtual
Implements the node comparison for this node type.
Reimplemented from souffle::ast::Node.
Definition at line 62 of file BranchInit.h.
References souffle::equal_targets().
{
         const auto& other = dynamic_cast<const BranchInit&>(node);
         return (constructor == other.constructor) && equal_targets(args, other.args);
     }
getConstructor()
const std::string& souffle::ast::BranchInit::getConstructor () const inline
Definition at line 48 of file BranchInit.h.
References constructor.
Referenced by souffle::ast::transform::TypeChecker::visitBranchInit(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitBranchInit().
{
         return constructor;
     }
print()
void souffle::ast::BranchInit::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 57 of file BranchInit.h.
References tinyformat::format(), and souffle::join().
{
         os << tfm::format("$%s(%s)", constructor, join(args, ", "));
     }
Field Documentation
constructor
std::string souffle::ast::BranchInit::constructor private
The adt branch constructor.
Definition at line 69 of file BranchInit.h.
Referenced by BranchInit(), and getConstructor().
The documentation for this class was generated from the following file:
ast/BranchInit.h