souffle: souffle::ast::analysis::AlgebraicDataType Class Reference
souffle::ast::analysis::AlgebraicDataType Class Reference
Aggregates types using sums and products.
#include <TypeSystem.h>
Data Structures
struct Branch
Public Member Functions
const std::vector< Branch > & getBranches () const
Return the branches as a sorted vector.
const std::vector< const Type * > & getBranchTypes (const std::string &constructor) const
void print (std::ostream &out) const override
void setBranches (std::vector< Branch > bs)
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Private Member Functions
AlgebraicDataType (const TypeEnvironment &env, QualifiedName name)
Private Attributes
std::vector< Branch > branches
Friends
class TypeEnvironment
Additional Inherited Members
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Detailed Description
Aggregates types using sums and products.
Invariant: branches are in stored in lexicographical order.
Definition at line 216 of file TypeSystem.h.
Constructor & Destructor Documentation
AlgebraicDataType()
souffle::ast::analysis::AlgebraicDataType::AlgebraicDataType (const TypeEnvironment & env, QualifiedName name) inline private
Definition at line 253 of file TypeSystem.h.
 : Type(env, std::move(name)) {}
Member Function Documentation
getBranches()
const std::vector<Branch>& souffle::ast::analysis::AlgebraicDataType::getBranches () const inline
Return the branches as a sorted vector.
Definition at line 248 of file TypeSystem.h.
Referenced by souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes().
{
         return branches;
     }
getBranchTypes()
const std::vector<const Type*>& souffle::ast::analysis::AlgebraicDataType::getBranchTypes (const std::string & constructor) const inline
Definition at line 239 of file TypeSystem.h.
{
         for (auto& branch : branches) {
             if (branch.name == constructor) return branch.types;
         }
         // Branch doesn't exist.
         throw std::out_of_range("Trying to access non-existing branch.");
     }
print()
void souffle::ast::analysis::AlgebraicDataType::print (std::ostream & out) const inline override virtual
Reimplemented from souffle::ast::analysis::Type.
Definition at line 228 of file TypeSystem.h.
References tinyformat::format(), souffle::join(), souffle::ast::analysis::Type::name, and souffle::ast::analysis::AlgebraicDataType::Branch::print().
{
         out << tfm::format("%s = %s", name,
                 join(branches, " | ", [](std::ostream& out, const Branch& branch) { branch.print(out); }));
     }
setBranches()
void souffle::ast::analysis::AlgebraicDataType::setBranches (std::vector< Branch > bs) inline
Definition at line 233 of file TypeSystem.h.
References souffle::ast::analysis::AlgebraicDataType::Branch::name.
{
         branches = std::move(bs);
         std::sort(branches.begin(), branches.end(),
                 [](const Branch& left, const Branch& right) { return left.name < right.name; });
     }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 255 of file TypeSystem.h.
Field Documentation
branches
std::vector<Branch> souffle::ast::analysis::AlgebraicDataType::branches private
Definition at line 257 of file TypeSystem.h.
The documentation for this class was generated from the following file:
ast/analysis/TypeSystem.h