souffle: souffle::ast::transform::IOAttributesTransformer Class Reference
souffle::ast::transform::IOAttributesTransformer Class Reference
Transformation pass to set attribute names and types in IO operations.
#include <IOAttributes.h>
Public Member Functions
IOAttributesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
json11::Json getAlgebraicDataTypes (TranslationUnit &translationUnit) const
Get sum types info for IO.
json11::Json getRecordsParams (TranslationUnit &translationUnit) const
json11::Json getRecordsTypes (TranslationUnit &translationUnit) const
std::string getRelationName (const Directive *node)
bool setAttributeNames (TranslationUnit &translationUnit)
bool setAttributeParams (TranslationUnit &translationUnit)
bool setAttributeTypes (TranslationUnit &translationUnit)
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to set attribute names and types in IO operations.
Definition at line 53 of file IOAttributes.h.
Member Function Documentation
clone()
IOAttributesTransformer* souffle::ast::transform::IOAttributesTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 59 of file IOAttributes.h.
{
         return new IOAttributesTransformer();
     }
getAlgebraicDataTypes()
json11::Json souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes (TranslationUnit & translationUnit) const inline private
Get sum types info for IO.
If they don't exists - create them.
The structure of JSON is approximately: {"ADTs" : {ADT_NAME : {"branches" : [branch..]}, {"arity": ...}}} branch = {{"types": [types ...]}, ["name": ...]}
Definition at line 188 of file IOAttributes.h.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::analysis::AlgebraicDataType::getBranches(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::analysis::getTypeQualifier(), souffle::ast::Program::getTypes(), json11::Json::is_null(), and souffle::ast::visitDepthFirst().
Referenced by setAttributeTypes().
{
         static json11::Json sumTypesInfo;
         // Check if the types were already constructed
         if (!sumTypesInfo.is_null()) {
             return sumTypesInfo;
         }
         Program& program = translationUnit.getProgram();
         auto& typeEnv =
                 translationUnit.getAnalysis<analysis::TypeEnvironmentAnalysis>()->getTypeEnvironment();
         std::map<std::string, json11::Json> sumTypes;
         visitDepthFirst(program.getTypes(), [&](const AlgebraicDataType& astAlgebraicDataType) {
             auto& sumType =
                     dynamic_cast<const analysis::AlgebraicDataType&>(typeEnv.getType(astAlgebraicDataType));
             auto& branches = sumType.getBranches();
             std::vector<json11::Json> branchesInfo;
             for (const auto& branch : branches) {
                 std::vector<json11::Json> branchTypes;
                 for (auto* type : branch.types) {
                     branchTypes.push_back(getTypeQualifier(*type));
                 }
                 auto branchInfo =
                         json11::Json::object{{{"types", std::move(branchTypes)}, {"name", branch.name}}};
                 branchesInfo.push_back(std::move(branchInfo));
             }
             auto typeQualifier = analysis::getTypeQualifier(sumType);
             auto&& sumInfo = json11::Json::object{{{"branches", std::move(branchesInfo)},
                     {"arity", static_cast<long long>(branches.size())}}};
             sumTypes.emplace(std::move(typeQualifier), std::move(sumInfo));
         });
         sumTypesInfo = json11::Json(sumTypes);
         return sumTypesInfo;
     }
getName()
std::string souffle::ast::transform::IOAttributesTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 55 of file IOAttributes.h.
{
         return "IOAttributesTransformer";
     }
getRecordsParams()
json11::Json souffle::ast::transform::IOAttributesTransformer::getRecordsParams (TranslationUnit & translationUnit) const inline private
Definition at line 264 of file IOAttributes.h.
References souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getTypes(), and json11::Json::is_null().
Referenced by setAttributeParams().
{
         static json11::Json ramRecordParams;
         // Check if the types where already constructed
         if (!ramRecordParams.is_null()) {
             return ramRecordParams;
         }
         Program& program = translationUnit.getProgram();
         std::vector<std::string> elementParams;
         std::map<std::string, json11::Json> records;
         // Iterate over all record types in the program populating the records map.
         for (auto* astType : program.getTypes()) {
             if (isA<ast::RecordType>(astType)) {
                 elementParams.clear();
                 for (const auto field : as<ast::RecordType>(astType)->getFields()) {
                     elementParams.push_back(field->getName());
                 }
                 const size_t recordArity = elementParams.size();
                 json11::Json recordInfo = json11::Json::object{
                         {"params", std::move(elementParams)}, {"arity", static_cast<long long>(recordArity)}};
                 records.emplace(astType->getQualifiedName().toString(), std::move(recordInfo));
             }
         }
         ramRecordParams = json11::Json(records);
         return ramRecordParams;
     }
getRecordsTypes()
json11::Json souffle::ast::transform::IOAttributesTransformer::getRecordsTypes (TranslationUnit & translationUnit) const inline private
Definition at line 231 of file IOAttributes.h.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::analysis::getTypeQualifier(), souffle::ast::Program::getTypes(), and json11::Json::is_null().
Referenced by setAttributeTypes().
{
         static json11::Json ramRecordTypes;
         // Check if the types where already constructed
         if (!ramRecordTypes.is_null()) {
             return ramRecordTypes;
         }
         Program& program = translationUnit.getProgram();
         auto typeEnv =
                 &translationUnit.getAnalysis<analysis::TypeEnvironmentAnalysis>()->getTypeEnvironment();
         std::vector<std::string> elementTypes;
         std::map<std::string, json11::Json> records;
         // Iterate over all record types in the program populating the records map.
         for (auto* astType : program.getTypes()) {
             const auto& type = typeEnv->getType(*astType);
             if (isA<analysis::RecordType>(type)) {
                 elementTypes.clear();
                 for (const analysis::Type* field : as<analysis::RecordType>(type)->getFields()) {
                     elementTypes.push_back(getTypeQualifier(*field));
                 }
                 const size_t recordArity = elementTypes.size();
                 json11::Json recordInfo = json11::Json::object{
                         {"types", std::move(elementTypes)}, {"arity", static_cast<long long>(recordArity)}};
                 records.emplace(getTypeQualifier(type), std::move(recordInfo));
             }
         }
         ramRecordTypes = json11::Json(records);
         return ramRecordTypes;
     }
getRelationName()
std::string souffle::ast::transform::IOAttributesTransformer::getRelationName (const Directive * node) inline private
Definition at line 176 of file IOAttributes.h.
References souffle::ast::Directive::getQualifiedName(), souffle::ast::QualifiedName::getQualifiers(), souffle::join(), and souffle::toString().
{
         return toString(join(node->getQualifiedName().getQualifiers(), "."));
     }
setAttributeNames()
bool souffle::ast::transform::IOAttributesTransformer::setAttributeNames (TranslationUnit & translationUnit) inline private
Definition at line 107 of file IOAttributes.h.
References souffle::Global::config(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Relation::getAttributes(), souffle::ast::Program::getDirectives(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::getRelation(), souffle::join(), souffle::ast::limitsize, and souffle::toString().
Referenced by transform().
{
         bool changed = false;
         Program& program = translationUnit.getProgram();
         for (Directive* io : program.getDirectives()) {
             if (io->getType() == ast::DirectiveType::limitsize) {
                 continue;
             }
             if (io->hasParameter("attributeNames")) {
                 continue;
             }
             Relation* rel = getRelation(program, io->getQualifiedName());
             std::string delimiter("\t");
             if (io->hasParameter("delimiter")) {
                 delimiter = io->getParameter("delimiter");
             }
             std::vector<std::string> attributeNames;
             for (const auto* attribute : rel->getAttributes()) {
                 attributeNames.push_back(attribute->getName());
             }
             if (Global::config().has("provenance")) {
                 auto auxArityAnalysis = translationUnit.getAnalysis<analysis::AuxiliaryArityAnalysis>();
                 std::vector<std::string> originalAttributeNames(
                         attributeNames.begin(), attributeNames.end() - auxArityAnalysis->getArity(rel));
                 io->addParameter("attributeNames", toString(join(originalAttributeNames, delimiter)));
             } else {
                 io->addParameter("attributeNames", toString(join(attributeNames, delimiter)));
             }
             changed = true;
         }
         return changed;
     }
setAttributeParams()
bool souffle::ast::transform::IOAttributesTransformer::setAttributeParams (TranslationUnit & translationUnit) inline private
Definition at line 74 of file IOAttributes.h.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Relation::getArity(), souffle::ast::Relation::getAttributes(), souffle::ast::Program::getDirectives(), souffle::ast::TranslationUnit::getProgram(), getRecordsParams(), souffle::ast::getRelation(), and souffle::ast::limitsize.
Referenced by transform().
{
         bool changed = false;
         Program& program = translationUnit.getProgram();
         auto auxArityAnalysis = translationUnit.getAnalysis<analysis::AuxiliaryArityAnalysis>();
         for (Directive* io : program.getDirectives()) {
             if (io->getType() == ast::DirectiveType::limitsize) {
                 continue;
             }
             Relation* rel = getRelation(program, io->getQualifiedName());
             // Prepare type system information.
             std::vector<std::string> attributesParams;
             for (const auto* attribute : rel->getAttributes()) {
                 attributesParams.push_back(attribute->getName());
             }
             // Casting due to json11.h type requirements.
             long long arity{static_cast<long long>(rel->getArity() - auxArityAnalysis->getArity(rel))};
             long long auxArity{static_cast<long long>(auxArityAnalysis->getArity(rel))};
             json11::Json relJson = json11::Json::object{{"arity", arity}, {"auxArity", auxArity},
                     {"params", json11::Json::array(attributesParams.begin(), attributesParams.end())}};
             json11::Json params = json11::Json::object{
                     {"relation", relJson}, {"records", getRecordsParams(translationUnit)}};
             io->addParameter("params", params.dump());
             changed = true;
         }
         return changed;
     }
setAttributeTypes()
bool souffle::ast::transform::IOAttributesTransformer::setAttributeTypes (TranslationUnit & translationUnit) inline private
Definition at line 141 of file IOAttributes.h.
References getAlgebraicDataTypes(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Relation::getArity(), souffle::ast::Relation::getAttributes(), souffle::ast::Program::getDirectives(), souffle::ast::TranslationUnit::getProgram(), getRecordsTypes(), souffle::ast::getRelation(), souffle::ast::analysis::getTypeQualifier(), and types.
Referenced by transform().
{
         bool changed = false;
         Program& program = translationUnit.getProgram();
         auto auxArityAnalysis = translationUnit.getAnalysis<analysis::AuxiliaryArityAnalysis>();
         auto typeEnv =
                 &translationUnit.getAnalysis<analysis::TypeEnvironmentAnalysis>()->getTypeEnvironment();
         for (Directive* io : program.getDirectives()) {
             Relation* rel = getRelation(program, io->getQualifiedName());
             // Prepare type system information.
             std::vector<std::string> attributesTypes;
             for (const auto* attribute : rel->getAttributes()) {
                 auto typeName = attribute->getTypeName();
                 auto type = getTypeQualifier(typeEnv->getType(typeName));
                 attributesTypes.push_back(type);
             }
             // Casting due to json11.h type requirements.
             long long arity{static_cast<long long>(rel->getArity() - auxArityAnalysis->getArity(rel))};
             long long auxArity{static_cast<long long>(auxArityAnalysis->getArity(rel))};
             json11::Json relJson = json11::Json::object{{"arity", arity}, {"auxArity", auxArity},
                     {"types", json11::Json::array(attributesTypes.begin(), attributesTypes.end())}};
             json11::Json types =
                     json11::Json::object{{"relation", relJson}, {"records", getRecordsTypes(translationUnit)},
                             {"ADTs", getAlgebraicDataTypes(translationUnit)}};
             io->addParameter("types", types.dump());
             changed = true;
         }
         return changed;
     }
transform()
bool souffle::ast::transform::IOAttributesTransformer::transform (TranslationUnit & translationUnit) inline override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 64 of file IOAttributes.h.
References setAttributeNames(), setAttributeParams(), and setAttributeTypes().
{
         bool changed = false;
         changed |= setAttributeNames(translationUnit);
         changed |= setAttributeTypes(translationUnit);
         changed |= setAttributeParams(translationUnit);
         return changed;
     }
The documentation for this class was generated from the following file:
ast/transform/IOAttributes.h