souffle: souffle::ast::Relation Class Reference
souffle::ast::Relation Class Reference
Defines a relation with a name, attributes, qualifiers, and internal representation.
#include <Relation.h>
Public Member Functions
void addAttribute (Own< Attribute > attr)
Add a new used type to this relation.
void addQualifier (RelationQualifier q)
Add qualifier to this relation.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Relation * clone () const override
Create a clone (i.e.
size_t getArity () const
Return the arity of this relation.
std::vector< Attribute * > getAttributes () const
Get relation attributes.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const QualifiedName & getQualifiedName () const
Get qualified relation name.
const std::set< RelationQualifier > & getQualifiers () const
Get relation qualifiers.
RelationRepresentation getRepresentation () const
Get relation representation.
bool hasQualifier (RelationQualifier q) const
Check for a relation qualifier.
Relation ()=default
Relation (QualifiedName name, SrcLocation loc={})
void removeQualifier (RelationQualifier q)
Remove qualifier from this relation.
void setAttributes (VecOwn< Attribute > attrs)
Set relation attributes.
void setQualifiedName (QualifiedName n)
Set name for this relation.
void setRepresentation (RelationRepresentation representation)
Set relation representation.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< Attribute > attributes
Attributes of the relation.
QualifiedName name
Name of relation.
std::set< RelationQualifier > qualifiers
Qualifiers of relation.
RelationRepresentation representation {RelationRepresentation::DEFAULT}
Datastructure to use for this relation.
Detailed Description
Defines a relation with a name, attributes, qualifiers, and internal representation.
Definition at line 43 of file Relation.h.
Constructor & Destructor Documentation
Relation() [1/2]
souffle::ast::Relation::Relation () default
Referenced by clone().
Relation() [2/2]
souffle::ast::Relation::Relation (QualifiedName name, SrcLocation loc = {}) inline
Definition at line 46 of file Relation.h.
References name, and souffle::ast::Node::setSrcLoc().
                                                    {}) : name(std::move(name)) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
addAttribute()
void souffle::ast::Relation::addAttribute (Own< Attribute > attr) inline
Add a new used type to this relation.
Definition at line 61 of file Relation.h.
References attributes.
{
         assert(attr && "Undefined attribute");
         attributes.push_back(std::move(attr));
     }
addQualifier()
void souffle::ast::Relation::addQualifier (RelationQualifier q) inline
Add qualifier to this relation.
Definition at line 87 of file Relation.h.
References qualifiers.
{
         qualifiers.insert(q);
     }
apply()
void souffle::ast::Relation::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 119 of file Relation.h.
References attributes, and souffle::map().
{
         for (auto& cur : attributes) {
             cur = map(std::move(cur));
         }
     }
clone()
Relation* souffle::ast::Relation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 111 of file Relation.h.
References attributes, souffle::clone(), souffle::ast::Node::getSrcLoc(), qualifiers, Relation(), and representation.
{
         auto res = new Relation(name, getSrcLoc());
         res->attributes = souffle::clone(attributes);
         res->qualifiers = qualifiers;
         res->representation = representation;
         return res;
     }
equal()
bool souffle::ast::Relation::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 139 of file Relation.h.
References attributes, and souffle::equal_targets().
{
         const auto& other = static_cast<const Relation&>(node);
         return name == other.name && equal_targets(attributes, other.attributes);
     }
getArity()
size_t souffle::ast::Relation::getArity () const inline
Return the arity of this relation.
Definition at line 67 of file Relation.h.
References attributes.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration(), souffle::ast::transform::IOAttributesTransformer::setAttributeParams(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), and souffle::ast::transform::transformEqrelRelation().
{
         return attributes.size();
     }
getAttributes()
std::vector<Attribute*> souffle::ast::Relation::getAttributes () const inline
Get relation attributes.
Definition at line 77 of file Relation.h.
References attributes, and souffle::toPtrVector().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::transform::IOAttributesTransformer::setAttributeParams(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), and souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform().
{
         return toPtrVector(attributes);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Relation::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 125 of file Relation.h.
References attributes.
{
         std::vector<const Node*> res;
         for (const auto& cur : attributes) {
             res.push_back(cur.get());
         }
         return res;
     }
getQualifiedName()
const QualifiedName& souffle::ast::Relation::getQualifiedName () const inline
Get qualified relation name.
Definition at line 51 of file Relation.h.
References name.
Referenced by souffle::ParserDriver::addIoFromDeprecatedTag(), souffle::ast::Program::addRelation(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::findInlineCycle(), souffle::ast::analysis::RelationDetailCacheAnalysis::getClauses(), souffle::ast::getClauses(), souffle::AstToRamTranslator::getInputDirectives(), souffle::AstToRamTranslator::getOutputDirectives(), souffle::ast::NameComparison::operator()(), print(), souffle::ast::analysis::SCCGraphAnalysis::print(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::transformEqrelRelation(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), and souffle::AstToRamTranslator::translateRelation().
{
         return name;
     }
getQualifiers()
const std::set<RelationQualifier>& souffle::ast::Relation::getQualifiers () const inline
Get relation qualifiers.
Definition at line 82 of file Relation.h.
References qualifiers.
{
         return qualifiers;
     }
getRepresentation()
RelationRepresentation souffle::ast::Relation::getRepresentation () const inline
Get relation representation.
Definition at line 97 of file Relation.h.
References representation.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelation(), and souffle::ast::transform::transformEqrelRelation().
{
         return representation;
     }
hasQualifier()
bool souffle::ast::Relation::hasQualifier (RelationQualifier q) const inline
Check for a relation qualifier.
Definition at line 107 of file Relation.h.
References qualifiers.
Referenced by souffle::ParserDriver::addIoFromDeprecatedTag(), souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::containsInlinedAtom(), and souffle::ast::transform::getInlinedLiteral().
{
         return qualifiers.find(q) != qualifiers.end();
     }
print()
void souffle::ast::Relation::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 134 of file Relation.h.
References attributes, getQualifiedName(), souffle::join(), qualifiers, and representation.
{
         os << ".decl " << getQualifiedName() << "(" << join(attributes, ", ") << ")" << join(qualifiers, " ")
            << " " << representation;
     }
removeQualifier()
void souffle::ast::Relation::removeQualifier (RelationQualifier q) inline
Remove qualifier from this relation.
Definition at line 92 of file Relation.h.
References qualifiers.
{
         qualifiers.erase(q);
     }
setAttributes()
void souffle::ast::Relation::setAttributes (VecOwn< Attribute > attrs) inline
Set relation attributes.
Definition at line 72 of file Relation.h.
References attributes.
{
         attributes = std::move(attrs);
     }
setQualifiedName()
void souffle::ast::Relation::setQualifiedName (QualifiedName n) inline
Set name for this relation.
Definition at line 56 of file Relation.h.
{
         name = std::move(n);
     }
setRepresentation()
void souffle::ast::Relation::setRepresentation (RelationRepresentation representation) inline
Set relation representation.
Definition at line 102 of file Relation.h.
References representation.
Referenced by souffle::ast::transform::transformEqrelRelation().
{
         this->representation = representation;
     }
Field Documentation
attributes
VecOwn<Attribute> souffle::ast::Relation::attributes protected
Attributes of the relation.
Definition at line 148 of file Relation.h.
Referenced by addAttribute(), apply(), clone(), equal(), getArity(), getAttributes(), getChildNodes(), print(), and setAttributes().
name
QualifiedName souffle::ast::Relation::name protected
Name of relation.
Definition at line 145 of file Relation.h.
Referenced by getQualifiedName(), and Relation().
qualifiers
std::set<RelationQualifier> souffle::ast::Relation::qualifiers protected
Qualifiers of relation.
Definition at line 151 of file Relation.h.
Referenced by addQualifier(), clone(), getQualifiers(), hasQualifier(), print(), and removeQualifier().
representation
RelationRepresentation souffle::ast::Relation::representation {RelationRepresentation::DEFAULT} protected
Datastructure to use for this relation.
Definition at line 154 of file Relation.h.
Referenced by clone(), getRepresentation(), print(), and setRepresentation().
The documentation for this class was generated from the following file:
ast/Relation.h