souffle: souffle::ast::Clause Class Reference
souffle::ast::Clause Class Reference
Intermediate representation of a horn clause.
#include <Clause.h>
Public Member Functions
void addToBody (Own< Literal > literal)
Add a literal to the body of the clause.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Clause (Own< Atom > head={}, VecOwn< Literal > bodyLiterals={}, Own< ExecutionPlan > plan={}, SrcLocation loc={})
void clearExecutionPlan ()
Resets the execution plan.
Clause * clone () const override
Create a clone (i.e.
std::vector< Literal * > getBodyLiterals () const
Obtains a copy of the internally maintained body literals.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const ExecutionPlan * getExecutionPlan () const
Obtains the execution plan associated to this clause or null if there is none.
Atom * getHead () const
Return the atom that represents the head of the clause.
void setBodyLiterals (VecOwn< Literal > body)
Set the bodyLiterals of clause to body.
void setExecutionPlan (Own< ExecutionPlan > plan)
Updates the execution plan associated to this clause.
void setHead (Own< Atom > h)
Set the head of clause to h.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< Literal > bodyLiterals
Body literals of clause.
Own< Atom > head
Head of the clause.
Own< ExecutionPlan > plan
User defined execution plan (if not defined, plan is null)
Detailed Description
Intermediate representation of a horn clause.
A clause can either be:
a fact - a clause with no body (e.g., X(a,b))
a rule - a clause with a head and a body (e.g., Y(a,b) -: X(a,b))
Definition at line 45 of file Clause.h.
Constructor & Destructor Documentation
Clause()
souffle::ast::Clause::Clause (Own< Atom > head = {}, VecOwn< Literal > bodyLiterals = {}, Own< ExecutionPlan > plan = {}, SrcLocation loc = {}) inline
Definition at line 47 of file Clause.h.
References bodyLiterals, head, souffle::ast::Node::Node(), and plan.
Referenced by clone().
                             {}, VecOwn<Literal> bodyLiterals = {}, Own<ExecutionPlan> plan = {},
             SrcLocation loc = {})
             : Node(std::move(loc)), head(std::move(head)), bodyLiterals(std::move(bodyLiterals)),
               plan(std::move(plan)) {}
Member Function Documentation
addToBody()
void souffle::ast::Clause::addToBody (Own< Literal > literal) inline
Add a literal to the body of the clause.
Definition at line 53 of file Clause.h.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::transform::getInlinedClause(), souffle::ast::reorderAtoms(), souffle::RuleBody::toClauseBodies(), and souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform().
{
         bodyLiterals.push_back(std::move(literal));
     }
apply()
void souffle::ast::Clause::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 97 of file Clause.h.
References head, and souffle::map().
Referenced by souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::replaceNamedVariables(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::replaceUnnamedVariable(), and souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform().
{
         head = map(std::move(head));
         for (auto& lit : bodyLiterals) {
             lit = map(std::move(lit));
         }
     }
clearExecutionPlan()
void souffle::ast::Clause::clearExecutionPlan () inline
Resets the execution plan.
Definition at line 88 of file Clause.h.
{
         plan = nullptr;
     }
clone()
Clause* souffle::ast::Clause::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 92 of file Clause.h.
References Clause(), souffle::clone(), souffle::ast::Node::getSrcLoc(), and head.
Referenced by souffle::ast::transform::getInlinedClause(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), and souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms().
{
         return new Clause(
                 souffle::clone(head), souffle::clone(bodyLiterals), souffle::clone(plan), getSrcLoc());
     }
equal()
bool souffle::ast::Clause::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 126 of file Clause.h.
References souffle::equal_ptr(), souffle::equal_targets(), and head.
{
         const auto& other = static_cast<const Clause&>(node);
         return equal_ptr(head, other.head) && equal_targets(bodyLiterals, other.bodyLiterals) &&
                equal_ptr(plan, other.plan);
     }
getBodyLiterals()
std::vector<Literal*> souffle::ast::Clause::getBodyLiterals () const inline
Obtains a copy of the internally maintained body literals.
Definition at line 73 of file Clause.h.
References souffle::toPtrVector().
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem(), souffle::AstToRamTranslator::ProvenanceClauseTranslator::createOperation(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::findVariablesRecordMapping(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::getBindingEqualityConstraints(), souffle::ast::getBodyRelations(), souffle::ast::transform::getInlinedClause(), souffle::ast::isFact(), souffle::ast::isRecursiveClause(), souffle::ast::transform::makeInfoRelation(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::makeSubproofSubroutine(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::analysis::NormalisedClause::NormalisedClause(), souffle::ast::transform::ResolveAliasesTransformer::removeTrivialEquality(), souffle::ast::reorderAtoms(), souffle::ast::test::TEST(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::FoldAnonymousRecords::transformClause(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and souffle::AstToRamTranslator::translateProgram().
{
         return toPtrVector(bodyLiterals);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Clause::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 104 of file Clause.h.
References head.
{
         std::vector<const Node*> res = {head.get()};
         for (auto& cur : bodyLiterals) {
             res.push_back(cur.get());
         }
         return res;
     }
getExecutionPlan()
const ExecutionPlan* souffle::ast::Clause::getExecutionPlan () const inline
Obtains the execution plan associated to this clause or null if there is none.
Definition at line 78 of file Clause.h.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::cloneHead(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), and souffle::ast::transform::ReorderLiteralsTransformer::reorderClauseWithSips().
{
         return plan.get();
     }
getHead()
Atom* souffle::ast::Clause::getHead () const inline
Return the atom that represents the head of the clause.
Definition at line 68 of file Clause.h.
References head.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::transform::SemanticCheckerImpl::checkFact(), souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem(), souffle::ast::cloneHead(), souffle::ast::analysis::TypeConstraintsAnalysis::collectConstraints(), souffle::AstToRamTranslator::ClauseTranslator::createCondition(), souffle::AstToRamTranslator::ClauseTranslator::createOperation(), souffle::ast::getBodyRelations(), souffle::ast::getClauseNum(), souffle::ast::getHeadRelation(), souffle::ast::transform::getInlinedClause(), souffle::ast::isFact(), souffle::ast::isRecursiveClause(), souffle::ast::isRule(), souffle::ast::transform::makeInfoRelation(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::makeSubproofSubroutine(), souffle::ast::analysis::NormalisedClause::NormalisedClause(), souffle::ast::test::TEST(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and souffle::AstToRamTranslator::translateProgram().
{
         return head.get();
     }
print()
void souffle::ast::Clause::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 113 of file Clause.h.
References head, souffle::join(), and plan.
{
         if (head != nullptr) {
             os << *head;
         }
         if (!bodyLiterals.empty()) {
             os << " :- \n   " << join(bodyLiterals, ",\n   ");
         }
         os << ".";
         if (plan != nullptr) {
             os << *plan;
         }
     }
setBodyLiterals()
void souffle::ast::Clause::setBodyLiterals (VecOwn< Literal > body) inline
Set the bodyLiterals of clause to body.
Definition at line 63 of file Clause.h.
{
         bodyLiterals = std::move(body);
     }
setExecutionPlan()
void souffle::ast::Clause::setExecutionPlan (Own< ExecutionPlan > plan) inline
Updates the execution plan associated to this clause.
Definition at line 83 of file Clause.h.
{
         this->plan = std::move(plan);
     }
setHead()
void souffle::ast::Clause::setHead (Own< Atom > h) inline
Set the head of clause to h.
Definition at line 58 of file Clause.h.
References head.
{
         head = std::move(h);
     }
Field Documentation
bodyLiterals
VecOwn<Literal> souffle::ast::Clause::bodyLiterals protected
Body literals of clause.
Definition at line 136 of file Clause.h.
Referenced by Clause().
head
Own<Atom> souffle::ast::Clause::head protected
Head of the clause.
Definition at line 133 of file Clause.h.
Referenced by apply(), Clause(), clone(), equal(), getChildNodes(), getHead(), print(), and setHead().
plan
Own<ExecutionPlan> souffle::ast::Clause::plan protected
User defined execution plan (if not defined, plan is null)
Definition at line 139 of file Clause.h.
Referenced by Clause(), and print().
The documentation for this class was generated from the following file:
ast/Clause.h