souffle: souffle::ast::transform::RemoveRedundantSumsTransformer Class Reference
souffle::ast::transform::RemoveRedundantSumsTransformer Class Reference
Transformation pass to remove expressions of the form sum k : { ...
#include <RemoveRedundantSums.h>
Public Member Functions
RemoveRedundantSumsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove expressions of the form sum k : { ...
} and replace them with k * count : { ... } where k is a constant.
Definition at line 29 of file RemoveRedundantSums.h.
Member Function Documentation
clone()
RemoveRedundantSumsTransformer* souffle::ast::transform::RemoveRedundantSumsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 35 of file RemoveRedundantSums.h.
References transform().
{
         return new RemoveRedundantSumsTransformer();
     }
getName()
std::string souffle::ast::transform::RemoveRedundantSumsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 31 of file RemoveRedundantSums.h.
{
         return "RemoveRedundantSumsTransformer";
     }
transform()
bool souffle::ast::transform::RemoveRedundantSumsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 34 of file RemoveRedundantSums.cpp.
References souffle::ast::Program::apply(), souffle::clone(), souffle::test::count(), souffle::COUNT, souffle::ast::TranslationUnit::getProgram(), and souffle::SUM.
Referenced by clone().
{
     struct ReplaceSumWithCount : public NodeMapper {
         ReplaceSumWithCount() = default;
         Own<Node> operator()(Own<Node> node) const override {
             // Apply to all aggregates of the form
             // sum k : { .. } where k is a constant
             if (auto* agg = dynamic_cast<Aggregator*>(node.get())) {
                 if (agg->getOperator() == AggregateOp::SUM) {
                     if (const auto* constant =
                                     dynamic_cast<const NumericConstant*>(agg->getTargetExpression())) {
                         changed = true;
                         // Then construct the new thing to replace it with
                         auto count = mk<Aggregator>(AggregateOp::COUNT);
                         // Duplicate the body of the aggregate
                         VecOwn<Literal> newBody;
                         for (const auto& lit : agg->getBodyLiterals()) {
                             newBody.push_back(souffle::clone(lit));
                         }
                         count->setBody(std::move(newBody));
                         auto number = souffle::clone(constant);
                         // Now it's constant * count : { ... }
                         auto result = mk<IntrinsicFunctor>("*", std::move(number), std::move(count));
                         return result;
                     }
                 }
             }
             node->apply(*this);
             return node;
         }
         // variables
         mutable bool changed = false;
     };
     ReplaceSumWithCount update;
     Program& program = translationUnit.getProgram();
     program.apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveRedundantSums.h
ast/transform/RemoveRedundantSums.cpp