souffle: souffle::ram::Query Class Reference
souffle::ram::Query Class Reference
A relational algebra query.
#include <Query.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Query * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Operation & getOperation () const
Get RAM operation.
Query (Own< Operation > o)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Operation > operation
RAM operation.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
A relational algebra query.
Corresponds to the core machinery of semi-naive evaluation
For example:
QUERY
  FOR t0 in A
    FOR t1 in B
      ...
Definition at line 46 of file Query.h.
Constructor & Destructor Documentation
Query()
souffle::ram::Query::Query (Own< Operation > o) inline
Definition at line 48 of file Query.h.
References operation.
Referenced by clone().
                             : operation(std::move(o)) {
         assert(operation && "operation is a nullptr");
     }
Member Function Documentation
apply()
void souffle::ram::Query::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 65 of file Query.h.
References souffle::map(), and operation.
Referenced by souffle::ram::transform::HoistConditionsTransformer::hoistConditions().
{
         operation = map(std::move(operation));
     }
clone()
Query* souffle::ram::Query::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 61 of file Query.h.
References souffle::clone(), operation, and Query().
Referenced by souffle::ram::test::TEST().
{
         return new Query(souffle::clone(operation));
     }
equal()
bool souffle::ram::Query::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 75 of file Query.h.
References souffle::equal_ptr(), and operation.
{
         const auto& other = static_cast<const Query&>(node);
         return equal_ptr(operation, other.operation);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Query::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 57 of file Query.h.
References operation.
{
         return {operation.get()};
     }
getOperation()
const Operation& souffle::ram::Query::getOperation () const inline
Get RAM operation.
Definition at line 53 of file Query.h.
References operation.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::HoistAggregateTransformer::hoistAggregate(), and souffle::NodeGenerator::visitQuery().
{
         return *operation;
     }
print()
void souffle::ram::Query::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 70 of file Query.h.
References operation, and souffle::times().
{
         os << times(" ", tabpos) << "QUERY" << std::endl;
         operation->print(os, tabpos + 1);
     }
Field Documentation
operation
Own<Operation> souffle::ram::Query::operation protected
RAM operation.
Definition at line 81 of file Query.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getOperation(), print(), and Query().
The documentation for this class was generated from the following file:
ram/Query.h