souffle: souffle::ast::Node Class Reference
souffle::ast::Node Class Reference abstract
Abstract class for syntactic elements in an input program.
#include <Node.h>
Public Member Functions
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual Node * clone () const =0
Create a clone (i.e.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
virtual bool equal (const Node &) const
Abstract equality check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
Private Attributes
SrcLocation location
Source location of a syntactic element.
Friends
std::ostream & operator<< (std::ostream &out, const Node &node)
Print node onto an output stream.
Detailed Description
Abstract class for syntactic elements in an input program.
Definition at line 34 of file Node.h.
Constructor & Destructor Documentation
Node()
souffle::ast::Node::Node (SrcLocation loc = {}) inline
Definition at line 36 of file Node.h.
References location, and ~Node().
Referenced by souffle::ast::Attribute::Attribute(), souffle::ast::BranchDeclaration::BranchDeclaration(), souffle::ast::Clause::Clause(), souffle::ast::ComponentInit::ComponentInit(), souffle::ast::ComponentType::ComponentType(), souffle::ast::FunctorDeclaration::FunctorDeclaration(), and souffle::ast::Pragma::Pragma().
 {}) : location(std::move(loc)){};
~Node()
virtual souffle::ast::Node::~Node () virtual default
Referenced by Node().
Member Function Documentation
apply()
virtual void souffle::ast::Node::apply (const NodeMapper &) inline virtual
Apply the mapper to all child nodes.
Reimplemented in souffle::ast::Component, souffle::ast::Program, souffle::ast::Relation, souffle::ast::Clause, souffle::ast::Aggregator, souffle::ast::Atom, souffle::ast::ComponentInit, souffle::ast::ExecutionPlan, souffle::ast::TypeCast, souffle::ast::Term, and souffle::ast::Negation.
Definition at line 73 of file Node.h.
Referenced by souffle::ast::renameAtoms(), and souffle::ast::transform::renameVariables().
 {}
clone()
virtual Node* souffle::ast::Node::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::ast::Component, souffle::ast::Program, souffle::ast::Relation, souffle::ast::Directive, souffle::ast::Clause, souffle::ast::Aggregator, souffle::ast::IntrinsicFunctor, souffle::ast::UserDefinedFunctor, souffle::ast::FunctorDeclaration, souffle::ast::Atom, souffle::ast::ComponentInit, souffle::ast::TypeCast, souffle::ast::ComponentType, souffle::ast::ExecutionPlan, souffle::ast::Attribute, souffle::ast::BranchDeclaration, souffle::ast::Negation, souffle::ast::BranchInit, souffle::ast::NumericConstant, souffle::ast::ExecutionOrder, souffle::ast::Variable, souffle::ast::Type, souffle::ast::SubroutineArgument, souffle::ast::RecordInit, souffle::ast::Functor, souffle::ast::ProvenanceNegation, souffle::ast::StringConstant, souffle::ast::Pragma, souffle::ast::Constant, souffle::ast::Literal, souffle::ast::NilConstant, souffle::ast::Argument, souffle::ast::Counter, souffle::ast::UnnamedVariable, and souffle::ast::Constraint.
Referenced by operator!=().
equal()
virtual bool souffle::ast::Node::equal (const Node &) const inline protected virtual
Abstract equality check for two AST nodes.
Reimplemented in souffle::ast::Component, souffle::ast::Program, souffle::ast::Relation, souffle::ast::Clause, souffle::ast::Directive, souffle::ast::Aggregator, souffle::ast::IntrinsicFunctor, souffle::ast::FunctorDeclaration, souffle::ast::Atom, souffle::ast::UserDefinedFunctor, souffle::ast::ExecutionPlan, souffle::ast::ComponentInit, souffle::ast::TypeCast, souffle::ast::ComponentType, souffle::ast::Term, souffle::ast::Negation, souffle::ast::NumericConstant, souffle::ast::Attribute, souffle::ast::BranchInit, souffle::ast::ExecutionOrder, souffle::ast::Variable, souffle::ast::SubroutineArgument, souffle::ast::Pragma, and souffle::ast::Constant.
Definition at line 91 of file Node.h.
Referenced by operator==().
{
         return true;
     }
extloc()
std::string souffle::ast::Node::extloc () const inline
Return source location of the syntactic element.
Definition at line 50 of file Node.h.
References souffle::SrcLocation::extloc(), and location.
{
         return location.extloc();
     }
getChildNodes()
virtual std::vector<const Node*> souffle::ast::Node::getChildNodes () const inline virtual
Obtain a list of all embedded AST child nodes.
Reimplemented in souffle::ast::Component, souffle::ast::Program, souffle::ast::Relation, souffle::ast::Clause, souffle::ast::Atom, souffle::ast::Aggregator, souffle::ast::ExecutionPlan, souffle::ast::ComponentInit, souffle::ast::Negation, souffle::ast::TypeCast, and souffle::ast::Term.
Definition at line 76 of file Node.h.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::Term::getChildNodes(), souffle::ast::TypeCast::getChildNodes(), souffle::ast::Aggregator::getChildNodes(), souffle::ast::visitDepthFirstPostOrder(), and souffle::ast::visitDepthFirstPreOrder().
{
         return {};
     }
getSrcLoc()
const SrcLocation& souffle::ast::Node::getSrcLoc () const inline
Return source location of the Node.
Definition at line 40 of file Node.h.
References location.
Referenced by souffle::ParserDriver::addFunctorDeclaration(), souffle::ParserDriver::addIoFromDeprecatedTag(), souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::transform::SemanticCheckerImpl::checkAtom(), souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::transform::ComponentChecker::checkComponent(), souffle::ast::transform::ComponentChecker::checkComponentInit(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration(), souffle::ast::Counter::clone(), souffle::ast::UnnamedVariable::clone(), souffle::ast::NilConstant::clone(), souffle::ast::Pragma::clone(), souffle::ast::StringConstant::clone(), souffle::ast::ProvenanceNegation::clone(), souffle::ast::RecordInit::clone(), souffle::ast::SubroutineArgument::clone(), souffle::ast::Variable::clone(), souffle::ast::ExecutionOrder::clone(), souffle::ast::NumericConstant::clone(), souffle::ast::BranchInit::clone(), souffle::ast::Negation::clone(), souffle::ast::BranchDeclaration::clone(), souffle::ast::Attribute::clone(), souffle::ast::ExecutionPlan::clone(), souffle::ast::ComponentType::clone(), souffle::ast::TypeCast::clone(), souffle::ast::ComponentInit::clone(), souffle::ast::Atom::clone(), souffle::ast::FunctorDeclaration::clone(), souffle::ast::UserDefinedFunctor::clone(), souffle::ast::IntrinsicFunctor::clone(), souffle::ast::Aggregator::clone(), souffle::ast::Clause::clone(), souffle::ast::Relation::clone(), souffle::ast::cloneHead(), souffle::ast::transform::getInlinedAtom(), souffle::ast::transform::getInlinedClause(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), souffle::ast::transform::TypeChecker::visitAggregator(), souffle::ast::transform::TypeChecker::visitBranchInit(), souffle::ast::transform::TypeChecker::visitIntrinsicFunctor(), souffle::ast::transform::TypeChecker::visitNilConstant(), souffle::ast::transform::TypeChecker::visitNumericConstant(), souffle::ast::transform::TypeChecker::visitRecordInit(), souffle::ast::transform::TypeChecker::visitStringConstant(), souffle::ast::transform::TypeChecker::visitTypeCast(), and souffle::ast::transform::TypeChecker::visitUserDefinedFunctor().
{
         return location;
     }
operator!=()
bool souffle::ast::Node::operator!= (const Node & other) const inline
Inequality check for two AST nodes.
Definition at line 65 of file Node.h.
References clone().
{
         return !(*this == other);
     }
operator==()
bool souffle::ast::Node::operator== (const Node & other) const inline
Equivalence check for two AST nodes.
Definition at line 55 of file Node.h.
References equal().
{
         if (this == &other) {
             return true;
         } else if (typeid(*this) == typeid(*&other)) {
             return equal(other);
         }
         return false;
     }
print()
virtual void souffle::ast::Node::print (std::ostream & os) const protected pure virtual
Output to a given output stream.
Implemented in souffle::ast::Component, souffle::ast::Program, souffle::ast::Relation, souffle::ast::Clause, souffle::ast::Directive, souffle::ast::Aggregator, souffle::ast::IntrinsicFunctor, souffle::ast::Atom, souffle::ast::UserDefinedFunctor, souffle::ast::ExecutionPlan, souffle::ast::FunctorDeclaration, souffle::ast::ComponentInit, souffle::ast::TypeCast, souffle::ast::ComponentType, souffle::ast::Negation, souffle::ast::Attribute, souffle::ast::BranchDeclaration, souffle::ast::BranchInit, souffle::ast::ExecutionOrder, souffle::ast::Variable, souffle::ast::SubroutineArgument, souffle::ast::Pragma, souffle::ast::RecordInit, souffle::ast::StringConstant, souffle::ast::ProvenanceNegation, souffle::ast::Constant, souffle::ast::Counter, and souffle::ast::UnnamedVariable.
setSrcLoc()
void souffle::ast::Node::setSrcLoc (SrcLocation l) inline
Set source location for the Node.
Definition at line 45 of file Node.h.
References location.
Referenced by souffle::ast::ExecutionOrder::ExecutionOrder(), souffle::ast::transform::getInlinedArgument(), souffle::ast::NumericConstant::NumericConstant(), souffle::ast::Relation::Relation(), and souffle::ast::StringConstant::StringConstant().
{
         location = std::move(l);
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Node & node) friend
Print node onto an output stream.
Definition at line 81 of file Node.h.
{
         node.print(out);
         return out;
     }
Field Documentation
location
SrcLocation souffle::ast::Node::location private
Source location of a syntactic element.
Definition at line 97 of file Node.h.
Referenced by extloc(), getSrcLoc(), Node(), and setSrcLoc().
The documentation for this class was generated from the following file:
ast/Node.h