souffle: souffle::ram::UnpackRecord Class Reference
souffle::ram::UnpackRecord Class Reference
Record lookup.
#include <UnpackRecord.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
UnpackRecord * clone () const override
Create a clone (i.e.
std::size_t getArity () const
Get arity of record.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Expression & getExpression () const
Get record expression.
UnpackRecord (Own< Operation > nested, int ident, Own< Expression > expr, size_t arity)
Public Member Functions inherited from souffle::ram::TupleOperation
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const size_t arity
Arity of the unpacked tuple.
Own< Expression > expression
Expression for record reference.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Record lookup.
Looks up a record with respect to an expression
For example:
UNPACK t0.0 INTO t1
Definition at line 47 of file UnpackRecord.h.
Constructor & Destructor Documentation
UnpackRecord()
souffle::ram::UnpackRecord::UnpackRecord (Own< Operation > nested, int ident, Own< Expression > expr, size_t arity) inline
Definition at line 49 of file UnpackRecord.h.
References expression.
Referenced by clone().
             : TupleOperation(ident, std::move(nested)), expression(std::move(expr)), arity(arity) {
         assert(expression != nullptr && "Expression is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::UnpackRecord::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::NestedOperation.
Definition at line 76 of file UnpackRecord.h.
References souffle::ram::NestedOperation::apply(), expression, and souffle::map().
{
         TupleOperation::apply(map);
         expression = map(std::move(expression));
     }
clone()
UnpackRecord* souffle::ram::UnpackRecord::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::TupleOperation.
Definition at line 71 of file UnpackRecord.h.
References arity, souffle::clone(), getExpression(), souffle::ram::NestedOperation::getOperation(), souffle::ram::TupleOperation::getTupleId(), and UnpackRecord().
Referenced by souffle::ram::test::TEST().
{
         return new UnpackRecord(
                 souffle::clone(&getOperation()), getTupleId(), souffle::clone(&getExpression()), arity);
     }
equal()
bool souffle::ram::UnpackRecord::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::TupleOperation.
Definition at line 88 of file UnpackRecord.h.
References arity, souffle::ram::TupleOperation::equal(), souffle::equal_ptr(), and expression.
{
         const auto& other = static_cast<const UnpackRecord&>(node);
         return TupleOperation::equal(other) && equal_ptr(expression, other.expression) &&
                arity == other.arity;
     }
getArity()
std::size_t souffle::ram::UnpackRecord::getArity () const inline
Get arity of record.
Definition at line 61 of file UnpackRecord.h.
References arity.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return arity;
     }
getChildNodes()
std::vector<const Node*> souffle::ram::UnpackRecord::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::TupleOperation.
Definition at line 65 of file UnpackRecord.h.
References expression, and souffle::ram::TupleOperation::getChildNodes().
{
         auto res = TupleOperation::getChildNodes();
         res.push_back(expression.get());
         return res;
     }
getExpression()
const Expression& souffle::ram::UnpackRecord::getExpression () const inline
Get record expression.
Definition at line 55 of file UnpackRecord.h.
References expression.
Referenced by clone(), souffle::synthesiser::Synthesiser::emitCode(), and souffle::ram::analysis::LevelAnalysis::getLevel().
{
         assert(expression != nullptr && "Expression of unpack-record is a null-pointer");
         return *expression;
     }
print()
void souffle::ram::UnpackRecord::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::ram::NestedOperation.
Definition at line 82 of file UnpackRecord.h.
References expression, souffle::ram::TupleOperation::getTupleId(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "UNPACK t" << getTupleId() << " FROM " << *expression << "\n";
         NestedOperation::print(os, tabpos + 1);
     }
Field Documentation
arity
const size_t souffle::ram::UnpackRecord::arity protected
Arity of the unpacked tuple.
Definition at line 98 of file UnpackRecord.h.
Referenced by clone(), equal(), and getArity().
expression
Own<Expression> souffle::ram::UnpackRecord::expression protected
Expression for record reference.
Definition at line 95 of file UnpackRecord.h.
Referenced by apply(), equal(), getChildNodes(), getExpression(), print(), and UnpackRecord().
The documentation for this class was generated from the following file:
ram/UnpackRecord.h