souffle: souffle::ast::analysis::AuxiliaryArityAnalysis Class Reference
souffle::ast::analysis::AuxiliaryArityAnalysis Class Reference
Determine the auxiliary arity for relations.
#include <AuxArity.h>
Public Member Functions
AuxiliaryArityAnalysis ()
size_t getArity (const Atom *atom) const
Returns the number of auxiliary parameters of an atom's relation.
size_t getArity (const Relation *relation) const
Returns the number of auxiliary parameters of a relation.
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "auxiliary-arity"
Private Member Functions
size_t computeArity (const Relation *relation) const
Returns the number of auxiliary parameters of a relation.
Private Attributes
const Program * program = nullptr
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Determine the auxiliary arity for relations.
Definition at line 32 of file AuxArity.h.
Constructor & Destructor Documentation
AuxiliaryArityAnalysis()
souffle::ast::analysis::AuxiliaryArityAnalysis::AuxiliaryArityAnalysis () inline
Definition at line 36 of file AuxArity.h.
 : Analysis(name) {}
Member Function Documentation
computeArity()
size_t souffle::ast::analysis::AuxiliaryArityAnalysis::computeArity (const Relation * relation) const private
Returns the number of auxiliary parameters of a relation.
Parameters
relation the relation to report on
Returns
number of auxiliary attributes
Definition at line 22 of file AuxArity.cpp.
References souffle::Global::config().
Referenced by getArity().
{
     if (Global::config().has("provenance")) {
         return 2;
     } else {
         return 0;
     }
 }
getArity() [1/2]
size_t souffle::ast::analysis::AuxiliaryArityAnalysis::getArity (const Atom * atom) const inline
Returns the number of auxiliary parameters of an atom's relation.
Parameters
atom the atom to report on
Returns
number of auxiliary attributes
Definition at line 47 of file AuxArity.h.
References computeArity(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), and program.
Referenced by souffle::AstToRamTranslator::getEvaluationArity(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::makeSubproofSubroutine(), and souffle::AstToRamTranslator::translateProgram().
{
         return computeArity(getRelation(*program, atom->getQualifiedName()));
     }
getArity() [2/2]
size_t souffle::ast::analysis::AuxiliaryArityAnalysis::getArity (const Relation * relation) const inline
Returns the number of auxiliary parameters of a relation.
Parameters
relation the relation to report on
Returns
number of auxiliary attributes
Definition at line 56 of file AuxArity.h.
References computeArity(), and relation.
{
         return computeArity(relation);
     }
run()
void souffle::ast::analysis::AuxiliaryArityAnalysis::run (const TranslationUnit &) inline override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 38 of file AuxArity.h.
References souffle::ast::TranslationUnit::getProgram(), and program.
{
         program = &translationUnit.getProgram();
     }
Field Documentation
name
constexpr const char* souffle::ast::analysis::AuxiliaryArityAnalysis::name = "auxiliary-arity" static
Definition at line 34 of file AuxArity.h.
program
const Program* souffle::ast::analysis::AuxiliaryArityAnalysis::program = nullptr private
Definition at line 68 of file AuxArity.h.
Referenced by getArity(), and run().
The documentation for this class was generated from the following files:
ast/analysis/AuxArity.h
ast/analysis/AuxArity.cpp