souffle: souffle::ram::Break Class Reference
souffle::ram::Break Class Reference
Breaks out of the loop if a condition holds.
#include <Break.h>
Public Member Functions
Break (Own< Condition > cond, Own< Operation > nested, std::string profileText="")
Break * clone () const override
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::AbstractConditional
AbstractConditional (Own< Condition > cond, Own< Operation > nested, std::string profileText="")
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Condition & getCondition () const
Get condition that must be satisfied.
Public Member Functions inherited from souffle::ram::NestedOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::AbstractConditional
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::AbstractConditional
Own< Condition > condition
Condition.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Breaks out of the loop if a condition holds.
The following example will break out of the inner-most loop if the condition (t1.1 = 4) holds:
FOR t0 in A
  FOR t1 in B
    IF t0.1 = 4 BREAK
    ...
Definition at line 45 of file Break.h.
Constructor & Destructor Documentation
Break()
souffle::ram::Break::Break (Own< Condition > cond, Own< Operation > nested, std::string profileText = "") inline
Definition at line 47 of file Break.h.
Referenced by clone().
             : AbstractConditional(std::move(cond), std::move(nested), std::move(profileText)) {}
Member Function Documentation
clone()
Break* souffle::ram::Break::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::AbstractConditional.
Definition at line 50 of file Break.h.
References Break(), souffle::clone(), souffle::ram::AbstractConditional::condition, souffle::ram::NestedOperation::getOperation(), and souffle::ram::NestedOperation::getProfileText().
Referenced by souffle::ram::test::TEST().
{
         return new Break(souffle::clone(condition), souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::ram::Break::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Definition at line 55 of file Break.h.
References souffle::ram::AbstractConditional::getCondition(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "IF " << getCondition() << " BREAK" << std::endl;
         NestedOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Break.h