souffle: souffle::AstToRamTranslator Class Reference
souffle::AstToRamTranslator Class Reference
Main class for AST Translator.
#include <AstToRamTranslator.h>
Data Structures
class ClauseTranslator
translate AST clause to RAM code
struct Location
Concrete attribute.
class ProvenanceClauseTranslator
class ValueIndex
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Public Member Functions
AstToRamTranslator ()=default
Own< ram::TranslationUnit > translateUnit (ast::TranslationUnit &tu)
translates AST to translation unit
Private Member Functions
Own< ram::RelationReference > createRelationReference (const std::string name)
create a reference to a RAM relation
RamDomain getConstantRamRepresentation (const ast::Constant &constant)
Get ram representation of constant.
size_t getEvaluationArity (const ast::Atom *atom) const
determine the auxiliary for relations
std::vector< std::map< std::string, std::string > > getInputDirectives (const ast::Relation *rel)
std::vector< std::map< std::string, std::string > > getOutputDirectives (const ast::Relation *rel)
std::string getRelationName (const ast::QualifiedName &id)
converts the given relation identifier into a relation name
SymbolTable & getSymbolTable ()
Return a symbol table.
Own< ram::Statement > makeNegationSubproofSubroutine (const ast::Clause &clause)
translate RAM code for subroutine to get subproofs for non-existence of a tuple
Own< ram::Statement > makeSubproofSubroutine (const ast::Clause &clause)
translate RAM code for subroutine to get subproofs
Own< ram::Statement > makeSubproofSubroutineOpt (const ast::Clause &clause)
translate RAM code for subroutine to get subproofs
void nameUnnamedVariables (ast::Clause *clause)
assigns names to unnamed variables such that enclosing constructs may be cloned without losing the variable-identity
Own< ram::Expression > translateConstant (ast::Constant const &c)
translate RAM code for a constant value
Own< ram::Condition > translateConstraint (const ast::Literal *arg, const ValueIndex &index)
translate an AST constraint to a RAM condition
Own< ram::RelationReference > translateDeltaRelation (const ast::Relation *rel)
translate a temporary delta relation to a RAM relation for semi-naive evaluation
void translateDirectives (std::map< std::string, std::string > &directives, const ast::Relation *rel)
translate AST directives to RAM directives
Own< ram::RelationReference > translateNewRelation (const ast::Relation *rel)
translate a temporary new relation to a RAM relation for semi-naive evaluation
Own< ram::Statement > translateNonRecursiveRelation (const ast::Relation &rel, const ast::analysis::RecursiveClausesAnalysis *recursiveClauses)
translate RAM code for the non-recursive clauses of the given relation.
void translateProgram (const ast::TranslationUnit &translationUnit)
translate AST to RAM Program
Own< ram::Statement > translateRecursiveRelation (const std::set< const ast::Relation *> &scc, const ast::analysis::RecursiveClausesAnalysis *recursiveClauses)
translate RAM code for recursive relations in a strongly-connected component
Own< ram::RelationReference > translateRelation (const ast::Atom *atom)
a utility to translate atoms to relations
Own< ram::RelationReference > translateRelation (const ast::Relation *rel, const std::string relationNamePrefix="")
translate an AST relation to a RAM relation
Own< ram::Expression > translateValue (const ast::Argument *arg, const ValueIndex &index)
translate an AST argument to a RAM value
Static Private Member Functions
static Own< ram::TupleElement > makeRamTupleElement (const Location &loc)
create a RAM element access node
Private Attributes
const ast::analysis::AuxiliaryArityAnalysis * auxArityAnalysis = nullptr
Auxiliary Arity Analysis.
const ast::analysis::IOTypeAnalysis * ioType = nullptr
IO Type.
const ast::Program * program = nullptr
AST program.
Own< ram::Statement > ramMain
RAM program.
std::map< std::string, Own< ram::Relation > > ramRels
RAM relations.
std::map< std::string, Own< ram::Statement > > ramSubs
Subroutines.
SymbolTable symbolTable
Symbol Table.
const ast::analysis::TypeEnvironment * typeEnv = nullptr
Type environment.
Detailed Description
Main class for AST Translator.
Definition at line 67 of file AstToRamTranslator.h.
Constructor & Destructor Documentation
AstToRamTranslator()
souffle::AstToRamTranslator::AstToRamTranslator () default
Member Function Documentation
createRelationReference()
Own< ram::RelationReference > souffle::AstToRamTranslator::createRelationReference (const std::string name) private
create a reference to a RAM relation
Definition at line 209 of file AstToRamTranslator.cpp.
References ramRels, and relation.
Referenced by getRelationName(), and translateRelation().
{
     auto it = ramRels.find(name);
     assert(it != ramRels.end() && "relation name not found");
     const ram::Relation* relation = it->second.get();
     return mk<ram::RelationReference>(relation);
 }
getConstantRamRepresentation()
RamDomain souffle::AstToRamTranslator::getConstantRamRepresentation (const ast::Constant & constant) inline private
Get ram representation of constant.
Definition at line 396 of file AstToRamTranslator.h.
References souffle::fatal(), souffle::ast::NumericConstant::Float, getSymbolTable(), souffle::ast::NumericConstant::Int, souffle::SymbolTable::lookup(), makeNegationSubproofSubroutine(), makeSubproofSubroutine(), makeSubproofSubroutineOpt(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), souffle::RamUnsignedFromString(), translateConstant(), translateNonRecursiveRelation(), translateProgram(), translateRecursiveRelation(), and souffle::ast::NumericConstant::Uint.
Referenced by translateConstant().
{
         if (auto strConstant = dynamic_cast<const ast::StringConstant*>(&constant)) {
             return getSymbolTable().lookup(strConstant->getConstant());
         } else if (isA<ast::NilConstant>(&constant)) {
             return 0;
         } else if (auto* numConstant = dynamic_cast<const ast::NumericConstant*>(&constant)) {
             assert(numConstant->getType().has_value());
             switch (*numConstant->getType()) {
                 case ast::NumericConstant::Type::Int:
                     return RamSignedFromString(numConstant->getConstant(), nullptr, 0);
                 case ast::NumericConstant::Type::Uint:
                     return RamUnsignedFromString(numConstant->getConstant(), nullptr, 0);
                 case ast::NumericConstant::Type::Float: return RamFloatFromString(numConstant->getConstant());
             }
         }
         fatal("unaccounted-for constant");
     }
getEvaluationArity()
size_t souffle::AstToRamTranslator::getEvaluationArity (const ast::Atom * atom) const private
determine the auxiliary for relations
Definition at line 144 of file AstToRamTranslator.cpp.
References auxArityAnalysis, souffle::ast::analysis::AuxiliaryArityAnalysis::getArity(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), program, and souffle::ast::QualifiedName::toString().
Referenced by translateConstraint().
{
     if (atom->getQualifiedName().toString().find("@delta_") == 0) {
         const ast::QualifiedName& originalRel =
                 ast::QualifiedName(atom->getQualifiedName().toString().substr(7));
         return auxArityAnalysis->getArity(getRelation(*program, originalRel));
     } else if (atom->getQualifiedName().toString().find("@new_") == 0) {
         const ast::QualifiedName& originalRel =
                 ast::QualifiedName(atom->getQualifiedName().toString().substr(5));
         return auxArityAnalysis->getArity(getRelation(*program, originalRel));
     } else if (atom->getQualifiedName().toString().find("@info_") == 0) {
         return 0;
     } else {
         return auxArityAnalysis->getArity(atom);
     }
 }
getInputDirectives()
std::vector< std::map< std::string, std::string > > souffle::AstToRamTranslator::getInputDirectives (const ast::Relation * rel) private
Definition at line 160 of file AstToRamTranslator.cpp.
References directives, souffle::ast::Program::getDirectives(), souffle::ast::Relation::getQualifiedName(), souffle::ast::input, program, and souffle::unescape().
Referenced by getRelationName(), and translateProgram().
{
     std::vector<std::map<std::string, std::string>> inputDirectives;
     for (const auto* load : program->getDirectives()) {
         if (load->getQualifiedName() != rel->getQualifiedName() ||
                 load->getType() != ast::DirectiveType::input) {
             continue;
         }
         std::map<std::string, std::string> directives;
         for (const auto& currentPair : load->getParameters()) {
             directives.insert(std::make_pair(currentPair.first, unescape(currentPair.second)));
         }
         inputDirectives.push_back(directives);
     }
     if (inputDirectives.empty()) {
         inputDirectives.emplace_back();
     }
     return inputDirectives;
 }
getOutputDirectives()
std::vector< std::map< std::string, std::string > > souffle::AstToRamTranslator::getOutputDirectives (const ast::Relation * rel) private
Definition at line 184 of file AstToRamTranslator.cpp.
References directives, souffle::ast::Program::getDirectives(), souffle::ast::Relation::getQualifiedName(), souffle::ast::output, souffle::ast::printsize, program, and souffle::unescape().
Referenced by getRelationName(), and translateProgram().
{
     std::vector<std::map<std::string, std::string>> outputDirectives;
     for (const auto* store : program->getDirectives()) {
         if (store->getQualifiedName() != rel->getQualifiedName() ||
                 (store->getType() != ast::DirectiveType::printsize &&
                         store->getType() != ast::DirectiveType::output)) {
             continue;
         }
         std::map<std::string, std::string> directives;
         for (const auto& currentPair : store->getParameters()) {
             directives.insert(std::make_pair(currentPair.first, unescape(currentPair.second)));
         }
         outputDirectives.push_back(directives);
     }
     if (outputDirectives.empty()) {
         outputDirectives.emplace_back();
     }
     return outputDirectives;
 }
getRelationName()
std::string souffle::AstToRamTranslator::getRelationName (const ast::QualifiedName & id) inline private
converts the given relation identifier into a relation name
Definition at line 297 of file AstToRamTranslator.h.
References createRelationReference(), directives, getInputDirectives(), getOutputDirectives(), souffle::join(), souffle::toString(), translateConstraint(), translateDeltaRelation(), translateDirectives(), translateNewRelation(), translateRelation(), and translateValue().
Referenced by translateRelation().
{
         return toString(join(id.getQualifiers(), "."));
     }
getSymbolTable()
SymbolTable& souffle::AstToRamTranslator::getSymbolTable () inline private
Return a symbol table.
Definition at line 389 of file AstToRamTranslator.h.
References symbolTable.
Referenced by getConstantRamRepresentation(), translateUnit(), and translateValue().
{
         return symbolTable;
     }
makeNegationSubproofSubroutine()
Own< ram::Statement > souffle::AstToRamTranslator::makeNegationSubproofSubroutine (const ast::Clause & clause) private
translate RAM code for subroutine to get subproofs for non-existence of a tuple
make a subroutine to search for subproofs for the non-existence of a tuple
Definition at line 1273 of file AstToRamTranslator.cpp.
References souffle::appendStmt(), auxArityAnalysis, souffle::clone(), souffle::ast::analysis::AuxiliaryArityAnalysis::getArity(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), i, translateConstraint(), translateRelation(), translateValue(), and souffle::ast::visitDepthFirst().
Referenced by getConstantRamRepresentation(), and translateProgram().
{
     // TODO (taipan-snake): Currently we only deal with atoms (no constraints or negations or aggregates
     // or anything else...)
     //
     // The resulting subroutine looks something like this:
     // IF (arg(0), arg(1), _, _) IN rel_1:
     //   return 1
     // IF (arg(0), arg(1), _ ,_) NOT IN rel_1:
     //   return 0
     // ...
     // clone clause for mutation, rearranging constraints to be at the end
     auto clauseReplacedAggregates = mk<ast::Clause>(souffle::clone(clause.getHead()));
     // create a clone where all the constraints are moved to the end
     for (auto bodyLit : clause.getBodyLiterals()) {
         // first add all the things that are not constraints
         if (!isA<ast::Constraint>(bodyLit)) {
             clauseReplacedAggregates->addToBody(souffle::clone(bodyLit));
         }
     }
     // now add all constraints
     for (auto bodyLit : ast::getBodyLiterals<ast::Constraint>(clause)) {
         clauseReplacedAggregates->addToBody(souffle::clone(bodyLit));
     }
     int aggNumber = 0;
     struct AggregatesToVariables : public ast::NodeMapper {
         int& aggNumber;
         AggregatesToVariables(int& aggNumber) : aggNumber(aggNumber) {}
         Own<ast::Node> operator()(Own<ast::Node> node) const override {
             if (dynamic_cast<ast::Aggregator*>(node.get()) != nullptr) {
                 return mk<ast::Variable>("agg_" + std::to_string(aggNumber++));
             }
             node->apply(*this);
             return node;
         }
     };
     AggregatesToVariables aggToVar(aggNumber);
     clauseReplacedAggregates->apply(aggToVar);
     // build a vector of unique variables
     std::vector<const ast::Variable*> uniqueVariables;
     visitDepthFirst(*clauseReplacedAggregates, [&](const ast::Variable& var) {
         if (var.getName().find("@level_num") == std::string::npos) {
             // use find_if since uniqueVariables stores pointers, and we need to dereference the pointer to
             // check equality
             if (std::find_if(uniqueVariables.begin(), uniqueVariables.end(),
                         [&](const ast::Variable* v) { return *v == var; }) == uniqueVariables.end()) {
                 uniqueVariables.push_back(&var);
             }
         }
     });
     // a mapper to replace variables with subroutine arguments
     struct VariablesToArguments : public ast::NodeMapper {
         const std::vector<const ast::Variable*>& uniqueVariables;
         VariablesToArguments(const std::vector<const ast::Variable*>& uniqueVariables)
                 : uniqueVariables(uniqueVariables) {}
         Own<ast::Node> operator()(Own<ast::Node> node) const override {
             // replace unknown variables
             if (auto varPtr = dynamic_cast<const ast::Variable*>(node.get())) {
                 if (varPtr->getName().find("@level_num") == std::string::npos) {
                     size_t argNum = std::find_if(uniqueVariables.begin(), uniqueVariables.end(),
                                             [&](const ast::Variable* v) { return *v == *varPtr; }) -
                                     uniqueVariables.begin();
                     return mk<ast::SubroutineArgument>(argNum);
                 } else {
                     return mk<ast::UnnamedVariable>();
                 }
             }
             // apply recursive
             node->apply(*this);
             // otherwise nothing
             return node;
         }
     };
     // the structure of this subroutine is a sequence where each nested statement is a search in each
     // relation
     VecOwn<ram::Statement> searchSequence;
     // make a copy so that when we mutate clause, pointers to objects in newClause are not affected
     auto newClause = souffle::clone(clauseReplacedAggregates);
     // go through each body atom and create a return
     size_t litNumber = 0;
     for (const auto& lit : newClause->getBodyLiterals()) {
         if (auto atom = dynamic_cast<ast::Atom*>(lit)) {
             size_t auxiliaryArity = auxArityAnalysis->getArity(atom);
             // get a ram::RelationReference
             auto relRef = translateRelation(atom);
             // construct a query
             VecOwn<ram::Expression> query;
             // translate variables to subroutine arguments
             VariablesToArguments varsToArgs(uniqueVariables);
             atom->apply(varsToArgs);
             auto atomArgs = atom->getArguments();
             // add each value (subroutine argument) to the search query
             for (size_t i = 0; i < atom->getArity() - auxiliaryArity; i++) {
                 auto arg = atomArgs[i];
                 query.push_back(translateValue(arg, ValueIndex()));
             }
             // fill up query with nullptrs for the provenance columns
             for (size_t i = 0; i < auxiliaryArity; i++) {
                 query.push_back(mk<ram::UndefValue>());
             }
             // ensure the length of query tuple is correct
             assert(query.size() == atom->getArity() && "wrong query tuple size");
             // create existence checks to check if the tuple exists or not
             auto existenceCheck = mk<ram::ExistenceCheck>(souffle::clone(relRef), std::move(query));
             auto negativeExistenceCheck = mk<ram::Negation>(souffle::clone(existenceCheck));
             // return true if the tuple exists
             VecOwn<ram::Expression> returnTrue;
             returnTrue.push_back(mk<ram::SignedConstant>(1));
             // return false if the tuple exists
             VecOwn<ram::Expression> returnFalse;
             returnFalse.push_back(mk<ram::SignedConstant>(0));
             // create a ram::Query to return true/false
             appendStmt(searchSequence, mk<ram::Query>(mk<ram::Filter>(std::move(existenceCheck),
                                                mk<ram::SubroutineReturn>(std::move(returnTrue)))));
             appendStmt(searchSequence, mk<ram::Query>(mk<ram::Filter>(std::move(negativeExistenceCheck),
                                                mk<ram::SubroutineReturn>(std::move(returnFalse)))));
         } else if (auto neg = dynamic_cast<ast::Negation*>(lit)) {
             auto atom = neg->getAtom();
             size_t auxiliaryArity = auxArityAnalysis->getArity(atom);
             // get a ram::RelationReference
             auto relRef = translateRelation(atom);
             // construct a query
             VecOwn<ram::Expression> query;
             // translate variables to subroutine arguments
             VariablesToArguments varsToArgs(uniqueVariables);
             atom->apply(varsToArgs);
             auto atomArgs = atom->getArguments();
             // add each value (subroutine argument) to the search query
             for (size_t i = 0; i < atom->getArity() - auxiliaryArity; i++) {
                 auto arg = atomArgs[i];
                 query.push_back(translateValue(arg, ValueIndex()));
             }
             // fill up query with nullptrs for the provenance columns
             for (size_t i = 0; i < auxiliaryArity; i++) {
                 query.push_back(mk<ram::UndefValue>());
             }
             // ensure the length of query tuple is correct
             assert(query.size() == atom->getArity() && "wrong query tuple size");
             // create existence checks to check if the tuple exists or not
             auto existenceCheck = mk<ram::ExistenceCheck>(souffle::clone(relRef), std::move(query));
             auto negativeExistenceCheck = mk<ram::Negation>(souffle::clone(existenceCheck));
             // return true if the tuple exists
             VecOwn<ram::Expression> returnTrue;
             returnTrue.push_back(mk<ram::SignedConstant>(1));
             // return false if the tuple exists
             VecOwn<ram::Expression> returnFalse;
             returnFalse.push_back(mk<ram::SignedConstant>(0));
             // create a ram::Query to return true/false
             appendStmt(searchSequence, mk<ram::Query>(mk<ram::Filter>(std::move(existenceCheck),
                                                mk<ram::SubroutineReturn>(std::move(returnFalse)))));
             appendStmt(searchSequence, mk<ram::Query>(mk<ram::Filter>(std::move(negativeExistenceCheck),
                                                mk<ram::SubroutineReturn>(std::move(returnTrue)))));
         } else if (auto con = dynamic_cast<ast::Constraint*>(lit)) {
             VariablesToArguments varsToArgs(uniqueVariables);
             con->apply(varsToArgs);
             // translate to a ram::Condition
             auto condition = translateConstraint(con, ValueIndex());
             auto negativeCondition = mk<ram::Negation>(souffle::clone(condition));
             // create a return true value
             VecOwn<ram::Expression> returnTrue;
             returnTrue.push_back(mk<ram::SignedConstant>(1));
             // create a return false value
             VecOwn<ram::Expression> returnFalse;
             returnFalse.push_back(mk<ram::SignedConstant>(0));
             appendStmt(searchSequence, mk<ram::Query>(mk<ram::Filter>(std::move(condition),
                                                mk<ram::SubroutineReturn>(std::move(returnTrue)))));
             appendStmt(searchSequence, mk<ram::Query>(mk<ram::Filter>(std::move(negativeCondition),
                                                mk<ram::SubroutineReturn>(std::move(returnFalse)))));
         }
         litNumber++;
     }
     return mk<ram::Sequence>(std::move(searchSequence));
 }
makeRamTupleElement()
Own< ram::TupleElement > souffle::AstToRamTranslator::makeRamTupleElement (const Location & loc) static private
create a RAM element access node
Definition at line 140 of file AstToRamTranslator.cpp.
References souffle::AstToRamTranslator::Location::element, and souffle::AstToRamTranslator::Location::identifier.
Referenced by souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and translateValue().
{
     return mk<ram::TupleElement>(loc.identifier, loc.element);
 }
makeSubproofSubroutine()
Own< ram::Statement > souffle::AstToRamTranslator::makeSubproofSubroutine (const ast::Clause & clause) private
translate RAM code for subroutine to get subproofs
make a subroutine to search for subproofs
Definition at line 1214 of file AstToRamTranslator.cpp.
References auxArityAnalysis, souffle::clone(), souffle::EQ, souffle::FEQ, souffle::Float, souffle::ast::analysis::AuxiliaryArityAnalysis::getArity(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), i, souffle::LT, nameUnnamedVariables(), and souffle::AstToRamTranslator::ClauseTranslator::translateClause().
Referenced by getConstantRamRepresentation(), and translateProgram().
{
     auto intermediateClause = mk<ast::Clause>(souffle::clone(clause.getHead()));
     // create a clone where all the constraints are moved to the end
     for (auto bodyLit : clause.getBodyLiterals()) {
         // first add all the things that are not constraints
         if (!isA<ast::Constraint>(bodyLit)) {
             intermediateClause->addToBody(souffle::clone(bodyLit));
         }
     }
     // now add all constraints
     for (auto bodyLit : ast::getBodyLiterals<ast::Constraint>(clause)) {
         intermediateClause->addToBody(souffle::clone(bodyLit));
     }
     // name unnamed variables
     nameUnnamedVariables(intermediateClause.get());
     // add constraint for each argument in head of atom
     ast::Atom* head = intermediateClause->getHead();
     size_t auxiliaryArity = auxArityAnalysis->getArity(head);
     auto args = head->getArguments();
     for (size_t i = 0; i < head->getArity() - auxiliaryArity; i++) {
         auto arg = args[i];
         if (auto var = dynamic_cast<ast::Variable*>(arg)) {
             // FIXME: float equiv (`FEQ`)
             intermediateClause->addToBody(mk<ast::BinaryConstraint>(
                     BinaryConstraintOp::EQ, souffle::clone(var), mk<ast::SubroutineArgument>(i)));
         } else if (auto func = dynamic_cast<ast::Functor*>(arg)) {
             auto opEq = func->getReturnType() == TypeAttribute::Float ? BinaryConstraintOp::FEQ
                                                                       : BinaryConstraintOp::EQ;
             intermediateClause->addToBody(
                     mk<ast::BinaryConstraint>(opEq, souffle::clone(func), mk<ast::SubroutineArgument>(i)));
         } else if (auto rec = dynamic_cast<ast::RecordInit*>(arg)) {
             intermediateClause->addToBody(mk<ast::BinaryConstraint>(
                     BinaryConstraintOp::EQ, souffle::clone(rec), mk<ast::SubroutineArgument>(i)));
         }
     }
     // index of level argument in argument list
     size_t levelIndex = head->getArguments().size() - auxiliaryArity;
     // add level constraints, i.e., that each body literal has height less than that of the head atom
     const auto& bodyLiterals = intermediateClause->getBodyLiterals();
     for (auto lit : bodyLiterals) {
         if (auto atom = dynamic_cast<ast::Atom*>(lit)) {
             auto arity = atom->getArity();
             auto atomArgs = atom->getArguments();
             // arity - 1 is the level number in body atoms
             intermediateClause->addToBody(mk<ast::BinaryConstraint>(BinaryConstraintOp::LT,
                     souffle::clone(atomArgs[arity - 1]), mk<ast::SubroutineArgument>(levelIndex)));
         }
     }
     return ProvenanceClauseTranslator(*this).translateClause(*intermediateClause, clause);
 }
makeSubproofSubroutineOpt()
Own<ram::Statement> souffle::AstToRamTranslator::makeSubproofSubroutineOpt (const ast::Clause & clause) private
translate RAM code for subroutine to get subproofs
Referenced by getConstantRamRepresentation().
nameUnnamedVariables()
void souffle::AstToRamTranslator::nameUnnamedVariables (ast::Clause * clause) private
assigns names to unnamed variables such that enclosing constructs may be cloned without losing the variable-identity
A utility function assigning names to unnamed variables such that enclosing constructs may be cloned without losing the variable-identity.
Definition at line 969 of file AstToRamTranslator.cpp.
References souffle::toString().
Referenced by makeSubproofSubroutine(), and translateRecursiveRelation().
{
     // the node mapper conducting the actual renaming
     struct Instantiator : public ast::NodeMapper {
         mutable int counter = 0;
         Instantiator() = default;
         Own<ast::Node> operator()(Own<ast::Node> node) const override {
             // apply recursive
             node->apply(*this);
             // replace unknown variables
             if (dynamic_cast<ast::UnnamedVariable*>(node.get()) != nullptr) {
                 auto name = " _unnamed_var" + toString(++counter);
                 return mk<ast::Variable>(name);
             }
             // otherwise nothing
             return node;
         }
     };
     // name all variables in the atoms
     Instantiator init;
     for (auto& atom : ast::getBodyLiterals<ast::Atom>(*clause)) {
         atom->apply(init);
     }
 }
translateConstant()
Own< ram::Expression > souffle::AstToRamTranslator::translateConstant (ast::Constant const & c) private
translate RAM code for a constant value
Definition at line 886 of file AstToRamTranslator.cpp.
References souffle::ast::NumericConstant::Float, getConstantRamRepresentation(), souffle::ast::NumericConstant::Int, and souffle::ast::NumericConstant::Uint.
Referenced by getConstantRamRepresentation().
{
     auto const rawConstant = getConstantRamRepresentation(c);
     if (auto* const c_num = dynamic_cast<const ast::NumericConstant*>(&c)) {
         switch (*c_num->getType()) {
             case ast::NumericConstant::Type::Int: return mk<ram::SignedConstant>(rawConstant);
             case ast::NumericConstant::Type::Uint: return mk<ram::UnsignedConstant>(rawConstant);
             case ast::NumericConstant::Type::Float: return mk<ram::FloatConstant>(rawConstant);
         }
     }
     return mk<ram::SignedConstant>(rawConstant);
 }
translateConstraint()
Own< ram::Condition > souffle::AstToRamTranslator::translateConstraint (const ast::Literal * arg, const ValueIndex & index) private
translate an AST constraint to a RAM condition
for atoms
for binary relations
for provenance negation
for negations
Definition at line 332 of file AstToRamTranslator.cpp.
References souffle::Global::config(), souffle::ast::Negation::getAtom(), getEvaluationArity(), souffle::ast::BinaryConstraint::getLHS(), souffle::ast::BinaryConstraint::getOperator(), souffle::ast::BinaryConstraint::getRHS(), i, translateRelation(), and translateValue().
Referenced by getRelationName(), and makeNegationSubproofSubroutine().
{
     class ConstraintTranslator : public ast::Visitor<Own<ram::Condition>> {
         AstToRamTranslator& translator;
         const ValueIndex& index;
     public:
         ConstraintTranslator(AstToRamTranslator& translator, const ValueIndex& index)
                 : translator(translator), index(index) {}
         /** for atoms */
         Own<ram::Condition> visitAtom(const ast::Atom&) override {
             return nullptr;  // covered already within the scan/lookup generation step
         }
         /** for binary relations */
         Own<ram::Condition> visitBinaryConstraint(const ast::BinaryConstraint& binRel) override {
             auto valLHS = translator.translateValue(binRel.getLHS(), index);
             auto valRHS = translator.translateValue(binRel.getRHS(), index);
             return mk<ram::Constraint>(binRel.getOperator(), std::move(valLHS), std::move(valRHS));
         }
         /** for provenance negation */
         Own<ram::Condition> visitProvenanceNegation(const ast::ProvenanceNegation& neg) override {
             const auto* atom = neg.getAtom();
             size_t auxiliaryArity = translator.getEvaluationArity(atom);
             assert(auxiliaryArity <= atom->getArity() && "auxiliary arity out of bounds");
             size_t arity = atom->getArity() - auxiliaryArity;
             VecOwn<ram::Expression> values;
             auto args = atom->getArguments();
             for (size_t i = 0; i < arity; i++) {
                 values.push_back(translator.translateValue(args[i], index));
             }
             // we don't care about the provenance columns when doing the existence check
             if (Global::config().has("provenance")) {
                 // undefined value for rule number
                 values.push_back(mk<ram::UndefValue>());
                 // add the height annotation for provenanceNotExists
                 for (size_t height = 1; height < auxiliaryArity; height++) {
                     values.push_back(translator.translateValue(args[arity + height], index));
                 }
             }
             return mk<ram::Negation>(
                     mk<ram::ProvenanceExistenceCheck>(translator.translateRelation(atom), std::move(values)));
         }
         /** for negations */
         Own<ram::Condition> visitNegation(const ast::Negation& neg) override {
             const auto* atom = neg.getAtom();
             size_t auxiliaryArity = translator.getEvaluationArity(atom);
             assert(auxiliaryArity <= atom->getArity() && "auxiliary arity out of bounds");
             size_t arity = atom->getArity() - auxiliaryArity;
             if (arity == 0) {
                 // for a nullary, negation is a simple emptiness check
                 return mk<ram::EmptinessCheck>(translator.translateRelation(atom));
             }
             // else, we construct the atom and create a negation
             VecOwn<ram::Expression> values;
             auto args = atom->getArguments();
             for (size_t i = 0; i < arity; i++) {
                 values.push_back(translator.translateValue(args[i], index));
             }
             for (size_t i = 0; i < auxiliaryArity; i++) {
                 values.push_back(mk<ram::UndefValue>());
             }
             return mk<ram::Negation>(
                     mk<ram::ExistenceCheck>(translator.translateRelation(atom), std::move(values)));
         }
     };
     return ConstraintTranslator(*this, index)(*lit);
 }
translateDeltaRelation()
Own< ram::RelationReference > souffle::AstToRamTranslator::translateDeltaRelation (const ast::Relation * rel) private
translate a temporary delta relation to a RAM relation for semi-naive evaluation
Definition at line 226 of file AstToRamTranslator.cpp.
References translateRelation().
Referenced by getRelationName(), and translateRecursiveRelation().
{
     return translateRelation(rel, "@delta_");
 }
translateDirectives()
void souffle::AstToRamTranslator::translateDirectives (std::map< std::string, std::string > & directives, const ast::Relation * rel) private
translate AST directives to RAM directives
Referenced by getRelationName().
translateNewRelation()
Own< ram::RelationReference > souffle::AstToRamTranslator::translateNewRelation (const ast::Relation * rel) private
translate a temporary new relation to a RAM relation for semi-naive evaluation
Definition at line 230 of file AstToRamTranslator.cpp.
References translateRelation().
Referenced by getRelationName(), and translateRecursiveRelation().
{
     return translateRelation(rel, "@new_");
 }
translateNonRecursiveRelation()
Own< ram::Statement > souffle::AstToRamTranslator::translateNonRecursiveRelation (const ast::Relation & rel, const ast::analysis::RecursiveClausesAnalysis * recursiveClauses) private
translate RAM code for the non-recursive clauses of the given relation.
generate RAM code for a non-recursive relation
Returns
a corresponding statement or null if there are no non-recursive clauses.
Definition at line 901 of file AstToRamTranslator.cpp.
References souffle::appendStmt(), souffle::clone(), souffle::Global::config(), souffle::ast::getClauses(), souffle::ast::Relation::getQualifiedName(), souffle::ast::Node::getSrcLoc(), souffle::LogStatement::nNonrecursiveRelation(), souffle::LogStatement::nNonrecursiveRule(), program, souffle::ast::analysis::RecursiveClausesAnalysis::recursive(), rule, souffle::stringify(), souffle::LogStatement::tNonrecursiveRelation(), souffle::LogStatement::tNonrecursiveRule(), souffle::toString(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and translateRelation().
Referenced by getConstantRamRepresentation(), translateProgram(), and translateRecursiveRelation().
{
     /* start with an empty sequence */
     VecOwn<ram::Statement> res;
     // the ram table reference
     Own<ram::RelationReference> rrel = translateRelation(&rel);
     /* iterate over all clauses that belong to the relation */
     for (ast::Clause* clause : getClauses(*program, rel)) {
         // skip recursive rules
         if (recursiveClauses->recursive(clause)) {
             continue;
         }
         // translate clause
         Own<ram::Statement> rule = ClauseTranslator(*this).translateClause(*clause, *clause);
         // add logging
         if (Global::config().has("profile")) {
             const std::string& relationName = toString(rel.getQualifiedName());
             const SrcLocation& srcLocation = clause->getSrcLoc();
             const std::string clauseText = stringify(toString(*clause));
             const std::string logTimerStatement =
                     LogStatement::tNonrecursiveRule(relationName, srcLocation, clauseText);
             const std::string logSizeStatement =
                     LogStatement::nNonrecursiveRule(relationName, srcLocation, clauseText);
             rule = mk<ram::LogRelationTimer>(std::move(rule), logTimerStatement, souffle::clone(rrel));
         }
         // add debug info
         std::ostringstream ds;
         ds << toString(*clause) << "\nin file ";
         ds << clause->getSrcLoc();
         rule = mk<ram::DebugInfo>(std::move(rule), ds.str());
         // add rule to result
         appendStmt(res, std::move(rule));
     }
     // add logging for entire relation
     if (Global::config().has("profile")) {
         const std::string& relationName = toString(rel.getQualifiedName());
         const SrcLocation& srcLocation = rel.getSrcLoc();
         const std::string logSizeStatement = LogStatement::nNonrecursiveRelation(relationName, srcLocation);
         // add timer if we did any work
         if (!res.empty()) {
             const std::string logTimerStatement =
                     LogStatement::tNonrecursiveRelation(relationName, srcLocation);
             auto newStmt = mk<ram::LogRelationTimer>(
                     mk<ram::Sequence>(std::move(res)), logTimerStatement, souffle::clone(rrel));
             res.clear();
             appendStmt(res, std::move(newStmt));
         } else {
             // add table size printer
             appendStmt(res, mk<ram::LogSize>(souffle::clone(rrel), logSizeStatement));
         }
     }
     // done
     return mk<ram::Sequence>(std::move(res));
 }
translateProgram()
void souffle::AstToRamTranslator::translateProgram (const ast::TranslationUnit & translationUnit) private
translate AST to RAM Program
translates the given datalog program into an equivalent RAM program
Definition at line 1490 of file AstToRamTranslator.cpp.
References souffle::appendStmt(), auxArityAnalysis, souffle::Global::config(), directives, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::analysis::AuxiliaryArityAnalysis::getArity(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::getClauseNum(), souffle::ast::Clause::getHead(), getInputDirectives(), souffle::getName, getOutputDirectives(), souffle::ast::Atom::getQualifiedName(), souffle::ast::analysis::getTypeQualifier(), i, ioType, makeNegationSubproofSubroutine(), makeSubproofSubroutine(), program, ramMain, ramRels, ramSubs, relation, souffle::LogStatement::runtime(), souffle::toString(), translateNonRecursiveRelation(), translateRecursiveRelation(), translateRelation(), souffle::LogStatement::tRelationLoadTime(), souffle::LogStatement::tRelationSaveTime(), typeEnv, and souffle::ast::visitDepthFirst().
Referenced by getConstantRamRepresentation(), and translateUnit().
{
     // obtain IO Type of relations
     ioType = translationUnit.getAnalysis<ast::analysis::IOTypeAnalysis>();
     // obtain type environment from analysis
     typeEnv = &translationUnit.getAnalysis<ast::analysis::TypeEnvironmentAnalysis>()->getTypeEnvironment();
     // obtain recursive clauses from analysis
     const auto* recursiveClauses = translationUnit.getAnalysis<ast::analysis::RecursiveClausesAnalysis>();
     // obtain strongly connected component (SCC) graph from analysis
     const auto& sccGraph = *translationUnit.getAnalysis<ast::analysis::SCCGraphAnalysis>();
     // obtain some topological order over the nodes of the SCC graph
     const auto& sccOrder = *translationUnit.getAnalysis<ast::analysis::TopologicallySortedSCCGraphAnalysis>();
     // obtain the schedule of relations expired at each index of the topological order
     const auto& expirySchedule =
             translationUnit.getAnalysis<ast::analysis::RelationScheduleAnalysis>()->schedule();
     // get auxiliary arity analysis
     auxArityAnalysis = translationUnit.getAnalysis<ast::analysis::AuxiliaryArityAnalysis>();
     // handle the case of an empty SCC graph
     if (sccGraph.getNumberOfSCCs() == 0) return;
     // a function to load relations
     const auto& makeRamLoad = [&](VecOwn<ram::Statement>& current, const ast::Relation* relation) {
         for (auto directives : getInputDirectives(relation)) {
             Own<ram::Statement> statement =
                     mk<ram::IO>(Own<ram::RelationReference>(translateRelation(relation)), directives);
             if (Global::config().has("profile")) {
                 const std::string logTimerStatement = LogStatement::tRelationLoadTime(
                         toString(relation->getQualifiedName()), relation->getSrcLoc());
                 statement = mk<ram::LogRelationTimer>(std::move(statement), logTimerStatement,
                         Own<ram::RelationReference>(translateRelation(relation)));
             }
             appendStmt(current, std::move(statement));
         }
     };
     // a function to store relations
     const auto& makeRamStore = [&](VecOwn<ram::Statement>& current, const ast::Relation* relation) {
         for (auto directives : getOutputDirectives(relation)) {
             Own<ram::Statement> statement =
                     mk<ram::IO>(Own<ram::RelationReference>(translateRelation(relation)), directives);
             if (Global::config().has("profile")) {
                 const std::string logTimerStatement = LogStatement::tRelationSaveTime(
                         toString(relation->getQualifiedName()), relation->getSrcLoc());
                 statement = mk<ram::LogRelationTimer>(std::move(statement), logTimerStatement,
                         Own<ram::RelationReference>(translateRelation(relation)));
             }
             appendStmt(current, std::move(statement));
         }
     };
     // a function to drop relations
     const auto& makeRamClear = [&](VecOwn<ram::Statement>& current, const ast::Relation* relation) {
         appendStmt(current, mk<ram::Clear>(translateRelation(relation)));
     };
     // maintain the index of the SCC within the topological order
     size_t indexOfScc = 0;
     // create all Ram relations in ramRels
     for (const auto& scc : sccOrder.order()) {
         const auto& isRecursive = sccGraph.isRecursive(scc);
         const auto& allInterns = sccGraph.getInternalRelations(scc);
         for (const auto& rel : allInterns) {
             std::string name = rel->getQualifiedName().toString();
             auto arity = rel->getArity();
             auto auxiliaryArity = auxArityAnalysis->getArity(rel);
             auto representation = rel->getRepresentation();
             const auto& attributes = rel->getAttributes();
             std::vector<std::string> attributeNames;
             std::vector<std::string> attributeTypeQualifiers;
             for (size_t i = 0; i < rel->getArity(); ++i) {
                 attributeNames.push_back(attributes[i]->getName());
                 if (typeEnv != nullptr) {
                     attributeTypeQualifiers.push_back(
                             getTypeQualifier(typeEnv->getType(attributes[i]->getTypeName())));
                 }
             }
             ramRels[name] = mk<ram::Relation>(
                     name, arity, auxiliaryArity, attributeNames, attributeTypeQualifiers, representation);
             if (isRecursive) {
                 std::string deltaName = "@delta_" + name;
                 std::string newName = "@new_" + name;
                 ramRels[deltaName] = mk<ram::Relation>(deltaName, arity, auxiliaryArity, attributeNames,
                         attributeTypeQualifiers, representation);
                 ramRels[newName] = mk<ram::Relation>(newName, arity, auxiliaryArity, attributeNames,
                         attributeTypeQualifiers, representation);
             }
         }
     }
     // iterate over each SCC according to the topological order
     for (const auto& scc : sccOrder.order()) {
         // make a new ram statement for the current SCC
         VecOwn<ram::Statement> current;
         // find out if the current SCC is recursive
         const auto& isRecursive = sccGraph.isRecursive(scc);
         // make variables for particular sets of relations contained within the current SCC, and,
         // predecessors and successor SCCs thereof
         const auto& allInterns = sccGraph.getInternalRelations(scc);
         const auto& internIns = sccGraph.getInternalInputRelations(scc);
         const auto& internOuts = sccGraph.getInternalOutputRelations(scc);
         // make a variable for all relations that are expired at the current SCC
         const auto& internExps = expirySchedule.at(indexOfScc).expired();
         // load all internal input relations from the facts dir with a .facts extension
         for (const auto& relation : internIns) {
             makeRamLoad(current, relation);
         }
         // compute the relations themselves
         Own<ram::Statement> bodyStatement =
                 (!isRecursive) ? translateNonRecursiveRelation(
                                          *((const ast::Relation*)*allInterns.begin()), recursiveClauses)
                                : translateRecursiveRelation(allInterns, recursiveClauses);
         appendStmt(current, std::move(bodyStatement));
         // store all internal output relations to the output dir with a .csv extension
         for (const auto& relation : internOuts) {
             makeRamStore(current, relation);
         }
         // if provenance is not enabled...
         if (!Global::config().has("provenance")) {
             // otherwise, drop all  relations expired as per the topological order
             for (const auto& relation : internExps) {
                 makeRamClear(current, relation);
             }
         }
         // create subroutine for this stratum
         ramSubs["stratum_" + std::to_string(indexOfScc)] = mk<ram::Sequence>(std::move(current));
         indexOfScc++;
     }
     // invoke all strata
     VecOwn<ram::Statement> res;
     for (size_t i = 0; i < indexOfScc; i++) {
         appendStmt(res, mk<ram::Call>("stratum_" + std::to_string(i)));
     }
     // add main timer if profiling
     if (res.size() > 0 && Global::config().has("profile")) {
         auto newStmt = mk<ram::LogTimer>(mk<ram::Sequence>(std::move(res)), LogStatement::runtime());
         res.clear();
         appendStmt(res, std::move(newStmt));
     }
     // done for main prog
     ramMain = mk<ram::Sequence>(std::move(res));
     // add subroutines for each clause
     if (Global::config().has("provenance")) {
         visitDepthFirst(*program, [&](const ast::Clause& clause) {
             std::stringstream relName;
             relName << clause.getHead()->getQualifiedName();
             // do not add subroutines for info relations or facts
             if (relName.str().find("@info") != std::string::npos || clause.getBodyLiterals().empty()) {
                 return;
             }
             std::string subroutineLabel =
                     relName.str() + "_" + std::to_string(getClauseNum(program, &clause)) + "_subproof";
             ramSubs[subroutineLabel] = makeSubproofSubroutine(clause);
             std::string negationSubroutineLabel = relName.str() + "_" +
                                                   std::to_string(getClauseNum(program, &clause)) +
                                                   "_negation_subproof";
             ramSubs[negationSubroutineLabel] = makeNegationSubproofSubroutine(clause);
         });
     }
 }
translateRecursiveRelation()
Own< ram::Statement > souffle::AstToRamTranslator::translateRecursiveRelation (const std::set< const ast::Relation *> & scc, const ast::analysis::RecursiveClausesAnalysis * recursiveClauses) private
translate RAM code for recursive relations in a strongly-connected component
generate RAM code for recursive relations in a strongly-connected component
Definition at line 999 of file AstToRamTranslator.cpp.
References souffle::appendStmt(), souffle::clone(), souffle::Global::config(), souffle::LogStatement::cRecursiveRelation(), souffle::EQREL, souffle::fatal(), souffle::GE, souffle::ram::RelationReference::get(), souffle::ram::Relation::getArity(), souffle::ast::getAtomRelation(), souffle::ast::getClauses(), souffle::ast::analysis::IOTypeAnalysis::getLimitSize(), souffle::getName, souffle::ram::Relation::getRepresentation(), i, ioType, souffle::ast::analysis::IOTypeAnalysis::isLimitSize(), j, k, nameUnnamedVariables(), souffle::LogStatement::nRecursiveRelation(), souffle::LogStatement::nRecursiveRule(), program, souffle::ast::analysis::RecursiveClausesAnalysis::recursive(), rule, souffle::stringify(), souffle::toString(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), translateDeltaRelation(), translateNewRelation(), translateNonRecursiveRelation(), translateRelation(), souffle::LogStatement::tRecursiveRelation(), and souffle::LogStatement::tRecursiveRule().
Referenced by getConstantRamRepresentation(), and translateProgram().
{
     // initialize sections
     VecOwn<ram::Statement> preamble;
     VecOwn<ram::Statement> updateTable;
     VecOwn<ram::Statement> postamble;
     auto genMerge = [](const ram::RelationReference* dest,
                             const ram::RelationReference* src) -> Own<ram::Statement> {
         VecOwn<ram::Expression> values;
         if (src->get()->getArity() == 0) {
             return mk<ram::Query>(
                     mk<ram::Filter>(mk<ram::Negation>(mk<ram::EmptinessCheck>(souffle::clone(src))),
                             mk<ram::Project>(souffle::clone(dest), std::move(values))));
         }
         for (std::size_t i = 0; i < dest->get()->getArity(); i++) {
             values.push_back(mk<ram::TupleElement>(0, i));
         }
         auto stmt = mk<ram::Query>(mk<ram::Scan>(
                 souffle::clone(src), 0, mk<ram::Project>(souffle::clone(dest), std::move(values))));
         if (dest->get()->getRepresentation() == RelationRepresentation::EQREL) {
             return mk<ram::Sequence>(
                     mk<ram::Extend>(souffle::clone(dest), souffle::clone(src)), std::move(stmt));
         }
         return stmt;
     };
     // --- create preamble ---
     /* Compute non-recursive clauses for relations in scc and push
        the results in their delta tables. */
     for (const ast::Relation* rel : scc) {
         /* create update statements for fixpoint (even iteration) */
         Own<ram::Statement> updateRelTable =
                 mk<ram::Sequence>(genMerge(translateRelation(rel).get(), translateNewRelation(rel).get()),
                         mk<ram::Swap>(translateDeltaRelation(rel), translateNewRelation(rel)),
                         mk<ram::Clear>(translateNewRelation(rel)));
         /* measure update time for each relation */
         if (Global::config().has("profile")) {
             updateRelTable = mk<ram::LogRelationTimer>(std::move(updateRelTable),
                     LogStatement::cRecursiveRelation(toString(rel->getQualifiedName()), rel->getSrcLoc()),
                     translateNewRelation(rel));
         }
         /* drop temporary tables after recursion */
         appendStmt(postamble, mk<ram::Clear>(translateDeltaRelation(rel)));
         appendStmt(postamble, mk<ram::Clear>(translateNewRelation(rel)));
         /* Generate code for non-recursive part of relation */
         /* Generate merge operation for temp tables */
         appendStmt(preamble, translateNonRecursiveRelation(*rel, recursiveClauses));
         appendStmt(preamble, genMerge(translateDeltaRelation(rel).get(), translateRelation(rel).get()));
         /* Add update operations of relations to parallel statements */
         appendStmt(updateTable, std::move(updateRelTable));
     }
     // --- build main loop ---
     VecOwn<ram::Statement> loopSeq;
     // create a utility to check SCC membership
     auto isInSameSCC = [&](const ast::Relation* rel) {
         return std::find(scc.begin(), scc.end(), rel) != scc.end();
     };
     /* Compute temp for the current tables */
     for (const ast::Relation* rel : scc) {
         VecOwn<ram::Statement> loopRelSeq;
         /* Find clauses for relation rel */
         for (const auto& cl : getClauses(*program, *rel)) {
             // skip non-recursive clauses
             if (!recursiveClauses->recursive(cl)) {
                 continue;
             }
             // each recursive rule results in several operations
             int version = 0;
             const auto& atoms = ast::getBodyLiterals<ast::Atom>(*cl);
             for (size_t j = 0; j < atoms.size(); ++j) {
                 const ast::Atom* atom = atoms[j];
                 const ast::Relation* atomRelation = getAtomRelation(atom, program);
                 // only interested in atoms within the same SCC
                 if (!isInSameSCC(atomRelation)) {
                     continue;
                 }
                 // modify the processed rule to use delta relation and write to new relation
                 Own<ast::Clause> r1(cl->clone());
                 r1->getHead()->setQualifiedName(translateNewRelation(rel)->get()->getName());
                 ast::getBodyLiterals<ast::Atom>(*r1)[j]->setQualifiedName(
                         translateDeltaRelation(atomRelation)->get()->getName());
                 if (Global::config().has("provenance")) {
                     r1->addToBody(mk<ast::ProvenanceNegation>(souffle::clone(cl->getHead())));
                 } else {
                     if (r1->getHead()->getArity() > 0) {
                         r1->addToBody(mk<ast::Negation>(souffle::clone(cl->getHead())));
                     }
                 }
                 // replace wildcards with variables (reduces indices when wildcards are used in recursive
                 // atoms)
                 nameUnnamedVariables(r1.get());
                 // reduce R to P ...
                 for (size_t k = j + 1; k < atoms.size(); k++) {
                     if (isInSameSCC(getAtomRelation(atoms[k], program))) {
                         auto cur = souffle::clone(ast::getBodyLiterals<ast::Atom>(*r1)[k]);
                         cur->setQualifiedName(
                                 translateDeltaRelation(getAtomRelation(atoms[k], program))->get()->getName());
                         r1->addToBody(mk<ast::Negation>(std::move(cur)));
                     }
                 }
                 Own<ram::Statement> rule = ClauseTranslator(*this).translateClause(*r1, *cl, version);
                 /* add logging */
                 if (Global::config().has("profile")) {
                     const std::string& relationName = toString(rel->getQualifiedName());
                     const SrcLocation& srcLocation = cl->getSrcLoc();
                     const std::string clauseText = stringify(toString(*cl));
                     const std::string logTimerStatement =
                             LogStatement::tRecursiveRule(relationName, version, srcLocation, clauseText);
                     const std::string logSizeStatement =
                             LogStatement::nRecursiveRule(relationName, version, srcLocation, clauseText);
                     rule = mk<ram::LogRelationTimer>(
                             std::move(rule), logTimerStatement, translateNewRelation(rel));
                 }
                 // add debug info
                 std::ostringstream ds;
                 ds << toString(*cl) << "\nin file ";
                 ds << cl->getSrcLoc();
                 rule = mk<ram::DebugInfo>(std::move(rule), ds.str());
                 // add to loop body
                 appendStmt(loopRelSeq, std::move(rule));
                 // increment version counter
                 version++;
             }
             if (cl->getExecutionPlan() != nullptr) {
                 // ensure that all required versions have been created, as expected
                 int maxVersion = -1;
                 for (auto const& cur : cl->getExecutionPlan()->getOrders()) {
                     maxVersion = std::max(cur.first, maxVersion);
                 }
                 assert(version > maxVersion && "missing clause versions");
             }
         }
         // if there was no rule, continue
         if (loopRelSeq.size() == 0) {
             continue;
         }
         // label all versions
         if (Global::config().has("profile")) {
             const std::string& relationName = toString(rel->getQualifiedName());
             const SrcLocation& srcLocation = rel->getSrcLoc();
             const std::string logTimerStatement = LogStatement::tRecursiveRelation(relationName, srcLocation);
             const std::string logSizeStatement = LogStatement::nRecursiveRelation(relationName, srcLocation);
             auto newStmt = mk<ram::LogRelationTimer>(
                     mk<ram::Sequence>(std::move(loopRelSeq)), logTimerStatement, translateNewRelation(rel));
             loopRelSeq.clear();
             appendStmt(loopRelSeq, std::move(newStmt));
         }
         /* add rule computations of a relation to parallel statement */
         appendStmt(loopSeq, mk<ram::Sequence>(std::move(loopRelSeq)));
     }
     auto loop = mk<ram::Parallel>(std::move(loopSeq));
     /* construct exit conditions for odd and even iteration */
     auto addCondition = [](Own<ram::Condition>& cond, Own<ram::Condition> clause) {
         cond = ((cond) ? mk<ram::Conjunction>(std::move(cond), std::move(clause)) : std::move(clause));
     };
     Own<ram::Condition> exitCond;
     VecOwn<ram::Statement> exitStmts;
     for (const ast::Relation* rel : scc) {
         addCondition(exitCond, mk<ram::EmptinessCheck>(translateNewRelation(rel)));
         if (ioType->isLimitSize(rel)) {
             Own<ram::Condition> limit =
                     mk<ram::Constraint>(BinaryConstraintOp::GE, mk<ram::RelationSize>(translateRelation(rel)),
                             mk<ram::SignedConstant>(ioType->getLimitSize(rel)));
             appendStmt(exitStmts, mk<ram::Exit>(std::move(limit)));
         }
     }
     /* construct fixpoint loop  */
     VecOwn<ram::Statement> res;
     if (preamble.size() > 0) {
         appendStmt(res, mk<ram::Sequence>(std::move(preamble)));
     }
     if (!loop->getStatements().empty() && exitCond && updateTable.size() > 0) {
         appendStmt(res,
                 mk<ram::Loop>(mk<ram::Sequence>(std::move(loop), mk<ram::Exit>(std::move(exitCond)),
                         mk<ram::Sequence>(std::move(exitStmts)), mk<ram::Sequence>(std::move(updateTable)))));
     }
     if (postamble.size() > 0) {
         appendStmt(res, mk<ram::Sequence>(std::move(postamble)));
     }
     if (res.size() > 0) {
         return mk<ram::Sequence>(std::move(res));
     }
     fatal("Not Implemented");
 }
translateRelation() [1/2]
Own< ram::RelationReference > souffle::AstToRamTranslator::translateRelation (const ast::Atom * atom) private
a utility to translate atoms to relations
Definition at line 217 of file AstToRamTranslator.cpp.
References createRelationReference(), souffle::ast::Atom::getQualifiedName(), and getRelationName().
Referenced by getRelationName(), makeNegationSubproofSubroutine(), translateConstraint(), translateDeltaRelation(), translateNewRelation(), translateNonRecursiveRelation(), translateProgram(), and translateRecursiveRelation().
{
     return createRelationReference(getRelationName(atom->getQualifiedName()));
 }
translateRelation() [2/2]
Own< ram::RelationReference > souffle::AstToRamTranslator::translateRelation (const ast::Relation * rel, const std::string relationNamePrefix = "") private
translate an AST relation to a RAM relation
Definition at line 221 of file AstToRamTranslator.cpp.
References createRelationReference(), souffle::ast::Relation::getQualifiedName(), and getRelationName().
{
     return createRelationReference(relationNamePrefix + getRelationName(rel->getQualifiedName()));
 }
translateUnit()
Own< ram::TranslationUnit > souffle::AstToRamTranslator::translateUnit (ast::TranslationUnit & tu)
translates AST to translation unit
Definition at line 1671 of file AstToRamTranslator.cpp.
References souffle::DebugReport::addSection(), souffle::Global::config(), souffle::test::count(), souffle::ast::TranslationUnit::getDebugReport(), souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::TranslationUnit::getProgram(), getSymbolTable(), souffle::now(), program, ramMain, ramRels, ramSubs, and translateProgram().
Referenced by souffle::main().
{
     auto ram_start = std::chrono::high_resolution_clock::now();
     program = &tu.getProgram();
     translateProgram(tu);
     SymbolTable& symTab = getSymbolTable();
     ErrorReport& errReport = tu.getErrorReport();
     DebugReport& debugReport = tu.getDebugReport();
     VecOwn<ram::Relation> rels;
     for (auto& cur : ramRels) {
         rels.push_back(std::move(cur.second));
     }
     if (ramMain == nullptr) {
         ramMain = mk<ram::Sequence>();
     }
     auto ramProg = mk<ram::Program>(std::move(rels), std::move(ramMain), std::move(ramSubs));
     if (!Global::config().get("debug-report").empty()) {
         if (ramProg) {
             auto ram_end = std::chrono::high_resolution_clock::now();
             std::string runtimeStr =
                     "(" + std::to_string(std::chrono::duration<double>(ram_end - ram_start).count()) + "s)";
             std::stringstream ramProgStr;
             ramProgStr << *ramProg;
             debugReport.addSection("ram-program", "RAM Program " + runtimeStr, ramProgStr.str());
         }
     }
     return mk<ram::TranslationUnit>(std::move(ramProg), std::move(symTab), errReport, debugReport);
 }
translateValue()
Own< ram::Expression > souffle::AstToRamTranslator::translateValue (const ast::Argument * arg, const ValueIndex & index) private
translate an AST argument to a RAM value
Definition at line 234 of file AstToRamTranslator.cpp.
References souffle::fatal(), souffle::ast::NumericConstant::Float, souffle::ast::UserDefinedFunctor::getArgsTypes(), souffle::ast::Term::getArguments(), souffle::ast::Constant::getConstant(), souffle::AstToRamTranslator::ValueIndex::getDefinitionPoint(), souffle::ast::IntrinsicFunctor::getFunctionInfo(), souffle::AstToRamTranslator::ValueIndex::getGeneratorLoc(), souffle::ast::UserDefinedFunctor::getName(), souffle::ast::SubroutineArgument::getNumber(), souffle::ast::UserDefinedFunctor::getReturnType(), getSymbolTable(), souffle::ast::NumericConstant::getType(), souffle::ast::NumericConstant::Int, souffle::AstToRamTranslator::ValueIndex::isDefined(), souffle::ast::UserDefinedFunctor::isStateful(), souffle::SymbolTable::lookup(), makeRamTupleElement(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), souffle::RamUnsignedFromString(), translateValue(), and souffle::ast::NumericConstant::Uint.
Referenced by getRelationName(), makeNegationSubproofSubroutine(), translateConstraint(), and translateValue().
{
     if (arg == nullptr) {
         return nullptr;
     }
     class ValueTranslator : public ast::Visitor<Own<ram::Expression>> {
         AstToRamTranslator& translator;
         const ValueIndex& index;
     public:
         ValueTranslator(AstToRamTranslator& translator, const ValueIndex& index)
                 : translator(translator), index(index) {}
         Own<ram::Expression> visitVariable(const ast::Variable& var) override {
             assert(index.isDefined(var) && "variable not grounded");
             return makeRamTupleElement(index.getDefinitionPoint(var));
         }
         Own<ram::Expression> visitUnnamedVariable(const ast::UnnamedVariable&) override {
             return mk<ram::UndefValue>();
         }
         Own<ram::Expression> visitNumericConstant(const ast::NumericConstant& c) override {
             assert(c.getType().has_value() && "At this points all constants should have type.");
             switch (*c.getType()) {
                 case ast::NumericConstant::Type::Int:
                     return mk<ram::SignedConstant>(RamSignedFromString(c.getConstant(), nullptr, 0));
                 case ast::NumericConstant::Type::Uint:
                     return mk<ram::UnsignedConstant>(RamUnsignedFromString(c.getConstant(), nullptr, 0));
                 case ast::NumericConstant::Type::Float:
                     return mk<ram::FloatConstant>(RamFloatFromString(c.getConstant()));
             }
             fatal("unexpected numeric constant type");
         }
         Own<ram::Expression> visitStringConstant(const ast::StringConstant& c) override {
             return mk<ram::SignedConstant>(translator.getSymbolTable().lookup(c.getConstant()));
         }
         Own<ram::Expression> visitNilConstant(const ast::NilConstant&) override {
             return mk<ram::SignedConstant>(0);
         }
         Own<ram::Expression> visitIntrinsicFunctor(const ast::IntrinsicFunctor& inf) override {
             VecOwn<ram::Expression> values;
             for (const auto& cur : inf.getArguments()) {
                 values.push_back(translator.translateValue(cur, index));
             }
             auto* info = inf.getFunctionInfo();
             assert(info && "no overload picked for instrinsic; missing transform pass?");
             if (info->multipleResults) {
                 return translator.makeRamTupleElement(index.getGeneratorLoc(inf));
             } else {
                 return mk<ram::IntrinsicOperator>(info->op, std::move(values));
             }
         }
         Own<ram::Expression> visitUserDefinedFunctor(const ast::UserDefinedFunctor& udf) override {
             // Sanity check.
             assert(udf.getArguments().size() == udf.getArgsTypes().size());
             VecOwn<ram::Expression> values;
             for (const auto& cur : udf.getArguments()) {
                 values.push_back(translator.translateValue(cur, index));
             }
             return mk<ram::UserDefinedOperator>(udf.getName(), udf.getArgsTypes(), udf.getReturnType(),
                     udf.isStateful(), std::move(values));
         }
         Own<ram::Expression> visitCounter(const ast::Counter&) override {
             return mk<ram::AutoIncrement>();
         }
         Own<ram::Expression> visitRecordInit(const ast::RecordInit& init) override {
             VecOwn<ram::Expression> values;
             for (const auto& cur : init.getArguments()) {
                 values.push_back(translator.translateValue(cur, index));
             }
             return mk<ram::PackRecord>(std::move(values));
         }
         Own<ram::Expression> visitAggregator(const ast::Aggregator& agg) override {
             // here we look up the location the aggregation result gets bound
             return translator.makeRamTupleElement(index.getGeneratorLoc(agg));
         }
         Own<ram::Expression> visitSubroutineArgument(const ast::SubroutineArgument& subArg) override {
             return mk<ram::SubroutineArgument>(subArg.getNumber());
         }
     };
     return ValueTranslator(*this, index)(*arg);
 }
Field Documentation
auxArityAnalysis
const ast::analysis::AuxiliaryArityAnalysis* souffle::AstToRamTranslator::auxArityAnalysis = nullptr private
Auxiliary Arity Analysis.
Definition at line 97 of file AstToRamTranslator.h.
Referenced by getEvaluationArity(), makeNegationSubproofSubroutine(), makeSubproofSubroutine(), and translateProgram().
ioType
const ast::analysis::IOTypeAnalysis* souffle::AstToRamTranslator::ioType = nullptr private
IO Type.
Definition at line 82 of file AstToRamTranslator.h.
Referenced by translateProgram(), and translateRecursiveRelation().
program
const ast::Program* souffle::AstToRamTranslator::program = nullptr private
AST program.
Definition at line 76 of file AstToRamTranslator.h.
Referenced by getEvaluationArity(), getInputDirectives(), getOutputDirectives(), translateNonRecursiveRelation(), translateProgram(), translateRecursiveRelation(), and translateUnit().
ramMain
Own<ram::Statement> souffle::AstToRamTranslator::ramMain private
RAM program.
Definition at line 85 of file AstToRamTranslator.h.
Referenced by translateProgram(), and translateUnit().
ramRels
std::map<std::string, Own<ram::Relation> > souffle::AstToRamTranslator::ramRels private
RAM relations.
Definition at line 91 of file AstToRamTranslator.h.
Referenced by createRelationReference(), translateProgram(), and translateUnit().
ramSubs
std::map<std::string, Own<ram::Statement> > souffle::AstToRamTranslator::ramSubs private
Subroutines.
Definition at line 88 of file AstToRamTranslator.h.
Referenced by translateProgram(), and translateUnit().
symbolTable
SymbolTable souffle::AstToRamTranslator::symbolTable private
Symbol Table.
Definition at line 94 of file AstToRamTranslator.h.
Referenced by getSymbolTable().
typeEnv
const ast::analysis::TypeEnvironment* souffle::AstToRamTranslator::typeEnv = nullptr private
Type environment.
Definition at line 79 of file AstToRamTranslator.h.
Referenced by translateProgram().
The documentation for this class was generated from the following files:
ast2ram/AstToRamTranslator.h
ast2ram/AstToRamTranslator.cpp