souffle: souffle::ast::analysis::Type Class Reference
souffle::ast::analysis::Type Class Reference
An abstract base class for types to be covered within a type environment.
#include <TypeSystem.h>
Public Member Functions
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
virtual void print (std::ostream &out) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
Type (const TypeEnvironment &environment, QualifiedName name)
Protected Attributes
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Friends
std::ostream & operator<< (std::ostream &out, const Type &t)
Detailed Description
An abstract base class for types to be covered within a type environment.
Definition at line 45 of file TypeSystem.h.
Constructor & Destructor Documentation
Type() [1/2]
souffle::ast::analysis::Type::Type (const Type & other) delete
Referenced by souffle::ast::AlgebraicDataType::AlgebraicDataType(), souffle::ast::RecordType::RecordType(), souffle::ast::analysis::RecordType::RecordType(), souffle::ast::SubsetType::SubsetType(), souffle::ast::UnionType::UnionType(), and souffle::ast::analysis::UnionType::UnionType().
~Type()
virtual souffle::ast::analysis::Type::~Type () virtual default
Type() [2/2]
souffle::ast::analysis::Type::Type (const TypeEnvironment & environment, QualifiedName name) inline protected
Definition at line 80 of file TypeSystem.h.
             : environment(environment), name(std::move(name)) {}
Member Function Documentation
getName()
const QualifiedName& souffle::ast::analysis::Type::getName () const inline
Definition at line 51 of file TypeSystem.h.
References name.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkSubsetType(), souffle::ast::analysis::getTypeQualifier(), souffle::ast::analysis::SubsetType::print(), souffle::ast::analysis::UnionType::print(), souffle::ast::analysis::RecordType::print(), souffle::ast::analysis::AlgebraicDataType::Branch::print(), and souffle::ast::analysis::TypeSet::print().
{
         return name;
     }
getTypeEnvironment()
const TypeEnvironment& souffle::ast::analysis::Type::getTypeEnvironment () const inline
Definition at line 55 of file TypeSystem.h.
References environment.
Referenced by souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::haveCommonSupertype(), souffle::ast::analysis::isOfKind(), souffle::ast::analysis::isSubtypeOf(), and souffle::ast::analysis::TypeEnvironment::isType().
{
         return environment;
     }
operator!=()
bool souffle::ast::analysis::Type::operator!= (const Type & other) const inline
Definition at line 63 of file TypeSystem.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::ast::analysis::Type::operator< (const Type & other) const inline
Definition at line 67 of file TypeSystem.h.
References name.
{
         return name < other.name;
     }
operator==()
bool souffle::ast::analysis::Type::operator== (const Type & other) const inline
Definition at line 59 of file TypeSystem.h.
{
         return this == &other;
     }
print()
virtual void souffle::ast::analysis::Type::print (std::ostream & out) const inline virtual
Reimplemented in souffle::ast::analysis::AlgebraicDataType, souffle::ast::analysis::SubsetRecordType, souffle::ast::analysis::RecordType, souffle::ast::analysis::UnionType, souffle::ast::analysis::PrimitiveType, souffle::ast::analysis::SubsetType, souffle::ast::RecordType, souffle::ast::UnionType, souffle::ast::AlgebraicDataType, and souffle::ast::SubsetType.
Definition at line 71 of file TypeSystem.h.
References name.
Referenced by souffle::ast::analysis::TypeEnvironment::getConstantNumericTypes(), souffle::ast::analysis::RecordType::getFields(), and souffle::ast::analysis::UnionType::setElements().
{
         out << name;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Type & t) friend
Definition at line 75 of file TypeSystem.h.
{
         return t.print(out), out;
     }
Field Documentation
environment
const TypeEnvironment& souffle::ast::analysis::Type::environment protected
A reference to the type environment this type is associated to.
Definition at line 84 of file TypeSystem.h.
Referenced by getTypeEnvironment().
name
QualifiedName souffle::ast::analysis::Type::name protected
Definition at line 86 of file TypeSystem.h.
Referenced by souffle::ast::analysis::TypeEnvironment::createType(), getName(), souffle::ast::Type::getQualifiedName(), operator<(), print(), souffle::ast::analysis::PrimitiveType::print(), souffle::ast::analysis::AlgebraicDataType::print(), and souffle::ast::Type::Type().
The documentation for this class was generated from the following file:
ast/analysis/TypeSystem.h