souffle: souffle::ast::analysis::RelationDetailCacheAnalysis Class Reference
souffle::ast::analysis::RelationDetailCacheAnalysis Class Reference
Analysis pass mapping identifiers with relations and clauses.
#include <RelationDetailCache.h>
Public Member Functions
std::set< Clause * > getClauses (const Relation *rel) const
std::set< Clause * > getClauses (const QualifiedName &name) const
Relation * getRelation (const QualifiedName &name) const
void print (std::ostream &os) const override
print the analysis result in HTML format
RelationDetailCacheAnalysis ()
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "relation-detail"
Private Attributes
std::map< QualifiedName, std::set< Clause * > > nameToClauses
std::map< QualifiedName, Relation * > nameToRelation
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass mapping identifiers with relations and clauses.
Definition at line 39 of file RelationDetailCache.h.
Constructor & Destructor Documentation
RelationDetailCacheAnalysis()
souffle::ast::analysis::RelationDetailCacheAnalysis::RelationDetailCacheAnalysis () inline
Definition at line 43 of file RelationDetailCache.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
getClauses() [1/2]
std::set<Clause*> souffle::ast::analysis::RelationDetailCacheAnalysis::getClauses (const Relation * rel) const inline
Definition at line 56 of file RelationDetailCache.h.
References souffle::ast::Relation::getQualifiedName().
{
         assert(rel != nullptr && "invalid relation");
         return getClauses(rel->getQualifiedName());
     }
getClauses() [2/2]
std::set<Clause*> souffle::ast::analysis::RelationDetailCacheAnalysis::getClauses (const QualifiedName & name) const inline
Definition at line 61 of file RelationDetailCache.h.
References nameToClauses.
{
         if (nameToClauses.find(name) != nameToClauses.end()) {
             return nameToClauses.at(name);
         }
         return std::set<Clause*>();
     }
getRelation()
Relation* souffle::ast::analysis::RelationDetailCacheAnalysis::getRelation (const QualifiedName & name) const inline
Definition at line 49 of file RelationDetailCache.h.
References nameToRelation.
{
         if (nameToRelation.find(name) != nameToRelation.end()) {
             return nameToRelation.at(name);
         }
         return nullptr;
     }
print()
void souffle::ast::analysis::RelationDetailCacheAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 48 of file RelationDetailCache.cpp.
References nameToClauses.
Referenced by RelationDetailCacheAnalysis().
{
     for (const auto& pair : nameToClauses) {
         os << "--" << pair.first << "--";
         os << std::endl;
         for (const auto* clause : pair.second) {
             os << *clause << std::endl;
         }
         os << std::endl;
     }
 }
run()
void souffle::ast::analysis::RelationDetailCacheAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 33 of file RelationDetailCache.cpp.
References souffle::ast::TranslationUnit::getProgram(), nameToClauses, and nameToRelation.
Referenced by RelationDetailCacheAnalysis().
{
     const auto& program = translationUnit.getProgram();
     for (auto* rel : program.getRelations()) {
         nameToRelation[rel->getQualifiedName()] = rel;
         nameToClauses[rel->getQualifiedName()] = std::set<Clause*>();
     }
     for (auto* clause : program.getClauses()) {
         const auto& relationName = clause->getHead()->getQualifiedName();
         if (nameToClauses.find(relationName) == nameToClauses.end()) {
             nameToClauses[relationName] = std::set<Clause*>();
         }
         nameToClauses.at(relationName).insert(clause);
     }
 }
Field Documentation
name
constexpr const char* souffle::ast::analysis::RelationDetailCacheAnalysis::name = "relation-detail" static
Definition at line 41 of file RelationDetailCache.h.
nameToClauses
std::map<QualifiedName, std::set<Clause*> > souffle::ast::analysis::RelationDetailCacheAnalysis::nameToClauses private
Definition at line 70 of file RelationDetailCache.h.
Referenced by getClauses(), print(), and run().
nameToRelation
std::map<QualifiedName, Relation*> souffle::ast::analysis::RelationDetailCacheAnalysis::nameToRelation private
Definition at line 69 of file RelationDetailCache.h.
Referenced by getRelation(), and run().
The documentation for this class was generated from the following files:
ast/analysis/RelationDetailCache.h
ast/analysis/RelationDetailCache.cpp