souffle: souffle::ast::transform::ReorderLiteralsTransformer Class Reference
souffle::ast::transform::ReorderLiteralsTransformer Class Reference
Transformation pass to reorder body literals.
#include <ReorderLiterals.h>
Public Member Functions
ReorderLiteralsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Static Public Member Functions
static std::unique_ptr< SipsMetric > getSipsFunction (const std::string &sipsChosen, const TranslationUnit &tu)
Returns a SIPS cost evaluator based on the SIPS option provided.
static Clause * reorderClauseWithSips (const SipsMetric &sips, const Clause *clause)
Reorder the clause based on a given SIPS function.
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to reorder body literals.
Definition at line 34 of file ReorderLiterals.h.
Member Function Documentation
clone()
ReorderLiteralsTransformer* souffle::ast::transform::ReorderLiteralsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 40 of file ReorderLiterals.h.
References getSipsFunction(), reorderClauseWithSips(), and transform().
{
         return new ReorderLiteralsTransformer();
     }
getName()
std::string souffle::ast::transform::ReorderLiteralsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file ReorderLiterals.h.
{
         return "ReorderLiteralsTransformer";
     }
getSipsFunction()
std::unique_ptr< SipsMetric > souffle::ast::transform::ReorderLiteralsTransformer::getSipsFunction (const std::string & sipsChosen, const TranslationUnit & tu) static
Returns a SIPS cost evaluator based on the SIPS option provided.
Definition at line 39 of file ReorderLiterals.cpp.
References souffle::ast::TranslationUnit::getAnalysis().
Referenced by clone(), and transform().
{
     if (sipsChosen == "strict")
         return std::make_unique<StrictSips>();
     else if (sipsChosen == "all-bound")
         return std::make_unique<AllBoundSips>();
     else if (sipsChosen == "naive")
         return std::make_unique<NaiveSips>();
     else if (sipsChosen == "max-bound")
         return std::make_unique<MaxBoundSips>();
     else if (sipsChosen == "max-ratio")
         return std::make_unique<MaxRatioSips>();
     else if (sipsChosen == "least-free")
         return std::make_unique<LeastFreeSips>();
     else if (sipsChosen == "least-free-vars")
         return std::make_unique<LeastFreeVarsSips>();
     else if (sipsChosen == "profile-use")
         return std::make_unique<ProfileUseSips>(*tu.getAnalysis<analysis::ProfileUseAnalysis>());
     // default is all-bound
     return getSipsFunction("all-bound", tu);
 }
reorderClauseWithSips()
Clause * souffle::ast::transform::ReorderLiteralsTransformer::reorderClauseWithSips (const SipsMetric & sips, const Clause * clause) static
Reorder the clause based on a given SIPS function.
Parameters
sipsFunction SIPS metric to use
clause clause to reorder
Returns
nullptr if no change, otherwise a new reordered clause
Definition at line 62 of file ReorderLiterals.cpp.
References souffle::ast::Clause::getExecutionPlan(), souffle::ast::SipsMetric::getReordering(), i, and souffle::ast::reorderAtoms().
Referenced by clone(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), and transform().
{
     // ignore clauses with fixed execution plans
     if (clause->getExecutionPlan() != nullptr) {
         return nullptr;
     }
     // get the ordering corresponding to the SIPS
     std::vector<unsigned int> newOrdering = sips.getReordering(clause);
     // check if we need a change
     bool changeNeeded = false;
     for (unsigned int i = 0; i < newOrdering.size(); i++) {
         if (newOrdering[i] != i) {
             changeNeeded = true;
         }
     }
     // reorder if needed
     return changeNeeded ? reorderAtoms(clause, newOrdering) : nullptr;
 }
transform()
bool souffle::ast::transform::ReorderLiteralsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 83 of file ReorderLiterals.cpp.
References souffle::ast::Program::addClause(), souffle::Global::config(), souffle::ast::Program::getClauses(), souffle::ast::TranslationUnit::getProgram(), getSipsFunction(), souffle::ast::Program::removeClause(), and reorderClauseWithSips().
Referenced by clone().
{
     bool changed = false;
     Program& program = translationUnit.getProgram();
     // --- SIPS-based static reordering ---
     // ordering is based on the given SIPS
     // default SIPS to choose is 'all-bound'
     std::string sipsChosen = "all-bound";
     if (Global::config().has("SIPS")) {
         sipsChosen = Global::config().get("SIPS");
     }
     auto sipsFunction = getSipsFunction(sipsChosen, translationUnit);
     // literal reordering is a rule-local transformation
     std::vector<Clause*> clausesToRemove;
     for (Clause* clause : program.getClauses()) {
         Clause* newClause = reorderClauseWithSips(*sipsFunction, clause);
         if (newClause != nullptr) {
             // reordering needed - swap around
             clausesToRemove.push_back(clause);
             program.addClause(Own<Clause>(newClause));
         }
     }
     changed |= !clausesToRemove.empty();
     for (auto* clause : clausesToRemove) {
         program.removeClause(clause);
     }
     // --- profile-guided reordering ---
     if (Global::config().has("profile-use")) {
         // parse supplied profile information
         auto profilerSips = getSipsFunction("profiler", translationUnit);
         // change the ordering of literals within clauses
         std::vector<Clause*> clausesToRemove;
         for (Clause* clause : program.getClauses()) {
             Clause* newClause = reorderClauseWithSips(*profilerSips, clause);
             if (newClause != nullptr) {
                 // reordering needed - swap around
                 clausesToRemove.push_back(clause);
                 program.addClause(Own<Clause>(newClause));
             }
         }
         changed |= !clausesToRemove.empty();
         for (auto* clause : clausesToRemove) {
             program.removeClause(clause);
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ReorderLiterals.h
ast/transform/ReorderLiterals.cpp