souffle: souffle::ram::UserDefinedOperator Class Reference
souffle::ram::UserDefinedOperator Class Reference
Operator that represents an extrinsic (user-defined) functor.
#include <UserDefinedOperator.h>
Public Member Functions
UserDefinedOperator * clone () const override
Create a clone (i.e.
const std::vector< TypeAttribute > & getArgsTypes () const
Get types of arguments.
const std::string & getName () const
Get operator name.
TypeAttribute getReturnType () const
Get return type.
bool isStateful () const
Is functor stateful?
UserDefinedOperator (std::string n, std::vector< TypeAttribute > argsTypes, TypeAttribute returnType, bool stateful, VecOwn< Expression > args)
Public Member Functions inherited from souffle::ram::AbstractOperator
AbstractOperator (VecOwn< Expression > args)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Expression * > getArguments () const
Get argument values.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const std::vector< TypeAttribute > argsTypes
Argument types.
const std::string name
Name of user-defined operator.
const TypeAttribute returnType
Return type.
const bool stateful
Stateful.
Protected Attributes inherited from souffle::ram::AbstractOperator
VecOwn< Expression > arguments
Arguments of user defined operator.
Detailed Description
Operator that represents an extrinsic (user-defined) functor.
Definition at line 37 of file UserDefinedOperator.h.
Constructor & Destructor Documentation
UserDefinedOperator()
souffle::ram::UserDefinedOperator::UserDefinedOperator (std::string n, std::vector< TypeAttribute > argsTypes, TypeAttribute returnType, bool stateful, VecOwn< Expression > args) inline
Definition at line 39 of file UserDefinedOperator.h.
Referenced by clone().
             : AbstractOperator(std::move(args)), name(std::move(n)), argsTypes(std::move(argsTypes)),
               returnType(returnType), stateful(stateful) {
         assert(argsTypes.size() == args.size());
     }
Member Function Documentation
clone()
UserDefinedOperator* souffle::ram::UserDefinedOperator::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Expression.
Definition at line 66 of file UserDefinedOperator.h.
References argsTypes, souffle::ram::AbstractOperator::arguments, souffle::ram::Expression::clone(), name, returnType, stateful, and UserDefinedOperator().
Referenced by souffle::ram::test::TEST().
{
         auto* res = new UserDefinedOperator(name, argsTypes, returnType, stateful, {});
         for (auto& cur : arguments) {
             Expression* arg = cur->clone();
             res->arguments.emplace_back(arg);
         }
         return res;
     }
equal()
bool souffle::ram::UserDefinedOperator::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::AbstractOperator.
Definition at line 86 of file UserDefinedOperator.h.
References argsTypes, souffle::ram::AbstractOperator::equal(), name, returnType, and stateful.
{
         const auto& other = static_cast<const UserDefinedOperator&>(node);
         return AbstractOperator::equal(node) && name == other.name && argsTypes == other.argsTypes &&
                returnType == other.returnType && stateful == other.stateful;
     }
getArgsTypes()
const std::vector<TypeAttribute>& souffle::ram::UserDefinedOperator::getArgsTypes () const inline
Get types of arguments.
Definition at line 52 of file UserDefinedOperator.h.
References argsTypes.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::synthesiser::Synthesiser::generateCode().
{
         return argsTypes;
     }
getName()
const std::string& souffle::ram::UserDefinedOperator::getName () const inline
Get operator name.
Definition at line 47 of file UserDefinedOperator.h.
References name.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::synthesiser::Synthesiser::generateCode().
{
         return name;
     }
getReturnType()
TypeAttribute souffle::ram::UserDefinedOperator::getReturnType () const inline
Get return type.
Definition at line 57 of file UserDefinedOperator.h.
References returnType.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::synthesiser::Synthesiser::generateCode().
{
         return returnType;
     }
isStateful()
bool souffle::ram::UserDefinedOperator::isStateful () const inline
Is functor stateful?
Definition at line 62 of file UserDefinedOperator.h.
References stateful.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::synthesiser::Synthesiser::generateCode().
{
         return stateful;
     }
print()
void souffle::ram::UserDefinedOperator::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 76 of file UserDefinedOperator.h.
References argsTypes, souffle::ram::AbstractOperator::arguments, souffle::join(), name, returnType, and stateful.
{
         os << "@" << name << "_" << argsTypes;
         os << "_" << returnType;
         if (stateful) {
             os << "_stateful";
         }
         os << "(" << join(arguments, ",", [](std::ostream& out, const Own<Expression>& arg) { out << *arg; })
            << ")";
     }
Field Documentation
argsTypes
const std::vector<TypeAttribute> souffle::ram::UserDefinedOperator::argsTypes protected
Argument types.
Definition at line 96 of file UserDefinedOperator.h.
Referenced by clone(), equal(), getArgsTypes(), and print().
name
const std::string souffle::ram::UserDefinedOperator::name protected
Name of user-defined operator.
Definition at line 93 of file UserDefinedOperator.h.
Referenced by clone(), equal(), getName(), and print().
returnType
const TypeAttribute souffle::ram::UserDefinedOperator::returnType protected
Return type.
Definition at line 99 of file UserDefinedOperator.h.
Referenced by clone(), equal(), getReturnType(), and print().
stateful
const bool souffle::ram::UserDefinedOperator::stateful protected
Stateful.
Definition at line 102 of file UserDefinedOperator.h.
Referenced by clone(), equal(), isStateful(), and print().
The documentation for this class was generated from the following file:
ram/UserDefinedOperator.h