souffle: souffle::ast::transform::TypeChecker Class Reference
souffle::ast::transform::TypeChecker Class Reference
Public Member Functions
void run ()
Analyse types, clause by clause.
TypeChecker (TranslationUnit &tu)
Private Member Functions
void visitAggregator (const Aggregator &aggregator) override
void visitAtom (const Atom &atom) override
void visitBinaryConstraint (const BinaryConstraint &constraint) override
void visitBranchInit (const BranchInit &adt) override
void visitIntrinsicFunctor (const IntrinsicFunctor &fun) override
void visitNilConstant (const NilConstant &constant) override
void visitNumericConstant (const NumericConstant &constant) override
void visitRecordInit (const RecordInit &rec) override
void visitStringConstant (const StringConstant &constant) override
void visitTypeCast (const ast::TypeCast &cast) override
void visitUserDefinedFunctor (const UserDefinedFunctor &fun) override
void visitVariable (const ast::Variable &var) override
Private Member Functions inherited from souffle::ast::Visitor< void >
void operator() (const Node &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const Node &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of Nodes.
virtual ~Visitor ()=default
A virtual destructor.
LINK (SubsetType, Type)
LINK (RecordType, Type)
LINK (AlgebraicDataType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (ComponentType, Node)
LINK (ComponentInit, Node)
LINK (Component, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const Node &, Params...)
The base case for all visitors – if no more specific overload was defined.
Private Attributes
const Program & program = tu.getProgram()
ErrorReport & report = tu.getErrorReport()
TranslationUnit & tu
const TypeAnalysis & typeAnalysis = *tu.getAnalysis<TypeAnalysis>()
const TypeEnvironment & typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment()
Detailed Description
Definition at line 147 of file SemanticChecker.cpp.
Constructor & Destructor Documentation
TypeChecker()
souffle::ast::transform::TypeChecker::TypeChecker (TranslationUnit & tu) inline
Definition at line 149 of file SemanticChecker.cpp.
 : tu(tu){};
Member Function Documentation
run()
void souffle::ast::transform::TypeChecker::run () inline
Analyse types, clause by clause.
Definition at line 152 of file SemanticChecker.cpp.
References souffle::ast::Program::getClauses(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::visitDepthFirstPreOrder().
                {
         const Program& program = tu.getProgram();
         for (auto* clause : program.getClauses()) {
             visitDepthFirstPreOrder(*clause, *this);
         }
     }
visitAggregator()
void souffle::ast::transform::TypeChecker::visitAggregator (const Aggregator & aggregator) override private
Definition at line 1550 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Aggregator::getOperator(), souffle::ast::Node::getSrcLoc(), souffle::getTypeAttributeAggregate(), souffle::ast::analysis::TypeAnalysis::getTypes(), and souffle::ast::analysis::isOfKind().
{
     auto op = aggregator.getOperator();
     auto aggregatorType = typeAnalysis.getTypes(&aggregator);
     TypeAttribute opType = getTypeAttributeAggregate(op);
     // Check if operation type and return type agree.
     if (!isOfKind(aggregatorType, opType)) {
         report.addError("Couldn't assign types to the aggregator", aggregator.getSrcLoc());
     }
 }
visitAtom()
void souffle::ast::transform::TypeChecker::visitAtom (const Atom & atom) override private
Definition at line 1278 of file SemanticChecker.cpp.
References souffle::ErrorReport::addDiagnostic(), souffle::all_of(), souffle::Global::config(), souffle::Diagnostic::ERROR, tinyformat::format(), souffle::ast::Atom::getArguments(), souffle::ast::getAtomRelation(), souffle::ast::analysis::TypeEnvironment::getType(), souffle::ast::analysis::TypeAnalysis::getTypes(), i, souffle::ast::analysis::isSubtypeOf(), souffle::ast::analysis::TypeEnvironment::isType(), and relation.
{
     auto relation = getAtomRelation(&atom, &program);
     if (relation == nullptr) {
         return;  // error unrelated to types.
     }
     auto attributes = relation->getAttributes();
     auto arguments = atom.getArguments();
     if (attributes.size() != arguments.size()) {
         return;  // error in input program
     }
     for (size_t i = 0; i < attributes.size(); ++i) {
         auto& typeName = attributes[i]->getTypeName();
         if (typeEnv.isType(typeName)) {
             auto argTypes = typeAnalysis.getTypes(arguments[i]);
             auto& attributeType = typeEnv.getType(typeName);
             if (argTypes.isAll() || argTypes.empty()) {
                 continue;  // This will be reported later.
             }
             // Attribute and argument type agree if, argument type is a subtype of declared type
             // or is of the appropriate constant type or the (constant) record type.
             bool validAttribute = all_of(argTypes, [&attributeType](const analysis::Type& type) {
                 if (isSubtypeOf(type, attributeType)) return true;
                 if (!isSubtypeOf(attributeType, type)) return false;
                 if (isA<ConstantType>(type)) return true;
                 return isA<analysis::RecordType>(type) && !isA<analysis::SubsetType>(type);
             });
             if (!validAttribute && !Global::config().has("legacy")) {
                 auto primaryDiagnostic =
                         DiagnosticMessage("Atom's argument type is not a subtype of its declared type",
                                 arguments[i]->getSrcLoc());
                 auto declaredTypeInfo =
                         DiagnosticMessage(tfm::format("The argument's declared type is %s", typeName),
                                 attributes[i]->getSrcLoc());
                 report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR, std::move(primaryDiagnostic),
                         {std::move(declaredTypeInfo)}));
             }
         }
     }
 }
visitBinaryConstraint()
void souffle::ast::transform::TypeChecker::visitBinaryConstraint (const BinaryConstraint & constraint) override private
Definition at line 1501 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ADT, souffle::any_of(), souffle::ast::analysis::areEquivalentTypes(), souffle::ast::analysis::TypeSet::begin(), souffle::Float, souffle::getBinaryConstraintTypes(), souffle::ast::BinaryConstraint::getLHS(), souffle::ast::BinaryConstraint::getOperator(), souffle::ast::BinaryConstraint::getRHS(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::analysis::isOfKind(), souffle::isOrderedBinaryConstraintOp(), souffle::join(), souffle::Record, souffle::Signed, souffle::profile::ss, souffle::Symbol, and souffle::Unsigned.
{
     auto op = constraint.getOperator();
     auto left = constraint.getLHS();
     auto right = constraint.getRHS();
     auto opTypesAttrs = getBinaryConstraintTypes(op);
     auto leftTypes = typeAnalysis.getTypes(left);
     auto rightTypes = typeAnalysis.getTypes(right);
     // Skip checks if either side is `Bottom` b/c it just adds noise.
     // The unable-to-deduce-type checker will point out the issue.
     if (leftTypes.empty() || rightTypes.empty() || leftTypes.isAll() || rightTypes.isAll()) return;
     assert((leftTypes.size() == 1) && (rightTypes.size() == 1));
     // Extract types from singleton sets.
     auto& leftType = *typeAnalysis.getTypes(left).begin();
     auto& rightType = *typeAnalysis.getTypes(right).begin();
     // give them a slightly nicer error
     if (isOrderedBinaryConstraintOp(op) && !areEquivalentTypes(leftType, rightType)) {
         report.addError("Cannot compare different types", constraint.getSrcLoc());
     } else {
         auto checkTyAttr = [&](Argument const& side) {
             auto opMatchesType = any_of(opTypesAttrs,
                     [&](auto& typeAttr) { return isOfKind(typeAnalysis.getTypes(&side), typeAttr); });
             if (!opMatchesType) {
                 std::stringstream ss;
                 ss << "Constraint requires an operand of type "
                    << join(opTypesAttrs, " or ", [&](auto& out, auto& typeAttr) {
                           switch (typeAttr) {
                               case TypeAttribute::Signed: out << "`number`"; break;
                               case TypeAttribute::Symbol: out << "`symbol`"; break;
                               case TypeAttribute::Unsigned: out << "`unsigned`"; break;
                               case TypeAttribute::Float: out << "`float`"; break;
                               case TypeAttribute::Record: out << "a record"; break;
                               case TypeAttribute::ADT: out << "a sum"; break;
                           }
                       });
                 report.addError(ss.str(), side.getSrcLoc());
             }
         };
         checkTyAttr(*left);
         checkTyAttr(*right);
     }
 }
visitBranchInit()
void souffle::ast::transform::TypeChecker::visitBranchInit (const BranchInit & adt) override private
Definition at line 1390 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ADT, souffle::all_of(), souffle::ast::analysis::TypeSet::begin(), souffle::ast::Term::getArguments(), souffle::ast::BranchInit::getConstructor(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), i, souffle::ast::analysis::TypeSet::isAll(), souffle::ast::analysis::isOfKind(), souffle::ast::analysis::isSubtypeOf(), souffle::ast::analysis::TypeSet::size(), and types.
{
     TypeSet types = typeAnalysis.getTypes(&adt);
     if (!isOfKind(types, TypeAttribute::ADT) || types.isAll() || types.size() != 1) {
         report.addError("Ambiguous branch", adt.getSrcLoc());
         return;
     }
     // We know now that the set "types" is a singleton
     auto& sumType = *as<analysis::AlgebraicDataType>(*types.begin());
     auto& argsDeclaredTypes = sumType.getBranchTypes(adt.getConstructor());
     auto args = adt.getArguments();
     if (argsDeclaredTypes.size() != args.size()) {
         // Invalid branchInit arity, handled by checkBranchInits.
         return;
     }
     for (size_t i = 0; i < args.size(); ++i) {
         auto argTypes = typeAnalysis.getTypes(args[i]);
         bool correctType = all_of(
                 argTypes, [&](const analysis::Type& t) { return isSubtypeOf(t, *argsDeclaredTypes[i]); });
         if (!correctType) {
             // TODO (darth_tytus): Give better error
             report.addError("Branch argument's type doesn't match its declared type", args[i]->getSrcLoc());
         }
     }
 }
visitIntrinsicFunctor()
void souffle::ast::transform::TypeChecker::visitIntrinsicFunctor (const IntrinsicFunctor & fun) override private
Definition at line 1441 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Term::getArguments(), souffle::ast::IntrinsicFunctor::getFunction(), souffle::ast::IntrinsicFunctor::getFunctionInfo(), souffle::ast::Node::getSrcLoc(), souffle::isValidFunctorOpArity(), and souffle::ast::validOverloads().
{
     if (!fun.getFunctionInfo()) {  // no info => no overload found during inference
         auto args = fun.getArguments();
         if (!isValidFunctorOpArity(fun.getFunction(), args.size())) {
             report.addError("invalid overload (arity mismatch)", fun.getSrcLoc());
             return;
         }
         assert(validOverloads(typeAnalysis, fun).empty() && "polymorphic transformation wasn't applied?");
         report.addError("no valid overloads", fun.getSrcLoc());
     }
 }
visitNilConstant()
void souffle::ast::transform::TypeChecker::visitNilConstant (const NilConstant & constant) override private
Definition at line 1365 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::analysis::isOfKind(), souffle::Record, and types.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     if (!isOfKind(types, TypeAttribute::Record)) {
         report.addError("Nil constant used as a non-record", constant.getSrcLoc());
         return;
     }
 }
visitNumericConstant()
void souffle::ast::transform::TypeChecker::visitNumericConstant (const NumericConstant & constant) override private
Definition at line 1337 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::Float, souffle::ast::NumericConstant::Float, souffle::ast::Node::getSrcLoc(), souffle::ast::NumericConstant::getType(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::NumericConstant::Int, souffle::ast::analysis::isOfKind(), souffle::Signed, types, souffle::ast::NumericConstant::Uint, and souffle::Unsigned.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     // No type could be assigned.
     if (!constant.getType().has_value()) {
         report.addError("Ambiguous constant (unable to deduce type)", constant.getSrcLoc());
         return;
     }
     switch (*constant.getType()) {
         case NumericConstant::Type::Int:
             if (!isOfKind(types, TypeAttribute::Signed)) {
                 report.addError("Number constant (type mismatch)", constant.getSrcLoc());
             }
             break;
         case NumericConstant::Type::Uint:
             if (!isOfKind(types, TypeAttribute::Unsigned)) {
                 report.addError("Unsigned constant (type mismatch)", constant.getSrcLoc());
             }
             break;
         case NumericConstant::Type::Float:
             if (!isOfKind(types, TypeAttribute::Float)) {
                 report.addError("Float constant (type mismatch)", constant.getSrcLoc());
             }
             break;
     }
 }
visitRecordInit()
void souffle::ast::transform::TypeChecker::visitRecordInit (const RecordInit & rec) override private
Definition at line 1373 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::analysis::TypeSet::begin(), souffle::ast::Term::getArguments(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::analysis::isOfKind(), souffle::Record, souffle::ast::analysis::TypeSet::size(), and types.
{
     TypeSet types = typeAnalysis.getTypes(&rec);
     if (!isOfKind(types, TypeAttribute::Record) || types.size() != 1) {
         report.addError("Ambiguous record", rec.getSrcLoc());
         return;
     }
     // At this point we know that there is exactly one type in set, so we can take it.
     auto& recordType = *as<analysis::RecordType>(*types.begin());
     if (recordType.getFields().size() != rec.getArguments().size()) {
         report.addError("Wrong number of arguments given to record", rec.getSrcLoc());
         return;
     }
 }
visitStringConstant()
void souffle::ast::transform::TypeChecker::visitStringConstant (const StringConstant & constant) override private
Definition at line 1330 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::analysis::isOfKind(), souffle::Symbol, and types.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     if (!isOfKind(types, TypeAttribute::Symbol)) {
         report.addError("Symbol constant (type mismatch)", constant.getSrcLoc());
     }
 }
visitTypeCast()
void souffle::ast::transform::TypeChecker::visitTypeCast (const ast::TypeCast & cast) override private
Definition at line 1420 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::ast::Node::getSrcLoc(), souffle::ast::TypeCast::getType(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::TypeCast::getValue(), and souffle::ast::analysis::TypeEnvironment::isType().
{
     if (!typeEnv.isType(cast.getType())) {
         report.addError(
                 tfm::format("Type cast to the undeclared type \"%s\"", cast.getType()), cast.getSrcLoc());
         return;
     }
     auto& castTypes = typeAnalysis.getTypes(&cast);
     auto& argTypes = typeAnalysis.getTypes(cast.getValue());
     if (castTypes.isAll() || castTypes.size() != 1) {
         report.addError("Unable to deduce type of the argument (cast)", cast.getSrcLoc());
         return;
     }
     // This should be reported elsewhere
     if (argTypes.isAll() || castTypes.size() != 1 || argTypes.isAll() || argTypes.size() != 1) {
         return;
     }
 }
visitUserDefinedFunctor()
void souffle::ast::transform::TypeChecker::visitUserDefinedFunctor (const UserDefinedFunctor & fun) override private
Definition at line 1454 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ADT, souffle::fatal(), souffle::Float, souffle::ast::UserDefinedFunctor::getArgType(), souffle::ast::Term::getArguments(), souffle::ast::UserDefinedFunctor::getReturnType(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), i, souffle::ast::analysis::isOfKind(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
{
     // check type of result
     const TypeSet& resultType = typeAnalysis.getTypes(&fun);
     if (!isOfKind(resultType, fun.getReturnType())) {
         switch (fun.getReturnType()) {
             case TypeAttribute::Signed:
                 report.addError("Non-numeric use for numeric functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Unsigned:
                 report.addError("Non-unsigned use for unsigned functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Float:
                 report.addError("Non-float use for float functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Symbol:
                 report.addError("Non-symbolic use for symbolic functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Record: fatal("Invalid return type");
             case TypeAttribute::ADT: fatal("Invalid return type");
         }
     }
     size_t i = 0;
     for (auto arg : fun.getArguments()) {
         if (!isOfKind(typeAnalysis.getTypes(arg), fun.getArgType(i))) {
             switch (fun.getArgType(i)) {
                 case TypeAttribute::Signed:
                     report.addError("Non-numeric argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Symbol:
                     report.addError("Non-symbolic argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Unsigned:
                     report.addError("Non-unsigned argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Float:
                     report.addError("Non-float argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Record: fatal("Invalid argument type");
                 case TypeAttribute::ADT: fatal("Invalid argument type");
             }
         }
         ++i;
     }
 }
visitVariable()
void souffle::ast::transform::TypeChecker::visitVariable (const ast::Variable & var) override private
Definition at line 1324 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::analysis::TypeSet::empty(), and souffle::ast::analysis::TypeAnalysis::getTypes().
{
     if (typeAnalysis.getTypes(&var).empty()) {
         report.addError("Unable to deduce type for variable " + var.getName(), var.getSrcLoc());
     }
 }
Field Documentation
program
const Program& souffle::ast::transform::TypeChecker::program = tu.getProgram() private
Definition at line 164 of file SemanticChecker.cpp.
report
ErrorReport& souffle::ast::transform::TypeChecker::report = tu.getErrorReport() private
Definition at line 161 of file SemanticChecker.cpp.
tu
TranslationUnit& souffle::ast::transform::TypeChecker::tu private
Definition at line 160 of file SemanticChecker.cpp.
typeAnalysis
const TypeAnalysis& souffle::ast::transform::TypeChecker::typeAnalysis = *tu.getAnalysis<TypeAnalysis>() private
Definition at line 162 of file SemanticChecker.cpp.
typeEnv
const TypeEnvironment& souffle::ast::transform::TypeChecker::typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment() private
Definition at line 163 of file SemanticChecker.cpp.
The documentation for this class was generated from the following file:
ast/transform/SemanticChecker.cpp