souffle: souffle::ram::Expression Class Reference
souffle::ram::Expression Class Reference abstract
Abstract class for describing scalar values in RAM.
#include <Expression.h>
Public Member Functions
Expression * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::ram::Node
virtual bool equal (const Node &) const
Equality check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
Detailed Description
Abstract class for describing scalar values in RAM.
Definition at line 27 of file Expression.h.
Member Function Documentation
clone()
Expression* souffle::ram::Expression::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Node.
Implemented in souffle::ram::UserDefinedOperator, souffle::ram::RelationSize, souffle::ram::PackRecord, souffle::ram::IntrinsicOperator, souffle::ram::TupleElement, souffle::ram::FloatConstant, souffle::ram::SignedConstant, souffle::ram::UnsignedConstant, souffle::ram::SubroutineArgument, souffle::ram::AutoIncrement, and souffle::ram::UndefValue.
Referenced by souffle::ram::UserDefinedOperator::clone(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), and souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan().
The documentation for this class was generated from the following file:
ram/Expression.h