souffle: souffle::ast::NilConstant Class Reference
souffle::ast::NilConstant Class Reference
Defines the nil constant.
#include <NilConstant.h>
Public Member Functions
NilConstant * clone () const override
Create clone.
NilConstant (SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Constant
const std::string & getConstant () const
Get string representation of Constant.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::ast::Constant
Constant (std::string value, SrcLocation loc={})
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Detailed Description
Defines the nil constant.
Definition at line 30 of file NilConstant.h.
Constructor & Destructor Documentation
NilConstant()
souffle::ast::NilConstant::NilConstant (SrcLocation loc = {}) inline
Definition at line 32 of file NilConstant.h.
References souffle::ast::Constant::Constant().
Referenced by clone().
 {}) : Constant("nil", std::move(loc)) {}
Member Function Documentation
clone()
NilConstant* souffle::ast::NilConstant::clone () const inline override virtual
Create clone.
Implements souffle::ast::Constant.
Definition at line 34 of file NilConstant.h.
References souffle::ast::Node::getSrcLoc(), and NilConstant().
{
         return new NilConstant(getSrcLoc());
     }
The documentation for this class was generated from the following file:
ast/NilConstant.h