souffle: souffle::ram::transform::TupleIdTransformer Class Reference
souffle::ram::transform::TupleIdTransformer Class Reference
Ordering tupleIds in TupleOperation operations correctly.
#include <TupleId.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool reorderOperations (Program &program)
Apply tupleId reordering to the whole program.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Ordering tupleIds in TupleOperation operations correctly.
Transformations, like MakeIndex and IfConversion do not ensure that TupleOperations maintain an appropriate order with respect to their tupleId's
For example: SEARCH ... (tupleId = 2) ... SEARCH ... (tupleId = 1) ...
Will be converted to SEARCH ... (tupleId = 0) ... SEARCH ... (tupleId = 1) ...
Definition at line 45 of file TupleId.h.
Member Function Documentation
getName()
std::string souffle::ram::transform::TupleIdTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 47 of file TupleId.h.
References reorderOperations().
{
         return "TupleIdTransformer";
     }
reorderOperations()
bool souffle::ram::transform::TupleIdTransformer::reorderOperations (Program & program)
Apply tupleId reordering to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Search for TupleOperations and TupleElements and rewrite their tupleIds
Definition at line 29 of file TupleId.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::makeLambdaRamMapper(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         // Maps old tupleIds to new tupleIds
         std::map<int, int> reorder;
         int ctr = 0;
         visitDepthFirst(query, [&](const TupleOperation& search) {
             if (ctr != search.getTupleId()) {
                 changed = true;
             }
             reorder[search.getTupleId()] = ctr;
             const_cast<TupleOperation*>(&search)->setTupleId(ctr);
             ctr++;
         });
         std::function<Own<Node>(Own<Node>)> elementRewriter = [&](Own<Node> node) -> Own<Node> {
             if (auto* element = dynamic_cast<TupleElement*>(node.get())) {
                 if (reorder[element->getTupleId()] != element->getTupleId()) {
                     changed = true;
                     node = mk<TupleElement>(reorder[element->getTupleId()], element->getElement());
                 }
             }
             node->apply(makeLambdaRamMapper(elementRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(elementRewriter));
     });
     return changed;
 }
transform()
bool souffle::ram::transform::TupleIdTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 61 of file TupleId.h.
References souffle::ram::TranslationUnit::getProgram(), and reorderOperations().
{
         return reorderOperations(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/TupleId.h
ram/transform/TupleId.cpp