souffle: souffle::ast::transform::MaterializeSingletonAggregationTransformer Class Reference
souffle::ast::transform::MaterializeSingletonAggregationTransformer Class Reference
Replaces literals containing single-valued aggregates with a synthesised relation.
#include <MaterializeSingletonAggregation.h>
Public Member Functions
MaterializeSingletonAggregationTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static std::string findUniqueAggregateRelationName (const Program &program)
findUniqueAggregateRelationName returns a synthesised aggregate relation name that hasn't appeared in the given clause.
static std::string findUniqueVariableName (const Clause &clause)
findUniqueVariableName returns a variable name that hasn't appeared in the given clause.
static bool isSingleValued (const Aggregator &agg, const Clause &clause)
Determines whether an aggregate is single-valued, ie the aggregate does not depend on the outer scope.
Detailed Description
Replaces literals containing single-valued aggregates with a synthesised relation.
Definition at line 33 of file MaterializeSingletonAggregation.h.
Member Function Documentation
clone()
MaterializeSingletonAggregationTransformer* souffle::ast::transform::MaterializeSingletonAggregationTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 39 of file MaterializeSingletonAggregation.h.
References findUniqueAggregateRelationName(), findUniqueVariableName(), isSingleValued(), and transform().
{
         return new MaterializeSingletonAggregationTransformer();
     }
findUniqueAggregateRelationName()
std::string souffle::ast::transform::MaterializeSingletonAggregationTransformer::findUniqueAggregateRelationName (const Program & program) static private
findUniqueAggregateRelationName returns a synthesised aggregate relation name that hasn't appeared in the given clause.
Definition at line 55 of file MaterializeSingletonAggregation.cpp.
References souffle::ast::getRelation(), and souffle::toString().
Referenced by clone(), and transform().
{
     static int counter = 0;
     auto candidate = "__agg_rel_" + toString(counter++);
     while (getRelation(program, candidate) != nullptr) {
         candidate = "__agg_rel_" + toString(counter++);
     }
     return candidate;
 }
findUniqueVariableName()
std::string souffle::ast::transform::MaterializeSingletonAggregationTransformer::findUniqueVariableName (const Clause & clause) static private
findUniqueVariableName returns a variable name that hasn't appeared in the given clause.
Definition at line 44 of file MaterializeSingletonAggregation.cpp.
References souffle::toString(), and souffle::ast::visitDepthFirst().
Referenced by clone(), and transform().
{
     static int counter = 0;
     std::set<std::string> variableNames;
     visitDepthFirst(clause, [&](const ast::Variable& variable) { variableNames.insert(variable.getName()); });
     std::string candidateVariableName = "z";  // completely arbitrary
     while (variableNames.find(candidateVariableName) != variableNames.end()) {
         candidateVariableName = "z" + toString(counter++);
     }
     return candidateVariableName;
 }
getName()
std::string souffle::ast::transform::MaterializeSingletonAggregationTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 35 of file MaterializeSingletonAggregation.h.
{
         return "MaterializeSingletonAggregationTransformer";
     }
isSingleValued()
bool souffle::ast::transform::MaterializeSingletonAggregationTransformer::isSingleValued (const Aggregator & agg, const Clause & clause) static private
Determines whether an aggregate is single-valued, ie the aggregate does not depend on the outer scope.
Definition at line 142 of file MaterializeSingletonAggregation.cpp.
References souffle::ast::visitDepthFirst().
Referenced by clone(), and transform().
{
     std::map<std::string, int> occurrences;
     visitDepthFirst(clause, [&](const ast::Variable& v) {
         if (occurrences.find(v.getName()) == occurrences.end()) {
             occurrences[v.getName()] = 0;
         }
         occurrences[v.getName()] = occurrences[v.getName()] + 1;
     });
     std::set<std::string> aggVariables;
     visitDepthFirst(agg, [&](const ast::Variable& v) {
         aggVariables.insert(v.getName());
         occurrences[v.getName()] = occurrences[v.getName()] - 1;
     });
     for (std::string variableName : aggVariables) {
         if (occurrences[variableName] != 0) {
             return false;
         }
     }
     return true;
 }
transform()
bool souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 65 of file MaterializeSingletonAggregation.cpp.
References souffle::ast::Program::addClause(), souffle::ast::Program::addRelation(), souffle::ast::Clause::addToBody(), souffle::ast::Clause::apply(), souffle::clone(), souffle::EQ, findUniqueAggregateRelationName(), findUniqueVariableName(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::TranslationUnit::getProgram(), isSingleValued(), and souffle::ast::visitDepthFirst().
Referenced by clone().
{
     Program& program = translationUnit.getProgram();
     std::set<std::pair<Aggregator*, Clause*>> pairs;
     // collect references to clause / aggregate pairs
     visitDepthFirst(program, [&](const Clause& clause) {
         visitDepthFirst(clause, [&](const Aggregator& agg) {
             // if the aggregate isn't single valued
             // (ie it relies on a grounding from the outer scope)
             // or it's the only atom in the clause, then there's no point materialising it!
             if (!isSingleValued(agg, clause) || clause.getBodyLiterals().size() == 1) {
                 return;
             }
             auto* foundAggregate = const_cast<Aggregator*>(&agg);
             auto* foundClause = const_cast<Clause*>(&clause);
             pairs.insert(std::make_pair(foundAggregate, foundClause));
         });
     });
     for (auto pair : pairs) {
         // Clone the aggregate that we're going to be deleting.
         auto aggregate = souffle::clone(pair.first);
         Clause* clause = pair.second;
         // synthesise an aggregate relation
         // __agg_rel_0()
         auto aggRel = mk<Relation>();
         auto aggHead = mk<Atom>();
         auto aggClause = mk<Clause>();
         std::string aggRelName = findUniqueAggregateRelationName(program);
         aggRel->setQualifiedName(aggRelName);
         aggHead->setQualifiedName(aggRelName);
         // create a synthesised variable to replace the aggregate term!
         std::string variableName = findUniqueVariableName(*clause);
         auto variable = mk<ast::Variable>(variableName);
         // __agg_rel_0(z) :- ...
         aggHead->addArgument(souffle::clone(variable));
         aggRel->addAttribute(mk<Attribute>(variableName, "number"));
         aggClause->setHead(souffle::clone(aggHead));
         //    A(x) :- x = sum .., B(x).
         // -> A(x) :- x = z, B(x), __agg_rel_0(z).
         auto equalityLiteral = mk<BinaryConstraint>(
                 BinaryConstraintOp::EQ, souffle::clone(variable), souffle::clone(aggregate));
         // __agg_rel_0(z) :- z = sum ...
         aggClause->addToBody(std::move(equalityLiteral));
         program.addRelation(std::move(aggRel));
         program.addClause(std::move(aggClause));
         // the only thing left to do is just replace the aggregate terms in the original
         // clause with the synthesised variable
         struct replaceAggregate : public NodeMapper {
             const Aggregator& aggregate;
             const Own<ast::Variable> variable;
             replaceAggregate(const Aggregator& aggregate, Own<ast::Variable> variable)
                     : aggregate(aggregate), variable(std::move(variable)) {}
             Own<Node> operator()(Own<Node> node) const override {
                 assert(node != nullptr);
                 if (auto* current = dynamic_cast<Aggregator*>(node.get())) {
                     if (*current == aggregate) {
                         auto replacement = souffle::clone(variable);
                         assert(replacement != nullptr);
                         return replacement;
                     }
                 }
                 node->apply(*this);
                 assert(node != nullptr);
                 return node;
             }
         };
         replaceAggregate update(*aggregate, std::move(variable));
         clause->apply(update);
         clause->addToBody(std::move(aggHead));
     }
     return pairs.size() > 0;
 }
The documentation for this class was generated from the following files:
ast/transform/MaterializeSingletonAggregation.h
ast/transform/MaterializeSingletonAggregation.cpp