souffle: souffle::ram::ListStatement Class Reference
souffle::ram::ListStatement Class Reference
Abstract class for a list of RAM statements.
#include <ListStatement.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< Statement * > getStatements () const
Get statements.
ListStatement ()=default
ListStatement (VecOwn< Statement > statements)
template<typename... Stmts>
ListStatement (Own< Stmts > &&... stmts)
Public Member Functions inherited from souffle::ram::Statement
Statement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Attributes
VecOwn< Statement > statements
ordered list of RAM statements
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for a list of RAM statements.
Definition at line 32 of file ListStatement.h.
Constructor & Destructor Documentation
ListStatement() [1/3]
souffle::ram::ListStatement::ListStatement () default
ListStatement() [2/3]
souffle::ram::ListStatement::ListStatement (VecOwn< Statement > statements) inline
Definition at line 35 of file ListStatement.h.
 : statements(std::move(statements)) {}
ListStatement() [3/3]
template<typename... Stmts> souffle::ram::ListStatement::ListStatement (Own< Stmts > &&... stmts) inline
Definition at line 38 of file ListStatement.h.
References statements.
{
         Own<Statement> tmp[] = {std::move(stmts)...};
         for (auto& cur : tmp) {
             assert(cur.get() != nullptr && "statement is a null-pointer");
             statements.emplace_back(std::move(cur));
         }
     }
Member Function Documentation
apply()
void souffle::ram::ListStatement::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 59 of file ListStatement.h.
References souffle::map(), and statements.
{
         for (auto& stmt : statements) {
             stmt = map(std::move(stmt));
         }
     }
equal()
bool souffle::ram::ListStatement::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 66 of file ListStatement.h.
References souffle::equal_targets(), and statements.
{
         const auto& other = static_cast<const ListStatement&>(node);
         return equal_targets(statements, other.statements);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::ListStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 51 of file ListStatement.h.
References statements.
{
         std::vector<const Node*> res;
         for (const auto& cur : statements) {
             res.push_back(cur.get());
         }
         return res;
     }
getStatements()
std::vector<Statement*> souffle::ram::ListStatement::getStatements () const inline
Get statements.
Definition at line 47 of file ListStatement.h.
References statements, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::visitParallel(), and souffle::NodeGenerator::visitSequence().
{
         return toPtrVector(statements);
     }
Field Documentation
statements
VecOwn<Statement> souffle::ram::ListStatement::statements protected
ordered list of RAM statements
Definition at line 73 of file ListStatement.h.
Referenced by apply(), souffle::ram::Sequence::clone(), souffle::ram::Parallel::clone(), equal(), getChildNodes(), getStatements(), ListStatement(), souffle::ram::Sequence::print(), and souffle::ram::Parallel::print().
The documentation for this class was generated from the following file:
ram/ListStatement.h