souffle: souffle::ast::RecordInit Class Reference
souffle::ast::RecordInit Class Reference
Defines a record initialization class.
#include <RecordInit.h>
Public Member Functions
RecordInit * clone () const override
Create clone.
RecordInit (VecOwn< Argument > operands={}, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Term
void addArgument (Own< Argument > arg)
Add argument to argument list.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Argument * > getArguments () const
Get arguments.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::ast::Term
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
template<typename... Operands>
Term (Operands &&... operands)
template<typename... Operands>
Term (SrcLocation loc, Operands &&... operands)
Term (VecOwn< Argument > operands, SrcLocation loc={})
Additional Inherited Members
Protected Attributes inherited from souffle::ast::Term
VecOwn< Argument > args
Arguments.
Detailed Description
Defines a record initialization class.
Definition at line 36 of file RecordInit.h.
Constructor & Destructor Documentation
RecordInit()
souffle::ast::RecordInit::RecordInit (VecOwn< Argument > operands = {}, SrcLocation loc = {}) inline
Definition at line 38 of file RecordInit.h.
References souffle::ast::Term::Term().
Referenced by clone().
                                            {}, SrcLocation loc = {})
             : Term(std::move(operands), std::move(loc)) {}
Member Function Documentation
clone()
RecordInit* souffle::ast::RecordInit::clone () const inline override virtual
Create clone.
Implements souffle::ast::Argument.
Definition at line 41 of file RecordInit.h.
References souffle::ast::Term::args, souffle::clone(), souffle::ast::Node::getSrcLoc(), and RecordInit().
{
         return new RecordInit(souffle::clone(args), getSrcLoc());
     }
print()
void souffle::ast::RecordInit::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 46 of file RecordInit.h.
References souffle::ast::Term::args, and souffle::join().
{
         os << "[" << join(args) << "]";
     }
The documentation for this class was generated from the following file:
ast/RecordInit.h