souffle: souffle::ast::analysis::SubsetType Class Reference
souffle::ast::analysis::SubsetType Class Reference
A type being a subset of another type.
#include <TypeSystem.h>
Public Member Functions
const Type & getBaseType () const
void print (std::ostream &out) const override
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
SubsetType (const TypeEnvironment &environment, const QualifiedName &name, const Type &base)
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Private Attributes
const Type & baseType
Friends
class TypeEnvironment
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Detailed Description
A type being a subset of another type.
Definition at line 102 of file TypeSystem.h.
Constructor & Destructor Documentation
SubsetType()
souffle::ast::analysis::SubsetType::SubsetType (const TypeEnvironment & environment, const QualifiedName & name, const Type & base) inline protected
Definition at line 111 of file TypeSystem.h.
Referenced by souffle::ast::SubsetType::clone().
             : Type(environment, name), baseType(base){};
Member Function Documentation
getBaseType()
const Type& souffle::ast::analysis::SubsetType::getBaseType () const inline
Definition at line 106 of file TypeSystem.h.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkSubsetType(), souffle::ast::SubsetType::clone(), souffle::ast::analysis::isOfRootType(), and souffle::ast::SubsetType::print().
{
         return baseType;
     }
print()
void souffle::ast::analysis::SubsetType::print (std::ostream & out) const override virtual
Reimplemented from souffle::ast::analysis::Type.
Reimplemented in souffle::ast::analysis::SubsetRecordType, and souffle::ast::analysis::PrimitiveType.
Definition at line 28 of file TypeSystem.cpp.
References baseType, tinyformat::format(), and souffle::ast::analysis::Type::getName().
Referenced by souffle::ast::analysis::SubsetRecordType::print().
{
     out << tfm::format("%s <: %s", getName(), baseType.getName());
 }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 112 of file TypeSystem.h.
Field Documentation
baseType
const Type& souffle::ast::analysis::SubsetType::baseType private
Definition at line 117 of file TypeSystem.h.
Referenced by souffle::ast::SubsetType::equal(), souffle::ast::SubsetType::getBaseType(), print(), and souffle::ast::SubsetType::SubsetType().
The documentation for this class was generated from the following files:
ast/analysis/TypeSystem.h
ast/analysis/TypeSystem.cpp