souffle: souffle::ram::AbstractOperator Class Reference
souffle::ram::AbstractOperator Class Reference
Abstract class for an operator/functor.
#include <AbstractOperator.h>
Public Member Functions
AbstractOperator (VecOwn< Expression > args)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Expression * > getArguments () const
Get argument values.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::Expression
Expression * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Node
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
Protected Attributes
VecOwn< Expression > arguments
Arguments of user defined operator.
Detailed Description
Abstract class for an operator/functor.
Definition at line 34 of file AbstractOperator.h.
Constructor & Destructor Documentation
AbstractOperator()
souffle::ram::AbstractOperator::AbstractOperator (VecOwn< Expression > args) inline explicit
Definition at line 36 of file AbstractOperator.h.
References arguments.
                                                        : arguments(std::move(args)) {
         for (auto const& arg : arguments) {
             assert(arg != nullptr && "argument is null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::ram::AbstractOperator::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 55 of file AbstractOperator.h.
References arguments, and souffle::map().
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
equal()
bool souffle::ram::AbstractOperator::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Reimplemented in souffle::ram::UserDefinedOperator, and souffle::ram::IntrinsicOperator.
Definition at line 62 of file AbstractOperator.h.
References arguments, and souffle::equal_targets().
Referenced by souffle::ram::IntrinsicOperator::equal(), and souffle::ram::UserDefinedOperator::equal().
{
         const auto& other = static_cast<const AbstractOperator&>(node);
         return equal_targets(arguments, other.arguments);
     }
getArguments()
std::vector<Expression*> souffle::ram::AbstractOperator::getArguments () const inline
Get argument values.
Definition at line 43 of file AbstractOperator.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::NodeGenerator::visitIntrinsicOperator(), and souffle::NodeGenerator::visitUserDefinedOperator().
{
         return toPtrVector(arguments);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::AbstractOperator::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 47 of file AbstractOperator.h.
References arguments.
{
         std::vector<const Node*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
Field Documentation
arguments
VecOwn<Expression> souffle::ram::AbstractOperator::arguments protected
Arguments of user defined operator.
Definition at line 68 of file AbstractOperator.h.
Referenced by AbstractOperator(), apply(), souffle::ram::IntrinsicOperator::clone(), souffle::ram::UserDefinedOperator::clone(), equal(), getArguments(), getChildNodes(), souffle::ram::IntrinsicOperator::print(), and souffle::ram::UserDefinedOperator::print().
The documentation for this class was generated from the following file:
ram/AbstractOperator.h