souffle: souffle::ast::Aggregator Class Reference
souffle::ast::Aggregator Class Reference
Defines the aggregator class.
#include <Aggregator.h>
Public Member Functions
Aggregator (AggregateOp fun, Own< Argument > expr=nullptr, VecOwn< Literal > body={}, SrcLocation loc={})
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Aggregator * clone () const override
Create clone.
std::vector< Literal * > getBodyLiterals () const
Return body literals.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
AggregateOp getOperator () const
Return aggregate operator.
const Argument * getTargetExpression () const
Return target expression.
void setBody (VecOwn< Literal > bodyLiterals)
Set body.
void setOperator (AggregateOp op)
Set aggregate operator.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
VecOwn< Literal > body
Body literal of sub-query.
AggregateOp fun
Aggregate operator.
Own< Argument > targetExpression
Aggregate expression.
Detailed Description
Defines the aggregator class.
Example: sum y+x: {A(y),B(x)}
Aggregates over a sub-query using an aggregate operator and an expression.
Definition at line 46 of file Aggregator.h.
Constructor & Destructor Documentation
Aggregator()
souffle::ast::Aggregator::Aggregator (AggregateOp fun, Own< Argument > expr = nullptr, VecOwn< Literal > body = {}, SrcLocation loc = {}) inline
Definition at line 48 of file Aggregator.h.
References body, fun, and targetExpression.
Referenced by clone().
                                                                                      {}, SrcLocation loc = {})
             : Argument(std::move(loc)), fun(fun), targetExpression(std::move(expr)), body(std::move(body)) {}
Member Function Documentation
apply()
void souffle::ast::Aggregator::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 91 of file Aggregator.h.
References body, souffle::map(), and targetExpression.
{
         if (targetExpression) {
             targetExpression = map(std::move(targetExpression));
         }
         for (auto& cur : body) {
             cur = map(std::move(cur));
         }
     }
clone()
Aggregator* souffle::ast::Aggregator::clone () const inline override virtual
Create clone.
Implements souffle::ast::Argument.
Definition at line 87 of file Aggregator.h.
References Aggregator(), body, souffle::clone(), souffle::ast::Node::getSrcLoc(), and targetExpression.
{
         return new Aggregator(fun, souffle::clone(targetExpression), souffle::clone(body), getSrcLoc());
     }
equal()
bool souffle::ast::Aggregator::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 109 of file Aggregator.h.
References body, souffle::equal_ptr(), souffle::equal_targets(), fun, and targetExpression.
{
         const auto& other = static_cast<const Aggregator&>(node);
         return fun == other.fun && equal_ptr(targetExpression, other.targetExpression) &&
                equal_targets(body, other.body);
     }
getBodyLiterals()
std::vector<Literal*> souffle::ast::Aggregator::getBodyLiterals () const inline
Return body literals.
Definition at line 67 of file Aggregator.h.
References body, and souffle::toPtrVector().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), and souffle::ast::transform::usesInvalidWitness().
{
         return toPtrVector(body);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Aggregator::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 76 of file Aggregator.h.
References body, souffle::ast::Node::getChildNodes(), and targetExpression.
{
         auto res = Argument::getChildNodes();
         if (targetExpression) {
             res.push_back(targetExpression.get());
         }
         for (auto& cur : body) {
             res.push_back(cur.get());
         }
         return res;
     }
getOperator()
AggregateOp souffle::ast::Aggregator::getOperator () const inline
Return aggregate operator.
Definition at line 52 of file Aggregator.h.
References fun.
Referenced by souffle::ast::transform::TypeChecker::visitAggregator(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitAggregator().
{
         return fun;
     }
getTargetExpression()
const Argument* souffle::ast::Aggregator::getTargetExpression () const inline
Return target expression.
Definition at line 62 of file Aggregator.h.
References targetExpression.
Referenced by souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::UniqueAggregationVariablesTransformer::transform(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitAggregator().
{
         return targetExpression.get();
     }
print()
void souffle::ast::Aggregator::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 101 of file Aggregator.h.
References body, fun, souffle::join(), and targetExpression.
{
         os << fun;
         if (targetExpression) {
             os << " " << *targetExpression;
         }
         os << " : { " << join(body) << " }";
     }
setBody()
void souffle::ast::Aggregator::setBody (VecOwn< Literal > bodyLiterals) inline
Set body.
Definition at line 72 of file Aggregator.h.
References body.
Referenced by souffle::ast::transform::getInlinedArgument().
{
         body = std::move(bodyLiterals);
     }
setOperator()
void souffle::ast::Aggregator::setOperator (AggregateOp op) inline
Set aggregate operator.
Definition at line 57 of file Aggregator.h.
{
         fun = op;
     }
Field Documentation
body
VecOwn<Literal> souffle::ast::Aggregator::body private
Body literal of sub-query.
Definition at line 123 of file Aggregator.h.
Referenced by Aggregator(), apply(), clone(), equal(), getBodyLiterals(), getChildNodes(), print(), and setBody().
fun
AggregateOp souffle::ast::Aggregator::fun private
Aggregate operator.
Definition at line 117 of file Aggregator.h.
Referenced by Aggregator(), equal(), getOperator(), and print().
targetExpression
Own<Argument> souffle::ast::Aggregator::targetExpression private
Aggregate expression.
Definition at line 120 of file Aggregator.h.
Referenced by Aggregator(), apply(), clone(), equal(), getChildNodes(), getTargetExpression(), and print().
The documentation for this class was generated from the following file:
ast/Aggregator.h