souffle: souffle::ram::Node Class Reference
souffle::ram::Node Class Reference abstract
Node is a superclass for all RAM IR classes.
#include <Node.h>
Public Member Functions
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual Node * clone () const =0
Create a clone (i.e.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
virtual bool equal (const Node &) const
Equality check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
Friends
std::ostream & operator<< (std::ostream &out, const Node &node)
Print RAM on a stream.
Detailed Description
Node is a superclass for all RAM IR classes.
Definition at line 36 of file Node.h.
Constructor & Destructor Documentation
~Node()
virtual souffle::ram::Node::~Node () virtual default
Member Function Documentation
apply()
virtual void souffle::ram::Node::apply (const NodeMapper &) inline virtual
Apply the mapper to all child nodes.
Reimplemented in souffle::ram::Program, souffle::ram::NestedIntrinsicOperator, souffle::ram::Project, souffle::ram::IndexOperation, souffle::ram::Constraint, souffle::ram::UnpackRecord, souffle::ram::IndexAggregate, souffle::ram::AbstractExistenceCheck, souffle::ram::Conjunction, souffle::ram::NestedOperation, souffle::ram::SubroutineReturn, souffle::ram::Aggregate, souffle::ram::BinRelationStatement, souffle::ram::LogRelationTimer, souffle::ram::EmptinessCheck, souffle::ram::IndexChoice, souffle::ram::PackRecord, souffle::ram::Query, souffle::ram::Exit, souffle::ram::LogTimer, souffle::ram::Loop, souffle::ram::RelationSize, souffle::ram::Negation, souffle::ram::Choice, souffle::ram::ListStatement, souffle::ram::AbstractConditional, souffle::ram::AbstractOperator, souffle::ram::DebugInfo, souffle::ram::RelationOperation, and souffle::ram::RelationStatement.
Definition at line 65 of file Node.h.
Referenced by rewrite().
 {}
clone()
virtual Node* souffle::ram::Node::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::ram::RelationReference, souffle::ram::Program, souffle::ram::Relation, souffle::ram::IndexOperation, souffle::ram::IndexChoice, souffle::ram::NestedIntrinsicOperator, souffle::ram::Constraint, souffle::ram::Project, souffle::ram::UnpackRecord, souffle::ram::Conjunction, souffle::ram::UserDefinedOperator, souffle::ram::Choice, souffle::ram::Aggregate, souffle::ram::SubroutineReturn, souffle::ram::LogRelationTimer, souffle::ram::ParallelIndexChoice, souffle::ram::EmptinessCheck, souffle::ram::IndexAggregate, souffle::ram::Query, souffle::ram::ParallelIndexScan, souffle::ram::Exit, souffle::ram::LogTimer, souffle::ram::Loop, souffle::ram::RelationSize, souffle::ram::Negation, souffle::ram::PackRecord, souffle::ram::ParallelAggregate, souffle::ram::IndexScan, souffle::ram::NestedOperation, souffle::ram::ParallelIndexAggregate, souffle::ram::IO, souffle::ram::Parallel, souffle::ram::ParallelChoice, souffle::ram::Extend, souffle::ram::DebugInfo, souffle::ram::ParallelScan, souffle::ram::Break, souffle::ram::Filter, souffle::ram::IntrinsicOperator, souffle::ram::TupleElement, souffle::ram::Scan, souffle::ram::Call, souffle::ram::ExistenceCheck, souffle::ram::Clear, souffle::ram::RelationOperation, souffle::ram::FloatConstant, souffle::ram::LogSize, souffle::ram::SignedConstant, souffle::ram::Swap, souffle::ram::UnsignedConstant, souffle::ram::SubroutineArgument, souffle::ram::AbstractConditional, souffle::ram::Sequence, souffle::ram::ProvenanceExistenceCheck, souffle::ram::TupleOperation, souffle::ram::False, souffle::ram::True, souffle::ram::AutoIncrement, souffle::ram::Statement, souffle::ram::UndefValue, souffle::ram::Condition, souffle::ram::Operation, and souffle::ram::Expression.
Referenced by operator!=().
equal()
virtual bool souffle::ram::Node::equal (const Node &) const inline protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented in souffle::ram::RelationReference, souffle::ram::Program, souffle::ram::IndexOperation, souffle::ram::Relation, souffle::ram::IndexChoice, souffle::ram::NestedIntrinsicOperator, souffle::ram::Project, souffle::ram::AbstractExistenceCheck, souffle::ram::IndexAggregate, souffle::ram::Constraint, souffle::ram::SubroutineReturn, souffle::ram::UnpackRecord, souffle::ram::Aggregate, souffle::ram::UserDefinedOperator, souffle::ram::Choice, souffle::ram::Conjunction, souffle::ram::NestedOperation, souffle::ram::PackRecord, souffle::ram::Query, souffle::ram::EmptinessCheck, souffle::ram::Loop, souffle::ram::BinRelationStatement, souffle::ram::Exit, souffle::ram::RelationSize, souffle::ram::Negation, souffle::ram::IO, souffle::ram::IntrinsicOperator, souffle::ram::ListStatement, souffle::ram::RelationOperation, souffle::ram::AbstractConditional, souffle::ram::AbstractOperator, souffle::ram::TupleElement, souffle::ram::Call, souffle::ram::LogSize, souffle::ram::RelationStatement, souffle::ram::TupleOperation, souffle::ram::SubroutineArgument, and souffle::ram::Constant.
Definition at line 109 of file Node.h.
Referenced by operator==().
{
         return true;
     }
getChildNodes()
virtual std::vector<const Node*> souffle::ram::Node::getChildNodes () const inline virtual
Obtain list of all embedded child nodes.
Reimplemented in souffle::ram::IndexChoice, souffle::ram::Constraint, souffle::ram::IndexOperation, souffle::ram::NestedIntrinsicOperator, souffle::ram::Choice, souffle::ram::Program, souffle::ram::NestedOperation, souffle::ram::Project, souffle::ram::UnpackRecord, souffle::ram::AbstractExistenceCheck, souffle::ram::Conjunction, souffle::ram::BinRelationStatement, souffle::ram::RelationOperation, souffle::ram::EmptinessCheck, souffle::ram::Query, souffle::ram::Aggregate, souffle::ram::LogRelationTimer, souffle::ram::Exit, souffle::ram::LogTimer, souffle::ram::Loop, souffle::ram::SubroutineReturn, souffle::ram::IndexAggregate, souffle::ram::RelationSize, souffle::ram::Negation, souffle::ram::ListStatement, souffle::ram::AbstractConditional, souffle::ram::PackRecord, souffle::ram::TupleOperation, souffle::ram::AbstractOperator, souffle::ram::DebugInfo, and souffle::ram::RelationStatement.
Definition at line 87 of file Node.h.
Referenced by souffle::ram::visitDepthFirstPreOrder().
{
         return {};
     }
operator!=()
bool souffle::ram::Node::operator!= (const Node & other) const inline
Inequality check for two RAM nodes.
Definition at line 53 of file Node.h.
References clone().
{
         return !(*this == other);
     }
operator==()
bool souffle::ram::Node::operator== (const Node & other) const inline
Equivalence check for two RAM nodes.
Definition at line 46 of file Node.h.
References equal().
{
         return this == &other || (typeid(*this) == typeid(other) && equal(other));
     }
print()
virtual void souffle::ram::Node::print (std::ostream & out = std::cout) const protected pure virtual
Print RAM node.
Implemented in souffle::ram::RelationReference, souffle::ram::Program, souffle::ram::Relation, souffle::ram::Constraint, souffle::ram::AbstractExistenceCheck, souffle::ram::Conjunction, souffle::ram::UserDefinedOperator, souffle::ram::PackRecord, souffle::ram::EmptinessCheck, souffle::ram::RelationSize, souffle::ram::Negation, souffle::ram::IntrinsicOperator, souffle::ram::TupleElement, souffle::ram::FloatConstant, souffle::ram::ProvenanceExistenceCheck, souffle::ram::SignedConstant, souffle::ram::UnsignedConstant, souffle::ram::SubroutineArgument, souffle::ram::False, souffle::ram::True, souffle::ram::AutoIncrement, souffle::ram::UndefValue, souffle::ram::Statement, and souffle::ram::Operation.
rewrite()
virtual void souffle::ram::Node::rewrite (const Node * oldNode, Own< Node > newNode) inline virtual
Rewrite a child node.
Definition at line 70 of file Node.h.
References apply(), and souffle::ram::makeLambdaRamMapper().
Referenced by souffle::ram::transform::HoistConditionsTransformer::hoistConditions().
{
         assert(oldNode != nullptr && "old node is a null-pointer");
         assert(newNode != nullptr && "new node is a null-pointer");
         std::function<Own<Node>(Own<Node>)> rewriter = [&](Own<Node> node) -> Own<Node> {
             if (oldNode == node.get()) {
                 return std::move(newNode);
             } else {
                 node->apply(makeLambdaRamMapper(rewriter));
                 return node;
             }
         };
         apply(makeLambdaRamMapper(rewriter));
     };
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Node & node) friend
Print RAM on a stream.
Definition at line 94 of file Node.h.
{
         node.print(out);
         return out;
     }
The documentation for this class was generated from the following file:
ram/Node.h