souffle: souffle::ram::Project Class Reference
souffle::ram::Project Class Reference
Project a result into the target relation.
#include <Project.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Project * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get relation.
std::vector< Expression * > getValues () const
Get expressions.
Project (Own< RelationReference > relRef, VecOwn< Expression > expressions)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
VecOwn< Expression > expressions
Own< RelationReference > relationRef
Relation that values are projected into.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Project a result into the target relation.
For example:
FOR t0 IN A
  ...
    PROJECT (t0.a, t0.b, t0.c) INTO @new_X
Definition at line 46 of file Project.h.
Constructor & Destructor Documentation
Project()
souffle::ram::Project::Project (Own< RelationReference > relRef, VecOwn< Expression > expressions) inline
Definition at line 48 of file Project.h.
References relationRef.
Referenced by clone().
             : relationRef(std::move(relRef)), expressions(std::move(expressions)) {
         assert(relationRef != nullptr && "Relation reference is a null-pointer");
         for (auto const& expr : expressions) {
             assert(expr != nullptr && "Expression is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::ram::Project::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 83 of file Project.h.
References expressions, souffle::map(), and relationRef.
{
         relationRef = map(std::move(relationRef));
         for (auto& expr : expressions) {
             expr = map(std::move(expr));
         }
     }
clone()
Project* souffle::ram::Project::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Operation.
Definition at line 75 of file Project.h.
References souffle::clone(), expressions, Project(), and relationRef.
Referenced by souffle::ram::test::TEST().
{
         VecOwn<Expression> newValues;
         for (auto& expr : expressions) {
             newValues.emplace_back(expr->clone());
         }
         return new Project(souffle::clone(relationRef), std::move(newValues));
     }
equal()
bool souffle::ram::Project::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 97 of file Project.h.
References souffle::equal_ptr(), souffle::equal_targets(), expressions, and relationRef.
{
         const auto& other = static_cast<const Project&>(node);
         return equal_ptr(relationRef, other.relationRef) && equal_targets(expressions, other.expressions);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Project::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 66 of file Project.h.
References expressions, and relationRef.
{
         std::vector<const Node*> res;
         res.push_back(relationRef.get());
         for (const auto& expr : expressions) {
             res.push_back(expr.get());
         }
         return res;
     }
getRelation()
const Relation& souffle::ram::Project::getRelation () const inline
Get relation.
Definition at line 57 of file Project.h.
References relationRef.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::getProjectSuperInstInfo(), print(), and souffle::NodeGenerator::visitProject().
{
         return *relationRef->get();
     }
getValues()
std::vector<Expression*> souffle::ram::Project::getValues () const inline
Get expressions.
Definition at line 62 of file Project.h.
References expressions, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), and souffle::NodeGenerator::getProjectSuperInstInfo().
{
         return toPtrVector(expressions);
     }
print()
void souffle::ram::Project::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Definition at line 91 of file Project.h.
References expressions, souffle::ram::Relation::getName(), getRelation(), souffle::join(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PROJECT (" << join(expressions, ", ", print_deref<Own<Expression>>()) << ") INTO "
            << getRelation().getName() << std::endl;
     }
Field Documentation
expressions
VecOwn<Expression> souffle::ram::Project::expressions protected
Definition at line 106 of file Project.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getValues(), and print().
relationRef
Own<RelationReference> souffle::ram::Project::relationRef protected
Relation that values are projected into.
Definition at line 103 of file Project.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRelation(), and Project().
The documentation for this class was generated from the following file:
ram/Project.h