souffle: souffle::Trie< Dim > Class Template Reference
souffle::Trie< Dim > Class Template Reference
The most generic implementation of a Trie forming the top-level of any Trie storing tuples of arity > 1.
#include <Brie.h>
Data Structures
class iterator_core
The iterator core for trie iterators involving this level.
struct nested_trie_cloner
struct nested_trie_merger
struct op_context
Public Types
using element_type = entry_type
using entry_type = typename souffle::Tuple< RamDomain, Dim >
using iterator = typename base::template iterator< iterator_core >
using operation_hints = op_context
Public Types inherited from souffle::detail::TrieBase< Dim, Trie< Dim > >
using entry_type = typename souffle::Tuple< RamDomain, Dim >
The type of the stored entries / tuples.
Public Member Functions
iterator begin () const
Obtains an iterator referencing the first element stored within this trie.
void clear ()
Removes all entries within this trie.
bool contains (const entry_type &tuple) const
Determines whether a given tuple is present within the set specified by this trie.
bool contains (const entry_type &tuple, op_context &ctxt) const
Determines whether a given tuple is present within the set specified by this trie.
bool empty () const
Determines whether this trie is empty or not.
iterator end () const
Obtains an iterator referencing the position after the last element stored within this trie.
iterator find (const entry_type &entry) const
iterator find (const entry_type &entry, op_context &ctxt) const
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry, op_context &ctxt) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
std::size_t getMemoryUsage () const
Computes the total memory usage of this data structure.
const store_type & getStore () const
Provides a protected access to the internally maintained store.
bool insert (const entry_type &tuple)
Inserts a new entry.
bool insert (const entry_type &tuple, op_context &ctxt)
Inserts a new entry.
void insertAll (const Trie &other)
Inserts all elements stored within the given trie into this trie.
iterator lower_bound (const entry_type &entry, op_context &) const
Obtains an iterator to the first element not less than the given entry value.
iterator lower_bound (const entry_type &entry) const
Obtains an iterator to the first element not less than the given entry value.
std::vector< range< iterator > > partition (unsigned chunks=500) const
Computes a partition of an approximate number of chunks of the content of this trie.
std::size_t size () const
Determines the number of entries in this trie.
iterator upper_bound (const entry_type &entry, op_context &) const
Obtains an iterator to the first element greater than the given entry value, or end if there is no such element.
iterator upper_bound (const entry_type &entry) const
Obtains an iterator to the first element greater than the given entry value, or end if there is no such element.
~Trie ()
A simple destructore.
Public Member Functions inherited from souffle::detail::TrieBase< Dim, Trie< Dim > >
bool contains (Values... values) const
A generic function enabling the convenient conduction of a membership check.
bool insert (Values... values)
A generic function enabling the insertion of tuple values in a user-friendly way.
void printStats (std::ostream &out) const
Private Types
using base = typename souffle::detail::TrieBase< Dim, Trie< Dim > >
using nested_trie_type = Trie< Dim - 1 >
using store_type = SparseArray< nested_trie_type *, 6, nested_trie_merger, nested_trie_cloner >
Private Member Functions
template<unsigned I, typename Tuple >
bool contains_internal (const Tuple &tuple, op_context &ctxt) const
An internal implementation of the contains member function determining whether a given tuple is present within this sub-trie or not.
template<unsigned I, typename Tuple >
iterator_core< I > getBeginCoreIterator (Tuple &entry) const
Creates a core iterator for this trie level and updates component I of the given entry to exhibit the corresponding first value.
template<unsigned I, typename Tuple >
bool insert_internal (const Tuple &tuple, op_context &ctxt)
The internally utilized implementation of the insert operation inserting a given tuple into this sub-trie.
Private Attributes
store_type store
Friends
template<unsigned D>
class Trie
template<unsigned D, typename Derived >
class TrieBase
Additional Inherited Members
Protected Attributes inherited from souffle::detail::TrieBase< Dim, Trie< Dim > >
hint_statistics hint_stats
Detailed Description
template<unsigned Dim>
class souffle::Trie< Dim >
The most generic implementation of a Trie forming the top-level of any Trie storing tuples of arity > 1.
Definition at line 2282 of file Brie.h.
Member Typedef Documentation
base
template<unsigned Dim> using souffle::Trie< Dim >::base = typename souffle::detail::TrieBase<Dim, Trie<Dim> > private
Definition at line 2290 of file Brie.h.
element_type
template<unsigned Dim> using souffle::Trie< Dim >::element_type = entry_type
Definition at line 2323 of file Brie.h.
entry_type
template<unsigned Dim> using souffle::Trie< Dim >::entry_type = typename souffle::Tuple<RamDomain, Dim>
Definition at line 2322 of file Brie.h.
iterator
template<unsigned Dim> using souffle::Trie< Dim >::iterator = typename base::template iterator<iterator_core>
Definition at line 2405 of file Brie.h.
nested_trie_type
template<unsigned Dim> using souffle::Trie< Dim >::nested_trie_type = Trie<Dim - 1> private
Definition at line 2293 of file Brie.h.
operation_hints
template<unsigned Dim> using souffle::Trie< Dim >::operation_hints = op_context
Definition at line 2426 of file Brie.h.
store_type
template<unsigned Dim> using souffle::Trie< Dim >::store_type = SparseArray<nested_trie_type*, 6, nested_trie_merger, nested_trie_cloner> private
Definition at line 2316 of file Brie.h.
Constructor & Destructor Documentation
~Trie()
template<unsigned Dim> souffle::Trie< Dim >::~Trie () inline
A simple destructore.
Definition at line 2434 of file Brie.h.
             {
         for (auto& cur : store) {
             delete cur.second;  // clears all nested tries
         }
     }
Member Function Documentation
begin()
template<unsigned Dim> iterator souffle::Trie< Dim >::begin () const inline
Obtains an iterator referencing the first element stored within this trie.
Definition at line 2548 of file Brie.h.
Referenced by souffle::TEST().
{
         auto it = store.begin();
         if (it.isEnd()) return end();
         return iterator(it);
     }
clear()
template<unsigned Dim> void souffle::Trie< Dim >::clear () inline
Removes all entries within this trie.
Definition at line 2478 of file Brie.h.
                  {
         // delete lower levels
         for (auto& cur : store) {
             delete cur.second;
         }
         // clear store
         store.clear();
     }
contains() [1/2]
template<unsigned Dim> bool souffle::Trie< Dim >::contains (const entry_type & tuple) const inline
Determines whether a given tuple is present within the set specified by this trie.
Parameters
tuple the tuple to be tested
Returns
true if present, false otherwise
Definition at line 2518 of file Brie.h.
Referenced by souffle::TEST().
{
         op_context ctxt;
         return contains(tuple, ctxt);
     }
contains() [2/2]
template<unsigned Dim> bool souffle::Trie< Dim >::contains (const entry_type & tuple, op_context & ctxt) const inline
Determines whether a given tuple is present within the set specified by this trie.
A operation context may be provided to exploit temporal locality.
Parameters
tuple the entry to be added
ctxt the operation context to be utilized
Returns
true if the same tuple hasn't been present before, false otherwise
Definition at line 2532 of file Brie.h.
{
         return contains_internal<0>(tuple, ctxt);
     }
contains_internal()
template<unsigned Dim> template<unsigned I, typename Tuple > bool souffle::Trie< Dim >::contains_internal (const Tuple & tuple, op_context & ctxt) const inline private
An internal implementation of the contains member function determining whether a given tuple is present within this sub-trie or not.
Template Parameters
I the component index associated to this level
Tuple the tuple type to be checked
Parameters
tuple the tuple to be checked
ctxt a operation context to exploit temporal locality
Returns
true if this tuple is present, false otherwise
Definition at line 2816 of file Brie.h.
{
         // check context
         if (ctxt.lastNested && ctxt.lastQuery == tuple[I]) {
             base::hint_stats.contains.addHit();
             return ctxt.lastNested->template contains_internal<I + 1>(tuple, ctxt.nestedCtxt);
         } else {
             base::hint_stats.contains.addMiss();
         }
         // lookup next step
         auto next = store.lookup(tuple[I], ctxt.local);
         // clear context if necessary
         if (next != ctxt.lastNested) {
             ctxt.lastQuery = tuple[I];
             ctxt.lastNested = next;
             ctxt.nestedCtxt = typename op_context::nested_ctxt();
         }
         // conduct recursive step
         return next && next->template contains_internal<I + 1>(tuple, ctxt.nestedCtxt);
     }
empty()
template<unsigned Dim> bool souffle::Trie< Dim >::empty () const inline
Determines whether this trie is empty or not.
Definition at line 2443 of file Brie.h.
Referenced by souffle::TEST().
{
         return store.empty();
     }
end()
template<unsigned Dim> iterator souffle::Trie< Dim >::end () const inline
Obtains an iterator referencing the position after the last element stored within this trie.
Definition at line 2558 of file Brie.h.
Referenced by souffle::TEST().
{
         return iterator();
     }
find() [1/2]
template<unsigned Dim> iterator souffle::Trie< Dim >::find (const entry_type & entry) const inline
Definition at line 2562 of file Brie.h.
{
         op_context ctxt;
         return find(entry, ctxt);
     }
find() [2/2]
template<unsigned Dim> iterator souffle::Trie< Dim >::find (const entry_type & entry, op_context & ctxt) const inline
Definition at line 2567 of file Brie.h.
{
         auto range = getBoundaries<Dim>(entry, ctxt);
         return (!range.empty()) ? range.begin() : end();
     }
getBeginCoreIterator()
template<unsigned Dim> template<unsigned I, typename Tuple > iterator_core<I> souffle::Trie< Dim >::getBeginCoreIterator (Tuple & entry) const inline private
Creates a core iterator for this trie level and updates component I of the given entry to exhibit the corresponding first value.
Template Parameters
I the index of the tuple to be processed by the resulting iterator core
Tuple the type of the tuple to be processed by the resulting iterator core
Parameters
entry a reference to the tuple to be updated to the first value
Returns
the requested iterator core instance
Definition at line 2745 of file Brie.h.
{
         return iterator_core<I>(store.begin(), entry);
     }
getBoundaries() [1/2]
template<unsigned Dim> template<unsigned levels> range<iterator> souffle::Trie< Dim >::getBoundaries (const entry_type & entry) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
Returns
the corresponding range of matching elements
Definition at line 2581 of file Brie.h.
{
         op_context ctxt;
         return getBoundaries<levels>(entry, ctxt);
     }
getBoundaries() [2/2]
template<unsigned Dim> template<unsigned levels> range<iterator> souffle::Trie< Dim >::getBoundaries (const entry_type & entry, op_context & ctxt) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
A operation context may be provided to exploit temporal locality.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
ctxt the operation context to be utilized
Returns
the corresponding range of matching elements
Definition at line 2597 of file Brie.h.
{
         // if nothing is bound => just use begin and end
         if (levels == 0) return make_range(begin(), end());
         // check context
         if (ctxt.lastBoundaryLevels == levels) {
             bool fit = true;
             for (unsigned i = 0; i < levels; ++i) {
                 fit = fit && (entry[i] == ctxt.lastBoundaryRequest[i]);
             }
             // if it fits => take it
             if (fit) {
                 base::hint_stats.get_boundaries.addHit();
                 return ctxt.lastBoundaries;
             }
         }
         // the hint has not been a hit
         base::hint_stats.get_boundaries.addMiss();
         // start with two end iterators
         iterator begin{};
         iterator end{};
         // adapt them level by level
         auto found = souffle::detail::fix_binding<levels, 0, Dim>()(store, begin, end, entry);
         if (!found) return make_range(iterator(), iterator());
         // update context
         ctxt.lastBoundaryLevels = levels;
         ctxt.lastBoundaryRequest = entry;
         ctxt.lastBoundaries = make_range(begin, end);
         // use the result
         return ctxt.lastBoundaries;
     }
getMemoryUsage()
template<unsigned Dim> std::size_t souffle::Trie< Dim >::getMemoryUsage () const inline
Computes the total memory usage of this data structure.
Definition at line 2462 of file Brie.h.
{
         // compute the total memory usage of this level
         std::size_t res = sizeof(*this) - sizeof(store) + store.getMemoryUsage();
         // add the memory usage of sub-levels
         for (const auto& cur : store) {
             res += cur.second->getMemoryUsage();
         }
         // done
         return res;
     }
getStore()
template<unsigned Dim> const store_type& souffle::Trie< Dim >::getStore () const inline
Provides a protected access to the internally maintained store.
Definition at line 2730 of file Brie.h.
{
         return store;
     }
insert() [1/2]
template<unsigned Dim> bool souffle::Trie< Dim >::insert (const entry_type & tuple) inline
Inserts a new entry.
Parameters
tuple the entry to be added
Returns
true if the same tuple hasn't been present before, false otherwise
Definition at line 2494 of file Brie.h.
Referenced by souffle::TEST().
{
         op_context ctxt;
         return insert(tuple, ctxt);
     }
insert() [2/2]
template<unsigned Dim> bool souffle::Trie< Dim >::insert (const entry_type & tuple, op_context & ctxt) inline
Inserts a new entry.
A operation context may be provided to exploit temporal locality.
Parameters
tuple the entry to be added
ctxt the operation context to be utilized
Returns
true if the same tuple hasn't been present before, false otherwise
Definition at line 2507 of file Brie.h.
{
         return insert_internal<0>(tuple, ctxt);
     }
insert_internal()
template<unsigned Dim> template<unsigned I, typename Tuple > bool souffle::Trie< Dim >::insert_internal (const Tuple & tuple, op_context & ctxt) inline private
The internally utilized implementation of the insert operation inserting a given tuple into this sub-trie.
Template Parameters
I the component index associated to this level
Tuple the tuple type to be inserted
Parameters
tuple the tuple to be inserted
ctxt a operation context to exploit temporal locality
Returns
true if this tuple wasn't contained before, false otherwise
Definition at line 2760 of file Brie.h.
{
         using value_t = typename store_type::value_type;
         using atomic_value_t = typename store_type::atomic_value_type;
         // check context
         if (ctxt.lastNested && ctxt.lastQuery == tuple[I]) {
             base::hint_stats.inserts.addHit();
             return ctxt.lastNested->template insert_internal<I + 1>(tuple, ctxt.nestedCtxt);
         } else {
             base::hint_stats.inserts.addMiss();
         }
         // lookup nested
         atomic_value_t& next = store.getAtomic(tuple[I], ctxt.local);
         // get pure pointer to next level
         value_t nextPtr = next;
         // conduct a lock-free lazy-creation of nested trees
         if (!nextPtr) {
             // create a new sub-tree
             auto newNested = new nested_trie_type();
             // register new sub-tree atomically
             if (next.compare_exchange_weak(nextPtr, newNested)) {
                 nextPtr = newNested;  // worked
             } else {
                 delete newNested;  // some other thread was faster => use its version
             }
         }
         // make sure a next has been established
         assert(nextPtr);
         // clear context if necessary
         if (nextPtr != ctxt.lastNested) {
             ctxt.lastQuery = tuple[I];
             ctxt.lastNested = nextPtr;
             ctxt.nestedCtxt = typename op_context::nested_ctxt();
         }
         // conduct recursive step
         return nextPtr->template insert_internal<I + 1>(tuple, ctxt.nestedCtxt);
     }
insertAll()
template<unsigned Dim> void souffle::Trie< Dim >::insertAll (const Trie< Dim > & other) inline
Inserts all elements stored within the given trie into this trie.
Parameters
other the elements to be inserted into this trie
Definition at line 2541 of file Brie.h.
Referenced by souffle::Trie< Dim >::nested_trie_merger::operator()(), and souffle::TEST().
{
         store.addAll(other.store);
     }
lower_bound() [1/2]
template<unsigned Dim> iterator souffle::Trie< Dim >::lower_bound (const entry_type & entry, op_context &) const inline
Obtains an iterator to the first element not less than the given entry value.
Parameters
entry the lower bound for this search
ctxt the operation context to be utilized
Returns
an iterator addressing the first element in this structure not less than the given value
Definition at line 2642 of file Brie.h.
{
         // start with a default-initialized iterator
         iterator res;
         // adapt it level by level
         bool found = detail::fix_lower_bound<0, Dim>()(store, res, entry);
         // use the result
         return found ? res : end();
     }
lower_bound() [2/2]
template<unsigned Dim> iterator souffle::Trie< Dim >::lower_bound (const entry_type & entry) const inline
Obtains an iterator to the first element not less than the given entry value.
Parameters
entry the lower bound for this search
Returns
an iterator addressing the first element in this structure not less than the given value
Definition at line 2659 of file Brie.h.
{
         op_context ctxt;
         return lower_bound(entry, ctxt);
     }
partition()
template<unsigned Dim> std::vector<range<iterator> > souffle::Trie< Dim >::partition (unsigned chunks = 500) const inline
Computes a partition of an approximate number of chunks of the content of this trie.
Thus, the union of the resulting set of disjoint ranges is equivalent to the content of this trie.
Parameters
chunks the number of chunks requested
Returns
a list of sub-ranges forming a partition of the content of this trie
Definition at line 2703 of file Brie.h.
{
         std::vector<range<iterator>> res;
         // shortcut for empty trie
         if (this->empty()) return res;
         // use top-level elements for partitioning
         int step = std::max(store.size() / chunks, size_t(1));
         int c = 1;
         auto priv = begin();
         for (auto it = store.begin(); it != store.end(); ++it, c++) {
             if (c % step != 0 || c == 1) {
                 continue;
             }
             auto cur = iterator(it);
             res.push_back(make_range(priv, cur));
             priv = cur;
         }
         // add final chunk
         res.push_back(make_range(priv, end()));
         return res;
     }
size()
template<unsigned Dim> std::size_t souffle::Trie< Dim >::size () const inline
Determines the number of entries in this trie.
Definition at line 2450 of file Brie.h.
Referenced by souffle::TEST().
{
         // the number of elements is lazy-evaluated
         std::size_t res = 0;
         for (const auto& cur : store) {
             res += cur.second->size();
         }
         return res;
     }
upper_bound() [1/2]
template<unsigned Dim> iterator souffle::Trie< Dim >::upper_bound (const entry_type & entry, op_context &) const inline
Obtains an iterator to the first element greater than the given entry value, or end if there is no such element.
Parameters
entry the upper bound for this search
ctxt the operation context to be utilized
Returns
an iterator addressing the first element in this structure greater than the given value
Definition at line 2672 of file Brie.h.
{
         // start with a default-initialized iterator
         iterator res;
         // adapt it level by level
         bool found = detail::fix_upper_bound<0, Dim>()(store, res, entry);
         // use the result
         return found ? res : end();
     }
upper_bound() [2/2]
template<unsigned Dim> iterator souffle::Trie< Dim >::upper_bound (const entry_type & entry) const inline
Obtains an iterator to the first element greater than the given entry value, or end if there is no such element.
Parameters
entry the upper bound for this search
Returns
an iterator addressing the first element in this structure greater than the given value
Definition at line 2690 of file Brie.h.
{
         op_context ctxt;
         return upper_bound(entry, ctxt);
     }
Friends And Related Function Documentation
Trie
template<unsigned Dim> template<unsigned D> friend class Trie friend
Definition at line 2284 of file Brie.h.
TrieBase
template<unsigned Dim> template<unsigned D, typename Derived > friend class TrieBase friend
Definition at line 2287 of file Brie.h.
Field Documentation
store
template<unsigned Dim> store_type souffle::Trie< Dim >::store private
Definition at line 2319 of file Brie.h.
Referenced by souffle::Trie< Arity >::insertAll().
The documentation for this class was generated from the following file:
include/souffle/datastructure/Brie.h