souffle: souffle::ram::RelationReference Class Reference
souffle::ram::RelationReference Class Reference
A RAM Relation in the RAM intermediate representation.
#include <Relation.h>
Public Member Functions
RelationReference * clone () const override
Create a clone (i.e.
const Relation * get () const
Get reference.
RelationReference (const Relation *relation)
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &out) const override
Print RAM node.
Protected Attributes
const Relation * relation
Name of relation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 150 of file Relation.h.
Constructor & Destructor Documentation
RelationReference()
souffle::ram::RelationReference::RelationReference (const Relation * relation) inline
Definition at line 152 of file Relation.h.
                                                 : relation(relation) {
         assert(relation != nullptr && "null relation");
     }
Member Function Documentation
clone()
RelationReference* souffle::ram::RelationReference::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Node.
Definition at line 161 of file Relation.h.
References relation.
Referenced by souffle::ram::test::TEST().
{
         return new RelationReference(relation);
     }
equal()
bool souffle::ram::RelationReference::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 170 of file Relation.h.
References souffle::equal_ptr(), and relation.
{
         const auto& other = static_cast<const RelationReference&>(node);
         return equal_ptr(relation, other.relation);
     }
get()
const Relation* souffle::ram::RelationReference::get () const inline
Get reference.
Definition at line 157 of file Relation.h.
References relation.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return relation;
     }
print()
void souffle::ram::RelationReference::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 166 of file Relation.h.
References relation.
{
         out << relation->getName();
     }
Field Documentation
relation
const Relation* souffle::ram::RelationReference::relation protected
Name of relation.
Definition at line 177 of file Relation.h.
The documentation for this class was generated from the following file:
ram/Relation.h