souffle: souffle::ast::transform::NullableVector< T > Class Template Reference
souffle::ast::transform::NullableVector< T > Class Template Reference
Public Member Functions
const std::vector< T > & getVector () const
bool isValid () const
NullableVector ()=default
NullableVector (std::vector< T > vector)
Private Attributes
bool valid = false
std::vector< T > vector
Detailed Description
template<class T>
class souffle::ast::transform::NullableVector< T >
Definition at line 62 of file InlineRelations.cpp.
Constructor & Destructor Documentation
NullableVector() [1/2]
template<class T> souffle::ast::transform::NullableVector< T >::NullableVector () default
NullableVector() [2/2]
template<class T> souffle::ast::transform::NullableVector< T >::NullableVector (std::vector< T > vector) inline
Definition at line 69 of file InlineRelations.cpp.
 : vector(std::move(vector)), valid(true) {}
Member Function Documentation
getVector()
template<class T> const std::vector<T>& souffle::ast::transform::NullableVector< T >::getVector () const inline
Definition at line 75 of file InlineRelations.cpp.
References souffle::ast::transform::getInlinedLiteral(), and souffle::ast::transform::NullableVector< T >::vector.
Referenced by souffle::ast::transform::formNegatedLiterals(), souffle::ast::transform::getInlinedArgument(), souffle::ast::transform::getInlinedAtom(), souffle::ast::transform::getInlinedClause(), souffle::ast::transform::getInlinedLiteral(), and souffle::ast::transform::inlineBodyLiterals().
{
         assert(valid && "Accessing invalid vector!");
         return vector;
     }
isValid()
template<class T> bool souffle::ast::transform::NullableVector< T >::isValid () const inline
Definition at line 71 of file InlineRelations.cpp.
References souffle::ast::transform::NullableVector< T >::valid.
Referenced by souffle::ast::transform::formNegatedLiterals(), souffle::ast::transform::getInlinedArgument(), souffle::ast::transform::getInlinedAtom(), souffle::ast::transform::getInlinedClause(), souffle::ast::transform::getInlinedLiteral(), and souffle::ast::transform::inlineBodyLiterals().
{
         return valid;
     }
Field Documentation
valid
template<class T> bool souffle::ast::transform::NullableVector< T >::valid = false private
Definition at line 65 of file InlineRelations.cpp.
Referenced by souffle::ast::transform::NullableVector< T >::isValid().
vector
template<class T> std::vector<T> souffle::ast::transform::NullableVector< T >::vector private
Definition at line 64 of file InlineRelations.cpp.
Referenced by souffle::ast::transform::NullableVector< T >::getVector().
The documentation for this class was generated from the following file:
ast/transform/InlineRelations.cpp