souffle: souffle::ram::IO Class Reference
souffle::ram::IO Class Reference
I/O statement for a relation.
#include <IO.h>
Public Member Functions
IO * clone () const override
Create a clone (i.e.
const std::string get (const std::string &key) const
value of I/O directive
const std::map< std::string, std::string > & getDirectives () const
get I/O directives
IO (Own< RelationReference > relRef, std::map< std::string, std::string > directives)
Public Member Functions inherited from souffle::ram::RelationStatement
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get RAM relation.
RelationStatement (Own< RelationReference > relRef)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::map< std::string, std::string > directives
IO directives.
Protected Attributes inherited from souffle::ram::RelationStatement
Own< RelationReference > relationRef
Relation reference.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
I/O statement for a relation.
I/O operation for a relation, e.g., input/output/printsize
Definition at line 38 of file IO.h.
Constructor & Destructor Documentation
IO()
souffle::ram::IO::IO (Own< RelationReference > relRef, std::map< std::string, std::string > directives) inline
Definition at line 40 of file IO.h.
Referenced by clone().
             : RelationStatement(std::move(relRef)), directives(std::move(directives)) {}
Member Function Documentation
clone()
IO* souffle::ram::IO::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 53 of file IO.h.
References souffle::clone(), directives, IO(), and souffle::ram::RelationStatement::relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new IO(souffle::clone(relationRef), directives);
     }
equal()
bool souffle::ram::IO::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 68 of file IO.h.
References directives, and souffle::ram::RelationStatement::equal().
{
         const auto& other = static_cast<const IO&>(node);
         return RelationStatement::equal(other) && directives == other.directives;
     }
get()
const std::string souffle::ram::IO::get (const std::string & key) const inline
value of I/O directive
Definition at line 49 of file IO.h.
References directives.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::synthesiser::Synthesiser::generateCode(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return directives.at(key);
     }
getDirectives()
const std::map<std::string, std::string>& souffle::ram::IO::getDirectives () const inline
get I/O directives
Definition at line 44 of file IO.h.
References directives.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return directives;
     }
print()
void souffle::ram::IO::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 58 of file IO.h.
References directives, souffle::escape(), souffle::ram::Relation::getName(), souffle::ram::RelationStatement::getRelation(), souffle::join(), and souffle::times().
{
         const Relation& rel = getRelation();
         os << times(" ", tabpos);
         os << "IO " << rel.getName() << " (";
         os << join(directives, ",", [](std::ostream& out, const auto& arg) {
             out << arg.first << "=\"" << escape(arg.second) << "\"";
         });
         os << ")" << std::endl;
     };
Field Documentation
directives
std::map<std::string, std::string> souffle::ram::IO::directives protected
IO directives.
Definition at line 74 of file IO.h.
Referenced by clone(), equal(), get(), getDirectives(), and print().
The documentation for this class was generated from the following file:
ram/IO.h