souffle: souffle::ast::transform::ConditionalTransformer Class Reference
souffle::ast::transform::ConditionalTransformer Class Reference
Transformer that executes a sub-transformer iff a condition holds.
#include <Conditional.h>
Public Member Functions
ConditionalTransformer * clone () const override
ConditionalTransformer (std::function< bool()> cond, Own< Transformer > transformer)
ConditionalTransformer (bool cond, Own< Transformer > transformer)
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< Transformer * > getSubtransformers () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::ast::transform::MetaTransformer
bool applySubtransformer (TranslationUnit &translationUnit, Transformer *transformer)
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Private Attributes
std::function< bool()> condition
Own< Transformer > transformer
Additional Inherited Members
Protected Attributes inherited from souffle::ast::transform::MetaTransformer
bool verbose = false
Detailed Description
Transformer that executes a sub-transformer iff a condition holds.
Definition at line 37 of file Conditional.h.
Constructor & Destructor Documentation
ConditionalTransformer() [1/2]
souffle::ast::transform::ConditionalTransformer::ConditionalTransformer (std::function< bool()> cond, Own< Transformer > transformer) inline
Definition at line 39 of file Conditional.h.
Referenced by clone().
             : condition(std::move(cond)), transformer(std::move(transformer)) {}
ConditionalTransformer() [2/2]
souffle::ast::transform::ConditionalTransformer::ConditionalTransformer (bool cond, Own< Transformer > transformer) inline
Definition at line 42 of file Conditional.h.
References transformer.
             : condition([=]() { return cond; }), transformer(std::move(transformer)) {}
Member Function Documentation
clone()
ConditionalTransformer* souffle::ast::transform::ConditionalTransformer::clone () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 76 of file Conditional.h.
References souffle::clone(), condition, ConditionalTransformer(), and transformer.
{
         return new ConditionalTransformer(condition, souffle::clone(transformer));
     }
disableTransformers()
void souffle::ast::transform::ConditionalTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 64 of file Conditional.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(transformer->getName()) != transforms.end()) {
             transformer = mk<NullTransformer>();
         }
     }
getName()
std::string souffle::ast::transform::ConditionalTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 72 of file Conditional.h.
{
         return "ConditionalTransformer";
     }
getSubtransformers()
std::vector<Transformer*> souffle::ast::transform::ConditionalTransformer::getSubtransformers () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 45 of file Conditional.h.
References transformer.
{
         return {transformer.get()};
     }
setDebugReport()
void souffle::ast::transform::ConditionalTransformer::setDebugReport () inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 49 of file Conditional.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setDebugReport();
         } else {
             transformer = mk<DebugReporter>(std::move(transformer));
         }
     }
setVerbosity()
void souffle::ast::transform::ConditionalTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 57 of file Conditional.h.
References transformer, and souffle::ast::transform::MetaTransformer::verbose.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
transform()
bool souffle::ast::transform::ConditionalTransformer::transform (TranslationUnit & translationUnit) inline override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 84 of file Conditional.h.
References souffle::ast::transform::MetaTransformer::applySubtransformer(), and condition.
{
         return condition() ? applySubtransformer(translationUnit, transformer.get()) : false;
     }
Field Documentation
condition
std::function<bool()> souffle::ast::transform::ConditionalTransformer::condition private
Definition at line 81 of file Conditional.h.
Referenced by clone(), and transform().
transformer
Own<Transformer> souffle::ast::transform::ConditionalTransformer::transformer private
Definition at line 82 of file Conditional.h.
Referenced by clone(), ConditionalTransformer(), disableTransformers(), getSubtransformers(), setDebugReport(), and setVerbosity().
The documentation for this class was generated from the following file:
ast/transform/Conditional.h