souffle: souffle::ast::SubsetType Class Reference
souffle::ast::SubsetType Class Reference
Defines subset type class.
#include <SubsetType.h>
Public Member Functions
SubsetType * clone () const override
const QualifiedName & getBaseType () const
Return base type.
SubsetType (QualifiedName name, QualifiedName baseTypeName, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
bool equal (const Node &node) const override
void print (std::ostream &os) const override
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Private Attributes
const QualifiedName baseType
Base type.
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Detailed Description
Defines subset type class.
Example: .type A <: B
Definition at line 36 of file SubsetType.h.
Constructor & Destructor Documentation
SubsetType()
souffle::ast::SubsetType::SubsetType (QualifiedName name, QualifiedName baseTypeName, SrcLocation loc = {}) inline
Definition at line 38 of file SubsetType.h.
References souffle::ast::analysis::SubsetType::baseType, and souffle::ast::analysis::Type::Type().
                                                                                  {})
             : Type(std::move(name), std::move(loc)), baseType(std::move(baseTypeName)) {}
Member Function Documentation
clone()
SubsetType* souffle::ast::SubsetType::clone () const inline override
Definition at line 41 of file SubsetType.h.
References souffle::ast::analysis::SubsetType::getBaseType(), and souffle::ast::analysis::SubsetType::SubsetType().
{
         return new SubsetType(getQualifiedName(), getBaseType(), getSrcLoc());
     }
equal()
bool souffle::ast::SubsetType::equal (const Node & node) const inline override protected
Definition at line 55 of file SubsetType.h.
References souffle::ast::analysis::SubsetType::baseType.
{
         const auto& other = static_cast<const SubsetType&>(node);
         return getQualifiedName() == other.getQualifiedName() && baseType == other.baseType;
     }
getBaseType()
const QualifiedName& souffle::ast::SubsetType::getBaseType () const inline
Return base type.
Definition at line 46 of file SubsetType.h.
References souffle::ast::analysis::SubsetType::baseType.
{
         return baseType;
     }
print()
void souffle::ast::SubsetType::print (std::ostream & os) const inline override protected virtual
Reimplemented from souffle::ast::analysis::Type.
Definition at line 51 of file SubsetType.h.
References souffle::ast::analysis::SubsetType::getBaseType().
{
         os << ".type " << getQualifiedName() << " <: " << getBaseType();
     }
Field Documentation
baseType
const QualifiedName souffle::ast::SubsetType::baseType private
Base type.
Definition at line 62 of file SubsetType.h.
The documentation for this class was generated from the following file:
ast/SubsetType.h