souffle: souffle::ram::EmptinessCheck Class Reference
souffle::ram::EmptinessCheck Class Reference
Emptiness check for a relation.
#include <EmptinessCheck.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
EmptinessCheck * clone () const override
Create a clone (i.e.
EmptinessCheck (Own< RelationReference > relRef)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get relation.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< RelationReference > relationRef
Relation.
Detailed Description
Emptiness check for a relation.
Evaluates to true if the given relation is the empty set
For example:
(B = ∅)
Definition at line 46 of file EmptinessCheck.h.
Constructor & Destructor Documentation
EmptinessCheck()
souffle::ram::EmptinessCheck::EmptinessCheck (Own< RelationReference > relRef) inline
Definition at line 48 of file EmptinessCheck.h.
References relationRef.
Referenced by clone().
                                                   : relationRef(std::move(relRef)) {
         assert(relationRef != nullptr && "Relation reference is a nullptr");
     }
Member Function Documentation
apply()
void souffle::ram::EmptinessCheck::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 65 of file EmptinessCheck.h.
References souffle::map(), and relationRef.
{
         relationRef = map(std::move(relationRef));
     }
clone()
EmptinessCheck* souffle::ram::EmptinessCheck::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Condition.
Definition at line 61 of file EmptinessCheck.h.
References souffle::clone(), EmptinessCheck(), and relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new EmptinessCheck(souffle::clone(relationRef));
     }
equal()
bool souffle::ram::EmptinessCheck::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 74 of file EmptinessCheck.h.
References souffle::equal_ptr(), and relationRef.
{
         const auto& other = static_cast<const EmptinessCheck&>(node);
         return equal_ptr(relationRef, other.relationRef);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::EmptinessCheck::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 57 of file EmptinessCheck.h.
References relationRef.
{
         return {relationRef.get()};
     }
getRelation()
const Relation& souffle::ram::EmptinessCheck::getRelation () const inline
Get relation.
Definition at line 53 of file EmptinessCheck.h.
References relationRef.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::ComplexityAnalysis::getComplexity(), print(), and souffle::NodeGenerator::visitEmptinessCheck().
{
         return *relationRef->get();
     }
print()
void souffle::ram::EmptinessCheck::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 70 of file EmptinessCheck.h.
References souffle::ram::Relation::getName(), and getRelation().
{
         os << "(" << getRelation().getName() << " = ∅)";
     }
Field Documentation
relationRef
Own<RelationReference> souffle::ram::EmptinessCheck::relationRef protected
Relation.
Definition at line 80 of file EmptinessCheck.h.
Referenced by apply(), clone(), EmptinessCheck(), equal(), getChildNodes(), and getRelation().
The documentation for this class was generated from the following file:
ram/EmptinessCheck.h