souffle: souffle::ast::Atom Class Reference
souffle::ast::Atom Class Reference
An atom class.
#include <Atom.h>
Public Member Functions
void addArgument (Own< Argument > arg)
Add argument to the atom.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Atom (QualifiedName name={}, VecOwn< Argument > args={}, SrcLocation loc={})
Atom * clone () const override
Create a clone (i.e.
std::vector< Argument * > getArguments () const
Return arguments.
size_t getArity () const
Return arity of the atom.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const QualifiedName & getQualifiedName () const
Return qualified name.
void setQualifiedName (QualifiedName n)
Set qualified name.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< Argument > arguments
Arguments of atom.
QualifiedName name
Name of atom.
Detailed Description
An atom class.
An atom representing the use of a relation either in the head or in the body of a clause, e.g., parent(x,y), !parent(x,y), ...
Definition at line 45 of file Atom.h.
Constructor & Destructor Documentation
Atom()
souffle::ast::Atom::Atom (QualifiedName name = {}, VecOwn< Argument > args = {}, SrcLocation loc = {}) inline
Definition at line 47 of file Atom.h.
References arguments, and name.
Referenced by clone().
                               {}, VecOwn<Argument> args = {}, SrcLocation loc = {})
             : Literal(std::move(loc)), name(std::move(name)), arguments(std::move(args)) {}
Member Function Documentation
addArgument()
void souffle::ast::Atom::addArgument (Own< Argument > arg) inline
Add argument to the atom.
Definition at line 66 of file Atom.h.
References arguments.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem(), and souffle::ast::transform::transformEqrelRelation().
{
         arguments.push_back(std::move(arg));
     }
apply()
void souffle::ast::Atom::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 79 of file Atom.h.
References arguments, and souffle::map().
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
clone()
Atom* souffle::ast::Atom::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Literal.
Definition at line 75 of file Atom.h.
References arguments, Atom(), souffle::clone(), souffle::ast::Node::getSrcLoc(), and name.
Referenced by souffle::ast::transform::negateLiteral().
{
         return new Atom(name, souffle::clone(arguments), getSrcLoc());
     }
equal()
bool souffle::ast::Atom::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 98 of file Atom.h.
References arguments, souffle::equal_targets(), and name.
{
         const auto& other = static_cast<const Atom&>(node);
         return name == other.name && equal_targets(arguments, other.arguments);
     }
getArguments()
std::vector<Argument*> souffle::ast::Atom::getArguments () const inline
Return arguments.
Definition at line 71 of file Atom.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::ast::analysis::NormalisedClause::addClauseAtom(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkAtom(), souffle::ast::transform::SemanticCheckerImpl::checkFact(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::createMagicAtom(), souffle::AstToRamTranslator::ClauseTranslator::createValueIndex(), souffle::ast::getBodyRelations(), souffle::ast::transform::getInlinedAtom(), souffle::ast::isProposition(), souffle::ast::analysis::TypeConstraintsAnalysis::iterateOverAtom(), souffle::ast::transform::makeInfoRelation(), souffle::ast::analysis::NormalisedClause::NormalisedClause(), souffle::ast::BindingStore::numBoundArguments(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::test::TEST(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::ast::transform::unifyAtoms(), and souffle::ast::transform::TypeChecker::visitAtom().
{
         return toPtrVector(arguments);
     }
getArity()
size_t souffle::ast::Atom::getArity () const inline
Return arity of the atom.
Definition at line 56 of file Atom.h.
References arguments.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkAtom(), and souffle::AstToRamTranslator::ClauseTranslator::translateClause().
{
         return arguments.size();
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Atom::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 85 of file Atom.h.
References arguments.
{
         std::vector<const Node*> res;
         for (auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
getQualifiedName()
const QualifiedName& souffle::ast::Atom::getQualifiedName () const inline
Return qualified name.
Definition at line 51 of file Atom.h.
References name.
Referenced by souffle::ast::analysis::NormalisedClause::addClauseAtom(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkAtom(), souffle::ast::transform::SemanticCheckerImpl::checkFact(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::containsInlinedAtom(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::createMagicAtom(), souffle::ast::transform::formNegatedLiterals(), souffle::ast::analysis::AuxiliaryArityAnalysis::getArity(), souffle::ast::getAtomRelation(), souffle::ast::getClauseNum(), souffle::AstToRamTranslator::getEvaluationArity(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::getInlinedAtom(), souffle::ast::isRecursiveClause(), souffle::ast::transform::makeInfoRelation(), print(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::AstToRamTranslator::translateProgram(), and souffle::AstToRamTranslator::translateRelation().
{
         return name;
     }
print()
void souffle::ast::Atom::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 94 of file Atom.h.
References arguments, getQualifiedName(), and souffle::join().
{
         os << getQualifiedName() << "(" << join(arguments) << ")";
     }
setQualifiedName()
void souffle::ast::Atom::setQualifiedName (QualifiedName n) inline
Set qualified name.
Definition at line 61 of file Atom.h.
References name.
{
         name = std::move(n);
     }
Field Documentation
arguments
VecOwn<Argument> souffle::ast::Atom::arguments protected
Arguments of atom.
Definition at line 107 of file Atom.h.
Referenced by addArgument(), apply(), Atom(), clone(), equal(), getArguments(), getArity(), getChildNodes(), and print().
name
QualifiedName souffle::ast::Atom::name protected
Name of atom.
Definition at line 104 of file Atom.h.
Referenced by Atom(), clone(), equal(), getQualifiedName(), and setQualifiedName().
The documentation for this class was generated from the following file:
ast/Atom.h