souffle: souffle::ram::ParallelChoice Class Reference
souffle::ram::ParallelChoice Class Reference
Find a tuple in a relation such that a given condition holds in parallel.
#include <ParallelChoice.h>
Public Member Functions
ParallelChoice * clone () const override
Create a clone (i.e.
ParallelChoice (Own< RelationReference > rel, size_t ident, Own< Condition > cond, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Choice
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Choice (Own< RelationReference > rel, size_t ident, Own< Condition > cond, Own< Operation > nested, std::string profileText="")
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractChoice
AbstractChoice (Own< Condition > cond)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Getter for the condition.
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Choice
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractChoice
bool equal (const Node &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractChoice
Own< Condition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Find a tuple in a relation such that a given condition holds in parallel.
For example:
QUERY
 ...
  PARALLEL CHOICE t1 IN A WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 47 of file ParallelChoice.h.
Constructor & Destructor Documentation
ParallelChoice()
souffle::ram::ParallelChoice::ParallelChoice (Own< RelationReference > rel, size_t ident, Own< Condition > cond, Own< Operation > nested, std::string profileText = "") inline
Definition at line 49 of file ParallelChoice.h.
Referenced by clone().
             : Choice(std::move(rel), ident, std::move(cond), std::move(nested), profileText) {}
Member Function Documentation
clone()
ParallelChoice* souffle::ram::ParallelChoice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::ram::Choice.
Definition at line 53 of file ParallelChoice.h.
References souffle::clone(), souffle::ram::AbstractChoice::condition, souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::TupleOperation::getTupleId(), ParallelChoice(), and souffle::ram::RelationOperation::relationRef.
Referenced by souffle::ram::test::TEST().
{
         return new ParallelChoice(souffle::clone(relationRef), getTupleId(), souffle::clone(condition),
                 souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::ram::ParallelChoice::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::ram::Choice.
Definition at line 59 of file ParallelChoice.h.
References souffle::ram::AbstractChoice::getCondition(), souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PARALLEL CHOICE t" << getTupleId();
         os << " IN " << getRelation().getName();
         os << " WHERE " << getCondition();
         os << std::endl;
         RelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/ParallelChoice.h