souffle: souffle::ast::transform::GroundedTermsChecker Class Reference
souffle::ast::transform::GroundedTermsChecker Class Reference
#include <GroundedTermsChecker.h>
Public Member Functions
GroundedTermsChecker * clone () const override
std::string getName () const override
void verify (TranslationUnit &translationUnit)
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Definition at line 25 of file GroundedTermsChecker.h.
Member Function Documentation
clone()
GroundedTermsChecker* souffle::ast::transform::GroundedTermsChecker::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 34 of file GroundedTermsChecker.h.
{
         return new GroundedTermsChecker();
     }
getName()
std::string souffle::ast::transform::GroundedTermsChecker::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 27 of file GroundedTermsChecker.h.
References verify().
{
         return "GroundedTermsChecker";
     }
transform()
bool souffle::ast::transform::GroundedTermsChecker::transform (TranslationUnit & translationUnit) inline override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 39 of file GroundedTermsChecker.h.
References verify().
{
         verify(translationUnit);
         return false;
     }
verify()
void souffle::ast::transform::GroundedTermsChecker::verify (TranslationUnit & translationUnit)
Definition at line 35 of file GroundedTermsChecker.cpp.
References souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::analysis::getGroundedTerms(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::getVariables(), souffle::ast::isFact(), and souffle::ast::visitDepthFirst().
Referenced by getName(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), and transform().
{
     auto&& program = translationUnit.getProgram();
     auto&& report = translationUnit.getErrorReport();
     // -- check grounded variables and records --
     visitDepthFirst(program.getClauses(), [&](const Clause& clause) {
         if (isFact(clause)) return;  // only interested in rules
         auto isGrounded = analysis::getGroundedTerms(translationUnit, clause);
         std::set<std::string> reportedVars;
         // all terms in head need to be grounded
         for (auto&& cur : getVariables(clause)) {
             if (!isGrounded[cur] && reportedVars.insert(cur->getName()).second) {
                 report.addError("Ungrounded variable " + cur->getName(), cur->getSrcLoc());
             }
         }
         // all records need to be grounded
         visitDepthFirst(clause, [&](const RecordInit& record) {
             if (!isGrounded[&record]) {
                 report.addError("Ungrounded record", record.getSrcLoc());
             }
         });
         // All sums need to be grounded
         visitDepthFirst(clause, [&](const BranchInit& adt) {
             if (!isGrounded[&adt]) {
                 report.addError("Ungrounded ADT branch", adt.getSrcLoc());
             }
         });
     });
 }
The documentation for this class was generated from the following files:
ast/transform/GroundedTermsChecker.h
ast/transform/GroundedTermsChecker.cpp