souffle: souffle::ast::transform::NameUnnamedVariablesTransformer Class Reference
souffle::ast::transform::NameUnnamedVariablesTransformer Class Reference
Transformation pass to replace unnamed variables with singletons.
#include <NameUnnamedVariables.h>
Public Member Functions
NameUnnamedVariablesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to replace unnamed variables with singletons.
E.g.: a() :- b(_). -> a() :- b(x).
Definition at line 32 of file NameUnnamedVariables.h.
Member Function Documentation
clone()
NameUnnamedVariablesTransformer* souffle::ast::transform::NameUnnamedVariablesTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 38 of file NameUnnamedVariables.h.
References transform().
{
         return new NameUnnamedVariablesTransformer();
     }
getName()
std::string souffle::ast::transform::NameUnnamedVariablesTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 34 of file NameUnnamedVariables.h.
{
         return "NameUnnamedVariablesTransformer";
     }
transform()
bool souffle::ast::transform::NameUnnamedVariablesTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 32 of file NameUnnamedVariables.cpp.
References souffle::ast::Program::apply(), souffle::ast::getClauses(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::Program::getRelations().
Referenced by clone().
{
     bool changed = false;
     static constexpr const char* boundPrefix = "+underscore";
     static size_t underscoreCount = 0;
     struct nameVariables : public NodeMapper {
         mutable bool changed = false;
         nameVariables() = default;
         Own<Node> operator()(Own<Node> node) const override {
             if (isA<UnnamedVariable>(node.get())) {
                 changed = true;
                 std::stringstream name;
                 name << boundPrefix << "_" << underscoreCount++;
                 return mk<ast::Variable>(name.str());
             }
             node->apply(*this);
             return node;
         }
     };
     Program& program = translationUnit.getProgram();
     for (Relation* rel : program.getRelations()) {
         for (Clause* clause : getClauses(program, *rel)) {
             nameVariables update;
             clause->apply(update);
             changed |= update.changed;
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/NameUnnamedVariables.h
ast/transform/NameUnnamedVariables.cpp