souffle: souffle::ast::transform::DebugReporter Class Reference
souffle::ast::transform::DebugReporter Class Reference
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
#include <DebugReporter.h>
Public Member Functions
DebugReporter * clone () const override
DebugReporter (Own< Transformer > wrappedTransformer)
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< Transformer * > getSubtransformers () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::ast::transform::MetaTransformer
bool applySubtransformer (TranslationUnit &translationUnit, Transformer *transformer)
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
void generateDebugReport (TranslationUnit &tu, const std::string &preTransformDatalog)
bool transform (TranslationUnit &translationUnit) override
Private Attributes
Own< Transformer > wrappedTransformer
Additional Inherited Members
Protected Attributes inherited from souffle::ast::transform::MetaTransformer
bool verbose = false
Detailed Description
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
Definition at line 37 of file DebugReporter.h.
Constructor & Destructor Documentation
DebugReporter()
souffle::ast::transform::DebugReporter::DebugReporter (Own< Transformer > wrappedTransformer) inline
Definition at line 39 of file DebugReporter.h.
Referenced by clone().
 : wrappedTransformer(std::move(wrappedTransformer)) {}
Member Function Documentation
clone()
DebugReporter* souffle::ast::transform::DebugReporter::clone () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 66 of file DebugReporter.h.
References souffle::clone(), DebugReporter(), and wrappedTransformer.
{
         return new DebugReporter(souffle::clone(wrappedTransformer));
     }
disableTransformers()
void souffle::ast::transform::DebugReporter::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 54 of file DebugReporter.h.
References wrappedTransformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(wrappedTransformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(wrappedTransformer->getName()) != transforms.end()) {
             wrappedTransformer = mk<NullTransformer>();
         }
     }
generateDebugReport()
void souffle::ast::transform::DebugReporter::generateDebugReport (TranslationUnit & tu, const std::string & preTransformDatalog) private
Definition at line 43 of file DebugReporter.cpp.
References souffle::DebugReport::addCodeSection(), souffle::ast::TranslationUnit::getDebugReport(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::pprint().
Referenced by transform().
{
     tu.getDebugReport().addCodeSection(
             "dl", "Datalog", "souffle", preTransformDatalog, pprint(tu.getProgram()));
 }
getName()
std::string souffle::ast::transform::DebugReporter::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 62 of file DebugReporter.h.
{
         return "DebugReporter";
     }
getSubtransformers()
std::vector<Transformer*> souffle::ast::transform::DebugReporter::getSubtransformers () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 41 of file DebugReporter.h.
References wrappedTransformer.
{
         return {wrappedTransformer.get()};
     }
setDebugReport()
void souffle::ast::transform::DebugReporter::setDebugReport () inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 45 of file DebugReporter.h.
 {}
setVerbosity()
void souffle::ast::transform::DebugReporter::setVerbosity (bool verbose) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 47 of file DebugReporter.h.
References souffle::ast::transform::MetaTransformer::verbose, and wrappedTransformer.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(wrappedTransformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
transform()
bool souffle::ast::transform::DebugReporter::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 26 of file DebugReporter.cpp.
References souffle::ast::transform::MetaTransformer::applySubtransformer(), souffle::test::count(), souffle::DebugReport::endSection(), generateDebugReport(), souffle::ast::TranslationUnit::getDebugReport(), souffle::ast::TranslationUnit::getProgram(), souffle::now(), souffle::ast::pprint(), souffle::DebugReport::startSection(), and wrappedTransformer.
{
     translationUnit.getDebugReport().startSection();
     auto datalogSpecOriginal = pprint(translationUnit.getProgram());
     auto start = std::chrono::high_resolution_clock::now();
     bool changed = applySubtransformer(translationUnit, wrappedTransformer.get());
     auto end = std::chrono::high_resolution_clock::now();
     if (changed) {
         generateDebugReport(translationUnit, datalogSpecOriginal);
     }
     auto elapsed = std::to_string(std::chrono::duration<double>(end - start).count());
     translationUnit.getDebugReport().endSection(wrappedTransformer->getName(),
             wrappedTransformer->getName() + " (" + elapsed + "s)" + (changed ? "" : " (unchanged)"));
     return changed;
 }
Field Documentation
wrappedTransformer
Own<Transformer> souffle::ast::transform::DebugReporter::wrappedTransformer private
Definition at line 71 of file DebugReporter.h.
Referenced by clone(), disableTransformers(), getSubtransformers(), setVerbosity(), and transform().
The documentation for this class was generated from the following files:
ast/transform/DebugReporter.h
ast/transform/DebugReporter.cpp