souffle: souffle::ast::UnionType Class Reference
souffle::ast::UnionType Class Reference
The union type class.
#include <UnionType.h>
Public Member Functions
void add (QualifiedName type)
Add another unioned type.
UnionType * clone () const override
const std::vector< QualifiedName > & getTypes () const
Return list of unioned types.
void setType (size_t idx, QualifiedName type)
Set type.
UnionType (QualifiedName name, std::vector< QualifiedName > types, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
bool equal (const Node &node) const override
void print (std::ostream &os) const override
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Private Attributes
std::vector< QualifiedName > types
List of unioned types.
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Detailed Description
The union type class.
Example: .type A = B1 | B2 | ... | Bk
A union type combines multiple types into a new super type. Each of the enumerated types become a sub-type of the new union type.
Definition at line 44 of file UnionType.h.
Constructor & Destructor Documentation
UnionType()
souffle::ast::UnionType::UnionType (QualifiedName name, std::vector< QualifiedName > types, SrcLocation loc = {}) inline
Definition at line 46 of file UnionType.h.
References souffle::ast::analysis::Type::Type(), and types.
                                                                                     {})
             : Type(std::move(name), std::move(loc)), types(std::move(types)) {}
Member Function Documentation
add()
void souffle::ast::UnionType::add (QualifiedName type) inline
Add another unioned type.
Definition at line 55 of file UnionType.h.
{
         types.push_back(std::move(type));
     }
clone()
UnionType* souffle::ast::UnionType::clone () const inline override
Definition at line 64 of file UnionType.h.
References souffle::ast::analysis::UnionType::UnionType().
{
         return new UnionType(getQualifiedName(), types, getSrcLoc());
     }
equal()
bool souffle::ast::UnionType::equal (const Node & node) const inline override protected
Definition at line 73 of file UnionType.h.
{
         const auto& other = static_cast<const UnionType&>(node);
         return getQualifiedName() == other.getQualifiedName() && types == other.types;
     }
getTypes()
const std::vector<QualifiedName>& souffle::ast::UnionType::getTypes () const inline
Return list of unioned types.
Definition at line 50 of file UnionType.h.
References types.
{
         return types;
     }
print()
void souffle::ast::UnionType::print (std::ostream & os) const inline override protected virtual
Reimplemented from souffle::ast::analysis::Type.
Definition at line 69 of file UnionType.h.
References souffle::join().
{
         os << ".type " << getQualifiedName() << " = " << join(types, " | ");
     }
setType()
void souffle::ast::UnionType::setType (size_t idx, QualifiedName type) inline
Set type.
Definition at line 60 of file UnionType.h.
{
         types.at(idx) = std::move(type);
     }
Field Documentation
types
std::vector<QualifiedName> souffle::ast::UnionType::types private
List of unioned types.
Definition at line 80 of file UnionType.h.
The documentation for this class was generated from the following file:
ast/UnionType.h