souffle: souffle::ast::TypeCast Class Reference
souffle::ast::TypeCast Class Reference
Defines a type cast class for expressions.
#include <TypeCast.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
TypeCast * clone () const override
Create clone.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const QualifiedName & getType () const
Return cast type.
Argument * getValue () const
Return value.
void setType (const QualifiedName &type)
Set cast type.
TypeCast (Own< Argument > value, QualifiedName type, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
QualifiedName type
Cast type.
Own< Argument > value
Casted value.
Detailed Description
Defines a type cast class for expressions.
Definition at line 40 of file TypeCast.h.
Constructor & Destructor Documentation
TypeCast()
souffle::ast::TypeCast::TypeCast (Own< Argument > value, QualifiedName type, SrcLocation loc = {}) inline
Definition at line 42 of file TypeCast.h.
References type, and value.
Referenced by clone().
                                                                         {})
             : Argument(std::move(loc)), value(std::move(value)), type(std::move(type)) {}
Member Function Documentation
apply()
void souffle::ast::TypeCast::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 70 of file TypeCast.h.
References souffle::map().
{
         value = map(std::move(value));
     }
clone()
TypeCast* souffle::ast::TypeCast::clone () const inline override virtual
Create clone.
Implements souffle::ast::Argument.
Definition at line 66 of file TypeCast.h.
References souffle::clone(), souffle::ast::Node::getSrcLoc(), and TypeCast().
{
         return new TypeCast(souffle::clone(value), type, getSrcLoc());
     }
equal()
bool souffle::ast::TypeCast::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 79 of file TypeCast.h.
References souffle::equal_ptr().
{
         const auto& other = static_cast<const TypeCast&>(node);
         return type == other.type && equal_ptr(value, other.value);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::TypeCast::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 60 of file TypeCast.h.
References souffle::ast::Node::getChildNodes().
{
         auto res = Argument::getChildNodes();
         res.push_back(value.get());
         return res;
     }
getType()
const QualifiedName& souffle::ast::TypeCast::getType () const inline
Return cast type.
Definition at line 51 of file TypeCast.h.
References type.
Referenced by souffle::ast::transform::TypeChecker::visitTypeCast(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitTypeCast().
{
         return type;
     }
getValue()
Argument* souffle::ast::TypeCast::getValue () const inline
Return value.
Definition at line 46 of file TypeCast.h.
Referenced by souffle::ast::transform::TypeChecker::visitTypeCast(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitTypeCast().
{
         return value.get();
     }
print()
void souffle::ast::TypeCast::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 75 of file TypeCast.h.
References tinyformat::format().
{
         os << tfm::format("as(%s, %s)", *value, type);
     }
setType()
void souffle::ast::TypeCast::setType (const QualifiedName & type) inline
Set cast type.
Definition at line 56 of file TypeCast.h.
References type.
{
         this->type = type;
     }
Field Documentation
type
QualifiedName souffle::ast::TypeCast::type protected
Cast type.
Definition at line 88 of file TypeCast.h.
Referenced by getType(), setType(), and TypeCast().
value
Own<Argument> souffle::ast::TypeCast::value protected
Casted value.
Definition at line 85 of file TypeCast.h.
Referenced by TypeCast().
The documentation for this class was generated from the following file:
ast/TypeCast.h