souffle: souffle::ast::Program Class Reference
souffle::ast::Program Class Reference
The program class consists of relations, clauses and types.
#include <Program.h>
Public Member Functions
void addClause (Own< Clause > clause)
Add a clause.
void addDirective (Own< Directive > directive)
Add relation directive.
void addRelation (Own< Relation > relation)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Program * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< Clause * > getClauses () const
Return clauses.
std::vector< ComponentInit * > getComponentInstantiations () const
Return component instantiation.
std::vector< Component * > getComponents () const
Return components.
std::vector< Directive * > getDirectives () const
Return relation directives.
std::vector< FunctorDeclaration * > getFunctorDeclarations () const
Return functor declarations.
const VecOwn< Pragma > & getPragmaDirectives () const
Return pragma directives.
std::vector< Relation * > getRelations () const
Return relations.
std::vector< Type * > getTypes () const
Return types.
bool removeClause (const Clause *clause)
Remove a clause.
bool removeDirective (const Directive *directive)
Remove a directive.
bool removeRelationDecl (const QualifiedName &name)
Remove relation.
void setClauses (VecOwn< Clause > newClauses)
Set clauses.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
void addComponent (Own< Component > component)
Add component.
void addFunctorDeclaration (Own< FunctorDeclaration > functor)
void addInstantiation (Own< ComponentInit > instantiation)
Add component instantiation.
void addPragma (Own< Pragma > pragma)
void addType (Own< Type > type)
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< Clause > clauses
Program clauses.
VecOwn< Component > components
Component definitions.
VecOwn< Directive > directives
Directives.
VecOwn< FunctorDeclaration > functors
External Functors.
VecOwn< ComponentInit > instantiations
Component instantiations.
VecOwn< Pragma > pragmas
Pragmas.
VecOwn< Relation > relations
Program relations.
VecOwn< Type > types
Program types.
Friends
class souffle::ParserDriver
class transform::ComponentInstantiationTransformer
Detailed Description
The program class consists of relations, clauses and types.
Definition at line 52 of file Program.h.
Member Function Documentation
addClause()
void souffle::ast::Program::addClause (Own< Clause > clause)
Add a clause.
Definition at line 54 of file Program.cpp.
References clauses.
Referenced by souffle::ParserDriver::addClause(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::makeInfoRelation(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::normaliseInlinedHeads(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceClauseBodies(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::InlineRelationsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::ReorderLiteralsTransformer::transform(), souffle::ast::transform::ResolveAliasesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform(), and souffle::ast::transform::transformEqrelRelation().
{
     assert(clause != nullptr && "Undefined clause");
     assert(clause->getHead() != nullptr && "Undefined head of the clause");
     clauses.push_back(std::move(clause));
 }
addComponent()
void souffle::ast::Program::addComponent (Own< Component > component) inline protected
Add component.
Definition at line 245 of file Program.h.
Referenced by souffle::ParserDriver::addComponent().
{
         assert(component && "NULL component");
         components.push_back(std::move(component));
     }
addDirective()
void souffle::ast::Program::addDirective (Own< Directive > directive) inline
Add relation directive.
Definition at line 80 of file Program.h.
References directives.
Referenced by souffle::ParserDriver::addDirective(), and souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO().
{
         assert(directive && "NULL directive");
         directives.push_back(std::move(directive));
     }
addFunctorDeclaration()
void souffle::ast::Program::addFunctorDeclaration (Own< FunctorDeclaration > functor) protected
Definition at line 92 of file Program.cpp.
References functors, getFunctorDeclarations(), souffle::getIf(), and souffle::ast::FunctorDeclaration::getName().
Referenced by souffle::ParserDriver::addFunctorDeclaration().
{
     auto* existingFunctorDecl = getIf(getFunctorDeclarations(),
             [&](const FunctorDeclaration* current) { return current->getName() == f->getName(); });
     assert(existingFunctorDecl == nullptr && "Redefinition of functor!");
     functors.push_back(std::move(f));
 }
addInstantiation()
void souffle::ast::Program::addInstantiation (Own< ComponentInit > instantiation) inline protected
Add component instantiation.
Definition at line 251 of file Program.h.
Referenced by souffle::ParserDriver::addInstantiation().
{
         assert(instantiation && "NULL instantiation");
         instantiations.push_back(std::move(instantiation));
     }
addPragma()
void souffle::ast::Program::addPragma (Own< Pragma > pragma) protected
Definition at line 87 of file Program.cpp.
References pragmas.
Referenced by souffle::ParserDriver::addPragma().
{
     assert(pragma && "NULL pragma");
     pragmas.push_back(std::move(pragma));
 }
addRelation()
void souffle::ast::Program::addRelation (Own< Relation > relation)
Definition at line 35 of file Program.cpp.
References souffle::getIf(), souffle::ast::Relation::getQualifiedName(), getRelations(), and relations.
Referenced by souffle::ParserDriver::addRelation(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform(), and souffle::ast::transform::ProvenanceTransformer::transformMaxHeight().
{
     auto* existingRelation = getIf(getRelations(), [&](const Relation* current) {
         return current->getQualifiedName() == relation->getQualifiedName();
     });
     assert(existingRelation == nullptr && "Redefinition of relation!");
     relations.push_back(std::move(relation));
 }
addType()
void souffle::ast::Program::addType (Own< Type > type) protected
Definition at line 80 of file Program.cpp.
References souffle::getIf(), getTypes(), and types.
Referenced by souffle::ParserDriver::addType().
{
     auto* existingType = getIf(getTypes(),
             [&](const Type* current) { return current->getQualifiedName() == type->getQualifiedName(); });
     assert(existingType == nullptr && "Redefinition of type!");
     types.push_back(std::move(type));
 }
apply()
void souffle::ast::Program::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 133 of file Program.h.
References clauses, directives, souffle::map(), relations, and types.
Referenced by souffle::ast::transform::nameInlinedUnderscores(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveTypecastsTransformer::transform(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::RemoveRedundantSumsTransformer::transform(), souffle::ast::transform::UserDefinedFunctorsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::ADTtoRecordsTransformer::transform(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), and souffle::ast::transform::NameUnnamedVariablesTransformer::transform().
{
         for (auto& cur : pragmas) {
             cur = map(std::move(cur));
         }
         for (auto& cur : components) {
             cur = map(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : functors) {
             cur = map(std::move(cur));
         }
         for (auto& cur : types) {
             cur = map(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = map(std::move(cur));
         }
         for (auto& cur : directives) {
             cur = map(std::move(cur));
         }
     }
clone()
Program* souffle::ast::Program::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 120 of file Program.h.
References clauses, souffle::clone(), directives, relations, and types.
{
         auto res = new Program();
         res->pragmas = souffle::clone(pragmas);
         res->components = souffle::clone(components);
         res->instantiations = souffle::clone(instantiations);
         res->types = souffle::clone(types);
         res->functors = souffle::clone(functors);
         res->relations = souffle::clone(relations);
         res->clauses = souffle::clone(clauses);
         res->directives = souffle::clone(directives);
         return res;
     }
equal()
bool souffle::ast::Program::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 205 of file Program.h.
References clauses, directives, souffle::equal_targets(), relations, and types.
{
         const auto& other = static_cast<const Program&>(node);
         if (!equal_targets(pragmas, other.pragmas)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(functors, other.functors)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(directives, other.directives)) {
             return false;
         }
         return true;
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Program::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 160 of file Program.h.
References clauses, directives, relations, and types.
{
         std::vector<const Node*> res;
         for (const auto& cur : pragmas) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : functors) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : directives) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<Clause*> souffle::ast::Program::getClauses () const inline
Return clauses.
Definition at line 65 of file Program.h.
References clauses, and souffle::toPtrVector().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkBranchInits(), souffle::ast::getClauses(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::normaliseArguments(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceClauseBodies(), souffle::ast::transform::MinimiseProgramTransformer::removeRedundantClauses(), souffle::ast::analysis::TypeAnalysis::run(), souffle::ast::transform::TypeChecker::run(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::transform(), souffle::ast::transform::ReorderLiteralsTransformer::transform(), souffle::ast::transform::FoldAnonymousRecords::transform(), and souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform().
{
         return toPtrVector(clauses);
     }
getComponentInstantiations()
std::vector<ComponentInit*> souffle::ast::Program::getComponentInstantiations () const inline
Return component instantiation.
Definition at line 116 of file Program.h.
References souffle::toPtrVector().
Referenced by souffle::ast::transform::ComponentChecker::checkComponentNamespaces(), and souffle::ast::transform::ComponentChecker::checkComponents().
{
         return toPtrVector(instantiations);
     }
getComponents()
std::vector<Component*> souffle::ast::Program::getComponents () const inline
Return components.
Definition at line 111 of file Program.h.
References souffle::toPtrVector().
Referenced by souffle::ast::transform::ComponentChecker::checkComponentNamespaces(), souffle::ast::transform::ComponentChecker::checkComponents(), and souffle::ast::analysis::ComponentLookupAnalysis::run().
{
         return toPtrVector(components);
     }
getDirectives()
std::vector<Directive*> souffle::ast::Program::getDirectives () const inline
Return relation directives.
Definition at line 75 of file Program.h.
References directives, and souffle::toPtrVector().
Referenced by souffle::ParserDriver::addDirective(), souffle::ast::transform::SemanticCheckerImpl::checkIO(), souffle::ast::getDirectives(), souffle::AstToRamTranslator::getInputDirectives(), souffle::AstToRamTranslator::getOutputDirectives(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::transform::IOAttributesTransformer::setAttributeParams(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), and souffle::ast::transform::IODefaultsTransformer::setDefaults().
{
         return toPtrVector(directives);
     }
getFunctorDeclarations()
std::vector<FunctorDeclaration*> souffle::ast::Program::getFunctorDeclarations () const inline
Return functor declarations.
Definition at line 70 of file Program.h.
References souffle::toPtrVector().
Referenced by souffle::ParserDriver::addFunctorDeclaration(), addFunctorDeclaration(), and souffle::ast::transform::UserDefinedFunctorsTransformer::transform().
{
         return toPtrVector(functors);
     }
getPragmaDirectives()
const VecOwn<Pragma>& souffle::ast::Program::getPragmaDirectives () const inline
Return pragma directives.
Definition at line 86 of file Program.h.
References relation.
{
         return pragmas;
     }
getRelations()
std::vector<Relation*> souffle::ast::Program::getRelations () const inline
Return relations.
Definition at line 60 of file Program.h.
References relations, and souffle::toPtrVector().
Referenced by addRelation(), souffle::ast::transform::ComponentChecker::checkComponentNamespaces(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkNamespaces(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::getRelation(), souffle::ast::transform::nameInlinedUnderscores(), souffle::ast::transform::normaliseInlinedHeads(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::analysis::PrecedenceGraphAnalysis::run(), souffle::ast::analysis::SCCGraphAnalysis::run(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::MagicSetTransformer::shouldRun(), souffle::ast::test::TEST(), souffle::ast::transform::test::TEST(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::ReplaceSingletonVariablesTransformer::transform(), souffle::ast::transform::InlineRelationsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::NormaliseConstraintsTransformer::transform(), souffle::ast::transform::NameUnnamedVariablesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform(), and souffle::ast::transform::ProvenanceTransformer::transformMaxHeight().
{
         return toPtrVector(relations);
     }
getTypes()
std::vector<Type*> souffle::ast::Program::getTypes () const inline
Return types.
Definition at line 55 of file Program.h.
References souffle::toPtrVector(), and types.
Referenced by souffle::ParserDriver::addType(), addType(), souffle::ast::transform::ComponentChecker::checkComponentNamespaces(), souffle::ast::transform::SemanticCheckerImpl::checkNamespaces(), souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration(), souffle::ast::transform::SemanticCheckerImpl::checkTypesDeclarations(), souffle::ast::transform::SemanticCheckerImpl::checkUnionType(), souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes(), souffle::ast::transform::IOAttributesTransformer::getRecordsParams(), souffle::ast::transform::IOAttributesTransformer::getRecordsTypes(), souffle::ast::analysis::SumTypeBranchesAnalysis::run(), and souffle::ast::analysis::TypeEnvironmentAnalysis::run().
{
         return toPtrVector(types);
     }
print()
void souffle::ast::Program::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 190 of file Program.h.
References clauses, directives, souffle::join(), relations, and types.
{
         auto show = [&](auto&& xs, char const* sep = "\n") {
             if (!xs.empty()) os << join(xs, sep) << "\n";
         };
         show(pragmas, "\n\n");
         show(components);
         show(instantiations);
         show(types);
         show(functors);
         show(relations);
         show(clauses, "\n\n");
         show(directives, "\n\n");
     }
removeClause()
bool souffle::ast::Program::removeClause (const Clause * clause)
Remove a clause.
Definition at line 60 of file Program.cpp.
References clauses.
Referenced by souffle::ast::transform::normaliseInlinedHeads(), souffle::ast::transform::MinimiseProgramTransformer::reduceClauseBodies(), souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ast::transform::MinimiseProgramTransformer::removeRedundantClauses(), souffle::ast::removeRelationClauses(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::InlineRelationsTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::ReorderLiteralsTransformer::transform(), souffle::ast::transform::ResolveAliasesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), and souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform().
{
     for (auto it = clauses.begin(); it != clauses.end(); it++) {
         if (**it == *clause) {
             clauses.erase(it);
             return true;
         }
     }
     return false;
 }
removeDirective()
bool souffle::ast::Program::removeDirective (const Directive * directive)
Remove a directive.
Definition at line 70 of file Program.cpp.
References directives.
Referenced by souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), and souffle::ast::removeRelationIOs().
{
     for (auto it = directives.begin(); it != directives.end(); it++) {
         if (**it == *directive) {
             directives.erase(it);
             return true;
         }
     }
     return false;
 }
removeRelationDecl()
bool souffle::ast::Program::removeRelationDecl (const QualifiedName & name)
Remove relation.
Definition at line 43 of file Program.cpp.
References relations.
Referenced by souffle::ast::removeRelation().
{
     for (auto it = relations.begin(); it != relations.end(); it++) {
         const auto& rel = *it;
         if (rel->getQualifiedName() == name) {
             relations.erase(it);
             return true;
         }
     }
     return false;
 }
setClauses()
void souffle::ast::Program::setClauses (VecOwn< Clause > newClauses) inline
Set clauses.
Definition at line 97 of file Program.h.
References clauses.
Referenced by souffle::ast::transform::FoldAnonymousRecords::transform().
{
         clauses = std::move(newClauses);
     }
Friends And Related Function Documentation
souffle::ParserDriver
friend class souffle::ParserDriver friend
Definition at line 236 of file Program.h.
transform::ComponentInstantiationTransformer
friend class transform::ComponentInstantiationTransformer friend
Definition at line 235 of file Program.h.
Field Documentation
clauses
VecOwn<Clause> souffle::ast::Program::clauses protected
Program clauses.
Definition at line 266 of file Program.h.
Referenced by addClause(), removeClause(), and souffle::ast::transform::ComponentInstantiationTransformer::transform().
components
VecOwn<Component> souffle::ast::Program::components protected
Component definitions.
Definition at line 272 of file Program.h.
Referenced by souffle::ast::transform::ComponentInstantiationTransformer::transform().
directives
VecOwn<Directive> souffle::ast::Program::directives protected
Directives.
Definition at line 269 of file Program.h.
Referenced by removeDirective(), and souffle::ast::transform::ComponentInstantiationTransformer::transform().
functors
VecOwn<FunctorDeclaration> souffle::ast::Program::functors protected
External Functors.
Definition at line 263 of file Program.h.
Referenced by addFunctorDeclaration().
instantiations
VecOwn<ComponentInit> souffle::ast::Program::instantiations protected
Component instantiations.
Definition at line 275 of file Program.h.
Referenced by souffle::ast::transform::ComponentInstantiationTransformer::transform().
pragmas
VecOwn<Pragma> souffle::ast::Program::pragmas protected
Pragmas.
Definition at line 278 of file Program.h.
Referenced by addPragma().
relations
VecOwn<Relation> souffle::ast::Program::relations protected
Program relations.
Definition at line 260 of file Program.h.
Referenced by addRelation(), removeRelationDecl(), and souffle::ast::transform::ComponentInstantiationTransformer::transform().
types
VecOwn<Type> souffle::ast::Program::types protected
Program types.
Definition at line 257 of file Program.h.
Referenced by addType(), and souffle::ast::transform::ComponentInstantiationTransformer::transform().
The documentation for this class was generated from the following files:
ast/Program.h
ast/Program.cpp