souffle: souffle::ram::FloatConstant Class Reference
souffle::ram::FloatConstant Class Reference
Represents a float constant.
#include <FloatConstant.h>
Public Member Functions
FloatConstant * clone () const override
Create clone.
FloatConstant (RamFloat val)
RamFloat getValue () const
Get value of the constant.
Public Member Functions inherited from souffle::ram::Constant
RamDomain getConstant () const
Get constant.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::Constant
Constant (RamDomain constant)
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::ram::Constant
const RamDomain constant
Constant value.
Detailed Description
Represents a float constant.
For example:
float(3.3)
Definition at line 34 of file FloatConstant.h.
Constructor & Destructor Documentation
FloatConstant()
souffle::ram::FloatConstant::FloatConstant (RamFloat val) inline explicit
Definition at line 36 of file FloatConstant.h.
Referenced by clone().
 : Constant(ramBitCast(val)) {}
Member Function Documentation
clone()
FloatConstant* souffle::ram::FloatConstant::clone () const inline override virtual
Create clone.
Implements souffle::ram::Expression.
Definition at line 44 of file FloatConstant.h.
References FloatConstant(), and getValue().
{
         return new FloatConstant(getValue());
     }
getValue()
RamFloat souffle::ram::FloatConstant::getValue () const inline
Get value of the constant.
Definition at line 39 of file FloatConstant.h.
References souffle::ram::Constant::constant.
Referenced by clone(), souffle::synthesiser::Synthesiser::emitCode(), and print().
{
         return ramBitCast<RamFloat>(constant);
     }
print()
void souffle::ram::FloatConstant::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 49 of file FloatConstant.h.
References getValue().
{
         os << "float(" << getValue() << ")";
     }
The documentation for this class was generated from the following file:
ram/FloatConstant.h