souffle: souffle::ast::transform::RemoveRedundantRelationsTransformer Class Reference
souffle::ast::transform::RemoveRedundantRelationsTransformer Class Reference
Transformation pass to remove relations which are redundant (do not contribute to output).
#include <RemoveRedundantRelations.h>
Public Member Functions
RemoveRedundantRelationsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove relations which are redundant (do not contribute to output).
Definition at line 26 of file RemoveRedundantRelations.h.
Member Function Documentation
clone()
RemoveRedundantRelationsTransformer* souffle::ast::transform::RemoveRedundantRelationsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 32 of file RemoveRedundantRelations.h.
References transform().
{
         return new RemoveRedundantRelationsTransformer();
     }
getName()
std::string souffle::ast::transform::RemoveRedundantRelationsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 28 of file RemoveRedundantRelations.h.
{
         return "RemoveRedundantRelationsTransformer";
     }
transform()
bool souffle::ast::transform::RemoveRedundantRelationsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 24 of file RemoveRedundantRelations.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::analysis::RedundantRelationsAnalysis::getRedundantRelations(), and souffle::ast::removeRelation().
Referenced by clone().
{
     bool changed = false;
     auto* redundantRelationsAnalysis = translationUnit.getAnalysis<analysis::RedundantRelationsAnalysis>();
     const std::set<const Relation*>& redundantRelations = redundantRelationsAnalysis->getRedundantRelations();
     if (!redundantRelations.empty()) {
         for (auto rel : redundantRelations) {
             removeRelation(translationUnit, rel->getQualifiedName());
             changed = true;
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveRedundantRelations.h
ast/transform/RemoveRedundantRelations.cpp