souffle: souffle::NodeGenerator Class Reference
souffle::NodeGenerator Class Reference
#include <InterpreterGenerator.h>
Public Member Functions
NodePtr generateTree (const ram::Node &root, const ram::Program &program)
Generate the tree based on given entry.
RelationHandle & getRelationHandle (const size_t idx)
Return relation handle from given index.
VecOwn< RelationHandle > & getRelations ()
Move relation map.
NodeGenerator (ram::analysis::IndexAnalysis *isa)
NodePtr visitAggregate (const ram::Aggregate &aggregate) override
NodePtr visitAutoIncrement (const ram::AutoIncrement &inc) override
NodePtr visitBreak (const ram::Break &breakOp) override
NodePtr visitCall (const ram::Call &call) override
NodePtr visitChoice (const ram::Choice &choice) override
NodePtr visitClear (const ram::Clear &clear) override
NodePtr visitConjunction (const ram::Conjunction &conj) override
NodePtr visitConstant (const ram::Constant &num) override
NodePtr visitConstraint (const ram::Constraint &relOp) override
NodePtr visitDebugInfo (const ram::DebugInfo &dbg) override
NodePtr visitEmptinessCheck (const ram::EmptinessCheck &emptiness) override
NodePtr visitExistenceCheck (const ram::ExistenceCheck &exists) override
NodePtr visitExit (const ram::Exit &exit) override
NodePtr visitExtend (const ram::Extend &extend) override
NodePtr visitFalse (const ram::False &lfalse) override
NodePtr visitFilter (const ram::Filter &filter) override
NodePtr visitIndexAggregate (const ram::IndexAggregate &aggregate) override
NodePtr visitIndexChoice (const ram::IndexChoice &choice) override
NodePtr visitIndexScan (const ram::IndexScan &scan) override
NodePtr visitIntrinsicOperator (const ram::IntrinsicOperator &op) override
NodePtr visitIO (const ram::IO &io) override
NodePtr visitLogRelationTimer (const ram::LogRelationTimer &timer) override
NodePtr visitLogSize (const ram::LogSize &size) override
NodePtr visitLogTimer (const ram::LogTimer &timer) override
NodePtr visitLoop (const ram::Loop &loop) override
NodePtr visitNegation (const ram::Negation &neg) override
NodePtr visitNestedIntrinsicOperator (const ram::NestedIntrinsicOperator &op) override
NodePtr visitNestedOperation (const ram::NestedOperation &nested) override
NodePtr visitNode (const ram::Node &node) override
NodePtr visitPackRecord (const ram::PackRecord &pr) override
NodePtr visitParallel (const ram::Parallel &parallel) override
NodePtr visitParallelAggregate (const ram::ParallelAggregate &aggregate) override
NodePtr visitParallelChoice (const ram::ParallelChoice &pchoice) override
NodePtr visitParallelIndexAggregate (const ram::ParallelIndexAggregate &aggregate) override
NodePtr visitParallelIndexChoice (const ram::ParallelIndexChoice &ichoice) override
NodePtr visitParallelIndexScan (const ram::ParallelIndexScan &piscan) override
NodePtr visitParallelScan (const ram::ParallelScan &pScan) override
NodePtr visitProject (const ram::Project &project) override
NodePtr visitProvenanceExistenceCheck (const ram::ProvenanceExistenceCheck &provExists) override
NodePtr visitQuery (const ram::Query &query) override
NodePtr visitRelationSize (const ram::RelationSize &size) override
NodePtr visitScan (const ram::Scan &scan) override
NodePtr visitSequence (const ram::Sequence &seq) override
NodePtr visitSubroutineArgument (const ram::SubroutineArgument &arg) override
NodePtr visitSubroutineReturn (const ram::SubroutineReturn &ret) override
NodePtr visitSwap (const ram::Swap &swap) override
NodePtr visitTrue (const ram::True &ltrue) override
NodePtr visitTupleElement (const ram::TupleElement &access) override
NodePtr visitTupleOperation (const ram::TupleOperation &search) override
NodePtr visitUndefValue (const ram::UndefValue &) override
NodePtr visitUnpackRecord (const ram::UnpackRecord &lookup) override
NodePtr visitUserDefinedOperator (const ram::UserDefinedOperator &op) override
Public Member Functions inherited from souffle::ram::Visitor< Own< InterpreterNode > >
Own< InterpreterNode > operator() (const Node &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
Own< InterpreterNode > operator() (const Node *node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual Own< InterpreterNode > visit (const Node &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of Nodes.
virtual Own< InterpreterNode > visit (const Node *node, Params... args)
virtual ~Visitor ()=default
A virtual destructor.
Private Types
using NodePtr = Own< InterpreterNode >
using NodePtrVec = std::vector< NodePtr >
using RelationHandle = Own< InterpreterRelation >
Private Member Functions
void createRelation (const ram::Relation &id, const ram::analysis::MinIndexSelection &orderSet, const size_t idx)
Create and add relation into the runtime environment.
template<class RamNode >
size_t encodeIndexPos (RamNode &node)
Return operation index id from the result of indexAnalysis.
size_t encodeRelation (const ram::Relation &rel)
Encode and create the relation, return the relation id.
size_t encodeView (const ram::Node *node)
Encode and return the View id of an operation.
NodePtrVec findAllViews (const ram::Node &node)
Find all operations under the root node that requires a view.
InterpreterSuperInstruction getExistenceSuperInstInfo (const ram::AbstractExistenceCheck &exist)
Encode and return the super-instruction information about an existence check operation.
InterpreterSuperInstruction getIndexSuperInstInfo (const ram::IndexOperation &ramIndex)
Encode and return the super-instruction information about a index operation.
size_t getNewRelId ()
Get a valid relation id for encoding.
size_t getNextViewId ()
Get a valid view id for encoding.
InterpreterSuperInstruction getProjectSuperInstInfo (const ram::Project &exist)
Encode and return the super-instruction information about a project operation.
const ram::Relation & getRelationRefForView (const ram::Node *node)
Return the associated relation of a operation which requires a view.
void newQueryBlock ()
Reset view allocation system, since view's life time is within each query.
bool requireView (const ram::Node *node)
Return true if the given operation requires a view.
std::vector< const ram::Condition * > toConjunctionList (const ram::Condition *condition)
Convert terms of a conjunction to a list.
Private Attributes
std::unordered_map< const ram::Node *, size_t > indexTable
Environment encoding, store a mapping from ram::Node to its operation index id.
ram::analysis::IndexAnalysis * isa
Used by index encoding.
const bool isProvenance
If generating a provenance program.
std::shared_ptr< InterpreterViewContext > parentQueryViewContext = nullptr
Points to the current viewContext during the generation.
const bool profileEnabled
If profile is enable in this program.
ram::Program * program
ram::Program
VecOwn< RelationHandle > relations
Symbol table for relations.
size_t relId = 0
Next available location to encode a relation.
std::unordered_map< const ram::Relation *, size_t > relTable
Environment encoding, store a mapping from ram::Relation to its id.
size_t viewId = 0
Next available location to encode View.
std::unordered_map< const ram::Node *, size_t > viewTable
Environment encoding, store a mapping from ram::Node to its View id.
Additional Inherited Members
Protected Member Functions inherited from souffle::ram::Visitor< Own< InterpreterNode > >
LINK (IO, RelationStatement)
LINK (Query, Statement)
LINK (Clear, RelationStatement)
LINK (LogSize, RelationStatement)
LINK (RelationStatement, Statement)
LINK (Swap, BinRelationStatement)
LINK (Extend, BinRelationStatement)
LINK (BinRelationStatement, Statement)
LINK (Sequence, ListStatement)
LINK (Loop, Statement)
LINK (Parallel, ListStatement)
LINK (ListStatement, Statement)
LINK (Exit, Statement)
LINK (LogTimer, Statement)
LINK (LogRelationTimer, Statement)
LINK (DebugInfo, Statement)
LINK (Call, Statement)
LINK (Statement, Node)
LINK (Project, Operation)
LINK (SubroutineReturn, Operation)
LINK (UnpackRecord, TupleOperation)
LINK (Scan, RelationOperation)
LINK (ParallelScan, Scan)
LINK (IndexScan, IndexOperation)
LINK (ParallelIndexScan, IndexScan)
LINK (Choice, RelationOperation)
LINK (ParallelChoice, Choice)
LINK (IndexChoice, IndexOperation)
LINK (ParallelIndexChoice, IndexChoice)
LINK (RelationOperation, TupleOperation)
LINK (Aggregate, RelationOperation)
LINK (ParallelAggregate, Aggregate)
LINK (IndexAggregate, IndexOperation)
LINK (ParallelIndexAggregate, IndexAggregate)
LINK (IndexOperation, RelationOperation)
LINK (TupleOperation, NestedOperation)
LINK (Filter, AbstractConditional)
LINK (Break, AbstractConditional)
LINK (AbstractConditional, NestedOperation)
LINK (NestedOperation, Operation)
LINK (Operation, Node)
LINK (True, Condition)
LINK (False, Condition)
LINK (Conjunction, Condition)
LINK (Negation, Condition)
LINK (Constraint, Condition)
LINK (ProvenanceExistenceCheck, AbstractExistenceCheck)
LINK (ExistenceCheck, AbstractExistenceCheck)
LINK (EmptinessCheck, Condition)
LINK (AbstractExistenceCheck, Condition)
LINK (Condition, Node)
LINK (SignedConstant, Constant)
LINK (UnsignedConstant, Constant)
LINK (FloatConstant, Constant)
LINK (Constant, Expression)
LINK (UndefValue, Expression)
LINK (TupleElement, Expression)
LINK (IntrinsicOperator, AbstractOperator)
LINK (UserDefinedOperator, AbstractOperator)
LINK (AbstractOperator, Expression)
LINK (AutoIncrement, Expression)
LINK (PackRecord, Expression)
LINK (SubroutineArgument, Expression)
LINK (RelationSize, Expression)
LINK (Expression, Node)
LINK (Program, Node)
LINK (Relation, Node)
LINK (RelationReference, Node)
virtual Own< InterpreterNode > visitNode (const Node &, Params...)
The base case for all visitors – if no more specific overload was defined.
Detailed Description
Definition at line 113 of file InterpreterGenerator.h.
Member Typedef Documentation
NodePtr
using souffle::NodeGenerator::NodePtr = Own<InterpreterNode> private
Definition at line 114 of file InterpreterGenerator.h.
NodePtrVec
using souffle::NodeGenerator::NodePtrVec = std::vector<NodePtr> private
Definition at line 115 of file InterpreterGenerator.h.
RelationHandle
using souffle::NodeGenerator::RelationHandle = Own<InterpreterRelation> private
Definition at line 116 of file InterpreterGenerator.h.
Constructor & Destructor Documentation
NodeGenerator()
souffle::NodeGenerator::NodeGenerator (ram::analysis::IndexAnalysis * isa) inline
Definition at line 119 of file InterpreterGenerator.h.
             : isa(isa), isProvenance(Global::config().has("provenance")),
               profileEnabled(Global::config().has("profile")) {}
Member Function Documentation
createRelation()
void souffle::NodeGenerator::createRelation (const ram::Relation & id, const ram::analysis::MinIndexSelection & orderSet, const size_t idx) inline private
Create and add relation into the runtime environment.
Definition at line 696 of file InterpreterGenerator.h.
References souffle::createBTreeProvenanceIndex(), and souffle::EQREL.
Referenced by encodeRelation().
{
         RelationHandle res;
         if (relations.size() < idx + 1) {
             relations.resize(idx + 1);
         }
         if (id.getRepresentation() == RelationRepresentation::EQREL) {
             res = mk<InterpreterEqRelation>(id.getArity(), id.getAuxiliaryArity(), id.getName(),
                     std::vector<std::string>(), orderSet);
         } else {
             if (isProvenance) {
                 res = mk<InterpreterRelation>(id.getArity(), id.getAuxiliaryArity(), id.getName(),
                         std::vector<std::string>(), orderSet, createBTreeProvenanceIndex);
             } else {
                 res = mk<InterpreterRelation>(id.getArity(), id.getAuxiliaryArity(), id.getName(),
                         std::vector<std::string>(), orderSet);
             }
         }
         relations[idx] = mk<RelationHandle>(std::move(res));
     }
encodeIndexPos()
template<class RamNode > size_t souffle::NodeGenerator::encodeIndexPos (RamNode & node) inline private
Return operation index id from the result of indexAnalysis.
Definition at line 593 of file InterpreterGenerator.h.
References souffle::ram::analysis::SearchSignature::arity(), souffle::ram::analysis::SearchSignature::empty(), souffle::ram::analysis::SearchSignature::getFullSearchSignature(), souffle::ram::analysis::IndexAnalysis::getIndexes(), souffle::ram::analysis::MinIndexSelection::getLexOrderNum(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), and i.
Referenced by generateTree(), visitParallelIndexChoice(), and visitParallelIndexScan().
{
         const ram::analysis::MinIndexSelection& orderSet = isa->getIndexes(node.getRelation());
         ram::analysis::SearchSignature signature = isa->getSearchSignature(&node);
         // A zero signature is equivalent as a full order signature.
         if (signature.empty()) {
             signature = ram::analysis::SearchSignature::getFullSearchSignature(signature.arity());
         }
         auto i = orderSet.getLexOrderNum(signature);
         indexTable[&node] = i;
         return i;
     };
encodeRelation()
size_t souffle::NodeGenerator::encodeRelation (const ram::Relation & rel) inline private
Encode and create the relation, return the relation id.
Definition at line 617 of file InterpreterGenerator.h.
References createRelation(), souffle::ram::analysis::IndexAnalysis::getIndexes(), and getNewRelId().
Referenced by visitAggregate(), visitChoice(), visitClear(), visitEmptinessCheck(), visitExtend(), visitIndexAggregate(), visitIO(), visitLogRelationTimer(), visitLogSize(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), visitProject(), visitQuery(), visitRelationSize(), visitScan(), and visitSwap().
{
         auto pos = relTable.find(&rel);
         if (pos != relTable.end()) {
             return pos->second;
         }
         size_t id = getNewRelId();
         relTable[&rel] = id;
         createRelation(rel, isa->getIndexes(rel), id);
         return id;
     }
encodeView()
size_t souffle::NodeGenerator::encodeView (const ram::Node * node) inline private
Encode and return the View id of an operation.
Definition at line 606 of file InterpreterGenerator.h.
References getNextViewId().
Referenced by generateTree(), visitExistenceCheck(), visitIndexAggregate(), visitIndexChoice(), visitIndexScan(), visitParallelIndexAggregate(), visitProvenanceExistenceCheck(), and visitQuery().
{
         auto pos = viewTable.find(node);
         if (pos != viewTable.end()) {
             return pos->second;
         }
         size_t id = getNextViewId();
         viewTable[node] = id;
         return id;
     }
findAllViews()
NodePtrVec souffle::NodeGenerator::findAllViews (const ram::Node & node) inline private
Find all operations under the root node that requires a view.
Return a list of InterpreterNodes.
Definition at line 632 of file InterpreterGenerator.h.
References requireView(), souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and souffle::ast::visitDepthFirst().
{
         NodePtrVec res;
         visitDepthFirst(node, [&](const ram::Node& node) {
             if (requireView(&node)) {
                 res.push_back(visit(node));
             };
         });
         return res;
     }
generateTree()
NodePtr souffle::NodeGenerator::generateTree (const ram::Node & root, const ram::Program & program) inline
Generate the tree based on given entry.
Return a NodePtr to the root.
Definition at line 127 of file InterpreterGenerator.h.
References encodeIndexPos(), encodeView(), newQueryBlock(), program, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and souffle::ast::visitDepthFirst().
{
         this->program = const_cast<ram::Program*>(&program);
         // Encode all relation, indexPos and viewId.
         visitDepthFirst(root, [&](const ram::Node& node) {
             if (isA<ram::Query>(&node)) {
                 newQueryBlock();
             }
             if (const auto* indexSearch = dynamic_cast<const ram::IndexOperation*>(&node)) {
                 encodeIndexPos(*indexSearch);
                 encodeView(indexSearch);
             } else if (const auto* exists = dynamic_cast<const ram::ExistenceCheck*>(&node)) {
                 encodeIndexPos(*exists);
                 encodeView(exists);
             } else if (const auto* provExists = dynamic_cast<const ram::ProvenanceExistenceCheck*>(&node)) {
                 encodeIndexPos(*provExists);
                 encodeView(provExists);
             }
         });
         // Parse program
         return visit(root);
     }
getExistenceSuperInstInfo()
InterpreterSuperInstruction souffle::NodeGenerator::getExistenceSuperInstInfo (const ram::AbstractExistenceCheck & exist) inline private
Encode and return the super-instruction information about an existence check operation.
Definition at line 781 of file InterpreterGenerator.h.
References souffle::InterpreterSuperInstruction::exprFirst, souffle::InterpreterSuperInstruction::first, souffle::ram::Relation::getArity(), souffle::ram::AbstractExistenceCheck::getRelation(), souffle::ram::AbstractExistenceCheck::getValues(), i, souffle::ram::isUndefValue(), souffle::MAX_RAM_SIGNED, souffle::MIN_RAM_SIGNED, souffle::InterpreterSuperInstruction::second, souffle::InterpreterSuperInstruction::tupleFirst, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
Referenced by visitExistenceCheck(), and visitProvenanceExistenceCheck().
{
         size_t arity = exist.getRelation().getArity();
         InterpreterSuperInstruction superOp(arity);
         const auto& children = exist.getValues();
         for (size_t i = 0; i < arity; ++i) {
             auto& child = children[i];
             // Unbounded
             if (isUndefValue(child)) {
                 superOp.first[i] = MIN_RAM_SIGNED;
                 superOp.second[i] = MAX_RAM_SIGNED;
                 continue;
             }
             // Constant
             if (isA<ram::Constant>(child)) {
                 superOp.first[i] = dynamic_cast<ram::Constant*>(child)->getConstant();
                 superOp.second[i] = superOp.first[i];
                 continue;
             }
             // TupleElement
             if (isA<ram::TupleElement>(child)) {
                 auto tuple = dynamic_cast<ram::TupleElement*>(child);
                 superOp.tupleFirst.push_back({i, (size_t)tuple->getTupleId(), tuple->getElement()});
                 continue;
             }
             // Generic expression
             superOp.exprFirst.push_back(std::pair<size_t, Own<InterpreterNode>>(i, visit(child)));
         }
         return superOp;
     }
getIndexSuperInstInfo()
InterpreterSuperInstruction souffle::NodeGenerator::getIndexSuperInstInfo (const ram::IndexOperation & ramIndex) inline private
Encode and return the super-instruction information about a index operation.
Definition at line 720 of file InterpreterGenerator.h.
References souffle::InterpreterSuperInstruction::exprFirst, souffle::InterpreterSuperInstruction::exprSecond, souffle::InterpreterSuperInstruction::first, souffle::ram::Relation::getArity(), souffle::ram::IndexOperation::getRangePattern(), souffle::ram::RelationOperation::getRelation(), i, souffle::ram::isUndefValue(), low, souffle::MAX_RAM_SIGNED, souffle::MIN_RAM_SIGNED, souffle::InterpreterSuperInstruction::second, souffle::InterpreterSuperInstruction::tupleFirst, souffle::InterpreterSuperInstruction::tupleSecond, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
Referenced by visitIndexAggregate(), visitIndexChoice(), visitIndexScan(), visitParallelIndexAggregate(), visitParallelIndexChoice(), and visitParallelIndexScan().
{
         size_t arity = ramIndex.getRelation().getArity();
         InterpreterSuperInstruction indexOperation(arity);
         const auto& first = ramIndex.getRangePattern().first;
         for (size_t i = 0; i < arity; ++i) {
             auto& low = first[i];
             // Unbounded
             if (isUndefValue(low)) {
                 indexOperation.first[i] = MIN_RAM_SIGNED;
                 continue;
             }
             // Constant
             if (isA<ram::Constant>(low)) {
                 indexOperation.first[i] = dynamic_cast<ram::Constant*>(low)->getConstant();
                 continue;
             }
             // TupleElement
             if (isA<ram::TupleElement>(low)) {
                 auto lowTuple = dynamic_cast<ram::TupleElement*>(low);
                 indexOperation.tupleFirst.push_back(
                         {i, (size_t)lowTuple->getTupleId(), lowTuple->getElement()});
                 continue;
             }
             // Generic expression
             indexOperation.exprFirst.push_back(std::pair<size_t, Own<InterpreterNode>>(i, visit(low)));
         }
         const auto& second = ramIndex.getRangePattern().second;
         for (size_t i = 0; i < arity; ++i) {
             auto& hig = second[i];
             // Unbounded
             if (isUndefValue(hig)) {
                 indexOperation.second[i] = MAX_RAM_SIGNED;
                 continue;
             }
             // Constant
             if (isA<ram::Constant>(hig)) {
                 indexOperation.second[i] = dynamic_cast<ram::Constant*>(hig)->getConstant();
                 continue;
             }
             // TupleElement
             if (isA<ram::TupleElement>(hig)) {
                 auto highTuple = dynamic_cast<ram::TupleElement*>(hig);
                 indexOperation.tupleSecond.push_back(
                         {i, (size_t)highTuple->getTupleId(), highTuple->getElement()});
                 continue;
             }
             // Generic expression
             indexOperation.exprSecond.push_back(std::pair<size_t, Own<InterpreterNode>>(i, visit(hig)));
         }
         return indexOperation;
     }
getNewRelId()
size_t souffle::NodeGenerator::getNewRelId () inline private
Get a valid relation id for encoding.
Definition at line 582 of file InterpreterGenerator.h.
Referenced by encodeRelation().
{
         return relId++;
     }
getNextViewId()
size_t souffle::NodeGenerator::getNextViewId () inline private
Get a valid view id for encoding.
Definition at line 587 of file InterpreterGenerator.h.
Referenced by encodeView().
{
         return viewId++;
     }
getProjectSuperInstInfo()
InterpreterSuperInstruction souffle::NodeGenerator::getProjectSuperInstInfo (const ram::Project & exist) inline private
Encode and return the super-instruction information about a project operation.
Definition at line 817 of file InterpreterGenerator.h.
References souffle::InterpreterSuperInstruction::exprFirst, souffle::InterpreterSuperInstruction::first, souffle::ram::Relation::getArity(), souffle::ram::Project::getRelation(), souffle::ram::Project::getValues(), i, souffle::InterpreterSuperInstruction::tupleFirst, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
Referenced by visitProject().
{
         size_t arity = exist.getRelation().getArity();
         InterpreterSuperInstruction superOp(arity);
         const auto& children = exist.getValues();
         for (size_t i = 0; i < arity; ++i) {
             auto& child = children[i];
             // Constant
             if (isA<ram::Constant>(child)) {
                 superOp.first[i] = dynamic_cast<ram::Constant*>(child)->getConstant();
                 continue;
             }
             // TupleElement
             if (isA<ram::TupleElement>(child)) {
                 auto tuple = dynamic_cast<ram::TupleElement*>(child);
                 superOp.tupleFirst.push_back({i, (size_t)tuple->getTupleId(), tuple->getElement()});
                 continue;
             }
             // Generic expression
             superOp.exprFirst.push_back(std::pair<size_t, Own<InterpreterNode>>(i, visit(child)));
         }
         return superOp;
     }
getRelationHandle()
RelationHandle& souffle::NodeGenerator::getRelationHandle (const size_t idx) inline
Return relation handle from given index.
Definition at line 545 of file InterpreterGenerator.h.
References relations.
{
         return *relations[idx];
     }
getRelationRefForView()
const ram::Relation& souffle::NodeGenerator::getRelationRefForView (const ram::Node * node) inline private
Return the associated relation of a operation which requires a view.
This function assume the operation does requires a view.
Definition at line 658 of file InterpreterGenerator.h.
References souffle::fatal().
Referenced by visitQuery().
{
         if (const auto* exist = dynamic_cast<const ram::AbstractExistenceCheck*>(node)) {
             return exist->getRelation();
         } else if (const auto* index = dynamic_cast<const ram::IndexOperation*>(node)) {
             return index->getRelation();
         }
         fatal("The ram::Node does not require a view.");
     }
getRelations()
VecOwn<RelationHandle>& souffle::NodeGenerator::getRelations () inline
Move relation map.
Definition at line 540 of file InterpreterGenerator.h.
References relations.
{
         return relations;
     }
newQueryBlock()
void souffle::NodeGenerator::newQueryBlock () inline private
Reset view allocation system, since view's life time is within each query.
Definition at line 576 of file InterpreterGenerator.h.
Referenced by generateTree().
{
         viewTable.clear();
         viewId = 0;
     }
requireView()
bool souffle::NodeGenerator::requireView (const ram::Node * node) inline private
Return true if the given operation requires a view.
Definition at line 645 of file InterpreterGenerator.h.
Referenced by findAllViews(), and visitQuery().
{
         if (isA<ram::AbstractExistenceCheck>(node)) {
             return true;
         } else if (isA<ram::IndexOperation>(node)) {
             return true;
         }
         return false;
     }
toConjunctionList()
std::vector<const ram::Condition*> souffle::NodeGenerator::toConjunctionList (const ram::Condition * condition) inline private
Convert terms of a conjunction to a list.
Convert a condition of the format C1 /\ C2 /\ ... /\ Cn to a list {C1, C2, ..., Cn}.
Definition at line 674 of file InterpreterGenerator.h.
Referenced by visitQuery().
{
         std::vector<const ram::Condition*> conditionList;
         std::queue<const ram::Condition*> conditionsToProcess;
         if (condition != nullptr) {
             conditionsToProcess.push(condition);
             while (!conditionsToProcess.empty()) {
                 condition = conditionsToProcess.front();
                 conditionsToProcess.pop();
                 if (const auto* ramConj = dynamic_cast<const ram::Conjunction*>(condition)) {
                     conditionsToProcess.push(&ramConj->getLHS());
                     conditionsToProcess.push(&ramConj->getRHS());
                 } else {
                     conditionList.emplace_back(condition);
                 }
             }
         }
         return conditionList;
     }
visitAggregate()
NodePtr souffle::NodeGenerator::visitAggregate (const ram::Aggregate & aggregate) inline override
Definition at line 332 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationOperation::getRelation(), souffle::I_Aggregate, relations, relId, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterAggregate>(I_Aggregate, &aggregate, rel, visit(aggregate.getExpression()),
                 visit(aggregate.getCondition()), visitTupleOperation(aggregate));
     }
visitAutoIncrement()
NodePtr souffle::NodeGenerator::visitAutoIncrement (const ram::AutoIncrement & inc) inline override
Definition at line 157 of file InterpreterGenerator.h.
References souffle::I_AutoIncrement.
{
         return mk<InterpreterAutoIncrement>(I_AutoIncrement, &inc);
     }
visitBreak()
NodePtr souffle::NodeGenerator::visitBreak (const ram::Break & breakOp) inline override
Definition at line 369 of file InterpreterGenerator.h.
References souffle::I_Break, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterBreak>(
                 I_Break, &breakOp, visit(breakOp.getCondition()), visit(breakOp.getOperation()));
     }
visitCall()
NodePtr souffle::NodeGenerator::visitCall (const ram::Call & call) inline override
Definition at line 420 of file InterpreterGenerator.h.
References souffle::ram::Call::getName(), souffle::ram::Program::getSubroutines(), souffle::I_Call, and program.
{
         // translate a subroutine name to an index
         // the index is used to identify the subroutine
         // in the interpreter. The index is stored in the
         // data array of the InterpreterNode as the first
         // entry.
         auto subs = program->getSubroutines();
         size_t subroutineId = distance(subs.begin(), subs.find(call.getName()));
         return mk<InterpreterCall>(I_Call, &call, subroutineId);
     }
visitChoice()
NodePtr souffle::NodeGenerator::visitChoice (const ram::Choice & choice) inline override
Definition at line 294 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationOperation::getRelation(), souffle::I_Choice, relations, relId, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(choice.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterChoice>(
                 I_Choice, &choice, rel, visit(choice.getCondition()), visitTupleOperation(choice));
     }
visitClear()
NodePtr souffle::NodeGenerator::visitClear (const ram::Clear & clear) inline override
Definition at line 451 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationStatement::getRelation(), souffle::I_Clear, relations, and relId.
{
         size_t relId = encodeRelation(clear.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterClear>(I_Clear, &clear, rel);
     }
visitConjunction()
NodePtr souffle::NodeGenerator::visitConjunction (const ram::Conjunction & conj) inline override
Definition at line 207 of file InterpreterGenerator.h.
References souffle::I_Conjunction, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterConjunction>(I_Conjunction, &conj, visit(conj.getLHS()), visit(conj.getRHS()));
     }
visitConstant()
NodePtr souffle::NodeGenerator::visitConstant (const ram::Constant & num) inline override
Definition at line 149 of file InterpreterGenerator.h.
References souffle::I_Constant.
{
         return mk<InterpreterConstant>(I_Constant, &num);
     }
visitConstraint()
NodePtr souffle::NodeGenerator::visitConstraint (const ram::Constraint & relOp) inline override
Definition at line 247 of file InterpreterGenerator.h.
References souffle::I_Constraint, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterConstraint>(I_Constraint, &relOp, visit(relOp.getLHS()), visit(relOp.getRHS()));
     }
visitDebugInfo()
NodePtr souffle::NodeGenerator::visitDebugInfo (const ram::DebugInfo & dbg) inline override
Definition at line 445 of file InterpreterGenerator.h.
References souffle::ram::AbstractLog::getStatement(), souffle::I_DebugInfo, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         children.push_back(visit(dbg.getStatement()));
         return mk<InterpreterDebugInfo>(I_DebugInfo, &dbg, visit(dbg.getStatement()));
     }
visitEmptinessCheck()
NodePtr souffle::NodeGenerator::visitEmptinessCheck (const ram::EmptinessCheck & emptiness) inline override
Definition at line 215 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::EmptinessCheck::getRelation(), souffle::I_EmptinessCheck, relations, and relId.
{
         size_t relId = encodeRelation(emptiness.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterEmptinessCheck>(I_EmptinessCheck, &emptiness, rel);
     }
visitExistenceCheck()
NodePtr souffle::NodeGenerator::visitExistenceCheck (const ram::ExistenceCheck & exists) inline override
Definition at line 227 of file InterpreterGenerator.h.
References encodeView(), getExistenceSuperInstInfo(), souffle::ram::AbstractExistenceCheck::getValues(), souffle::I_ExistenceCheck, and souffle::ram::isUndefValue().
{
         InterpreterSuperInstruction superOp = getExistenceSuperInstInfo(exists);
         // Check if the search signature is a total signature
         bool isTotal = true;
         for (const auto& cur : exists.getValues()) {
             if (isUndefValue(cur)) {
                 isTotal = false;
             }
         }
         return mk<InterpreterExistenceCheck>(
                 I_ExistenceCheck, &exists, isTotal, encodeView(&exists), std::move(superOp));
     }
visitExit()
NodePtr souffle::NodeGenerator::visitExit (const ram::Exit & exit) inline override
Definition at line 416 of file InterpreterGenerator.h.
References souffle::I_Exit, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterExit>(I_Exit, &exit, visit(exit.getCondition()));
     }
visitExtend()
NodePtr souffle::NodeGenerator::visitExtend (const ram::Extend & extend) inline override
Definition at line 518 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::BinRelationStatement::getFirstRelation(), souffle::ram::BinRelationStatement::getSecondRelation(), and souffle::I_Extend.
{
         size_t src = encodeRelation(extend.getFirstRelation());
         size_t target = encodeRelation(extend.getSecondRelation());
         return mk<InterpreterExtend>(I_Extend, &extend, src, target);
     }
visitFalse()
NodePtr souffle::NodeGenerator::visitFalse (const ram::False & lfalse) inline override
Definition at line 203 of file InterpreterGenerator.h.
References souffle::I_False.
{
         return mk<InterpreterFalse>(I_False, &lfalse);
     }
visitFilter()
NodePtr souffle::NodeGenerator::visitFilter (const ram::Filter & filter) inline override
Definition at line 374 of file InterpreterGenerator.h.
References souffle::filter(), souffle::I_Filter, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterFilter>(
                 I_Filter, &filter, visit(filter.getCondition()), visit(filter.getOperation()));
     }
visitIndexAggregate()
NodePtr souffle::NodeGenerator::visitIndexAggregate (const ram::IndexAggregate & aggregate) inline override
Definition at line 349 of file InterpreterGenerator.h.
References encodeRelation(), encodeView(), getIndexSuperInstInfo(), souffle::ram::RelationOperation::getRelation(), souffle::I_IndexAggregate, relations, relId, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(aggregate);
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterIndexAggregate>(I_IndexAggregate, &aggregate, rel,
                 visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate), encodeView(&aggregate), std::move(indexOperation));
     }
visitIndexChoice()
NodePtr souffle::NodeGenerator::visitIndexChoice (const ram::IndexChoice & choice) inline override
Definition at line 310 of file InterpreterGenerator.h.
References encodeView(), getIndexSuperInstInfo(), souffle::I_IndexChoice, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(choice);
         return mk<InterpreterIndexChoice>(I_IndexChoice, &choice, nullptr, visit(choice.getCondition()),
                 visitTupleOperation(choice), encodeView(&choice), std::move(indexOperation));
     }
visitIndexScan()
NodePtr souffle::NodeGenerator::visitIndexScan (const ram::IndexScan & scan) inline override
Definition at line 276 of file InterpreterGenerator.h.
References encodeView(), getIndexSuperInstInfo(), souffle::I_IndexScan, and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(scan);
         NodePtrVec children;
         children.push_back(visitTupleOperation(scan));
         return mk<InterpreterIndexScan>(I_IndexScan, &scan, nullptr, visitTupleOperation(scan),
                 encodeView(&scan), std::move(indexOperation));
     }
visitIntrinsicOperator()
NodePtr souffle::NodeGenerator::visitIntrinsicOperator (const ram::IntrinsicOperator & op) inline override
Definition at line 161 of file InterpreterGenerator.h.
References souffle::ram::AbstractOperator::getArguments(), souffle::I_IntrinsicOperator, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& arg : op.getArguments()) {
             children.push_back(visit(arg));
         }
         return mk<InterpreterIntrinsicOperator>(I_IntrinsicOperator, &op, std::move(children));
     }
visitIO()
NodePtr souffle::NodeGenerator::visitIO (const ram::IO & io) inline override
Definition at line 463 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationStatement::getRelation(), souffle::I_IO, relations, and relId.
{
         size_t relId = encodeRelation(io.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterIO>(I_IO, &io, rel);
     }
visitLogRelationTimer()
NodePtr souffle::NodeGenerator::visitLogRelationTimer (const ram::LogRelationTimer & timer) inline override
Definition at line 431 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationStatement::getRelation(), souffle::ram::AbstractLog::getStatement(), souffle::I_LogRelationTimer, relations, relId, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         size_t relId = encodeRelation(timer.getRelation());
         auto rel = relations[relId].get();
         NodePtrVec children;
         children.push_back(visit(timer.getStatement()));
         return mk<InterpreterLogRelationTimer>(I_LogRelationTimer, &timer, visit(timer.getStatement()), rel);
     }
visitLogSize()
NodePtr souffle::NodeGenerator::visitLogSize (const ram::LogSize & size) inline override
Definition at line 457 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationStatement::getRelation(), souffle::I_LogSize, relations, and relId.
{
         size_t relId = encodeRelation(size.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterLogSize>(I_LogSize, &size, rel);
     }
visitLogTimer()
NodePtr souffle::NodeGenerator::visitLogTimer (const ram::LogTimer & timer) inline override
Definition at line 439 of file InterpreterGenerator.h.
References souffle::ram::AbstractLog::getStatement(), souffle::I_LogTimer, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         children.push_back(visit(timer.getStatement()));
         return mk<InterpreterLogTimer>(I_LogTimer, &timer, visit(timer.getStatement()));
     }
visitLoop()
NodePtr souffle::NodeGenerator::visitLoop (const ram::Loop & loop) inline override
Definition at line 412 of file InterpreterGenerator.h.
References souffle::I_Loop, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterLoop>(I_Loop, &loop, visit(loop.getBody()));
     }
visitNegation()
NodePtr souffle::NodeGenerator::visitNegation (const ram::Negation & neg) inline override
Definition at line 211 of file InterpreterGenerator.h.
References souffle::I_Negation, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return mk<InterpreterNegation>(I_Negation, &neg, visit(neg.getOperand()));
     }
visitNestedIntrinsicOperator()
NodePtr souffle::NodeGenerator::visitNestedIntrinsicOperator (const ram::NestedIntrinsicOperator & op) inline override
Definition at line 177 of file InterpreterGenerator.h.
References souffle::ram::NestedIntrinsicOperator::getArguments(), souffle::I_NestedIntrinsicOperator, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         NodePtrVec children;
         for (auto&& arg : op.getArguments()) {
             children.push_back(visit(arg));
         }
         children.push_back(visitTupleOperation(op));
         return mk<InterpreterNestedIntrinsicOperator>(I_NestedIntrinsicOperator, &op, std::move(children));
     }
visitNestedOperation()
NodePtr souffle::NodeGenerator::visitNestedOperation (const ram::NestedOperation & nested) inline override
Definition at line 251 of file InterpreterGenerator.h.
References souffle::ram::NestedOperation::getOperation(), and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         return visit(nested.getOperation());
     }
visitNode()
NodePtr souffle::NodeGenerator::visitNode (const ram::Node & node) inline override
Definition at line 534 of file InterpreterGenerator.h.
References souffle::fatal().
{
         fatal("unsupported node type: %s", typeid(node).name());
     }
visitPackRecord()
NodePtr souffle::NodeGenerator::visitPackRecord (const ram::PackRecord & pr) inline override
Definition at line 186 of file InterpreterGenerator.h.
References souffle::ram::PackRecord::getArguments(), souffle::I_PackRecord, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& arg : pr.getArguments()) {
             children.push_back(visit(arg));
         }
         return mk<InterpreterPackRecord>(I_PackRecord, &pr, std::move(children));
     }
visitParallel()
NodePtr souffle::NodeGenerator::visitParallel (const ram::Parallel & parallel) inline override
Definition at line 403 of file InterpreterGenerator.h.
References souffle::ram::ListStatement::getStatements(), souffle::I_Parallel, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         // Parallel statements are executed in sequence for now.
         NodePtrVec children;
         for (const auto& value : parallel.getStatements()) {
             children.push_back(visit(value));
         }
         return mk<InterpreterParallel>(I_Parallel, &parallel, std::move(children));
     }
visitParallelAggregate()
NodePtr souffle::NodeGenerator::visitParallelAggregate (const ram::ParallelAggregate & aggregate) inline override
Definition at line 339 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationOperation::getRelation(), souffle::I_ParallelAggregate, parentQueryViewContext, relations, relId, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         auto res = mk<InterpreterParallelAggregate>(I_ParallelAggregate, &aggregate, rel,
                 visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitParallelChoice()
NodePtr souffle::NodeGenerator::visitParallelChoice (const ram::ParallelChoice & pchoice) inline override
Definition at line 301 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationOperation::getRelation(), souffle::I_ParallelChoice, parentQueryViewContext, relations, relId, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(pchoice.getRelation());
         auto rel = relations[relId].get();
         auto res = mk<InterpreterParallelChoice>(
                 I_ParallelChoice, &pchoice, rel, visit(pchoice.getCondition()), visitTupleOperation(pchoice));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitParallelIndexAggregate()
NodePtr souffle::NodeGenerator::visitParallelIndexAggregate (const ram::ParallelIndexAggregate & aggregate) inline override
Definition at line 358 of file InterpreterGenerator.h.
References encodeRelation(), encodeView(), getIndexSuperInstInfo(), souffle::ram::RelationOperation::getRelation(), souffle::I_ParallelIndexAggregate, parentQueryViewContext, relations, relId, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(aggregate);
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         auto res = mk<InterpreterParallelIndexAggregate>(I_ParallelIndexAggregate, &aggregate, rel,
                 visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate), encodeView(&aggregate), std::move(indexOperation));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitParallelIndexChoice()
NodePtr souffle::NodeGenerator::visitParallelIndexChoice (const ram::ParallelIndexChoice & ichoice) inline override
Definition at line 316 of file InterpreterGenerator.h.
References encodeIndexPos(), encodeRelation(), getIndexSuperInstInfo(), souffle::ram::RelationOperation::getRelation(), souffle::I_ParallelIndexChoice, parentQueryViewContext, relations, relId, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(ichoice);
         size_t relId = encodeRelation(ichoice.getRelation());
         auto rel = relations[relId].get();
         auto res = mk<InterpreterParallelIndexChoice>(I_ParallelIndexChoice, &ichoice, rel,
                 visit(ichoice.getCondition()), visit(ichoice.getOperation()), encodeIndexPos(ichoice),
                 std::move(indexOperation));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitParallelIndexScan()
NodePtr souffle::NodeGenerator::visitParallelIndexScan (const ram::ParallelIndexScan & piscan) inline override
Definition at line 284 of file InterpreterGenerator.h.
References encodeIndexPos(), encodeRelation(), getIndexSuperInstInfo(), souffle::ram::RelationOperation::getRelation(), souffle::I_ParallelIndexScan, parentQueryViewContext, relations, relId, and visitTupleOperation().
{
         size_t relId = encodeRelation(piscan.getRelation());
         auto rel = relations[relId].get();
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(piscan);
         auto res = mk<InterpreterParallelIndexScan>(I_ParallelIndexScan, &piscan, rel,
                 visitTupleOperation(piscan), encodeIndexPos(piscan), std::move(indexOperation));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitParallelScan()
NodePtr souffle::NodeGenerator::visitParallelScan (const ram::ParallelScan & pScan) inline override
Definition at line 268 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationOperation::getRelation(), souffle::I_ParallelScan, parentQueryViewContext, relations, relId, and visitTupleOperation().
{
         size_t relId = encodeRelation(pScan.getRelation());
         auto rel = relations[relId].get();
         auto res = mk<InterpreterParallelScan>(I_ParallelScan, &pScan, rel, visitTupleOperation(pScan));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitProject()
NodePtr souffle::NodeGenerator::visitProject (const ram::Project & project) inline override
Definition at line 379 of file InterpreterGenerator.h.
References encodeRelation(), getProjectSuperInstInfo(), souffle::ram::Project::getRelation(), souffle::I_Project, relations, and relId.
{
         InterpreterSuperInstruction superOp = getProjectSuperInstInfo(project);
         size_t relId = encodeRelation(project.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterProject>(I_Project, &project, rel, std::move(superOp));
     }
visitProvenanceExistenceCheck()
NodePtr souffle::NodeGenerator::visitProvenanceExistenceCheck (const ram::ProvenanceExistenceCheck & provExists) inline override
Definition at line 240 of file InterpreterGenerator.h.
References encodeView(), getExistenceSuperInstInfo(), souffle::I_ProvenanceExistenceCheck, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         InterpreterSuperInstruction superOp = getExistenceSuperInstInfo(provExists);
         return mk<InterpreterProvenanceExistenceCheck>(I_ProvenanceExistenceCheck, &provExists,
                 visit(provExists.getChildNodes().back()), encodeView(&provExists), std::move(superOp));
     }
visitQuery()
NodePtr souffle::NodeGenerator::visitQuery (const ram::Query & query) inline override
Definition at line 469 of file InterpreterGenerator.h.
References encodeRelation(), encodeView(), souffle::filter(), souffle::ram::Query::getOperation(), getRelationRefForView(), souffle::I_Query, indexTable, parentQueryViewContext, requireView(), toConjunctionList(), souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and souffle::ast::visitDepthFirst().
{
         std::shared_ptr<InterpreterViewContext> viewContext = std::make_shared<InterpreterViewContext>();
         parentQueryViewContext = viewContext;
         // split terms of conditions of outer-most filter operation
         // into terms that require a context and terms that
         // do not require a view
         const ram::Operation* next = &query.getOperation();
         std::vector<const ram::Condition*> freeOfView;
         if (const auto* filter = dynamic_cast<const ram::Filter*>(&query.getOperation())) {
             next = &filter->getOperation();
             // Check terms of outer filter operation whether they can be pushed before
             // the view-generation for speed improvements
             auto conditions = toConjunctionList(&filter->getCondition());
             for (auto const& cur : conditions) {
                 bool needView = false;
                 visitDepthFirst(*cur, [&](const ram::Node& node) {
                     if (requireView(&node)) {
                         needView = true;
                         const auto& rel = getRelationRefForView(&node);
                         viewContext->addViewInfoForFilter(
                                 encodeRelation(rel), indexTable[&node], encodeView(&node));
                     }
                 });
                 if (needView) {
                     viewContext->addViewOperationForFilter(visit(*cur));
                 } else {
                     viewContext->addViewFreeOperationForFilter(visit(*cur));
                 }
             }
         }
         visitDepthFirst(*next, [&](const ram::Node& node) {
             if (requireView(&node)) {
                 const auto& rel = getRelationRefForView(&node);
                 viewContext->addViewInfoForNested(encodeRelation(rel), indexTable[&node], encodeView(&node));
             };
         });
         visitDepthFirst(*next, [&](const ram::AbstractParallel&) { viewContext->isParallel = true; });
         NodePtrVec children;
         children.push_back(visit(*next));
         auto res = mk<InterpreterQuery>(I_Query, &query, visit(*next));
         res->setViewContext(parentQueryViewContext);
         return res;
     }
visitRelationSize()
NodePtr souffle::NodeGenerator::visitRelationSize (const ram::RelationSize & size) inline override
Definition at line 221 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationSize::getRelation(), souffle::I_RelationSize, relations, and relId.
{
         size_t relId = encodeRelation(size.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterRelationSize>(I_RelationSize, &size, rel);
     }
visitScan()
NodePtr souffle::NodeGenerator::visitScan (const ram::Scan & scan) inline override
Definition at line 262 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::RelationOperation::getRelation(), souffle::I_Scan, relations, relId, and visitTupleOperation().
{
         size_t relId = encodeRelation(scan.getRelation());
         auto rel = relations[relId].get();
         return mk<InterpreterScan>(I_Scan, &scan, rel, visitTupleOperation(scan));
     }
visitSequence()
NodePtr souffle::NodeGenerator::visitSequence (const ram::Sequence & seq) inline override
Definition at line 395 of file InterpreterGenerator.h.
References souffle::ram::ListStatement::getStatements(), souffle::I_Sequence, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& value : seq.getStatements()) {
             children.push_back(visit(value));
         }
         return mk<InterpreterSequence>(I_Sequence, &seq, std::move(children));
     }
visitSubroutineArgument()
NodePtr souffle::NodeGenerator::visitSubroutineArgument (const ram::SubroutineArgument & arg) inline override
Definition at line 194 of file InterpreterGenerator.h.
References souffle::I_SubroutineArgument.
{
         return mk<InterpreterSubroutineArgument>(I_SubroutineArgument, &arg);
     }
visitSubroutineReturn()
NodePtr souffle::NodeGenerator::visitSubroutineReturn (const ram::SubroutineReturn & ret) inline override
Definition at line 387 of file InterpreterGenerator.h.
References souffle::ram::SubroutineReturn::getValues(), souffle::I_SubroutineReturn, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& value : ret.getValues()) {
             children.push_back(visit(value));
         }
         return mk<InterpreterSubroutineReturn>(I_SubroutineReturn, &ret, std::move(children));
     }
visitSwap()
NodePtr souffle::NodeGenerator::visitSwap (const ram::Swap & swap) inline override
Definition at line 524 of file InterpreterGenerator.h.
References encodeRelation(), souffle::ram::BinRelationStatement::getFirstRelation(), souffle::ram::BinRelationStatement::getSecondRelation(), and souffle::I_Swap.
{
         size_t src = encodeRelation(swap.getFirstRelation());
         size_t target = encodeRelation(swap.getSecondRelation());
         return mk<InterpreterSwap>(I_Swap, &swap, src, target);
     }
visitTrue()
NodePtr souffle::NodeGenerator::visitTrue (const ram::True & ltrue) inline override
Definition at line 199 of file InterpreterGenerator.h.
References souffle::I_True.
{
         return mk<InterpreterTrue>(I_True, &ltrue);
     }
visitTupleElement()
NodePtr souffle::NodeGenerator::visitTupleElement (const ram::TupleElement & access) inline override
Definition at line 153 of file InterpreterGenerator.h.
References souffle::I_TupleElement.
{
         return mk<InterpreterTupleElement>(I_TupleElement, &access);
     }
visitTupleOperation()
NodePtr souffle::NodeGenerator::visitTupleOperation (const ram::TupleOperation & search) inline override
Definition at line 255 of file InterpreterGenerator.h.
References souffle::ram::NestedOperation::getOperation(), souffle::I_TupleOperation, profileEnabled, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
Referenced by visitAggregate(), visitChoice(), visitIndexAggregate(), visitIndexChoice(), visitIndexScan(), visitNestedIntrinsicOperator(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexScan(), visitParallelScan(), visitScan(), and visitUnpackRecord().
{
         if (profileEnabled) {
             return mk<InterpreterTupleOperation>(I_TupleOperation, &search, visit(search.getOperation()));
         }
         return visit(search.getOperation());
     }
visitUndefValue()
NodePtr souffle::NodeGenerator::visitUndefValue (const ram::UndefValue &) inline override
Definition at line 530 of file InterpreterGenerator.h.
{
         return nullptr;
     }
visitUnpackRecord()
NodePtr souffle::NodeGenerator::visitUnpackRecord (const ram::UnpackRecord & lookup) inline override
Definition at line 327 of file InterpreterGenerator.h.
References souffle::I_UnpackRecord, souffle::ram::Visitor< Own< InterpreterNode > >::visit(), and visitTupleOperation().
                                                                       {  // get reference
         return mk<InterpreterUnpackRecord>(
                 I_UnpackRecord, &lookup, visit(lookup.getExpression()), visitTupleOperation(lookup));
     }
visitUserDefinedOperator()
NodePtr souffle::NodeGenerator::visitUserDefinedOperator (const ram::UserDefinedOperator & op) inline override
Definition at line 169 of file InterpreterGenerator.h.
References souffle::ram::AbstractOperator::getArguments(), souffle::I_UserDefinedOperator, and souffle::ram::Visitor< Own< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& arg : op.getArguments()) {
             children.push_back(visit(arg));
         }
         return mk<InterpreterUserDefinedOperator>(I_UserDefinedOperator, &op, std::move(children));
     }
Field Documentation
indexTable
std::unordered_map<const ram::Node*, size_t> souffle::NodeGenerator::indexTable private
Environment encoding, store a mapping from ram::Node to its operation index id.
Definition at line 551 of file InterpreterGenerator.h.
Referenced by visitQuery().
isa
ram::analysis::IndexAnalysis* souffle::NodeGenerator::isa private
Used by index encoding.
Definition at line 553 of file InterpreterGenerator.h.
isProvenance
const bool souffle::NodeGenerator::isProvenance private
If generating a provenance program.
Definition at line 569 of file InterpreterGenerator.h.
parentQueryViewContext
std::shared_ptr<InterpreterViewContext> souffle::NodeGenerator::parentQueryViewContext = nullptr private
Points to the current viewContext during the generation.
It is used to passing viewContext between parent query and its nested parallel operation. As parallel operation requires its own view information.
Definition at line 557 of file InterpreterGenerator.h.
Referenced by visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), and visitQuery().
profileEnabled
const bool souffle::NodeGenerator::profileEnabled private
If profile is enable in this program.
Definition at line 571 of file InterpreterGenerator.h.
Referenced by visitTupleOperation().
program
ram::Program* souffle::NodeGenerator::program private
ram::Program
Definition at line 573 of file InterpreterGenerator.h.
Referenced by generateTree(), and visitCall().
relations
VecOwn<RelationHandle> souffle::NodeGenerator::relations private
Symbol table for relations.
Definition at line 567 of file InterpreterGenerator.h.
Referenced by getRelationHandle(), getRelations(), visitAggregate(), visitChoice(), visitClear(), visitEmptinessCheck(), visitIndexAggregate(), visitIO(), visitLogRelationTimer(), visitLogSize(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), visitProject(), visitRelationSize(), and visitScan().
relId
size_t souffle::NodeGenerator::relId = 0 private
Next available location to encode a relation.
Definition at line 561 of file InterpreterGenerator.h.
Referenced by visitAggregate(), visitChoice(), visitClear(), visitEmptinessCheck(), visitIndexAggregate(), visitIO(), visitLogRelationTimer(), visitLogSize(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), visitProject(), visitRelationSize(), and visitScan().
relTable
std::unordered_map<const ram::Relation*, size_t> souffle::NodeGenerator::relTable private
Environment encoding, store a mapping from ram::Relation to its id.
Definition at line 565 of file InterpreterGenerator.h.
viewId
size_t souffle::NodeGenerator::viewId = 0 private
Next available location to encode View.
Definition at line 559 of file InterpreterGenerator.h.
viewTable
std::unordered_map<const ram::Node*, size_t> souffle::NodeGenerator::viewTable private
Environment encoding, store a mapping from ram::Node to its View id.
Definition at line 563 of file InterpreterGenerator.h.
The documentation for this class was generated from the following file:
interpreter/InterpreterGenerator.h