souffle: souffle::ast::NumericConstant Class Reference
souffle::ast::NumericConstant Class Reference
Numeric Constant.
#include <NumericConstant.h>
Public Types
enum Type { Type::Int, Type::Uint, Type::Float }
Public Member Functions
NumericConstant * clone () const override
Create clone.
const std::optional< Type > & getType () const
NumericConstant (RamSigned value)
NumericConstant (std::string constant, SrcLocation loc)
NumericConstant (std::string constant, std::optional< Type > type=std::nullopt, SrcLocation loc={})
void setType (Type newType)
Public Member Functions inherited from souffle::ast::Constant
const std::string & getConstant () const
Get string representation of Constant.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
Protected Member Functions inherited from souffle::ast::Constant
Constant (std::string value, SrcLocation loc={})
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::optional< Type > type
Detailed Description
Numeric Constant.
The constant can be initialized with type. If this is the case, the typesystem will be forced to use it. Otherwise the type is inferred from context.
Definition at line 36 of file NumericConstant.h.
Member Enumeration Documentation
Type
enum souffle::ast::NumericConstant::Type strong
Enumerator
Int
Uint
Float
Definition at line 38 of file NumericConstant.h.
 { Int, Uint, Float };
Constructor & Destructor Documentation
NumericConstant() [1/3]
souffle::ast::NumericConstant::NumericConstant (RamSigned value) inline
Definition at line 40 of file NumericConstant.h.
Referenced by clone().
 : Constant(std::to_string(value)), type(Type::Int) {}
NumericConstant() [2/3]
souffle::ast::NumericConstant::NumericConstant (std::string constant, SrcLocation loc) inline
Definition at line 42 of file NumericConstant.h.
References souffle::ast::Node::setSrcLoc().
                                                          : Constant(std::move(constant)) {
         setSrcLoc(std::move(loc));
     }
NumericConstant() [3/3]
souffle::ast::NumericConstant::NumericConstant (std::string constant, std::optional< Type > type = std::nullopt, SrcLocation loc = {}) inline
Definition at line 46 of file NumericConstant.h.
References souffle::ast::Constant::Constant(), souffle::ast::Node::setSrcLoc(), and type.
                                                                                                {})
             : Constant(std::move(constant)), type(type) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
clone()
NumericConstant* souffle::ast::NumericConstant::clone () const inline override virtual
Create clone.
Implements souffle::ast::Constant.
Definition at line 51 of file NumericConstant.h.
References souffle::ast::Constant::getConstant(), souffle::ast::Node::getSrcLoc(), getType(), and NumericConstant().
{
         auto* copy = new NumericConstant(getConstant(), getType());
         copy->setSrcLoc(getSrcLoc());
         return copy;
     }
equal()
bool souffle::ast::NumericConstant::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Constant.
Definition at line 66 of file NumericConstant.h.
References souffle::ast::Constant::equal(), and type.
{
         const auto& other = static_cast<const NumericConstant&>(node);
         return Constant::equal(node) && type == other.type;
     }
getType()
const std::optional<Type>& souffle::ast::NumericConstant::getType () const inline
Definition at line 57 of file NumericConstant.h.
References type.
Referenced by clone(), souffle::AstToRamTranslator::translateValue(), souffle::ast::transform::TypeChecker::visitNumericConstant(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
{
         return type;
     }
setType()
void souffle::ast::NumericConstant::setType (Type newType) inline
Definition at line 61 of file NumericConstant.h.
References type.
{
         type = newType;
     }
Field Documentation
type
std::optional<Type> souffle::ast::NumericConstant::type private
Definition at line 72 of file NumericConstant.h.
Referenced by equal(), getType(), NumericConstant(), and setType().
The documentation for this class was generated from the following file:
ast/NumericConstant.h