souffle: souffle::ram::transform::HoistAggregateTransformer Class Reference
souffle::ram::transform::HoistAggregateTransformer Class Reference
#include <HoistAggregate.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool hoistAggregate (Program &program)
Apply hoistAggregate to the whole program.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
analysis::LevelAnalysis * rla {nullptr}
Detailed Description
Definition at line 34 of file HoistAggregate.h.
Member Function Documentation
getName()
std::string souffle::ram::transform::HoistAggregateTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 36 of file HoistAggregate.h.
References hoistAggregate().
{
         return "HoistAggregateTransformer";
     }
hoistAggregate()
bool souffle::ram::transform::HoistAggregateTransformer::hoistAggregate (Program & program)
Apply hoistAggregate to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Pushes an Aggregate up the loop nest if possible
Definition at line 30 of file HoistAggregate.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::clone(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::Query::getOperation(), souffle::ram::makeLambdaRamMapper(), rla, and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     // There are two cases: aggregates that have no data-dependencies on
     // other RAM operations, and aggregates that have data-dependencies.
     // A rewriter has two tasks: (1) identify a single aggregate that
     // can be hoisted and (2) insert it at the outermost level.
     // We assume all Operations are renumbered for this transformation.
     // Hoist a single aggregate to an outer scope that is data-independent.
     visitDepthFirst(program, [&](const Query& query) {
         Own<NestedOperation> newAgg;
         bool priorTupleOp = false;
         std::function<Own<Node>(Own<Node>)> aggRewriter = [&](Own<Node> node) -> Own<Node> {
             if (isA<Aggregate>(node.get())) {
                 auto* tupleOp = dynamic_cast<TupleOperation*>(node.get());
                 assert(tupleOp != nullptr && "aggregate conversion to tuple operation failed");
                 if (rla->getLevel(tupleOp) == -1 && !priorTupleOp) {
                     changed = true;
                     newAgg = souffle::clone(tupleOp);
                     assert(newAgg != nullptr && "failed to make a clone");
                     return souffle::clone(&tupleOp->getOperation());
                 }
             } else if (isA<TupleOperation>(node.get())) {
                 // tuple operation that is a non-aggregate
                 priorTupleOp = true;
             }
             node->apply(makeLambdaRamMapper(aggRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(aggRewriter));
         if (newAgg != nullptr) {
             newAgg->rewrite(&newAgg->getOperation(), souffle::clone(&query.getOperation()));
             const_cast<Query*>(&query)->rewrite(&query.getOperation(), std::move(newAgg));
         }
     });
     // hoist a single aggregate to an outer scope that is data-dependent on a prior operation.
     visitDepthFirst(program, [&](const Query& query) {
         int newLevel = -1;
         Own<NestedOperation> newAgg;
         int priorOpLevel = -1;
         std::function<Own<Node>(Own<Node>)> aggRewriter = [&](Own<Node> node) -> Own<Node> {
             if (isA<AbstractAggregate>(node.get())) {
                 auto* tupleOp = dynamic_cast<TupleOperation*>(node.get());
                 assert(tupleOp != nullptr && "aggregate conversion to nested operation failed");
                 int dataDepLevel = rla->getLevel(tupleOp);
                 if (dataDepLevel != -1 && dataDepLevel < tupleOp->getTupleId() - 1) {
                     // If all tuple ops between the data-dependence level and agg
                     // are aggregates, then we do not hoist, i.e., we would
                     // continuously swap their positions.
                     if (dataDepLevel != priorOpLevel) {
                         changed = true;
                         newLevel = dataDepLevel;
                         newAgg = souffle::clone(tupleOp);
                         assert(newAgg != nullptr && "failed to make a clone");
                         return souffle::clone(&tupleOp->getOperation());
                     }
                 }
             } else if (const TupleOperation* tupleOp = dynamic_cast<TupleOperation*>(node.get())) {
                 priorOpLevel = tupleOp->getTupleId();
             }
             node->apply(makeLambdaRamMapper(aggRewriter));
             if (auto* search = dynamic_cast<TupleOperation*>(node.get())) {
                 if (newAgg != nullptr && search->getTupleId() == newLevel) {
                     newAgg->rewrite(&newAgg->getOperation(), souffle::clone(&search->getOperation()));
                     search->rewrite(&search->getOperation(), std::move(newAgg));
                 }
             }
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(aggRewriter));
     });
     return changed;
 }  // namespace souffle
transform()
bool souffle::ram::transform::HoistAggregateTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 51 of file HoistAggregate.h.
References souffle::ram::TranslationUnit::getAnalysis(), souffle::ram::TranslationUnit::getProgram(), hoistAggregate(), and rla.
{
         rla = translationUnit.getAnalysis<analysis::LevelAnalysis>();
         return hoistAggregate(translationUnit.getProgram());
     }
Field Documentation
rla
analysis::LevelAnalysis* souffle::ram::transform::HoistAggregateTransformer::rla {nullptr} protected
Definition at line 50 of file HoistAggregate.h.
Referenced by hoistAggregate(), and transform().
The documentation for this class was generated from the following files:
ram/transform/HoistAggregate.h
ram/transform/HoistAggregate.cpp