souffle: souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer Class Reference
souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer Class Reference
Transformation pass to add artificial nullary atom (+Tautology()) to aggregate bodies that have no atoms.
#include <AddNullariesToAtomlessAggregates.h>
Public Member Functions
AddNullariesToAtomlessAggregatesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to add artificial nullary atom (+Tautology()) to aggregate bodies that have no atoms.
Definition at line 34 of file AddNullariesToAtomlessAggregates.h.
Member Function Documentation
clone()
AddNullariesToAtomlessAggregatesTransformer* souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 40 of file AddNullariesToAtomlessAggregates.h.
References transform().
{
         return new AddNullariesToAtomlessAggregatesTransformer();
     }
getName()
std::string souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file AddNullariesToAtomlessAggregates.h.
{
         return "AddNullariesToAtomlessAggregatesTransformer";
     }
transform()
bool souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 34 of file AddNullariesToAtomlessAggregates.cpp.
References souffle::ast::Program::addClause(), souffle::ast::Program::addRelation(), souffle::clone(), souffle::ast::Aggregator::getBodyLiterals(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::getRelation(), and souffle::ast::visitDepthFirst().
Referenced by clone().
{
     bool changed{false};
     Program& program = translationUnit.getProgram();
     visitDepthFirst(program, [&](const Aggregator& agg) {
         bool seenAtom{false};
         for (const auto& literal : agg.getBodyLiterals()) {
             if (isA<Atom>(literal)) {
                 seenAtom = true;
             }
         }
         if (seenAtom) {
             return;
         }
         // We will add in the Tautology atom to the body of this aggregate now
         changed = true;
         // +Tautology()
         auto nullaryAtom = mk<Atom>();
         std::string relName = "+Tautology";
         nullaryAtom->setQualifiedName(relName);
         if (getRelation(program, relName) == nullptr) {
             // +Tautology().
             auto fact = mk<Clause>();
             fact->setHead(souffle::clone(nullaryAtom));
             // .decl +Tautology()
             auto tautologyRel = mk<Relation>();
             tautologyRel->setQualifiedName(relName);
             program.addRelation(std::move(tautologyRel));
             program.addClause(std::move(fact));
         }
         VecOwn<Literal> newBody;
         for (const auto& lit : agg.getBodyLiterals()) {
             newBody.push_back(souffle::clone(lit));
         }
         newBody.push_back(souffle::clone(nullaryAtom));
         const_cast<Aggregator&>(agg).setBody(std::move(newBody));
     });
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/AddNullariesToAtomlessAggregates.h
ast/transform/AddNullariesToAtomlessAggregates.cpp