souffle: souffle::ram::BinRelationStatement Class Reference
souffle::ram::BinRelationStatement Class Reference
Abstract class for a binary relation.
#include <BinRelationStatement.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
BinRelationStatement (Own< RelationReference > f, Own< RelationReference > s)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getFirstRelation () const
Get first relation.
const Relation & getSecondRelation () const
Get second relation.
Public Member Functions inherited from souffle::ram::Statement
Statement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Attributes
Own< RelationReference > first
first argument of binary statement
Own< RelationReference > second
second argument of binary statement
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for a binary relation.
Comprises two Relations
Definition at line 37 of file BinRelationStatement.h.
Constructor & Destructor Documentation
BinRelationStatement()
souffle::ram::BinRelationStatement::BinRelationStatement (Own< RelationReference > f, Own< RelationReference > s) inline
Definition at line 39 of file BinRelationStatement.h.
References first, i, and second.
             : first(std::move(f)), second(std::move(s)) {
         assert(first->get()->getArity() == second->get()->getArity() && "mismatching arities");
         assert(first != nullptr && "First relation is a null-pointer");
         assert(second != nullptr && "Second relation is a null-pointer");
         const auto& type1 = first->get()->getAttributeTypes();
         const auto& type2 = first->get()->getAttributeTypes();
         for (size_t i = 0; i < first->get()->getArity(); i++) {
             assert(type1[i] == type2[i] && "mismatching type");
         }
     }
Member Function Documentation
apply()
void souffle::ram::BinRelationStatement::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 66 of file BinRelationStatement.h.
References first, souffle::map(), and second.
{
         first = map(std::move(first));
         second = map(std::move(second));
     }
equal()
bool souffle::ram::BinRelationStatement::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 72 of file BinRelationStatement.h.
References souffle::equal_ptr(), first, and second.
{
         const auto& other = static_cast<const BinRelationStatement&>(node);
         return equal_ptr(first, other.first) && equal_ptr(second, other.second);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::BinRelationStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 62 of file BinRelationStatement.h.
References first, and second.
{
         return {first.get(), second.get()};
     }
getFirstRelation()
const Relation& souffle::ram::BinRelationStatement::getFirstRelation () const inline
Get first relation.
Definition at line 53 of file BinRelationStatement.h.
References first.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::Extend::getSourceRelation(), souffle::ram::Swap::print(), souffle::NodeGenerator::visitExtend(), and souffle::NodeGenerator::visitSwap().
{
         return *first->get();
     }
getSecondRelation()
const Relation& souffle::ram::BinRelationStatement::getSecondRelation () const inline
Get second relation.
Definition at line 58 of file BinRelationStatement.h.
References second.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::Extend::getTargetRelation(), souffle::ram::Swap::print(), souffle::NodeGenerator::visitExtend(), and souffle::NodeGenerator::visitSwap().
{
         return *second->get();
     }
Field Documentation
first
Own<RelationReference> souffle::ram::BinRelationStatement::first protected
first argument of binary statement
Definition at line 79 of file BinRelationStatement.h.
Referenced by apply(), BinRelationStatement(), souffle::ram::Swap::clone(), souffle::ram::Extend::clone(), equal(), getChildNodes(), and getFirstRelation().
second
Own<RelationReference> souffle::ram::BinRelationStatement::second protected
second argument of binary statement
Definition at line 82 of file BinRelationStatement.h.
Referenced by apply(), BinRelationStatement(), souffle::ram::Swap::clone(), souffle::ram::Extend::clone(), equal(), getChildNodes(), and getSecondRelation().
The documentation for this class was generated from the following file:
ram/BinRelationStatement.h