souffle: souffle::ast::ExecutionPlan Class Reference
souffle::ast::ExecutionPlan Class Reference
#include <ExecutionPlan.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
ExecutionPlan * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::map< int, const ExecutionOrder * > getOrders () const
Get orders.
void setOrderFor (int version, Own< ExecutionOrder > plan)
Set execution order for a given rule version.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &out) const override
Output to a given output stream.
Private Attributes
std::map< int, Own< ExecutionOrder > > plans
Mapping versions of clauses to execution orders.
Detailed Description
Definition at line 45 of file ExecutionPlan.h.
Member Function Documentation
apply()
void souffle::ast::ExecutionPlan::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 70 of file ExecutionPlan.h.
References souffle::map(), and plans.
{
         for (auto& plan : plans) {
             plan.second = map(std::move(plan.second));
         }
     }
clone()
ExecutionPlan* souffle::ast::ExecutionPlan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 61 of file ExecutionPlan.h.
References souffle::ast::Node::getSrcLoc(), and plans.
{
         auto res = new ExecutionPlan();
         res->setSrcLoc(getSrcLoc());
         for (auto& plan : plans) {
             res->setOrderFor(plan.first, Own<ExecutionOrder>(plan.second->clone()));
         }
         return res;
     }
equal()
bool souffle::ast::ExecutionPlan::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 93 of file ExecutionPlan.h.
References souffle::equal_targets(), and plans.
{
         const auto& other = static_cast<const ExecutionPlan&>(node);
         return equal_targets(plans, other.plans);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::ExecutionPlan::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 76 of file ExecutionPlan.h.
References plans.
{
         std::vector<const Node*> childNodes;
         for (auto& plan : plans) {
             childNodes.push_back(plan.second.get());
         }
         return childNodes;
     }
getOrders()
std::map<int, const ExecutionOrder*> souffle::ast::ExecutionPlan::getOrders () const inline
Get orders.
Definition at line 53 of file ExecutionPlan.h.
References plans.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkClause(), and souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause().
{
         std::map<int, const ExecutionOrder*> result;
         for (auto& plan : plans) {
             result.insert(std::make_pair(plan.first, plan.second.get()));
         }
         return result;
     }
print()
void souffle::ast::ExecutionPlan::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 85 of file ExecutionPlan.h.
References souffle::join(), and plans.
{
         if (!plans.empty()) {
             out << " .plan ";
             out << join(plans, ", ",
                     [](std::ostream& os, const auto& arg) { os << arg.first << ":" << *arg.second; });
         }
     }
setOrderFor()
void souffle::ast::ExecutionPlan::setOrderFor (int version, Own< ExecutionOrder > plan) inline
Set execution order for a given rule version.
Definition at line 48 of file ExecutionPlan.h.
References plans.
{
         plans[version] = std::move(plan);
     }
Field Documentation
plans
std::map<int, Own<ExecutionOrder> > souffle::ast::ExecutionPlan::plans private
Mapping versions of clauses to execution orders.
Definition at line 100 of file ExecutionPlan.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getOrders(), print(), and setOrderFor().
The documentation for this class was generated from the following file:
ast/ExecutionPlan.h