souffle: souffle::ram::SubroutineArgument Class Reference
souffle::ram::SubroutineArgument Class Reference
Access argument of a subroutine.
#include <SubroutineArgument.h>
Public Member Functions
SubroutineArgument * clone () const override
Create a clone (i.e.
size_t getArgument () const
Get argument.
SubroutineArgument (size_t number)
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const size_t number
Argument number.
Detailed Description
Access argument of a subroutine.
Arguments are number from zero 0 to n-1 where n is the number of arguments of the subroutine.
Definition at line 34 of file SubroutineArgument.h.
Constructor & Destructor Documentation
SubroutineArgument()
souffle::ram::SubroutineArgument::SubroutineArgument (size_t number) inline
Definition at line 36 of file SubroutineArgument.h.
Referenced by clone().
 : number(number) {}
Member Function Documentation
clone()
SubroutineArgument* souffle::ram::SubroutineArgument::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Expression.
Definition at line 43 of file SubroutineArgument.h.
References number, and SubroutineArgument().
Referenced by souffle::ram::test::TEST().
{
         return new SubroutineArgument(number);
     }
equal()
bool souffle::ram::SubroutineArgument::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 52 of file SubroutineArgument.h.
References number.
{
         const auto& other = static_cast<const SubroutineArgument&>(node);
         return number == other.number;
     }
getArgument()
size_t souffle::ram::SubroutineArgument::getArgument () const inline
Get argument.
Definition at line 39 of file SubroutineArgument.h.
References number.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return number;
     }
print()
void souffle::ram::SubroutineArgument::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 48 of file SubroutineArgument.h.
References number.
{
         os << "argument(" << number << ")";
     }
Field Documentation
number
const size_t souffle::ram::SubroutineArgument::number protected
Argument number.
Definition at line 58 of file SubroutineArgument.h.
Referenced by clone(), equal(), getArgument(), and print().
The documentation for this class was generated from the following file:
ram/SubroutineArgument.h