souffle: souffle::ast::transform::PipelineTransformer Class Reference
souffle::ast::transform::PipelineTransformer Class Reference
Transformer that holds an arbitrary number of sub-transformations.
#include <Pipeline.h>
Public Member Functions
PipelineTransformer * clone () const override
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< Transformer * > getSubtransformers () const override
template<typename... Args>
PipelineTransformer (Args... args)
PipelineTransformer (VecOwn< Transformer > pipeline)
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::ast::transform::MetaTransformer
bool applySubtransformer (TranslationUnit &translationUnit, Transformer *transformer)
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
Protected Attributes
VecOwn< Transformer > pipeline
Protected Attributes inherited from souffle::ast::transform::MetaTransformer
bool verbose = false
Detailed Description
Transformer that holds an arbitrary number of sub-transformations.
Definition at line 38 of file Pipeline.h.
Constructor & Destructor Documentation
PipelineTransformer() [1/2]
template<typename... Args> souffle::ast::transform::PipelineTransformer::PipelineTransformer (Args... args) inline
Definition at line 41 of file Pipeline.h.
References pipeline.
Referenced by clone().
{
         Own<Transformer> tmp[] = {std::move(args)...};
         for (auto& cur : tmp) {
             pipeline.push_back(std::move(cur));
         }
     }
PipelineTransformer() [2/2]
souffle::ast::transform::PipelineTransformer::PipelineTransformer (VecOwn< Transformer > pipeline) inline
Definition at line 48 of file Pipeline.h.
 : pipeline(std::move(pipeline)) {}
Member Function Documentation
clone()
PipelineTransformer* souffle::ast::transform::PipelineTransformer::clone () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 87 of file Pipeline.h.
References souffle::clone(), pipeline, and PipelineTransformer().
{
         VecOwn<Transformer> transformers;
         for (const auto& transformer : pipeline) {
             transformers.push_back(souffle::clone(transformer));
         }
         return new PipelineTransformer(std::move(transformers));
     }
disableTransformers()
void souffle::ast::transform::PipelineTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 73 of file Pipeline.h.
References i, and pipeline.
{
         for (auto& i : pipeline) {
             if (auto* mt = dynamic_cast<MetaTransformer*>(i.get())) {
                 mt->disableTransformers(transforms);
             } else if (transforms.find(i->getName()) != transforms.end()) {
                 i = mk<NullTransformer>();
             }
         }
     }
getName()
std::string souffle::ast::transform::PipelineTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 83 of file Pipeline.h.
{
         return "PipelineTransformer";
     }
getSubtransformers()
std::vector<Transformer*> souffle::ast::transform::PipelineTransformer::getSubtransformers () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 50 of file Pipeline.h.
References pipeline, and souffle::toPtrVector().
{
         return toPtrVector(pipeline);
     }
setDebugReport()
void souffle::ast::transform::PipelineTransformer::setDebugReport () inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 54 of file Pipeline.h.
References i, and pipeline.
{
         for (auto& i : pipeline) {
             if (auto* mt = dynamic_cast<MetaTransformer*>(i.get())) {
                 mt->setDebugReport();
             } else {
                 i = mk<DebugReporter>(std::move(i));
             }
         }
     }
setVerbosity()
void souffle::ast::transform::PipelineTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 64 of file Pipeline.h.
References pipeline, and souffle::ast::transform::MetaTransformer::verbose.
{
         this->verbose = verbose;
         for (auto& cur : pipeline) {
             if (auto* mt = dynamic_cast<MetaTransformer*>(cur.get())) {
                 mt->setVerbosity(verbose);
             }
         }
     }
transform()
bool souffle::ast::transform::PipelineTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
Implements souffle::ast::transform::Transformer.
Definition at line 97 of file Pipeline.h.
References souffle::ast::transform::MetaTransformer::applySubtransformer().
Referenced by souffle::ast::transform::MagicSetTransformer::transform().
{
         bool changed = false;
         for (auto& transformer : pipeline) {
             changed |= applySubtransformer(translationUnit, transformer.get());
         }
         return changed;
     }
Field Documentation
pipeline
VecOwn<Transformer> souffle::ast::transform::PipelineTransformer::pipeline protected
Definition at line 96 of file Pipeline.h.
Referenced by clone(), disableTransformers(), getSubtransformers(), PipelineTransformer(), setDebugReport(), and setVerbosity().
The documentation for this class was generated from the following file:
ast/transform/Pipeline.h