souffle: souffle::ast::transform::UserDefinedFunctorsTransformer Class Reference
souffle::ast::transform::UserDefinedFunctorsTransformer Class Reference
Transformation that passes the type information from user functors declaration to functors instances.
#include <UserDefinedFunctors.h>
Public Member Functions
UserDefinedFunctorsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation that passes the type information from user functors declaration to functors instances.
Definition at line 30 of file UserDefinedFunctors.h.
Member Function Documentation
clone()
UserDefinedFunctorsTransformer* souffle::ast::transform::UserDefinedFunctorsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 36 of file UserDefinedFunctors.h.
References transform().
{
         return new UserDefinedFunctorsTransformer();
     }
getName()
std::string souffle::ast::transform::UserDefinedFunctorsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 32 of file UserDefinedFunctors.h.
{
         return "UserDefinedFunctorsTransformer";
     }
transform()
bool souffle::ast::transform::UserDefinedFunctorsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 30 of file UserDefinedFunctors.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Program::apply(), souffle::ast::FunctorDeclaration::getArgsTypes(), souffle::ast::FunctorDeclaration::getArity(), souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::Program::getFunctorDeclarations(), souffle::getIf(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::FunctorDeclaration::getReturnType(), and souffle::ast::FunctorDeclaration::isStateful().
Referenced by clone().
{
     struct UserFunctorRewriter : public NodeMapper {
         mutable bool changed{false};
         const Program& program;
         ErrorReport& report;
         UserFunctorRewriter(const Program& program, ErrorReport& report) : program(program), report(report){};
         Own<Node> operator()(Own<Node> node) const override {
             node->apply(*this);
             if (auto* userFunctor = dynamic_cast<UserDefinedFunctor*>(node.get())) {
                 const FunctorDeclaration* functorDeclaration =
                         getIf(program.getFunctorDeclarations(), [&](const FunctorDeclaration* current) {
                             return current->getName() == userFunctor->getName();
                         });
                 // Check if the functor has been declared
                 if (functorDeclaration == nullptr) {
                     report.addError("User-defined functor hasn't been declared", userFunctor->getSrcLoc());
                     return node;
                 }
                 // Check arity correctness.
                 if (functorDeclaration->getArity() != userFunctor->getArguments().size()) {
                     report.addError("Mismatching number of arguments of functor", userFunctor->getSrcLoc());
                     return node;
                 }
                 // Set types of functor instance based on its declaration.
                 userFunctor->setTypes(functorDeclaration->getArgsTypes(), functorDeclaration->getReturnType(),
                         functorDeclaration->isStateful());
                 changed = true;
             }
             return node;
         }
     };
     Program& program = translationUnit.getProgram();
     UserFunctorRewriter update(program, translationUnit.getErrorReport());
     program.apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/UserDefinedFunctors.h
ast/transform/UserDefinedFunctors.cpp