souffle: souffle::ram::transform::IndexedInequalityTransformer Class Reference
souffle::ram::transform::IndexedInequalityTransformer Class Reference
Removes Inequalities from Indexed Operations and replaces them with a Filter Operation and empty Indexed Operations are coverted to their Non-Indexed semantic equivalent.
#include <IndexedInequality.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool transformIndexToFilter (Program &program)
Converts a box query into a corresponding partial box query operation.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
analysis::IndexAnalysis * idxAnalysis
Detailed Description
Removes Inequalities from Indexed Operations and replaces them with a Filter Operation and empty Indexed Operations are coverted to their Non-Indexed semantic equivalent.
If there exists inequality constraints in an Indexed Operation, these constraints will be replaced with a semantically equivalent nested Filter Operation.
Furthermore, if after removing all of these inequality constraints from the Indexed Operation we may find that the Indexed Operation is empty (no constraints). This occurs in the case where an Indexed Operation is composed entirely of inequality constraints. In this situation, the Indexed Operation is empty and replaced with a semantically equivalent Operation. i.e. IndexScan -> Scan
For example,
QUERY
 ...
 FOR t1 IN X ON INDEX t1.x < 10 AND t1.y > 20
   ... // t1 only has inequality constraints placed on it
will be rewritten to
QUERY
 ...
     FOR t1 in X ON INDEX // empty index since all inequalities have been removed
          IF t1.x < 10 AND t1.y > 20
              // replaced with a semantically equivalent filter
    ...
will be rewritten to
QUERY
 ...
     FOR t1 in X // Scan instead of IndexScan
          IF t1.x < 10 AND t1.y > 20
              // replaced with a semantically equivalent filter
    ...
Definition at line 71 of file IndexedInequality.h.
Member Function Documentation
getName()
std::string souffle::ram::transform::IndexedInequalityTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 73 of file IndexedInequality.h.
References transformIndexToFilter().
{
         return "IndexedInequalityTransformer";
     }
transform()
bool souffle::ram::transform::IndexedInequalityTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 83 of file IndexedInequality.h.
References souffle::ram::TranslationUnit::getAnalysis(), souffle::ram::TranslationUnit::getProgram(), idxAnalysis, and transformIndexToFilter().
{
         idxAnalysis = translationUnit.getAnalysis<analysis::IndexAnalysis>();
         return transformIndexToFilter(translationUnit.getProgram());
     }
transformIndexToFilter()
bool souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter (Program & program)
Converts a box query into a corresponding partial box query operation.
This will turn every box query into a filter operation.
Definition at line 37 of file IndexedInequality.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::clone(), souffle::fatal(), souffle::filter(), souffle::ram::analysis::MinIndexSelection::getAttributesToDischarge(), souffle::getGreaterEqualConstraint(), souffle::ram::analysis::IndexAnalysis::getIndexes(), souffle::getLessEqualConstraint(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), i, idxAnalysis, souffle::ram::isUndefValue(), souffle::ram::makeLambdaRamMapper(), p, and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     // helper for collecting conditions from filter operations
     auto addCondition = [](Own<Condition> condition, Own<Condition> c) -> Own<Condition> {
         if (condition == nullptr) {
             return c;
         } else {
             return mk<Conjunction>(std::move(condition), std::move(c));
         }
     };
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> indexToFilterRewriter = [&](Own<Node> node) -> Own<Node> {
             // find a IndexOperation
             if (const IndexOperation* indexOperation = dynamic_cast<IndexOperation*>(node.get())) {
                 auto indexSelection = idxAnalysis->getIndexes(indexOperation->getRelation());
                 auto attributesToDischarge = indexSelection.getAttributesToDischarge(
                         idxAnalysis->getSearchSignature(indexOperation), indexOperation->getRelation());
                 auto pattern = indexOperation->getRangePattern();
                 Own<Condition> condition;
                 RamPattern updatedPattern;
                 for (Expression* p : indexOperation->getRangePattern().first) {
                     updatedPattern.first.emplace_back(p->clone());
                 }
                 for (Expression* p : indexOperation->getRangePattern().second) {
                     updatedPattern.second.emplace_back(p->clone());
                 }
                 for (auto i : attributesToDischarge) {
                     // move constraints out of the indexed inequality and into a conjuction
                     Own<Constraint> lowerBound;
                     Own<Constraint> upperBound;
                     changed = true;
                     if (!isUndefValue(pattern.first[i])) {
                         lowerBound =
                                 mk<Constraint>(getGreaterEqualConstraint(
                                                        indexOperation->getRelation().getAttributeTypes()[i]),
                                         mk<TupleElement>(indexOperation->getTupleId(), i),
                                         souffle::clone(pattern.first[i]));
                         condition = addCondition(std::move(condition), souffle::clone(lowerBound));
                     }
                     if (!isUndefValue(pattern.second[i])) {
                         upperBound = mk<Constraint>(
                                 getLessEqualConstraint(indexOperation->getRelation().getAttributeTypes()[i]),
                                 mk<TupleElement>(indexOperation->getTupleId(), i),
                                 souffle::clone(pattern.second[i]));
                         condition = addCondition(std::move(condition), souffle::clone(upperBound));
                     }
                     // reset the bounds
                     updatedPattern.first[i] = mk<UndefValue>();
                     updatedPattern.second[i] = mk<UndefValue>();
                 }
                 if (condition) {
                     auto nestedOp = souffle::clone(&indexOperation->getOperation());
                     auto filter = mk<Filter>(souffle::clone(condition), souffle::clone(nestedOp));
                     // need to rewrite the node with the same index operation
                     if (const IndexScan* iscan = dynamic_cast<IndexScan*>(node.get())) {
                         node = mk<IndexScan>(mk<RelationReference>(&iscan->getRelation()),
                                 iscan->getTupleId(), std::move(updatedPattern), std::move(filter),
                                 iscan->getProfileText());
                     } else if (const ParallelIndexScan* pscan =
                                        dynamic_cast<ParallelIndexScan*>(node.get())) {
                         node = mk<ParallelIndexScan>(mk<RelationReference>(&pscan->getRelation()),
                                 pscan->getTupleId(), std::move(updatedPattern), std::move(filter),
                                 pscan->getProfileText());
                     } else if (const IndexChoice* ichoice = dynamic_cast<IndexChoice*>(node.get())) {
                         node = mk<IndexChoice>(mk<RelationReference>(&ichoice->getRelation()),
                                 ichoice->getTupleId(), souffle::clone(&ichoice->getCondition()),
                                 std::move(updatedPattern), std::move(filter), ichoice->getProfileText());
                     } else if (const IndexAggregate* iagg = dynamic_cast<IndexAggregate*>(node.get())) {
                         // in the case of an aggregate we must strengthen the condition of the aggregate
                         // it doesn't make sense to nest a filter operation because the aggregate needs the
                         // condition in its scope
                         auto strengthenedCondition = addCondition(
                                 Own<Condition>(souffle::clone(&iagg->getCondition())), std::move(condition));
                         node = mk<IndexAggregate>(std::move(nestedOp), iagg->getFunction(),
                                 mk<RelationReference>(&iagg->getRelation()),
                                 souffle::clone(&iagg->getExpression()), std::move(strengthenedCondition),
                                 std::move(updatedPattern), iagg->getTupleId());
                     } else {
                         fatal("New IndexOperation subclass found but not supported while making index.");
                     }
                 }
             }
             node->apply(makeLambdaRamMapper(indexToFilterRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(indexToFilterRewriter));
     });
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> removeEmptyIndexRewriter = [&](Own<Node> node) -> Own<Node> {
             // find an IndexOperation
             if (const IndexOperation* indexOperation = dynamic_cast<IndexOperation*>(node.get())) {
                 auto pattern = indexOperation->getRangePattern();
                 size_t length = pattern.first.size();
                 bool foundRealIndexableOperation = false;
                 for (size_t i = 0; i < length; ++i) {
                     // if both bounds are undefined we don't have a box query
                     if (isUndefValue(pattern.first[i]) && isUndefValue(pattern.second[i])) {
                         continue;
                     }
                     // if lower and upper bounds are equal its also not a box query
                     foundRealIndexableOperation = true;
                     break;
                 }
                 if (!foundRealIndexableOperation) {
                     // need to rewrite the node with a semantically equivalent operation to get rid of the
                     // index operation i.e. IndexScan with no indexable attributes -> Scan
                     if (const IndexScan* iscan = dynamic_cast<IndexScan*>(node.get())) {
                         node = mk<Scan>(mk<RelationReference>(&iscan->getRelation()), iscan->getTupleId(),
                                 souffle::clone(&iscan->getOperation()), iscan->getProfileText());
                     } else if (const ParallelIndexScan* pscan =
                                        dynamic_cast<ParallelIndexScan*>(node.get())) {
                         node = mk<ParallelScan>(mk<RelationReference>(&pscan->getRelation()),
                                 pscan->getTupleId(), souffle::clone(&pscan->getOperation()),
                                 pscan->getProfileText());
                     } else if (const IndexChoice* ichoice = dynamic_cast<IndexChoice*>(node.get())) {
                         node = mk<Choice>(mk<RelationReference>(&ichoice->getRelation()),
                                 ichoice->getTupleId(), souffle::clone(&ichoice->getCondition()),
                                 souffle::clone(&ichoice->getOperation()), ichoice->getProfileText());
                     } else if (const IndexAggregate* iagg = dynamic_cast<IndexAggregate*>(node.get())) {
                         node = mk<Aggregate>(souffle::clone(&iagg->getOperation()), iagg->getFunction(),
                                 mk<RelationReference>(&iagg->getRelation()),
                                 souffle::clone(&iagg->getExpression()), souffle::clone(&iagg->getCondition()),
                                 iagg->getTupleId());
                     } else {
                         fatal("New IndexOperation subclass found but not supported while transforming "
                               "index.");
                     }
                 }
             }
             node->apply(makeLambdaRamMapper(removeEmptyIndexRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(removeEmptyIndexRewriter));
     });
     return changed;
 }
Field Documentation
idxAnalysis
analysis::IndexAnalysis* souffle::ram::transform::IndexedInequalityTransformer::idxAnalysis protected
Definition at line 88 of file IndexedInequality.h.
Referenced by transform(), and transformIndexToFilter().
The documentation for this class was generated from the following files:
ram/transform/IndexedInequality.h
ram/transform/IndexedInequality.cpp