souffle: souffle::ast::transform::FoldAnonymousRecords Class Reference
souffle::ast::transform::FoldAnonymousRecords Class Reference
Transformation pass that removes (binary) constraints on the anonymous records.
#include <FoldAnonymousRecords.h>
Public Member Functions
FoldAnonymousRecords * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool containsValidRecordConstraint (const Clause &)
Determine if the clause contains at least one binary constraint which can be expanded.
VecOwn< Literal > expandRecordBinaryConstraint (const BinaryConstraint &)
Expand constraint on records position-wise.
bool isValidRecordConstraint (const Literal *literal)
Determine if binary constraint can be expanded.
bool transform (TranslationUnit &translationUnit) override
void transformClause (const Clause &clause, VecOwn< Clause > &newClauses)
Process a single clause.
Detailed Description
Transformation pass that removes (binary) constraints on the anonymous records.
After resolving aliases this is equivalent to completely removing anonymous records.
e.g. [a, b, c] = [x, y, z] → a = x, b = y, c = z. [a, b, c] != [x, y, z] → a != x b != y c != z (expanded to three new clauses)
In a single pass, in case of equalities a transformation expands a single level of records in every clause. (e.g. [[a]] = [[1]] => [a] = [1]) In case of inequalities, it expands at most a single inequality in every clause
This transformation does not resolve aliases. E.g. A = [a, b], A = [c, d] Thus it should be called in conjunction with ResolveAnonymousRecordAliases.
Definition at line 48 of file FoldAnonymousRecords.h.
Member Function Documentation
clone()
FoldAnonymousRecords* souffle::ast::transform::FoldAnonymousRecords::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 54 of file FoldAnonymousRecords.h.
References containsValidRecordConstraint(), expandRecordBinaryConstraint(), isValidRecordConstraint(), transform(), and transformClause().
{
         return new FoldAnonymousRecords();
     }
containsValidRecordConstraint()
bool souffle::ast::transform::FoldAnonymousRecords::containsValidRecordConstraint (const Clause & clause) private
Determine if the clause contains at least one binary constraint which can be expanded.
Definition at line 66 of file FoldAnonymousRecords.cpp.
References souffle::contains(), isValidRecordConstraint(), and souffle::ast::visitDepthFirst().
Referenced by clone(), and transform().
{
     bool contains = false;
     visitDepthFirst(clause, [&](const BinaryConstraint& binary) {
         contains = (contains || isValidRecordConstraint(&binary));
     });
     return contains;
 }
expandRecordBinaryConstraint()
VecOwn< Literal > souffle::ast::transform::FoldAnonymousRecords::expandRecordBinaryConstraint (const BinaryConstraint & constraint) private
Expand constraint on records position-wise.
eg. [1, 2, 3] = [a, b, c] => vector(1 = a, 2 = b, 3 = c) [x, y, z] != [a, b, c] => vector(x != a, x != b, z != c)
Procedure assumes that argument has a valid operation, that children are of type RecordInit and that the size of both sides is the same
Definition at line 74 of file FoldAnonymousRecords.cpp.
References souffle::clone(), souffle::ast::BinaryConstraint::getLHS(), souffle::ast::BinaryConstraint::getOperator(), souffle::ast::BinaryConstraint::getRHS(), i, and souffle::isEqConstraint().
Referenced by clone(), and transformClause().
{
     VecOwn<Literal> replacedContraint;
     const auto* left = dynamic_cast<RecordInit*>(constraint.getLHS());
     const auto* right = dynamic_cast<RecordInit*>(constraint.getRHS());
     assert(left != nullptr && "Non-record passed to record method");
     assert(right != nullptr && "Non-record passed to record method");
     auto leftChildren = left->getArguments();
     auto rightChildren = right->getArguments();
     assert(leftChildren.size() == rightChildren.size());
     // [a, b..] = [c, d...] → a = c, b = d ...
     for (size_t i = 0; i < leftChildren.size(); ++i) {
         auto newConstraint = mk<BinaryConstraint>(
                 constraint.getOperator(), souffle::clone(leftChildren[i]), souffle::clone(rightChildren[i]));
         replacedContraint.push_back(std::move(newConstraint));
     }
     // Handle edge case. Empty records.
     if (leftChildren.size() == 0) {
         if (isEqConstraint(constraint.getOperator())) {
             replacedContraint.emplace_back(new BooleanConstraint(true));
         } else {
             replacedContraint.emplace_back(new BooleanConstraint(false));
         }
     }
     return replacedContraint;
 }
getName()
std::string souffle::ast::transform::FoldAnonymousRecords::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 50 of file FoldAnonymousRecords.h.
{
         return "FoldAnonymousRecords";
     }
isValidRecordConstraint()
bool souffle::ast::transform::FoldAnonymousRecords::isValidRecordConstraint (const Literal * literal) private
Determine if binary constraint can be expanded.
Definition at line 37 of file FoldAnonymousRecords.cpp.
References souffle::ast::BinaryConstraint::getLHS(), souffle::isEqConstraint(), and souffle::negatedConstraintOp().
Referenced by clone(), containsValidRecordConstraint(), and transformClause().
{
     auto constraint = dynamic_cast<const BinaryConstraint*>(literal);
     if (constraint == nullptr) {
         return false;
     }
     const auto* left = constraint->getLHS();
     const auto* right = constraint->getRHS();
     const auto* leftRecord = dynamic_cast<const RecordInit*>(left);
     const auto* rightRecord = dynamic_cast<const RecordInit*>(right);
     // Check if arguments are records records.
     if ((leftRecord == nullptr) || (rightRecord == nullptr)) {
         return false;
     }
     // Check if records are of the same size.
     if (leftRecord->getChildNodes().size() != rightRecord->getChildNodes().size()) {
         return false;
     }
     // Check if operator is "=" or "!="
     auto op = constraint->getOperator();
     return isEqConstraint(op) || isEqConstraint(negatedConstraintOp(op));
 }
transform()
bool souffle::ast::transform::FoldAnonymousRecords::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 160 of file FoldAnonymousRecords.cpp.
References containsValidRecordConstraint(), souffle::ast::Program::getClauses(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::setClauses(), and transformClause().
Referenced by clone().
{
     bool changed = false;
     Program& program = translationUnit.getProgram();
     VecOwn<Clause> newClauses;
     for (const auto* clause : program.getClauses()) {
         if (containsValidRecordConstraint(*clause)) {
             changed = true;
             transformClause(*clause, newClauses);
         } else {
             newClauses.emplace_back(clause->clone());
         }
     }
     // Update Program.
     if (changed) {
         program.setClauses(std::move(newClauses));
     }
     return changed;
 }
transformClause()
void souffle::ast::transform::FoldAnonymousRecords::transformClause (const Clause & clause, VecOwn< Clause > & newClauses) private
Process a single clause.
clause Clause to be processed.
Parameters
newClauses a destination for the newly produced clauses.
Definition at line 106 of file FoldAnonymousRecords.cpp.
References souffle::clone(), expandRecordBinaryConstraint(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::BinaryConstraint::getOperator(), souffle::isEqConstraint(), and isValidRecordConstraint().
Referenced by clone(), and transform().
{
     // If we have an inequality constraint, we need to create new clauses
     // At most one inequality constraint will be expanded in a single pass.
     BinaryConstraint* neqConstraint = nullptr;
     VecOwn<Literal> newBody;
     for (auto* literal : clause.getBodyLiterals()) {
         if (isValidRecordConstraint(literal)) {
             const BinaryConstraint& constraint = dynamic_cast<BinaryConstraint&>(*literal);
             // Simple case, [a_0, ..., a_n] = [b_0, ..., b_n]
             if (isEqConstraint(constraint.getOperator())) {
                 auto transformedLiterals = expandRecordBinaryConstraint(constraint);
                 std::move(std::begin(transformedLiterals), std::end(transformedLiterals),
                         std::back_inserter(newBody));
                 // else if: Case [a_0, ..., a_n] != [b_0, ..., b_n].
                 // track single such case, it will be expanded in the end.
             } else if (neqConstraint == nullptr) {
                 neqConstraint = dynamic_cast<BinaryConstraint*>(literal);
                 // Else: repeated inequality.
             } else {
                 newBody.push_back(souffle::clone(literal));
             }
             // else, we simply copy the literal.
         } else {
             newBody.push_back(souffle::clone(literal));
         }
     }
     // If no inequality: create a single modified clause.
     if (neqConstraint == nullptr) {
         auto newClause = souffle::clone(&clause);
         newClause->setBodyLiterals(std::move(newBody));
         newClauses.emplace_back(std::move(newClause));
         // Else: For each pair in negation, we need an extra clause.
     } else {
         auto transformedLiterals = expandRecordBinaryConstraint(*neqConstraint);
         for (auto it = begin(transformedLiterals); it != end(transformedLiterals); ++it) {
             auto newClause = souffle::clone(&clause);
             auto copyBody = souffle::clone(newBody);
             copyBody.push_back(std::move(*it));
             newClause->setBodyLiterals(std::move(copyBody));
             newClauses.push_back(std::move(newClause));
         }
     }
 }
The documentation for this class was generated from the following files:
ast/transform/FoldAnonymousRecords.h
ast/transform/FoldAnonymousRecords.cpp