souffle: souffle::ast::analysis::TypeEnvironmentAnalysis Class Reference
souffle::ast::analysis::TypeEnvironmentAnalysis Class Reference
#include <TypeEnvironment.h>
Public Member Functions
const std::set< QualifiedName > & getPrimitiveTypesInUnion (const QualifiedName &identifier) const
const TypeEnvironment & getTypeEnvironment () const
bool isCyclic (const QualifiedName &identifier) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeEnvironmentAnalysis ()
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "type-environment"
Private Member Functions
const Type * createType (const QualifiedName &typeName, const std::map< QualifiedName, const ast::Type *> &nameToType)
Recursively create a type in env, that is first create its base types and then the type itself.
Private Attributes
std::set< QualifiedName > cyclicTypes
TypeEnvironment env
std::map< QualifiedName, std::set< QualifiedName > > primitiveTypesInUnions
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 32 of file TypeEnvironment.h.
Constructor & Destructor Documentation
TypeEnvironmentAnalysis()
souffle::ast::analysis::TypeEnvironmentAnalysis::TypeEnvironmentAnalysis () inline
Definition at line 36 of file TypeEnvironment.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
createType()
const Type * souffle::ast::analysis::TypeEnvironmentAnalysis::createType (const QualifiedName & typeName, const std::map< QualifiedName, const ast::Type *> & nameToType) private
Recursively create a type in env, that is first create its base types and then the type itself.
Definition at line 141 of file TypeEnvironment.cpp.
References souffle::fatal(), tinyformat::format(), and souffle::ast::analysis::RecordType::setFields().
Referenced by run().
{
     // base case
     if (env.isType(typeName)) {
         return &env.getType(typeName);
     }
     // Handle undeclared type in the definition of another type.
     auto iterToType = nameToType.find(typeName);
     if (iterToType == nameToType.end()) {
         return nullptr;
     }
     const auto& astType = iterToType->second;
     if (isA<ast::SubsetType>(astType)) {
         // First create a base type.
         auto* baseType = createType(as<ast::SubsetType>(astType)->getBaseType(), nameToType);
         if (baseType == nullptr) {
             return nullptr;
         }
         // Subset of a record is a special case.
         if (isA<RecordType>(baseType)) {
             return &env.createType<SubsetRecordType>(typeName, *as<RecordType>(baseType));
         }
         return &env.createType<SubsetType>(typeName, *baseType);
     } else if (isA<ast::UnionType>(astType)) {
         // Create all elements and then the type itself
         std::vector<const Type*> elements;
         for (const auto& element : as<ast::UnionType>(astType)->getTypes()) {
             auto* elementType = createType(element, nameToType);
             if (elementType == nullptr) {
                 return nullptr;
             }
             elements.push_back(elementType);
         }
         return &env.createType<UnionType>(typeName, elements);
     } else if (isA<ast::RecordType>(astType)) {
         // Create anonymous base type first.
         // The types need to be initialized upfront,
         // because we may have mutually recursive record definitions.
         auto& recordBase = env.createType<RecordType>(tfm::format("__%sConstant", typeName));
         auto& recordType = env.createType<SubsetRecordType>(typeName, recordBase);
         std::vector<const Type*> elements;
         for (const auto* field : as<ast::RecordType>(astType)->getFields()) {
             if (field->getTypeName() == typeName) {
                 elements.push_back(&recordBase);
                 continue;
             }
             auto* elementType = createType(field->getTypeName(), nameToType);
             if (elementType == nullptr) {
                 return nullptr;
             }
             elements.push_back(elementType);
         }
         recordBase.setFields(elements);
         std::replace(elements.begin(), elements.end(), dynamic_cast<Type*>(&recordBase),
                 dynamic_cast<Type*>(&recordType));
         recordType.setFields(std::move(elements));
         return &recordType;
     } else if (isA<ast::AlgebraicDataType>(astType)) {
         // ADT can be recursive so its need to be forward initialized
         auto& adt = env.createType<AlgebraicDataType>(typeName);
         std::vector<AlgebraicDataType::Branch> elements;
         // Create and collect branches types.
         for (auto* branch : as<ast::AlgebraicDataType>(astType)->getBranches()) {
             std::vector<const Type*> branchTypes;
             for (auto* attr : branch->getFields()) {
                 auto* type = createType(attr->getTypeName(), nameToType);
                 if (type == nullptr) return nullptr;
                 branchTypes.push_back(type);
             }
             elements.push_back({branch->getConstructor(), std::move(branchTypes)});
         }
         adt.setBranches(std::move(elements));
         return &adt;
     } else {
         fatal("unsupported type construct: %s", typeid(*astType).name());
     }
 }
getPrimitiveTypesInUnion()
const std::set<QualifiedName>& souffle::ast::analysis::TypeEnvironmentAnalysis::getPrimitiveTypesInUnion (const QualifiedName & identifier) const inline
Definition at line 46 of file TypeEnvironment.h.
References primitiveTypesInUnions.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkUnionType().
{
         return primitiveTypesInUnions.at(identifier);
     }
getTypeEnvironment()
const TypeEnvironment& souffle::ast::analysis::TypeEnvironmentAnalysis::getTypeEnvironment () const inline
Definition at line 42 of file TypeEnvironment.h.
References env.
{
         return env;
     }
isCyclic()
bool souffle::ast::analysis::TypeEnvironmentAnalysis::isCyclic (const QualifiedName & identifier) const inline
Definition at line 50 of file TypeEnvironment.h.
References souffle::contains(), and cyclicTypes.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkSubsetType(), souffle::ast::transform::SemanticCheckerImpl::checkUnionType(), and run().
{
         return contains(cyclicTypes, identifier);
     }
print()
void souffle::ast::analysis::TypeEnvironmentAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 236 of file TypeEnvironment.cpp.
Referenced by TypeEnvironmentAnalysis().
{
     env.print(os);
 }
run()
void souffle::ast::analysis::TypeEnvironmentAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 114 of file TypeEnvironment.cpp.
References createType(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getTypes(), and isCyclic().
Referenced by TypeEnvironmentAnalysis().
{
     const Program& program = translationUnit.getProgram();
     auto rawProgramTypes = program.getTypes();
     Graph<QualifiedName> typeDependencyGraph{createTypeDependencyGraph(rawProgramTypes)};
     cyclicTypes = analyseCyclicTypes(typeDependencyGraph, rawProgramTypes);
     primitiveTypesInUnions = analysePrimitiveTypesInUnion(typeDependencyGraph, rawProgramTypes, env);
     std::map<QualifiedName, const ast::Type*> nameToType;
     // Filter redefined primitive types and cyclic types.
     std::vector<ast::Type*> programTypes;
     for (auto* type : program.getTypes()) {
         if (env.isType(type->getQualifiedName()) || isCyclic(type->getQualifiedName())) {
             continue;
         }
         programTypes.push_back(type);
         nameToType.insert({type->getQualifiedName(), type});
     }
     for (const auto* astType : programTypes) {
         createType(astType->getQualifiedName(), nameToType);
     }
 }
Field Documentation
cyclicTypes
std::set<QualifiedName> souffle::ast::analysis::TypeEnvironmentAnalysis::cyclicTypes private
Definition at line 57 of file TypeEnvironment.h.
Referenced by isCyclic().
env
TypeEnvironment souffle::ast::analysis::TypeEnvironmentAnalysis::env private
Definition at line 55 of file TypeEnvironment.h.
Referenced by getTypeEnvironment().
name
constexpr const char* souffle::ast::analysis::TypeEnvironmentAnalysis::name = "type-environment" static
Definition at line 34 of file TypeEnvironment.h.
primitiveTypesInUnions
std::map<QualifiedName, std::set<QualifiedName> > souffle::ast::analysis::TypeEnvironmentAnalysis::primitiveTypesInUnions private
Definition at line 56 of file TypeEnvironment.h.
Referenced by getPrimitiveTypesInUnion().
The documentation for this class was generated from the following files:
ast/analysis/TypeEnvironment.h
ast/analysis/TypeEnvironment.cpp