souffle: souffle::ram::TranslationUnit Class Reference
souffle::ram::TranslationUnit Class Reference
Translating a RAM program.
#include <TranslationUnit.h>
Public Member Functions
std::set< const analysis::Analysis * > getAliveAnalyses () const
get the set of alive analyses of the translation unit
template<class Analysis >
Analysis * getAnalysis () const
templated method to compute/retrieve an analysis for a translation unit
DebugReport & getDebugReport ()
get debug report
const DebugReport & getDebugReport () const
get const debug report
ErrorReport & getErrorReport ()
get error report
const ErrorReport & getErrorReport () const
get error report
const Program & getProgram () const
get the RAM Program of the translation unit
Program & getProgram ()
get the RAM Program of the translation unit
souffle::SymbolTable & getSymbolTable ()
get symbol table
void invalidateAnalyses ()
throw away all alive analyses of the translation unit
TranslationUnit (Own< Program > prog, SymbolTable sym, ErrorReport &e, DebugReport &d)
virtual ~TranslationUnit ()=default
Protected Attributes
std::map< std::string, Own< analysis::Analysis > > analyses
DebugReport & debugReport
ErrorReport & errorReport
Own< Program > program
souffle::SymbolTable symbolTable
Detailed Description
Translating a RAM program.
Comprises the program, symbol table, error report and debug report
Definition at line 44 of file TranslationUnit.h.
Constructor & Destructor Documentation
TranslationUnit()
souffle::ram::TranslationUnit::TranslationUnit (Own< Program > prog, SymbolTable sym, ErrorReport & e, DebugReport & d) inline
Definition at line 46 of file TranslationUnit.h.
References program, and ~TranslationUnit().
             : program(std::move(prog)), symbolTable(std::move(sym)), errorReport(e), debugReport(d) {
         assert(program != nullptr && "program is a null-pointer");
     }
~TranslationUnit()
virtual souffle::ram::TranslationUnit::~TranslationUnit () virtual default
Referenced by TranslationUnit().
Member Function Documentation
getAliveAnalyses()
std::set<const analysis::Analysis*> souffle::ram::TranslationUnit::getAliveAnalyses () const inline
get the set of alive analyses of the translation unit
Definition at line 82 of file TranslationUnit.h.
References analyses.
{
         std::set<const analysis::Analysis*> result;
         for (auto const& a : analyses) {
             result.insert(a.second.get());
         }
         return result;
     }
getAnalysis()
template<class Analysis > Analysis* souffle::ram::TranslationUnit::getAnalysis () const inline
templated method to compute/retrieve an analysis for a translation unit
Definition at line 55 of file TranslationUnit.h.
References souffle::DebugReport::addSection(), analyses, souffle::Global::config(), and debugReport.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::ReportIndexTransformer::transform(), souffle::ram::transform::HoistAggregateTransformer::transform(), souffle::ram::transform::ReorderConditionsTransformer::transform(), souffle::ram::transform::IndexedInequalityTransformer::transform(), souffle::ram::transform::HoistConditionsTransformer::transform(), souffle::ram::transform::ChoiceConversionTransformer::transform(), and souffle::ram::transform::MakeIndexTransformer::transform().
{
         static const bool debug = Global::config().has("debug-report");
         std::string name = Analysis::name;
         auto it = analyses.find(name);
         if (it == analyses.end()) {
             // analysis does not exist yet, create instance and run it.
             auto analysis = mk<Analysis>(Analysis::name);
             analysis->run(*this);
             // output analysis in debug report
             if (debug) {
                 std::stringstream ramAnalysisStr;
                 ramAnalysisStr << *analysis;
                 if (!ramAnalysisStr.str().empty()) {
                     debugReport.addSection(
                             analysis->getName(), "RAM Analysis " + analysis->getName(), ramAnalysisStr.str());
                 }
             }
             // check it hasn't been created by someone else, and insert if not
             it = analyses.find(name);
             if (it == analyses.end()) {
                 analyses[name] = std::move(analysis);
             }
         }
         return dynamic_cast<Analysis*>(analyses[name].get());
     }
getDebugReport() [1/2]
DebugReport& souffle::ram::TranslationUnit::getDebugReport () inline
get debug report
Definition at line 121 of file TranslationUnit.h.
References debugReport.
Referenced by souffle::ram::transform::Transformer::apply().
{
         return debugReport;
     }
getDebugReport() [2/2]
const DebugReport& souffle::ram::TranslationUnit::getDebugReport () const inline
get const debug report
Definition at line 126 of file TranslationUnit.h.
References debugReport.
{
         return debugReport;
     }
getErrorReport() [1/2]
ErrorReport& souffle::ram::TranslationUnit::getErrorReport () inline
get error report
Definition at line 111 of file TranslationUnit.h.
References errorReport.
Referenced by souffle::ram::transform::Transformer::apply().
{
         return errorReport;
     }
getErrorReport() [2/2]
const ErrorReport& souffle::ram::TranslationUnit::getErrorReport () const inline
get error report
Definition at line 116 of file TranslationUnit.h.
References errorReport.
{
         return errorReport;
     }
getProgram() [1/2]
const Program& souffle::ram::TranslationUnit::getProgram () const inline
get the RAM Program of the translation unit
Definition at line 96 of file TranslationUnit.h.
References program.
Referenced by souffle::ram::transform::Transformer::apply(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::IndexAnalysis::run(), souffle::ram::transform::HoistAggregateTransformer::transform(), souffle::ram::transform::ParallelTransformer::transform(), souffle::ram::transform::TupleIdTransformer::transform(), souffle::ram::transform::ExpandFilterTransformer::transform(), souffle::ram::transform::CollapseFiltersTransformer::transform(), souffle::ram::transform::ReorderFilterBreak::transform(), souffle::ram::transform::EliminateDuplicatesTransformer::transform(), souffle::ram::transform::ReorderConditionsTransformer::transform(), souffle::ram::transform::IfConversionTransformer::transform(), souffle::ram::transform::IndexedInequalityTransformer::transform(), souffle::ram::transform::HoistConditionsTransformer::transform(), souffle::ram::transform::ChoiceConversionTransformer::transform(), and souffle::ram::transform::MakeIndexTransformer::transform().
{
         return *program;
     }
getProgram() [2/2]
Program& souffle::ram::TranslationUnit::getProgram () inline
get the RAM Program of the translation unit
Definition at line 101 of file TranslationUnit.h.
References program.
{
         return *program;
     }
getSymbolTable()
souffle::SymbolTable& souffle::ram::TranslationUnit::getSymbolTable () inline
get symbol table
Definition at line 106 of file TranslationUnit.h.
References symbolTable.
{
         return symbolTable;
     }
invalidateAnalyses()
void souffle::ram::TranslationUnit::invalidateAnalyses () inline
throw away all alive analyses of the translation unit
Definition at line 91 of file TranslationUnit.h.
References analyses.
Referenced by souffle::ram::transform::Transformer::apply().
{
         analyses.clear();
     }
Field Documentation
analyses
std::map<std::string, Own<analysis::Analysis> > souffle::ram::TranslationUnit::analyses mutable protected
Definition at line 132 of file TranslationUnit.h.
Referenced by getAliveAnalyses(), getAnalysis(), and invalidateAnalyses().
debugReport
DebugReport& souffle::ram::TranslationUnit::debugReport protected
Definition at line 144 of file TranslationUnit.h.
Referenced by getAnalysis(), and getDebugReport().
errorReport
ErrorReport& souffle::ram::TranslationUnit::errorReport protected
Definition at line 141 of file TranslationUnit.h.
Referenced by getErrorReport().
program
Own<Program> souffle::ram::TranslationUnit::program protected
Definition at line 135 of file TranslationUnit.h.
Referenced by getProgram(), and TranslationUnit().
symbolTable
souffle::SymbolTable souffle::ram::TranslationUnit::symbolTable protected
Definition at line 138 of file TranslationUnit.h.
Referenced by getSymbolTable().
The documentation for this class was generated from the following file:
ram/TranslationUnit.h