souffle: souffle::ast::UserDefinedFunctor Class Reference
souffle::ast::UserDefinedFunctor Class Reference
User-Defined functor class.
#include <UserDefinedFunctor.h>
Public Member Functions
UserDefinedFunctor * clone () const override
Create clone.
const std::vector< TypeAttribute > & getArgsTypes () const
get argument types
TypeAttribute getArgType (const size_t arg) const override
return an argument type
const std::string & getName () const
return the name
TypeAttribute getReturnType () const override
get the return type of the functor
bool isStateful () const
is stateful
void setTypes (std::vector< TypeAttribute > argumentsTypes, TypeAttribute retType, bool state)
set types of functor
UserDefinedFunctor (std::string name)
UserDefinedFunctor (std::string name, VecOwn< Argument > args, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Term
void addArgument (Own< Argument > arg)
Add argument to argument list.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Argument * > getArguments () const
Get arguments.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::ast::Term
template<typename... Operands>
Term (Operands &&... operands)
template<typename... Operands>
Term (SrcLocation loc, Operands &&... operands)
Term (VecOwn< Argument > operands, SrcLocation loc={})
Protected Attributes
std::optional< std::vector< TypeAttribute > > argTypes
Argument types.
const std::string name
Name.
std::optional< TypeAttribute > returnType
Return type.
bool stateful
stateful
Protected Attributes inherited from souffle::ast::Term
VecOwn< Argument > args
Arguments.
Detailed Description
User-Defined functor class.
Definition at line 40 of file UserDefinedFunctor.h.
Constructor & Destructor Documentation
UserDefinedFunctor() [1/2]
souffle::ast::UserDefinedFunctor::UserDefinedFunctor (std::string name) inline explicit
Definition at line 42 of file UserDefinedFunctor.h.
References name.
Referenced by clone().
 : Functor({}, {}), name(std::move(name)){};
UserDefinedFunctor() [2/2]
souffle::ast::UserDefinedFunctor::UserDefinedFunctor (std::string name, VecOwn< Argument > args, SrcLocation loc = {}) inline
Definition at line 44 of file UserDefinedFunctor.h.
References name.
                                                                                 {})
             : Functor(std::move(args), std::move(loc)), name(std::move(name)){};
Member Function Documentation
clone()
UserDefinedFunctor* souffle::ast::UserDefinedFunctor::clone () const inline override virtual
Create clone.
Implements souffle::ast::Functor.
Definition at line 80 of file UserDefinedFunctor.h.
References argTypes, souffle::clone(), souffle::ast::Node::getSrcLoc(), returnType, stateful, and UserDefinedFunctor().
{
         auto res = new UserDefinedFunctor(name, souffle::clone(args), getSrcLoc());
         // Only copy types if they have already been set.
         if (returnType.has_value()) {
             res->setTypes(argTypes.value(), returnType.value(), stateful);
         }
         return res;
     }
equal()
bool souffle::ast::UserDefinedFunctor::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Term.
Definition at line 94 of file UserDefinedFunctor.h.
References souffle::ast::Term::equal(), and name.
{
         const auto& other = static_cast<const UserDefinedFunctor&>(node);
         return name == other.name && Functor::equal(node);
     }
getArgsTypes()
const std::vector<TypeAttribute>& souffle::ast::UserDefinedFunctor::getArgsTypes () const inline
get argument types
Definition at line 71 of file UserDefinedFunctor.h.
References argTypes.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return argTypes.value();
     }
getArgType()
TypeAttribute souffle::ast::UserDefinedFunctor::getArgType (const size_t arg) const inline override virtual
return an argument type
Implements souffle::ast::Functor.
Definition at line 53 of file UserDefinedFunctor.h.
References argTypes.
Referenced by souffle::ast::transform::TypeChecker::visitUserDefinedFunctor().
{
         return argTypes->at(arg);
     }
getName()
const std::string& souffle::ast::UserDefinedFunctor::getName () const inline
return the name
Definition at line 48 of file UserDefinedFunctor.h.
References name.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return name;
     }
getReturnType()
TypeAttribute souffle::ast::UserDefinedFunctor::getReturnType () const inline override virtual
get the return type of the functor
Implements souffle::ast::Functor.
Definition at line 58 of file UserDefinedFunctor.h.
References returnType.
Referenced by souffle::AstToRamTranslator::translateValue(), and souffle::ast::transform::TypeChecker::visitUserDefinedFunctor().
{
         return returnType.value();
     }
isStateful()
bool souffle::ast::UserDefinedFunctor::isStateful () const inline
is stateful
Definition at line 76 of file UserDefinedFunctor.h.
References stateful.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return stateful;
     }
print()
void souffle::ast::UserDefinedFunctor::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 90 of file UserDefinedFunctor.h.
References souffle::join().
{
         os << '@' << name << "(" << join(args) << ")";
     }
setTypes()
void souffle::ast::UserDefinedFunctor::setTypes (std::vector< TypeAttribute > argumentsTypes, TypeAttribute retType, bool state) inline
set types of functor
Definition at line 63 of file UserDefinedFunctor.h.
References argTypes, returnType, and stateful.
{
         assert(argumentsTypes.size() == args.size() && "Size of types must match size of arguments");
         argTypes = std::move(argumentsTypes);
         returnType = retType;
         stateful = state;
     }
Field Documentation
argTypes
std::optional<std::vector<TypeAttribute> > souffle::ast::UserDefinedFunctor::argTypes protected
Argument types.
Definition at line 100 of file UserDefinedFunctor.h.
Referenced by clone(), getArgsTypes(), getArgType(), and setTypes().
name
const std::string souffle::ast::UserDefinedFunctor::name protected
Name.
Definition at line 109 of file UserDefinedFunctor.h.
Referenced by equal(), getName(), and UserDefinedFunctor().
returnType
std::optional<TypeAttribute> souffle::ast::UserDefinedFunctor::returnType protected
Return type.
Definition at line 103 of file UserDefinedFunctor.h.
Referenced by clone(), getReturnType(), and setTypes().
stateful
bool souffle::ast::UserDefinedFunctor::stateful protected
stateful
Definition at line 106 of file UserDefinedFunctor.h.
Referenced by clone(), isStateful(), and setTypes().
The documentation for this class was generated from the following file:
ast/UserDefinedFunctor.h