souffle: souffle::ram::AbstractConditional Class Reference
souffle::ram::AbstractConditional Class Reference abstract
Abstract conditional statement.
#include <AbstractConditional.h>
Public Member Functions
AbstractConditional (Own< Condition > cond, Own< Operation > nested, std::string profileText="")
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
AbstractConditional * clone () const override=0
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Condition & getCondition () const
Get condition that must be satisfied.
Public Member Functions inherited from souffle::ram::NestedOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Condition > condition
Condition.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract conditional statement.
Definition at line 35 of file AbstractConditional.h.
Constructor & Destructor Documentation
AbstractConditional()
souffle::ram::AbstractConditional::AbstractConditional (Own< Condition > cond, Own< Operation > nested, std::string profileText = "") inline
Definition at line 37 of file AbstractConditional.h.
References clone(), and condition.
             : NestedOperation(std::move(nested), std::move(profileText)), condition(std::move(cond)) {
         assert(condition != nullptr && "Condition is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::AbstractConditional::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 56 of file AbstractConditional.h.
References souffle::ram::NestedOperation::apply(), condition, and souffle::map().
Referenced by souffle::ram::transform::CollapseFiltersTransformer::collapseFilters().
{
         NestedOperation::apply(map);
         condition = map(std::move(condition));
     }
clone()
AbstractConditional* souffle::ram::AbstractConditional::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::NestedOperation.
Implemented in souffle::ram::Break, and souffle::ram::Filter.
Referenced by AbstractConditional().
equal()
bool souffle::ram::AbstractConditional::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 62 of file AbstractConditional.h.
References condition, souffle::ram::NestedOperation::equal(), and souffle::equal_ptr().
{
         const auto& other = static_cast<const AbstractConditional&>(node);
         return NestedOperation::equal(node) && equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::AbstractConditional::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 50 of file AbstractConditional.h.
References condition, and souffle::ram::NestedOperation::getChildNodes().
{
         auto res = NestedOperation::getChildNodes();
         res.push_back(condition.get());
         return res;
     }
getCondition()
const Condition& souffle::ram::AbstractConditional::getCondition () const inline
Get condition that must be satisfied.
Definition at line 45 of file AbstractConditional.h.
References condition.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::Filter::print(), and souffle::ram::Break::print().
{
         assert(condition != nullptr && "condition of conditional operation is a null-pointer");
         return *condition;
     }
Field Documentation
condition
Own<Condition> souffle::ram::AbstractConditional::condition protected
Condition.
Definition at line 68 of file AbstractConditional.h.
Referenced by AbstractConditional(), apply(), souffle::ram::Filter::clone(), souffle::ram::Break::clone(), equal(), getChildNodes(), and getCondition().
The documentation for this class was generated from the following file:
ram/AbstractConditional.h