souffle: souffle::ast::Directive Class Reference
souffle::ast::Directive Class Reference
a directive has a type (e.g.
#include <Directive.h>
Public Member Functions
void addParameter (const std::string &key, std::string value)
Add new parameter.
Directive * clone () const override
Create a clone (i.e.
Directive (DirectiveType type, QualifiedName name, SrcLocation loc={})
const std::string & getParameter (const std::string &key) const
Get parameter.
const std::map< std::string, std::string > & getParameters () const
Get parameters.
const QualifiedName & getQualifiedName () const
Get relation name.
DirectiveType getType () const
Get directive type.
bool hasParameter (const std::string &key) const
Check for a parameter.
void setQualifiedName (QualifiedName name)
Set relation name.
void setType (DirectiveType type)
Set directive type.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
QualifiedName name
Relation name of the directive.
std::map< std::string, std::string > parameters
Parameters of directive.
DirectiveType type
Type of directive.
Detailed Description
a directive has a type (e.g.
input/output/printsize/limitsize), qualified relation name, and a key value map for storing parameters of the directive.
Definition at line 50 of file Directive.h.
Constructor & Destructor Documentation
Directive()
souffle::ast::Directive::Directive (DirectiveType type, QualifiedName name, SrcLocation loc = {}) inline
Definition at line 52 of file Directive.h.
                                                                         {})
             : Node(std::move(loc)), type(type), name(std::move(name)) {}
Member Function Documentation
addParameter()
void souffle::ast::Directive::addParameter (const std::string & key, std::string value) inline
Add new parameter.
Definition at line 81 of file Directive.h.
{
         parameters[key] = std::move(value);
     }
clone()
Directive* souffle::ast::Directive::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 95 of file Directive.h.
{
         auto res = new Directive(type, name, getSrcLoc());
         res->parameters = parameters;
         return res;
     }
equal()
bool souffle::ast::Directive::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 111 of file Directive.h.
References type.
{
         const auto& other = static_cast<const Directive&>(node);
         return other.type == type && other.name == name && other.parameters == parameters;
     }
getParameter()
const std::string& souffle::ast::Directive::getParameter (const std::string & key) const inline
Get parameter.
Definition at line 76 of file Directive.h.
Referenced by souffle::ast::analysis::IOTypeAnalysis::run().
{
         return parameters.at(key);
     }
getParameters()
const std::map<std::string, std::string>& souffle::ast::Directive::getParameters () const inline
Get parameters.
Definition at line 91 of file Directive.h.
{
         return parameters;
     }
getQualifiedName()
const QualifiedName& souffle::ast::Directive::getQualifiedName () const inline
Get relation name.
Definition at line 66 of file Directive.h.
Referenced by souffle::ast::transform::IODefaultsTransformer::getRelationName(), souffle::ast::transform::IOAttributesTransformer::getRelationName(), and souffle::ast::analysis::IOTypeAnalysis::run().
{
         return name;
     }
getType()
DirectiveType souffle::ast::Directive::getType () const inline
Get directive type.
Definition at line 56 of file Directive.h.
Referenced by souffle::ast::analysis::IOTypeAnalysis::run().
{
         return type;
     }
hasParameter()
bool souffle::ast::Directive::hasParameter (const std::string & key) const inline
Check for a parameter.
Definition at line 86 of file Directive.h.
Referenced by souffle::ast::analysis::IOTypeAnalysis::run().
{
         return parameters.find(key) != parameters.end();
     }
print()
void souffle::ast::Directive::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 102 of file Directive.h.
References souffle::join().
{
         os << "." << type << " " << name;
         if (!parameters.empty()) {
             os << "(" << join(parameters, ",", [](std::ostream& out, const auto& arg) {
                 out << arg.first << "=\"" << arg.second << "\"";
             }) << ")";
         }
     }
setQualifiedName()
void souffle::ast::Directive::setQualifiedName (QualifiedName name) inline
Set relation name.
Definition at line 71 of file Directive.h.
{
         this->name = std::move(name);
     }
setType()
void souffle::ast::Directive::setType (DirectiveType type) inline
Set directive type.
Definition at line 61 of file Directive.h.
{
         this->type = type;
     }
Field Documentation
name
QualifiedName souffle::ast::Directive::name protected
Relation name of the directive.
Definition at line 120 of file Directive.h.
parameters
std::map<std::string, std::string> souffle::ast::Directive::parameters protected
Parameters of directive.
Definition at line 123 of file Directive.h.
type
DirectiveType souffle::ast::Directive::type protected
Type of directive.
Definition at line 117 of file Directive.h.
Referenced by equal().
The documentation for this class was generated from the following file:
ast/Directive.h