souffle: souffle::ast::ComponentType Class Reference
souffle::ast::ComponentType Class Reference
Component type of a component.
#include <ComponentType.h>
Public Member Functions
ComponentType * clone () const override
Create a clone (i.e.
ComponentType (std::string name="", std::vector< QualifiedName > params={}, SrcLocation loc={})
const std::string & getName () const
Return component name.
const std::vector< QualifiedName > & getTypeParameters () const
Return component type parameters.
void setName (std::string n)
Set component name.
void setTypeParameters (const std::vector< QualifiedName > &params)
Set component type parameters.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::string name
Component name.
std::vector< QualifiedName > typeParams
Component type parameters.
Detailed Description
Component type of a component.
Example: name < Type1, Type2, ... > where name is the component name and < Type, Type, ... > is a list of component type parameters (either actual or formal).
Definition at line 39 of file ComponentType.h.
Constructor & Destructor Documentation
ComponentType()
souffle::ast::ComponentType::ComponentType (std::string name = "", std::vector< QualifiedName > params = {}, SrcLocation loc = {}) inline
Definition at line 41 of file ComponentType.h.
References name, souffle::ast::Node::Node(), and typeParams.
Referenced by clone().
                                                                          {}, SrcLocation loc = {})
             : Node(std::move(loc)), name(std::move(name)), typeParams(std::move(params)) {}
Member Function Documentation
clone()
ComponentType* souffle::ast::ComponentType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 64 of file ComponentType.h.
References ComponentType(), souffle::ast::Node::getSrcLoc(), name, and typeParams.
{
         return new ComponentType(name, typeParams, getSrcLoc());
     }
equal()
bool souffle::ast::ComponentType::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 76 of file ComponentType.h.
References name, and typeParams.
{
         const auto& other = static_cast<const ComponentType&>(node);
         return name == other.name && typeParams == other.typeParams;
     }
getName()
const std::string& souffle::ast::ComponentType::getName () const inline
Return component name.
Definition at line 45 of file ComponentType.h.
References name.
Referenced by souffle::ast::transform::ComponentChecker::checkComponent(), and souffle::ast::transform::ComponentChecker::checkComponentReference().
{
         return name;
     }
getTypeParameters()
const std::vector<QualifiedName>& souffle::ast::ComponentType::getTypeParameters () const inline
Return component type parameters.
Definition at line 55 of file ComponentType.h.
References typeParams.
Referenced by souffle::ast::transform::ComponentChecker::checkComponent(), and souffle::ast::transform::ComponentChecker::checkComponentReference().
{
         return typeParams;
     }
print()
void souffle::ast::ComponentType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 69 of file ComponentType.h.
References souffle::join(), name, and typeParams.
{
         os << name;
         if (!typeParams.empty()) {
             os << "<" << join(typeParams) << ">";
         }
     }
setName()
void souffle::ast::ComponentType::setName (std::string n) inline
Set component name.
Definition at line 50 of file ComponentType.h.
References name.
{
         name = std::move(n);
     }
setTypeParameters()
void souffle::ast::ComponentType::setTypeParameters (const std::vector< QualifiedName > & params) inline
Set component type parameters.
Definition at line 60 of file ComponentType.h.
References typeParams.
{
         typeParams = params;
     }
Field Documentation
name
std::string souffle::ast::ComponentType::name private
Component name.
Definition at line 83 of file ComponentType.h.
Referenced by clone(), ComponentType(), equal(), getName(), print(), and setName().
typeParams
std::vector<QualifiedName> souffle::ast::ComponentType::typeParams private
Component type parameters.
Definition at line 86 of file ComponentType.h.
Referenced by clone(), ComponentType(), equal(), getTypeParameters(), print(), and setTypeParameters().
The documentation for this class was generated from the following file:
ast/ComponentType.h