souffle: souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis Class Reference
souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis Class Reference
Analysis pass computing a topologically sorted strongly connected component (SCC) graph.
#include <TopologicallySortedSCCGraph.h>
Public Member Functions
size_t indexOfScc (const size_t scc) const
std::set< size_t > indexOfScc (const std::set< size_t > &sccs) const
const std::vector< size_t > & order () const
void print (std::ostream &os) const override
Output topologically sorted strongly connected component graph in text format.
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
size_t sccOfIndex (const size_t index) const
TopologicallySortedSCCGraphAnalysis ()
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "topological-scc-graph"
Private Member Functions
void computeTopologicalOrdering (size_t scc, std::vector< bool > &visited)
Recursive component for the forwards algorithm computing the topological ordering of the SCCs.
int topologicalOrderingCost (const std::vector< size_t > &permutationOfSCCs) const
Calculate the topological ordering cost of a permutation of as of yet unordered SCCs using the ordered SCCs.
Private Attributes
SCCGraphAnalysis * sccGraph = nullptr
The strongly connected component (SCC) graph.
std::vector< size_t > sccOrder
The final topological ordering of the SCCs.
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass computing a topologically sorted strongly connected component (SCC) graph.
Definition at line 41 of file TopologicallySortedSCCGraph.h.
Constructor & Destructor Documentation
TopologicallySortedSCCGraphAnalysis()
souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::TopologicallySortedSCCGraphAnalysis () inline
Definition at line 45 of file TopologicallySortedSCCGraph.h.
References run().
 : Analysis(name) {}
Member Function Documentation
computeTopologicalOrdering()
void souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::computeTopologicalOrdering (size_t scc, std::vector< bool > & visited) private
Recursive component for the forwards algorithm computing the topological ordering of the SCCs.
Definition at line 69 of file TopologicallySortedSCCGraph.cpp.
References souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs(), souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs(), sccGraph, and sccOrder.
Referenced by run().
{
     // create a flag to indicate that a successor was visited (by default it hasn't been)
     bool found = false;
     bool hasUnvisitedSuccessor = false;
     bool hasUnvisitedPredecessor = false;
     // for each successor of the input scc
     const auto& successorsToVisit = sccGraph->getSuccessorSCCs(scc);
     for (const auto scc_i : successorsToVisit) {
         if (visited[scc_i]) {
             continue;
         }
         hasUnvisitedPredecessor = false;
         const auto& successorsPredecessors = sccGraph->getPredecessorSCCs(scc_i);
         for (const auto scc_j : successorsPredecessors) {
             if (!visited[scc_j]) {
                 hasUnvisitedPredecessor = true;
                 break;
             }
         }
         if (!hasUnvisitedPredecessor) {
             // give it a temporary marking
             visited[scc_i] = true;
             // add it to the permanent ordering
             sccOrder.push_back(scc_i);
             // and use it as a root node in a recursive call to this function
             computeTopologicalOrdering(scc_i, visited);
             // finally, indicate that a successor has been found for this node
             found = true;
         }
     }
     // return at once if no valid successors have been found; as either it has none or they all have a
     // better predecessor
     if (!found) {
         return;
     }
     hasUnvisitedPredecessor = false;
     const auto& predecessors = sccGraph->getPredecessorSCCs(scc);
     for (const auto scc_j : predecessors) {
         if (!visited[scc_j]) {
             hasUnvisitedPredecessor = true;
             break;
         }
     }
     hasUnvisitedSuccessor = false;
     const auto& successors = sccGraph->getSuccessorSCCs(scc);
     for (const auto scc_j : successors) {
         if (!visited[scc_j]) {
             hasUnvisitedSuccessor = true;
             break;
         }
     }
     // otherwise, if more white successors remain for the current scc, use it again as the root node in a
     // recursive call to this function
     if (hasUnvisitedSuccessor && !hasUnvisitedPredecessor) {
         computeTopologicalOrdering(scc, visited);
     }
 }
indexOfScc() [1/2]
size_t souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::indexOfScc (const size_t scc) const inline
Definition at line 57 of file TopologicallySortedSCCGraph.h.
References sccOrder.
Referenced by indexOfScc().
{
         auto it = std::find(sccOrder.begin(), sccOrder.end(), scc);
         assert(it != sccOrder.end());
         return (size_t)std::distance(sccOrder.begin(), it);
     }
indexOfScc() [2/2]
std::set<size_t> souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::indexOfScc (const std::set< size_t > & sccs) const inline
Definition at line 63 of file TopologicallySortedSCCGraph.h.
References indexOfScc(), and print().
{
         std::set<size_t> indices;
         for (const auto scc : sccs) {
             indices.insert(indexOfScc(scc));
         }
         return indices;
     }
order()
const std::vector<size_t>& souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::order () const inline
Definition at line 49 of file TopologicallySortedSCCGraph.h.
References sccOrder.
{
         return sccOrder;
     }
print()
void souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::print (std::ostream & os) const override virtual
Output topologically sorted strongly connected component graph in text format.
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 151 of file TopologicallySortedSCCGraph.cpp.
References souffle::ast::analysis::SCCGraphAnalysis::getInternalRelations(), souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs(), souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs(), i, souffle::join(), sccGraph, sccOrder, and topologicalOrderingCost().
Referenced by indexOfScc().
{
     os << "--- partial order of strata as list of pairs ---" << std::endl;
     for (size_t sccIndex = 0; sccIndex < sccOrder.size(); sccIndex++) {
         const auto& successorSccs = sccGraph->getSuccessorSCCs(sccOrder.at(sccIndex));
         // use a self-loop to indicate that an SCC has no successors or predecessors
         if (successorSccs.empty() && sccGraph->getPredecessorSCCs(sccOrder.at(sccIndex)).empty()) {
             os << sccIndex << " " << sccIndex << std::endl;
             continue;
         }
         for (const auto successorScc : successorSccs) {
             const auto successorSccIndex = *std::find(sccOrder.begin(), sccOrder.end(), successorScc);
             os << sccIndex << " " << successorSccIndex << std::endl;
         }
     }
     os << "--- total order with relations of each strata ---" << std::endl;
     for (size_t i = 0; i < sccOrder.size(); i++) {
         os << i << ": [";
         os << join(sccGraph->getInternalRelations(sccOrder[i]), ", ",
                 [](std::ostream& out, const Relation* rel) { out << rel->getQualifiedName(); });
         os << "]" << std::endl;
     }
     os << std::endl;
     os << "--- statistics of topological order ---" << std::endl;
     os << "cost: " << topologicalOrderingCost(sccOrder) << std::endl;
 }
run()
void souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 127 of file TopologicallySortedSCCGraph.cpp.
References computeTopologicalOrdering(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::analysis::SCCGraphAnalysis::getNumberOfSCCs(), souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs(), souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs(), sccGraph, and sccOrder.
Referenced by TopologicallySortedSCCGraphAnalysis().
{
     // obtain the scc graph
     sccGraph = translationUnit.getAnalysis<SCCGraphAnalysis>();
     // clear the list of ordered sccs
     sccOrder.clear();
     std::vector<bool> visited;
     visited.resize(sccGraph->getNumberOfSCCs());
     std::fill(visited.begin(), visited.end(), false);
     // generate topological ordering using forwards algorithm (like Khan's algorithm)
     // for each of the sccs in the graph
     for (size_t scc = 0; scc < sccGraph->getNumberOfSCCs(); ++scc) {
         // if that scc has no predecessors
         if (sccGraph->getPredecessorSCCs(scc).empty()) {
             // put it in the ordering
             sccOrder.push_back(scc);
             visited[scc] = true;
             // if the scc has successors
             if (!sccGraph->getSuccessorSCCs(scc).empty()) {
                 computeTopologicalOrdering(scc, visited);
             }
         }
     }
 }
sccOfIndex()
size_t souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::sccOfIndex (const size_t index) const inline
Definition at line 53 of file TopologicallySortedSCCGraph.h.
References sccOrder.
{
         return sccOrder.at(index);
     }
topologicalOrderingCost()
int souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::topologicalOrderingCost (const std::vector< size_t > & permutationOfSCCs) const private
Calculate the topological ordering cost of a permutation of as of yet unordered SCCs using the ordered SCCs.
Returns -1 if the given vector is not a valid topological ordering.
Definition at line 31 of file TopologicallySortedSCCGraph.cpp.
References souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs(), souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs(), sccGraph, and sccOrder.
Referenced by print().
{
     // create variables to hold the cost of the current SCC and the permutation as a whole
     int costOfSCC = 0;
     int costOfPermutation = -1;
     // obtain an iterator to the end of the already ordered partition of sccs
     auto it_k = permutationOfSCCs.begin() + sccOrder.size();
     // for each of the scc's in the ordering, resetting the cost of the scc to zero on each loop
     for (auto it_i = permutationOfSCCs.begin(); it_i != permutationOfSCCs.end(); ++it_i, costOfSCC = 0) {
         // if the index of the current scc is after the end of the ordered partition
         if (it_i >= it_k) {
             // check that the index of all predecessor sccs of are before the index of the current scc
             for (auto scc : sccGraph->getPredecessorSCCs(*it_i)) {
                 if (std::find(permutationOfSCCs.begin(), it_i, scc) == it_i) {
                     // if not, the sort is not a valid topological sort
                     return -1;
                 }
             }
         }
         // otherwise, calculate the cost of the current scc
         // as the number of sccs with an index before the current scc
         for (auto it_j = permutationOfSCCs.begin(); it_j != it_i; ++it_j) {
             // having some successor scc with an index after the current scc
             for (auto scc : sccGraph->getSuccessorSCCs(*it_j)) {
                 if (std::find(permutationOfSCCs.begin(), it_i, scc) == it_i) {
                     costOfSCC++;
                 }
             }
         }
         // and if this cost is greater than the maximum recorded cost for the whole permutation so far,
         // set the cost of the permutation to it
         if (costOfSCC > costOfPermutation) {
             costOfPermutation = costOfSCC;
         }
     }
     return costOfPermutation;
 }
Field Documentation
name
constexpr const char* souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::name = "topological-scc-graph" static
Definition at line 43 of file TopologicallySortedSCCGraph.h.
sccGraph
SCCGraphAnalysis* souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::sccGraph = nullptr private
The strongly connected component (SCC) graph.
Definition at line 76 of file TopologicallySortedSCCGraph.h.
Referenced by computeTopologicalOrdering(), print(), run(), and topologicalOrderingCost().
sccOrder
std::vector<size_t> souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::sccOrder private
The final topological ordering of the SCCs.
Definition at line 79 of file TopologicallySortedSCCGraph.h.
Referenced by computeTopologicalOrdering(), indexOfScc(), order(), print(), run(), sccOfIndex(), and topologicalOrderingCost().
The documentation for this class was generated from the following files:
ast/analysis/TopologicallySortedSCCGraph.h
ast/analysis/TopologicallySortedSCCGraph.cpp