souffle: souffle::ast::analysis::IOTypeAnalysis Class Reference
souffle::ast::analysis::IOTypeAnalysis Class Reference
#include <IOType.h>
Public Member Functions
std::size_t getLimitSize (const Relation *relation) const
IOTypeAnalysis ()
bool isInput (const Relation *relation) const
bool isIO (const Relation *relation) const
bool isLimitSize (const Relation *relation) const
bool isOutput (const Relation *relation) const
bool isPrintSize (const Relation *relation) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "IO-type-analysis"
Private Attributes
std::set< const Relation * > inputRelations
std::map< const Relation *, std::size_t > limitSize
std::set< const Relation * > limitSizeRelations
std::set< const Relation * > outputRelations
std::set< const Relation * > printSizeRelations
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 33 of file IOType.h.
Constructor & Destructor Documentation
IOTypeAnalysis()
souffle::ast::analysis::IOTypeAnalysis::IOTypeAnalysis () inline
Definition at line 37 of file IOType.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
getLimitSize()
std::size_t souffle::ast::analysis::IOTypeAnalysis::getLimitSize (const Relation * relation) const inline
Definition at line 59 of file IOType.h.
References limitSize.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         auto iter = limitSize.find(relation);
         if (iter != limitSize.end()) {
             return (*iter).second;
         } else
             return 0;
     }
isInput()
bool souffle::ast::analysis::IOTypeAnalysis::isInput (const Relation * relation) const inline
Definition at line 43 of file IOType.h.
References inputRelations.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::analysis::SCCGraphAnalysis::getInternalInputRelations(), and isIO().
{
         return inputRelations.count(relation) != 0;
     }
isIO()
bool souffle::ast::analysis::IOTypeAnalysis::isIO (const Relation * relation) const inline
Definition at line 67 of file IOType.h.
References isInput(), isOutput(), and isPrintSize().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkInlining().
{
         return isInput(relation) || isOutput(relation) || isPrintSize(relation);
     }
isLimitSize()
bool souffle::ast::analysis::IOTypeAnalysis::isLimitSize (const Relation * relation) const inline
Definition at line 55 of file IOType.h.
References limitSizeRelations.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return limitSizeRelations.count(relation) != 0;
     }
isOutput()
bool souffle::ast::analysis::IOTypeAnalysis::isOutput (const Relation * relation) const inline
Definition at line 47 of file IOType.h.
References outputRelations.
Referenced by souffle::ast::analysis::SCCGraphAnalysis::getExternalNonOutputPredecessorRelations(), souffle::ast::analysis::SCCGraphAnalysis::getExternalOutputPredecessorRelations(), souffle::ast::analysis::SCCGraphAnalysis::getInternalNonOutputRelationsWithExternalSuccessors(), souffle::ast::analysis::SCCGraphAnalysis::getInternalOutputRelations(), and isIO().
{
         return outputRelations.count(relation) != 0;
     }
isPrintSize()
bool souffle::ast::analysis::IOTypeAnalysis::isPrintSize (const Relation * relation) const inline
Definition at line 51 of file IOType.h.
References printSizeRelations.
Referenced by isIO().
{
         return printSizeRelations.count(relation) != 0;
     }
print()
void souffle::ast::analysis::IOTypeAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 55 of file IOType.cpp.
References inputRelations, souffle::join(), limitSizeRelations, outputRelations, and printSizeRelations.
Referenced by IOTypeAnalysis().
{
     auto show = [](std::ostream& os, const Relation* r) { os << r->getQualifiedName(); };
     os << "input relations: {" << join(inputRelations, ", ", show) << "}\n";
     os << "output relations: {" << join(outputRelations, ", ", show) << "}\n";
     os << "printsize relations: {" << join(printSizeRelations, ", ", show) << "}\n";
     os << "limitsize relations: {" << join(limitSizeRelations, ", ", show) << "}\n";
 }
run()
void souffle::ast::analysis::IOTypeAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 32 of file IOType.cpp.
References souffle::ast::Directive::getParameter(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Directive::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::Directive::getType(), souffle::ast::Directive::hasParameter(), souffle::ast::input, inputRelations, souffle::ast::limitsize, limitSize, limitSizeRelations, souffle::ast::output, outputRelations, souffle::ast::printsize, printSizeRelations, relation, and souffle::ast::visitDepthFirst().
Referenced by IOTypeAnalysis().
{
     const Program& program = translationUnit.getProgram();
     visitDepthFirst(program, [&](const Directive& directive) {
         auto* relation = getRelation(program, directive.getQualifiedName());
         if (relation == nullptr) {
             return;
         }
         switch (directive.getType()) {
             case ast::DirectiveType::input: inputRelations.insert(relation); break;
             case ast::DirectiveType::output: outputRelations.insert(relation); break;
             case ast::DirectiveType::printsize:
                 printSizeRelations.insert(relation);
                 outputRelations.insert(relation);
                 break;
             case ast::DirectiveType::limitsize:
                 limitSizeRelations.insert(relation);
                 assert(directive.hasParameter("n") && "limitsize has no n directive");
                 limitSize[relation] = stoi(directive.getParameter("n"));
                 break;
         }
     });
 }
Field Documentation
inputRelations
std::set<const Relation*> souffle::ast::analysis::IOTypeAnalysis::inputRelations private
Definition at line 72 of file IOType.h.
Referenced by isInput(), print(), and run().
limitSize
std::map<const Relation*, std::size_t> souffle::ast::analysis::IOTypeAnalysis::limitSize private
Definition at line 76 of file IOType.h.
Referenced by getLimitSize(), and run().
limitSizeRelations
std::set<const Relation*> souffle::ast::analysis::IOTypeAnalysis::limitSizeRelations private
Definition at line 75 of file IOType.h.
Referenced by isLimitSize(), print(), and run().
name
constexpr const char* souffle::ast::analysis::IOTypeAnalysis::name = "IO-type-analysis" static
Definition at line 35 of file IOType.h.
outputRelations
std::set<const Relation*> souffle::ast::analysis::IOTypeAnalysis::outputRelations private
Definition at line 73 of file IOType.h.
Referenced by isOutput(), print(), and run().
printSizeRelations
std::set<const Relation*> souffle::ast::analysis::IOTypeAnalysis::printSizeRelations private
Definition at line 74 of file IOType.h.
Referenced by isPrintSize(), print(), and run().
The documentation for this class was generated from the following files:
ast/analysis/IOType.h
ast/analysis/IOType.cpp