souffle: souffle::ram::ExistenceCheck Class Reference
souffle::ram::ExistenceCheck Class Reference
Existence check for a tuple(-pattern) in a relation.
#include <ExistenceCheck.h>
Public Member Functions
ExistenceCheck * clone () const override
Create a clone (i.e.
ExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals)
Public Member Functions inherited from souffle::ram::AbstractExistenceCheck
AbstractExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get relation.
const std::vector< Expression * > getValues () const
Get arguments of the tuple/pattern A null pointer element in the vector denotes an unspecified pattern for a tuple element.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::ram::AbstractExistenceCheck
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes inherited from souffle::ram::AbstractExistenceCheck
Own< RelationReference > relationRef
Relation.
VecOwn< Expression > values
Pattern – nullptr if undefined.
Detailed Description
Existence check for a tuple(-pattern) in a relation.
Returns true if the tuple is in the relation
The following condition is evaluated to true if the tuple element t0.1 is in the relation A:
t0.1 IN A
Definition at line 42 of file ExistenceCheck.h.
Constructor & Destructor Documentation
ExistenceCheck()
souffle::ram::ExistenceCheck::ExistenceCheck (Own< RelationReference > relRef, VecOwn< Expression > vals) inline
Definition at line 44 of file ExistenceCheck.h.
Referenced by clone().
             : AbstractExistenceCheck(std::move(relRef), std::move(vals)) {}
Member Function Documentation
clone()
ExistenceCheck* souffle::ram::ExistenceCheck::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Condition.
Definition at line 47 of file ExistenceCheck.h.
References souffle::clone(), ExistenceCheck(), souffle::ram::AbstractExistenceCheck::relationRef, and souffle::ram::AbstractExistenceCheck::values.
Referenced by souffle::ram::test::TEST().
{
         VecOwn<Expression> newValues;
         for (auto& cur : values) {
             newValues.emplace_back(cur->clone());
         }
         return new ExistenceCheck(souffle::clone(relationRef), std::move(newValues));
     }
The documentation for this class was generated from the following file:
ram/ExistenceCheck.h