souffle: souffle::ram::LogTimer Class Reference
souffle::ram::LogTimer Class Reference
Execution time logger for a statement.
#include <LogTimer.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
LogTimer * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
LogTimer (Own< Statement > stmt, std::string msg)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractLog
AbstractLog (Own< Statement > stmt, std::string msg)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const std::string & getMessage () const
Get logging message.
const Statement & getStatement () const
Get logging statement.
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::Node
virtual bool equal (const Node &) const
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::AbstractLog
bool equal (const Node &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::AbstractLog
std::string message
logging message
Own< Statement > statement
logging statement
Detailed Description
Execution time logger for a statement.
Logs the execution time of a statement. Before and after the execution of the logging statement the wall-clock time is taken to compute the time duration for the statement. Duration and logging message is printed after the execution of the statement.
For example:
START_TIMER "@runtime\;"
  BEGIN_STRATUM 0
    ...
  ...
END_TIMER
Definition at line 51 of file LogTimer.h.
Constructor & Destructor Documentation
LogTimer()
souffle::ram::LogTimer::LogTimer (Own< Statement > stmt, std::string msg) inline
Definition at line 53 of file LogTimer.h.
Referenced by clone().
 : AbstractLog(std::move(stmt), std::move(msg)) {}
Member Function Documentation
apply()
void souffle::ram::LogTimer::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 63 of file LogTimer.h.
References souffle::ram::AbstractLog::apply().
{
         AbstractLog::apply(map);
     }
clone()
LogTimer* souffle::ram::LogTimer::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 59 of file LogTimer.h.
References souffle::clone(), LogTimer(), souffle::ram::AbstractLog::message, and souffle::ram::AbstractLog::statement.
Referenced by souffle::ram::test::TEST().
{
         return new LogTimer(souffle::clone(statement), message);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::LogTimer::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 55 of file LogTimer.h.
References souffle::ram::AbstractLog::getChildNodes().
{
         return AbstractLog::getChildNodes();
     }
print()
void souffle::ram::LogTimer::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 68 of file LogTimer.h.
References souffle::ram::AbstractLog::message, souffle::ram::Statement::print(), souffle::ram::AbstractLog::statement, souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "START_TIMER \"" << stringify(message) << "\"" << std::endl;
         Statement::print(statement.get(), os, tabpos + 1);
         os << times(" ", tabpos) << "END_TIMER" << std::endl;
     }
The documentation for this class was generated from the following file:
ram/LogTimer.h