souffle: souffle::ast::transform::InlineRelationsTransformer Class Reference
souffle::ast::transform::InlineRelationsTransformer Class Reference
Transformation pass to inline marked relations.
#include <InlineRelations.h>
Public Member Functions
InlineRelationsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to inline marked relations.
Definition at line 28 of file InlineRelations.h.
Member Function Documentation
clone()
InlineRelationsTransformer* souffle::ast::transform::InlineRelationsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 34 of file InlineRelations.h.
References transform().
{
         return new InlineRelationsTransformer();
     }
getName()
std::string souffle::ast::transform::InlineRelationsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 30 of file InlineRelations.h.
{
         return "InlineRelationsTransformer";
     }
transform()
bool souffle::ast::transform::InlineRelationsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 992 of file InlineRelations.cpp.
References souffle::ast::Program::addClause(), souffle::ast::transform::containsInlinedAtom(), souffle::ast::getClauses(), souffle::ast::transform::getInlinedClause(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getRelations(), souffle::INLINE, souffle::ast::transform::nameInlinedUnderscores(), souffle::ast::transform::normaliseInlinedHeads(), and souffle::ast::Program::removeClause().
Referenced by clone().
{
     bool changed = false;
     Program& program = translationUnit.getProgram();
     // Replace constants in the head of inlined clauses with (constrained) variables.
     // This is done to simplify atom unification, particularly when negations are involved.
     normaliseInlinedHeads(program);
     // Remove underscores in inlined atoms in the program to avoid issues during atom unification
     nameInlinedUnderscores(program);
     // Keep trying to inline things until we reach a fixed point.
     // Since we know there are no cyclic dependencies between inlined relations, this will necessarily
     // terminate.
     bool clausesChanged = true;
     while (clausesChanged) {
         std::set<Clause*> clausesToDelete;
         clausesChanged = false;
         // Go through each relation in the program and check if we need to inline any of its clauses
         for (Relation* rel : program.getRelations()) {
             // Skip if the relation is going to be inlined
             if (rel->hasQualifier(RelationQualifier::INLINE)) {
                 continue;
             }
             // Go through the relation's clauses and try inlining them
             for (Clause* clause : getClauses(program, *rel)) {
                 if (containsInlinedAtom(program, *clause)) {
                     // Generate the inlined versions of this clause - the clause will be replaced by these
                     std::vector<Clause*> newClauses = getInlinedClause(program, *clause);
                     // Replace the clause with these equivalent versions
                     clausesToDelete.insert(clause);
                     for (Clause* replacementClause : newClauses) {
                         program.addClause(Own<Clause>(replacementClause));
                     }
                     // We've changed the program this iteration
                     clausesChanged = true;
                     changed = true;
                 }
             }
         }
         // Delete all clauses that were replaced
         for (const Clause* clause : clausesToDelete) {
             program.removeClause(clause);
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/InlineRelations.h
ast/transform/InlineRelations.cpp