souffle: souffle::ast::analysis::Analysis Class Reference
souffle::ast::analysis::Analysis Class Reference abstract
Abstract class for a AST Analysis.
#include <Analysis.h>
Public Member Functions
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual void run (const TranslationUnit &)=0
run analysis for a Ast translation unit
virtual ~Analysis ()=default
Protected Attributes
const std::string identifier
Friends
std::ostream & operator<< (std::ostream &out, const Analysis &other)
define output stream operator
Detailed Description
Abstract class for a AST Analysis.
Definition at line 32 of file Analysis.h.
Constructor & Destructor Documentation
Analysis()
souffle::ast::analysis::Analysis::Analysis (std::string identifier) inline
Definition at line 34 of file Analysis.h.
References run(), and ~Analysis().
 : identifier(std::move(identifier)) {}
~Analysis()
virtual souffle::ast::analysis::Analysis::~Analysis () virtual default
Referenced by Analysis().
Member Function Documentation
getName()
virtual const std::string& souffle::ast::analysis::Analysis::getName () const inline virtual
get name of the analysis
Definition at line 44 of file Analysis.h.
References identifier.
Referenced by souffle::ast::analysis::PrecedenceGraphAnalysis::print(), and souffle::ast::analysis::SCCGraphAnalysis::print().
{
         return identifier;
     }
print()
virtual void souffle::ast::analysis::Analysis::print (std::ostream &) const inline virtual
print the analysis result in HTML format
Reimplemented in souffle::ast::analysis::SCCGraphAnalysis, souffle::ast::analysis::ClauseNormalisationAnalysis, souffle::ast::analysis::RelationScheduleAnalysis, souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis, souffle::ast::analysis::ProfileUseAnalysis, souffle::ast::analysis::RelationDetailCacheAnalysis, souffle::ast::analysis::PrecedenceGraphAnalysis, souffle::ast::analysis::RecursiveClausesAnalysis, souffle::ast::analysis::RedundantRelationsAnalysis, souffle::ast::analysis::IOTypeAnalysis, souffle::ast::analysis::TypeEnvironmentAnalysis, and souffle::ast::analysis::TypeAnalysis.
Definition at line 41 of file Analysis.h.
 {}
run()
virtual void souffle::ast::analysis::Analysis::run (const TranslationUnit &) pure virtual
run analysis for a Ast translation unit
Implemented in souffle::ast::analysis::ClauseNormalisationAnalysis, souffle::ast::analysis::ComponentLookupAnalysis, souffle::ast::analysis::RelationScheduleAnalysis, souffle::ast::analysis::SCCGraphAnalysis, souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis, souffle::ast::analysis::ProfileUseAnalysis, souffle::ast::analysis::RelationDetailCacheAnalysis, souffle::ast::analysis::RecursiveClausesAnalysis, souffle::ast::analysis::RedundantRelationsAnalysis, souffle::ast::analysis::PrecedenceGraphAnalysis, souffle::ast::analysis::IOTypeAnalysis, souffle::ast::analysis::AuxiliaryArityAnalysis, souffle::ast::analysis::TypeEnvironmentAnalysis, souffle::ast::analysis::TypeAnalysis, and souffle::ast::analysis::SumTypeBranchesAnalysis.
Referenced by Analysis().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Analysis & other) friend
define output stream operator
Definition at line 49 of file Analysis.h.
{
         other.print(out);
         return out;
     }
Field Documentation
identifier
const std::string souffle::ast::analysis::Analysis::identifier protected
Definition at line 55 of file Analysis.h.
Referenced by getName().
The documentation for this class was generated from the following file:
ast/analysis/Analysis.h