souffle: souffle::ram::Program Class Reference
souffle::ram::Program Class Reference
RAM program relation declaration and functions.
#include <Program.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Program * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Statement & getMain () const
Get main program.
std::vector< Relation * > getRelations () const
Get all relations of RAM program.
const Statement & getSubroutine (const std::string &name) const
Get a specific subroutine.
const std::map< std::string, Statement * > getSubroutines () const
Get all subroutines of a RAM program.
Program (VecOwn< Relation > rels, Own< Statement > main, std::map< std::string, Own< Statement >> subs)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &out) const override
Print RAM node.
Protected Attributes
Own< Statement > main
Main program.
VecOwn< Relation > relations
Relations of RAM program.
std::map< std::string, Own< Statement > > subroutines
Subroutines for provenance system.
Private Member Functions
Program ()=default
Detailed Description
RAM program relation declaration and functions.
A typical example:
PROGRAM
  DECLARATION
    A(x:i:number)
  END DECLARATION
  BEGIN MAIN
    ...
  END MAIN
END PROGRAM
Definition at line 52 of file Program.h.
Constructor & Destructor Documentation
Program() [1/2]
souffle::ram::Program::Program () private default
Referenced by clone().
Program() [2/2]
souffle::ram::Program::Program (VecOwn< Relation > rels, Own< Statement > main, std::map< std::string, Own< Statement >> subs) inline
Definition at line 57 of file Program.h.
References relations, souffle::ast::analysis::sub(), and subroutines.
             : relations(std::move(rels)), main(std::move(main)), subroutines(std::move(subs)) {
         assert(this->main != nullptr && "Main program is a null-pointer");
         for (const auto& rel : relations) {
             assert(rel != nullptr && "Relation is a null-pointer");
         }
         for (const auto& sub : subroutines) {
             assert(sub.second != nullptr && "Subroutine is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::ram::Program::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 127 of file Program.h.
References main, souffle::map(), relations, souffle::ast::analysis::sub(), and subroutines.
Referenced by souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak().
{
         main = map(std::move(main));
         for (auto& rel : relations) {
             rel = map(std::move(rel));
         }
         for (auto& sub : subroutines) {
             sub.second = map(std::move(sub.second));
         }
     }
clone()
Program* souffle::ram::Program::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Node.
Definition at line 104 of file Program.h.
References souffle::clone(), main, souffle::ram::makeLambdaRamMapper(), Program(), relations, souffle::ast::analysis::sub(), and subroutines.
{
         auto* res = new Program();
         res->main = souffle::clone(main);
         for (auto& rel : relations) {
             res->relations.push_back(souffle::clone(rel));
         }
         for (auto& sub : subroutines) {
             res->subroutines[sub.first] = souffle::clone(sub.second);
         }
         std::map<const Relation*, const Relation*> refMap;
         res->apply(makeLambdaRamMapper([&](Own<Node> node) -> Own<Node> {
             // rewire relation references to newly cloned relations
             if (const RelationReference* relRef = dynamic_cast<RelationReference*>(node.get())) {
                 const Relation* rel = refMap[relRef->get()];
                 assert(rel != nullptr && "dangling RAM relation reference");
                 return mk<RelationReference>(rel);
             } else {
                 return node;
             }
         }));
         return res;
     }
equal()
bool souffle::ram::Program::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 156 of file Program.h.
References souffle::equal_ptr(), souffle::equal_targets(), main, relations, and subroutines.
{
         const auto& other = static_cast<const Program&>(node);
         return equal_targets(relations, other.relations) && equal_ptr(main, other.main) &&
                equal_targets(subroutines, other.subroutines);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Program::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 68 of file Program.h.
References main, relations, souffle::ast::analysis::sub(), and subroutines.
{
         std::vector<const Node*> children;
         children = main->getChildNodes();
         for (auto& rel : relations) {
             children.push_back(rel.get());
         }
         for (auto& sub : subroutines) {
             children.push_back(sub.second.get());
         }
         return children;
     }
getMain()
Statement& souffle::ram::Program::getMain () const inline
Get main program.
Definition at line 81 of file Program.h.
References main.
Referenced by souffle::synthesiser::Synthesiser::generateCode(), and souffle::InterpreterEngine::generateIR().
{
         return *main;
     }
getRelations()
std::vector<Relation*> souffle::ram::Program::getRelations () const inline
Get all relations of RAM program.
Definition at line 86 of file Program.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::generateCode().
{
         return toPtrVector(relations);
     }
getSubroutine()
const Statement& souffle::ram::Program::getSubroutine (const std::string & name) const inline
Get a specific subroutine.
Definition at line 100 of file Program.h.
References subroutines.
{
         return *subroutines.at(name);
     }
getSubroutines()
const std::map<std::string, Statement*> souffle::ram::Program::getSubroutines () const inline
Get all subroutines of a RAM program.
Definition at line 91 of file Program.h.
References souffle::ast::analysis::sub(), and subroutines.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::InterpreterEngine::executeSubroutine(), souffle::synthesiser::Synthesiser::generateCode(), souffle::InterpreterEngine::generateIR(), and souffle::NodeGenerator::visitCall().
{
         std::map<std::string, Statement*> subroutineRefs;
         for (auto& sub : subroutines) {
             subroutineRefs.insert({sub.first, sub.second.get()});
         }
         return subroutineRefs;
     }
print()
void souffle::ram::Program::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 138 of file Program.h.
References main, relations, souffle::ast::analysis::sub(), and subroutines.
{
         out << "PROGRAM" << std::endl;
         out << " DECLARATION" << std::endl;
         for (const auto& rel : relations) {
             out << "  " << *rel << std::endl;
         }
         out << " END DECLARATION" << std::endl;
         for (const auto& sub : subroutines) {
             out << " SUBROUTINE " << sub.first << std::endl;
             sub.second->print(out, 2);
             out << " END SUBROUTINE" << std::endl;
         }
         out << " BEGIN MAIN" << std::endl;
         main->print(out, 2);
         out << " END MAIN" << std::endl;
         out << "END PROGRAM" << std::endl;
     }
Field Documentation
main
Own<Statement> souffle::ram::Program::main protected
Main program.
Definition at line 168 of file Program.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getMain(), and print().
relations
VecOwn<Relation> souffle::ram::Program::relations protected
Relations of RAM program.
Definition at line 165 of file Program.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRelations(), print(), and Program().
subroutines
std::map<std::string, Own<Statement> > souffle::ram::Program::subroutines protected
Subroutines for provenance system.
Definition at line 171 of file Program.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getSubroutine(), getSubroutines(), print(), and Program().
The documentation for this class was generated from the following file:
ram/Program.h