souffle: souffle::Global Class Reference
souffle::Global Class Reference
#include <Global.h>
Public Member Functions
Global (const Global &)=delete
Global & operator= (const Global &)=delete
Static Public Member Functions
static MainConfig & config ()
Private Member Functions
Global ()=default
Detailed Description
Definition at line 128 of file Global.h.
Constructor & Destructor Documentation
Global() [1/2]
souffle::Global::Global (const Global &) delete
Global() [2/2]
souffle::Global::Global () private default
Member Function Documentation
config()
static MainConfig& souffle::Global::config () inline static
Definition at line 135 of file Global.h.
Referenced by souffle::ParserDriver::addDeprecatedTag(), souffle::ram::transform::Transformer::apply(), souffle::compileToBinary(), souffle::ast::analysis::AuxiliaryArityAnalysis::computeArity(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::test::evalExpression(), souffle::executeBinary(), souffle::InterpreterEngine::executeMain(), souffle::synthesiser::Synthesiser::generateCode(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ram::TranslationUnit::getAnalysis(), souffle::ram::analysis::MinIndexSelection::getAttributesToDischarge(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::InterpreterEngine::loadDLL(), souffle::main(), souffle::ParserDriver::mkDeprecatedSubType(), souffle::ast::analysis::SCCGraphAnalysis::print(), souffle::MainConfig::processArgs(), souffle::ast::analysis::TypeAnalysis::run(), souffle::ast::analysis::ProfileUseAnalysis::run(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::transform::IODefaultsTransformer::setDefaults(), souffle::ast::transform::MagicSetTransformer::shouldRun(), souffle::ram::test::TEST(), souffle::ram::test::testInterpreterStore(), souffle::ast::transform::PragmaChecker::transform(), souffle::ast::transform::ReorderLiteralsTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::AstToRamTranslator::translateConstraint(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), souffle::AstToRamTranslator::translateProgram(), souffle::AstToRamTranslator::translateRecursiveRelation(), souffle::AstToRamTranslator::translateUnit(), and souffle::ast::transform::TypeChecker::visitAtom().
{
         static MainConfig _config;
         return _config;
     }
operator=()
Global& souffle::Global::operator= (const Global &) delete
The documentation for this class was generated from the following file:
Global.h