souffle: souffle::ast::transform::UniqueAggregationVariablesTransformer Class Reference
souffle::ast::transform::UniqueAggregationVariablesTransformer Class Reference
Transformation pass to rename aggregation variables to make them unique.
#include <UniqueAggregationVariables.h>
Public Member Functions
UniqueAggregationVariablesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to rename aggregation variables to make them unique.
Definition at line 26 of file UniqueAggregationVariables.h.
Member Function Documentation
clone()
UniqueAggregationVariablesTransformer* souffle::ast::transform::UniqueAggregationVariablesTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 32 of file UniqueAggregationVariables.h.
References transform().
{
         return new UniqueAggregationVariablesTransformer();
     }
getName()
std::string souffle::ast::transform::UniqueAggregationVariablesTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 28 of file UniqueAggregationVariables.h.
{
         return "UniqueAggregationVariablesTransformer";
     }
transform()
bool souffle::ast::transform::UniqueAggregationVariablesTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 28 of file UniqueAggregationVariables.cpp.
References souffle::ast::TranslationUnit::getProgram(), souffle::ast::Aggregator::getTargetExpression(), souffle::toString(), souffle::ast::visitDepthFirst(), and souffle::ast::visitDepthFirstPostOrder().
Referenced by clone().
{
     bool changed = false;
     // make variables in aggregates unique
     int aggNumber = 0;
     Program& program = translationUnit.getProgram();
     visitDepthFirstPostOrder(program, [&](const Aggregator& agg) {
         // only applicable for aggregates with target expression
         if (agg.getTargetExpression() == nullptr) {
             return;
         }
         // get all variables in the target expression
         std::set<std::string> names;
         visitDepthFirst(
                 *agg.getTargetExpression(), [&](const ast::Variable& var) { names.insert(var.getName()); });
         // rename them
         visitDepthFirst(agg, [&](const ast::Variable& var) {
             auto pos = names.find(var.getName());
             if (pos == names.end()) {
                 return;
             }
             const_cast<ast::Variable&>(var).setName(" " + var.getName() + toString(aggNumber));
             changed = true;
         });
         // increment aggregation number
         aggNumber++;
     });
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/UniqueAggregationVariables.h
ast/transform/UniqueAggregationVariables.cpp