souffle: souffle::ram::AbstractLog Class Reference
souffle::ram::AbstractLog Class Reference
Abstract class for logging.
#include <AbstractLog.h>
Public Member Functions
AbstractLog (Own< Statement > stmt, std::string msg)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const std::string & getMessage () const
Get logging message.
const Statement & getStatement () const
Get logging statement.
Protected Member Functions
bool equal (const Node &node) const
Protected Attributes
std::string message
logging message
Own< Statement > statement
logging statement
Detailed Description
Abstract class for logging.
Comprises a Statement and the message (string) to be logged
Definition at line 35 of file AbstractLog.h.
Constructor & Destructor Documentation
AbstractLog()
souffle::ram::AbstractLog::AbstractLog (Own< Statement > stmt, std::string msg) inline
Definition at line 37 of file AbstractLog.h.
References statement.
                                                     : statement(std::move(stmt)), message(std::move(msg)) {
         assert(statement && "log statement is a nullptr");
     }
Member Function Documentation
apply()
void souffle::ram::AbstractLog::apply (const NodeMapper & map) inline
Definition at line 55 of file AbstractLog.h.
References souffle::map(), and statement.
Referenced by souffle::ram::DebugInfo::apply(), souffle::ram::LogTimer::apply(), and souffle::ram::LogRelationTimer::apply().
{
         statement = map(std::move(statement));
     }
equal()
bool souffle::ram::AbstractLog::equal (const Node & node) const inline protected
Definition at line 60 of file AbstractLog.h.
References souffle::equal_ptr(), message, and statement.
{
         const auto& other = dynamic_cast<const AbstractLog&>(node);
         return equal_ptr(statement, other.statement) && message == other.message;
     }
getChildNodes()
std::vector<const Node*> souffle::ram::AbstractLog::getChildNodes () const inline
Definition at line 41 of file AbstractLog.h.
References statement.
Referenced by souffle::ram::DebugInfo::getChildNodes(), souffle::ram::LogTimer::getChildNodes(), and souffle::ram::LogRelationTimer::getChildNodes().
{
         return {statement.get()};
     }
getMessage()
const std::string& souffle::ram::AbstractLog::getMessage () const inline
Get logging message.
Definition at line 46 of file AbstractLog.h.
References message.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return message;
     }
getStatement()
const Statement& souffle::ram::AbstractLog::getStatement () const inline
Get logging statement.
Definition at line 51 of file AbstractLog.h.
References statement.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::visitDebugInfo(), souffle::NodeGenerator::visitLogRelationTimer(), and souffle::NodeGenerator::visitLogTimer().
{
         return *statement;
     }
Field Documentation
message
std::string souffle::ram::AbstractLog::message protected
logging message
Definition at line 70 of file AbstractLog.h.
Referenced by souffle::ram::DebugInfo::clone(), souffle::ram::LogTimer::clone(), souffle::ram::LogRelationTimer::clone(), equal(), getMessage(), souffle::ram::DebugInfo::print(), souffle::ram::LogTimer::print(), and souffle::ram::LogRelationTimer::print().
statement
Own<Statement> souffle::ram::AbstractLog::statement protected
logging statement
Definition at line 67 of file AbstractLog.h.
Referenced by AbstractLog(), apply(), souffle::ram::DebugInfo::clone(), souffle::ram::LogTimer::clone(), souffle::ram::LogRelationTimer::clone(), equal(), getChildNodes(), getStatement(), souffle::ram::DebugInfo::print(), souffle::ram::LogTimer::print(), and souffle::ram::LogRelationTimer::print().
The documentation for this class was generated from the following file:
ram/AbstractLog.h