souffle: souffle::ram::transform::EliminateDuplicatesTransformer Class Reference
souffle::ram::transform::EliminateDuplicatesTransformer Class Reference
Eliminates duplicated conjunctive terms.
#include <EliminateDuplicates.h>
Public Member Functions
bool eliminateDuplicates (Program &program)
Eliminate duplicated conjunctive terms.
std::string getName () const override
get name of the transformer
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Eliminates duplicated conjunctive terms.
For example ..
QUERY
 ...
  IF C1 /\ C2 /\ ... /\  CN
    ...
will be rewritten to
QUERY
 ...
  IF C2 /\ ... /\ CN then
   ...
assuming that C1 and C2 are equal.
Definition at line 49 of file EliminateDuplicates.h.
Member Function Documentation
eliminateDuplicates()
bool souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates (Program & program)
Eliminate duplicated conjunctive terms.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 31 of file EliminateDuplicates.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::clone(), souffle::filter(), i, j, souffle::ram::makeLambdaRamMapper(), souffle::ram::toCondition(), souffle::ram::toConjunctionList(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> filterRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const Filter* filter = dynamic_cast<Filter*>(node.get())) {
                 const Condition* condition = &filter->getCondition();
                 VecOwn<Condition> conds = toConjunctionList(condition);
                 bool eliminatedDuplicate = false;
                 for (std::size_t i = 0; i < conds.size(); i++) {
                     for (std::size_t j = i + 1; j < conds.size(); j++) {
                         if (*conds[i] == *conds[j]) {
                             conds.erase(conds.begin() + j);
                             i = -1;
                             eliminatedDuplicate = true;
                             break;
                         }
                     }
                 }
                 if (eliminatedDuplicate) {
                     changed = true;
                     node = mk<Filter>(
                             Own<Condition>(toCondition(conds)), souffle::clone(&filter->getOperation()));
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ram::transform::EliminateDuplicatesTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 51 of file EliminateDuplicates.h.
References eliminateDuplicates().
{
         return "EliminateDuplicatesTransformer";
     }
transform()
bool souffle::ram::transform::EliminateDuplicatesTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 63 of file EliminateDuplicates.h.
References eliminateDuplicates(), and souffle::ram::TranslationUnit::getProgram().
{
         return eliminateDuplicates(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/EliminateDuplicates.h
ram/transform/EliminateDuplicates.cpp