souffle: souffle::ram::IndexScan Class Reference
souffle::ram::IndexScan Class Reference
Search for tuples of a relation matching a criteria.
#include <IndexScan.h>
Public Member Functions
IndexScan * clone () const override
Create a clone (i.e.
IndexScan (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::IndexOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< Expression * >, std::vector< Expression * > > getRangePattern () const
Get range pattern.
IndexOperation (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
void printIndex (std::ostream &os) const
Helper method for printing.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::IndexOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::IndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Search for tuples of a relation matching a criteria.
For example:
QUERY
 ...
 FOR t1 IN X ON INDEX t1.c = t0.0
 ...
Definition at line 48 of file IndexScan.h.
Constructor & Destructor Documentation
IndexScan()
souffle::ram::IndexScan::IndexScan (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText = "") inline
Definition at line 50 of file IndexScan.h.
Referenced by clone().
             : IndexOperation(std::move(r), ident, std::move(queryPattern), std::move(nested),
                       std::move(profileText)) {}
Member Function Documentation
clone()
IndexScan* souffle::ram::IndexScan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::ram::IndexOperation.
Reimplemented in souffle::ram::ParallelIndexScan.
Definition at line 55 of file IndexScan.h.
References souffle::clone(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::TupleOperation::getTupleId(), i, IndexScan(), souffle::ram::IndexOperation::queryPattern, and souffle::ram::RelationOperation::relationRef.
Referenced by souffle::ram::test::TEST().
{
         RamPattern resQueryPattern;
         for (const auto& i : queryPattern.first) {
             resQueryPattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             resQueryPattern.second.emplace_back(i->clone());
         }
         return new IndexScan(souffle::clone(relationRef), getTupleId(), std::move(resQueryPattern),
                 souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::ram::IndexScan::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Reimplemented in souffle::ram::ParallelIndexScan.
Definition at line 68 of file IndexScan.h.
References souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::NestedOperation::print(), souffle::ram::IndexOperation::printIndex(), and souffle::times().
{
         const Relation& rel = getRelation();
         os << times(" ", tabpos);
         os << "FOR t" << getTupleId() << " IN ";
         os << rel.getName();
         printIndex(os);
         os << std::endl;
         IndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/IndexScan.h