souffle: souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer Class Reference
souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer Class Reference
Transformer resolving aliases for anonymous records.
#include <ResolveAnonymousRecordAliases.h>
Public Member Functions
ResolveAnonymousRecordAliasesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
std::map< std::string, const RecordInit * > findVariablesRecordMapping (TranslationUnit &, const Clause &)
For each variable equal to some anonymous record, assign a value of that record.
bool replaceNamedVariables (TranslationUnit &, Clause &)
Use mapping found by findVariablesRecordMapping to substitute a records for each variable that operates on records.
bool replaceUnnamedVariable (Clause &)
For unnamed variables, replace each equation _ op record with true.
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformer resolving aliases for anonymous records.
The transformer works by searching the clause for equalities of the form a = [...], where a is an anonymous record, and replacing all occurrences of a with the RHS.
The transformer is to be called in conjunction with FoldAnonymousRecords.
Definition at line 35 of file ResolveAnonymousRecordAliases.h.
Member Function Documentation
clone()
ResolveAnonymousRecordAliasesTransformer* souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 41 of file ResolveAnonymousRecordAliases.h.
References findVariablesRecordMapping(), replaceNamedVariables(), replaceUnnamedVariable(), and transform().
{
         return new ResolveAnonymousRecordAliasesTransformer();
     }
findVariablesRecordMapping()
std::map< std::string, const RecordInit * > souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::findVariablesRecordMapping (TranslationUnit & tu, const Clause & clause) private
For each variable equal to some anonymous record, assign a value of that record.
Definition at line 40 of file ResolveAnonymousRecordAliases.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::analysis::getGroundedTerms(), and souffle::isEqConstraint().
Referenced by clone(), and replaceNamedVariables().
{
     std::map<std::string, const RecordInit*> variableRecordMap;
     auto isVariable = [](Node* node) -> bool { return isA<ast::Variable>(node); };
     auto isRecord = [](Node* node) -> bool { return isA<RecordInit>(node); };
     auto& typeAnalysis = *tu.getAnalysis<analysis::TypeAnalysis>();
     auto groundedTerms = analysis::getGroundedTerms(tu, clause);
     for (auto* literal : clause.getBodyLiterals()) {
         if (auto constraint = dynamic_cast<BinaryConstraint*>(literal)) {
             if (!isEqConstraint(constraint->getOperator())) {
                 continue;
             }
             auto left = constraint->getLHS();
             auto right = constraint->getRHS();
             if (!isVariable(left) && !isVariable(right)) {
                 continue;
             }
             if (!isRecord(left) && !isRecord(right)) {
                 continue;
             }
             // TODO (darth_tytus): This should change in the future.
             // Currently type system assigns to anonymous records {- All types - }
             // which is inelegant.
             if (!typeAnalysis.getTypes(left).isAll()) {
                 continue;
             }
             auto* variable = static_cast<ast::Variable*>(isVariable(left) ? left : right);
             const auto& variableName = variable->getName();
             if (!groundedTerms.find(variable)->second) {
                 continue;
             }
             // We are interested only in the first mapping.
             if (variableRecordMap.find(variableName) != variableRecordMap.end()) {
                 continue;
             }
             auto* record = static_cast<RecordInit*>(isRecord(left) ? left : right);
             variableRecordMap.insert({variableName, record});
         }
     }
     return variableRecordMap;
 }
getName()
std::string souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 37 of file ResolveAnonymousRecordAliases.h.
{
         return "ResolveAnonymousRecordAliases";
     }
replaceNamedVariables()
bool souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::replaceNamedVariables (TranslationUnit & tu, Clause & clause) private
Use mapping found by findVariablesRecordMapping to substitute a records for each variable that operates on records.
Definition at line 95 of file ResolveAnonymousRecordAliases.cpp.
References souffle::ast::Clause::apply(), souffle::clone(), and findVariablesRecordMapping().
Referenced by clone(), and transform().
{
     struct ReplaceVariables : public NodeMapper {
         std::map<std::string, const RecordInit*> varToRecordMap;
         ReplaceVariables(std::map<std::string, const RecordInit*> varToRecordMap)
                 : varToRecordMap(std::move(varToRecordMap)){};
         Own<Node> operator()(Own<Node> node) const override {
             if (auto variable = dynamic_cast<ast::Variable*>(node.get())) {
                 auto iteratorToRecord = varToRecordMap.find(variable->getName());
                 if (iteratorToRecord != varToRecordMap.end()) {
                     return souffle::clone(iteratorToRecord->second);
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     auto variableToRecordMap = findVariablesRecordMapping(tu, clause);
     bool changed = variableToRecordMap.size() > 0;
     if (changed) {
         ReplaceVariables update(std::move(variableToRecordMap));
         clause.apply(update);
     }
     return changed;
 }
replaceUnnamedVariable()
bool souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::replaceUnnamedVariable (Clause & clause) private
For unnamed variables, replace each equation _ op record with true.
Definition at line 125 of file ResolveAnonymousRecordAliases.cpp.
References souffle::ast::Clause::apply(), and souffle::isEqConstraint().
Referenced by clone(), and transform().
{
     struct ReplaceUnnamed : public NodeMapper {
         mutable bool changed{false};
         ReplaceUnnamed() = default;
         Own<Node> operator()(Own<Node> node) const override {
             auto isUnnamed = [](Node* node) -> bool { return isA<UnnamedVariable>(node); };
             auto isRecord = [](Node* node) -> bool { return isA<RecordInit>(node); };
             if (auto constraint = dynamic_cast<BinaryConstraint*>(node.get())) {
                 auto left = constraint->getLHS();
                 auto right = constraint->getRHS();
                 bool hasUnnamed = isUnnamed(left) || isUnnamed(right);
                 bool hasRecord = isRecord(left) || isRecord(right);
                 auto op = constraint->getOperator();
                 if (hasUnnamed && hasRecord && isEqConstraint(op)) {
                     return mk<BooleanConstraint>(true);
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     ReplaceUnnamed update;
     clause.apply(update);
     return update.changed;
 }
transform()
bool souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 157 of file ResolveAnonymousRecordAliases.cpp.
References souffle::ast::Program::getClauses(), souffle::ast::TranslationUnit::getProgram(), replaceNamedVariables(), and replaceUnnamedVariable().
Referenced by clone().
{
     bool changed = false;
     Program& program = translationUnit.getProgram();
     for (auto* clause : program.getClauses()) {
         changed |= replaceNamedVariables(translationUnit, *clause);
         changed |= replaceUnnamedVariable(*clause);
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ResolveAnonymousRecordAliases.h
ast/transform/ResolveAnonymousRecordAliases.cpp