souffle: souffle::ram::transform::ChoiceConversionTransformer Class Reference
souffle::ram::transform::ChoiceConversionTransformer Class Reference
Convert (Scan/If)/(IndexScan/If) operaitons to (Choice)/(IndexChoice) operations.
#include <ChoiceConversion.h>
Public Member Functions
bool convertScans (Program &program)
Apply choice-conversion to the whole program.
std::string getName () const override
get name of the transformer
Own< Operation > rewriteIndexScan (const IndexScan *indexScan)
Rewrite IndexScan operations.
Own< Operation > rewriteScan (const Scan *scan)
Rewrite Scan operations.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
analysis::LevelAnalysis * rla {nullptr}
Detailed Description
Convert (Scan/If)/(IndexScan/If) operaitons to (Choice)/(IndexChoice) operations.
If there exists Scan/IndexScan operations in the RAM, and the variables are used in a subsequent Filter operation but no subsequent operation in the tree (up until and including the Project), the operations are rewritten to Choice/IndexChoice operations.
For example,
QUERY
 ...
  FOR t1 IN A ON INDEX t1.x=10 AND t1.y = 20
   IF (t1.x, t1.y) NOT IN A
        ... // no occurrence of t1
will be rewritten to
QUERY
 ...
  CHOICE A AS t1 ON INDEX t1.x=10 AND t1.y = 20
  WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 61 of file ChoiceConversion.h.
Member Function Documentation
convertScans()
bool souffle::ram::transform::ChoiceConversionTransformer::convertScans (Program & program)
Apply choice-conversion to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Search for queries and rewrite their Scan/IndexScan and If operations if possible.
Definition at line 114 of file ChoiceConversion.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::ram::makeLambdaRamMapper(), rewriteIndexScan(), rewriteScan(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> scanRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const Scan* scan = dynamic_cast<Scan*>(node.get())) {
                 if (Own<Operation> op = rewriteScan(scan)) {
                     changed = true;
                     node = std::move(op);
                 }
             } else if (const IndexScan* indexScan = dynamic_cast<IndexScan*>(node.get())) {
                 if (Own<Operation> op = rewriteIndexScan(indexScan)) {
                     changed = true;
                     node = std::move(op);
                 }
             }
             node->apply(makeLambdaRamMapper(scanRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(scanRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ram::transform::ChoiceConversionTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 63 of file ChoiceConversion.h.
References convertScans(), rewriteIndexScan(), and rewriteScan().
{
         return "ChoiceConversionTransformer";
     }
rewriteIndexScan()
Own< Operation > souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan (const IndexScan * indexScan)
Rewrite IndexScan operations.
Parameters
An index operation
Returns
The old operation if the if-conversion fails; otherwise the IndexChoice operation
Rewrites IndexScan/If pair to an IndexChoice operation if value is not used in a consecutive RAM operation
Definition at line 65 of file ChoiceConversion.cpp.
References souffle::ram::Expression::clone(), souffle::clone(), souffle::filter(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::IndexOperation::getRangePattern(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::TupleElement::getTupleId(), souffle::identifier(), rla, and souffle::ram::visitDepthFirst().
Referenced by convertScans(), and getName().
{
     bool transformTuple = false;
     // Check that Filter follows the IndexScan in the loop nest
     if (const auto* filter = dynamic_cast<const Filter*>(&indexScan->getOperation())) {
         // Check that the Filter uses the identifier in the IndexScan
         if (rla->getLevel(&filter->getCondition()) == indexScan->getTupleId()) {
             transformTuple = true;
             // Check that the filter is not referred to after
             const auto* nextNode = dynamic_cast<const Node*>(&filter->getOperation());
             visitDepthFirst(*nextNode, [&](const TupleElement& element) {
                 if (element.getTupleId() == indexScan->getTupleId()) {
                     transformTuple = false;
                 }
             });
         }
     }
     // Convert the IndexScan/If pair into an IndexChoice
     if (transformTuple) {
         RamPattern newValues;
         const auto* filter = dynamic_cast<const Filter*>(&indexScan->getOperation());
         const int identifier = indexScan->getTupleId();
         const Relation& rel = indexScan->getRelation();
         for (auto& cur : indexScan->getRangePattern().first) {
             Expression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.first.emplace_back(val);
         }
         for (auto& cur : indexScan->getRangePattern().second) {
             Expression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.second.emplace_back(val);
         }
         return mk<IndexChoice>(mk<RelationReference>(&rel), identifier,
                 souffle::clone(&filter->getCondition()), std::move(newValues),
                 souffle::clone(&filter->getOperation()), indexScan->getProfileText());
     }
     return nullptr;
 }
rewriteScan()
Own< Operation > souffle::ram::transform::ChoiceConversionTransformer::rewriteScan (const Scan * scan)
Rewrite Scan operations.
Parameters
A scan operation
Returns
The old operation if the if-conversion fails; otherwise the Choice operation
Rewrites Scan/If pair to a Choice operation if value is not used in a consecutive RAM operation
Definition at line 32 of file ChoiceConversion.cpp.
References souffle::clone(), souffle::filter(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::TupleElement::getTupleId(), souffle::identifier(), rla, and souffle::ram::visitDepthFirst().
Referenced by convertScans(), and getName().
{
     bool transformTuple = false;
     // Check that Filter follows the Scan in the loop nest
     if (const auto* filter = dynamic_cast<const Filter*>(&scan->getOperation())) {
         // Check that the Filter uses the identifier in the Scan
         if (rla->getLevel(&filter->getCondition()) == scan->getTupleId()) {
             transformTuple = true;
             // Check that the filter is not referred to after
             const auto* nextNode = dynamic_cast<const Node*>(&filter->getOperation());
             visitDepthFirst(*nextNode, [&](const TupleElement& element) {
                 if (element.getTupleId() == scan->getTupleId()) {
                     transformTuple = false;
                 }
             });
         }
     }
     // Convert the Scan/If pair into a Choice
     if (transformTuple) {
         VecOwn<Expression> newValues;
         const auto* filter = dynamic_cast<const Filter*>(&scan->getOperation());
         const int identifier = scan->getTupleId();
         return mk<Choice>(mk<RelationReference>(&scan->getRelation()), identifier,
                 souffle::clone(&filter->getCondition()), souffle::clone(&filter->getOperation()),
                 scan->getProfileText());
     }
     return nullptr;
 }
transform()
bool souffle::ram::transform::ChoiceConversionTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 98 of file ChoiceConversion.h.
References convertScans(), souffle::ram::TranslationUnit::getAnalysis(), souffle::ram::TranslationUnit::getProgram(), and rla.
{
         rla = translationUnit.getAnalysis<analysis::LevelAnalysis>();
         return convertScans(translationUnit.getProgram());
     }
Field Documentation
rla
analysis::LevelAnalysis* souffle::ram::transform::ChoiceConversionTransformer::rla {nullptr} protected
Definition at line 97 of file ChoiceConversion.h.
Referenced by rewriteIndexScan(), rewriteScan(), and transform().
The documentation for this class was generated from the following files:
ram/transform/ChoiceConversion.h
ram/transform/ChoiceConversion.cpp