souffle: souffle::ast::transform::RemoveEmptyRelationsTransformer Class Reference
souffle::ast::transform::RemoveEmptyRelationsTransformer Class Reference
Transformation pass to remove all empty relations and rules that use empty relations.
#include <RemoveEmptyRelations.h>
Public Member Functions
RemoveEmptyRelationsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Static Public Member Functions
static bool removeEmptyRelations (TranslationUnit &translationUnit)
Eliminate all empty relations (and their uses) in the given program.
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static bool removeEmptyRelationUses (TranslationUnit &translationUnit, const QualifiedName &emptyRelation)
Eliminate rules that contain empty relations and/or rewrite them.
Detailed Description
Transformation pass to remove all empty relations and rules that use empty relations.
Definition at line 27 of file RemoveEmptyRelations.h.
Member Function Documentation
clone()
RemoveEmptyRelationsTransformer* souffle::ast::transform::RemoveEmptyRelationsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 41 of file RemoveEmptyRelations.h.
{
         return new RemoveEmptyRelationsTransformer();
     }
getName()
std::string souffle::ast::transform::RemoveEmptyRelationsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 29 of file RemoveEmptyRelations.h.
References removeEmptyRelations().
{
         return "RemoveEmptyRelationsTransformer";
     }
removeEmptyRelations()
bool souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations (TranslationUnit & translationUnit) static
Eliminate all empty relations (and their uses) in the given program.
Parameters
translationUnit the program to be processed
Returns
whether the program was modified
Definition at line 36 of file RemoveEmptyRelations.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::getAtomRelation(), souffle::ast::Aggregator::getBodyLiterals(), souffle::ast::getClauses(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getRelations(), removeEmptyRelationUses(), souffle::ast::removeRelation(), and souffle::ast::visitDepthFirst().
Referenced by getName(), and transform().
{
     Program& program = translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<analysis::IOTypeAnalysis>();
     std::set<QualifiedName> emptyRelations;
     bool changed = false;
     for (auto rel : program.getRelations()) {
         if (!getClauses(program, *rel).empty() || ioTypes->isInput(rel)) {
             continue;
         }
         emptyRelations.insert(rel->getQualifiedName());
         bool usedInAggregate = false;
         visitDepthFirst(program, [&](const Aggregator& agg) {
             for (const auto lit : agg.getBodyLiterals()) {
                 visitDepthFirst(*lit, [&](const Atom& atom) {
                     if (getAtomRelation(&atom, &program) == rel) {
                         usedInAggregate = true;
                     }
                 });
             }
         });
         if (!usedInAggregate && !ioTypes->isOutput(rel)) {
             removeRelation(translationUnit, rel->getQualifiedName());
             changed = true;
         }
     }
     for (const auto& relName : emptyRelations) {
         changed |= removeEmptyRelationUses(translationUnit, relName);
     }
     return changed;
 }
removeEmptyRelationUses()
bool souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses (TranslationUnit & translationUnit, const QualifiedName & emptyRelation) static private
Eliminate rules that contain empty relations and/or rewrite them.
Parameters
translationUnit the program to be processed
emptyRelation relation that is empty
Returns
whether the program was modified
Definition at line 71 of file RemoveEmptyRelations.cpp.
References souffle::ast::Program::addClause(), clauses, souffle::clone(), souffle::ast::cloneHead(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::removeClause(), and souffle::ast::visitDepthFirst().
Referenced by removeEmptyRelations(), and transform().
{
     Program& program = translationUnit.getProgram();
     bool changed = false;
     //
     // (1) drop rules from the program that have empty relations in their bodies.
     // (2) drop negations of empty relations
     //
     // get all clauses
     std::vector<const Clause*> clauses;
     visitDepthFirst(program, [&](const Clause& cur) { clauses.push_back(&cur); });
     // clean all clauses
     for (const Clause* cl : clauses) {
         // check for an atom whose relation is the empty relation
         bool removed = false;
         for (Literal* lit : cl->getBodyLiterals()) {
             if (auto* arg = dynamic_cast<Atom*>(lit)) {
                 if (arg->getQualifiedName() == emptyRelationName) {
                     program.removeClause(cl);
                     removed = true;
                     changed = true;
                     break;
                 }
             }
         }
         if (!removed) {
             // check whether a negation with empty relations exists
             bool rewrite = false;
             for (Literal* lit : cl->getBodyLiterals()) {
                 if (auto* neg = dynamic_cast<Negation*>(lit)) {
                     if (neg->getAtom()->getQualifiedName() == emptyRelationName) {
                         rewrite = true;
                         break;
                     }
                 }
             }
             if (rewrite) {
                 // clone clause without negation for empty relations
                 auto res = Own<Clause>(cloneHead(cl));
                 for (Literal* lit : cl->getBodyLiterals()) {
                     if (auto* neg = dynamic_cast<Negation*>(lit)) {
                         if (neg->getAtom()->getQualifiedName() != emptyRelationName) {
                             res->addToBody(souffle::clone(lit));
                         }
                     } else {
                         res->addToBody(souffle::clone(lit));
                     }
                 }
                 program.removeClause(cl);
                 program.addClause(std::move(res));
                 changed = true;
             }
         }
     }
     return changed;
 }
transform()
bool souffle::ast::transform::RemoveEmptyRelationsTransformer::transform (TranslationUnit & translationUnit) inline override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 46 of file RemoveEmptyRelations.h.
References removeEmptyRelations(), and removeEmptyRelationUses().
{
         return removeEmptyRelations(translationUnit);
     }
The documentation for this class was generated from the following files:
ast/transform/RemoveEmptyRelations.h
ast/transform/RemoveEmptyRelations.cpp