souffle: souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer Class Reference
souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer Class Reference
Runs the second stage of the labelling algorithm.
#include <MagicSet.h>
Public Member Functions
PositiveLabellingTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static QualifiedName getPositiveLabel (const QualifiedName &name, size_t count)
Provide a unique name for a positively labelled relation copy.
Detailed Description
Runs the second stage of the labelling algorithm.
Separates out the dependencies of negatively labelled atoms from the main SCC graph, preventing them from affecting stratification after magic. Note: Negative labelling must have been run first.
Definition at line 185 of file MagicSet.h.
Member Function Documentation
clone()
PositiveLabellingTransformer* souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 191 of file MagicSet.h.
References souffle::test::count(), and souffle::ast::transform::MagicSetTransformer::transform().
{
         return new PositiveLabellingTransformer();
     }
getName()
std::string souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 187 of file MagicSet.h.
{
         return "PositiveLabellingTransformer";
     }
getPositiveLabel()
QualifiedName souffle::ast::transform::PositiveLabellingTransformer::getPositiveLabel (const QualifiedName & name, size_t count) static private
Provide a unique name for a positively labelled relation copy.
Definition at line 676 of file MagicSet.cpp.
References souffle::test::count(), and souffle::ast::QualifiedName::prepend().
{
     std::stringstream label;
     label << "@poscopy_" << count;
     QualifiedName labelledName(name);
     labelledName.prepend(label.str());
     return labelledName;
 }
transform()
bool souffle::ast::transform::PositiveLabellingTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 756 of file MagicSet.cpp.
References souffle::ast::Program::addClause(), souffle::ast::Program::addRelation(), clauses, souffle::clone(), souffle::contains(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::getClauses(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::Program::getRelations(), souffle::ast::renameAtoms(), and souffle::ast::visitDepthFirst().
{
     Program& program = translationUnit.getProgram();
     const auto& sccGraph = *translationUnit.getAnalysis<analysis::SCCGraphAnalysis>();
     const auto& precedenceGraph = translationUnit.getAnalysis<analysis::PrecedenceGraphAnalysis>()->graph();
     auto ignoredRelations = getIgnoredRelations(translationUnit);
     // Partition the strata into neglabelled and regular
     std::set<size_t> neglabelledStrata;
     std::map<size_t, size_t> originalStrataCopyCount;
     for (size_t stratum = 0; stratum < sccGraph.getNumberOfSCCs(); stratum++) {
         size_t numNeggedRelations = 0;
         const auto& stratumRels = sccGraph.getInternalRelations(stratum);
         // Count how many relations in this node are neglabelled
         for (const auto* rel : stratumRels) {
             if (isNegativelyLabelled(rel->getQualifiedName())) {
                 numNeggedRelations++;
             }
         }
         assert((numNeggedRelations == 0 || numNeggedRelations == stratumRels.size()) &&
                 "stratum cannot contain a mix of neglabelled and unlabelled relations");
         if (numNeggedRelations > 0) {
             // This is a neglabelled stratum that will not be copied
             neglabelledStrata.insert(stratum);
         } else {
             // This is a regular stratum that may be copied
             originalStrataCopyCount[stratum] = 0;
         }
     }
     // Keep track of strata that depend on each stratum
     // e.g. T in dependentStrata[S] iff a relation in T depends on a relation in S
     std::map<size_t, std::set<size_t>> dependentStrata;
     for (size_t stratum = 0; stratum < sccGraph.getNumberOfSCCs(); stratum++) {
         dependentStrata[stratum] = std::set<size_t>();
     }
     for (const auto* rel : program.getRelations()) {
         size_t stratum = sccGraph.getSCC(rel);
         precedenceGraph.visitDepthFirst(rel, [&](const auto* dependentRel) {
             dependentStrata[stratum].insert(sccGraph.getSCC(dependentRel));
         });
     }
     // Label the positive derived literals in the clauses of neglabelled relations
     // Need a new copy of those relations up to that point for each
     for (size_t stratum = 0; stratum < sccGraph.getNumberOfSCCs(); stratum++) {
         if (!contains(neglabelledStrata, stratum)) continue;
         // Rename in the current stratum
         for (const auto* rel : sccGraph.getInternalRelations(stratum)) {
             assert(isNegativelyLabelled(rel->getQualifiedName()) &&
                     "should only be looking at neglabelled strata");
             const auto& clauses = getClauses(program, *rel);
             std::set<QualifiedName> relsToCopy;
             // Get the unignored unlabelled relations appearing in the rules
             for (const auto* clause : clauses) {
                 visitDepthFirst(*clause, [&](const Atom& atom) {
                     const auto& name = atom.getQualifiedName();
                     if (!contains(ignoredRelations, name) && !isNegativelyLabelled(name)) {
                         relsToCopy.insert(name);
                     }
                 });
             }
             // Positively label them
             for (auto* clause : clauses) {
                 std::map<QualifiedName, QualifiedName> labelledNames;
                 for (const auto& relName : relsToCopy) {
                     size_t relStratum = sccGraph.getSCC(getRelation(program, relName));
                     size_t copyCount = originalStrataCopyCount.at(relStratum) + 1;
                     labelledNames[relName] = getPositiveLabel(relName, copyCount);
                 }
                 renameAtoms(*clause, labelledNames);
             }
         }
         // Create the rules (from all previous strata) for the newly positive labelled literals
         for (int preStratum = stratum - 1; preStratum >= 0; preStratum--) {
             if (contains(neglabelledStrata, preStratum)) continue;
             if (!contains(dependentStrata[preStratum], stratum)) continue;
             for (const auto* rel : sccGraph.getInternalRelations(preStratum)) {
                 if (contains(ignoredRelations, rel->getQualifiedName())) continue;
                 for (const auto* clause : getClauses(program, rel->getQualifiedName())) {
                     // Grab the new names for all unignored unlabelled positive atoms
                     std::map<QualifiedName, QualifiedName> labelledNames;
                     visitDepthFirst(*clause, [&](const Atom& atom) {
                         const auto& relName = atom.getQualifiedName();
                         if (contains(ignoredRelations, relName) || isNegativelyLabelled(relName)) return;
                         size_t relStratum = sccGraph.getSCC(getRelation(program, relName));
                         size_t copyCount = originalStrataCopyCount.at(relStratum) + 1;
                         labelledNames[relName] = getPositiveLabel(relName, copyCount);
                     });
                     // Rename atoms accordingly
                     auto labelledClause = souffle::clone(clause);
                     renameAtoms(*labelledClause, labelledNames);
                     program.addClause(std::move(labelledClause));
                 }
             }
             originalStrataCopyCount[preStratum]++;
         }
     }
     // Add each copy for each relation in
     bool changed = false;
     for (const auto& [stratum, numCopies] : originalStrataCopyCount) {
         const auto& stratumRels = sccGraph.getInternalRelations(stratum);
         for (size_t copy = 0; copy < numCopies; copy++) {
             for (auto* rel : stratumRels) {
                 auto newRelation = souffle::clone(rel);
                 newRelation->setQualifiedName(getPositiveLabel(newRelation->getQualifiedName(), copy + 1));
                 program.addRelation(std::move(newRelation));
                 changed = true;
             }
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp