souffle: souffle::ast::transform::RemoveTypecastsTransformer Class Reference
souffle::ast::transform::RemoveTypecastsTransformer Class Reference
Transformation to remove typecasts.
#include <RemoveTypecasts.h>
Public Member Functions
RemoveTypecastsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation to remove typecasts.
Definition at line 28 of file RemoveTypecasts.h.
Member Function Documentation
clone()
RemoveTypecastsTransformer* souffle::ast::transform::RemoveTypecastsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 37 of file RemoveTypecasts.h.
{
         return new RemoveTypecastsTransformer();
     }
getName()
std::string souffle::ast::transform::RemoveTypecastsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 33 of file RemoveTypecasts.h.
{
         return "RemoveTypecastsTransformer";
     }
transform()
bool souffle::ast::transform::RemoveTypecastsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 27 of file RemoveTypecasts.cpp.
References souffle::ast::Program::apply(), souffle::clone(), and souffle::ast::TranslationUnit::getProgram().
{
     struct TypecastRemover : public NodeMapper {
         mutable bool changed{false};
         Own<Node> operator()(Own<Node> node) const override {
             // remove sub-typecasts first
             node->apply(*this);
             // if current node is a typecast, replace with the value directly
             if (auto* cast = dynamic_cast<ast::TypeCast*>(node.get())) {
                 changed = true;
                 return souffle::clone(cast->getValue());
             }
             // otherwise, return the original node
             return node;
         }
     };
     TypecastRemover update;
     Program& program = translationUnit.getProgram();
     program.apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveTypecasts.h
ast/transform/RemoveTypecasts.cpp