souffle: souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer Class Reference
souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer Class Reference
Runs the first stage of the labelling algorithm.
#include <MagicSet.h>
Public Member Functions
NegativeLabellingTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static QualifiedName getNegativeLabel (const QualifiedName &name)
Provide a unique name for negatively-labelled relations.
Detailed Description
Runs the first stage of the labelling algorithm.
Separates out negated appearances of relations from the main SCC graph, preventing them from affecting stratification once magic dependencies are added.
Definition at line 162 of file MagicSet.h.
Member Function Documentation
clone()
NegativeLabellingTransformer* souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 168 of file MagicSet.h.
References souffle::ast::transform::MagicSetTransformer::transform().
{
         return new NegativeLabellingTransformer();
     }
getName()
std::string souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 164 of file MagicSet.h.
{
         return "NegativeLabellingTransformer";
     }
getNegativeLabel()
QualifiedName souffle::ast::transform::NegativeLabellingTransformer::getNegativeLabel (const QualifiedName & name) static private
Provide a unique name for negatively-labelled relations.
Definition at line 670 of file MagicSet.cpp.
References souffle::ast::QualifiedName::prepend().
{
     QualifiedName newName(name);
     newName.prepend("@neglabel");
     return newName;
 }
transform()
bool souffle::ast::transform::NegativeLabellingTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 690 of file MagicSet.cpp.
References souffle::clone(), souffle::contains(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Negation::getAtom(), souffle::ast::getClauses(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::renameAtoms(), and souffle::ast::visitDepthFirst().
{
     const auto& sccGraph = *translationUnit.getAnalysis<analysis::SCCGraphAnalysis>();
     Program& program = translationUnit.getProgram();
     std::set<QualifiedName> relationsToLabel;
     std::set<Own<Clause>> clausesToAdd;
     auto ignoredRelations = getIgnoredRelations(translationUnit);
     // Negatively label all relations that might affect stratification after MST
     //      - Negated relations
     //      - Relations that appear in aggregators
     visitDepthFirst(program, [&](const Negation& neg) {
         auto* atom = neg.getAtom();
         auto relName = atom->getQualifiedName();
         if (contains(ignoredRelations, relName)) return;
         atom->setQualifiedName(getNegativeLabel(relName));
         relationsToLabel.insert(relName);
     });
     visitDepthFirst(program, [&](const Aggregator& aggr) {
         visitDepthFirst(aggr, [&](const Atom& atom) {
             auto relName = atom.getQualifiedName();
             if (contains(ignoredRelations, relName)) return;
             const_cast<Atom&>(atom).setQualifiedName(getNegativeLabel(relName));
             relationsToLabel.insert(relName);
         });
     });
     // Copy over the rules for labelled relations one stratum at a time
     for (size_t stratum = 0; stratum < sccGraph.getNumberOfSCCs(); stratum++) {
         // Check which relations to label in this stratum
         const auto& stratumRels = sccGraph.getInternalRelations(stratum);
         std::map<QualifiedName, QualifiedName> newSccFriendNames;
         for (const auto* rel : stratumRels) {
             auto relName = rel->getQualifiedName();
             if (contains(ignoredRelations, relName)) continue;
             relationsToLabel.insert(relName);
             newSccFriendNames[relName] = getNegativeLabel(relName);
         }
         // Negatively label the relations in a new copy of this stratum
         for (const auto* rel : stratumRels) {
             for (auto* clause : getClauses(program, rel->getQualifiedName())) {
                 auto neggedClause = souffle::clone(clause);
                 renameAtoms(*neggedClause, newSccFriendNames);
                 clausesToAdd.insert(std::move(neggedClause));
             }
         }
     }
     // Add in all the relations that were labelled
     for (const auto& relName : relationsToLabel) {
         const auto* originalRel = getRelation(program, relName);
         assert(originalRel != nullptr && "unlabelled relation does not exist");
         auto labelledRelation = souffle::clone(originalRel);
         labelledRelation->setQualifiedName(getNegativeLabel(relName));
         program.addRelation(std::move(labelledRelation));
     }
     // Add in all the negged clauses
     for (const auto& clause : clausesToAdd) {
         program.addClause(souffle::clone(clause));
     }
     return !relationsToLabel.empty();
 }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp