souffle: souffle::ram::Swap Class Reference
souffle::ram::Swap Class Reference
Swap operation with respect to two relations.
#include <Swap.h>
Public Member Functions
Swap * clone () const override
Create a clone (i.e.
Swap (Own< RelationReference > f, Own< RelationReference > s)
Public Member Functions inherited from souffle::ram::BinRelationStatement
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
BinRelationStatement (Own< RelationReference > f, Own< RelationReference > s)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getFirstRelation () const
Get first relation.
const Relation & getSecondRelation () const
Get second relation.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::BinRelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::BinRelationStatement
Own< RelationReference > first
first argument of binary statement
Own< RelationReference > second
second argument of binary statement
Detailed Description
Swap operation with respect to two relations.
Swaps the contents of the two relations
For example:
SWAP(A, B)
Definition at line 39 of file Swap.h.
Constructor & Destructor Documentation
Swap()
souffle::ram::Swap::Swap (Own< RelationReference > f, Own< RelationReference > s) inline
Definition at line 41 of file Swap.h.
Referenced by clone().
             : BinRelationStatement(std::move(f), std::move(s)) {}
Member Function Documentation
clone()
Swap* souffle::ram::Swap::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 44 of file Swap.h.
References souffle::clone(), souffle::ram::BinRelationStatement::first, souffle::ram::BinRelationStatement::second, and Swap().
Referenced by souffle::ram::test::TEST().
{
         return new Swap(souffle::clone(first), souffle::clone(second));
     }
print()
void souffle::ram::Swap::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 49 of file Swap.h.
References souffle::ram::BinRelationStatement::getFirstRelation(), souffle::ram::Relation::getName(), souffle::ram::BinRelationStatement::getSecondRelation(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "SWAP (" << getFirstRelation().getName() << ", " << getSecondRelation().getName() << ")";
         os << std::endl;
     }
The documentation for this class was generated from the following file:
ram/Swap.h