souffle: souffle::ast::Negation Class Reference
souffle::ast::Negation Class Reference
Negation of an atom negated atom.
#include <Negation.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Negation * clone () const override
Create a clone (i.e.
Atom * getAtom () const
Get negated atom.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Negation (Own< Atom > atom, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
Own< Atom > atom
Negated atom.
Detailed Description
Negation of an atom negated atom.
Example: !parent(x,y).
A negated atom can only occur in the body of a clause.
Definition at line 44 of file Negation.h.
Constructor & Destructor Documentation
Negation()
souffle::ast::Negation::Negation (Own< Atom > atom, SrcLocation loc = {}) inline
Definition at line 46 of file Negation.h.
References atom.
Referenced by clone().
 {}) : Literal(std::move(loc)), atom(std::move(atom)) {}
Member Function Documentation
apply()
void souffle::ast::Negation::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 57 of file Negation.h.
References souffle::map().
{
         atom = map(std::move(atom));
     }
clone()
Negation* souffle::ast::Negation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Literal.
Reimplemented in souffle::ast::ProvenanceNegation.
Definition at line 53 of file Negation.h.
References souffle::clone(), souffle::ast::Node::getSrcLoc(), and Negation().
{
         return new Negation(souffle::clone(atom), getSrcLoc());
     }
equal()
bool souffle::ast::Negation::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 70 of file Negation.h.
References souffle::equal_ptr().
{
         assert(isA<Negation>(&node));
         const auto& other = static_cast<const Negation&>(node);
         return equal_ptr(atom, other.atom);
     }
getAtom()
Atom* souffle::ast::Negation::getAtom () const inline
Get negated atom.
Definition at line 49 of file Negation.h.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::AstToRamTranslator::translateConstraint(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNegation().
{
         return atom.get();
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Negation::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 61 of file Negation.h.
{
         return {atom.get()};
     }
print()
void souffle::ast::Negation::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Reimplemented in souffle::ast::ProvenanceNegation.
Definition at line 66 of file Negation.h.
References atom.
{
         os << "!" << *atom;
     }
Field Documentation
atom
Own<Atom> souffle::ast::Negation::atom protected
Negated atom.
Definition at line 77 of file Negation.h.
Referenced by souffle::ast::ProvenanceNegation::clone(), Negation(), souffle::ast::ProvenanceNegation::print(), and print().
The documentation for this class was generated from the following file:
ast/Negation.h