souffle: souffle::ram::analysis::IndexAnalysis Class Reference
souffle::ram::analysis::IndexAnalysis Class Reference
#include <Index.h>
Public Member Functions
MinIndexSelection & getIndexes (const Relation &rel)
get the minimal index cover for a relation
MinIndexSelection & getIndexes (const std::string &relName)
get the minimal index cover for a relation
SearchSignature getSearchSignature (const IndexOperation *search) const
Get index signature for an Ram IndexOperation operation
SearchSignature getSearchSignature (const ExistenceCheck *existCheck) const
Get the index signature for an existence check
SearchSignature getSearchSignature (const ProvenanceExistenceCheck *existCheck) const
Get the index signature for a provenance existence check
SearchSignature getSearchSignature (const Relation *ramRel) const
Get the default index signature for a relation (the total-order index)
IndexAnalysis (const char *id)
bool isTotalSignature (const AbstractExistenceCheck *existCheck) const
index signature of existence check resembles a total index
void print (std::ostream &os) const override
Print the analysis result in HTML format.
void run (const TranslationUnit &translationUnit) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::ram::analysis::Analysis
Analysis (const char *id)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "index-analysis"
Private Attributes
std::map< const Relation *, MinIndexSelection > minIndexCover
minimal index cover for relations, i.e., maps a relation to a set of indexes
Additional Inherited Members
Protected Attributes inherited from souffle::ram::analysis::Analysis
std::string identifier
name of analysis instance
Detailed Description
Definition at line 387 of file Index.h.
Constructor & Destructor Documentation
IndexAnalysis()
souffle::ram::analysis::IndexAnalysis::IndexAnalysis (const char * id) inline
Definition at line 389 of file Index.h.
 : Analysis(id) {}
Member Function Documentation
getIndexes() [1/2]
MinIndexSelection & souffle::ram::analysis::IndexAnalysis::getIndexes (const Relation & rel)
get the minimal index cover for a relation
Parameters
relation
Returns
set of indexes of the minimal index cover
Definition at line 539 of file Index.cpp.
Referenced by souffle::NodeGenerator::encodeIndexPos(), souffle::NodeGenerator::encodeRelation(), and souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter().
{
     auto pos = minIndexCover.find(&rel);
     if (pos != minIndexCover.end()) {
         return pos->second;
     } else {
         auto ret = minIndexCover.insert(std::make_pair(&rel, MinIndexSelection()));
         assert(ret.second);
         return ret.first->second;
     }
 }
getIndexes() [2/2]
MinIndexSelection& souffle::ram::analysis::IndexAnalysis::getIndexes (const std::string & relName)
get the minimal index cover for a relation
Parameters
relation name
Returns
set of indexes of the minimal index cover
getSearchSignature() [1/4]
SearchSignature souffle::ram::analysis::IndexAnalysis::getSearchSignature (const IndexOperation * search) const
Get index signature for an Ram IndexOperation operation
Parameters
Index-relation-search operation
Returns
Index signature of operation
Definition at line 603 of file Index.cpp.
References souffle::ram::analysis::SearchSignature::arity(), souffle::ram::analysis::Equal, souffle::ram::Relation::getArity(), souffle::ram::IndexOperation::getRangePattern(), souffle::ram::RelationOperation::getRelation(), i, souffle::ram::analysis::Inequal, souffle::ram::isUndefValue(), and souffle::ram::analysis::None.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::encodeIndexPos(), and souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter().
{
     size_t arity = search->getRelation().getArity();
     auto lower = search->getRangePattern().first;
     auto upper = search->getRangePattern().second;
     SearchSignature keys(arity);
     for (size_t i = 0; i < arity; ++i) {
         // if both bounds are undefined
         if (isUndefValue(lower[i]) && isUndefValue(upper[i])) {
             keys[i] = AttributeConstraint::None;
             // if bounds are equal we have an equality
         } else if (*lower[i] == *upper[i]) {
             keys[i] = AttributeConstraint::Equal;
         } else {
             keys[i] = AttributeConstraint::Inequal;
         }
     }
     return keys;
 }
getSearchSignature() [2/4]
SearchSignature souffle::ram::analysis::IndexAnalysis::getSearchSignature (const ExistenceCheck * existCheck) const
Get the index signature for an existence check
Parameters
Existence check
Returns
index signature of existence check
Definition at line 644 of file Index.cpp.
References souffle::ram::Relation::getArity(), souffle::ram::AbstractExistenceCheck::getRelation(), and souffle::ram::AbstractExistenceCheck::getValues().
{
     return searchSignature(existCheck->getRelation().getArity(), existCheck->getValues());
 }
getSearchSignature() [3/4]
SearchSignature souffle::ram::analysis::IndexAnalysis::getSearchSignature (const ProvenanceExistenceCheck * existCheck) const
Get the index signature for a provenance existence check
Parameters
Provenance-existence check
Returns
index signature of provenance-existence check
Definition at line 623 of file Index.cpp.
References souffle::ram::analysis::Equal, souffle::ram::Relation::getAuxiliaryArity(), souffle::ram::AbstractExistenceCheck::getRelation(), souffle::ram::AbstractExistenceCheck::getValues(), i, souffle::ram::isUndefValue(), and souffle::ram::analysis::None.
{
     const auto values = provExistCheck->getValues();
     auto auxiliaryArity = provExistCheck->getRelation().getAuxiliaryArity();
     SearchSignature keys(values.size());
     // all payload attributes should be equalities
     for (size_t i = 0; i < values.size() - auxiliaryArity; i++) {
         if (!isUndefValue(values[i])) {
             keys[i] = AttributeConstraint::Equal;
         }
     }
     // all auxiliary attributes should be free
     for (size_t i = values.size() - auxiliaryArity; i < values.size(); i++) {
         keys[i] = AttributeConstraint::None;
     }
     return keys;
 }
getSearchSignature() [4/4]
SearchSignature souffle::ram::analysis::IndexAnalysis::getSearchSignature (const Relation * ramRel) const
Get the default index signature for a relation (the total-order index)
Parameters
ramRel RAM-relation
Returns
total full-signature of the relation
Definition at line 648 of file Index.cpp.
References souffle::ram::Relation::getArity(), and souffle::ram::analysis::SearchSignature::getFullSearchSignature().
{
     return SearchSignature::getFullSearchSignature(ramRel->getArity());
 }
isTotalSignature()
bool souffle::ram::analysis::IndexAnalysis::isTotalSignature (const AbstractExistenceCheck * existCheck) const
index signature of existence check resembles a total index
Parameters
(provenance) existence check
isTotalSignature returns true if all elements of a tuple are used for the the existence check.
Definition at line 652 of file Index.cpp.
References souffle::ram::AbstractExistenceCheck::getValues(), and souffle::ram::isUndefValue().
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
     for (const auto& cur : existCheck->getValues()) {
         if (isUndefValue(cur)) {
             return false;
         }
     }
     return true;
 }
print()
void souffle::ram::analysis::IndexAnalysis::print (std::ostream &) const override virtual
Print the analysis result in HTML format.
Reimplemented from souffle::ram::analysis::Analysis.
Definition at line 550 of file Index.cpp.
References souffle::ram::analysis::SearchSignature::arity(), souffle::ram::analysis::Equal, souffle::ram::analysis::MinIndexSelection::getAllChains(), souffle::ram::analysis::MinIndexSelection::getAllOrders(), souffle::ram::Relation::getName(), souffle::ram::analysis::MinIndexSelection::getSearches(), i, souffle::ram::isUndefValue(), and souffle::join().
{
     for (auto& cur : minIndexCover) {
         const Relation& rel = *cur.first;
         const MinIndexSelection& indexes = cur.second;
         const std::string& relName = rel.getName();
         /* Print searches */
         os << "Relation " << relName << "\n";
         os << "\tNumber of Searches: " << indexes.getSearches().size() << "\n";
         /* print searches */
         for (auto& search : indexes.getSearches()) {
             os << "\t\t";
             os << search;
             os << "\n";
         }
         /* print chains */
         for (auto& chain : indexes.getAllChains()) {
             os << join(chain, "-->") << "\n";
         }
         os << "\n";
         os << "\tNumber of Indexes: " << indexes.getAllOrders().size() << "\n";
         for (auto& order : indexes.getAllOrders()) {
             os << "\t\t";
             os << join(order, "<") << "\n";
             os << "\n";
         }
     }
 }
run()
void souffle::ram::analysis::IndexAnalysis::run (const TranslationUnit & translationUnit) override virtual
Run analysis for a RAM translation unit.
Implements souffle::ram::analysis::Analysis.
Definition at line 472 of file Index.cpp.
References souffle::ram::analysis::MinIndexSelection::addSearch(), souffle::ram::analysis::MinIndexSelection::getAllOrders(), souffle::ram::TranslationUnit::getProgram(), souffle::ram::analysis::MinIndexSelection::getSearches(), souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex(), souffle::ram::analysis::MinIndexSelection::solve(), and souffle::ram::visitDepthFirst().
{
     // After complete:
     // 1. All relations should have at least one index (for full-order search).
     // 2. Two relations involved in a swap operation will have same set of indices.
     // 3. A 0-arity relation will have only one index where LexOrder is defined as empty. A comparator using
     // an empty order should regard all elements as equal and therefore only allow one arbitrary tuple to be
     // inserted.
     //
     // TODO:
     // 0-arity relation in a provenance program still need to be revisited.
     // visit all nodes to collect searches of each relation
     visitDepthFirst(translationUnit.getProgram(), [&](const Node& node) {
         if (const auto* indexSearch = dynamic_cast<const IndexOperation*>(&node)) {
             MinIndexSelection& indexes = getIndexes(indexSearch->getRelation());
             indexes.addSearch(getSearchSignature(indexSearch));
         } else if (const auto* exists = dynamic_cast<const ExistenceCheck*>(&node)) {
             MinIndexSelection& indexes = getIndexes(exists->getRelation());
             indexes.addSearch(getSearchSignature(exists));
         } else if (const auto* provExists = dynamic_cast<const ProvenanceExistenceCheck*>(&node)) {
             MinIndexSelection& indexes = getIndexes(provExists->getRelation());
             indexes.addSearch(getSearchSignature(provExists));
         } else if (const auto* ramRel = dynamic_cast<const Relation*>(&node)) {
             MinIndexSelection& indexes = getIndexes(*ramRel);
             indexes.addSearch(getSearchSignature(ramRel));
         }
     });
     // A swap happen between rel A and rel B indicates A should include all indices of B, vice versa.
     visitDepthFirst(translationUnit.getProgram(), [&](const Swap& swap) {
         // Note: this naive approach will not work if there exists chain or cyclic swapping.
         // e.g.  swap(relA, relB) swap(relB, relC) swap(relC, relA)
         // One need to keep merging the search set until a fixed point where no more index is introduced
         // in any of the relation in a complete iteration.
         //
         // Currently RAM does not have such situation.
         const Relation& relA = swap.getFirstRelation();
         const Relation& relB = swap.getSecondRelation();
         MinIndexSelection& indexesA = getIndexes(relA);
         MinIndexSelection& indexesB = getIndexes(relB);
         // Add all searchSignature of A into B
         for (const auto& signature : indexesA.getSearches()) {
             indexesB.addSearch(signature);
         }
         // Add all searchSignature of B into A
         for (const auto& signature : indexesB.getSearches()) {
             indexesA.addSearch(signature);
         }
     });
     // find optimal indexes for relations
     for (auto& cur : minIndexCover) {
         MinIndexSelection& indexes = cur.second;
         indexes.solve();
     }
     // Only case where indexSet is still empty is when relation has arity == 0
     for (auto& cur : minIndexCover) {
         MinIndexSelection& indexes = cur.second;
         if (indexes.getAllOrders().empty()) {
             indexes.insertDefaultTotalIndex(0);
         }
     }
 }
Field Documentation
minIndexCover
std::map<const Relation*, MinIndexSelection> souffle::ram::analysis::IndexAnalysis::minIndexCover private
minimal index cover for relations, i.e., maps a relation to a set of indexes
Definition at line 452 of file Index.h.
name
constexpr const char* souffle::ram::analysis::IndexAnalysis::name = "index-analysis" static
Definition at line 391 of file Index.h.
The documentation for this class was generated from the following files:
ram/analysis/Index.h
ram/analysis/Index.cpp