souffle: souffle::synthesiser::Relation Class Reference
souffle::synthesiser::Relation Class Reference abstract
#include <Relation.h>
Public Member Functions
virtual void computeIndices ()=0
Compute the final list of indices to be used.
virtual void generateTypeStruct (std::ostream &out)=0
Generate relation type struct.
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
MinIndexSelection::OrderCollection getIndices () const
Get list of indices used for relation, guaranteed that original indices in analysis::MinIndexSelection come before any generated indices.
const MinIndexSelection & getMinIndexSelection () const
Get stored analysis::MinIndexSelection.
std::set< int > getProvenenceIndexNumbers () const
const ram::Relation & getRelation () const
Get stored ram::Relation.
std::string getTypeAttributeString (const std::vector< std::string > &attributeTypes, const std::unordered_set< uint32_t > &attributesUsed) const
Helper function to convert attribute types to a single string.
virtual std::string getTypeName ()=0
Print type name.
Relation (const ram::Relation &rel, const MinIndexSelection &indices, const bool isProvenance=false)
virtual ~Relation ()=default
Static Public Member Functions
static Own< Relation > getSynthesiserRelation (const ram::Relation &ramRel, const MinIndexSelection &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes
MinIndexSelection::OrderCollection computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const MinIndexSelection & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
std::set< int > provenanceIndexNumbers
The list of indices added for provenance computation.
const ram::Relation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 26 of file Relation.h.
Constructor & Destructor Documentation
Relation()
souffle::synthesiser::Relation::Relation (const ram::Relation & rel, const MinIndexSelection & indices, const bool isProvenance = false) inline
Definition at line 28 of file Relation.h.
References computeIndices(), and isProvenance.
             : relation(rel), indices(indices), isProvenance(isProvenance) {}
~Relation()
virtual souffle::synthesiser::Relation::~Relation () virtual default
Member Function Documentation
computeIndices()
virtual void souffle::synthesiser::Relation::computeIndices () pure virtual
Compute the final list of indices to be used.
Referenced by Relation().
generateTypeStruct()
virtual void souffle::synthesiser::Relation::generateTypeStruct (std::ostream & out) pure virtual
Generate relation type struct.
Referenced by getRelation().
getArity()
size_t souffle::synthesiser::Relation::getArity () const inline
Get arity of relation.
Definition at line 37 of file Relation.h.
References relation.
{
         return relation.getArity();
     }
getDataStructure()
const std::string& souffle::synthesiser::Relation::getDataStructure () const inline
Get data structure of relation.
Definition at line 42 of file Relation.h.
References dataStructure.
{
         return dataStructure;
     }
getIndices()
MinIndexSelection::OrderCollection souffle::synthesiser::Relation::getIndices () const inline
Get list of indices used for relation, guaranteed that original indices in analysis::MinIndexSelection come before any generated indices.
Definition at line 49 of file Relation.h.
References computedIndices.
{
         return computedIndices;
     }
getMinIndexSelection()
const MinIndexSelection& souffle::synthesiser::Relation::getMinIndexSelection () const inline
Get stored analysis::MinIndexSelection.
Definition at line 58 of file Relation.h.
References indices.
{
         return indices;
     }
getProvenenceIndexNumbers()
std::set<int> souffle::synthesiser::Relation::getProvenenceIndexNumbers () const inline
Definition at line 53 of file Relation.h.
References provenanceIndexNumbers.
{
         return provenanceIndexNumbers;
     }
getRelation()
const ram::Relation& souffle::synthesiser::Relation::getRelation () const inline
Get stored ram::Relation.
Definition at line 63 of file Relation.h.
References souffle::ram::Relation::attributeTypes, generateTypeStruct(), getSynthesiserRelation(), getTypeAttributeString(), getTypeName(), isProvenance, and relation.
{
         return relation;
     }
getSynthesiserRelation()
Own< Relation > souffle::synthesiser::Relation::getSynthesiserRelation (const ram::Relation & ramRel, const MinIndexSelection & indexSet, bool isProvenance) static
Factory method to generate a SynthesiserRelation.
Definition at line 43 of file Relation.cpp.
References souffle::BRIE, souffle::BTREE, souffle::EQREL, souffle::ram::Relation::getArity(), souffle::ram::Relation::getRepresentation(), souffle::INFO, and souffle::ram::Relation::isNullary().
Referenced by getRelation().
{
     Relation* rel;
     // Handle the qualifier in souffle code
     if (isProvenance) {
         rel = new DirectRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.isNullary()) {
         rel = new NullaryRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::BTREE) {
         rel = new DirectRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::BRIE) {
         rel = new BrieRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::EQREL) {
         rel = new EqrelRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::INFO) {
         rel = new InfoRelation(ramRel, indexSet, isProvenance);
     } else {
         // Handle the data structure command line flag
         if (ramRel.getArity() > 6) {
             rel = new IndirectRelation(ramRel, indexSet, isProvenance);
         } else {
             rel = new DirectRelation(ramRel, indexSet, isProvenance);
         }
     }
     assert(rel != nullptr && "relation type not specified");
     // generate index set
     rel->computeIndices();
     return Own<Relation>(rel);
 }
getTypeAttributeString()
std::string souffle::synthesiser::Relation::getTypeAttributeString (const std::vector< std::string > & attributeTypes, const std::unordered_set< uint32_t > & attributesUsed) const
Helper function to convert attribute types to a single string.
Definition at line 27 of file Relation.cpp.
References i.
Referenced by getRelation().
{
     std::stringstream type;
     for (size_t i = 0; i < attributeTypes.size(); ++i) {
         // consider only attributes used in a lex-order
         if (attributesUsed.find(i) != attributesUsed.end()) {
             switch (attributeTypes[i][0]) {
                 case 'f': type << 'f'; break;
                 case 'u': type << 'u'; break;
                 default: type << 'i';  // consider all non-float/unsigned types (i.e. records) as RamSigned
             }
         }
     }
     return type.str();
 }
getTypeName()
virtual std::string souffle::synthesiser::Relation::getTypeName () pure virtual
Print type name.
Referenced by getRelation().
Field Documentation
computedIndices
MinIndexSelection::OrderCollection souffle::synthesiser::Relation::computedIndices protected
The final list of indices used.
Definition at line 92 of file Relation.h.
Referenced by getIndices().
dataStructure
std::string souffle::synthesiser::Relation::dataStructure protected
The data structure used for the relation.
Definition at line 89 of file Relation.h.
Referenced by getDataStructure().
indices
const MinIndexSelection& souffle::synthesiser::Relation::indices protected
Indices used for this relation.
Definition at line 86 of file Relation.h.
Referenced by getMinIndexSelection().
isProvenance
const bool souffle::synthesiser::Relation::isProvenance protected
Is this relation used with provenance.
Definition at line 101 of file Relation.h.
Referenced by getRelation(), and Relation().
masterIndex
size_t souffle::synthesiser::Relation::masterIndex = -1 protected
The number of the master index.
Definition at line 98 of file Relation.h.
provenanceIndexNumbers
std::set<int> souffle::synthesiser::Relation::provenanceIndexNumbers protected
The list of indices added for provenance computation.
Definition at line 95 of file Relation.h.
Referenced by getProvenenceIndexNumbers().
relation
const ram::Relation& souffle::synthesiser::Relation::relation protected
Ram relation referred to by this.
Definition at line 83 of file Relation.h.
The documentation for this class was generated from the following files:
synthesiser/Relation.h
synthesiser/Relation.cpp