souffle: souffle::ram::IndexOperation Class Reference
souffle::ram::IndexOperation Class Reference
#include <IndexOperation.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
IndexOperation * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< Expression * >, std::vector< Expression * > > getRangePattern () const
Get range pattern.
IndexOperation (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
void printIndex (std::ostream &os) const
Helper method for printing.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Definition at line 44 of file IndexOperation.h.
Constructor & Destructor Documentation
IndexOperation()
souffle::ram::IndexOperation::IndexOperation (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText = "") inline
Definition at line 46 of file IndexOperation.h.
References souffle::ram::Relation::getArity(), getRangePattern(), and souffle::ram::RelationOperation::getRelation().
Referenced by clone().
             : RelationOperation(std::move(r), ident, std::move(nested), std::move(profileText)),
               queryPattern(std::move(queryPattern)) {
         assert(getRangePattern().first.size() == getRelation().getArity() &&
                 getRangePattern().second.size() == getRelation().getArity());
         for (const auto& pattern : queryPattern.first) {
             assert(pattern != nullptr && "pattern is a null-pointer");
         }
         for (const auto& pattern : queryPattern.second) {
             assert(pattern != nullptr && "pattern is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::ram::IndexOperation::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 82 of file IndexOperation.h.
References souffle::ram::RelationOperation::apply(), souffle::map(), and queryPattern.
Referenced by souffle::ram::IndexAggregate::apply().
{
         RelationOperation::apply(map);
         for (auto& pattern : queryPattern.first) {
             pattern = map(std::move(pattern));
         }
         for (auto& pattern : queryPattern.second) {
             pattern = map(std::move(pattern));
         }
     }
clone()
IndexOperation* souffle::ram::IndexOperation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::RelationOperation.
Reimplemented in souffle::ram::ParallelIndexChoice, souffle::ram::ParallelIndexScan, souffle::ram::IndexScan, and souffle::ram::ParallelIndexAggregate.
Definition at line 92 of file IndexOperation.h.
References souffle::clone(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::TupleOperation::getTupleId(), i, IndexOperation(), queryPattern, and souffle::ram::RelationOperation::relationRef.
{
         RamPattern resQueryPattern;
         for (const auto& i : queryPattern.first) {
             resQueryPattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             resQueryPattern.second.emplace_back(i->clone());
         }
         return new IndexOperation(souffle::clone(relationRef), getTupleId(), std::move(resQueryPattern),
                 souffle::clone(&getOperation()), getProfileText());
     }
equal()
bool souffle::ram::IndexOperation::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 152 of file IndexOperation.h.
References souffle::ram::RelationOperation::equal(), souffle::equal_targets(), and queryPattern.
Referenced by souffle::ram::IndexAggregate::equal(), and souffle::ram::IndexChoice::equal().
{
         const auto& other = static_cast<const IndexOperation&>(node);
         return RelationOperation::equal(other) &&
                equal_targets(queryPattern.first, other.queryPattern.first) &&
                equal_targets(queryPattern.second, other.queryPattern.second);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::IndexOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 71 of file IndexOperation.h.
References souffle::ram::RelationOperation::getChildNodes(), and queryPattern.
Referenced by souffle::ram::IndexAggregate::getChildNodes(), and souffle::ram::IndexChoice::getChildNodes().
{
         auto res = RelationOperation::getChildNodes();
         for (auto& pattern : queryPattern.first) {
             res.push_back(pattern.get());
         }
         for (auto& pattern : queryPattern.second) {
             res.push_back(pattern.get());
         }
         return res;
     }
getRangePattern()
std::pair<std::vector<Expression*>, std::vector<Expression*> > souffle::ram::IndexOperation::getRangePattern () const inline
Get range pattern.
Returns
A pair of std::vector of pointers to Expression objects These vectors represent the lower and upper bounds for each attribute in the tuple <expr1> <= Tuple[level, element] <= <expr2> We have that at an index for an attribute, its bounds are <expr1> and <expr2> respectively
Definition at line 67 of file IndexOperation.h.
References queryPattern, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), souffle::ram::IndexChoice::IndexChoice(), IndexOperation(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan().
{
         return std::make_pair(toPtrVector(queryPattern.first), toPtrVector(queryPattern.second));
     }
printIndex()
void souffle::ram::IndexOperation::printIndex (std::ostream & os) const inline
Helper method for printing.
Definition at line 105 of file IndexOperation.h.
References souffle::ram::Relation::getArity(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), i, souffle::ram::isUndefValue(), and queryPattern.
Referenced by souffle::ram::IndexScan::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::ParallelIndexScan::print(), souffle::ram::ParallelIndexChoice::print(), souffle::ram::IndexAggregate::print(), and souffle::ram::IndexChoice::print().
{
         //  const auto& attrib = getRelation().getAttributeNames();
         bool first = true;
         for (unsigned int i = 0; i < getRelation().getArity(); ++i) {
             // TODO: print proper upper lower/bound
             // early exit if no upper/lower bounds are defined
             if (isUndefValue(queryPattern.first[i].get()) && isUndefValue(queryPattern.second[i].get())) {
                 continue;
             }
             if (first) {
                 os << " ON INDEX ";
                 first = false;
             } else {
                 os << " AND ";
             }
             // both bounds defined and equal => equality
             if (!isUndefValue(queryPattern.first[i].get()) && !isUndefValue(queryPattern.second[i].get())) {
                 // print equality when lower bound = upper bound
                 if (*(queryPattern.first[i]) == *(queryPattern.second[i])) {
                     os << "t" << getTupleId() << ".";
                     os << i << " = ";
                     os << *(queryPattern.first[i]);
                     continue;
                 }
             }
             // at least one bound defined => inequality
             if (!isUndefValue(queryPattern.first[i].get()) || !isUndefValue(queryPattern.second[i].get())) {
                 if (!isUndefValue(queryPattern.first[i].get())) {
                     os << *(queryPattern.first[i]) << " <= ";
                 }
                 os << "t" << getTupleId() << ".";
                 os << i;
                 if (!isUndefValue(queryPattern.second[i].get())) {
                     os << " <= " << *(queryPattern.second[i]);
                 }
                 continue;
             }
         }
     }
Field Documentation
queryPattern
RamPattern souffle::ram::IndexOperation::queryPattern protected
Values of index per column of table (if indexable)
Definition at line 160 of file IndexOperation.h.
Referenced by souffle::ram::IndexChoice::apply(), apply(), souffle::ram::IndexScan::clone(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::ParallelIndexScan::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::IndexChoice::clone(), clone(), equal(), getChildNodes(), getRangePattern(), and printIndex().
The documentation for this class was generated from the following file:
ram/IndexOperation.h