souffle: souffle::ram::LogRelationTimer Class Reference
souffle::ram::LogRelationTimer Class Reference
Execution time logger for a statement.
#include <LogRelationTimer.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
LogRelationTimer * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
LogRelationTimer (Own< Statement > stmt, std::string msg, Own< RelationReference > relRef)
Public Member Functions inherited from souffle::ram::RelationStatement
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get RAM relation.
RelationStatement (Own< RelationReference > relRef)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractLog
AbstractLog (Own< Statement > stmt, std::string msg)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const std::string & getMessage () const
Get logging message.
const Statement & getStatement () const
Get logging statement.
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractLog
bool equal (const Node &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationStatement
Own< RelationReference > relationRef
Relation reference.
Protected Attributes inherited from souffle::ram::AbstractLog
std::string message
logging message
Own< Statement > statement
logging statement
Detailed Description
Execution time logger for a statement.
Logs the execution time of a statement. Before and after the execution of the logging statement the wall-clock time is taken to compute the time duration for the statement. Duration and logging message is printed after the execution of the statement.
For example:
START_TIMER ON A "file.dl [8:1-8:8]\;"
  ...
END_TIMER
Definition at line 51 of file LogRelationTimer.h.
Constructor & Destructor Documentation
LogRelationTimer()
souffle::ram::LogRelationTimer::LogRelationTimer (Own< Statement > stmt, std::string msg, Own< RelationReference > relRef) inline
Definition at line 53 of file LogRelationTimer.h.
Referenced by clone().
             : RelationStatement(std::move(relRef)), AbstractLog(std::move(stmt), std::move(msg)) {}
Member Function Documentation
apply()
void souffle::ram::LogRelationTimer::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 66 of file LogRelationTimer.h.
References souffle::ram::RelationStatement::apply(), and souffle::ram::AbstractLog::apply().
{
         RelationStatement::apply(map);
         AbstractLog::apply(map);
     }
clone()
LogRelationTimer* souffle::ram::LogRelationTimer::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 62 of file LogRelationTimer.h.
References souffle::clone(), LogRelationTimer(), souffle::ram::AbstractLog::message, souffle::ram::RelationStatement::relationRef, and souffle::ram::AbstractLog::statement.
Referenced by souffle::ram::test::TEST().
{
         return new LogRelationTimer(souffle::clone(statement), message, souffle::clone(relationRef));
     }
getChildNodes()
std::vector<const Node*> souffle::ram::LogRelationTimer::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 56 of file LogRelationTimer.h.
References souffle::ram::AbstractLog::getChildNodes(), and souffle::ram::RelationStatement::getChildNodes().
{
         std::vector<const Node*> res = RelationStatement::getChildNodes();
         res.push_back(AbstractLog::getChildNodes().at(0));
         return res;
     }
print()
void souffle::ram::LogRelationTimer::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 72 of file LogRelationTimer.h.
References souffle::ram::Relation::getName(), souffle::ram::RelationStatement::getRelation(), souffle::ram::AbstractLog::message, souffle::ram::Statement::print(), souffle::ram::AbstractLog::statement, souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "START_TIMER ON " << getRelation().getName() << " \""
            << stringify(message) << "\"" << std::endl;
         Statement::print(statement.get(), os, tabpos + 1);
         os << times(" ", tabpos) << "END_TIMER" << std::endl;
     }
The documentation for this class was generated from the following file:
ram/LogRelationTimer.h