souffle: souffle::ast::transform::PragmaChecker Class Reference
souffle::ast::transform::PragmaChecker Class Reference
#include <PragmaChecker.h>
Public Member Functions
PragmaChecker * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &) override
Detailed Description
Definition at line 25 of file PragmaChecker.h.
Member Function Documentation
clone()
PragmaChecker* souffle::ast::transform::PragmaChecker::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 31 of file PragmaChecker.h.
References transform().
{
         return new PragmaChecker();
     }
getName()
std::string souffle::ast::transform::PragmaChecker::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 27 of file PragmaChecker.h.
{
         return "PragmaChecker";
     }
transform()
bool souffle::ast::transform::PragmaChecker::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 27 of file PragmaChecker.cpp.
References souffle::Global::config(), souffle::ast::Pragma::getkvp(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::visitDepthFirst().
Referenced by clone().
{
     bool changed = false;
     Program& program = translationUnit.getProgram();
     // Take in pragma options from the datalog file
     visitDepthFirst(program, [&](const Pragma& pragma) {
         std::pair<std::string, std::string> kvp = pragma.getkvp();
         // Command line options take precedence
         if (!Global::config().has(kvp.first)) {
             changed = true;
             Global::config().set(kvp.first, kvp.second);
         }
     });
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/PragmaChecker.h
ast/transform/PragmaChecker.cpp