souffle: souffle::ram::transform::ParallelTransformer Class Reference
souffle::ram::transform::ParallelTransformer Class Reference
Transforms Choice/IndexChoice/IndexScan/Scan into parallel versions.
#include <Parallel.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool parallelizeOperations (Program &program)
Parallelize operations.
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transforms Choice/IndexChoice/IndexScan/Scan into parallel versions.
For example ..
QUERY
  FOR t0 in A
   ...
will be rewritten to
QUERY
  PARALLEL FOR t0 in A
   ...
Definition at line 45 of file Parallel.h.
Member Function Documentation
getName()
std::string souffle::ram::transform::ParallelTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 47 of file Parallel.h.
References parallelizeOperations().
{
         return "ParallelTransformer";
     }
parallelizeOperations()
bool souffle::ram::transform::ParallelTransformer::parallelizeOperations (Program & program)
Parallelize operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 32 of file Parallel.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::clone(), souffle::ram::makeLambdaRamMapper(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     // parallelize the most outer loop only
     // most outer loops can be scan/choice/indexScan/indexChoice
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> parallelRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const Scan* scan = dynamic_cast<Scan*>(node.get())) {
                 if (scan->getTupleId() == 0 && scan->getRelation().getArity() > 0) {
                     if (!isA<Project>(&scan->getOperation())) {
                         changed = true;
                         return mk<ParallelScan>(mk<RelationReference>(&scan->getRelation()),
                                 scan->getTupleId(), souffle::clone(&scan->getOperation()),
                                 scan->getProfileText());
                     }
                 }
             } else if (const Choice* choice = dynamic_cast<Choice*>(node.get())) {
                 if (choice->getTupleId() == 0) {
                     changed = true;
                     return mk<ParallelChoice>(mk<RelationReference>(&choice->getRelation()),
                             choice->getTupleId(), souffle::clone(&choice->getCondition()),
                             souffle::clone(&choice->getOperation()), choice->getProfileText());
                 }
             } else if (const IndexScan* indexScan = dynamic_cast<IndexScan*>(node.get())) {
                 if (indexScan->getTupleId() == 0) {
                     changed = true;
                     const Relation& rel = indexScan->getRelation();
                     RamPattern queryPattern = clone(indexScan->getRangePattern());
                     return mk<ParallelIndexScan>(mk<RelationReference>(&rel), indexScan->getTupleId(),
                             std::move(queryPattern), souffle::clone(&indexScan->getOperation()),
                             indexScan->getProfileText());
                 }
             } else if (const IndexChoice* indexChoice = dynamic_cast<IndexChoice*>(node.get())) {
                 if (indexChoice->getTupleId() == 0) {
                     changed = true;
                     const Relation& rel = indexChoice->getRelation();
                     RamPattern queryPattern = clone(indexChoice->getRangePattern());
                     return mk<ParallelIndexChoice>(mk<RelationReference>(&rel), indexChoice->getTupleId(),
                             souffle::clone(&indexChoice->getCondition()), std::move(queryPattern),
                             souffle::clone(&indexChoice->getOperation()), indexChoice->getProfileText());
                 }
             } else if (const Aggregate* aggregate = dynamic_cast<Aggregate*>(node.get())) {
                 if (aggregate->getTupleId() == 0 && !aggregate->getRelation().isNullary()) {
                     changed = true;
                     const Relation& rel = aggregate->getRelation();
                     return mk<ParallelAggregate>(Own<Operation>(aggregate->getOperation().clone()),
                             aggregate->getFunction(), mk<RelationReference>(&rel),
                             Own<Expression>(aggregate->getExpression().clone()),
                             Own<Condition>(aggregate->getCondition().clone()), aggregate->getTupleId());
                 }
             } else if (const IndexAggregate* indexAggregate = dynamic_cast<IndexAggregate*>(node.get())) {
                 if (indexAggregate->getTupleId() == 0 && !indexAggregate->getRelation().isNullary()) {
                     changed = true;
                     const Relation& rel = indexAggregate->getRelation();
                     RamPattern queryPattern = clone(indexAggregate->getRangePattern());
                     return mk<ParallelIndexAggregate>(Own<Operation>(indexAggregate->getOperation().clone()),
                             indexAggregate->getFunction(), mk<RelationReference>(&rel),
                             Own<Expression>(indexAggregate->getExpression().clone()),
                             Own<Condition>(indexAggregate->getCondition().clone()), std::move(queryPattern),
                             indexAggregate->getTupleId());
                 }
             }
             node->apply(makeLambdaRamMapper(parallelRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(parallelRewriter));
     });
     return changed;
 }
transform()
bool souffle::ram::transform::ParallelTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 59 of file Parallel.h.
References souffle::ram::TranslationUnit::getProgram(), and parallelizeOperations().
{
         return parallelizeOperations(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/Parallel.h
ram/transform/Parallel.cpp