souffle: souffle::ram::Extend Class Reference
souffle::ram::Extend Class Reference
Extend equivalence relation.
#include <Extend.h>
Public Member Functions
Extend * clone () const override
Create a clone (i.e.
Extend (Own< RelationReference > tRef, Own< RelationReference > sRef)
const Relation & getSourceRelation () const
Get source relation.
const Relation & getTargetRelation () const
Get target relation.
Public Member Functions inherited from souffle::ram::BinRelationStatement
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
BinRelationStatement (Own< RelationReference > f, Own< RelationReference > s)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getFirstRelation () const
Get first relation.
const Relation & getSecondRelation () const
Get second relation.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::BinRelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::BinRelationStatement
Own< RelationReference > first
first argument of binary statement
Own< RelationReference > second
second argument of binary statement
Detailed Description
Extend equivalence relation.
The following example merges A into B:
EXTEND B WITH A
Definition at line 37 of file Extend.h.
Constructor & Destructor Documentation
Extend()
souffle::ram::Extend::Extend (Own< RelationReference > tRef, Own< RelationReference > sRef) inline
Definition at line 39 of file Extend.h.
Referenced by clone().
             : BinRelationStatement(std::move(sRef), std::move(tRef)) {}
Member Function Documentation
clone()
Extend* souffle::ram::Extend::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 52 of file Extend.h.
References souffle::clone(), Extend(), souffle::ram::BinRelationStatement::first, and souffle::ram::BinRelationStatement::second.
Referenced by souffle::ram::test::TEST().
{
         auto* res = new Extend(souffle::clone(second), souffle::clone(first));
         return res;
     }
getSourceRelation()
const Relation& souffle::ram::Extend::getSourceRelation () const inline
Get source relation.
Definition at line 43 of file Extend.h.
References souffle::ram::BinRelationStatement::getFirstRelation().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and print().
{
         return getFirstRelation();
     }
getTargetRelation()
const Relation& souffle::ram::Extend::getTargetRelation () const inline
Get target relation.
Definition at line 48 of file Extend.h.
References souffle::ram::BinRelationStatement::getSecondRelation().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and print().
{
         return getSecondRelation();
     }
print()
void souffle::ram::Extend::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 58 of file Extend.h.
References souffle::ram::Relation::getName(), getSourceRelation(), getTargetRelation(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "EXTEND " << getTargetRelation().getName() << " WITH " << getSourceRelation().getName();
         os << std::endl;
     }
The documentation for this class was generated from the following file:
ram/Extend.h