souffle: souffle::ast::analysis::PrecedenceGraphAnalysis Class Reference
souffle::ast::analysis::PrecedenceGraphAnalysis Class Reference
Analysis pass computing the precedence graph of the relations of the datalog progam.
#include <PrecedenceGraph.h>
Public Member Functions
const Graph< const Relation *, NameComparison > & graph () const
PrecedenceGraphAnalysis ()
void print (std::ostream &os) const override
Output precedence graph in graphviz format to a given stream.
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "precedence-graph"
Private Attributes
Graph< const Relation *, NameComparison > backingGraph
Adjacency list of precedence graph (determined by the dependencies of the relations)
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass computing the precedence graph of the relations of the datalog progam.
Definition at line 35 of file PrecedenceGraph.h.
Constructor & Destructor Documentation
PrecedenceGraphAnalysis()
souffle::ast::analysis::PrecedenceGraphAnalysis::PrecedenceGraphAnalysis () inline
Definition at line 39 of file PrecedenceGraph.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
graph()
const Graph<const Relation*, NameComparison>& souffle::ast::analysis::PrecedenceGraphAnalysis::graph () const inline
Definition at line 46 of file PrecedenceGraph.h.
References backingGraph.
Referenced by souffle::ast::transform::findInlineCycle(), souffle::ast::analysis::SCCGraphAnalysis::getExternalNonOutputPredecessorRelations(), souffle::ast::analysis::SCCGraphAnalysis::getExternalOutputPredecessorRelations(), souffle::ast::analysis::SCCGraphAnalysis::getExternalPredecessorRelations(), souffle::ast::analysis::SCCGraphAnalysis::getInternalNonOutputRelationsWithExternalSuccessors(), souffle::ast::analysis::SCCGraphAnalysis::getInternalRelationsWithExternalSuccessors(), souffle::ast::analysis::SCCGraphAnalysis::getPredecessorSCCs(), souffle::ast::analysis::SCCGraphAnalysis::getSuccessorSCCs(), souffle::ast::analysis::SCCGraphAnalysis::isRecursive(), souffle::ast::analysis::RedundantRelationsAnalysis::run(), souffle::ast::analysis::SCCGraphAnalysis::run(), and souffle::ast::analysis::SCCGraphAnalysis::scR().
{
         return backingGraph;
     }
print()
void souffle::ast::analysis::PrecedenceGraphAnalysis::print (std::ostream & os) const override virtual
Output precedence graph in graphviz format to a given stream.
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 55 of file PrecedenceGraph.cpp.
References backingGraph, souffle::ast::analysis::Analysis::getName(), souffle::printHTMLGraph(), and souffle::profile::ss.
Referenced by PrecedenceGraphAnalysis().
{
     /* Print dependency graph */
     std::stringstream ss;
     ss << "digraph {\n";
     /* Print node of dependence graph */
     for (const Relation* rel : backingGraph.vertices()) {
         if (rel != nullptr) {
             ss << "\t\"" << rel->getQualifiedName() << "\" [label = \"" << rel->getQualifiedName()
                << "\"];\n";
         }
     }
     for (const Relation* rel : backingGraph.vertices()) {
         if (rel != nullptr) {
             for (const Relation* adjRel : backingGraph.successors(rel)) {
                 if (adjRel != nullptr) {
                     ss << "\t\"" << rel->getQualifiedName() << "\" -> \"" << adjRel->getQualifiedName()
                        << "\";\n";
                 }
             }
         }
     }
     ss << "}\n";
     printHTMLGraph(os, ss.str(), getName());
 }
run()
void souffle::ast::analysis::PrecedenceGraphAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 37 of file PrecedenceGraph.cpp.
References backingGraph, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getRelations(), and souffle::ast::visitDepthFirst().
Referenced by PrecedenceGraphAnalysis().
{
     /* Get relations */
     Program& program = translationUnit.getProgram();
     const auto& relationDetail = *translationUnit.getAnalysis<RelationDetailCacheAnalysis>();
     for (const auto* r : program.getRelations()) {
         backingGraph.insert(r);
         for (const auto& c : relationDetail.getClauses(r)) {
             visitDepthFirst(c->getBodyLiterals(), [&](const Atom& atom) {
                 backingGraph.insert(relationDetail.getRelation(atom.getQualifiedName()), r);
             });
             visitDepthFirst(c->getHead()->getArguments(), [&](const Atom& atom) {
                 backingGraph.insert(relationDetail.getRelation(atom.getQualifiedName()), r);
             });
         }
     }
 }
Field Documentation
backingGraph
Graph<const Relation*, NameComparison> souffle::ast::analysis::PrecedenceGraphAnalysis::backingGraph private
Adjacency list of precedence graph (determined by the dependencies of the relations)
Definition at line 52 of file PrecedenceGraph.h.
Referenced by graph(), print(), and run().
name
constexpr const char* souffle::ast::analysis::PrecedenceGraphAnalysis::name = "precedence-graph" static
Definition at line 37 of file PrecedenceGraph.h.
The documentation for this class was generated from the following files:
ast/analysis/PrecedenceGraph.h
ast/analysis/PrecedenceGraph.cpp