souffle: souffle::ram::RelationStatement Class Reference
souffle::ram::RelationStatement Class Reference
RAM Statements with a single relation.
#include <RelationStatement.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get RAM relation.
RelationStatement (Own< RelationReference > relRef)
Public Member Functions inherited from souffle::ram::Statement
Statement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Attributes
Own< RelationReference > relationRef
Relation reference.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
RAM Statements with a single relation.
Definition at line 33 of file RelationStatement.h.
Constructor & Destructor Documentation
RelationStatement()
souffle::ram::RelationStatement::RelationStatement (Own< RelationReference > relRef) inline
Definition at line 35 of file RelationStatement.h.
References relationRef.
                                                      : relationRef(std::move(relRef)) {
         assert(relationRef != nullptr && "Relation reference is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::RelationStatement::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 48 of file RelationStatement.h.
References souffle::map(), and relationRef.
Referenced by souffle::ram::LogRelationTimer::apply().
{
         relationRef = map(std::move(relationRef));
     }
equal()
bool souffle::ram::RelationStatement::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 53 of file RelationStatement.h.
References souffle::equal_ptr(), and relationRef.
Referenced by souffle::ram::LogSize::equal(), and souffle::ram::IO::equal().
{
         const auto& other = static_cast<const RelationStatement&>(node);
         return equal_ptr(relationRef, other.relationRef);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::RelationStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 44 of file RelationStatement.h.
References relationRef.
Referenced by souffle::ram::LogRelationTimer::getChildNodes().
{
         return {relationRef.get()};
     }
getRelation()
const Relation& souffle::ram::RelationStatement::getRelation () const inline
Get RAM relation.
Definition at line 40 of file RelationStatement.h.
References relationRef.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::synthesiser::Synthesiser::generateCode(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::ram::LogSize::print(), souffle::ram::Clear::print(), souffle::ram::IO::print(), souffle::ram::LogRelationTimer::print(), souffle::NodeGenerator::visitClear(), souffle::NodeGenerator::visitIO(), souffle::NodeGenerator::visitLogRelationTimer(), and souffle::NodeGenerator::visitLogSize().
{
         return *relationRef->get();
     }
Field Documentation
relationRef
Own<RelationReference> souffle::ram::RelationStatement::relationRef protected
Relation reference.
Definition at line 60 of file RelationStatement.h.
Referenced by apply(), souffle::ram::LogSize::clone(), souffle::ram::Clear::clone(), souffle::ram::IO::clone(), souffle::ram::LogRelationTimer::clone(), equal(), getChildNodes(), getRelation(), and RelationStatement().
The documentation for this class was generated from the following file:
ram/RelationStatement.h