souffle: souffle::ast::analysis::RelationScheduleAnalysisStep Class Reference
souffle::ast::analysis::RelationScheduleAnalysisStep Class Reference
A single step in a relation schedule, consisting of the relations computed in the step and the relations that are no longer required at that step.
#include <RelationSchedule.h>
Public Member Functions
const std::set< const Relation * > & computed () const
const std::set< const Relation * > & expired () const
void print (std::ostream &os) const
bool recursive () const
RelationScheduleAnalysisStep (std::set< const Relation *> computedRelations, std::set< const Relation *> expiredRelations, const bool isRecursive)
Private Attributes
std::set< const Relation * > computedRelations
std::set< const Relation * > expiredRelations
const bool isRecursive
Friends
std::ostream & operator<< (std::ostream &out, const RelationScheduleAnalysisStep &other)
Add support for printing nodes.
Detailed Description
A single step in a relation schedule, consisting of the relations computed in the step and the relations that are no longer required at that step.
Definition at line 38 of file RelationSchedule.h.
Constructor & Destructor Documentation
RelationScheduleAnalysisStep()
souffle::ast::analysis::RelationScheduleAnalysisStep::RelationScheduleAnalysisStep (std::set< const Relation *> computedRelations, std::set< const Relation *> expiredRelations, const bool isRecursive) inline
Definition at line 40 of file RelationSchedule.h.
             : computedRelations(std::move(computedRelations)), expiredRelations(std::move(expiredRelations)),
               isRecursive(isRecursive) {}
Member Function Documentation
computed()
const std::set<const Relation*>& souffle::ast::analysis::RelationScheduleAnalysisStep::computed () const inline
Definition at line 45 of file RelationSchedule.h.
References computedRelations.
Referenced by print().
{
         return computedRelations;
     }
expired()
const std::set<const Relation*>& souffle::ast::analysis::RelationScheduleAnalysisStep::expired () const inline
Definition at line 49 of file RelationSchedule.h.
References expiredRelations.
Referenced by print().
{
         return expiredRelations;
     }
print()
void souffle::ast::analysis::RelationScheduleAnalysisStep::print (std::ostream & os) const
Definition at line 35 of file RelationSchedule.cpp.
References computed(), expired(), and recursive().
Referenced by recursive(), and souffle::ast::analysis::RelationScheduleAnalysis::schedule().
{
     os << "computed: ";
     for (const Relation* compRel : computed()) {
         os << compRel->getQualifiedName() << ", ";
     }
     os << "\nexpired: ";
     for (const Relation* compRel : expired()) {
         os << compRel->getQualifiedName() << ", ";
     }
     os << "\n";
     if (recursive()) {
         os << "recursive";
     } else {
         os << "not recursive";
     }
     os << "\n";
 }
recursive()
bool souffle::ast::analysis::RelationScheduleAnalysisStep::recursive () const inline
Definition at line 53 of file RelationSchedule.h.
References isRecursive, and print().
Referenced by print().
{
         return isRecursive;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const RelationScheduleAnalysisStep & other) friend
Add support for printing nodes.
Definition at line 60 of file RelationSchedule.h.
{
         other.print(out);
         return out;
     }
Field Documentation
computedRelations
std::set<const Relation*> souffle::ast::analysis::RelationScheduleAnalysisStep::computedRelations private
Definition at line 66 of file RelationSchedule.h.
Referenced by computed(), and souffle::ast::analysis::RelationScheduleAnalysis::run().
expiredRelations
std::set<const Relation*> souffle::ast::analysis::RelationScheduleAnalysisStep::expiredRelations private
Definition at line 67 of file RelationSchedule.h.
Referenced by expired().
isRecursive
const bool souffle::ast::analysis::RelationScheduleAnalysisStep::isRecursive private
Definition at line 68 of file RelationSchedule.h.
Referenced by recursive().
The documentation for this class was generated from the following files:
ast/analysis/RelationSchedule.h
ast/analysis/RelationSchedule.cpp