souffle: souffle::ast::analysis::UnionType Class Reference
souffle::ast::analysis::UnionType Class Reference
A union type combining a list of types into a new, aggregated type.
#include <TypeSystem.h>
Public Member Functions
const std::vector< const Type * > & getElementTypes () const
void print (std::ostream &out) const override
void setElements (std::vector< const Type *> elements)
Public Member Functions inherited from souffle::ast::analysis::Type
const QualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
UnionType (const TypeEnvironment &environment, const QualifiedName &name, std::vector< const Type *> elementTypes={})
Protected Member Functions inherited from souffle::ast::analysis::Type
Type (const TypeEnvironment &environment, QualifiedName name)
Protected Attributes
std::vector< const Type * > elementTypes
Protected Attributes inherited from souffle::ast::analysis::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
QualifiedName name
Friends
class TypeEnvironment
Detailed Description
A union type combining a list of types into a new, aggregated type.
Definition at line 140 of file TypeSystem.h.
Constructor & Destructor Documentation
UnionType()
souffle::ast::analysis::UnionType::UnionType (const TypeEnvironment & environment, const QualifiedName & name, std::vector< const Type *> elementTypes = {}) inline protected
Definition at line 156 of file TypeSystem.h.
References souffle::ast::analysis::Type::Type().
Referenced by souffle::ast::UnionType::clone().
                                                   {})
             : Type(environment, name), elementTypes(std::move(elementTypes)) {}
Member Function Documentation
getElementTypes()
const std::vector<const Type*>& souffle::ast::analysis::UnionType::getElementTypes () const inline
Definition at line 142 of file TypeSystem.h.
Referenced by souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::getTypeQualifier(), and souffle::ast::analysis::isOfRootType().
{
         return elementTypes;
     }
print()
void souffle::ast::analysis::UnionType::print (std::ostream & out) const override virtual
Reimplemented from souffle::ast::analysis::Type.
Definition at line 32 of file TypeSystem.cpp.
References tinyformat::format(), souffle::ast::analysis::Type::getName(), and souffle::join().
{
     out << tfm::format("%s = %s", getName(),
             join(elementTypes, " | ", [](std::ostream& out, const Type* type) { out << type->getName(); }));
 }
setElements()
void souffle::ast::analysis::UnionType::setElements (std::vector< const Type *> elements) inline
Definition at line 146 of file TypeSystem.h.
References souffle::ast::analysis::Type::print().
Referenced by souffle::ast::test::TEST().
{
         elementTypes = std::move(elements);
     }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 153 of file TypeSystem.h.
Field Documentation
elementTypes
std::vector<const Type*> souffle::ast::analysis::UnionType::elementTypes protected
Definition at line 154 of file TypeSystem.h.
The documentation for this class was generated from the following files:
ast/analysis/TypeSystem.h
ast/analysis/TypeSystem.cpp