souffle: souffle::ram::Scan Class Reference
souffle::ram::Scan Class Reference
Iterate all tuples of a relation.
#include <Scan.h>
Public Member Functions
Scan * clone () const override
Create a clone (i.e.
Scan (Own< RelationReference > rel, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Iterate all tuples of a relation.
The following example iterates over all tuples in the set A:
QUERY
 ...
 FOR t0 IN A
   ...
Definition at line 43 of file Scan.h.
Constructor & Destructor Documentation
Scan()
souffle::ram::Scan::Scan (Own< RelationReference > rel, int ident, Own< Operation > nested, std::string profileText = "") inline
Definition at line 45 of file Scan.h.
Referenced by clone().
             : RelationOperation(std::move(rel), ident, std::move(nested), std::move(profileText)) {}
Member Function Documentation
clone()
Scan* souffle::ram::Scan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::RelationOperation.
Definition at line 48 of file Scan.h.
References souffle::clone(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::RelationOperation::relationRef, and Scan().
Referenced by souffle::ram::test::TEST().
{
         return new Scan(
                 souffle::clone(relationRef), getTupleId(), souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::ram::Scan::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::ram::NestedOperation.
Definition at line 54 of file Scan.h.
References souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "FOR t" << getTupleId();
         os << " IN " << getRelation().getName() << std::endl;
         RelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Scan.h