souffle: souffle::ram::NestedIntrinsicOperator Class Reference
souffle::ram::NestedIntrinsicOperator Class Reference
Effectively identical to IntrinsicOperator, except it can produce multiple results.
#include <NestedIntrinsicOperator.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
NestedIntrinsicOperator * clone () const override
Create a clone (i.e.
std::vector< Expression * > getArguments () const
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
NestedIntrinsicOp getFunction () const
NestedIntrinsicOperator (NestedIntrinsicOp op, VecOwn< Expression > args, Own< Operation > nested, int ident)
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
VecOwn< Expression > args
NestedIntrinsicOp op
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Effectively identical to IntrinsicOperator, except it can produce multiple results.
For example:
RANGE(t0.0, t0.1, t0.2) INTO t1
Definition at line 58 of file NestedIntrinsicOperator.h.
Constructor & Destructor Documentation
NestedIntrinsicOperator()
souffle::ram::NestedIntrinsicOperator::NestedIntrinsicOperator (NestedIntrinsicOp op, VecOwn< Expression > args, Own< Operation > nested, int ident) inline
Definition at line 60 of file NestedIntrinsicOperator.h.
             : TupleOperation(ident, std::move(nested)), args(std::move(args)), op(op) {}
Member Function Documentation
apply()
void souffle::ram::NestedIntrinsicOperator::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 84 of file NestedIntrinsicOperator.h.
References souffle::ram::NestedOperation::apply(), and souffle::map().
{
         TupleOperation::apply(map);
         for (auto&& x : args) {
             x = map(std::move(x));
         }
     }
clone()
NestedIntrinsicOperator* souffle::ram::NestedIntrinsicOperator::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::TupleOperation.
Definition at line 79 of file NestedIntrinsicOperator.h.
References souffle::clone().
{
         return new NestedIntrinsicOperator(
                 op, souffle::clone(args), souffle::clone(&getOperation()), getTupleId());
     }
equal()
bool souffle::ram::NestedIntrinsicOperator::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 99 of file NestedIntrinsicOperator.h.
References souffle::ram::TupleOperation::equal(), and souffle::equal_targets().
{
         auto&& other = static_cast<const NestedIntrinsicOperator&>(node);
         return TupleOperation::equal(node) && op == other.op && equal_targets(args, other.args);
     }
getArguments()
std::vector<Expression*> souffle::ram::NestedIntrinsicOperator::getArguments () const inline
Definition at line 67 of file NestedIntrinsicOperator.h.
References souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::NodeGenerator::visitNestedIntrinsicOperator().
{
         return toPtrVector(args);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::NestedIntrinsicOperator::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 71 of file NestedIntrinsicOperator.h.
References souffle::ram::TupleOperation::getChildNodes().
{
         auto res = TupleOperation::getChildNodes();
         for (auto&& x : args) {
             res.push_back(x.get());
         }
         return res;
     }
getFunction()
NestedIntrinsicOp souffle::ram::NestedIntrinsicOperator::getFunction () const inline
Definition at line 63 of file NestedIntrinsicOperator.h.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return op;
     }
print()
void souffle::ram::NestedIntrinsicOperator::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Definition at line 92 of file NestedIntrinsicOperator.h.
References souffle::join(), souffle::ram::NestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << op << "(" << join(args, ",", print_deref<Own<Expression>>()) << ") INTO t" << getTupleId()
            << "\n";
         NestedOperation::print(os, tabpos + 1);
     }
Field Documentation
args
VecOwn<Expression> souffle::ram::NestedIntrinsicOperator::args protected
Definition at line 104 of file NestedIntrinsicOperator.h.
op
NestedIntrinsicOp souffle::ram::NestedIntrinsicOperator::op protected
Definition at line 105 of file NestedIntrinsicOperator.h.
The documentation for this class was generated from the following file:
ram/NestedIntrinsicOperator.h