souffle: souffle::ram::Constraint Class Reference
souffle::ram::Constraint Class Reference
Evaluates a binary constraint with respect to two Expressions.
#include <Constraint.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Constraint * clone () const override
Create a clone (i.e.
Constraint (BinaryConstraintOp op, Own< Expression > l, Own< Expression > r)
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Expression & getLHS () const
Get left-hand side.
BinaryConstraintOp getOperator () const
Get operator symbol.
const Expression & getRHS () const
Get right-hand side.
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Expression > lhs
Left-hand side of constraint.
BinaryConstraintOp op
Operator.
Own< Expression > rhs
Right-hand side of constraint.
Detailed Description
Evaluates a binary constraint with respect to two Expressions.
Condition is true if the constraint (a logical operator such as "<") holds between the two operands
The following example checks the equality of the two given tuple elements:
t0.1 = t1.0
Definition at line 48 of file Constraint.h.
Constructor & Destructor Documentation
Constraint()
souffle::ram::Constraint::Constraint (BinaryConstraintOp op, Own< Expression > l, Own< Expression > r) inline
Definition at line 50 of file Constraint.h.
References lhs, and rhs.
Referenced by clone().
             : op(op), lhs(std::move(l)), rhs(std::move(r)) {
         assert(lhs != nullptr && "left-hand side of constraint is a null-pointer");
         assert(rhs != nullptr && "right-hand side of constraint is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::ram::Constraint::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 79 of file Constraint.h.
References lhs, souffle::map(), and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
clone()
Constraint* souffle::ram::Constraint::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Condition.
Definition at line 75 of file Constraint.h.
References souffle::clone(), Constraint(), lhs, op, and rhs.
{
         return new Constraint(op, souffle::clone(lhs), souffle::clone(rhs));
     }
equal()
bool souffle::ram::Constraint::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 91 of file Constraint.h.
References souffle::equal_ptr(), lhs, op, and rhs.
{
         const auto& other = static_cast<const Constraint&>(node);
         return op == other.op && equal_ptr(lhs, other.lhs) && equal_ptr(rhs, other.rhs);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::Constraint::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 71 of file Constraint.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
getLHS()
const Expression& souffle::ram::Constraint::getLHS () const inline
Get left-hand side.
Definition at line 57 of file Constraint.h.
References lhs.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::MakeIndexTransformer::getExpressionPair(), and souffle::ram::analysis::LevelAnalysis::getLevel().
{
         return *lhs;
     }
getOperator()
BinaryConstraintOp souffle::ram::Constraint::getOperator () const inline
Get operator symbol.
Definition at line 67 of file Constraint.h.
References op.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::ram::transform::MakeIndexTransformer::getExpressionPair().
{
         return op;
     }
getRHS()
const Expression& souffle::ram::Constraint::getRHS () const inline
Get right-hand side.
Definition at line 62 of file Constraint.h.
References rhs.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::MakeIndexTransformer::getExpressionPair(), and souffle::ram::analysis::LevelAnalysis::getLevel().
{
         return *rhs;
     }
print()
void souffle::ram::Constraint::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 85 of file Constraint.h.
References lhs, op, rhs, and souffle::toBinaryConstraintSymbol().
{
         os << "(" << *lhs << " ";
         os << toBinaryConstraintSymbol(op);
         os << " " << *rhs << ")";
     }
Field Documentation
lhs
Own<Expression> souffle::ram::Constraint::lhs protected
Left-hand side of constraint.
Definition at line 100 of file Constraint.h.
Referenced by apply(), clone(), Constraint(), equal(), getChildNodes(), getLHS(), and print().
op
BinaryConstraintOp souffle::ram::Constraint::op protected
Operator.
Definition at line 97 of file Constraint.h.
Referenced by clone(), equal(), getOperator(), and print().
rhs
Own<Expression> souffle::ram::Constraint::rhs protected
Right-hand side of constraint.
Definition at line 103 of file Constraint.h.
Referenced by apply(), clone(), Constraint(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
ram/Constraint.h