souffle: souffle::ast::analysis::RedundantRelationsAnalysis Class Reference
souffle::ast::analysis::RedundantRelationsAnalysis Class Reference
Analysis pass identifying relations which do not contribute to the computation of the output relations.
#include <RedundantRelations.h>
Public Member Functions
const std::set< const Relation * > & getRedundantRelations () const
void print (std::ostream &os) const override
print the analysis result in HTML format
RedundantRelationsAnalysis ()
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "redundant-relations"
Private Attributes
PrecedenceGraphAnalysis * precedenceGraph = nullptr
std::set< const Relation * > redundantRelations
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass identifying relations which do not contribute to the computation of the output relations.
Definition at line 36 of file RedundantRelations.h.
Constructor & Destructor Documentation
RedundantRelationsAnalysis()
souffle::ast::analysis::RedundantRelationsAnalysis::RedundantRelationsAnalysis () inline
Definition at line 40 of file RedundantRelations.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
getRedundantRelations()
const std::set<const Relation*>& souffle::ast::analysis::RedundantRelationsAnalysis::getRedundantRelations () const inline
Definition at line 46 of file RedundantRelations.h.
References redundantRelations.
Referenced by souffle::ast::transform::RemoveRedundantRelationsTransformer::transform().
{
         return redundantRelations;
     }
print()
void souffle::ast::analysis::RedundantRelationsAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 75 of file RedundantRelations.cpp.
References redundantRelations.
Referenced by RedundantRelationsAnalysis().
{
     os << redundantRelations << std::endl;
 }
run()
void souffle::ast::analysis::RedundantRelationsAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 33 of file RedundantRelations.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), precedenceGraph, redundantRelations, and relations.
Referenced by RedundantRelationsAnalysis().
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraphAnalysis>();
     std::set<const Relation*> work;
     std::set<const Relation*> notRedundant;
     auto* ioType = translationUnit.getAnalysis<IOTypeAnalysis>();
     Program& program = translationUnit.getProgram();
     const std::vector<Relation*>& relations = program.getRelations();
     /* Add all output relations to the work set */
     for (const Relation* r : relations) {
         if (ioType->isOutput(r)) {
             work.insert(r);
         }
     }
     /* Find all relations which are not redundant for the computations of the
        output relations. */
     while (!work.empty()) {
         /* Chose one element in the work set and add it to notRedundant */
         const Relation* u = *(work.begin());
         work.erase(work.begin());
         notRedundant.insert(u);
         /* Find all predecessors of u and add them to the worklist
             if they are not in the set notRedundant */
         for (const Relation* predecessor : precedenceGraph->graph().predecessors(u)) {
             if (notRedundant.count(predecessor) == 0u) {
                 work.insert(predecessor);
             }
         }
     }
     /* All remaining relations are redundant. */
     redundantRelations.clear();
     for (const Relation* r : relations) {
         if (notRedundant.count(r) == 0u) {
             redundantRelations.insert(r);
         }
     }
 }
Field Documentation
name
constexpr const char* souffle::ast::analysis::RedundantRelationsAnalysis::name = "redundant-relations" static
Definition at line 38 of file RedundantRelations.h.
precedenceGraph
PrecedenceGraphAnalysis* souffle::ast::analysis::RedundantRelationsAnalysis::precedenceGraph = nullptr private
Definition at line 51 of file RedundantRelations.h.
Referenced by run().
redundantRelations
std::set<const Relation*> souffle::ast::analysis::RedundantRelationsAnalysis::redundantRelations private
Definition at line 53 of file RedundantRelations.h.
Referenced by getRedundantRelations(), print(), and run().
The documentation for this class was generated from the following files:
ast/analysis/RedundantRelations.h
ast/analysis/RedundantRelations.cpp