souffle: souffle::ast::SubroutineArgument Class Reference
souffle::ast::SubroutineArgument Class Reference
Defines the argument class for subrountines.
#include <SubroutineArgument.h>
Public Member Functions
SubroutineArgument * clone () const override
Create clone.
size_t getNumber () const
Return argument index.
SubroutineArgument (size_t index, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
size_t index
Index of subroutine argument.
Detailed Description
Defines the argument class for subrountines.
Definition at line 33 of file SubroutineArgument.h.
Constructor & Destructor Documentation
SubroutineArgument()
souffle::ast::SubroutineArgument::SubroutineArgument (size_t index, SrcLocation loc = {}) inline
Definition at line 35 of file SubroutineArgument.h.
References index.
Referenced by clone().
 {}) : Argument(std::move(loc)), index(index) {}
Member Function Documentation
clone()
SubroutineArgument* souffle::ast::SubroutineArgument::clone () const inline override virtual
Create clone.
Implements souffle::ast::Argument.
Definition at line 42 of file SubroutineArgument.h.
References souffle::ast::Node::getSrcLoc(), and SubroutineArgument().
{
         return new SubroutineArgument(index, getSrcLoc());
     }
equal()
bool souffle::ast::SubroutineArgument::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 51 of file SubroutineArgument.h.
References index.
{
         const auto& other = static_cast<const SubroutineArgument&>(node);
         return index == other.index;
     }
getNumber()
size_t souffle::ast::SubroutineArgument::getNumber () const inline
Return argument index.
Definition at line 38 of file SubroutineArgument.h.
References index.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return index;
     }
print()
void souffle::ast::SubroutineArgument::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 47 of file SubroutineArgument.h.
{
         os << "arg(" << index << ")";
     }
Field Documentation
index
size_t souffle::ast::SubroutineArgument::index private
Index of subroutine argument.
Definition at line 58 of file SubroutineArgument.h.
Referenced by equal(), getNumber(), and SubroutineArgument().
The documentation for this class was generated from the following file:
ast/SubroutineArgument.h