souffle: souffle::ast::transform::PolymorphicObjectsTransformer Class Reference
souffle::ast::transform::PolymorphicObjectsTransformer Class Reference
Transformation pass to determine instances of polymorphic object objects = Functors (plus, minus...) ∪ binary constraints (>, ≥ ...) ∪ aggregation ∪ numeric constants.
#include <PolymorphicObjects.h>
Public Member Functions
PolymorphicObjectsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Transformation pass to determine instances of polymorphic object objects = Functors (plus, minus...) ∪ binary constraints (>, ≥ ...) ∪ aggregation ∪ numeric constants.
Definition at line 31 of file PolymorphicObjects.h.
Member Function Documentation
clone()
PolymorphicObjectsTransformer* souffle::ast::transform::PolymorphicObjectsTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 37 of file PolymorphicObjects.h.
References transform().
{
         return new PolymorphicObjectsTransformer();
     }
getName()
std::string souffle::ast::transform::PolymorphicObjectsTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 33 of file PolymorphicObjects.h.
{
         return "PolymorphicObjectsTransformer";
     }
transform()
bool souffle::ast::transform::PolymorphicObjectsTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 42 of file PolymorphicObjects.cpp.
References souffle::any_of(), souffle::ast::Program::apply(), souffle::convertOverloadedAggregator(), souffle::convertOverloadedConstraint(), souffle::Float, souffle::ast::NumericConstant::Float, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::NumericConstant::Int, souffle::ast::analysis::isOfKind(), souffle::isOverloaded(), souffle::isOverloadedAggregator(), souffle::Signed, souffle::Symbol, types, souffle::ast::NumericConstant::Uint, souffle::Unsigned, and souffle::ast::validOverloads().
Referenced by clone().
{
     struct TypeRewriter : public NodeMapper {
         mutable bool changed{false};
         const TypeAnalysis& typeAnalysis;
         ErrorReport& report;
         TypeRewriter(const TypeAnalysis& typeAnalysis, ErrorReport& report)
                 : typeAnalysis(typeAnalysis), report(report) {}
         Own<Node> operator()(Own<Node> node) const override {
             // Utility lambdas to determine if all args are of the same type.
             auto isFloat = [&](const Argument* argument) {
                 return isOfKind(typeAnalysis.getTypes(argument), TypeAttribute::Float);
             };
             auto isUnsigned = [&](const Argument* argument) {
                 return isOfKind(typeAnalysis.getTypes(argument), TypeAttribute::Unsigned);
             };
             auto isSymbol = [&](const Argument* argument) {
                 return isOfKind(typeAnalysis.getTypes(argument), TypeAttribute::Symbol);
             };
             // rewrite sub-expressions first
             node->apply(*this);
             // It's possible that at this stage we get an undeclared clause.
             // In this case types can't be assigned to it, and the procedure getTypes can fail
             try {
                 // Handle numeric constant
                 if (auto* numericConstant = dynamic_cast<NumericConstant*>(node.get())) {
                     // Check if there is no value yet.
                     if (!numericConstant->getType().has_value()) {
                         TypeSet types = typeAnalysis.getTypes(numericConstant);
                         auto hasOfKind = [&](TypeAttribute kind) -> bool {
                             return any_of(
                                     types, [&](const analysis::Type& type) { return isOfKind(type, kind); });
                         };
                         if (hasOfKind(TypeAttribute::Signed)) {
                             numericConstant->setType(NumericConstant::Type::Int);
                             changed = true;
                         } else if (hasOfKind(TypeAttribute::Unsigned)) {
                             numericConstant->setType(NumericConstant::Type::Uint);
                             changed = true;
                         } else if (hasOfKind(TypeAttribute::Float)) {
                             numericConstant->setType(NumericConstant::Type::Float);
                             changed = true;
                         }
                     }
                 }
                 // Handle functor
                 auto* functor = as<IntrinsicFunctor>(node);
                 if (functor && !functor->getFunctionInfo()) {
                     // any valid candidate will do. pick the first.
                     auto candidates = validOverloads(typeAnalysis, *functor);
                     if (!candidates.empty()) {
                         functor->setFunctionInfo(candidates.front().get());
                         changed = true;
                     }
                 }
                 // Handle binary constraint
                 if (auto* binaryConstraint = dynamic_cast<BinaryConstraint*>(node.get())) {
                     if (isOverloaded(binaryConstraint->getOperator())) {
                         // Get arguments
                         auto* leftArg = binaryConstraint->getLHS();
                         auto* rightArg = binaryConstraint->getRHS();
                         auto oldOp = binaryConstraint->getOperator();
                         // Both args must be of the same type
                         if (isFloat(leftArg) && isFloat(rightArg)) {
                             binaryConstraint->setOperator(convertOverloadedConstraint(
                                     binaryConstraint->getOperator(), TypeAttribute::Float));
                         } else if (isUnsigned(leftArg) && isUnsigned(rightArg)) {
                             binaryConstraint->setOperator(convertOverloadedConstraint(
                                     binaryConstraint->getOperator(), TypeAttribute::Unsigned));
                         } else if (isSymbol(leftArg) && isSymbol(rightArg)) {
                             binaryConstraint->setOperator(convertOverloadedConstraint(
                                     binaryConstraint->getOperator(), TypeAttribute::Symbol));
                         }
                         changed |= binaryConstraint->getOperator() != oldOp;
                     }
                 }
                 if (auto* aggregator = dynamic_cast<Aggregator*>(node.get())) {
                     if (isOverloadedAggregator(aggregator->getOperator())) {
                         auto* targetExpression = aggregator->getTargetExpression();
                         auto oldOp = aggregator->getOperator();
                         if (isFloat(targetExpression)) {
                             aggregator->setOperator(convertOverloadedAggregator(
                                     aggregator->getOperator(), TypeAttribute::Float));
                         } else if (isUnsigned(targetExpression)) {
                             aggregator->setOperator(convertOverloadedAggregator(
                                     aggregator->getOperator(), TypeAttribute::Unsigned));
                         }
                         changed |= aggregator->getOperator() != oldOp;
                     }
                 }
             } catch (std::out_of_range&) {
                 // No types to convert in undeclared clauses
             }
             return node;
         }
     };
     const TypeAnalysis& typeAnalysis = *translationUnit.getAnalysis<analysis::TypeAnalysis>();
     TypeRewriter update(typeAnalysis, translationUnit.getErrorReport());
     translationUnit.getProgram().apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/PolymorphicObjects.h
ast/transform/PolymorphicObjects.cpp