souffle: souffle::ram::transform::Transformer Class Reference
souffle::ram::transform::Transformer Class Reference abstract
Transformer abstract transformer class for a translation unit
#include <Transformer.h>
Public Member Functions
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual std::string getName () const =0
get name of the transformer
virtual ~Transformer ()=default
Protected Member Functions
virtual bool transform (TranslationUnit &translationUnit)=0
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transformer abstract transformer class for a translation unit
This is an abstract class to implement transformers. A transformer takes a translation unit and changes its state.
Transformers can be composed using other transformers.
For debugging purposes, a transformer has a name (this will show up in the debug report) and a protected method transform(), that performs the actual transformation.
The method apply is used to call transform() and does the reporting of the debug information.
Definition at line 44 of file Transformer.h.
Constructor & Destructor Documentation
~Transformer()
virtual souffle::ram::transform::Transformer::~Transformer () virtual default
Member Function Documentation
apply()
bool souffle::ram::transform::Transformer::apply (TranslationUnit & translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Definition at line 33 of file Transformer.cpp.
References souffle::DebugReport::addCodeSection(), souffle::Global::config(), souffle::test::count(), souffle::DebugReport::endSection(), souffle::ram::TranslationUnit::getDebugReport(), souffle::ram::TranslationUnit::getErrorReport(), getName(), souffle::ErrorReport::getNumErrors(), souffle::ram::TranslationUnit::getProgram(), souffle::ram::TranslationUnit::invalidateAnalyses(), souffle::now(), souffle::DebugReport::startSection(), souffle::toString(), and transform().
Referenced by souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::ram::transform::IfConversionTransformer::convertIndexScans(), souffle::ram::transform::ChoiceConversionTransformer::convertScans(), souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::ram::transform::ExpandFilterTransformer::expandFilters(), souffle::ram::transform::HoistAggregateTransformer::hoistAggregate(), souffle::ram::transform::MakeIndexTransformer::makeIndex(), souffle::ram::transform::ParallelTransformer::parallelizeOperations(), souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak(), souffle::ram::transform::TupleIdTransformer::reorderOperations(), and souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter().
{
     const bool debug = Global::config().has("debug-report");
     const bool verbose = Global::config().has("verbose");
     std::string ramProgStrOld = debug ? toString(translationUnit.getProgram()) : "";
     // invoke the transformation
     auto start = std::chrono::high_resolution_clock::now();
     bool changed = transform(translationUnit);
     auto end = std::chrono::high_resolution_clock::now();
     // invalidate analyses in case the program has changed
     if (changed) {
         translationUnit.invalidateAnalyses();
     }
     // print runtime & change info for transformer in verbose mode
     if (verbose && (!isA<MetaTransformer>(this))) {
         std::string changedString = changed ? "changed" : "unchanged";
         std::cout << getName() << " time: " << std::chrono::duration<double>(end - start).count() << "sec ["
                   << changedString << "]" << std::endl;
     }
     // print program after transformation in debug report
     if (debug) {
         translationUnit.getDebugReport().startSection();
         if (changed) {
             translationUnit.getDebugReport().addCodeSection(getName(), "RAM Program after " + getName(),
                     "ram", ramProgStrOld, toString(translationUnit.getProgram()));
             translationUnit.getDebugReport().endSection(getName(), getName());
         } else {
             translationUnit.getDebugReport().endSection(getName(), getName() + " " + " (unchanged)");
         }
     }
     // abort evaluation of the program if errors were encountered
     if (translationUnit.getErrorReport().getNumErrors() != 0) {
         std::cerr << translationUnit.getErrorReport();
         std::cerr << translationUnit.getErrorReport().getNumErrors()
                   << " errors generated, evaluation aborted" << std::endl;
         exit(EXIT_FAILURE);
     }
     return changed;
 }
getName()
virtual std::string souffle::ram::transform::Transformer::getName () const pure virtual
get name of the transformer
Implemented in souffle::ram::transform::IndexedInequalityTransformer, souffle::ram::transform::HoistConditionsTransformer, souffle::ram::transform::MakeIndexTransformer, souffle::ram::transform::ChoiceConversionTransformer, souffle::ram::transform::IfConversionTransformer, souffle::ram::transform::ReorderConditionsTransformer, souffle::ram::transform::EliminateDuplicatesTransformer, souffle::ram::transform::ReorderFilterBreak, souffle::ram::transform::TransformerSequence, souffle::ram::transform::CollapseFiltersTransformer, souffle::ram::transform::ExpandFilterTransformer, souffle::ram::transform::ParallelTransformer, souffle::ram::transform::TupleIdTransformer, souffle::ram::transform::ReportIndexTransformer, souffle::ram::transform::ConditionalTransformer, souffle::ram::transform::LoopTransformer, and souffle::ram::transform::HoistAggregateTransformer.
Referenced by apply().
transform()
virtual bool souffle::ram::transform::Transformer::transform (TranslationUnit & translationUnit) protected pure virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implemented in souffle::ram::transform::MakeIndexTransformer, souffle::ram::transform::ChoiceConversionTransformer, souffle::ram::transform::HoistConditionsTransformer, souffle::ram::transform::IndexedInequalityTransformer, souffle::ram::transform::IfConversionTransformer, souffle::ram::transform::ReorderConditionsTransformer, souffle::ram::transform::EliminateDuplicatesTransformer, souffle::ram::transform::ReorderFilterBreak, souffle::ram::transform::CollapseFiltersTransformer, souffle::ram::transform::ExpandFilterTransformer, souffle::ram::transform::TupleIdTransformer, souffle::ram::transform::ParallelTransformer, souffle::ram::transform::TransformerSequence, souffle::ram::transform::HoistAggregateTransformer, souffle::ram::transform::ReportIndexTransformer, souffle::ram::transform::ConditionalTransformer, and souffle::ram::transform::LoopTransformer.
Referenced by apply().
The documentation for this class was generated from the following files:
ram/transform/Transformer.h
ram/transform/Transformer.cpp