souffle: souffle::ast::BranchDeclaration Class Reference
souffle::ast::BranchDeclaration Class Reference
Wrapper for the single branch declaration (product type) inside ADT declaration.
#include <BranchDeclaration.h>
Public Member Functions
BranchDeclaration (std::string constructor, VecOwn< Attribute > fields, SrcLocation loc={})
BranchDeclaration * clone () const override
Create a clone (i.e.
const std::string & getConstructor () const
std::vector< Attribute * > getFields ()
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::ast::Node
virtual bool equal (const Node &) const
Abstract equality check for two AST nodes.
Private Attributes
std::string constructor
VecOwn< Attribute > fields
Detailed Description
Wrapper for the single branch declaration (product type) inside ADT declaration.
Parameters
constructor An entity used to create a variant type. Can be though of as a name of the branch.
fields Branch arguments and their types.
A branch declaration corresponds to a product type and forms a part of ADT declaration. Currently it's required for all the branches to have unique names.
Definition at line 42 of file BranchDeclaration.h.
Constructor & Destructor Documentation
BranchDeclaration()
souffle::ast::BranchDeclaration::BranchDeclaration (std::string constructor, VecOwn< Attribute > fields, SrcLocation loc = {}) inline
Definition at line 44 of file BranchDeclaration.h.
References constructor, fields, and souffle::ast::Node::Node().
Referenced by clone().
                                                                                          {})
             : Node(std::move(loc)), constructor(std::move(constructor)), fields(std::move(fields)){};
Member Function Documentation
clone()
BranchDeclaration* souffle::ast::BranchDeclaration::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 55 of file BranchDeclaration.h.
References BranchDeclaration(), souffle::clone(), and souffle::ast::Node::getSrcLoc().
{
         return new BranchDeclaration(constructor, souffle::clone(fields), getSrcLoc());
     }
getConstructor()
const std::string& souffle::ast::BranchDeclaration::getConstructor () const inline
Definition at line 47 of file BranchDeclaration.h.
References constructor.
{
         return constructor;
     }
getFields()
std::vector<Attribute*> souffle::ast::BranchDeclaration::getFields () inline
Definition at line 51 of file BranchDeclaration.h.
References souffle::toPtrVector().
{
         return toPtrVector(fields);
     }
print()
void souffle::ast::BranchDeclaration::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 60 of file BranchDeclaration.h.
References tinyformat::format(), and souffle::join().
{
         os << tfm::format("%s {%s}", constructor, join(fields, ", "));
     }
Field Documentation
constructor
std::string souffle::ast::BranchDeclaration::constructor private
Definition at line 65 of file BranchDeclaration.h.
Referenced by BranchDeclaration(), and getConstructor().
fields
VecOwn<Attribute> souffle::ast::BranchDeclaration::fields private
Definition at line 66 of file BranchDeclaration.h.
Referenced by BranchDeclaration().
The documentation for this class was generated from the following file:
ast/BranchDeclaration.h