souffle: souffle::ast::analysis::ComponentLookupAnalysis Class Reference
souffle::ast::analysis::ComponentLookupAnalysis Class Reference
#include <ComponentLookup.h>
Public Member Functions
ComponentLookupAnalysis ()
const Component * getComponent (const Component *scope, const std::string &name, const TypeBinding &activeBinding) const
Performs a lookup operation for a component with the given name within the addressed scope.
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "component-lookup"
Private Attributes
std::map< const Component *, const Component * > enclosingComponent
std::set< const Component * > globalScopeComponents
std::map< const Component *, std::set< const Component * > > nestedComponents
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 74 of file ComponentLookup.h.
Constructor & Destructor Documentation
ComponentLookupAnalysis()
souffle::ast::analysis::ComponentLookupAnalysis::ComponentLookupAnalysis () inline
Definition at line 78 of file ComponentLookup.h.
 : Analysis(name) {}
Member Function Documentation
getComponent()
const Component * souffle::ast::analysis::ComponentLookupAnalysis::getComponent (const Component * scope, const std::string & name, const TypeBinding & activeBinding) const
Performs a lookup operation for a component with the given name within the addressed scope.
Parameters
scope the component scope to lookup in (null for global scope)
name the name of the component to be looking for
Returns
a pointer to the obtained component or null if there is no such component.
Definition at line 42 of file ComponentLookup.cpp.
References souffle::ast::QualifiedName::empty(), enclosingComponent, souffle::ast::analysis::TypeBinding::find(), souffle::ast::Component::getComponents(), globalScopeComponents, name, and souffle::toString().
Referenced by souffle::ast::transform::ComponentChecker::checkComponent(), and souffle::ast::transform::ComponentChecker::checkComponentNameReference().
{
     // forward according to binding (we do not do this recursively on purpose)
     QualifiedName boundName = activeBinding.find(name);
     if (boundName.empty()) {
         // compName is not bound to anything => just just compName
         boundName = name;
     }
     // search nested scopes bottom up
     const Component* searchScope = scope;
     while (searchScope != nullptr) {
         for (const Component* cur : searchScope->getComponents()) {
             if (cur->getComponentType()->getName() == toString(boundName)) {
                 return cur;
             }
         }
         auto found = enclosingComponent.find(searchScope);
         if (found != enclosingComponent.end()) {
             searchScope = found->second;
         } else {
             searchScope = nullptr;
             break;
         }
     }
     // check global scope
     for (const Component* cur : globalScopeComponents) {
         if (cur->getComponentType()->getName() == toString(boundName)) {
             return cur;
         }
     }
     // no such component in scope
     return nullptr;
 }
run()
void souffle::ast::analysis::ComponentLookupAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 27 of file ComponentLookup.cpp.
References enclosingComponent, souffle::ast::Program::getComponents(), souffle::ast::Component::getComponents(), souffle::ast::TranslationUnit::getProgram(), globalScopeComponents, nestedComponents, and souffle::ast::visitDepthFirst().
{
     Program& program = translationUnit.getProgram();
     for (Component* component : program.getComponents()) {
         globalScopeComponents.insert(component);
         enclosingComponent[component] = nullptr;
     }
     visitDepthFirst(program, [&](const Component& cur) {
         nestedComponents[&cur];
         for (Component* nestedComponent : cur.getComponents()) {
             nestedComponents[&cur].insert(nestedComponent);
             enclosingComponent[nestedComponent] = &cur;
         }
     });
 }
Field Documentation
enclosingComponent
std::map<const Component*, const Component*> souffle::ast::analysis::ComponentLookupAnalysis::enclosingComponent private
Definition at line 98 of file ComponentLookup.h.
Referenced by getComponent(), and run().
globalScopeComponents
std::set<const Component*> souffle::ast::analysis::ComponentLookupAnalysis::globalScopeComponents private
Definition at line 94 of file ComponentLookup.h.
Referenced by getComponent(), and run().
name
constexpr const char* souffle::ast::analysis::ComponentLookupAnalysis::name = "component-lookup" static
Definition at line 76 of file ComponentLookup.h.
Referenced by getComponent().
nestedComponents
std::map<const Component*, std::set<const Component*> > souffle::ast::analysis::ComponentLookupAnalysis::nestedComponents private
Definition at line 96 of file ComponentLookup.h.
Referenced by run().
The documentation for this class was generated from the following files:
ast/analysis/ComponentLookup.h
ast/analysis/ComponentLookup.cpp