souffle: souffle::ast::BinaryConstraint Class Reference
souffle::ast::BinaryConstraint Class Reference
Binary constraint class.
#include <BinaryConstraint.h>
Public Member Functions
void apply (const NodeMapper &map) override
BinaryConstraint (BinaryConstraintOp o, Own< Argument > ls, Own< Argument > rs, SrcLocation loc={})
BinaryConstraint * clone () const override
std::vector< const Node * > getChildNodes () const override
Argument * getLHS () const
Return left-hand side argument.
BinaryConstraintOp getOperator () const
Return binary operator.
Argument * getRHS () const
Return right-hand side argument.
void setOperator (BinaryConstraintOp op)
Set binary operator.
Public Member Functions inherited from souffle::ast::analysis::Constraint< Var >
virtual bool update (Assignment< Var > &ass) const =0
Requests the given assignment to be updated according to this constraint.
virtual ~Constraint ()=default
A virtual destructor.
Protected Member Functions
bool equal (const Node &node) const override
void print (std::ostream &os) const override
Adds print support for constraints (debugging)
Protected Attributes
Own< Argument > lhs
Left-hand side argument of binary constraint.
BinaryConstraintOp operation
Constraint operator.
Own< Argument > rhs
Right-hand side argument of binary constraint.
Detailed Description
Binary constraint class.
Example: x = y
A binary constraint has a constraint operator, a left-hand side expression, and right-hand side expression.
Definition at line 46 of file BinaryConstraint.h.
Constructor & Destructor Documentation
BinaryConstraint()
souffle::ast::BinaryConstraint::BinaryConstraint (BinaryConstraintOp o, Own< Argument > ls, Own< Argument > rs, SrcLocation loc = {}) inline
Definition at line 48 of file BinaryConstraint.h.
References lhs, operation, and rhs.
Referenced by clone().
                                                                                                  {})
             : Constraint(std::move(loc)), operation(o), lhs(std::move(ls)), rhs(std::move(rs)) {}
Member Function Documentation
apply()
void souffle::ast::BinaryConstraint::apply (const NodeMapper & map) inline override
Definition at line 75 of file BinaryConstraint.h.
References lhs, souffle::map(), and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
clone()
BinaryConstraint* souffle::ast::BinaryConstraint::clone () const inline override
Definition at line 71 of file BinaryConstraint.h.
References BinaryConstraint(), souffle::clone(), lhs, operation, and rhs.
{
         return new BinaryConstraint(operation, souffle::clone(lhs), souffle::clone(rhs), getSrcLoc());
     }
equal()
bool souffle::ast::BinaryConstraint::equal (const Node & node) const inline override protected
Definition at line 89 of file BinaryConstraint.h.
References souffle::equal_ptr(), lhs, operation, and rhs.
{
         assert(isA<BinaryConstraint>(&node));
         const auto& other = static_cast<const BinaryConstraint&>(node);
         return operation == other.operation && equal_ptr(lhs, other.lhs) && equal_ptr(rhs, other.rhs);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::BinaryConstraint::getChildNodes () const inline override
Definition at line 80 of file BinaryConstraint.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
getLHS()
Argument* souffle::ast::BinaryConstraint::getLHS () const inline
Return left-hand side argument.
Definition at line 52 of file BinaryConstraint.h.
References lhs.
Referenced by souffle::ast::transform::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::ast::transform::FoldAnonymousRecords::isValidRecordConstraint(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), souffle::AstToRamTranslator::translateConstraint(), souffle::ast::transform::TypeChecker::visitBinaryConstraint(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitBinaryConstraint().
{
         return lhs.get();
     }
getOperator()
BinaryConstraintOp souffle::ast::BinaryConstraint::getOperator () const inline
Return binary operator.
Definition at line 62 of file BinaryConstraint.h.
References operation.
Referenced by souffle::ast::transform::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::ast::BindingStore::generateBindingDependencies(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), souffle::ast::transform::FoldAnonymousRecords::transformClause(), souffle::AstToRamTranslator::translateConstraint(), and souffle::ast::transform::TypeChecker::visitBinaryConstraint().
{
         return operation;
     }
getRHS()
Argument* souffle::ast::BinaryConstraint::getRHS () const inline
Return right-hand side argument.
Definition at line 57 of file BinaryConstraint.h.
References rhs.
Referenced by souffle::ast::transform::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), souffle::AstToRamTranslator::translateConstraint(), souffle::ast::transform::TypeChecker::visitBinaryConstraint(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitBinaryConstraint().
{
         return rhs.get();
     }
print()
void souffle::ast::BinaryConstraint::print (std::ostream & out) const inline override protected virtual
Adds print support for constraints (debugging)
Implements souffle::ast::analysis::Constraint< Var >.
Definition at line 85 of file BinaryConstraint.h.
References lhs, operation, and rhs.
{
         os << *lhs << " " << operation << " " << *rhs;
     }
setOperator()
void souffle::ast::BinaryConstraint::setOperator (BinaryConstraintOp op) inline
Set binary operator.
Definition at line 67 of file BinaryConstraint.h.
References operation.
{
         operation = op;
     }
Field Documentation
lhs
Own<Argument> souffle::ast::BinaryConstraint::lhs protected
Left-hand side argument of binary constraint.
Definition at line 99 of file BinaryConstraint.h.
Referenced by apply(), BinaryConstraint(), clone(), equal(), getChildNodes(), getLHS(), and print().
operation
BinaryConstraintOp souffle::ast::BinaryConstraint::operation protected
Constraint operator.
Definition at line 96 of file BinaryConstraint.h.
Referenced by BinaryConstraint(), clone(), equal(), getOperator(), print(), and setOperator().
rhs
Own<Argument> souffle::ast::BinaryConstraint::rhs protected
Right-hand side argument of binary constraint.
Definition at line 102 of file BinaryConstraint.h.
Referenced by apply(), BinaryConstraint(), clone(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
ast/BinaryConstraint.h