souffle: souffle::ast::Term Class Reference
souffle::ast::Term Class Reference
Defines an abstract term class used for functors and other constructors.
#include <Term.h>
Public Member Functions
void addArgument (Own< Argument > arg)
Add argument to argument list.
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< Argument * > getArguments () const
Get arguments.
std::vector< const Node * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::ast::Argument
Argument * clone () const override=0
Create clone.
Public Member Functions inherited from souffle::ast::Node
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
template<typename... Operands>
Term (Operands &&... operands)
template<typename... Operands>
Term (SrcLocation loc, Operands &&... operands)
Term (VecOwn< Argument > operands, SrcLocation loc={})
Protected Member Functions inherited from souffle::ast::Node
virtual void print (std::ostream &os) const =0
Output to a given output stream.
Protected Attributes
VecOwn< Argument > args
Arguments.
Static Private Member Functions
template<typename... Operands>
static VecOwn< Argument > asVec (Operands... ops)
Detailed Description
Defines an abstract term class used for functors and other constructors.
Definition at line 36 of file Term.h.
Constructor & Destructor Documentation
Term() [1/3]
template<typename... Operands> souffle::ast::Term::Term (Operands &&... operands) inline protected
Definition at line 39 of file Term.h.
Referenced by souffle::ast::BranchInit::BranchInit(), and souffle::ast::RecordInit::RecordInit().
 : Term(asVec(std::forward<Operands>(operands)...)) {}
Term() [2/3]
template<typename... Operands> souffle::ast::Term::Term (SrcLocation loc, Operands &&... operands) inline protected
Definition at line 42 of file Term.h.
             : Term(asVec(std::forward<Operands>(operands)...), std::move(loc)) {}
Term() [3/3]
souffle::ast::Term::Term (VecOwn< Argument > operands, SrcLocation loc = {}) inline protected
Definition at line 45 of file Term.h.
References args.
                                                       {})
             : Argument(std::move(loc)), args(std::move(operands)) {}
Member Function Documentation
addArgument()
void souffle::ast::Term::addArgument (Own< Argument > arg) inline
Add argument to argument list.
Definition at line 55 of file Term.h.
References args.
{
         args.push_back(std::move(arg));
     }
apply()
void souffle::ast::Term::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 67 of file Term.h.
References args, and souffle::map().
{
         for (auto& arg : args) {
             arg = map(std::move(arg));
         }
     }
asVec()
template<typename... Operands> static VecOwn<Argument> souffle::ast::Term::asVec (Operands... ops) inline static private
Definition at line 84 of file Term.h.
{
         Own<Argument> ary[] = {std::move(ops)...};
         VecOwn<Argument> xs;
         for (auto&& x : ary) {
             xs.push_back(std::move(x));
         }
         return xs;
     }
equal()
bool souffle::ast::Term::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Reimplemented in souffle::ast::UserDefinedFunctor.
Definition at line 74 of file Term.h.
References args, and souffle::equal_targets().
Referenced by souffle::ast::UserDefinedFunctor::equal(), and souffle::ast::IntrinsicFunctor::equal().
{
         const auto& other = static_cast<const Term&>(node);
         return equal_targets(args, other.args);
     }
getArguments()
std::vector<Argument*> souffle::ast::Term::getArguments () const inline
Get arguments.
Definition at line 50 of file Term.h.
References args, and souffle::toPtrVector().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkLiteral(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::normaliseArguments(), souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), souffle::AstToRamTranslator::translateValue(), souffle::ast::validOverloads(), souffle::ast::transform::TypeChecker::visitBranchInit(), souffle::ast::analysis::TypeConstraintsAnalysis::visitBranchInit(), souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor(), souffle::ast::transform::TypeChecker::visitIntrinsicFunctor(), souffle::ast::transform::TypeChecker::visitRecordInit(), souffle::ast::analysis::TypeConstraintsAnalysis::visitRecordInit(), and souffle::ast::transform::TypeChecker::visitUserDefinedFunctor().
{
         return toPtrVector(args);
     }
getChildNodes()
std::vector<const Node*> souffle::ast::Term::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::ast::Node.
Definition at line 59 of file Term.h.
References args, and souffle::ast::Node::getChildNodes().
{
         auto res = Argument::getChildNodes();
         for (auto& cur : args) {
             res.push_back(cur.get());
         }
         return res;
     }
Field Documentation
args
VecOwn<Argument> souffle::ast::Term::args protected
Arguments.
Definition at line 80 of file Term.h.
Referenced by addArgument(), apply(), souffle::ast::RecordInit::clone(), equal(), getArguments(), getChildNodes(), souffle::ast::RecordInit::print(), and Term().
The documentation for this class was generated from the following file:
ast/Term.h