souffle: souffle::ram::transform::CollapseFiltersTransformer Class Reference
souffle::ram::transform::CollapseFiltersTransformer Class Reference
Transforms consecutive filters into a single filter containing a conjunction.
#include <CollapseFilters.h>
Public Member Functions
bool collapseFilters (Program &program)
Collapse consecutive filter operations.
std::string getName () const override
get name of the transformer
Public Member Functions inherited from souffle::ram::transform::Transformer
bool apply (TranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~Transformer ()=default
Protected Member Functions
bool transform (TranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transforms consecutive filters into a single filter containing a conjunction.
For example ..
QUERY
 ...
  IF C1
   IF C2
    ...
will be rewritten to
QUERY
 ...
  IF C1 /\ C2 then
   ...
Definition at line 48 of file CollapseFilters.h.
Member Function Documentation
collapseFilters()
bool souffle::ram::transform::CollapseFiltersTransformer::collapseFilters (Program & program)
Collapse consecutive filter operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 31 of file CollapseFilters.cpp.
References souffle::ram::transform::Transformer::apply(), souffle::ram::AbstractConditional::apply(), souffle::clone(), souffle::filter(), souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::makeLambdaRamMapper(), souffle::ram::toCondition(), and souffle::ram::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const Query& query) {
         std::function<Own<Node>(Own<Node>)> filterRewriter = [&](Own<Node> node) -> Own<Node> {
             if (const Filter* filter = dynamic_cast<Filter*>(node.get())) {
                 // true if two consecutive filters in loop nest found
                 bool canCollapse = false;
                 // storing conditions for collapsing
                 VecOwn<Condition> conditions;
                 const Filter* prevFilter = filter;
                 conditions.emplace_back(filter->getCondition().clone());
                 while (auto* nextFilter = dynamic_cast<Filter*>(&prevFilter->getOperation())) {
                     canCollapse = true;
                     conditions.emplace_back(nextFilter->getCondition().clone());
                     prevFilter = nextFilter;
                 }
                 if (canCollapse) {
                     changed = true;
                     node = mk<Filter>(toCondition(conditions), souffle::clone(&prevFilter->getOperation()),
                             prevFilter->getProfileText());
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<Query*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ram::transform::CollapseFiltersTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::ram::transform::Transformer.
Definition at line 50 of file CollapseFilters.h.
References collapseFilters().
{
         return "CollapseFiltersTransformer";
     }
transform()
bool souffle::ram::transform::CollapseFiltersTransformer::transform (TranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::ram::transform::Transformer.
Definition at line 62 of file CollapseFilters.h.
References collapseFilters(), and souffle::ram::TranslationUnit::getProgram().
{
         return collapseFilters(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/CollapseFilters.h
ram/transform/CollapseFilters.cpp