souffle: souffle::ast::Constant Class Reference
souffle::ast::Constant Class Reference abstract
Abstract constant class.
#include <Constant.h>
Public Member Functions
Constant * clone () const override=0
Create clone.
const std::string & getConstant () const
Get string representation of Constant.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
Constant (std::string value, SrcLocation loc={})
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
const std::string constant
String representation of constant.
Detailed Description
Abstract constant class.
Definition at line 32 of file Constant.h.
Constructor & Destructor Documentation
Constant()
souffle::ast::Constant::Constant (std::string value, SrcLocation loc = {}) inline protected
Definition at line 51 of file Constant.h.
Referenced by souffle::ast::NilConstant::NilConstant(), souffle::ast::NumericConstant::NumericConstant(), and souffle::ast::StringConstant::StringConstant().
                                                 {})
             : Argument(std::move(loc)), constant(std::move(value)){};
Member Function Documentation
clone()
Constant* souffle::ast::Constant::clone () const override pure virtual
Create clone.
Implements souffle::ast::Argument.
Implemented in souffle::ast::NumericConstant, souffle::ast::StringConstant, and souffle::ast::NilConstant.
equal()
bool souffle::ast::Constant::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Reimplemented in souffle::ast::NumericConstant.
Definition at line 46 of file Constant.h.
References constant.
Referenced by souffle::ast::NumericConstant::equal().
{
         const auto& other = static_cast<const Constant&>(node);
         return constant == other.constant;
     }
getConstant()
const std::string& souffle::ast::Constant::getConstant () const inline
Get string representation of Constant.
Definition at line 37 of file Constant.h.
References constant.
Referenced by souffle::ast::StringConstant::clone(), souffle::ast::NumericConstant::clone(), print(), souffle::ast::StringConstant::print(), souffle::AstToRamTranslator::translateValue(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
{
         return constant;
     }
print()
void souffle::ast::Constant::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Reimplemented in souffle::ast::StringConstant.
Definition at line 42 of file Constant.h.
References getConstant().
{
         os << getConstant();
     }
Field Documentation
constant
const std::string souffle::ast::Constant::constant private
String representation of constant.
Definition at line 52 of file Constant.h.
Referenced by equal(), and getConstant().
The documentation for this class was generated from the following file:
ast/Constant.h