souffle: souffle::ast::analysis::RecursiveClausesAnalysis Class Reference
souffle::ast::analysis::RecursiveClausesAnalysis Class Reference
Analysis pass identifying clauses which are recursive.
#include <RecursiveClauses.h>
Public Member Functions
void print (std::ostream &os) const override
print the analysis result in HTML format
bool recursive (const Clause *clause) const
RecursiveClausesAnalysis ()
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "recursive-clauses"
Private Member Functions
bool computeIsRecursive (const Clause &clause, const TranslationUnit &translationUnit) const
Determines whether the given clause is recursive within the given program.
Private Attributes
std::set< const Clause * > recursiveClauses
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Analysis pass identifying clauses which are recursive.
Definition at line 36 of file RecursiveClauses.h.
Constructor & Destructor Documentation
RecursiveClausesAnalysis()
souffle::ast::analysis::RecursiveClausesAnalysis::RecursiveClausesAnalysis () inline
Definition at line 40 of file RecursiveClauses.h.
References print(), and run().
 : Analysis(name) {}
Member Function Documentation
computeIsRecursive()
bool souffle::ast::analysis::RecursiveClausesAnalysis::computeIsRecursive (const Clause & clause, const TranslationUnit & translationUnit) const private
Determines whether the given clause is recursive within the given program.
Definition at line 50 of file RecursiveClauses.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::getHeadRelation(), and souffle::ast::TranslationUnit::getProgram().
Referenced by run().
{
     const auto& relationDetail = *translationUnit.getAnalysis<RelationDetailCacheAnalysis>();
     const Program& program = translationUnit.getProgram();
     // we want to reach the atom of the head through the body
     const Relation* trg = getHeadRelation(&clause, &program);
     std::set<const Relation*> reached;
     std::vector<const Relation*> worklist;
     // set up start list
     for (const auto* cur : getBodyLiterals<Atom>(clause)) {
         auto rel = relationDetail.getRelation(cur->getQualifiedName());
         if (rel == trg) {
             return true;
         }
         worklist.push_back(rel);
     }
     // process remaining elements
     while (!worklist.empty()) {
         // get next to process
         const Relation* cur = worklist.back();
         worklist.pop_back();
         // skip null pointers (errors in the input code)
         if (cur == nullptr) {
             continue;
         }
         // check whether this one has been checked before
         if (!reached.insert(cur).second) {
             continue;
         }
         // check all atoms in the relations
         for (const Clause* cl : relationDetail.getClauses(cur)) {
             for (const Atom* at : getBodyLiterals<Atom>(*cl)) {
                 auto rel = relationDetail.getRelation(at->getQualifiedName());
                 if (rel == trg) {
                     return true;
                 }
                 worklist.push_back(rel);
             }
         }
     }
     // no cycles found
     return false;
 }
print()
void souffle::ast::analysis::RecursiveClausesAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 46 of file RecursiveClauses.cpp.
References recursiveClauses.
Referenced by RecursiveClausesAnalysis().
{
     os << recursiveClauses << std::endl;
 }
recursive()
bool souffle::ast::analysis::RecursiveClausesAnalysis::recursive (const Clause * clause) const inline
Definition at line 46 of file RecursiveClauses.h.
References recursiveClauses.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return recursiveClauses.count(clause) != 0u;
     }
run()
void souffle::ast::analysis::RecursiveClausesAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 37 of file RecursiveClauses.cpp.
References computeIsRecursive(), souffle::ast::TranslationUnit::getProgram(), recursiveClauses, and souffle::ast::visitDepthFirst().
Referenced by RecursiveClausesAnalysis().
{
     Program& program = translationUnit.getProgram();
     visitDepthFirst(program, [&](const Clause& clause) {
         if (computeIsRecursive(clause, translationUnit)) {
             recursiveClauses.insert(&clause);
         }
     });
 }
Field Documentation
name
constexpr const char* souffle::ast::analysis::RecursiveClausesAnalysis::name = "recursive-clauses" static
Definition at line 38 of file RecursiveClauses.h.
recursiveClauses
std::set<const Clause*> souffle::ast::analysis::RecursiveClausesAnalysis::recursiveClauses private
Definition at line 51 of file RecursiveClauses.h.
Referenced by print(), recursive(), and run().
The documentation for this class was generated from the following files:
ast/analysis/RecursiveClauses.h
ast/analysis/RecursiveClauses.cpp