souffle: souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer Class Reference
souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer Class Reference
Database adornment.
#include <MagicSet.h>
Public Member Functions
AdornDatabaseTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Types
using adorned_predicate = std::pair< QualifiedName, std::string >
Private Member Functions
Own< Clause > adornClause (const Clause *clause, const std::string &adornmentMarker)
Returns the adorned version of a clause.
bool hasAdornmentToProcess () const
Check if any more relations need to be adorned.
adorned_predicate nextAdornmentToProcess ()
Pop off the next predicate adornment to process.
void queueAdornment (const QualifiedName &relName, const std::string &adornmentMarker)
Add an adornment to the ToDo queue if it hasn't been processed before.
bool transform (TranslationUnit &translationUnit) override
Static Private Member Functions
static QualifiedName getAdornmentID (const QualifiedName &relName, const std::string &adornmentMarker)
Get the unique identifier corresponding to an adorned predicate.
Private Attributes
VecOwn< Clause > adornedClauses
std::set< QualifiedName > headAdornmentsSeen
std::set< adorned_predicate > headAdornmentsToDo
VecOwn< Clause > redundantClauses
std::set< QualifiedName > relationsToIgnore
Detailed Description
Database adornment.
Adorns the rules of a database with variable flow and binding information. Prerequisite for the magic set transformation.
Definition at line 207 of file MagicSet.h.
Member Typedef Documentation
adorned_predicate
using souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adorned_predicate = std::pair<QualifiedName, std::string> private
Definition at line 218 of file MagicSet.h.
Member Function Documentation
adornClause()
Own< Clause > souffle::ast::transform::AdornDatabaseTransformer::adornClause (const Clause * clause, const std::string & adornmentMarker) private
Returns the adorned version of a clause.
Definition at line 517 of file MagicSet.cpp.
References souffle::ast::BindingStore::bindVariableStrongly(), souffle::ast::BindingStore::bindVariableWeakly(), souffle::clone(), souffle::contains(), souffle::ast::Atom::getArguments(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getExecutionPlan(), souffle::ast::Clause::getHead(), souffle::ast::Atom::getQualifiedName(), i, and souffle::ast::BindingStore::isBound().
{
     const auto& relName = clause->getHead()->getQualifiedName();
     const auto& headArgs = clause->getHead()->getArguments();
     BindingStore variableBindings(clause);
     /* Note that variables can be bound through:
      *  (1) an appearance in a body atom (strong)
      *  (2) an appearance in a bound field of the head atom (weak)
      *  (3) equality with a fully bound functor (via dependency analysis)
      *
      * When computing (3), appearances (1) and (2) must be separated to maintain the termination semantics of
      * the original program. Functor variables are not considered bound if they are only bound via the head.
      *
      * Justification: Suppose a new variable Y is marked as bound because of its appearance in a functor
      * Y=X+1, and X was already found to be bound:
      *  (1) If X was bound through a body atom, then the behaviour of typical magic-set is exhibited, where
      * the magic-set of Y is bounded by the values that X can take, which is bounded by induction.
      *  (2) If X was bound only through the head atom, then Y is only fixed to an appearance in a magic-atom.
      * In the presence of recursion, this can potentially lead to an infinitely-sized magic-set for an atom.
      *
      * Therefore, bound head atom vars should be marked as weakly bound.
      */
     for (size_t i = 0; i < adornmentMarker.length(); i++) {
         const auto* var = dynamic_cast<ast::Variable*>(headArgs[i]);
         assert(var != nullptr && "expected only variables in head");
         if (adornmentMarker[i] == 'b') {
             variableBindings.bindVariableWeakly(var->getName());
         }
     }
     // Create the adorned clause with an empty body
     auto adornedClause = mk<Clause>();
     // Copy over plans if needed
     if (clause->getExecutionPlan() != nullptr) {
         assert(contains(relationsToIgnore, clause->getHead()->getQualifiedName()) &&
                 "clauses with plans should be ignored");
         adornedClause->setExecutionPlan(souffle::clone(clause->getExecutionPlan()));
     }
     // Create the head atom
     auto adornedHeadAtom = mk<Atom>(getAdornmentID(relName, adornmentMarker));
     assert((adornmentMarker == "" || headArgs.size() == adornmentMarker.length()) &&
             "adornment marker should correspond to head atom variables");
     for (const auto* arg : headArgs) {
         const auto* var = dynamic_cast<const ast::Variable*>(arg);
         assert(var != nullptr && "expected only variables in head");
         adornedHeadAtom->addArgument(souffle::clone(var));
     }
     adornedClause->setHead(std::move(adornedHeadAtom));
     // Add in adorned body literals
     std::vector<Own<Literal>> adornedBodyLiterals;
     for (const auto* lit : clause->getBodyLiterals()) {
         if (const auto* negation = dynamic_cast<const Negation*>(lit)) {
             // Negated atoms should not be adorned, but their clauses should be anyway
             const auto negatedAtomName = negation->getAtom()->getQualifiedName();
             assert(contains(relationsToIgnore, negatedAtomName) && "negated atoms should not be adorned");
             queueAdornment(negatedAtomName, "");
         }
         if (!isA<Atom>(lit)) {
             // Non-atoms are added directly
             adornedBodyLiterals.push_back(souffle::clone(lit));
             continue;
         }
         const auto* atom = dynamic_cast<const Atom*>(lit);
         assert(atom != nullptr && "expected atom");
         // Form the appropriate adornment marker
         std::stringstream atomAdornment;
         if (!contains(relationsToIgnore, atom->getQualifiedName())) {
             for (const auto* arg : atom->getArguments()) {
                 const auto* var = dynamic_cast<const ast::Variable*>(arg);
                 assert(var != nullptr && "expected only variables in atom");
                 atomAdornment << (variableBindings.isBound(var->getName()) ? "b" : "f");
             }
         }
         auto currAtomAdornmentID = getAdornmentID(atom->getQualifiedName(), atomAdornment.str());
         // Add to the ToDo queue if needed
         queueAdornment(atom->getQualifiedName(), atomAdornment.str());
         // Add the adorned version to the clause
         auto adornedBodyAtom = souffle::clone(atom);
         adornedBodyAtom->setQualifiedName(currAtomAdornmentID);
         adornedBodyLiterals.push_back(std::move(adornedBodyAtom));
         // All arguments are now bound
         for (const auto* arg : atom->getArguments()) {
             const auto* var = dynamic_cast<const ast::Variable*>(arg);
             assert(var != nullptr && "expected only variables in atom");
             variableBindings.bindVariableStrongly(var->getName());
         }
     }
     adornedClause->setBodyLiterals(std::move(adornedBodyLiterals));
     return adornedClause;
 }
clone()
AdornDatabaseTransformer* souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 213 of file MagicSet.h.
{
         return new AdornDatabaseTransformer();
     }
getAdornmentID()
QualifiedName souffle::ast::transform::AdornDatabaseTransformer::getAdornmentID (const QualifiedName & relName, const std::string & adornmentMarker) static private
Get the unique identifier corresponding to an adorned predicate.
Definition at line 507 of file MagicSet.cpp.
References souffle::ast::QualifiedName::append().
{
     if (adornmentMarker == "") return relName;
     QualifiedName adornmentID(relName);
     std::stringstream adornmentMarkerRepr;
     adornmentMarkerRepr << "{" << adornmentMarker << "}";
     adornmentID.append(adornmentMarkerRepr.str());
     return adornmentID;
 }
getName()
std::string souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 209 of file MagicSet.h.
{
         return "AdornDatabaseTransformer";
     }
hasAdornmentToProcess()
bool souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::hasAdornmentToProcess () const inline private
Check if any more relations need to be adorned.
Definition at line 242 of file MagicSet.h.
{
         return !headAdornmentsToDo.empty();
     }
nextAdornmentToProcess()
adorned_predicate souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::nextAdornmentToProcess () inline private
Pop off the next predicate adornment to process.
Definition at line 247 of file MagicSet.h.
{
         assert(hasAdornmentToProcess() && "no adornment to pop");
         auto headAdornment = *(headAdornmentsToDo.begin());
         headAdornmentsToDo.erase(headAdornmentsToDo.begin());
         return headAdornment;
     }
queueAdornment()
void souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::queueAdornment (const QualifiedName & relName, const std::string & adornmentMarker) inline private
Add an adornment to the ToDo queue if it hasn't been processed before.
Definition at line 233 of file MagicSet.h.
References souffle::contains().
{
         auto adornmentID = getAdornmentID(relName, adornmentMarker);
         if (!contains(headAdornmentsSeen, adornmentID)) {
             headAdornmentsToDo.insert(std::make_pair(relName, adornmentMarker));
             headAdornmentsSeen.insert(adornmentID);
         }
     }
transform()
bool souffle::ast::transform::AdornDatabaseTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 618 of file MagicSet.cpp.
References souffle::ast::Program::addClause(), souffle::ast::Program::addRelation(), souffle::clone(), souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::getClauses(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::getRelation(), souffle::ast::Program::getRelations(), and souffle::ast::Program::removeClause().
{
     Program& program = translationUnit.getProgram();
     const auto& ioTypes = *translationUnit.getAnalysis<analysis::IOTypeAnalysis>();
     relationsToIgnore = getIgnoredRelations(translationUnit);
     // Output relations trigger the adornment process
     for (const auto* rel : program.getRelations()) {
         if (ioTypes.isOutput(rel) || ioTypes.isPrintSize(rel)) {
             queueAdornment(rel->getQualifiedName(), "");
         }
     }
     // Keep going while there's things to adorn
     while (hasAdornmentToProcess()) {
         // Pop off the next head adornment to do
         const auto& [relName, adornmentMarker] = nextAdornmentToProcess();
         // Add the adorned relation if needed
         if (adornmentMarker != "") {
             const auto* rel = getRelation(program, relName);
             assert(rel != nullptr && "relation does not exist");
             auto adornedRelation = mk<Relation>(getAdornmentID(relName, adornmentMarker));
             for (const auto* attr : rel->getAttributes()) {
                 adornedRelation->addAttribute(souffle::clone(attr));
             }
             program.addRelation(std::move(adornedRelation));
         }
         // Adorn every clause correspondingly
         for (const auto* clause : getClauses(program, relName)) {
             if (adornmentMarker == "") {
                 redundantClauses.push_back(souffle::clone(clause));
             }
             auto adornedClause = adornClause(clause, adornmentMarker);
             adornedClauses.push_back(std::move(adornedClause));
         }
     }
     // Swap over the redundant clauses with the adorned clauses
     for (const auto& clause : redundantClauses) {
         program.removeClause(clause.get());
     }
     for (auto& clause : adornedClauses) {
         program.addClause(souffle::clone(clause));
     }
     return !adornedClauses.empty() || !redundantClauses.empty();
 }
Field Documentation
adornedClauses
VecOwn<Clause> souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornedClauses private
Definition at line 223 of file MagicSet.h.
headAdornmentsSeen
std::set<QualifiedName> souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::headAdornmentsSeen private
Definition at line 221 of file MagicSet.h.
headAdornmentsToDo
std::set<adorned_predicate> souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::headAdornmentsToDo private
Definition at line 220 of file MagicSet.h.
redundantClauses
VecOwn<Clause> souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::redundantClauses private
Definition at line 224 of file MagicSet.h.
relationsToIgnore
std::set<QualifiedName> souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::relationsToIgnore private
Definition at line 225 of file MagicSet.h.
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp