souffle: souffle::ram::IndexChoice Class Reference
souffle::ram::IndexChoice Class Reference
Use an index to find a tuple in a relation such that a given condition holds.
#include <IndexChoice.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
IndexChoice * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
IndexChoice (Own< RelationReference > r, int ident, Own< Condition > cond, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::IndexOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
IndexOperation * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< Expression * >, std::vector< Expression * > > getRangePattern () const
Get range pattern.
IndexOperation (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
void printIndex (std::ostream &os) const
Helper method for printing.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractChoice
AbstractChoice (Own< Condition > cond)
void apply (const NodeMapper &map)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Getter for the condition.
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::IndexOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::NestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractChoice
bool equal (const Node &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::IndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractChoice
Own< Condition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Use an index to find a tuple in a relation such that a given condition holds.
Only one tuple is returned (if one exists), even if multiple tuples satisfying the condition exist.
For example:
QUERY
 ...
  CHOICE A AS t1 ON INDEX t1.x=10 AND t1.y = 20
  WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 54 of file IndexChoice.h.
Constructor & Destructor Documentation
IndexChoice()
souffle::ram::IndexChoice::IndexChoice (Own< RelationReference > r, int ident, Own< Condition > cond, RamPattern queryPattern, Own< Operation > nested, std::string profileText = "") inline
Definition at line 56 of file IndexChoice.h.
References souffle::ram::Relation::getArity(), souffle::ram::IndexOperation::getRangePattern(), and souffle::ram::RelationOperation::getRelation().
Referenced by clone().
             : IndexOperation(std::move(r), ident, std::move(queryPattern), std::move(nested),
                       std::move(profileText)),
               AbstractChoice(std::move(cond)) {
         assert(getRangePattern().first.size() == getRelation().getArity());
         assert(getRangePattern().second.size() == getRelation().getArity());
     }
Member Function Documentation
apply()
void souffle::ram::IndexChoice::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 65 of file IndexChoice.h.
References souffle::ram::AbstractChoice::apply(), souffle::ram::RelationOperation::apply(), souffle::map(), and souffle::ram::IndexOperation::queryPattern.
{
         RelationOperation::apply(map);
         for (auto& pattern : queryPattern.first) {
             pattern = map(std::move(pattern));
         }
         for (auto& pattern : queryPattern.second) {
             pattern = map(std::move(pattern));
         }
         AbstractChoice::apply(map);
     }
clone()
IndexChoice* souffle::ram::IndexChoice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::RelationOperation.
Reimplemented in souffle::ram::ParallelIndexChoice.
Definition at line 82 of file IndexChoice.h.
References souffle::clone(), souffle::ram::AbstractChoice::condition, souffle::ram::NestedOperation::getOperation(), souffle::ram::NestedOperation::getProfileText(), souffle::ram::TupleOperation::getTupleId(), i, IndexChoice(), souffle::ram::IndexOperation::queryPattern, and souffle::ram::RelationOperation::relationRef.
Referenced by souffle::ram::test::TEST().
{
         RamPattern resQueryPattern;
         for (const auto& i : queryPattern.first) {
             resQueryPattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             resQueryPattern.second.emplace_back(i->clone());
         }
         auto* res = new IndexChoice(souffle::clone(relationRef), getTupleId(), souffle::clone(condition),
                 std::move(resQueryPattern), souffle::clone(&getOperation()), getProfileText());
         return res;
     }
equal()
bool souffle::ram::IndexChoice::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 106 of file IndexChoice.h.
References souffle::ram::AbstractChoice::equal(), and souffle::ram::IndexOperation::equal().
{
         const auto& other = static_cast<const IndexChoice&>(node);
         return IndexOperation::equal(other) && AbstractChoice::equal(other);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::IndexChoice::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 76 of file IndexChoice.h.
References souffle::ram::AbstractChoice::getChildNodes(), and souffle::ram::IndexOperation::getChildNodes().
{
         auto res = IndexOperation::getChildNodes();
         res.push_back(AbstractChoice::getChildNodes().at(0));
         return res;
     }
print()
void souffle::ram::IndexChoice::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Reimplemented in souffle::ram::ParallelIndexChoice.
Definition at line 96 of file IndexChoice.h.
References souffle::ram::AbstractChoice::getCondition(), souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::NestedOperation::print(), souffle::ram::IndexOperation::printIndex(), and souffle::times().
{
         const Relation& rel = getRelation();
         os << times(" ", tabpos);
         os << "CHOICE " << rel.getName() << " AS t" << getTupleId();
         printIndex(os);
         os << " WHERE " << getCondition();
         os << std::endl;
         IndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/IndexChoice.h