souffle: souffle::ram::Relation Class Reference
souffle::ram::Relation Class Reference
Index.
#include <Relation.h>
Public Member Functions
Relation * clone () const override
Create a clone (i.e.
unsigned getArity () const
Get arity of relation.
const std::vector< std::string > & getAttributeNames () const
Get attribute names.
const std::vector< std::string > & getAttributeTypes () const
Get attribute types.
unsigned getAuxiliaryArity () const
Get number of auxiliary attributes.
const std::string & getName () const
Get name.
RelationRepresentation getRepresentation () const
Relation representation type.
bool isNullary () const
Is nullary relation.
bool isTemp () const
Is temporary relation (for semi-naive evaluation)
bool operator< (const Relation &other) const
Compare two relations via their name.
Relation (std::string name, size_t arity, size_t auxiliaryArity, std::vector< std::string > attributeNames, std::vector< std::string > attributeTypes, RelationRepresentation representation)
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &out) const override
Print RAM node.
Protected Attributes
const size_t arity
Arity, i.e., number of attributes.
const std::vector< std::string > attributeNames
Name of attributes.
const std::vector< std::string > attributeTypes
Type of attributes.
const size_t auxiliaryArity
Number of auxiliary attributes (e.g.
const std::string name
Name of relation.
const RelationRepresentation representation
Data-structure representation.
Detailed Description
Index.
A RAM Relation in the RAM intermediate representation.
An abstract class for performing indexed operations
Definition at line 35 of file Relation.h.
Constructor & Destructor Documentation
Relation()
souffle::ram::Relation::Relation (std::string name, size_t arity, size_t auxiliaryArity, std::vector< std::string > attributeNames, std::vector< std::string > attributeTypes, RelationRepresentation representation) inline
Definition at line 37 of file Relation.h.
References arity, and i.
Referenced by clone().
             : representation(representation), name(std::move(name)), arity(arity),
               auxiliaryArity(auxiliaryArity), attributeNames(std::move(attributeNames)),
               attributeTypes(std::move(attributeTypes)) {
         assert(this->attributeNames.size() == arity && "arity mismatch for attributes");
         assert(this->attributeTypes.size() == arity && "arity mismatch for types");
         for (std::size_t i = 0; i < arity; i++) {
             assert(!this->attributeNames[i].empty() && "no attribute name specified");
             assert(!this->attributeTypes[i].empty() && "no attribute type specified");
         }
     }
Member Function Documentation
clone()
Relation* souffle::ram::Relation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Node.
Definition at line 95 of file Relation.h.
References arity, attributeNames, attributeTypes, auxiliaryArity, name, Relation(), and representation.
Referenced by souffle::ram::test::TEST().
{
         return new Relation(name, arity, auxiliaryArity, attributeNames, attributeTypes, representation);
     }
equal()
bool souffle::ram::Relation::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 118 of file Relation.h.
References arity, attributeNames, attributeTypes, auxiliaryArity, name, and representation.
{
         assert(isA<Relation>(&node));
         const auto& other = static_cast<const Relation&>(node);
         return representation == other.representation && name == other.name && arity == other.arity &&
                auxiliaryArity == other.auxiliaryArity && attributeNames == other.attributeNames &&
                attributeTypes == other.attributeTypes;
     }
getArity()
unsigned souffle::ram::Relation::getArity () const inline
Get arity of relation.
Definition at line 81 of file Relation.h.
References arity.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::ComplexityAnalysis::getComplexity(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::NodeGenerator::getProjectSuperInstInfo(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), souffle::synthesiser::Relation::getSynthesiserRelation(), souffle::ram::IndexChoice::IndexChoice(), souffle::ram::IndexOperation::IndexOperation(), souffle::ram::IndexOperation::printIndex(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::MakeIndexTransformer::rewriteScan(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return arity;
     }
getAttributeNames()
const std::vector<std::string>& souffle::ram::Relation::getAttributeNames () const inline
Get attribute names.
Definition at line 61 of file Relation.h.
References attributeNames.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return attributeNames;
     }
getAttributeTypes()
const std::vector<std::string>& souffle::ram::Relation::getAttributeTypes () const inline
Get attribute types.
Definition at line 56 of file Relation.h.
References attributeTypes.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::MinIndexSelection::getAttributesToDischarge(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteScan().
{
         return attributeTypes;
     }
getAuxiliaryArity()
unsigned souffle::ram::Relation::getAuxiliaryArity () const inline
Get number of auxiliary attributes.
Definition at line 86 of file Relation.h.
References auxiliaryArity.
Referenced by souffle::ram::analysis::IndexAnalysis::getSearchSignature().
{
         return auxiliaryArity;
     }
getName()
const std::string& souffle::ram::Relation::getName () const inline
Get name.
Definition at line 51 of file Relation.h.
References name.
Referenced by souffle::synthesiser::Synthesiser::generateCode(), souffle::synthesiser::Synthesiser::getRelationName(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::ram::Swap::print(), souffle::ram::LogSize::print(), souffle::ram::Clear::print(), souffle::ram::Scan::print(), souffle::ram::ParallelScan::print(), souffle::ram::Extend::print(), souffle::ram::IO::print(), souffle::ram::ParallelChoice::print(), souffle::ram::ParallelAggregate::print(), souffle::ram::RelationSize::print(), souffle::ram::IndexScan::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::EmptinessCheck::print(), souffle::ram::LogRelationTimer::print(), souffle::ram::ParallelIndexScan::print(), souffle::ram::Choice::print(), souffle::ram::Aggregate::print(), souffle::ram::ParallelIndexChoice::print(), souffle::ram::AbstractExistenceCheck::print(), souffle::ram::IndexAggregate::print(), souffle::ram::Project::print(), souffle::ram::IndexChoice::print(), and souffle::ram::analysis::IndexAnalysis::print().
{
         return name;
     }
getRepresentation()
RelationRepresentation souffle::ram::Relation::getRepresentation () const inline
Relation representation type.
Definition at line 71 of file Relation.h.
References representation.
Referenced by souffle::ram::analysis::MinIndexSelection::getAttributesToDischarge(), souffle::synthesiser::Relation::getSynthesiserRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return representation;
     }
isNullary()
bool souffle::ram::Relation::isNullary () const inline
Is nullary relation.
Definition at line 66 of file Relation.h.
References arity.
Referenced by souffle::synthesiser::Relation::getSynthesiserRelation().
{
         return arity == 0;
     }
isTemp()
bool souffle::ram::Relation::isTemp () const inline
Is temporary relation (for semi-naive evaluation)
Definition at line 76 of file Relation.h.
References name.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
         return name.at(0) == '@';
     }
operator<()
bool souffle::ram::Relation::operator< (const Relation & other) const inline
Compare two relations via their name.
Definition at line 91 of file Relation.h.
References name.
{
         return name < other.name;
     }
print()
void souffle::ram::Relation::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 100 of file Relation.h.
References arity, attributeNames, attributeTypes, auxiliaryArity, i, name, and representation.
{
         out << name;
         if (arity > 0) {
             out << "(" << attributeNames[0] << ":" << attributeTypes[0];
             for (unsigned i = 1; i < arity; i++) {
                 out << ",";
                 out << attributeNames[i] << ":" << attributeTypes[i];
                 if (i >= arity - auxiliaryArity) {
                     out << " auxiliary";
                 }
             }
             out << ")";
             out << " " << representation;
         } else {
             out << " nullary";
         }
     }
Field Documentation
arity
const size_t souffle::ram::Relation::arity protected
Arity, i.e., number of attributes.
Definition at line 134 of file Relation.h.
Referenced by clone(), equal(), getArity(), isNullary(), print(), and Relation().
attributeNames
const std::vector<std::string> souffle::ram::Relation::attributeNames protected
Name of attributes.
Definition at line 140 of file Relation.h.
Referenced by clone(), equal(), getAttributeNames(), and print().
attributeTypes
const std::vector<std::string> souffle::ram::Relation::attributeTypes protected
Type of attributes.
Definition at line 143 of file Relation.h.
Referenced by clone(), equal(), getAttributeTypes(), souffle::synthesiser::Relation::getRelation(), and print().
auxiliaryArity
const size_t souffle::ram::Relation::auxiliaryArity protected
Number of auxiliary attributes (e.g.
provenance attributes etc)
Definition at line 137 of file Relation.h.
Referenced by clone(), equal(), getAuxiliaryArity(), and print().
name
const std::string souffle::ram::Relation::name protected
Name of relation.
Definition at line 131 of file Relation.h.
Referenced by clone(), equal(), getName(), isTemp(), operator<(), and print().
representation
const RelationRepresentation souffle::ram::Relation::representation protected
Data-structure representation.
Definition at line 128 of file Relation.h.
Referenced by clone(), equal(), getRepresentation(), and print().
The documentation for this class was generated from the following file:
ram/Relation.h