souffle: souffle::ast::transform::ComponentInstantiationTransformer Class Reference
souffle::ast::transform::ComponentInstantiationTransformer Class Reference
#include <ComponentInstantiation.h>
Public Member Functions
ComponentInstantiationTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Definition at line 23 of file ComponentInstantiation.h.
Member Function Documentation
clone()
ComponentInstantiationTransformer* souffle::ast::transform::ComponentInstantiationTransformer::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 29 of file ComponentInstantiation.h.
References transform().
{
         return new ComponentInstantiationTransformer();
     }
getName()
std::string souffle::ast::transform::ComponentInstantiationTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 25 of file ComponentInstantiation.h.
{
         return "ComponentInstantiationTransformer";
     }
transform()
bool souffle::ast::transform::ComponentInstantiationTransformer::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 433 of file ComponentInstantiation.cpp.
References souffle::ast::Program::clauses, souffle::ast::Program::components, souffle::ast::Program::directives, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::instantiations, souffle::ast::Program::relations, and souffle::ast::Program::types.
Referenced by clone().
{
     // TODO: Do this without being a friend class of Program
     Program& program = translationUnit.getProgram();
     auto* componentLookup = translationUnit.getAnalysis<ComponentLookupAnalysis>();
     for (const auto& cur : program.instantiations) {
         std::vector<Own<Clause>> orphans;
         ComponentContent content = getInstantiatedContent(
                 program, *cur, nullptr, *componentLookup, orphans, translationUnit.getErrorReport());
         for (auto& type : content.types) {
             program.types.push_back(std::move(type));
         }
         for (auto& rel : content.relations) {
             program.relations.push_back(std::move(rel));
         }
         for (auto& clause : content.clauses) {
             program.clauses.push_back(std::move(clause));
         }
         for (auto& orphan : orphans) {
             program.clauses.push_back(std::move(orphan));
         }
         for (auto& directive : content.directives) {
             program.directives.push_back(std::move(directive));
         }
     }
     // delete components and instantiations
     program.instantiations.clear();
     program.components.clear();
     return true;
 }
The documentation for this class was generated from the following files:
ast/transform/ComponentInstantiation.h
ast/transform/ComponentInstantiation.cpp