souffle: souffle::ParserDriver Class Reference
souffle::ParserDriver Class Reference
#include <ParserDriver.h>
Public Member Functions
void addClause (Own< ast::Clause > c)
void addComponent (Own< ast::Component > c)
std::set< RelationTag > addDeprecatedTag (RelationTag tag, SrcLocation tagLoc, std::set< RelationTag > tags)
void addDirective (Own< ast::Directive > d)
void addFunctorDeclaration (Own< ast::FunctorDeclaration > f)
void addInstantiation (Own< ast::ComponentInit > ci)
void addIoFromDeprecatedTag (ast::Relation &r)
void addPragma (Own< ast::Pragma > p)
void addRelation (Own< ast::Relation > r)
std::set< RelationTag > addReprTag (RelationTag tag, SrcLocation tagLoc, std::set< RelationTag > tags)
std::set< RelationTag > addTag (RelationTag tag, SrcLocation tagLoc, std::set< RelationTag > tags)
std::set< RelationTag > addTag (RelationTag tag, std::vector< RelationTag > incompatible, SrcLocation tagLoc, std::set< RelationTag > tags)
void addType (Own< ast::Type > type)
void error (const SrcLocation &loc, const std::string &msg)
void error (const std::string &msg)
Own< ast::SubsetType > mkDeprecatedSubType (ast::QualifiedName name, ast::QualifiedName attr, SrcLocation loc)
Own< ast::TranslationUnit > parse (const std::string &filename, FILE *in, ErrorReport &errorReport, DebugReport &debugReport)
Own< ast::TranslationUnit > parse (const std::string &code, ErrorReport &errorReport, DebugReport &debugReport)
void warning (const SrcLocation &loc, const std::string &msg)
virtual ~ParserDriver ()=default
Static Public Member Functions
static Own< ast::TranslationUnit > parseTranslationUnit (const std::string &filename, FILE *in, ErrorReport &errorReport, DebugReport &debugReport)
static Own< ast::TranslationUnit > parseTranslationUnit (const std::string &code, ErrorReport &errorReport, DebugReport &debugReport)
Data Fields
bool trace_scanning = false
Own< ast::TranslationUnit > translationUnit
Detailed Description
Definition at line 51 of file ParserDriver.h.
Constructor & Destructor Documentation
~ParserDriver()
virtual souffle::ParserDriver::~ParserDriver () virtual default
Member Function Documentation
addClause()
void souffle::ParserDriver::addClause (Own< ast::Clause > c)
Definition at line 176 of file ParserDriver.cpp.
References souffle::ast::Program::addClause(), and translationUnit.
{
     ast::Program& program = translationUnit->getProgram();
     program.addClause(std::move(c));
 }
addComponent()
void souffle::ParserDriver::addComponent (Own< ast::Component > c)
Definition at line 180 of file ParserDriver.cpp.
References souffle::ast::Program::addComponent(), and translationUnit.
{
     ast::Program& program = translationUnit->getProgram();
     program.addComponent(std::move(c));
 }
addDeprecatedTag()
std::set< RelationTag > souffle::ParserDriver::addDeprecatedTag (RelationTag tag, SrcLocation tagLoc, std::set< RelationTag > tags)
Definition at line 204 of file ParserDriver.cpp.
References addTag(), souffle::Global::config(), tinyformat::format(), and warning().
{
     if (!Global::config().has("legacy")) {
         warning(tagLoc, tfm::format("Deprecated %s qualifier was used", tag));
     }
     return addTag(tag, std::move(tagLoc), std::move(tags));
 }
addDirective()
void souffle::ParserDriver::addDirective (Own< ast::Directive > d)
Definition at line 129 of file ParserDriver.cpp.
References souffle::ast::Program::addDirective(), err, souffle::Diagnostic::ERROR, souffle::ast::Program::getDirectives(), souffle::ast::limitsize, souffle::ast::printsize, souffle::toString(), and translationUnit.
Referenced by addIoFromDeprecatedTag().
{
     ast::Program& program = translationUnit->getProgram();
     if (directive->getType() == ast::DirectiveType::printsize) {
         for (const auto& cur : program.getDirectives()) {
             if (cur->getQualifiedName() == directive->getQualifiedName() &&
                     cur->getType() == ast::DirectiveType::printsize) {
                 Diagnostic err(Diagnostic::Type::ERROR,
                         DiagnosticMessage("Redefinition of printsize directives for relation " +
                                                   toString(directive->getQualifiedName()),
                                 directive->getSrcLoc()),
                         {DiagnosticMessage("Previous definition", cur->getSrcLoc())});
                 translationUnit->getErrorReport().addDiagnostic(err);
                 return;
             }
         }
     } else if (directive->getType() == ast::DirectiveType::limitsize) {
         for (const auto& cur : program.getDirectives()) {
             if (cur->getQualifiedName() == directive->getQualifiedName() &&
                     cur->getType() == ast::DirectiveType::limitsize) {
                 Diagnostic err(Diagnostic::Type::ERROR,
                         DiagnosticMessage("Redefinition of limitsize directives for relation " +
                                                   toString(directive->getQualifiedName()),
                                 directive->getSrcLoc()),
                         {DiagnosticMessage("Previous definition", cur->getSrcLoc())});
                 translationUnit->getErrorReport().addDiagnostic(err);
                 return;
             }
         }
     }
     program.addDirective(std::move(directive));
 }
addFunctorDeclaration()
void souffle::ParserDriver::addFunctorDeclaration (Own< ast::FunctorDeclaration > f)
Definition at line 101 of file ParserDriver.cpp.
References souffle::ast::Program::addFunctorDeclaration(), err, souffle::Diagnostic::ERROR, souffle::ast::Program::getFunctorDeclarations(), souffle::getIf(), souffle::ast::Node::getSrcLoc(), souffle::toString(), and translationUnit.
{
     const std::string& name = f->getName();
     ast::Program& program = translationUnit->getProgram();
     const ast::FunctorDeclaration* existingFunctorDecl = getIf(program.getFunctorDeclarations(),
             [&](const ast::FunctorDeclaration* current) { return current->getName() == name; });
     if (existingFunctorDecl != nullptr) {
         Diagnostic err(Diagnostic::Type::ERROR,
                 DiagnosticMessage("Redefinition of functor " + toString(name), f->getSrcLoc()),
                 {DiagnosticMessage("Previous definition", existingFunctorDecl->getSrcLoc())});
         translationUnit->getErrorReport().addDiagnostic(err);
     } else {
         program.addFunctorDeclaration(std::move(f));
     }
 }
addInstantiation()
void souffle::ParserDriver::addInstantiation (Own< ast::ComponentInit > ci)
Definition at line 184 of file ParserDriver.cpp.
References souffle::ast::Program::addInstantiation(), and translationUnit.
{
     ast::Program& program = translationUnit->getProgram();
     program.addInstantiation(std::move(ci));
 }
addIoFromDeprecatedTag()
void souffle::ParserDriver::addIoFromDeprecatedTag (ast::Relation & r)
Definition at line 189 of file ParserDriver.cpp.
References addDirective(), souffle::ast::Relation::getQualifiedName(), souffle::ast::Node::getSrcLoc(), souffle::ast::Relation::hasQualifier(), souffle::INPUT, souffle::ast::input, souffle::OUTPUT, souffle::ast::output, souffle::PRINTSIZE, and souffle::ast::printsize.
{
     if (rel.hasQualifier(RelationQualifier::INPUT)) {
         addDirective(mk<ast::Directive>(ast::DirectiveType::input, rel.getQualifiedName(), rel.getSrcLoc()));
     }
     if (rel.hasQualifier(RelationQualifier::OUTPUT)) {
         addDirective(mk<ast::Directive>(ast::DirectiveType::output, rel.getQualifiedName(), rel.getSrcLoc()));
     }
     if (rel.hasQualifier(RelationQualifier::PRINTSIZE)) {
         addDirective(
                 mk<ast::Directive>(ast::DirectiveType::printsize, rel.getQualifiedName(), rel.getSrcLoc()));
     }
 }
addPragma()
void souffle::ParserDriver::addPragma (Own< ast::Pragma > p)
Definition at line 96 of file ParserDriver.cpp.
References souffle::ast::Program::addPragma(), and translationUnit.
{
     ast::Program& program = translationUnit->getProgram();
     program.addPragma(std::move(p));
 }
addRelation()
void souffle::ParserDriver::addRelation (Own< ast::Relation > r)
Definition at line 116 of file ParserDriver.cpp.
References souffle::ast::Program::addRelation(), err, souffle::Diagnostic::ERROR, souffle::ast::getRelation(), souffle::toString(), and translationUnit.
{
     const auto& name = r->getQualifiedName();
     ast::Program& program = translationUnit->getProgram();
     if (ast::Relation* prev = getRelation(program, name)) {
         Diagnostic err(Diagnostic::Type::ERROR,
                 DiagnosticMessage("Redefinition of relation " + toString(name), r->getSrcLoc()),
                 {DiagnosticMessage("Previous definition", prev->getSrcLoc())});
         translationUnit->getErrorReport().addDiagnostic(err);
     } else {
         program.addRelation(std::move(r));
     }
 }
addReprTag()
std::set< RelationTag > souffle::ParserDriver::addReprTag (RelationTag tag, SrcLocation tagLoc, std::set< RelationTag > tags)
Definition at line 212 of file ParserDriver.cpp.
References addTag(), souffle::BRIE, souffle::BTREE, and souffle::EQREL.
{
     return addTag(tag, {RelationTag::BTREE, RelationTag::BRIE, RelationTag::EQREL}, std::move(tagLoc),
             std::move(tags));
 }
addTag() [1/2]
std::set< RelationTag > souffle::ParserDriver::addTag (RelationTag tag, SrcLocation tagLoc, std::set< RelationTag > tags)
Definition at line 218 of file ParserDriver.cpp.
Referenced by addDeprecatedTag(), and addReprTag().
{
     return addTag(tag, {tag}, std::move(tagLoc), std::move(tags));
 }
addTag() [2/2]
std::set< RelationTag > souffle::ParserDriver::addTag (RelationTag tag, std::vector< RelationTag > incompatible, SrcLocation tagLoc, std::set< RelationTag > tags)
Definition at line 222 of file ParserDriver.cpp.
References souffle::any_of(), souffle::contains(), error(), tinyformat::format(), and souffle::join().
{
     if (any_of(incompatible, [&](auto&& x) { return contains(tags, x); })) {
         error(tagLoc, tfm::format("%s qualifier already set", join(incompatible, "/")));
     }
     tags.insert(tag);
     return tags;
 }
addType()
void souffle::ParserDriver::addType (Own< ast::Type > type)
Definition at line 161 of file ParserDriver.cpp.
References souffle::ast::Program::addType(), err, souffle::Diagnostic::ERROR, souffle::getIf(), souffle::ast::Program::getTypes(), souffle::toString(), and translationUnit.
{
     ast::Program& program = translationUnit->getProgram();
     const auto& name = type->getQualifiedName();
     auto* existingType = getIf(program.getTypes(),
             [&](const ast::Type* current) { return current->getQualifiedName() == name; });
     if (existingType != nullptr) {
         Diagnostic err(Diagnostic::Type::ERROR,
                 DiagnosticMessage("Redefinition of type " + toString(name), type->getSrcLoc()),
                 {DiagnosticMessage("Previous definition", existingType->getSrcLoc())});
         translationUnit->getErrorReport().addDiagnostic(err);
     } else {
         program.addType(std::move(type));
     }
 }
error() [1/2]
void souffle::ParserDriver::error (const SrcLocation & loc, const std::string & msg)
Definition at line 243 of file ParserDriver.cpp.
References translationUnit.
Referenced by addTag().
{
     translationUnit->getErrorReport().addError(msg, loc);
 }
error() [2/2]
void souffle::ParserDriver::error (const std::string & msg)
Definition at line 246 of file ParserDriver.cpp.
References souffle::Diagnostic::ERROR, and translationUnit.
{
     translationUnit->getErrorReport().addDiagnostic(
             Diagnostic(Diagnostic::Type::ERROR, DiagnosticMessage(msg)));
 }
mkDeprecatedSubType()
Own< ast::SubsetType > souffle::ParserDriver::mkDeprecatedSubType (ast::QualifiedName name, ast::QualifiedName attr, SrcLocation loc)
Definition at line 232 of file ParserDriver.cpp.
References souffle::Global::config(), and warning().
{
     if (!Global::config().has("legacy")) {
         warning(loc, "Deprecated type declaration used");
     }
     return mk<ast::SubsetType>(std::move(name), std::move(baseTypeName), std::move(loc));
 }
parse() [1/2]
Own< ast::TranslationUnit > souffle::ParserDriver::parse (const std::string & filename, FILE * in, ErrorReport & errorReport, DebugReport & debugReport)
Definition at line 50 of file ParserDriver.cpp.
References translationUnit, souffle::scanner_data::yyfilename, yylex_destroy(), yylex_init_extra(), and yyset_in().
Referenced by parseTranslationUnit().
{
     translationUnit = mk<ast::TranslationUnit>(mk<ast::Program>(), errorReport, debugReport);
     yyscan_t scanner;
     scanner_data data;
     data.yyfilename = filename;
     yylex_init_extra(&data, &scanner);
     yyset_in(in, scanner);
     yy::parser parser(*this, scanner);
     parser.parse();
     yylex_destroy(scanner);
     return std::move(translationUnit);
 }
parse() [2/2]
Own< ast::TranslationUnit > souffle::ParserDriver::parse (const std::string & code, ErrorReport & errorReport, DebugReport & debugReport)
Definition at line 67 of file ParserDriver.cpp.
References translationUnit, yy_scan_string(), souffle::scanner_data::yyfilename, yylex_destroy(), and yylex_init_extra().
{
     translationUnit = mk<ast::TranslationUnit>(mk<ast::Program>(), errorReport, debugReport);
     scanner_data data;
     data.yyfilename = "<in-memory>";
     yyscan_t scanner;
     yylex_init_extra(&data, &scanner);
     yy_scan_string(code.c_str(), scanner);
     yy::parser parser(*this, scanner);
     parser.parse();
     yylex_destroy(scanner);
     return std::move(translationUnit);
 }
parseTranslationUnit() [1/2]
Own< ast::TranslationUnit > souffle::ParserDriver::parseTranslationUnit (const std::string & filename, FILE * in, ErrorReport & errorReport, DebugReport & debugReport) static
Definition at line 84 of file ParserDriver.cpp.
References parse().
Referenced by souffle::main(), souffle::ast::test::makeATU(), souffle::ast::transform::test::TEST(), and souffle::ast::test::TEST().
{
     ParserDriver parser;
     return parser.parse(filename, in, errorReport, debugReport);
 }
parseTranslationUnit() [2/2]
Own< ast::TranslationUnit > souffle::ParserDriver::parseTranslationUnit (const std::string & code, ErrorReport & errorReport, DebugReport & debugReport) static
Definition at line 90 of file ParserDriver.cpp.
References parse().
{
     ParserDriver parser;
     return parser.parse(code, errorReport, debugReport);
 }
warning()
void souffle::ParserDriver::warning (const SrcLocation & loc, const std::string & msg)
Definition at line 240 of file ParserDriver.cpp.
References translationUnit.
Referenced by addDeprecatedTag(), and mkDeprecatedSubType().
{
     translationUnit->getErrorReport().addWarning(msg, loc);
 }
Field Documentation
trace_scanning
bool souffle::ParserDriver::trace_scanning = false
Definition at line 76 of file ParserDriver.h.
translationUnit
Own<ast::TranslationUnit> souffle::ParserDriver::translationUnit
Definition at line 55 of file ParserDriver.h.
Referenced by addClause(), addComponent(), addDirective(), addFunctorDeclaration(), addInstantiation(), addPragma(), addRelation(), addType(), error(), parse(), and warning().
The documentation for this class was generated from the following files:
parser/ParserDriver.h
parser/ParserDriver.cpp