souffle: souffle::ast::Attribute Class Reference
souffle::ast::Attribute Class Reference
Attribute class.
#include <Attribute.h>
Public Member Functions
Attribute (std::string n, QualifiedName t, SrcLocation loc={})
Attribute * clone () const override
Create a clone (i.e.
const std::string & getName () const
Return attribute name.
const QualifiedName & getTypeName () const
Return type name.
void setTypeName (QualifiedName name)
Set type name.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::string name
Attribute name.
QualifiedName typeName
Type name.
Detailed Description
Attribute class.
Example: x: number An attribute consists of a name and its type name.
Definition at line 36 of file Attribute.h.
Constructor & Destructor Documentation
Attribute()
souffle::ast::Attribute::Attribute (std::string n, QualifiedName t, SrcLocation loc = {}) inline
Definition at line 38 of file Attribute.h.
References name, souffle::ast::Node::Node(), and typeName.
Referenced by clone().
                                                               {})
             : Node(std::move(loc)), name(std::move(n)), typeName(std::move(t)) {}
Member Function Documentation
clone()
Attribute* souffle::ast::Attribute::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ast::Node.
Definition at line 56 of file Attribute.h.
References Attribute(), souffle::ast::Node::getSrcLoc(), name, and typeName.
{
         return new Attribute(name, typeName, getSrcLoc());
     }
equal()
bool souffle::ast::Attribute::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Node.
Definition at line 65 of file Attribute.h.
References name, and typeName.
{
         const auto& other = static_cast<const Attribute&>(node);
         return name == other.name && typeName == other.typeName;
     }
getName()
const std::string& souffle::ast::Attribute::getName () const inline
Return attribute name.
Definition at line 42 of file Attribute.h.
References name.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration().
{
         return name;
     }
getTypeName()
const QualifiedName& souffle::ast::Attribute::getTypeName () const inline
Return type name.
Definition at line 47 of file Attribute.h.
References typeName.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration().
{
         return typeName;
     }
print()
void souffle::ast::Attribute::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::ast::Node.
Definition at line 61 of file Attribute.h.
References name, and typeName.
{
         os << name << ":" << typeName;
     }
setTypeName()
void souffle::ast::Attribute::setTypeName (QualifiedName name) inline
Set type name.
Definition at line 52 of file Attribute.h.
References typeName.
{
         typeName = std::move(name);
     }
Field Documentation
name
std::string souffle::ast::Attribute::name private
Attribute name.
Definition at line 72 of file Attribute.h.
Referenced by Attribute(), clone(), equal(), getName(), and print().
typeName
QualifiedName souffle::ast::Attribute::typeName private
Type name.
Definition at line 75 of file Attribute.h.
Referenced by Attribute(), clone(), equal(), getTypeName(), print(), and setTypeName().
The documentation for this class was generated from the following file:
ast/Attribute.h