souffle: souffle::ast::transform::Transformer Class Reference
souffle::ast::transform::Transformer Class Reference abstract
#include <Transformer.h>
Public Member Functions
bool apply (TranslationUnit &translationUnit)
virtual Transformer * clone () const =0
virtual std::string getName () const =0
virtual ~Transformer ()=default
Private Member Functions
virtual bool transform (TranslationUnit &translationUnit)=0
Detailed Description
Definition at line 24 of file Transformer.h.
Constructor & Destructor Documentation
~Transformer()
virtual souffle::ast::transform::Transformer::~Transformer () virtual default
Member Function Documentation
apply()
bool souffle::ast::transform::Transformer::apply (TranslationUnit & translationUnit)
Definition at line 23 of file Transformer.cpp.
References souffle::ErrorReport::exitIfErrors(), souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::TranslationUnit::invalidateAnalyses(), and transform().
Referenced by souffle::ast::transform::MetaTransformer::applySubtransformer().
{
     // invoke the transformation
     bool changed = transform(translationUnit);
     if (changed) {
         translationUnit.invalidateAnalyses();
     }
     /* Abort evaluation of the program if errors were encountered */
     translationUnit.getErrorReport().exitIfErrors();
     return changed;
 }
clone()
virtual Transformer* souffle::ast::transform::Transformer::clone () const pure virtual
Implemented in souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer, souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer, souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer, souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::DebugReporter, souffle::ast::transform::MagicSetTransformer, souffle::ast::transform::ResolveAliasesTransformer, souffle::ast::transform::IOAttributesTransformer, souffle::ast::transform::FoldAnonymousRecords, souffle::ast::transform::NullTransformer, souffle::ast::transform::MetaTransformer, souffle::ast::transform::MaterializeAggregationQueriesTransformer, souffle::ast::transform::RemoveRelationCopiesTransformer, souffle::ast::transform::PartitionBodyLiteralsTransformer, souffle::ast::transform::IODefaultsTransformer, souffle::ast::transform::RemoveEmptyRelationsTransformer, souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer, souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer, souffle::ast::transform::ComponentChecker, souffle::ast::transform::MinimiseProgramTransformer, souffle::ast::transform::ReorderLiteralsTransformer, souffle::ast::transform::MaterializeSingletonAggregationTransformer, souffle::ast::transform::NameUnnamedVariablesTransformer, souffle::ast::transform::ADTtoRecordsTransformer, souffle::ast::transform::PolymorphicObjectsTransformer, souffle::ast::transform::RemoveTypecastsTransformer, souffle::ast::transform::NormaliseConstraintsTransformer, souffle::ast::transform::ReduceExistentialsTransformer, souffle::ast::transform::UserDefinedFunctorsTransformer, souffle::ast::transform::RemoveRedundantSumsTransformer, souffle::ast::transform::GroundedTermsChecker, souffle::ast::transform::InlineRelationsTransformer, souffle::ast::transform::ProvenanceTransformer, souffle::ast::transform::ReplaceSingletonVariablesTransformer, souffle::ast::transform::RemoveBooleanConstraintsTransformer, souffle::ast::transform::SemanticChecker, souffle::ast::transform::RemoveRedundantRelationsTransformer, souffle::ast::transform::UniqueAggregationVariablesTransformer, souffle::ast::transform::ExecutionPlanChecker, souffle::ast::transform::PragmaChecker, and souffle::ast::transform::ComponentInstantiationTransformer.
getName()
virtual std::string souffle::ast::transform::Transformer::getName () const pure virtual
Implemented in souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer, souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer, souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer, souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::DebugReporter, souffle::ast::transform::MagicSetTransformer, souffle::ast::transform::IOAttributesTransformer, souffle::ast::transform::FoldAnonymousRecords, souffle::ast::transform::NullTransformer, souffle::ast::transform::PartitionBodyLiteralsTransformer, souffle::ast::transform::IODefaultsTransformer, souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer, souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer, souffle::ast::transform::ComponentChecker, souffle::ast::transform::ReorderLiteralsTransformer, souffle::ast::transform::MaterializeSingletonAggregationTransformer, souffle::ast::transform::NameUnnamedVariablesTransformer, souffle::ast::transform::ADTtoRecordsTransformer, souffle::ast::transform::MaterializeAggregationQueriesTransformer, souffle::ast::transform::PolymorphicObjectsTransformer, souffle::ast::transform::RemoveRelationCopiesTransformer, souffle::ast::transform::RemoveTypecastsTransformer, souffle::ast::transform::ResolveAliasesTransformer, souffle::ast::transform::MinimiseProgramTransformer, souffle::ast::transform::NormaliseConstraintsTransformer, souffle::ast::transform::ReduceExistentialsTransformer, souffle::ast::transform::UserDefinedFunctorsTransformer, souffle::ast::transform::RemoveRedundantSumsTransformer, souffle::ast::transform::InlineRelationsTransformer, souffle::ast::transform::ProvenanceTransformer, souffle::ast::transform::ReplaceSingletonVariablesTransformer, souffle::ast::transform::RemoveBooleanConstraintsTransformer, souffle::ast::transform::RemoveEmptyRelationsTransformer, souffle::ast::transform::SemanticChecker, souffle::ast::transform::RemoveRedundantRelationsTransformer, souffle::ast::transform::UniqueAggregationVariablesTransformer, souffle::ast::transform::ExecutionPlanChecker, souffle::ast::transform::GroundedTermsChecker, souffle::ast::transform::PragmaChecker, and souffle::ast::transform::ComponentInstantiationTransformer.
Referenced by souffle::ast::transform::MetaTransformer::applySubtransformer().
transform()
virtual bool souffle::ast::transform::Transformer::transform (TranslationUnit & translationUnit) private pure virtual
Implemented in souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer, souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer, souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer, souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer, souffle::ast::transform::PipelineTransformer, souffle::ast::transform::ConditionalTransformer, souffle::ast::transform::WhileTransformer, souffle::ast::transform::FixpointTransformer, souffle::ast::transform::DebugReporter, souffle::ast::transform::MagicSetTransformer, souffle::ast::transform::ResolveAliasesTransformer, souffle::ast::transform::IOAttributesTransformer, souffle::ast::transform::FoldAnonymousRecords, souffle::ast::transform::ReorderLiteralsTransformer, souffle::ast::transform::MaterializeAggregationQueriesTransformer, souffle::ast::transform::RemoveRelationCopiesTransformer, souffle::ast::transform::PartitionBodyLiteralsTransformer, souffle::ast::transform::IODefaultsTransformer, souffle::ast::transform::RemoveEmptyRelationsTransformer, souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer, souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer, souffle::ast::transform::ComponentChecker, souffle::ast::transform::MinimiseProgramTransformer, souffle::ast::transform::MaterializeSingletonAggregationTransformer, souffle::ast::transform::NameUnnamedVariablesTransformer, souffle::ast::transform::ADTtoRecordsTransformer, souffle::ast::transform::PolymorphicObjectsTransformer, souffle::ast::transform::NormaliseConstraintsTransformer, souffle::ast::transform::ReduceExistentialsTransformer, souffle::ast::transform::UserDefinedFunctorsTransformer, souffle::ast::transform::RemoveRedundantSumsTransformer, souffle::ast::transform::GroundedTermsChecker, souffle::ast::transform::InlineRelationsTransformer, souffle::ast::transform::ProvenanceTransformer, souffle::ast::transform::ReplaceSingletonVariablesTransformer, souffle::ast::transform::RemoveBooleanConstraintsTransformer, souffle::ast::transform::SemanticChecker, souffle::ast::transform::RemoveRedundantRelationsTransformer, souffle::ast::transform::UniqueAggregationVariablesTransformer, souffle::ast::transform::ExecutionPlanChecker, souffle::ast::transform::PragmaChecker, souffle::ast::transform::ComponentInstantiationTransformer, souffle::ast::transform::NullTransformer, and souffle::ast::transform::RemoveTypecastsTransformer.
Referenced by apply().
The documentation for this class was generated from the following files:
ast/transform/Transformer.h
ast/transform/Transformer.cpp