souffle: souffle::ast::BindingStore Class Reference
souffle::ast::BindingStore Class Reference
#include <BindingStore.h>
Public Member Functions
BindingStore (const Clause *clause)
void bindVariableStrongly (std::string varName)
Mark the given variable as strongly bound.
void bindVariableWeakly (std::string varName)
Mark the given variable as weakly bound.
bool isBound (std::string varName) const
Check if a variable is bound.
bool isBound (const Argument *arg) const
Check if an argument is bound.
size_t numBoundArguments (const Atom *atom) const
Counts the number of bound arguments in the given atom.
Private Types
using ConjBindingSet = std::set< std::string >
using DisjBindingSet = std::set< ConjBindingSet >
Private Member Functions
void addBindingDependency (std::string variable, ConjBindingSet dependency)
Add a new conjunction of variables as a potential binder for a given variable.
void generateBindingDependencies (const Clause *clause)
Generate all binding dependencies implied by the constraints within a given clause.
void processEqualityBindings (const Argument *lhs, const Argument *rhs)
Add binding dependencies formed on lhs by a <lhs> = <rhs> equality constraint.
bool reduceDependencies ()
Reduce the full set of dependencies for all tracked variables, binding whatever needs to be bound.
ConjBindingSet reduceDependency (const ConjBindingSet &origDependency)
Reduce a conjunctive set of dependencies based on the current bound variable set.
DisjBindingSet reduceDependency (const DisjBindingSet &origDependency)
Reduce a disjunctive set of variable dependencies based on the current bound variable set.
Private Attributes
std::set< std::string > stronglyBoundVariables {}
std::map< std::string, DisjBindingSet > variableDependencies {}
std::set< std::string > weaklyBoundVariables {}
Detailed Description
Definition at line 31 of file BindingStore.h.
Member Typedef Documentation
ConjBindingSet
using souffle::ast::BindingStore::ConjBindingSet = std::set<std::string> private
Definition at line 69 of file BindingStore.h.
DisjBindingSet
using souffle::ast::BindingStore::DisjBindingSet = std::set<ConjBindingSet> private
Definition at line 70 of file BindingStore.h.
Constructor & Destructor Documentation
BindingStore()
souffle::ast::BindingStore::BindingStore (const Clause * clause)
Definition at line 35 of file BindingStore.cpp.
References generateBindingDependencies(), and reduceDependencies().
{
     generateBindingDependencies(clause);
     reduceDependencies();
 }
Member Function Documentation
addBindingDependency()
void souffle::ast::BindingStore::addBindingDependency (std::string variable, ConjBindingSet dependency) inline private
Add a new conjunction of variables as a potential binder for a given variable.
The variable is considered bound if all variables in the conjunction are bound.
Definition at line 80 of file BindingStore.h.
References souffle::contains(), generateBindingDependencies(), lhs, processEqualityBindings(), reduceDependencies(), reduceDependency(), rhs, and variableDependencies.
Referenced by processEqualityBindings().
{
         if (!contains(variableDependencies, variable)) {
             variableDependencies[variable] = DisjBindingSet();
         }
         variableDependencies[variable].insert(dependency);
     }
bindVariableStrongly()
void souffle::ast::BindingStore::bindVariableStrongly (std::string varName) inline
Mark the given variable as strongly bound.
Strongly bound variables can be used to bind functor arguments. This is the usual case, e.g. body atom appearances
Definition at line 40 of file BindingStore.h.
References reduceDependencies(), and stronglyBoundVariables.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), and souffle::ast::SipsMetric::getReordering().
{
         stronglyBoundVariables.insert(varName);
         // Some functor dependencies may be reduced
         reduceDependencies();
     }
bindVariableWeakly()
void souffle::ast::BindingStore::bindVariableWeakly (std::string varName) inline
Mark the given variable as weakly bound.
Weakly bound variables cannot be used to bind functor arguments. E.g. bound head arguments in MST adorned relations
Definition at line 52 of file BindingStore.h.
References weaklyBoundVariables.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause().
{
         weaklyBoundVariables.insert(varName);
     }
generateBindingDependencies()
void souffle::ast::BindingStore::generateBindingDependencies (const Clause * clause) private
Generate all binding dependencies implied by the constraints within a given clause.
Definition at line 40 of file BindingStore.cpp.
References souffle::EQ, souffle::ast::BinaryConstraint::getOperator(), processEqualityBindings(), and souffle::ast::visitDepthFirst().
Referenced by addBindingDependency(), and BindingStore().
{
     // Grab all relevant constraints (i.e. eq. constrs not involving aggregators)
     std::set<const BinaryConstraint*> relevantEqConstraints;
     visitDepthFirst(*clause, [&](const BinaryConstraint& bc) {
         bool containsAggregators = false;
         visitDepthFirst(bc, [&](const Aggregator& /* aggr */) { containsAggregators = true; });
         if (!containsAggregators && bc.getOperator() == BinaryConstraintOp::EQ) {
             relevantEqConstraints.insert(&bc);
         }
     });
     // Add variable binding dependencies implied by the constraint
     for (const auto* eqConstraint : relevantEqConstraints) {
         processEqualityBindings(eqConstraint->getLHS(), eqConstraint->getRHS());
         processEqualityBindings(eqConstraint->getRHS(), eqConstraint->getLHS());
     }
 }
isBound() [1/2]
bool souffle::ast::BindingStore::isBound (std::string varName) const inline
Check if a variable is bound.
Definition at line 57 of file BindingStore.h.
References souffle::contains(), numBoundArguments(), stronglyBoundVariables, and weaklyBoundVariables.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::LeastFreeVarsSips::evaluateCosts(), isBound(), and numBoundArguments().
{
         return contains(stronglyBoundVariables, varName) || contains(weaklyBoundVariables, varName);
     }
isBound() [2/2]
bool souffle::ast::BindingStore::isBound (const Argument * arg) const
Check if an argument is bound.
Definition at line 142 of file BindingStore.cpp.
References isBound().
{
     if (const auto* var = dynamic_cast<const Variable*>(arg)) {
         return isBound(var->getName());
     } else if (const auto* term = dynamic_cast<const Term*>(arg)) {
         for (const auto* subArg : term->getArguments()) {
             if (!isBound(subArg)) {
                 return false;
             }
         }
         return true;
     } else if (isA<Constant>(arg)) {
         return true;
     } else {
         return false;
     }
 }
numBoundArguments()
size_t souffle::ast::BindingStore::numBoundArguments (const Atom * atom) const
Counts the number of bound arguments in the given atom.
Definition at line 159 of file BindingStore.cpp.
References souffle::test::count(), souffle::ast::Atom::getArguments(), and isBound().
Referenced by souffle::ast::AllBoundSips::evaluateCosts(), souffle::ast::NaiveSips::evaluateCosts(), souffle::ast::MaxBoundSips::evaluateCosts(), souffle::ast::MaxRatioSips::evaluateCosts(), souffle::ast::LeastFreeSips::evaluateCosts(), souffle::ast::ProfileUseSips::evaluateCosts(), and isBound().
{
     size_t count = 0;
     for (const auto* arg : atom->getArguments()) {
         if (isBound(arg)) {
             count++;
         }
     }
     return count;
 }
processEqualityBindings()
void souffle::ast::BindingStore::processEqualityBindings (const Argument * lhs, const Argument * rhs) private
Add binding dependencies formed on lhs by a <lhs> = <rhs> equality constraint.
Definition at line 58 of file BindingStore.cpp.
References addBindingDependency(), lhs, and souffle::ast::visitDepthFirst().
Referenced by addBindingDependency(), and generateBindingDependencies().
{
     // Only care about equalities affecting the bound status of variables
     const auto* var = dynamic_cast<const Variable*>(lhs);
     if (var == nullptr) return;
     // If all variables on the rhs are bound, then lhs is also bound
     BindingStore::ConjBindingSet depSet;
     visitDepthFirst(*rhs, [&](const Variable& subVar) { depSet.insert(subVar.getName()); });
     addBindingDependency(var->getName(), depSet);
     // If the lhs is bound, then all args in the rec on the rhs are also bound
     if (const auto* rec = dynamic_cast<const RecordInit*>(rhs)) {
         for (const auto* arg : rec->getArguments()) {
             const auto* subVar = dynamic_cast<const Variable*>(arg);
             assert(subVar != nullptr && "expected args to be variables");
             addBindingDependency(subVar->getName(), BindingStore::ConjBindingSet({var->getName()}));
         }
     }
 }
reduceDependencies()
bool souffle::ast::BindingStore::reduceDependencies () private
Reduce the full set of dependencies for all tracked variables, binding whatever needs to be bound.
Definition at line 102 of file BindingStore.cpp.
References souffle::contains(), reduceDependency(), stronglyBoundVariables, and variableDependencies.
Referenced by addBindingDependency(), BindingStore(), and bindVariableStrongly().
{
     bool changed = false;
     std::map<std::string, BindingStore::DisjBindingSet> newVariableDependencies;
     std::set<std::string> variablesToBind;
     // Reduce each variable's set of dependencies one by one
     for (const auto& [headVar, dependencies] : variableDependencies) {
         // No need to track the dependencies of already-bound variables
         if (contains(stronglyBoundVariables, headVar)) {
             changed = true;
             continue;
         }
         // Reduce the dependency set based on bound variables
         auto newDependencies = reduceDependency(dependencies);
         if (newDependencies.empty() || newDependencies.size() < dependencies.size()) {
             // At least one dependency has been satisfied, so variable is now bound
             changed = true;
             variablesToBind.insert(headVar);
             continue;
         }
         newVariableDependencies[headVar] = newDependencies;
         changed |= (newDependencies != dependencies);
     }
     // Bind variables that need to be bound
     for (auto var : variablesToBind) {
         stronglyBoundVariables.insert(var);
     }
     // Repeat it recursively if any changes happened, until we reach a fixpoint
     if (changed) {
         variableDependencies = newVariableDependencies;
         reduceDependencies();
         return true;
     }
     assert(variableDependencies == newVariableDependencies && "unexpected change");
     return false;
 }
reduceDependency() [1/2]
BindingStore::ConjBindingSet souffle::ast::BindingStore::reduceDependency (const ConjBindingSet & origDependency) private
Reduce a conjunctive set of dependencies based on the current bound variable set.
Definition at line 78 of file BindingStore.cpp.
References souffle::contains(), and stronglyBoundVariables.
Referenced by addBindingDependency(), reduceDependencies(), and reduceDependency().
{
     BindingStore::ConjBindingSet newDependency;
     for (const auto& var : origDependency) {
         // Only keep unbound variables in the dependency
         if (!contains(stronglyBoundVariables, var)) {
             newDependency.insert(var);
         }
     }
     return newDependency;
 }
reduceDependency() [2/2]
BindingStore::DisjBindingSet souffle::ast::BindingStore::reduceDependency (const DisjBindingSet & origDependency) private
Reduce a disjunctive set of variable dependencies based on the current bound variable set.
Definition at line 90 of file BindingStore.cpp.
References reduceDependency().
{
     BindingStore::DisjBindingSet newDependencies;
     for (const auto& dep : origDependency) {
         auto newDep = reduceDependency(dep);
         if (!newDep.empty()) {
             newDependencies.insert(newDep);
         }
     }
     return newDependencies;
 }
Field Documentation
stronglyBoundVariables
std::set<std::string> souffle::ast::BindingStore::stronglyBoundVariables {} private
Definition at line 72 of file BindingStore.h.
Referenced by bindVariableStrongly(), isBound(), reduceDependencies(), and reduceDependency().
variableDependencies
std::map<std::string, DisjBindingSet> souffle::ast::BindingStore::variableDependencies {} private
Definition at line 74 of file BindingStore.h.
Referenced by addBindingDependency(), and reduceDependencies().
weaklyBoundVariables
std::set<std::string> souffle::ast::BindingStore::weaklyBoundVariables {} private
Definition at line 73 of file BindingStore.h.
Referenced by bindVariableWeakly(), and isBound().
The documentation for this class was generated from the following files:
ast/utility/BindingStore.h
ast/utility/BindingStore.cpp