souffle: souffle::ram::UnsignedConstant Class Reference
souffle::ram::UnsignedConstant Class Reference
Represents a unsigned constant.
#include <UnsignedConstant.h>
Public Member Functions
UnsignedConstant * clone () const override
Create clone.
RamUnsigned getValue () const
Get value of the constant.
UnsignedConstant (RamUnsigned val)
Public Member Functions inherited from souffle::ram::Constant
RamDomain getConstant () const
Get constant.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::Constant
Constant (RamDomain constant)
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::ram::Constant
const RamDomain constant
Constant value.
Detailed Description
Represents a unsigned constant.
For example:
unsigned(5)
Definition at line 34 of file UnsignedConstant.h.
Constructor & Destructor Documentation
UnsignedConstant()
souffle::ram::UnsignedConstant::UnsignedConstant (RamUnsigned val) inline explicit
Definition at line 36 of file UnsignedConstant.h.
Referenced by clone().
 : Constant(ramBitCast(val)) {}
Member Function Documentation
clone()
UnsignedConstant* souffle::ram::UnsignedConstant::clone () const inline override virtual
Create clone.
Implements souffle::ram::Expression.
Definition at line 44 of file UnsignedConstant.h.
References getValue(), and UnsignedConstant().
{
         return new UnsignedConstant(getValue());
     }
getValue()
RamUnsigned souffle::ram::UnsignedConstant::getValue () const inline
Get value of the constant.
Definition at line 39 of file UnsignedConstant.h.
References souffle::ram::Constant::constant.
Referenced by clone(), souffle::synthesiser::Synthesiser::emitCode(), and print().
{
         return ramBitCast<RamUnsigned>(constant);
     }
print()
void souffle::ram::UnsignedConstant::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 49 of file UnsignedConstant.h.
References getValue().
{
         os << "unsigned(" << getValue() << ")";
     }
The documentation for this class was generated from the following file:
ram/UnsignedConstant.h