souffle: souffle::ast::analysis::TypeConstraintsAnalysis Class Reference
souffle::ast::analysis::TypeConstraintsAnalysis Class Reference
Constraint analysis framework for types.
Public Member Functions
TypeConstraintsAnalysis (const TranslationUnit &tu)
Public Member Functions inherited from souffle::ast::analysis::ConstraintAnalysis< TypeVar >
solution_type analyse (const Clause &clause, std::ostream *debugOutput=nullptr)
Runs this constraint analysis on the given clause.
Public Member Functions inherited from souffle::ast::Visitor< void >
void operator() (const Node &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const Node &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of Nodes.
virtual ~Visitor ()=default
A virtual destructor.
Private Member Functions
void collectConstraints (const Clause &clause) override
void iterateOverAtom (const Atom &atom, std::function< void(const Argument &, const Type &)> map)
Utility function.
void visitAggregator (const Aggregator &agg) override
void visitAtom (const Atom &atom) override
void visitBinaryConstraint (const BinaryConstraint &rel) override
void visitBranchInit (const BranchInit &adt) override
void visitCounter (const Counter &counter) override
void visitFunctor (const Functor &fun) override
void visitNegation (const Negation &cur) override
void visitNumericConstant (const NumericConstant &constant) override
void visitRecordInit (const RecordInit &record) override
void visitSink (const Atom &atom)
void visitStringConstant (const StringConstant &cnst) override
void visitTypeCast (const ast::TypeCast &typeCast) override
Private Attributes
const Program & program = tu.getProgram()
std::set< const Atom * > sinks
const SumTypeBranchesAnalysis & sumTypesBranches = *tu.getAnalysis<SumTypeBranchesAnalysis>()
const TranslationUnit & tu
const TypeEnvironment & typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment()
Additional Inherited Members
Public Types inherited from souffle::ast::analysis::ConstraintAnalysis< TypeVar >
using constraint_type = std::shared_ptr< Constraint< TypeVar > >
using solution_type = std::map< const Argument *, value_type >
using value_type = typename TypeVar ::property_space::value_type
Protected Member Functions inherited from souffle::ast::analysis::ConstraintAnalysis< TypeVar >
void addConstraint (const constraint_type &constraint)
Adds another constraint to the internally maintained list of constraints.
TypeVar getVar (const Argument &arg)
A utility function mapping an Argument to its associated analysis variable.
TypeVar getVar (const Argument *arg)
A utility function mapping an Argument to its associated analysis variable.
Protected Member Functions inherited from souffle::ast::Visitor< void >
LINK (SubsetType, Type)
LINK (RecordType, Type)
LINK (AlgebraicDataType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (ComponentType, Node)
LINK (ComponentInit, Node)
LINK (Component, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const Node &, Params...)
The base case for all visitors – if no more specific overload was defined.
Protected Attributes inherited from souffle::ast::analysis::ConstraintAnalysis< TypeVar >
Assignment< TypeVar > assignment
Problem< TypeVar > constraints
The list of constraints making underlying this analysis.
std::map< std::string, TypeVar > variables
A map mapping variables to unique instances to facilitate the unification of variables.
Detailed Description
Constraint analysis framework for types.
The analysis operates on the concept of sinks and sources. If the atom is negated or is a head then it's a sink, and we can only extract the kind constraint from it Otherwise it is a source, and the type of the element must be a subtype of source attribute.
Definition at line 560 of file Type.cpp.
Constructor & Destructor Documentation
TypeConstraintsAnalysis()
souffle::ast::analysis::TypeConstraintsAnalysis::TypeConstraintsAnalysis (const TranslationUnit & tu) inline
Definition at line 562 of file Type.cpp.
 : tu(tu) {}
Member Function Documentation
collectConstraints()
void souffle::ast::analysis::TypeConstraintsAnalysis::collectConstraints (const Clause & clause) inline override private virtual
Reimplemented from souffle::ast::analysis::ConstraintAnalysis< TypeVar >.
Definition at line 573 of file Type.cpp.
References souffle::ast::Clause::getHead(), and souffle::ast::visitDepthFirstPreOrder().
{
         sinks.insert(clause.getHead());
         visitDepthFirstPreOrder(clause, *this);
     }
iterateOverAtom()
void souffle::ast::analysis::TypeConstraintsAnalysis::iterateOverAtom (const Atom & atom, std::function< void(const Argument &, const Type &)> map) inline private
Utility function.
Iterate over atoms valid pairs of (argument, type-attribute) and apply procedure map for its side-effects.
Definition at line 780 of file Type.cpp.
References souffle::ast::Atom::getArguments(), souffle::ast::getAtomRelation(), souffle::ast::analysis::TypeEnvironment::getType(), i, souffle::ast::analysis::TypeEnvironment::isType(), and souffle::map().
{
         // get relation
         auto rel = getAtomRelation(&atom, &program);
         if (rel == nullptr) {
             return;  // error in input program
         }
         auto atts = rel->getAttributes();
         auto args = atom.getArguments();
         if (atts.size() != args.size()) {
             return;  // error in input program
         }
         for (size_t i = 0; i < atts.size(); i++) {
             const auto& typeName = atts[i]->getTypeName();
             if (typeEnv.isType(typeName)) {
                 map(*args[i], typeEnv.getType(typeName));
             }
         }
     }
visitAggregator()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitAggregator (const Aggregator & agg) inline override private
Definition at line 759 of file Type.cpp.
References souffle::COUNT, souffle::Float, souffle::ast::analysis::TypeEnvironment::getConstantNumericTypes(), souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::ast::Aggregator::getOperator(), souffle::ast::Aggregator::getTargetExpression(), souffle::ast::analysis::isSubtypeOf(), souffle::MEAN, and souffle::Signed.
{
         if (agg.getOperator() == AggregateOp::COUNT) {
             addConstraint(isSubtypeOf(getVar(agg), typeEnv.getConstantType(TypeAttribute::Signed)));
         } else if (agg.getOperator() == AggregateOp::MEAN) {
             addConstraint(isSubtypeOf(getVar(agg), typeEnv.getConstantType(TypeAttribute::Float)));
         } else {
             addConstraint(hasSuperTypeInSet(getVar(agg), typeEnv.getConstantNumericTypes()));
         }
         // If there is a target expression - it should be of the same type as the aggregator.
         if (auto expr = agg.getTargetExpression()) {
             addConstraint(isSubtypeOf(getVar(expr), getVar(agg)));
             addConstraint(isSubtypeOf(getVar(agg), getVar(expr)));
         }
     }
visitAtom()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitAtom (const Atom & atom) inline override private
Definition at line 592 of file Type.cpp.
References souffle::contains(), and souffle::ast::analysis::isSubtypeOf().
{
         if (contains(sinks, &atom)) {
             visitSink(atom);
             return;
         }
         iterateOverAtom(atom, [&](const Argument& argument, const Type& attributeType) {
             addConstraint(isSubtypeOf(getVar(argument), attributeType));
         });
     }
visitBinaryConstraint()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitBinaryConstraint (const BinaryConstraint & rel) inline override private
Definition at line 652 of file Type.cpp.
References souffle::ast::BinaryConstraint::getLHS(), souffle::ast::BinaryConstraint::getRHS(), souffle::ast::analysis::isSubtypeOf(), lhs, and rhs.
{
         auto lhs = getVar(rel.getLHS());
         auto rhs = getVar(rel.getRHS());
         addConstraint(isSubtypeOf(lhs, rhs));
         addConstraint(isSubtypeOf(rhs, lhs));
     }
visitBranchInit()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitBranchInit (const BranchInit & adt) inline override private
Definition at line 726 of file Type.cpp.
References souffle::ast::Term::getArguments(), souffle::ast::BranchInit::getConstructor(), souffle::ast::analysis::SumTypeBranchesAnalysis::getType(), i, and souffle::ast::analysis::isSubtypeOf().
{
         auto* correspondingType = sumTypesBranches.getType(adt.getConstructor());
         if (correspondingType == nullptr) {
             return;  // malformed program.
         }
         // Sanity check
         assert(isA<AlgebraicDataType>(correspondingType));
         // Constraint on the whole branch. $Branch(...) <: ADTtype
         addConstraint(isSubtypeOf(getVar(adt), *correspondingType));
         // Constraints on arguments
         try {
             auto branchTypes = as<AlgebraicDataType>(correspondingType)->getBranchTypes(adt.getConstructor());
             auto branchArgs = adt.getArguments();
             if (branchTypes.size() != branchArgs.size()) {
                 // handled by semantic checker later.
                 throw std::invalid_argument("Invalid arity");
             }
             // Add constraints for each of the branch arguments.
             for (size_t i = 0; i < branchArgs.size(); ++i) {
                 auto argVar = getVar(branchArgs[i]);
                 addConstraint(isSubtypeOf(argVar, *branchTypes[i]));
             }
         } catch (...) {
             return;  // Invalid program.
         }
     }
visitCounter()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitCounter (const Counter & counter) inline override private
Definition at line 698 of file Type.cpp.
References souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::ast::analysis::isSubtypeOf(), and souffle::Signed.
{
         addConstraint(isSubtypeOf(getVar(counter), typeEnv.getConstantType(TypeAttribute::Signed)));
     }
visitFunctor()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor (const Functor & fun) inline override private
Definition at line 659 of file Type.cpp.
References souffle::functorBuiltIn(), souffle::ast::Functor::getArgType(), souffle::ast::Term::getArguments(), souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::ast::Functor::getReturnType(), i, souffle::isInfixFunctorOp(), souffle::ast::analysis::isSubtypeOf(), souffle::map(), and souffle::ORD.
{
         auto functorVar = getVar(fun);
         auto intrFun = as<IntrinsicFunctor>(fun);
         if (intrFun) {
             auto argVars = map(intrFun->getArguments(), [&](auto&& x) { return getVar(x); });
             // The type of the user-defined function might not be set at this stage.
             // If so then add overloads as alternatives
             if (!intrFun->getFunctionInfo())
                 addConstraint(satisfiesOverload(typeEnv, functorBuiltIn(intrFun->getFunction()), functorVar,
                         argVars, isInfixFunctorOp(intrFun->getFunction())));
             // In polymorphic case
             // We only require arguments to share a base type with a return type.
             // (instead of, for example, requiring them to be of the same type)
             // This approach is related to old type semantics
             // See #1296 and tests/semantic/type_system4
             if (isInfixFunctorOp(intrFun->getFunction())) {
                 for (auto&& var : argVars)
                     addConstraint(subtypesOfTheSameBaseType(var, functorVar));
                 return;
             }
             if (!intrFun->getFunctionInfo()) return;
         }
         // add a constraint for the return type of the functor
         addConstraint(isSubtypeOf(functorVar, typeEnv.getConstantType(fun.getReturnType())));
         // Special case. Ord returns the ram representation of any object.
         if (intrFun && intrFun->getFunctionInfo()->op == FunctorOp::ORD) return;
         auto arguments = fun.getArguments();
         for (size_t i = 0; i < arguments.size(); ++i) {
             addConstraint(isSubtypeOf(getVar(arguments[i]), typeEnv.getConstantType(fun.getArgType(i))));
         }
     }
visitNegation()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitNegation (const Negation & cur) inline override private
Definition at line 603 of file Type.cpp.
References souffle::ast::Negation::getAtom().
{
         sinks.insert(cur.getAtom());
     }
visitNumericConstant()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant (const NumericConstant & constant) inline override private
Definition at line 611 of file Type.cpp.
References souffle::canBeParsedAsRamFloat(), souffle::canBeParsedAsRamSigned(), souffle::canBeParsedAsRamUnsigned(), souffle::Float, souffle::ast::NumericConstant::Float, souffle::ast::Constant::getConstant(), souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::ast::NumericConstant::getType(), souffle::ast::analysis::TypeSet::insert(), souffle::ast::NumericConstant::Int, souffle::Signed, souffle::ast::NumericConstant::Uint, and souffle::Unsigned.
{
         TypeSet possibleTypes;
         // Check if the type is given.
         if (constant.getType().has_value()) {
             switch (*constant.getType()) {
                 // Insert a type, but only after checking that parsing is possible.
                 case NumericConstant::Type::Int:
                     if (canBeParsedAsRamSigned(constant.getConstant())) {
                         possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Signed));
                     }
                     break;
                 case NumericConstant::Type::Uint:
                     if (canBeParsedAsRamUnsigned(constant.getConstant())) {
                         possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Unsigned));
                     }
                     break;
                 case NumericConstant::Type::Float:
                     if (canBeParsedAsRamFloat(constant.getConstant())) {
                         possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Float));
                     }
                     break;
             }
             // Else: all numeric types that can be parsed are valid.
         } else {
             if (canBeParsedAsRamSigned(constant.getConstant())) {
                 possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Signed));
             }
             if (canBeParsedAsRamUnsigned(constant.getConstant())) {
                 possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Unsigned));
             }
             if (canBeParsedAsRamFloat(constant.getConstant())) {
                 possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Float));
             }
         }
         addConstraint(hasSuperTypeInSet(getVar(constant), possibleTypes));
     }
visitRecordInit()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitRecordInit (const RecordInit & record) inline override private
Definition at line 719 of file Type.cpp.
References souffle::ast::Term::getArguments(), and i.
{
         auto arguments = record.getArguments();
         for (size_t i = 0; i < arguments.size(); ++i) {
             addConstraint(isSubtypeOfComponent(getVar(arguments[i]), getVar(record), i));
         }
     }
visitSink()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitSink (const Atom & atom) inline private
Definition at line 578 of file Type.cpp.
References souffle::ast::analysis::TypeEnvironment::getConstantTypes(), and souffle::ast::analysis::isSubtypeOf().
{
         iterateOverAtom(atom, [&](const Argument& argument, const Type& attributeType) {
             if (isA<RecordType>(attributeType)) {
                 addConstraint(isSubtypeOf(getVar(argument), getBaseType(&attributeType)));
                 return;
             }
             for (auto& constantType : typeEnv.getConstantTypes()) {
                 if (isSubtypeOf(attributeType, constantType)) {
                     addConstraint(isSubtypeOf(getVar(argument), constantType));
                 }
             }
         });
     }
visitStringConstant()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitStringConstant (const StringConstant & cnst) inline override private
Definition at line 607 of file Type.cpp.
References souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::ast::analysis::isSubtypeOf(), and souffle::Symbol.
{
         addConstraint(isSubtypeOf(getVar(cnst), typeEnv.getConstantType(TypeAttribute::Symbol)));
     }
visitTypeCast()
void souffle::ast::analysis::TypeConstraintsAnalysis::visitTypeCast (const ast::TypeCast & typeCast) inline override private
Definition at line 702 of file Type.cpp.
References souffle::ast::TypeCast::getType(), souffle::ast::analysis::TypeEnvironment::getType(), souffle::ast::TypeCast::getValue(), souffle::ast::analysis::isSubtypeOf(), and souffle::ast::analysis::TypeEnvironment::isType().
{
         auto& typeName = typeCast.getType();
         if (!typeEnv.isType(typeName)) {
             return;
         }
         addConstraint(isSubtypeOf(getVar(typeCast), typeEnv.getType(typeName)));
         // If we are dealing with a constant then its type must be deduced from the cast
         // Otherwise, expression like: to_string(as(2, float)) couldn't be typed.
         auto* value = typeCast.getValue();
         if (isA<Constant>(value)) {
             addConstraint(isSubtypeOf(getVar(*value), typeEnv.getType(typeName)));
         }
     }
Field Documentation
program
const Program& souffle::ast::analysis::TypeConstraintsAnalysis::program = tu.getProgram() private
Definition at line 567 of file Type.cpp.
sinks
std::set<const Atom*> souffle::ast::analysis::TypeConstraintsAnalysis::sinks private
Definition at line 571 of file Type.cpp.
sumTypesBranches
const SumTypeBranchesAnalysis& souffle::ast::analysis::TypeConstraintsAnalysis::sumTypesBranches = *tu.getAnalysis<SumTypeBranchesAnalysis>() private
Definition at line 568 of file Type.cpp.
tu
const TranslationUnit& souffle::ast::analysis::TypeConstraintsAnalysis::tu private
Definition at line 565 of file Type.cpp.
typeEnv
const TypeEnvironment& souffle::ast::analysis::TypeConstraintsAnalysis::typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment() private
Definition at line 566 of file Type.cpp.
The documentation for this class was generated from the following file:
ast/analysis/Type.cpp