souffle: souffle::ram::analysis::LevelAnalysis Class Reference
souffle::ram::analysis::LevelAnalysis Class Reference
A Ram Analysis for determining the level of a expression/condition.
#include <Level.h>
Public Member Functions
int getLevel (const Node *value) const
Get level of a RAM expression/condition.
LevelAnalysis (const char *id)
void run (const TranslationUnit &) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::ram::analysis::Analysis
Analysis (const char *id)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "level-analysis"
Additional Inherited Members
Protected Attributes inherited from souffle::ram::analysis::Analysis
std::string identifier
name of analysis instance
Detailed Description
A Ram Analysis for determining the level of a expression/condition.
The expression is determined by the TupleElement of an expression/condition with the highest tuple-id number. Note in the implementation we assume that the tuple-id of TupleOperation operations are ordered, i.e., the most-outer loop has the smallest tuple-id and the most inner-loop has the largest tuple-id number.
If an expression/condition does not contain an TupleElement accessing an element of a tuple, the analysis yields -1 for denoting that the expression/condition can be executed outside of the loop-nest, i.e., the expression/condition is independent of data stemming from relations.
Definition at line 42 of file Level.h.
Constructor & Destructor Documentation
LevelAnalysis()
souffle::ram::analysis::LevelAnalysis::LevelAnalysis (const char * id) inline
Definition at line 44 of file Level.h.
 : Analysis(id) {}
Member Function Documentation
getLevel()
int souffle::ram::analysis::LevelAnalysis::getLevel (const Node * value) const
Get level of a RAM expression/condition.
Definition at line 58 of file Level.cpp.
References b, souffle::fatal(), souffle::filter(), souffle::ram::AbstractOperator::getArguments(), souffle::ram::PackRecord::getArguments(), souffle::ram::AbstractChoice::getCondition(), souffle::ram::AbstractConditional::getCondition(), souffle::ram::AbstractAggregate::getCondition(), souffle::ram::UnpackRecord::getExpression(), souffle::ram::AbstractAggregate::getExpression(), souffle::ram::Conjunction::getLHS(), souffle::ram::Constraint::getLHS(), souffle::ram::Negation::getOperand(), souffle::ram::IndexOperation::getRangePattern(), souffle::ram::Conjunction::getRHS(), souffle::ram::Constraint::getRHS(), souffle::ram::TupleElement::getTupleId(), souffle::ram::SubroutineReturn::getValues(), souffle::ram::AbstractExistenceCheck::getValues(), souffle::ram::Project::getValues(), and souffle::pack().
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern(), souffle::ram::transform::MakeIndexTransformer::getExpressionPair(), souffle::ram::transform::MakeIndexTransformer::getLowerUpperExpression(), souffle::ram::transform::HoistAggregateTransformer::hoistAggregate(), souffle::ram::transform::HoistConditionsTransformer::hoistConditions(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), and run().
{
     // visitor
     class ValueLevelVisitor : public Visitor<int> {
     public:
         // number
         int visitConstant(const Constant&) override {
             return -1;
         }
         // true
         int visitTrue(const True&) override {
             return -1;
         }
         // false
         int visitFalse(const False&) override {
             return -1;
         }
         // tuple element access
         int visitTupleElement(const TupleElement& elem) override {
             return elem.getTupleId();
         }
         // scan
         int visitScan(const Scan&) override {
             return -1;
         }
         // index scan
         int visitIndexScan(const IndexScan& indexScan) override {
             int level = -1;
             for (auto& index : indexScan.getRangePattern().first) {
                 level = std::max(level, visit(index));
             }
             for (auto& index : indexScan.getRangePattern().second) {
                 level = std::max(level, visit(index));
             }
             return level;
         }
         // choice
         int visitChoice(const Choice& choice) override {
             return std::max(-1, visit(choice.getCondition()));
         }
         // index choice
         int visitIndexChoice(const IndexChoice& indexChoice) override {
             int level = -1;
             for (auto& index : indexChoice.getRangePattern().first) {
                 level = std::max(level, visit(index));
             }
             for (auto& index : indexChoice.getRangePattern().second) {
                 level = std::max(level, visit(index));
             }
             return std::max(level, visit(indexChoice.getCondition()));
         }
         // aggregate
         int visitAggregate(const Aggregate& aggregate) override {
             return std::max(visit(aggregate.getExpression()), visit(aggregate.getCondition()));
         }
         // index aggregate
         int visitIndexAggregate(const IndexAggregate& indexAggregate) override {
             int level = -1;
             for (auto& index : indexAggregate.getRangePattern().first) {
                 level = std::max(level, visit(index));
             }
             for (auto& index : indexAggregate.getRangePattern().second) {
                 level = std::max(level, visit(index));
             }
             level = std::max(visit(indexAggregate.getExpression()), level);
             return std::max(level, visit(indexAggregate.getCondition()));
         }
         // unpack record
         int visitUnpackRecord(const UnpackRecord& unpack) override {
             return visit(unpack.getExpression());
         }
         // filter
         int visitFilter(const Filter& filter) override {
             return visit(filter.getCondition());
         }
         // break
         int visitBreak(const Break& b) override {
             return visit(b.getCondition());
         }
         // project
         int visitProject(const Project& project) override {
             int level = -1;
             for (auto& exp : project.getValues()) {
                 level = std::max(level, visit(exp));
             }
             return level;
         }
         // return
         int visitSubroutineReturn(const SubroutineReturn& ret) override {
             int level = -1;
             for (auto& exp : ret.getValues()) {
                 level = std::max(level, visit(exp));
             }
             return level;
         }
         // auto increment
         int visitAutoIncrement(const AutoIncrement&) override {
             return -1;
         }
         // undef value
         int visitUndefValue(const UndefValue&) override {
             return -1;
         }
         // intrinsic functors
         int visitIntrinsicOperator(const IntrinsicOperator& op) override {
             int level = -1;
             for (const auto& arg : op.getArguments()) {
                 level = std::max(level, visit(arg));
             }
             return level;
         }
         // pack operator
         int visitPackRecord(const PackRecord& pack) override {
             int level = -1;
             for (const auto& arg : pack.getArguments()) {
                 level = std::max(level, visit(arg));
             }
             return level;
         }
         // argument
         int visitSubroutineArgument(const SubroutineArgument&) override {
             return -1;
         }
         // user defined operator
         int visitUserDefinedOperator(const UserDefinedOperator& op) override {
             int level = -1;
             for (const auto& arg : op.getArguments()) {
                 level = std::max(level, visit(arg));
             }
             return level;
         }
         // conjunction
         int visitConjunction(const Conjunction& conj) override {
             return std::max(visit(conj.getLHS()), visit(conj.getRHS()));
         }
         // negation
         int visitNegation(const Negation& neg) override {
             return visit(neg.getOperand());
         }
         // constraint
         int visitConstraint(const Constraint& binRel) override {
             return std::max(visit(binRel.getLHS()), visit(binRel.getRHS()));
         }
         // existence check
         int visitExistenceCheck(const ExistenceCheck& exists) override {
             int level = -1;
             for (const auto& cur : exists.getValues()) {
                 level = std::max(level, visit(cur));
             }
             return level;
         }
         // provenance existence check
         int visitProvenanceExistenceCheck(const ProvenanceExistenceCheck& provExists) override {
             int level = -1;
             for (const auto& cur : provExists.getValues()) {
                 level = std::max(level, visit(cur));
             }
             return level;
         }
         // emptiness check
         int visitEmptinessCheck(const EmptinessCheck&) override {
             return -1;  // can be in the top level
         }
         // default rule
         int visitNode(const Node&) override {
             fatal("Node not implemented!");
         }
     };
     assert((isA<Expression>(node) || isA<Condition>(node) || isA<Operation>(node)) &&
             "not an expression/condition/operation");
     return ValueLevelVisitor().visit(node);
 }
run()
void souffle::ram::analysis::LevelAnalysis::run (const TranslationUnit & translationUnit) inline override virtual
Run analysis for a RAM translation unit.
Implements souffle::ram::analysis::Analysis.
Definition at line 48 of file Level.h.
References getLevel().
 {}
Field Documentation
name
constexpr const char* souffle::ram::analysis::LevelAnalysis::name = "level-analysis" static
Definition at line 46 of file Level.h.
The documentation for this class was generated from the following files:
ram/analysis/Level.h
ram/analysis/Level.cpp