souffle: souffle::ram::SubroutineReturn Class Reference
souffle::ram::SubroutineReturn Class Reference
A statement for returning from a ram subroutine.
#include <SubroutineReturn.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
SubroutineReturn * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< Expression * > getValues () const
Getter for expressions.
SubroutineReturn (VecOwn< Expression > vals)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
VecOwn< Expression > expressions
Return expressions.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
A statement for returning from a ram subroutine.
For example:
...
  RETURN (t0.0, t0.1)
Definition at line 42 of file SubroutineReturn.h.
Constructor & Destructor Documentation
SubroutineReturn()
souffle::ram::SubroutineReturn::SubroutineReturn (VecOwn< Expression > vals) inline
Definition at line 44 of file SubroutineReturn.h.
References expressions.
Referenced by clone().
                                               : expressions(std::move(vals)) {
         for (const auto& expr : expressions) {
             assert(expr != nullptr && "Expression is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::ram::SubroutineReturn::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 71 of file SubroutineReturn.h.
References expressions, and souffle::map().
{
         for (auto& expr : expressions) {
             expr = map(std::move(expr));
         }
     }
clone()
SubroutineReturn* souffle::ram::SubroutineReturn::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Operation.
Definition at line 63 of file SubroutineReturn.h.
References expressions, and SubroutineReturn().
Referenced by souffle::ram::test::TEST().
{
         VecOwn<Expression> newValues;
         for (auto& expr : expressions) {
             newValues.emplace_back(expr->clone());
         }
         return new SubroutineReturn(std::move(newValues));
     }
equal()
bool souffle::ram::SubroutineReturn::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 90 of file SubroutineReturn.h.
References souffle::equal_targets(), and expressions.
{
         const auto& other = static_cast<const SubroutineReturn&>(node);
         return equal_targets(expressions, other.expressions);
     }
getChildNodes()
std::vector<const Node*> souffle::ram::SubroutineReturn::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 55 of file SubroutineReturn.h.
References expressions.
{
         std::vector<const Node*> res;
         for (const auto& expr : expressions) {
             res.push_back(expr.get());
         }
         return res;
     }
getValues()
std::vector<Expression*> souffle::ram::SubroutineReturn::getValues () const inline
Getter for expressions.
Definition at line 51 of file SubroutineReturn.h.
References expressions, and souffle::toPtrVector().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), print(), and souffle::NodeGenerator::visitSubroutineReturn().
{
         return toPtrVector(expressions);
     }
print()
void souffle::ram::SubroutineReturn::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Operation.
Definition at line 78 of file SubroutineReturn.h.
References getValues(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "RETURN (";
         for (auto val : getValues()) {
             os << *val;
             if (val != *(getValues().end() - 1)) {
                 os << ", ";
             }
         }
         os << ")" << std::endl;
     }
Field Documentation
expressions
VecOwn<Expression> souffle::ram::SubroutineReturn::expressions protected
Return expressions.
Definition at line 96 of file SubroutineReturn.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getValues(), and SubroutineReturn().
The documentation for this class was generated from the following file:
ram/SubroutineReturn.h