souffle: souffle::ram::analysis::Analysis Class Reference
souffle::ram::analysis::Analysis Class Reference abstract
Abstract class for a RAM Analysis.
#include <Analysis.h>
Public Member Functions
Analysis (const char *id)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
virtual void run (const TranslationUnit &translationUnit)=0
Run analysis for a RAM translation unit.
virtual ~Analysis ()=default
Protected Attributes
std::string identifier
name of analysis instance
Friends
std::ostream & operator<< (std::ostream &out, const Analysis &other)
define output stream operator
Detailed Description
Abstract class for a RAM Analysis.
Definition at line 32 of file Analysis.h.
Constructor & Destructor Documentation
Analysis()
souffle::ram::analysis::Analysis::Analysis (const char * id) inline
Definition at line 34 of file Analysis.h.
References ~Analysis().
 : identifier(id) {}
~Analysis()
virtual souffle::ram::analysis::Analysis::~Analysis () virtual default
Referenced by Analysis().
Member Function Documentation
getName()
virtual const std::string& souffle::ram::analysis::Analysis::getName () const inline virtual
get name of the analysis
Definition at line 38 of file Analysis.h.
References identifier, and run().
{
         return identifier;
     }
print()
virtual void souffle::ram::analysis::Analysis::print (std::ostream &) const inline virtual
Print the analysis result in HTML format.
Reimplemented in souffle::ram::analysis::IndexAnalysis.
Definition at line 46 of file Analysis.h.
 {}
run()
virtual void souffle::ram::analysis::Analysis::run (const TranslationUnit & translationUnit) pure virtual
Run analysis for a RAM translation unit.
Implemented in souffle::ram::analysis::IndexAnalysis, souffle::ram::analysis::LevelAnalysis, and souffle::ram::analysis::ComplexityAnalysis.
Referenced by getName().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Analysis & other) friend
define output stream operator
Definition at line 49 of file Analysis.h.
{
         other.print(out);
         return out;
     }
Field Documentation
identifier
std::string souffle::ram::analysis::Analysis::identifier protected
name of analysis instance
Definition at line 56 of file Analysis.h.
Referenced by getName().
The documentation for this class was generated from the following file:
ram/analysis/Analysis.h