souffle: souffle::ast::StringConstant Class Reference
souffle::ast::StringConstant Class Reference
String constant class.
#include <StringConstant.h>
Public Member Functions
StringConstant * clone () const override
Create clone.
StringConstant (std::string value, SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Constant
const std::string & getConstant () const
Get string representation of Constant.
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::ast::Constant
Constant (std::string value, SrcLocation loc={})
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
Detailed Description
String constant class.
Definition at line 31 of file StringConstant.h.
Constructor & Destructor Documentation
StringConstant()
souffle::ast::StringConstant::StringConstant (std::string value, SrcLocation loc = {}) inline explicit
Definition at line 33 of file StringConstant.h.
References souffle::ast::Constant::Constant(), and souffle::ast::Node::setSrcLoc().
Referenced by clone().
                                                                {}) : Constant(std::move(value)) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
clone()
StringConstant* souffle::ast::StringConstant::clone () const inline override virtual
Create clone.
Implements souffle::ast::Constant.
Definition at line 37 of file StringConstant.h.
References souffle::ast::Constant::getConstant(), souffle::ast::Node::getSrcLoc(), and StringConstant().
{
         auto* res = new StringConstant(getConstant());
         res->setSrcLoc(getSrcLoc());
         return res;
     }
print()
void souffle::ast::StringConstant::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Reimplemented from souffle::ast::Constant.
Definition at line 44 of file StringConstant.h.
References souffle::ast::Constant::getConstant().
{
         os << "\"" << getConstant() << "\"";
     }
The documentation for this class was generated from the following file:
ast/StringConstant.h