souffle: souffle::Trie< 1u > Class Template Reference
souffle::Trie< 1u > Class Template Reference
A template specialization for tries representing a set.
#include <Brie.h>
Data Structures
class iterator_core
The iterator core of this level contributing to the construction of a composed trie iterator.
Public Types
using element_type = entry_type
using iterator = typename base::template iterator< iterator_core >
using op_context = typename map_type::op_context
using operation_hints = op_context
Public Types inherited from souffle::detail::TrieBase< 1u, Trie< 1u > >
using entry_type = typename souffle::Tuple< RamDomain, Dim >
The type of the stored entries / tuples.
Public Member Functions
iterator begin () const
Obtains an iterator referencing the first element stored within this trie or end() if this trie is empty.
void clear ()
Removes all elements form this trie.
bool contains (const entry_type &tuple) const
Determines whether the given tuple is present in this trie or not.
bool contains (const entry_type &tuple, op_context &ctxt) const
Determines whether the given tuple is present in this trie or not.
bool empty () const
Determines whether this trie is empty or not.
iterator end () const
Obtains an iterator referencing the first position after the last element within this trie.
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry, op_context &ctxt) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
std::size_t getMemoryUsage () const
Computes the total memory usage of this data structure.
const map_type & getStore () const
Provides protected access to the internally maintained store.
bool insert (const entry_type &tuple)
Inserts the given tuple into this trie.
bool insert (const entry_type &tuple, op_context &ctxt)
Inserts the given tuple into this trie.
void insertAll (const Trie &other)
Inserts all tuples stored within the given trie into this trie.
iterator lower_bound (const entry_type &entry, op_context &) const
iterator lower_bound (const entry_type &entry) const
std::vector< range< iterator > > partition (unsigned chunks=500) const
Obtains a partition of this tire such that the resulting list of ranges cover disjoint subsets of the elements stored in this trie.
std::size_t size () const
Determines the number of elements stored in this trie.
iterator upper_bound (const entry_type &entry, op_context &) const
iterator upper_bound (const entry_type &entry) const
Public Member Functions inherited from souffle::detail::TrieBase< 1u, Trie< 1u > >
bool contains (Values... values) const
A generic function enabling the convenient conduction of a membership check.
bool insert (Values... values)
A generic function enabling the insertion of tuple values in a user-friendly way.
void printStats (std::ostream &out) const
Private Types
using base = typename detail::TrieBase< 1u, Trie< 1u > >
using map_type = SparseBitMap<>
Private Member Functions
template<unsigned I, typename Tuple >
bool contains_internal (const Tuple &tuple, op_context &ctxt) const
An internal implementation of the contains member function determining whether a given tuple is present within this sub-trie or not.
template<unsigned I, typename Tuple >
iterator_core< I > getBeginCoreIterator (Tuple &entry) const
Creates a core iterator for this trie level and updates component I of the given entry to exhibit the corresponding first value.
template<unsigned I, typename Tuple >
bool insert_internal (const Tuple &tuple, op_context &ctxt)
The internally utilized implementation of the insert operation inserting a given tuple into this sub-trie.
Private Attributes
map_type map
Friends
template<unsigned Dim, typename Derived >
class detail::TrieBase
template<unsigned Dim>
class Trie
Additional Inherited Members
Protected Attributes inherited from souffle::detail::TrieBase< 1u, Trie< 1u > >
hint_statistics hint_stats
Detailed Description
template<>
class souffle::Trie< 1u >
A template specialization for tries representing a set.
For improved memory efficiency, this level is the leaf-node level of all tries exhibiting an arity >= 1. Internally, values are stored utilizing sparse bit maps.
Definition at line 2847 of file Brie.h.
Member Typedef Documentation
base
using souffle::Trie< 1u >::base = typename detail::TrieBase<1u, Trie<1u> > private
Definition at line 2855 of file Brie.h.
element_type
using souffle::Trie< 1u >::element_type = entry_type
Definition at line 2864 of file Brie.h.
iterator
using souffle::Trie< 1u >::iterator = typename base::template iterator<iterator_core>
Definition at line 3021 of file Brie.h.
map_type
using souffle::Trie< 1u >::map_type = SparseBitMap<> private
Definition at line 2858 of file Brie.h.
op_context
using souffle::Trie< 1u >::op_context = typename map_type::op_context
Definition at line 2865 of file Brie.h.
operation_hints
using souffle::Trie< 1u >::operation_hints = op_context
Definition at line 2866 of file Brie.h.
Member Function Documentation
begin()
iterator souffle::Trie< 1u >::begin () const inline
Obtains an iterator referencing the first element stored within this trie or end() if this trie is empty.
Definition at line 3027 of file Brie.h.
References souffle::SparseBitMap< BITS >::begin(), and souffle::SparseBitMap< BITS >::empty().
{
         if (map.empty()) return end();
         return iterator(map.begin());
     }
clear()
void souffle::Trie< 1u >::clear () inline
Removes all elements form this trie.
Definition at line 2896 of file Brie.h.
References souffle::SparseBitMap< BITS >::clear().
                  {
         map.clear();
     }
contains() [1/2]
bool souffle::Trie< 1u >::contains (const entry_type & tuple) const inline
Determines whether the given tuple is present in this trie or not.
Parameters
tuple the tuple to be tested
Returns
true if present, false otherwise
Definition at line 2929 of file Brie.h.
References souffle::contains().
{
         op_context ctxt;
         return contains(tuple, ctxt);
     }
contains() [2/2]
bool souffle::Trie< 1u >::contains (const entry_type & tuple, op_context & ctxt) const inline
Determines whether the given tuple is present in this trie or not.
An operation context can be provided to exploit temporal locality.
Parameters
tuple the tuple to be tested
ctxt an operation context for exploiting temporal locality
Returns
true if present, false otherwise
Definition at line 2942 of file Brie.h.
{
         return contains_internal<0>(tuple, ctxt);
     }
contains_internal()
template<unsigned I, typename Tuple > bool souffle::Trie< 1u >::contains_internal (const Tuple & tuple, op_context & ctxt) const inline private
An internal implementation of the contains member function determining whether a given tuple is present within this sub-trie or not.
Template Parameters
I the component index associated to this level
Tuple the tuple type to be checked
Parameters
tuple the tuple to be checked
ctxt a operation context to exploit temporal locality
Returns
true if this tuple is present, false otherwise
Definition at line 3171 of file Brie.h.
References souffle::SparseBitMap< BITS >::test().
{
         return map.test(tuple[I], ctxt);
     }
empty()
bool souffle::Trie< 1u >::empty () const inline
Determines whether this trie is empty or not.
Definition at line 2874 of file Brie.h.
References souffle::SparseBitMap< BITS >::empty().
{
         return map.empty();
     }
end()
iterator souffle::Trie< 1u >::end () const inline
Obtains an iterator referencing the first position after the last element within this trie.
Definition at line 3036 of file Brie.h.
{
         return iterator();
     }
getBeginCoreIterator()
template<unsigned I, typename Tuple > iterator_core<I> souffle::Trie< 1u >::getBeginCoreIterator (Tuple & entry) const inline private
Creates a core iterator for this trie level and updates component I of the given entry to exhibit the corresponding first value.
Template Parameters
I the index of the tuple to be processed by the resulting iterator core
Tuple the type of the tuple to be processed by the resulting iterator core
Parameters
entry a reference to the tuple to be updated to the first value
Returns
the requested iterator core instance
Definition at line 3141 of file Brie.h.
References souffle::SparseBitMap< BITS >::begin().
{
         return iterator_core<I>(map.begin(), entry);
     }
getBoundaries() [1/2]
template<unsigned levels> range<iterator> souffle::Trie< 1u >::getBoundaries (const entry_type & entry) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
Returns
the corresponding range of matching elements
Definition at line 3078 of file Brie.h.
{
         op_context ctxt;
         return getBoundaries<levels>(entry, ctxt);
     }
getBoundaries() [2/2]
template<unsigned levels> range<iterator> souffle::Trie< 1u >::getBoundaries (const entry_type & entry, op_context & ctxt) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
A operation context may be provided to exploit temporal locality.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
ctxt the operation context to be utilized
Returns
the corresponding range of matching elements
Definition at line 3094 of file Brie.h.
References souffle::SparseBitMap< BITS >::end(), souffle::SparseBitMap< BITS >::find(), and souffle::make_range().
{
         // for levels = 0
         if (levels == 0) return make_range(begin(), end());
         // for levels = 1
         auto pos = map.find(entry[0], ctxt);
         if (pos == map.end()) return make_range(end(), end());
         auto next = pos;
         ++next;
         return make_range(iterator(pos), iterator(next));
     }
getMemoryUsage()
std::size_t souffle::Trie< 1u >::getMemoryUsage () const inline
Computes the total memory usage of this data structure.
Definition at line 2888 of file Brie.h.
References souffle::SparseBitMap< BITS >::getMemoryUsage().
{
         // compute the total memory usage
         return sizeof(*this) - sizeof(map_type) + map.getMemoryUsage();
     }
getStore()
const map_type& souffle::Trie< 1u >::getStore () const inline
Provides protected access to the internally maintained store.
Definition at line 3126 of file Brie.h.
References souffle::map().
{
         return map;
     }
insert() [1/2]
bool souffle::Trie< 1u >::insert (const entry_type & tuple) inline
Inserts the given tuple into this trie.
Parameters
tuple the tuple to be inserted
Returns
true if the tuple has not been present before, false otherwise
Definition at line 2906 of file Brie.h.
{
         op_context ctxt;
         return insert(tuple, ctxt);
     }
insert() [2/2]
bool souffle::Trie< 1u >::insert (const entry_type & tuple, op_context & ctxt) inline
Inserts the given tuple into this trie.
An operation context can be provided to exploit temporal locality.
Parameters
tuple the tuple to be inserted
ctxt an operation context for exploiting temporal locality
Returns
true if the tuple has not been present before, false otherwise
Definition at line 2919 of file Brie.h.
{
         return insert_internal<0>(tuple, ctxt);
     }
insert_internal()
template<unsigned I, typename Tuple > bool souffle::Trie< 1u >::insert_internal (const Tuple & tuple, op_context & ctxt) inline private
The internally utilized implementation of the insert operation inserting a given tuple into this sub-trie.
Template Parameters
I the component index associated to this level
Tuple the tuple type to be inserted
Parameters
tuple the tuple to be inserted
ctxt a operation context to exploit temporal locality
Returns
true if this tuple wasn't contained before, false otherwise
Definition at line 3156 of file Brie.h.
References souffle::SparseBitMap< BITS >::set().
{
         return map.set(tuple[I], ctxt);
     }
insertAll()
void souffle::Trie< 1u >::insertAll (const Trie< 1u > & other) inline
Inserts all tuples stored within the given trie into this trie.
This operation is considerably more efficient than the consecutive insertion of the elements in other into this trie.
Definition at line 2951 of file Brie.h.
References souffle::SparseBitMap< BITS >::addAll().
{
         map.addAll(other.map);
     }
lower_bound() [1/2]
iterator souffle::Trie< 1u >::lower_bound (const entry_type & entry, op_context &) const inline
Definition at line 3105 of file Brie.h.
References souffle::SparseBitMap< BITS >::lower_bound().
{
         return iterator(map.lower_bound(entry[0]));
     }
lower_bound() [2/2]
iterator souffle::Trie< 1u >::lower_bound (const entry_type & entry) const inline
Definition at line 3109 of file Brie.h.
{
         op_context ctxt;
         return lower_bound(entry, ctxt);
     }
partition()
std::vector<range<iterator> > souffle::Trie< 1u >::partition (unsigned chunks = 500) const inline
Obtains a partition of this tire such that the resulting list of ranges cover disjoint subsets of the elements stored in this trie.
Their union is equivalent to the content of this trie.
Definition at line 3045 of file Brie.h.
References souffle::SparseBitMap< BITS >::begin(), souffle::SparseBitMap< BITS >::end(), souffle::make_range(), and souffle::SparseBitMap< BITS >::size().
{
         std::vector<range<iterator>> res;
         // shortcut for empty trie
         if (this->empty()) return res;
         // use top-level elements for partitioning
         int step = static_cast<int>(std::max(map.size() / chunks, size_t(1)));
         int c = 1;
         auto priv = begin();
         for (auto it = map.begin(); it != map.end(); ++it, c++) {
             if (c % step != 0 || c == 1) {
                 continue;
             }
             auto cur = iterator(it);
             res.push_back(make_range(priv, cur));
             priv = cur;
         }
         // add final chunk
         res.push_back(make_range(priv, end()));
         return res;
     }
size()
std::size_t souffle::Trie< 1u >::size () const inline
Determines the number of elements stored in this trie.
Definition at line 2881 of file Brie.h.
References souffle::SparseBitMap< BITS >::size().
{
         return map.size();
     }
upper_bound() [1/2]
iterator souffle::Trie< 1u >::upper_bound (const entry_type & entry, op_context &) const inline
Definition at line 3114 of file Brie.h.
References souffle::SparseBitMap< BITS >::upper_bound().
{
         return iterator(map.upper_bound(entry[0]));
     }
upper_bound() [2/2]
iterator souffle::Trie< 1u >::upper_bound (const entry_type & entry) const inline
Definition at line 3118 of file Brie.h.
{
         op_context ctxt;
         return upper_bound(entry, ctxt);
     }
Friends And Related Function Documentation
detail::TrieBase
template<unsigned Dim, typename Derived > friend class detail::TrieBase friend
Definition at line 2852 of file Brie.h.
Trie
template<unsigned Dim> friend class Trie friend
Definition at line 2849 of file Brie.h.
Field Documentation
map
map_type souffle::Trie< 1u >::map private
Definition at line 2861 of file Brie.h.
The documentation for this class was generated from the following file:
include/souffle/datastructure/Brie.h