souffle: souffle::ram::ParallelIndexAggregate Class Reference
souffle::ram::ParallelIndexAggregate Class Reference
Aggregate over values of a relation using an index in parallel.
#include <ParallelIndexAggregate.h>
Public Member Functions
ParallelIndexAggregate * clone () const override
Create a clone (i.e.
ParallelIndexAggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, RamPattern queryPattern, int ident)
Public Member Functions inherited from souffle::ram::IndexAggregate
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
IndexAggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, RamPattern queryPattern, int ident)
Public Member Functions inherited from souffle::ram::IndexOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< Expression * >, std::vector< Expression * > > getRangePattern () const
Get range pattern.
IndexOperation (Own< RelationReference > r, int ident, RamPattern queryPattern, Own< Operation > nested, std::string profileText="")
void printIndex (std::ostream &os) const
Helper method for printing.
Public Member Functions inherited from souffle::ram::RelationOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Relation & getRelation () const
Get search relation.
RelationOperation (Own< RelationReference > relRef, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractAggregate
AbstractAggregate (AggregateOp fun, Own< Expression > expr, Own< Condition > cond)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Get condition.
const Expression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
virtual ~AbstractAggregate ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::IndexAggregate
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::IndexOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractAggregate
bool equal (const Node &node) const
void print (std::ostream &os, int) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::IndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::ram::RelationOperation
Own< RelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractAggregate
Own< Condition > condition
Aggregation tuple condition.
Own< Expression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Aggregate over values of a relation using an index in parallel.
For example:
t0.0=sum t0.1 SEARCH t0  S ON INDEX t0.0 = number(1)
Definition at line 48 of file ParallelIndexAggregate.h.
Constructor & Destructor Documentation
ParallelIndexAggregate()
souffle::ram::ParallelIndexAggregate::ParallelIndexAggregate (Own< Operation > nested, AggregateOp fun, Own< RelationReference > relRef, Own< Expression > expression, Own< Condition > condition, RamPattern queryPattern, int ident) inline
Definition at line 50 of file ParallelIndexAggregate.h.
Referenced by clone().
             : IndexAggregate(std::move(nested), fun, std::move(relRef), std::move(expression),
                       std::move(condition), std::move(queryPattern), ident) {}
Member Function Documentation
clone()
ParallelIndexAggregate* souffle::ram::ParallelIndexAggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::ram::IndexAggregate.
Definition at line 55 of file ParallelIndexAggregate.h.
References souffle::clone(), souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::expression, souffle::ram::NestedOperation::getOperation(), souffle::ram::TupleOperation::getTupleId(), i, ParallelIndexAggregate(), souffle::ram::IndexOperation::queryPattern, and souffle::ram::RelationOperation::relationRef.
{
         RamPattern pattern;
         for (const auto& i : queryPattern.first) {
             pattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             pattern.second.emplace_back(i->clone());
         }
         return new ParallelIndexAggregate(souffle::clone(&getOperation()), function,
                 souffle::clone(relationRef), souffle::clone(expression), souffle::clone(condition),
                 std::move(pattern), getTupleId());
     }
print()
void souffle::ram::ParallelIndexAggregate::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::ram::IndexAggregate.
Definition at line 69 of file ParallelIndexAggregate.h.
References souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::getCondition(), souffle::ram::Relation::getName(), souffle::ram::RelationOperation::getRelation(), souffle::ram::TupleOperation::getTupleId(), souffle::ram::isTrue(), souffle::ram::AbstractAggregate::print(), souffle::ram::NestedOperation::print(), souffle::ram::IndexOperation::printIndex(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PARALLEL t" << getTupleId() << ".0=";
         AbstractAggregate::print(os, tabpos);
         os << "SEARCH t" << getTupleId() << "  " << getRelation().getName();
         printIndex(os);
         if (!isTrue(condition.get())) {
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         IndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/ParallelIndexAggregate.h