souffle: souffle::ast::transform::MagicSetTransformer Class Reference
souffle::ast::transform::MagicSetTransformer Class Reference
Magic Set Transformation.
#include <MagicSet.h>
Data Structures
class AdornDatabaseTransformer
Database adornment.
class LabelDatabaseTransformer
Database labeller.
class MagicSetCoreTransformer
Core section of the magic set transformer.
class NormaliseDatabaseTransformer
Database normaliser for MST.
Public Member Functions
MagicSetTransformer * clone () const override
std::string getName () const override
MagicSetTransformer ()
Public Member Functions inherited from souffle::ast::transform::PipelineTransformer
PipelineTransformer * clone () const override
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< Transformer * > getSubtransformers () const override
template<typename... Args>
PipelineTransformer (Args... args)
PipelineTransformer (VecOwn< Transformer > pipeline)
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::ast::transform::MetaTransformer
bool applySubtransformer (TranslationUnit &translationUnit, Transformer *transformer)
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &tu) override
Static Private Member Functions
static std::set< QualifiedName > getIgnoredRelations (const TranslationUnit &tu)
Gets set of relations to ignore during the MST process.
static bool shouldRun (const TranslationUnit &tu)
Determines whether any part of the MST should be run.
Additional Inherited Members
Protected Member Functions inherited from souffle::ast::transform::PipelineTransformer
bool transform (TranslationUnit &translationUnit) override
Protected Attributes inherited from souffle::ast::transform::PipelineTransformer
VecOwn< Transformer > pipeline
Protected Attributes inherited from souffle::ast::transform::MetaTransformer
bool verbose = false
Detailed Description
Magic Set Transformation.
Involves four stages: (1) NormaliseDatabaseTransformer, for assumptions to hold (2) LabelDatabaseTransformer, to support negation (3) AdornDatabaseTransformer, to annotate information flow (4) MagicSetCoreTransformer, to perform the core magifying transformation
Definition at line 47 of file MagicSet.h.
Constructor & Destructor Documentation
MagicSetTransformer()
souffle::ast::transform::MagicSetTransformer::MagicSetTransformer () inline
Definition at line 54 of file MagicSet.h.
Referenced by clone().
             : PipelineTransformer(mk<NormaliseDatabaseTransformer>(), mk<LabelDatabaseTransformer>(),
                       mk<RemoveRedundantRelationsTransformer>(), mk<AdornDatabaseTransformer>(),
                       mk<RemoveRedundantRelationsTransformer>(), mk<MagicSetCoreTransformer>()) {}
Member Function Documentation
clone()
MagicSetTransformer* souffle::ast::transform::MagicSetTransformer::clone () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 63 of file MagicSet.h.
References MagicSetTransformer().
{
         return new MagicSetTransformer();
     }
getIgnoredRelations()
std::set< QualifiedName > souffle::ast::transform::MagicSetTransformer::getIgnoredRelations (const TranslationUnit & tu) static private
Gets set of relations to ignore during the MST process.
Ignored relations are relations that should not be copied or altered beyond normalisation.
Definition at line 62 of file MagicSet.cpp.
References souffle::Global::config(), souffle::contains(), souffle::DIV, souffle::EQREL, souffle::FDIV, souffle::FEQ, souffle::FGE, souffle::FGT, souffle::FLE, souffle::FLT, souffle::FNE, souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::Program::getClauses(), souffle::ast::getClauses(), souffle::ast::IntrinsicFunctor::getFunctionInfo(), souffle::ast::BinaryConstraint::getOperator(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Atom::getQualifiedName(), souffle::ast::QualifiedName::getQualifiers(), souffle::ast::Program::getRelations(), souffle::MAGIC, souffle::MOD, souffle::IntrinsicFunctorInfo::op, souffle::splitString(), souffle::UMOD, and souffle::ast::visitDepthFirst().
Referenced by transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), and souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform().
{
     Program& program = tu.getProgram();
     const auto& ioTypes = *tu.getAnalysis<analysis::IOTypeAnalysis>();
     std::set<QualifiedName> relationsToIgnore;
     // - Any relations not specified to magic-set
     std::vector<QualifiedName> specifiedRelations;
     // Pick up specified relations from config
     std::vector<std::string> configRels = splitString(Global::config().get("magic-transform"), ',');
     for (const auto& relStr : configRels) {
         std::vector<std::string> qualifiers = splitString(relStr, '.');
         specifiedRelations.push_back(QualifiedName(qualifiers));
     }
     // Pick up specified relations from relation tags
     for (const auto* rel : program.getRelations()) {
         if (rel->hasQualifier(RelationQualifier::MAGIC)) {
             specifiedRelations.push_back(rel->getQualifiedName());
         }
     }
     // Get the complement if not everything is magic'd
     if (!contains(configRels, "*")) {
         for (const Relation* rel : program.getRelations()) {
             if (!contains(specifiedRelations, rel->getQualifiedName())) {
                 relationsToIgnore.insert(rel->getQualifiedName());
             }
         }
     }
     // - Any relations known in constant time (IDB relations)
     for (auto* rel : program.getRelations()) {
         // Input relations
         if (ioTypes.isInput(rel)) {
             relationsToIgnore.insert(rel->getQualifiedName());
             continue;
         }
         // Any relations not dependent on any atoms
         bool hasRules = false;
         for (const auto* clause : getClauses(program, rel->getQualifiedName())) {
             visitDepthFirst(clause->getBodyLiterals(), [&](const Atom& /* atom */) { hasRules = true; });
         }
         if (!hasRules) {
             relationsToIgnore.insert(rel->getQualifiedName());
         }
     }
     // - Any relation with a neglabel
     visitDepthFirst(program, [&](const Atom& atom) {
         const auto& qualifiers = atom.getQualifiedName().getQualifiers();
         if (!qualifiers.empty() && qualifiers[0] == "@neglabel") {
             relationsToIgnore.insert(atom.getQualifiedName());
         }
     });
     // - Any relation with a clause containing float-related binary constraints
     const std::set<BinaryConstraintOp> floatOps(
             {BinaryConstraintOp::FEQ, BinaryConstraintOp::FNE, BinaryConstraintOp::FLE,
                     BinaryConstraintOp::FGE, BinaryConstraintOp::FLT, BinaryConstraintOp::FGT});
     for (const auto* clause : program.getClauses()) {
         visitDepthFirst(*clause, [&](const BinaryConstraint& bc) {
             if (contains(floatOps, bc.getOperator())) {
                 relationsToIgnore.insert(clause->getHead()->getQualifiedName());
             }
         });
     }
     // - Any relation with a clause containing order-dependent functors
     const std::set<FunctorOp> orderDepFuncOps(
             {FunctorOp::MOD, FunctorOp::FDIV, FunctorOp::DIV, FunctorOp::UMOD});
     for (const auto* clause : program.getClauses()) {
         visitDepthFirst(*clause, [&](const IntrinsicFunctor& functor) {
             if (contains(orderDepFuncOps, functor.getFunctionInfo()->op)) {
                 relationsToIgnore.insert(clause->getHead()->getQualifiedName());
             }
         });
     }
     // - Any eqrel relation
     for (auto* rel : program.getRelations()) {
         if (rel->getRepresentation() == RelationRepresentation::EQREL) {
             relationsToIgnore.insert(rel->getQualifiedName());
         }
     }
     // - Any relation with execution plans
     for (auto* clause : program.getClauses()) {
         if (clause->getExecutionPlan() != nullptr) {
             relationsToIgnore.insert(clause->getHead()->getQualifiedName());
         }
     }
     // - Any atom appearing in a clause containing a counter
     for (auto* clause : program.getClauses()) {
         bool containsCounter = false;
         visitDepthFirst(*clause, [&](const Counter& /* counter */) { containsCounter = true; });
         if (containsCounter) {
             visitDepthFirst(
                     *clause, [&](const Atom& atom) { relationsToIgnore.insert(atom.getQualifiedName()); });
         }
     }
     return relationsToIgnore;
 }
getName()
std::string souffle::ast::transform::MagicSetTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 59 of file MagicSet.h.
{
         return "MagicSetTransformer";
     }
shouldRun()
bool souffle::ast::transform::MagicSetTransformer::shouldRun (const TranslationUnit & tu) static private
Determines whether any part of the MST should be run.
Definition at line 170 of file MagicSet.cpp.
References souffle::Global::config(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Program::getRelations(), and souffle::MAGIC.
Referenced by transform().
{
     const Program& program = tu.getProgram();
     if (Global::config().has("magic-transform")) return true;
     for (const auto* rel : program.getRelations()) {
         if (rel->hasQualifier(RelationQualifier::MAGIC)) return true;
     }
     return false;
 }
transform()
bool souffle::ast::transform::MagicSetTransformer::transform (TranslationUnit & tu) inline override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 68 of file MagicSet.h.
References getIgnoredRelations(), shouldRun(), and souffle::ast::transform::PipelineTransformer::transform().
Referenced by souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::clone(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::clone(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::clone(), and souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::clone().
{
         return shouldRun(tu) ? PipelineTransformer::transform(tu) : false;
     }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp