souffle: souffle::test Namespace Reference
souffle::test Namespace Reference
Data Structures
struct reserver
struct reserver< std::unordered_set< A, B, C, D > >
Typedefs
using Entry = std::tuple< int, int >
using EqRel = souffle::EquivalenceRelation< Tuple< RamDomain, 2 > >
typedef souffle::LambdaBTreeSet< TestPair, std::function< TestPair::second_type(TestPair &)>, souffle::EqrelMapComparator< TestPair > > TestLambdaTree
typedef std::pair< size_t, size_t > TestPair
using time_point = std::chrono::high_resolution_clock::time_point
Functions
template<typename C >
int count (const C &c)
long duration (const time_point &start, const time_point &end)
std::vector< Entry > getData (unsigned numEntries)
time_point now ()
TEST (ParallelUtils, SpinLock)
TEST (SymbolTable, Basics)
TEST (Graph, Basic)
TEST (Relation0, Construction)
TEST (Pack, Tuple)
TEST (Table, Basic)
TEST (EqRelTest, Scoping)
TEST (ParallelUtils, ReadWriteLock)
TEST (RandomInsertPiggyTest, Scoping)
Piggy List that allows creation at arbitrary elements.
TEST (SymbolTable, Copy)
TEST (EqRelTest, Basic)
TEST (Relation1, Construction)
TEST (RandomInsertPiggyTest, Insertion)
TEST (Table, Stress)
TEST (PackUnpack, Tuple)
TEST (BTreeMultiSet, Basic)
TEST (BTreeSet, Basic)
TEST (RandomInsertPiggyTest, DoubleClear)
TEST (ParallelUtils, OptimisticReadWriteLock)
TEST (SymbolTable, Assign)
TEST (Basic, Iteration)
TEST (EqRelTest, Clear)
TEST (PackUnpack, Vector)
TEST (Independence, Iteration)
TEST (SymbolTable, Inserts)
TEST (EqRelTest, Duplicates)
TEST (PiggyTest, Scoping)
Regular Old Piggy List.
TEST (PiggyTest, Append)
TEST (EqRelTest, TransitivityTest)
TEST (IndependentMoving, Iteration)
TEST (PiggyTest, ElementCreation)
TEST (PiggyTest, Iteration)
TEST (EqRelTest, PairwiseIncremental)
TEST (IndependentCopying, Iteration)
TEST (PiggyTest, CopyCtor)
TEST (BTreeMultiSet, Duplicates)
TEST (EqRelTest, PairwiseDecremental)
TEST (BTreeSet, Duplicates)
TEST (BTreeMultiSet, Incremental)
TEST (BTreeMultiSet, Decremental)
TEST (BTreeSet, Incremental)
TEST (EqRelTest, Shuffled)
TEST (BTreeMultiSet, Shuffled)
TEST (PiggyTest, DoubleClear)
TEST (BTreeSet, Decremental)
TEST (BTreeMultiSet, IteratorEmpty)
TEST (EqRelTest, Extend)
TEST (BTreeMultiSet, IteratorBasic)
TEST (BTreeSet, Shuffled)
TEST (BTreeMultiSet, IteratorStress)
TEST (DjTest, Scoping)
The underlying Disjoint Set (essentially Anderson '91 Find-Union, but dynamic)
TEST (BTreeSet, Copy)
TEST (DjTest, MakeNode)
TEST (BTreeMultiSet, BoundaryTest)
TEST (DjTest, TestUnion)
TEST (EqRelTest, Merge)
TEST (DjTest, Clear)
TEST (BTreeSet, Merge)
TEST (BTreeMultiSet, BoundaryEmpty)
TEST (BTreeSet, IteratorEmpty)
TEST (BTreeSet, IteratorBasic)
TEST (BTreeMultiSet, Load)
TEST (EqRelTest, IterEmpty)
TEST (SparseDjTest, Scoping)
The SparseDisjointSet that is used by the EquivalenceRelation.
TEST (EqRelTest, IterBasic)
TEST (SparseDjTest, MakeNode)
TEST (BTreeMultiSet, Clear)
TEST (BTreeSet, IteratorStress)
TEST (SparseDjTest, TestUnion)
TEST (EqRelTest, IterRange)
TEST (BTreeSet, BoundaryTest)
TEST (SparseDjTest, SignedData)
TEST (BTreeSet, BoundaryEmpty)
TEST (BTreeSet, Load)
TEST (EqRelTest, IterPartition)
TEST (BTreeSet, Clear)
TEST (Performance, Basic)
TEST (BTreeSet, ChunkSplit)
TEST (LambdaBTreeTest, Scoping)
The LambdaBTree - essentially a ripoff to the Btree, but allows a function to be called on successful insert.
TEST (LambdaBTreeTest, Insert)
TEST (Performance, Load)
TEST (EqRelTest, Scaling)
TEST (BTreeSet, ChunkSplitStress)
TEST (BTreeSet, Parallel)
template<typename Op >
long time (const std::string &name, const Op &operation)
Typedef Documentation
Entry
typedef std::tuple< int, int > souffle::test::Entry
Definition at line 385 of file btree_multiset_test.cpp.
EqRel
using souffle::test::EqRel = typedef souffle::EquivalenceRelation<Tuple<RamDomain, 2> >
Definition at line 45 of file binary_relation_test.cpp.
TestLambdaTree
typedef souffle::LambdaBTreeSet<TestPair, std::function<TestPair::second_type(TestPair&)>, souffle::EqrelMapComparator<TestPair> > souffle::test::TestLambdaTree
Definition at line 500 of file eqrel_datastructure_test.cpp.
TestPair
typedef std::pair<size_t, size_t> souffle::test::TestPair
Definition at line 497 of file eqrel_datastructure_test.cpp.
time_point
typedef std::chrono::high_resolution_clock::time_point souffle::test::time_point
Definition at line 400 of file btree_multiset_test.cpp.
Function Documentation
count()
template<typename C > int souffle::test::count (const C & c)
Definition at line 28 of file table_test.cpp.
Referenced by souffle::ram::transform::Transformer::apply(), souffle::ast::transform::MetaTransformer::applySubtransformer(), souffle::ReadStreamSQLite::checkTableExists(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::clone(), duration(), souffle::duration_in_ns(), souffle::duration_in_us(), souffle::DebugReportSection::generateUniqueID(), genJsonAtoms(), souffle::profile::Tui::genJsonTop(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::getPositiveLabel(), souffle::detail::binary_search::lower_bound(), souffle::main(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::BindingStore::numBoundArguments(), souffle::detail::binary_search::operator()(), TEST(), souffle::ast::test::TEST(), souffle::TEST(), souffle::ast::transform::RemoveRedundantSumsTransformer::transform(), souffle::ast::transform::DebugReporter::transform(), souffle::AstToRamTranslator::translateUnit(), and souffle::detail::binary_search::upper_bound().
                       {
     int res = 0;
     for (auto it = c.begin(); it != c.end(); ++it) {
         res++;
     }
     return res;
 }
duration()
long souffle::test::duration (const time_point & start, const time_point & end)
Definition at line 406 of file btree_multiset_test.cpp.
References count().
Referenced by souffle::ExplainProvenanceImpl::measureRelation(), TEST(), and time().
{
     return std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
 }
getData()
std::vector< Entry > souffle::test::getData (unsigned numEntries)
Definition at line 387 of file btree_multiset_test.cpp.
References i, and k.
Referenced by TEST().
{
     std::vector<Entry> res(numEntries);
     int k = 0;
     for (unsigned i = 0; i < numEntries; i++) {
         res[k++] = Entry(i / 100, i % 100);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(res.begin(), res.end(), generator);
     return res;
 }
now()
time_point souffle::test::now ()
Definition at line 402 of file btree_multiset_test.cpp.
Referenced by TEST(), and time().
                  {
     return std::chrono::high_resolution_clock::now();
 }
TEST() [1/84]
souffle::test::TEST (ParallelUtils , SpinLock)
Definition at line 26 of file parallel_utils_test.cpp.
References EXPECT_EQ, i, souffle::SpinLock::lock(), and souffle::SpinLock::unlock().
{
     const int N = 1000000;
     SpinLock lock;
     volatile int c = 0;
 #pragma omp parallel for num_threads(4)
     for (int i = 0; i < N; i++) {
         lock.lock();
         c++;
         lock.unlock();
     }
     EXPECT_EQ(N, c);
 }
TEST() [2/84]
souffle::test::TEST (SymbolTable , Basics)
Definition at line 29 of file symbol_table_test.cpp.
References EXPECT_EQ, EXPECT_STREQ, souffle::SymbolTable::insert(), souffle::SymbolTable::lookup(), and souffle::SymbolTable::resolve().
{
     SymbolTable table;
     table.insert("Hello");
     EXPECT_STREQ("Hello", table.resolve(table.lookup(table.resolve(table.lookup("Hello")))));
     EXPECT_EQ(table.lookup("Hello"), table.lookup(table.resolve(table.lookup("Hello"))));
     EXPECT_STREQ("Hello", table.resolve(table.lookup(table.resolve(table.lookup("Hello")))));
     EXPECT_EQ(table.lookup("Hello"),
             table.lookup(table.resolve(table.lookup(table.resolve(table.lookup("Hello"))))));
 }
TEST() [3/84]
souffle::test::TEST (Graph , Basic)
Definition at line 30 of file graph_utils_test.cpp.
References souffle::Graph< Vertex, Compare >::contains(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::Graph< Vertex, Compare >::insert(), souffle::Graph< Vertex, Compare >::reaches(), and souffle::toString().
                    {
     Graph<int> g;
     EXPECT_FALSE(g.contains(1));
     EXPECT_FALSE(g.contains(2));
     EXPECT_FALSE(g.contains(3));
     EXPECT_FALSE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_FALSE(g.contains(2, 3));
     EXPECT_FALSE(g.reaches(1, 1));
     EXPECT_FALSE(g.reaches(1, 2));
     EXPECT_FALSE(g.reaches(1, 3));
     EXPECT_FALSE(g.reaches(2, 1));
     EXPECT_FALSE(g.reaches(2, 2));
     EXPECT_FALSE(g.reaches(2, 3));
     EXPECT_FALSE(g.reaches(3, 1));
     EXPECT_FALSE(g.reaches(3, 2));
     EXPECT_FALSE(g.reaches(3, 3));
     g.insert(1, 2);
     EXPECT_TRUE(g.contains(1));
     EXPECT_TRUE(g.contains(2));
     EXPECT_FALSE(g.contains(3));
     EXPECT_TRUE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_FALSE(g.contains(2, 3));
     EXPECT_FALSE(g.reaches(1, 1));
     EXPECT_TRUE(g.reaches(1, 2));
     EXPECT_FALSE(g.reaches(1, 3));
     EXPECT_FALSE(g.reaches(2, 1));
     EXPECT_FALSE(g.reaches(2, 2));
     EXPECT_FALSE(g.reaches(2, 3));
     EXPECT_FALSE(g.reaches(3, 1));
     EXPECT_FALSE(g.reaches(3, 2));
     EXPECT_FALSE(g.reaches(3, 3));
     g.insert(2, 3);
     EXPECT_TRUE(g.contains(1));
     EXPECT_TRUE(g.contains(2));
     EXPECT_TRUE(g.contains(3));
     EXPECT_TRUE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_TRUE(g.contains(2, 3));
     EXPECT_FALSE(g.reaches(1, 1));
     EXPECT_TRUE(g.reaches(1, 2));
     EXPECT_TRUE(g.reaches(1, 3));
     EXPECT_FALSE(g.reaches(2, 1));
     EXPECT_FALSE(g.reaches(2, 2));
     EXPECT_TRUE(g.reaches(2, 3));
     EXPECT_FALSE(g.reaches(3, 1));
     EXPECT_FALSE(g.reaches(3, 2));
     EXPECT_FALSE(g.reaches(3, 3));
     g.insert(3, 1);
     EXPECT_TRUE(g.contains(1));
     EXPECT_TRUE(g.contains(2));
     EXPECT_TRUE(g.contains(3));
     EXPECT_TRUE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_TRUE(g.contains(2, 3));
     EXPECT_TRUE(g.reaches(1, 1));
     EXPECT_TRUE(g.reaches(1, 2));
     EXPECT_TRUE(g.reaches(1, 3));
     EXPECT_TRUE(g.reaches(2, 1));
     EXPECT_TRUE(g.reaches(2, 2));
     EXPECT_TRUE(g.reaches(2, 3));
     EXPECT_TRUE(g.reaches(3, 1));
     EXPECT_TRUE(g.reaches(3, 2));
     EXPECT_TRUE(g.reaches(3, 3));
     EXPECT_EQ("{1->2,2->3,3->1}", toString(g));
 }
TEST() [4/84]
souffle::test::TEST (Relation0 , Construction)
Definition at line 32 of file interpreter_relation_test.cpp.
References EXPECT_EQ, and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
Referenced by TEST().
{
     // create a nullary relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(0);
     InterpreterRelation rel(0, 0, "test", {}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {}, {}, 0);
     // add some values
     EXPECT_EQ(0, rel.size());
     relInt.insert(tuple(&relInt, {}));
     EXPECT_EQ(1, rel.size());
     relInt.insert(tuple(&relInt, {}));
     EXPECT_EQ(1, rel.size());
 }
TEST() [5/84]
souffle::test::TEST (Pack , Tuple)
Definition at line 35 of file record_table_test.cpp.
References EXPECT_EQ, i, souffle::pack(), and souffle::RecordTable::unpack().
                   {
     RecordTable recordTable;
     const Tuple<RamDomain, 3> tuple = {{1, 2, 3}};
     RamDomain ref = pack(recordTable, tuple);
     const RamDomain* ptr = recordTable.unpack(ref, 3);
     for (size_t i = 0; i < 3; ++i) {
         EXPECT_EQ(tuple[i], ptr[i]);
     }
 }
TEST() [6/84]
souffle::test::TEST (Table , Basic)
Definition at line 36 of file table_test.cpp.
References count(), souffle::Table< T, blockSize >::empty(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::Table< T, blockSize >::insert(), and souffle::Table< T, blockSize >::size().
                    {
     Table<int> table;
     EXPECT_TRUE(table.empty());
     EXPECT_EQ(0, table.size());
     EXPECT_EQ(0, count(table));
     table.insert(1);
     EXPECT_FALSE(table.empty());
     EXPECT_EQ(1, table.size());
     EXPECT_EQ(1, count(table));
 }
TEST() [7/84]
souffle::test::TEST (EqRelTest , Scoping)
Definition at line 40 of file binary_relation_test.cpp.
{
     // simply test that namespaces were setup correctly
     souffle::EquivalenceRelation<souffle::Tuple<RamDomain, 2>> br;
 }
TEST() [8/84]
souffle::test::TEST (ParallelUtils , ReadWriteLock)
Definition at line 43 of file parallel_utils_test.cpp.
References souffle::ReadWriteLock::end_read(), souffle::ReadWriteLock::end_write(), EXPECT_EQ, i, souffle::ReadWriteLock::start_read(), and souffle::ReadWriteLock::start_write().
{
     const int N = 1000000;
     const int K = 10;
     ReadWriteLock lock;
     volatile int c = 0;
 #pragma omp parallel for num_threads(4)
     for (int i = 0; i < N; i++) {
         if (i % K == 0) {  // 10% write probability
             lock.start_write();
             c++;
             lock.end_write();
         } else {
             lock.start_read();
             // nothing to do here ..
             lock.end_read();
         }
     }
     EXPECT_EQ(N / K, c);
 }
TEST() [9/84]
souffle::test::TEST (RandomInsertPiggyTest , Scoping)
Piggy List that allows creation at arbitrary elements.
Definition at line 43 of file eqrel_datastructure_test.cpp.
{
     // simply test that namespaces were setup correctly (compile time)
     souffle::RandomInsertPiggyList<size_t> pl;
 }
TEST() [10/84]
souffle::test::TEST (SymbolTable , Copy)
Definition at line 44 of file symbol_table_test.cpp.
References b, EXPECT_EQ, and EXPECT_STREQ.
{
     auto* a = new SymbolTable();
     a->insert("Hello");
     auto* b = new SymbolTable(*a);
     size_t a_idx = a->lookup("Hello");
     size_t b_idx = b->lookup("Hello");
     // hash should be the same
     EXPECT_EQ(a_idx, b_idx);
     EXPECT_STREQ("Hello", a->resolve(a_idx));
     EXPECT_STREQ("Hello", b->resolve(b_idx));
     // should be the same actual string
     EXPECT_STREQ(a->resolve(a_idx), b->resolve(b_idx));
     // b should survive
     delete a;
     EXPECT_STREQ("Hello", b->resolve(b_idx));
     delete b;
 }
TEST() [11/84]
souffle::test::TEST (EqRelTest , Basic)
Definition at line 47 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     // empty bin rel should be exactly that
     EXPECT_EQ(br.size(), 0);
     EXPECT_FALSE(br.contains(1, 2));
     EXPECT_FALSE(br.contains(0, 0));
     // test implicit rules
     br.insert(1, 2);
     EXPECT_EQ(br.size(), 4);
     EXPECT_TRUE(br.contains(1, 2));
     EXPECT_TRUE(br.contains(2, 1));
     EXPECT_TRUE(br.contains(1, 1));
     EXPECT_TRUE(br.contains(2, 2));
     // test insert of exactly one pair
     br.insert(3, 3);
     EXPECT_EQ(br.size(), 5);
     EXPECT_TRUE(br.contains(3, 3));
     EXPECT_FALSE(br.contains(1, 3));
     EXPECT_FALSE(br.contains(3, 2));
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [12/84]
souffle::test::TEST (Relation1 , Construction)
Definition at line 48 of file interpreter_relation_test.cpp.
References EXPECT_EQ, and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a single attribute relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     tuple d1(&relInt, {1});
     // add some values
     EXPECT_EQ(0, rel.size());
     relInt.insert(d1);
     EXPECT_EQ(1, rel.size());
     relInt.insert(tuple(&relInt, {2}));
     EXPECT_EQ(2, rel.size());
     relInt.insert(tuple(&relInt, {3}));
     EXPECT_EQ(3, rel.size());
     relInt.insert(tuple(&relInt, {4}));
     EXPECT_EQ(4, rel.size());
 }
TEST() [13/84]
souffle::test::TEST (RandomInsertPiggyTest , Insertion)
Definition at line 48 of file eqrel_datastructure_test.cpp.
References EXPECT_EQ, souffle::RandomInsertPiggyList< T >::get(), souffle::RandomInsertPiggyList< T >::insertAt(), and souffle::RandomInsertPiggyList< T >::size().
{
     // insert a bunch of stuff and check the size is valid?
     souffle::RandomInsertPiggyList<size_t> pl;
     EXPECT_EQ(pl.size(), 0);
     pl.insertAt(0, 99);
     EXPECT_EQ(pl.get(0), 99);
     EXPECT_EQ(pl.size(), 1);
     pl.insertAt(1000, 33);
     EXPECT_EQ(pl.get(1000), 33);
     EXPECT_EQ(pl.size(), 2);
 }
TEST() [14/84]
souffle::test::TEST (Table , Stress)
Definition at line 49 of file table_test.cpp.
References EXPECT_EQ, i, souffle::Table< T, blockSize >::insert(), j, and souffle::Table< T, blockSize >::size().
                     {
     for (int i = 0; i < 10000; ++i) {
         Table<int> table;
         for (int j = 0; j < i; ++j) {
             table.insert(j);
         }
         EXPECT_EQ((size_t)i, table.size());
         int last = -1;
         for (const auto& cur : table) {
             EXPECT_EQ(last + 1, cur);
             last = cur;
         }
         EXPECT_EQ(last + 1, i);
     }
 }
TEST() [15/84]
souffle::test::TEST (PackUnpack , Tuple)
Definition at line 51 of file record_table_test.cpp.
References EXPECT_EQ, i, NUMBER_OF_TESTS, souffle::pack(), and souffle::RecordTable::unpack().
{
     constexpr size_t tupleSize = 3;
     using tupleType = Tuple<RamDomain, tupleSize>;
     RecordTable recordTable;
     // Setup random number generation
     std::default_random_engine randomGenerator(3);
     std::uniform_int_distribution<RamDomain> distribution(
             std::numeric_limits<RamDomain>::lowest(), std::numeric_limits<RamDomain>::max());
     auto random = std::bind(distribution, randomGenerator);
     // Tuples that will be packed
     std::vector<tupleType> toPack(NUMBER_OF_TESTS);
     // Tuple reference after they are packed.
     std::vector<RamDomain> tupleRef(NUMBER_OF_TESTS);
     // Generate and pack the tuples
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         toPack[i] = {{random(), random(), random()}};
         tupleRef[i] = pack(recordTable, toPack[i]);
     }
     // unpack and test
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         auto unpacked = recordTable.unpack(tupleRef[i], tupleSize);
         tupleType cmp = {unpacked[0], unpacked[1], unpacked[2]};
         EXPECT_EQ(toPack[i], cmp);
     }
 }
TEST() [16/84]
souffle::test::TEST (BTreeMultiSet , Basic)
Definition at line 56 of file btree_multiset_test.cpp.
References DEBUG, EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
{
     const bool DEBUG = false;
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(3, test_set::max_keys_per_node);
     // check initial conditions
     EXPECT_EQ(0u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_FALSE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(0, t.getDepth());
     EXPECT_EQ(0, t.getNumNodes());
     if (DEBUG) t.printTree();
     // add an element
     t.insert(12);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(1u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a larger element
     t.insert(14);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(2u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a smaller element
     t.insert(10);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(3u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // cause a split
     t.insert(11);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(4u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(11));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(12);
     EXPECT_EQ(5u, t.size());
     t.insert(12);
     EXPECT_EQ(6u, t.size());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(15);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(16);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
 }
TEST() [17/84]
souffle::test::TEST (BTreeSet , Basic)
Definition at line 60 of file btree_set_test.cpp.
References DEBUG, EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
                       {
     const bool DEBUG = false;
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(3, test_set::max_keys_per_node);
     // check initial conditions
     EXPECT_EQ(0u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_FALSE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(0, t.getDepth());
     EXPECT_EQ(0, t.getNumNodes());
     if (DEBUG) t.printTree();
     // add an element
     t.insert(12);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(1u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a larger element
     t.insert(14);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(2u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a smaller element
     t.insert(10);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(3u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // cause a split
     t.insert(11);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(4u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(11));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(4u, t.size());
     t.insert(12);
     EXPECT_EQ(4u, t.size());
     t.insert(12);
     EXPECT_EQ(4u, t.size());
     t.insert(10);
     EXPECT_EQ(4u, t.size());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(15);
     EXPECT_EQ(5u, t.size());
     EXPECT_EQ(2, t.getDepth());
     EXPECT_EQ(3, t.getNumNodes());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(16);
     EXPECT_EQ(6u, t.size());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
 }
TEST() [18/84]
souffle::test::TEST (RandomInsertPiggyTest , DoubleClear)
Definition at line 62 of file eqrel_datastructure_test.cpp.
References souffle::RandomInsertPiggyList< T >::clear(), EXPECT_EQ, souffle::RandomInsertPiggyList< T >::get(), i, souffle::RandomInsertPiggyList< T >::insertAt(), souffle::RandomInsertPiggyList< T >::size(), and TEST().
{
     // err.. prior versions have had the bug where clear caused double-free errors (as we don't set the
     // container to null) This should *crash* the test-suite if this is the case, but I also try to check the
     // contents here
     souffle::RandomInsertPiggyList<size_t> pl;
     pl.insertAt(0, 3213);
     pl.insertAt(1, 3213);
     pl.insertAt(2, 3213);
     pl.insertAt(3, 3213);
     EXPECT_EQ(pl.size(), 4);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.insertAt(0, 1);
     EXPECT_EQ(pl.size(), 1);
 }
TEST() [19/84]
souffle::test::TEST (ParallelUtils , OptimisticReadWriteLock)
Definition at line 67 of file parallel_utils_test.cpp.
References souffle::OptimisticReadWriteLock::end_read(), souffle::OptimisticReadWriteLock::end_write(), EXPECT_EQ, EXPECT_TRUE, i, souffle::OptimisticReadWriteLock::start_read(), and souffle::OptimisticReadWriteLock::start_write().
{
     const int N = 1000000;
     const int K = 10;
     OptimisticReadWriteLock lock;
     volatile int c = 0;
 #pragma omp parallel for num_threads(4)
     for (int i = 0; i < N; i++) {
         if (i % K == 0) {  // 10% write probability
             lock.start_write();
             c++;
             c++;
             lock.end_write();
         } else {
             bool succ = false;
             do {
                 auto lease = lock.start_read();
                 // nothing to do here ..
                 int x = c;
                 succ = lock.end_read(lease);
                 EXPECT_TRUE((x % 2 == 0) || !succ);
             } while (!succ);
         }
     }
     EXPECT_EQ(2 * (N / K), c);
 }
TEST() [20/84]
souffle::test::TEST (SymbolTable , Assign)
Definition at line 69 of file symbol_table_test.cpp.
References b, EXPECT_EQ, EXPECT_STREQ, souffle::SymbolTable::lookup(), and souffle::SymbolTable::resolve().
{
     auto* a = new SymbolTable();
     a->insert("Hello");
     SymbolTable b = *a;
     SymbolTable c;
     c = *a;
     size_t a_idx = a->lookup("Hello");
     size_t b_idx = b.lookup("Hello");
     size_t c_idx = c.lookup("Hello");
     // hash should be the same
     EXPECT_EQ(a_idx, b_idx);
     EXPECT_EQ(b_idx, c_idx);
     EXPECT_STREQ("Hello", a->resolve(a_idx));
     EXPECT_STREQ("Hello", b.resolve(b_idx));
     EXPECT_STREQ("Hello", c.resolve(c_idx));
     // b and c should survive
     delete a;
     EXPECT_STREQ("Hello", b.resolve(b_idx));
     EXPECT_STREQ("Hello", c.resolve(c_idx));
 }
TEST() [21/84]
souffle::test::TEST (Basic , Iteration)
Definition at line 69 of file interpreter_relation_test.cpp.
References count(), EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add some values
     relInt.insert(tuple(&relInt, {1}));
     relInt.insert(tuple(&relInt, {2}));
     relInt.insert(tuple(&relInt, {3}));
     relInt.insert(tuple(&relInt, {4}));
     // Iterate
     Relation::iterator it = relInt.begin();
     std::size_t count = 0;
     while (it != relInt.end()) {
         // Check the 'deref' doesn't crash
         auto value = (*it)[0];
         (void)value;
         ++it;
         ++count;
     }
     EXPECT_EQ(4, count);
 }
TEST() [22/84]
souffle::test::TEST (EqRelTest , Clear)
Definition at line 76 of file binary_relation_test.cpp.
References count(), EXPECT_EQ, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     br.insert(0, 44);
     br.insert(0, 1);
     EXPECT_EQ(9, br.size());
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     br.clear();
     EXPECT_EQ(0, br.size());
     count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [23/84]
souffle::test::TEST (PackUnpack , Vector)
Definition at line 87 of file record_table_test.cpp.
References EXPECT_EQ, i, j, NUMBER_OF_TESTS, souffle::RecordTable::pack(), and souffle::RecordTable::unpack().
{
     constexpr size_t vectorSize = 10;
     RecordTable recordTable;
     // Tuples that will be packed
     std::vector<std::vector<RamDomain>> toPack(NUMBER_OF_TESTS);
     // Tuple reference after they are packed.
     std::vector<RamDomain> tupleRef(NUMBER_OF_TESTS);
     // Generate and pack the tuples
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         toPack[i] = testutil::generateRandomVector<RamDomain>(10);
         tupleRef[i] = recordTable.pack(toPack[i].data(), vectorSize);
         std::cerr << "Ref: " << tupleRef[i] << std::endl;
     }
     // unpack and test
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         const RamDomain* unpacked{recordTable.unpack(tupleRef[i], vectorSize)};
         for (size_t j = 0; j < vectorSize; ++j) {
             EXPECT_EQ(toPack[i][j], unpacked[j]);
         }
     }
 }
TEST() [24/84]
souffle::test::TEST (Independence , Iteration)
Definition at line 96 of file interpreter_relation_test.cpp.
References EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     // Test a iterator returns the correct value
     Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Copy the iterator and modify the copy
     {
         Relation::iterator it2(it);
         EXPECT_EQ(1, (*it2)[0]);
         ++it2;
     }
     EXPECT_EQ(1, (*it)[0]);
     // Test that a new iterator is also valid
     Relation::iterator it3 = relInt.begin();
     EXPECT_EQ(1, (*it3)[0]);
 }
TEST() [25/84]
souffle::test::TEST (SymbolTable , Inserts)
Definition at line 96 of file symbol_table_test.cpp.
References souffle::duration_in_ns(), i, souffle::SymbolTable::insert(), n, and now().
{
     // whether to print the recorded times to stdout
     // should be false unless developing
     const bool ECHO_TIME = false;
     // type for very big number
     using T = unsigned long long;
     time_point start;
     time_point end;
     T n = 0;        // counter
     T N = 1000000;  // number of symbols to insert
     // T N = 10000000;   // larger tables for debugging/timing
     // T N = 100000000;  // larger tables for debugging/timing
     SymbolTable X;
     std::string x;
     std::vector<std::string> A;
     A.reserve(N);
     for (T i = 0; i < N; ++i) {
         x = std::to_string(i) + "string";
         A.push_back(x);
     }
     start = now();
     for (T i = 0; i < N; ++i) {
         X.insert(A[i]);  // insert one at a time
     }
     end = now();
     n = duration_in_ns(start, end);  // record the time
     if (ECHO_TIME) {
         std::cout << "Time to insert " << N << " new elements:      " << n << " ns" << std::endl;
     }
     // try inserting all the elements that were just inserted
     start = now();
     X.insert(A);
     end = now();
     n = duration_in_ns(start, end);
     if (ECHO_TIME) {
         std::cout << "Time to insert " << N << " existing elements: " << n << " ns" << std::endl;
     }
 }
TEST() [26/84]
souffle::test::TEST (EqRelTest , Duplicates)
Definition at line 98 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::begin(), souffle::EquivalenceRelation< TupleType >::contains(), souffle::EquivalenceRelation< TupleType >::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, i, souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     // test inserting same pair
     for (int i = 0; i < 10; ++i) {
         br.insert(0, 0);
     }
     EXPECT_EQ(br.size(), 1);
     for (int i = 0; i < 10; ++i) {
         EXPECT_TRUE(br.contains(0, 0));
     }
     EXPECT_EQ(br.size(), 1);
     EXPECT_FALSE(br.contains(1, 1));
     // check iteration of duplicate is fine
     Tuple<RamDomain, 2> tup{};
     tup[0] = 0;
     tup[1] = 0;
     auto x = br.begin();
     EXPECT_EQ(tup, *x);
     ++x;
     EXPECT_EQ(x, br.end());
 }
TEST() [27/84]
souffle::test::TEST (PiggyTest , Scoping)
Regular Old Piggy List.
Definition at line 99 of file eqrel_datastructure_test.cpp.
{
     // simply test that namespaces were setup correctly (compile time)
     souffle::PiggyList<size_t> pl;
 }
TEST() [28/84]
souffle::test::TEST (PiggyTest , Append)
Definition at line 104 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), EXPECT_EQ, souffle::PiggyList< T >::get(), i, and souffle::PiggyList< T >::size().
{
     souffle::PiggyList<size_t> pl;
     EXPECT_EQ(pl.size(), 0);
     pl.append(99);
     EXPECT_EQ(pl.size(), 1);
     pl.append(99);
     pl.append(99);
     EXPECT_EQ(pl.size(), 3);
     EXPECT_EQ(pl.get(0), 99);
     EXPECT_EQ(pl.get(1), 99);
     EXPECT_EQ(pl.get(2), 99);
     // larger than BLOCKSIZE
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         pl.append(2);
     }
     EXPECT_EQ(pl.size(), N + 3);
     // make sure that all of our inserties are exacties
     for (size_t i = 3; i < N + 3; ++i) {
         EXPECT_EQ(pl.get(i), 2);
     }
 }
TEST() [29/84]
souffle::test::TEST (EqRelTest , TransitivityTest)
Definition at line 122 of file binary_relation_test.cpp.
References count(), EXPECT_EQ, EXPECT_TRUE, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test (a,b) && (b, c) => (a,c) etc
     EqRel br;
     br.insert(1, 2);
     br.insert(2, 3);
     EXPECT_EQ(br.size(), 9);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     EXPECT_TRUE(br.contains(1, 1));
     EXPECT_TRUE(br.contains(1, 2));
     EXPECT_TRUE(br.contains(1, 3));
     EXPECT_TRUE(br.contains(2, 1));
     EXPECT_TRUE(br.contains(2, 2));
     EXPECT_TRUE(br.contains(2, 3));
     EXPECT_TRUE(br.contains(3, 1));
     EXPECT_TRUE(br.contains(3, 2));
     EXPECT_TRUE(br.contains(3, 3));
 }
TEST() [30/84]
souffle::test::TEST (IndependentMoving , Iteration)
Definition at line 124 of file interpreter_relation_test.cpp.
References EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Make a new iterator, move it to the first iterator, then let the new iterator go out of scope
     {
         Relation::iterator it2(relInt.begin());
         EXPECT_EQ(1, (*it2)[0]);
         it = std::move(it2);
     }
     EXPECT_EQ(1, (*it)[0]);
 }
TEST() [31/84]
souffle::test::TEST (PiggyTest , ElementCreation)
Definition at line 129 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::createNode(), EXPECT_EQ, souffle::PiggyList< T >::get(), and souffle::PiggyList< T >::size().
{
     // test that we can use makeNode() and set the values properly
     souffle::PiggyList<size_t> pl;
     pl.get(pl.createNode()) = 99;
     EXPECT_EQ(pl.size(), 1);
     EXPECT_EQ(pl.get(0), 99);
 }
TEST() [32/84]
souffle::test::TEST (PiggyTest , Iteration)
Definition at line 137 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), e, EXPECT_EQ, and i.
{
     souffle::PiggyList<size_t> pl;
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         pl.append(i);
     }
     size_t counter = 0;
     for (size_t e : pl) {
         EXPECT_EQ(e, counter++);
     }
 }
TEST() [33/84]
souffle::test::TEST (EqRelTest , PairwiseIncremental)
Definition at line 145 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_TRUE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     const size_t N = 100;
     // test inserting ascending pairs still isolates them
     for (size_t i = 1; i < N; ++i) {
         br.insert(i, i);
         EXPECT_TRUE(br.contains(i, i));
         br.insert(i + (N + 1), i);
         EXPECT_TRUE(br.contains(i, i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i));
     }
     EXPECT_EQ(br.size(), (N - 1) * 4);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [34/84]
souffle::test::TEST (IndependentCopying , Iteration)
Definition at line 147 of file interpreter_relation_test.cpp.
References EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::ram::analysis::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Make a new iterator, copy it to the first iterator, then let the new iterator go out of scope
     {
         Relation::iterator it2(relInt.begin());
         EXPECT_EQ(1, (*it2)[0]);
         it = it2;
     }
     EXPECT_EQ(1, (*it)[0]);
 }
TEST() [35/84]
souffle::test::TEST (PiggyTest , CopyCtor)
Definition at line 149 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), souffle::PiggyList< T >::begin(), souffle::PiggyList< T >::clear(), souffle::PiggyList< T >::end(), EXPECT_EQ, EXPECT_FALSE, souffle::PiggyList< T >::get(), i, and souffle::PiggyList< T >::size().
{
     souffle::PiggyList<size_t> pl;
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         pl.append(i);
     }
     souffle::PiggyList<size_t> pl2(pl);
     EXPECT_EQ(pl.size(), pl2.size());
     // check every element is equal and same order
     for (size_t i = 0; i < N; ++i) {
         EXPECT_EQ(pl.get(i), pl2.get(i));
         EXPECT_EQ(pl.get(i), i);
     }
     auto pl1It = pl.begin();
     auto pl2It = pl2.begin();
     while (true) {
         // yep, they both finished at the same time
         if (pl1It == pl.end() && pl2It == pl2.end()) {
             break;
         }
         // uhoh, they didn't both finish at the same time
         if (pl1It == pl.end() || pl2It == pl2.end()) {
             EXPECT_FALSE(true && "whoops, looks like the iterators are broken");
         }
         EXPECT_EQ(*pl1It, *pl2It);
         ++pl1It;
         ++pl2It;
     }
     // change contents of pl1 and makesure they don't change in pl2
     pl.get(2) = 99;
     EXPECT_EQ(pl.get(2), 99);
     EXPECT_EQ(pl2.get(2), 2);
     // check clearing one doesn't invalidate the other
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     EXPECT_EQ(pl2.size(), N);
     pl2.clear();
     EXPECT_EQ(pl.size(), 0);
     EXPECT_EQ(pl2.size(), 0);
 }
TEST() [36/84]
souffle::test::TEST (BTreeMultiSet , Duplicates)
Definition at line 157 of file btree_multiset_test.cpp.
References EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(0);
     }
     EXPECT_EQ(10, t.size());
     std::vector<int> data(t.begin(), t.end());
     EXPECT_EQ(10, data.size());
     for (int i = 0; i < 10; i++) {
         EXPECT_EQ(0, data[i]);
     }
 }
TEST() [37/84]
souffle::test::TEST (EqRelTest , PairwiseDecremental)
Definition at line 167 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_TRUE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     const size_t N = 100;
     // test inserting descending pairs still isolates them
     for (size_t i = N; i > 1; --i) {
         br.insert(i, i);
         EXPECT_TRUE(br.contains(i, i));
         br.insert(i + (N + 1), i);
         EXPECT_TRUE(br.contains(i, i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i));
     }
     EXPECT_EQ(br.size(), (N - 1) * 4);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [38/84]
souffle::test::TEST (BTreeSet , Duplicates)
Definition at line 170 of file btree_set_test.cpp.
References EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(0);
     }
     EXPECT_EQ(1, t.size());
     EXPECT_EQ(0, *t.begin());
     //        t.printTree();
 }
TEST() [39/84]
souffle::test::TEST (BTreeMultiSet , Incremental)
Definition at line 171 of file btree_multiset_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = 0; i < N; i++) {
         t.insert(i);
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j <= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
 }
TEST() [40/84]
souffle::test::TEST (BTreeMultiSet , Decremental)
Definition at line 183 of file btree_multiset_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = N; i >= 0; i--) {
         t.insert(i);
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j >= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
 }
TEST() [41/84]
souffle::test::TEST (BTreeSet , Incremental)
Definition at line 186 of file btree_set_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = 0; i < N; i++) {
         //        std::cout << "\nBefore:\n";
         //        t.printTree();
         //        std::cout << "\n";
         t.insert(i);
         //        std::cout << "\nAfter:\n";
         //        std::cout << "\n";
         //        t.printTree();
         //        std::cout << "\n";
         //        std::cout << "\n\n";
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j <= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
     t.printStats();
 }
TEST() [42/84]
souffle::test::TEST (EqRelTest , Shuffled)
Definition at line 190 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_TRUE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     size_t N = 100;
     // test inserting data "out of order" keeps isolation
     std::vector<int> data;
     for (size_t i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (auto x : data) {
         br.insert(x, x);
     }
     for (size_t i = 0; i < N; ++i) {
         EXPECT_TRUE(br.contains(i, i));
     }
     EXPECT_EQ(br.size(), N);
     // always check the iterator for size too
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [43/84]
souffle::test::TEST (BTreeMultiSet , Shuffled)
Definition at line 195 of file btree_multiset_test.cpp.
References EXPECT_TRUE, and i.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 10000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         t.insert(data[i]);
     }
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.contains(i)) << "i=" << i;
     }
 }
TEST() [44/84]
souffle::test::TEST (PiggyTest , DoubleClear)
Definition at line 199 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), souffle::PiggyList< T >::clear(), souffle::PiggyList< T >::createNode(), e, EXPECT_EQ, EXPECT_TRUE, souffle::PiggyList< T >::get(), i, souffle::PiggyList< T >::size(), and TEST().
{
     // err.. prior versions have had the bug where clear caused double-free errors (as we don't set the
     // container to null) This should *crash* the test-suite if this is the case, but I also try to check the
     // contents here
     souffle::PiggyList<size_t> pl;
     pl.append(3213);
     pl.append(3213);
     pl.append(3213);
     pl.append(3213);
     EXPECT_EQ(pl.size(), 4);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.append(1);
     EXPECT_EQ(pl.size(), 1);
 }
TEST() [45/84]
souffle::test::TEST (BTreeSet , Decremental)
Definition at line 212 of file btree_set_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = N; i >= 0; i--) {
         //            std::cout << "\nBefore:\n";
         //            t.printTree();
         //            std::cout << "\n";
         t.insert(i);
         //            std::cout << "\nAfter:\n";
         //            t.printTree();
         //            std::cout << "\n";
         //            std::cout << "\n\n";
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j >= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
 }
TEST() [46/84]
souffle::test::TEST (BTreeMultiSet , IteratorEmpty)
Definition at line 220 of file btree_multiset_test.cpp.
References EXPECT_EQ.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.begin(), t.end());
 }
TEST() [47/84]
souffle::test::TEST (EqRelTest , Extend)
Definition at line 223 of file binary_relation_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test running extend for a relation
     // br is {{0,1,2,3,4,5,6}, {8,9}, {44, 70}, {11}}
     EqRel br;
     br.insert(0, 1);
     br.insert(0, 2);
     br.insert(0, 3);
     br.insert(0, 4);
     br.insert(0, 5);
     br.insert(0, 6);
     br.insert(8, 9);
     br.insert(44, 70);
     br.insert(11, 11);
     EXPECT_EQ(br.size(), (7 * 7) + (2 * 2) + (2 * 2) + (1 * 1));
     // br2 is {{0,8,33,99}, {68,69,70}, {101, 102}}
     EqRel br2;
     br2.insert(33, 8);
     br2.insert(33, 99);
     br2.insert(33, 0);
     br2.insert(69, 68);
     br2.insert(69, 70);
     br2.insert(101, 102);
     EXPECT_EQ(br2.size(), (4 * 4) + (3 * 3) + (2 * 2));
     // let's say br2 the new knowledge, so we must extend it to actually contain the implied knowledge from
     // new
     br2.extend(br);
     // it should contain {0,1,2,3,4,5,6,8,9,33,99}, {44, 68, 69, 70}, {101, 102}
     // shouldn't contain {11}.
     EXPECT_TRUE(br2.contains(0, 0));
     EXPECT_TRUE(br2.contains(0, 1));
     EXPECT_TRUE(br2.contains(1, 8));
     EXPECT_TRUE(br2.contains(9, 4));
     EXPECT_TRUE(br2.contains(33, 4));
     EXPECT_TRUE(br2.contains(33, 99));
     EXPECT_TRUE(br2.contains(68, 69));
     EXPECT_TRUE(br2.contains(70, 44));
     EXPECT_FALSE(br2.contains(11, 11));
     EXPECT_FALSE(br2.contains(0, 69));
     EXPECT_TRUE(br2.contains(101, 102));
     // check this hasn't changed size
     EXPECT_EQ(br.size(), (7 * 7) + (2 * 2) + (2 * 2) + (1 * 1));
     // check that it was properly extended
     EXPECT_EQ(br2.size(), (11 * 11) + (4 * 4) + (2 * 2));
 }
TEST() [48/84]
souffle::test::TEST (BTreeMultiSet , IteratorBasic)
Definition at line 227 of file btree_multiset_test.cpp.
References e, EXPECT_EQ, EXPECT_NE, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     //        t.printTree();
     auto it = t.begin();
     auto e = t.end();
     EXPECT_NE(it, e);
     int last = -1;
     for (int i : t) {
         EXPECT_EQ(last + 1, i);
         last = i;
     }
     EXPECT_EQ(last, 9);
 }
TEST() [49/84]
souffle::test::TEST (BTreeSet , Shuffled)
Definition at line 235 of file btree_set_test.cpp.
References EXPECT_TRUE, and i.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 10000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         t.insert(data[i]);
     }
     //        t.printTree();
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.contains(i)) << "i=" << i;
     }
 }
TEST() [50/84]
souffle::test::TEST (BTreeMultiSet , IteratorStress)
Definition at line 250 of file btree_multiset_test.cpp.
References EXPECT_EQ, EXPECT_LT, and i.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         EXPECT_EQ((size_t)i, t.size());
         int last = -1;
         for (int i : t) {
             EXPECT_LT(last, i);
             last = i;
         }
         t.insert(data[i]);
     }
 }
TEST() [51/84]
souffle::test::TEST (DjTest , Scoping)
The underlying Disjoint Set (essentially Anderson '91 Find-Union, but dynamic)
Definition at line 259 of file eqrel_datastructure_test.cpp.
                       {
     souffle::DisjointSet ds;
 }
TEST() [52/84]
souffle::test::TEST (BTreeSet , Copy)
Definition at line 262 of file btree_set_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_NE, EXPECT_TRUE, and i.
                      {
     using test_set = btree_set<int>;
     test_set t;
     int N = 100000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         t.insert(data[i]);
     }
     EXPECT_EQ((size_t)N, t.size());
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.find(i) != t.end()) << "i=" << i;
     }
     test_set t2;
     EXPECT_EQ((size_t)N, t.size());
     EXPECT_EQ(0, t2.size());
     t2 = t;
     EXPECT_EQ((size_t)N, t.size());
     EXPECT_EQ((size_t)N, t2.size());
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.find(i) != t.end()) << "i=" << i;
     }
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t2.find(i) != t2.end()) << "i=" << i;
     }
     EXPECT_FALSE(t.find(N + 1) != t.end());
     EXPECT_FALSE(t2.find(N + 1) != t2.end());
     t2.insert(N + 1);
     EXPECT_FALSE(t.find(N + 1) != t.end());
     EXPECT_TRUE(t2.find(N + 1) != t2.end());
     for (int i = 0; i < N; i++) {
         EXPECT_NE(&*t.find(i), &*t2.find(i)) << "i=" << i;
     }
 }
TEST() [53/84]
souffle::test::TEST (DjTest , MakeNode)
Definition at line 263 of file eqrel_datastructure_test.cpp.
References souffle::DisjointSet::b2p(), souffle::DisjointSet::b2r(), EXPECT_EQ, souffle::DisjointSet::makeNode(), n, and souffle::DisjointSet::size().
{
     souffle::DisjointSet ds;
     EXPECT_EQ(ds.size(), 0);
     souffle::block_t n = ds.makeNode();
     // parent should be itself
     EXPECT_EQ(DisjointSet::b2p(n), 0);
     // rank should be 0
     EXPECT_EQ(DisjointSet::b2r(n), 0);
     EXPECT_EQ(ds.size(), 1);
     souffle::block_t n2 = ds.makeNode();
     // parent should be itself
     EXPECT_EQ(DisjointSet::b2p(n2), 1);
     // rank should be 0
     EXPECT_EQ(DisjointSet::b2r(n2), 0);
     EXPECT_EQ(ds.size(), 2);
 }
TEST() [54/84]
souffle::test::TEST (BTreeMultiSet , BoundaryTest)
Definition at line 279 of file btree_multiset_test.cpp.
References b, EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     //        t.printTree();
     auto a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     auto b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // add duplicates
     t.insert(5);
     t.insert(5);
     t.insert(5);
     //        t.printTree(); std::cout << "\n";
     // test again ..
     a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // check the distance
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(6, *a);
 }
TEST() [55/84]
souffle::test::TEST (DjTest , TestUnion)
Definition at line 281 of file eqrel_datastructure_test.cpp.
References souffle::DisjointSet::b2p(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::DisjointSet::makeNode(), souffle::DisjointSet::sameSet(), souffle::DisjointSet::size(), and souffle::DisjointSet::unionNodes().
{
     // check whether the unioning works to see if the elements are properly in the same set
     souffle::DisjointSet ds;
     parent_t n1 = DisjointSet::b2p(ds.makeNode());
     parent_t n2 = DisjointSet::b2p(ds.makeNode());
     parent_t n3 = DisjointSet::b2p(ds.makeNode());
     parent_t n4 = DisjointSet::b2p(ds.makeNode());
     parent_t n5 = DisjointSet::b2p(ds.makeNode());
     EXPECT_EQ(ds.size(), 5);
     // test running same set doesn't accidentally union them
     EXPECT_FALSE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n1, n2));
     ds.unionNodes(n1, n2);
     EXPECT_TRUE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n3, n2));
     ds.unionNodes(n3, n4);
     ds.unionNodes(n3, n5);
     ds.unionNodes(n1, n5);
     // ensure that nodes that weren't explicitly connected are in fact connected
     EXPECT_TRUE(ds.sameSet(n1, n4));
     // and their symmetric
     EXPECT_TRUE(ds.sameSet(n4, n1));
     // size shouldn't change
     EXPECT_EQ(ds.size(), 5);
 }
TEST() [56/84]
souffle::test::TEST (EqRelTest , Merge)
Definition at line 282 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::begin(), souffle::EquivalenceRelation< TupleType >::clear(), count(), souffle::EquivalenceRelation< TupleType >::end(), EXPECT_EQ, EXPECT_FALSE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test insertAll isolates data
     EqRel br;
     int N = 100;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         br.insert(data[i], data[i]);
     }
     // also insert a joint pair
     br.insert(N - 1, N + 1);
     EXPECT_EQ((size_t)N + 3, br.size());
     EqRel br2;
     EXPECT_EQ(0, br2.size());
     size_t count = 0;
     for (auto x : br2) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br2.size());
     br2.insertAll(br);
     EXPECT_EQ((size_t)N + 3, br2.size());
     EXPECT_EQ((size_t)N + 3, br.size());
     count = 0;
     for (auto x : br2) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br2.size());
     br.clear();
     EXPECT_EQ((size_t)N + 3, br2.size());
     EXPECT_EQ(0, br.size());
     EXPECT_FALSE(br.begin() != br.end());
     count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     br2.clear();
     EXPECT_EQ(0, br2.size());
     EXPECT_EQ(0, br.size());
     count = 0;
     for (auto x : br2) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br2.size());
 }
TEST() [57/84]
souffle::test::TEST (DjTest , Clear)
Definition at line 315 of file eqrel_datastructure_test.cpp.
References souffle::DisjointSet::clear(), EXPECT_EQ, souffle::DisjointSet::findNode(), i, souffle::DisjointSet::makeNode(), souffle::DisjointSet::size(), TEST(), and souffle::DisjointSet::unionNodes().
                     {
     souffle::DisjointSet ds;
     ds.clear();
     EXPECT_EQ(ds.size(), 0);
     // get ready 2 double free y'all
     for (size_t i = 0; i < 10000; ++i) {
         ds.makeNode();
     }
     ds.unionNodes(1, 2);
     ds.clear();
     ds.clear();
 }
TEST() [58/84]
souffle::test::TEST (BTreeSet , Merge)
Definition at line 315 of file btree_set_test.cpp.
References b, d, and EXPECT_NE.
                       {
     using test_set = btree_set<int>;
     test_set a;
     test_set b;
     a.insert(1);
     a.insert(2);
     a.insert(3);
     a.insert(4);
     b.insert(2);
     b.insert(4);
     b.insert(6);
     EXPECT_NE(a, b);
     test_set c = a;
     test_set d = b;
     EXPECT_NE(c, d);
 }
TEST() [59/84]
souffle::test::TEST (BTreeMultiSet , BoundaryEmpty)
Definition at line 323 of file btree_multiset_test.cpp.
References EXPECT_EQ, and EXPECT_NE.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.end(), t.lower_bound(5));
     EXPECT_EQ(t.end(), t.upper_bound(5));
     t.insert(4);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(6);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(5);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_NE(t.lower_bound(5), t.upper_bound(5));
 }
TEST() [60/84]
souffle::test::TEST (BTreeSet , IteratorEmpty)
Definition at line 338 of file btree_set_test.cpp.
References EXPECT_EQ.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.begin(), t.end());
 }
TEST() [61/84]
souffle::test::TEST (BTreeSet , IteratorBasic)
Definition at line 345 of file btree_set_test.cpp.
References e, EXPECT_EQ, EXPECT_NE, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 10;
     for (int i = 0; i <= N; i++) {
         t.insert(i);
     }
     //        t.printTree();
     auto it = t.begin();
     auto e = t.end();
     EXPECT_NE(it, e);
     int last = -1;
     for (int i : t) {
         EXPECT_EQ(last + 1, i);
         last = i;
     }
     EXPECT_EQ(last, N);
 }
TEST() [62/84]
souffle::test::TEST (BTreeMultiSet , Load)
Definition at line 346 of file btree_multiset_test.cpp.
References EXPECT_EQ, EXPECT_TRUE, and i.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     for (int N = 0; N < 100; N++) {
         // generate some ordered data
         std::vector<int> data;
         for (int i = 0; i < N; i++) {
             data.push_back(i);
         }
         auto t = test_set::load(data.begin(), data.end());
         EXPECT_EQ(data.size(), t.size());
         EXPECT_TRUE(t.check());
         int last = -1;
         for (int c : t) {
             EXPECT_EQ(last + 1, c);
             last = c;
         }
         EXPECT_EQ(last, N - 1);
     }
 }
TEST() [63/84]
souffle::test::TEST (EqRelTest , IterEmpty)
Definition at line 350 of file binary_relation_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, and testutil::ignore().
{
     // test iterating over an empty binrel fails
     EqRel br;
     for (auto x : br) {
         EXPECT_FALSE(true);
         testutil::ignore(x);
     }
     EXPECT_EQ(0, br.size());
 }
TEST() [64/84]
souffle::test::TEST (SparseDjTest , Scoping)
The SparseDisjointSet that is used by the EquivalenceRelation.
Definition at line 360 of file eqrel_datastructure_test.cpp.
{
     souffle::SparseDisjointSet<size_t> sds;
 }
TEST() [65/84]
souffle::test::TEST (EqRelTest , IterBasic)
Definition at line 360 of file binary_relation_test.cpp.
References count(), EXPECT_EQ, testutil::ignore(), and souffle::EquivalenceRelation< TupleType >::insert().
{
     EqRel br;
     br.insert(0, 0);
     br.insert(1, 1);
     br.insert(2, 2);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     // merge one disjoint set
     br.insert(0, 1);
     count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [66/84]
souffle::test::TEST (SparseDjTest , MakeNode)
Definition at line 364 of file eqrel_datastructure_test.cpp.
References EXPECT_EQ, i, souffle::SparseDisjointSet< SparseDomain >::makeNode(), and souffle::SparseDisjointSet< SparseDomain >::size().
{
     souffle::SparseDisjointSet<size_t> sds;
     EXPECT_EQ(sds.size(), 0);
     sds.makeNode(99);
     EXPECT_EQ(sds.size(), 1);
     // whilst this shouldn't happen in regular use, it *shouldn't* create a new node
     sds.makeNode(99);
     EXPECT_EQ(sds.size(), 1);
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         sds.makeNode(i);
     }
     EXPECT_EQ(sds.size(), N);
 }
TEST() [67/84]
souffle::test::TEST (BTreeMultiSet , Clear)
Definition at line 368 of file btree_multiset_test.cpp.
References EXPECT_FALSE, and EXPECT_TRUE.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_TRUE(t.empty());
     t.insert(5);
     EXPECT_FALSE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
 }
TEST() [68/84]
souffle::test::TEST (BTreeSet , IteratorStress)
Definition at line 370 of file btree_set_test.cpp.
References EXPECT_EQ, EXPECT_LT, and i.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     int max = -1;
     for (int i = 0; i < N; i++) {
         EXPECT_EQ((size_t)i, t.size());
         int last = -1;
         for (int i : t) {
             EXPECT_LT(last, i);
             last = i;
         }
         EXPECT_EQ(last, max);
         t.insert(data[i]);
         max = (data[i] > max) ? data[i] : max;
     }
 }
TEST() [69/84]
souffle::test::TEST (SparseDjTest , TestUnion)
Definition at line 383 of file eqrel_datastructure_test.cpp.
References souffle::SparseDisjointSet< SparseDomain >::contains(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::SparseDisjointSet< SparseDomain >::makeNode(), souffle::SparseDisjointSet< SparseDomain >::size(), and souffle::SparseDisjointSet< SparseDomain >::unionNodes().
{
     // check whether the unioning works to see if the elements are properly in the same set
     souffle::SparseDisjointSet<size_t> sds;
     sds.makeNode(20);
     sds.makeNode(32);
     EXPECT_FALSE(sds.contains(20, 32));
     sds.unionNodes(20, 32);
     EXPECT_TRUE(sds.contains(20, 32));
     EXPECT_EQ(sds.size(), 2);
     sds.makeNode(33);
     EXPECT_FALSE(sds.contains(20, 33));
     sds.unionNodes(32, 33);
     EXPECT_TRUE(sds.contains(20, 33));
     EXPECT_EQ(sds.size(), 3);
 }
TEST() [70/84]
souffle::test::TEST (EqRelTest , IterRange)
Definition at line 384 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::clear(), EXPECT_EQ, souffle::EquivalenceRelation< TupleType >::getBoundaries(), and souffle::EquivalenceRelation< TupleType >::insert().
{
     // write some tests to use that templated range for different indexes too
     EqRel br;
     br.insert(0, 1);
     br.insert(0, 2);
     br.insert(0, 3);
     br.insert(0, 4);
     br.insert(0, 5);
     br.insert(0, 6);
     br.insert(8, 9);
     br.insert(8, 10);
     // this should return an iterator covering (3, 0), (3, 1), ..., (3, 6), it's a (3, *) iterator
     auto rangeIt = br.getBoundaries<1>({{3, 18293018}});
     std::vector<size_t> posteriorsCovered;
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 7);
     // this should be of everything, so doesn't matter the args
     rangeIt = br.getBoundaries<0>({{332, 888}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), (7 * 7) + (3 * 3));
     // and now iterate over two levels (exactly one pretty much)
     rangeIt = br.getBoundaries<2>({{2, 3}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 1);
     EXPECT_EQ(posteriorsCovered.front(), 3);
     // and now the same, but for levels 1 and two, stuff that doesn't exist
     rangeIt = br.getBoundaries<1>({{99, 99}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 0);
     rangeIt = br.getBoundaries<2>({{8, 1}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 0);
     // and now the same for an empty binary relation
     br.clear();
     // repeat the same, but notice that we expect the size to be 0 always
     {
         auto rangeIt = br.getBoundaries<1>({{3, 18293018}});
         std::vector<size_t> posteriorsCovered;
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         // this should be of everything, so doesn't matter the args
         rangeIt = br.getBoundaries<0>({{332, 888}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         // and now iterate over two levels (exactly one pretty much)
         rangeIt = br.getBoundaries<2>({{2, 3}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         // and now the same, but for levels 1 and two, stuff that doesn't exist
         rangeIt = br.getBoundaries<1>({{99, 99}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         rangeIt = br.getBoundaries<2>({{8, 1}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
     }
 }
TEST() [71/84]
souffle::test::TEST (BTreeSet , BoundaryTest)
Definition at line 402 of file btree_set_test.cpp.
References b, EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     //    t.printTree();
     auto a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     auto b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // add duplicates
     t.insert(5);
     t.insert(5);
     t.insert(5);
     //    t.printTree(); std::cout << "\n";
     // test again ..
     a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [72/84]
souffle::test::TEST (SparseDjTest , SignedData)
Definition at line 403 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), b, souffle::SparseDisjointSet< SparseDomain >::contains(), EXPECT_EQ, EXPECT_TRUE, souffle::PiggyList< T >::get(), i, souffle::SparseDisjointSet< SparseDomain >::makeNode(), souffle::PiggyList< T >::size(), souffle::SparseDisjointSet< SparseDomain >::size(), TEST(), souffle::SparseDisjointSet< SparseDomain >::toDense(), and souffle::SparseDisjointSet< SparseDomain >::unionNodes().
{
     // test when the sparse dj set stores different signed-ness to the internally stored data
     souffle::SparseDisjointSet<ssize_t> sds;
     EXPECT_EQ(sds.size(), 0);
     sds.makeNode(9999);
     EXPECT_EQ(sds.size(), 1);
 }
TEST() [73/84]
souffle::test::TEST (BTreeSet , BoundaryEmpty)
Definition at line 438 of file btree_set_test.cpp.
References EXPECT_EQ, and EXPECT_NE.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.end(), t.lower_bound(5));
     EXPECT_EQ(t.end(), t.upper_bound(5));
     t.insert(4);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(6);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(5);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_NE(t.lower_bound(5), t.upper_bound(5));
 }
TEST() [74/84]
souffle::test::TEST (BTreeSet , Load)
Definition at line 461 of file btree_set_test.cpp.
References EXPECT_EQ, EXPECT_TRUE, and i.
                      {
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     for (int N = 0; N < 100; N++) {
         // generate some ordered data
         std::vector<int> data;
         for (int i = 0; i < N; i++) {
             data.push_back(i);
         }
         auto t = test_set::load(data.begin(), data.end());
         //        t.printTree();
         EXPECT_EQ(data.size(), t.size());
         EXPECT_TRUE(t.check());
         int last = -1;
         for (int c : t) {
             EXPECT_EQ(last + 1, c);
             last = c;
         }
         EXPECT_EQ(last, N - 1);
     }
 }
TEST() [75/84]
souffle::test::TEST (EqRelTest , IterPartition)
Definition at line 483 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::clear(), EXPECT_EQ, EXPECT_TRUE, i, souffle::EquivalenceRelation< TupleType >::insert(), souffle::EquivalenceRelation< TupleType >::partition(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test that the union equals the input
     // test single set binary rel
     EqRel br;
     std::vector<std::pair<RamDomain, RamDomain>> values;
     RamDomain N = 1000;
     for (RamDomain i = 0; i < N; ++i) {
         br.insert(i, i + 1);
     }
     EXPECT_EQ(size_t((N + 1) * (N + 1)), br.size());
     auto chunks = br.partition(400);
     // we can't make too many assumptions..
     EXPECT_TRUE(chunks.size() > 0);
     for (auto chunk : chunks) {
         for (auto x : chunk) {
             values.push_back(std::make_pair(x[0], x[1]));
         }
     }
     EXPECT_EQ(br.size(), values.size());
     br.clear();
     values.clear();
     chunks.clear();
     // many disjoint sets (note, can't use N, because even & odd numbers don't work the same..)
     for (RamDomain i = 0; i < 1000; i += 2) {
         br.insert(i, i + 1);
     }
     EXPECT_EQ((size_t)4 * 1000 / 2, br.size());
     chunks = br.partition(400);
     for (auto chunk : chunks) {
         for (auto x : chunk) {
             values.push_back(std::make_pair(x[0], x[1]));
         }
     }
     EXPECT_EQ(br.size(), values.size());
 }
TEST() [76/84]
souffle::test::TEST (BTreeSet , Clear)
Definition at line 487 of file btree_set_test.cpp.
References EXPECT_FALSE, and EXPECT_TRUE.
                       {
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_TRUE(t.empty());
     t.insert(5);
     EXPECT_FALSE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
 }
TEST() [77/84]
souffle::test::TEST (Performance , Basic)
Definition at line 494 of file btree_multiset_test.cpp.
References checkPerformance, getData(), i, and time().
{
     int N = 1 << 18;
     // get list of tuples to be inserted
     std::cout << "Generating Test-Data ...\n";
     std::vector<Entry> in;
     std::vector<Entry> out;
     time("generating data", [&]() {
         auto data = getData(2 * N);
         for (std::size_t i = 0; i < data.size(); i += 2) {
             in.push_back(data[i]);
             out.push_back(data[i + 1]);
         }
     });
     using t1 = std::set<Entry>;
     checkPerformance(t1, " -- warm up -- ", in, out);
     using t2 = btree_multiset<Entry, detail::comparator<Entry>, std::allocator<Entry>, 256,
             detail::linear_search>;
     checkPerformance(t2, "souffle btree_multiset - 256 - linear", in, out);
     using t3 = btree_multiset<Entry, detail::comparator<Entry>, std::allocator<Entry>, 256,
             detail::binary_search>;
     checkPerformance(t3, "souffle btree_multiset - 256 - binary", in, out);
 }
TEST() [78/84]
souffle::test::TEST (BTreeSet , ChunkSplit)
Definition at line 504 of file btree_set_test.cpp.
References EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     // TODO: test for empty
     for (int i = 0; i < 100; i++) {
         t.insert(i);
     }
     // split chunks
     auto chunks = t.getChunks(20);
     //        EXPECT_EQ(20, chunks.size());
     for (const auto& cur : chunks) {
         for (int i : cur) {
             std::cout << i << ", ";
         }
         std::cout << "\n";
     }
     int last = -1;
     for (const auto& cur : chunks) {
         for (auto i = cur.begin(); i != cur.end(); ++i) {
             EXPECT_EQ(last + 1, *i);
             last = *i;
         }
     }
 }
TEST() [79/84]
souffle::test::TEST (LambdaBTreeTest , Scoping)
The LambdaBTree - essentially a ripoff to the Btree, but allows a function to be called on successful insert.
I just am gonna test a subset of it, because I can argue that BTree already tests the basic stuff
Definition at line 505 of file eqrel_datastructure_test.cpp.
{
     // lambda btree set current has some hard coded stuff h1
     TestLambdaTree t;
 }
TEST() [80/84]
souffle::test::TEST (LambdaBTreeTest , Insert)
Definition at line 510 of file eqrel_datastructure_test.cpp.
References b, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::contains(), EXPECT_EQ, EXPECT_TRUE, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::find(), i, souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, Functor, WeakComparator, Updater >::insert(), p, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::printTree(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::size(), and TEST().
{
     // insert some stuff and make sure the sideeffects are correct (as observed within the lambda), and also
     // that the elements are contained
     // the ticket machine that sets the second argument (for now our functor will just postincrent to assign)
     std::atomic<size_t> assigner(0);
     TestLambdaTree t;
     EXPECT_EQ(t.size(), 0);
     std::function<TestPair::second_type(TestPair&)> update_fn = [&](TestPair& tp) {
         tp.second = assigner.fetch_add(1);
         return tp.second;
     };
     TestPair toInsert = {55, -1};
     // inserting the ticketed value
     EXPECT_EQ(t.insert(toInsert, update_fn), 0);
     EXPECT_EQ(t.size(), 1);
     // the second argument should be ignored because its unknown until you fetch it!
     EXPECT_TRUE(t.contains({55, 1329139123}));
     // post increment of 0 is zero.
     EXPECT_EQ(((*t.find({55, 3232})).second), 0);
     TestPair insert2 = {43, 22};
     // insert should also return the value
     EXPECT_EQ(t.insert(insert2, update_fn), 1);
     EXPECT_TRUE(t.contains({43, 1329139123}));
     // post increment now should equal 1
     EXPECT_EQ(((*t.find({43, 3232})).second), 1);
     EXPECT_EQ(t.size(), 2);
     // now lets insert something that already exists (the anterior is all that matters)
     TestPair alreadyExistsPair = {55, 12313123};
     EXPECT_EQ(t.insert(alreadyExistsPair,
                       [&](TestPair&) {
                           EXPECT_TRUE(false &&
                                       "newly inserted function called for an element that already exists!");
                           // some dummy value
                           return 3223;
                       }),
             0);
     EXPECT_EQ(t.size(), 2);
 }
TEST() [81/84]
souffle::test::TEST (Performance , Load)
Definition at line 519 of file btree_multiset_test.cpp.
References i, and time().
{
     int N = 1 << 20;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     // take time for conventional load
     time("conventional load", [&]() { btree_multiset<int> t(data.begin(), data.end()); });
     // take time for structured load
     time("bulk-load", [&]() { auto t = btree_multiset<int>::load(data.begin(), data.end()); });
 }
TEST() [82/84]
souffle::test::TEST (EqRelTest , Scaling)
Definition at line 528 of file binary_relation_test.cpp.
References EXPECT_EQ, i, souffle::EquivalenceRelation< TupleType >::insert(), souffle::EquivalenceRelation< TupleType >::size(), and TEST().
{
     const int N = 100;
     EqRel br;
     for (int i = 0; i < N; ++i) {
         br.insert(i, i);
     }
     EXPECT_EQ(N, br.size());
 }
TEST() [83/84]
souffle::test::TEST (BTreeSet , ChunkSplitStress)
Definition at line 536 of file btree_set_test.cpp.
References b, count(), duration(), EXPECT_EQ, getData(), i, j, k, souffle::now(), and time().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     for (int i = 0; i < 1000; i++) {
         // generate random sequence
         std::vector<int> data;
         for (int j = 0; j < i; j++) {
             data.push_back(j);
         }
         std::random_device rd;
         std::mt19937 generator(rd());
         shuffle(data.begin(), data.end(), generator);
         // fill tree
         test_set t;
         for (int x : data) {
             t.insert(x);
         }
         for (int j = 1; j < 100; j++) {
             auto chunks = t.getChunks(j);
             //                EXPECT_LT(chunks.size(), j * 2);
             if (chunks.empty()) continue;
             // check covered range
             EXPECT_EQ(0, *chunks.front().begin());
             int last = -1;
             for (const auto& cur : chunks) {
                 for (auto it = cur.begin(); it != cur.end(); ++it) {
                     EXPECT_EQ(last + 1, *it);
                     last = *it;
                 }
             }
             EXPECT_EQ(i - 1, last);
         }
     }
 }
TEST() [84/84]
souffle::test::TEST (BTreeSet , Parallel)
Definition at line 731 of file btree_set_test.cpp.
References count(), EXPECT_EQ, EXPECT_TRUE, souffle::filter(), i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     //        const int N = 600000000;
     //        const int N = 100000;
     //        const int N = 10000;
     const int N = 1000;
     //        const int N = 300;
     //        const int N = 100;
     // get a unordered list of test data
     using entry_t = int;
     std::vector<entry_t> list;
     btree_set<entry_t> filter;
     for (int i = 0; i < N; i++) {
         list.push_back(i);
     }
     // the number of times duplicates show up in the input set
     for (int dup = 1; dup < 4; dup++) {
         // now duplicate this list
         std::vector<entry_t> full;
         for (int i = 0; i < dup; i++) {
             for (const auto& cur : list) {
                 full.push_back(cur);
             }
         }
         // shuffle data
         std::random_device rd;
         std::mt19937 generator(rd());
         std::shuffle(full.begin(), full.end(), generator);
         // now insert all those values into a new set - in parallel
         btree_set<entry_t> res;
 #pragma omp parallel for  //  schedule(static,1)
         for (auto it = full.begin(); it < full.end(); ++it) {
             res.insert(*it);
         }
         EXPECT_TRUE(res.check());
         // check resulting values
         EXPECT_EQ(N, res.size());
         std::set<entry_t> should(full.begin(), full.end());
         std::set<entry_t> is(res.begin(), res.end());
         for (const auto& cur : should) {
             EXPECT_TRUE(res.contains(cur)) << "Missing: " << cur << "\n";
         }
         for (const auto& cur : res) {
             EXPECT_TRUE(should.find(cur) != should.end()) << "Additional: " << cur << "\n"
                                                           << "Contained: " << res.contains(cur) << "\n";
         }
         std::vector<entry_t> extra;
         for (const auto& cur : is) {
             if (should.find(cur) == should.end()) extra.push_back(cur);
         }
         EXPECT_TRUE(extra.empty()) << "Extra elments: " << extra << "\n";
         std::vector<entry_t> missing;
         for (const auto& cur : should) {
             if (is.find(cur) == is.end()) missing.push_back(cur);
         }
         EXPECT_TRUE(missing.empty()) << "Missing elments: " << missing << "\n";
         //                << "All Elements: " << should << "\n";
         EXPECT_EQ(N, should.size());
         EXPECT_EQ(N, is.size());
         EXPECT_EQ(should, is);
     }
 }
time()
template<typename Op > long souffle::test::time (const std::string & name, const Op & operation)
Definition at line 411 of file btree_multiset_test.cpp.
References b, duration(), and now().
Referenced by souffle::main(), souffle::ProfileEventSingleton::makeUtilisationEvent(), souffle::profile::ProgramTimepointProcessor::process(), souffle::profile::ProgramResourceUtilisationProcessor::process(), souffle::profile::ProgramRun::setEndtime(), souffle::profile::Rule::setEndtime(), souffle::profile::Iteration::setEndtime(), souffle::profile::Relation::setEndtime(), souffle::profile::ProgramRun::setStarttime(), souffle::profile::Rule::setStarttime(), souffle::profile::Iteration::setStarttime(), souffle::profile::Relation::setStarttime(), TEST(), and TEST().
{
     std::cout << "\t" << std::setw(30) << std::setiosflags(std::ios::left) << name
               << std::resetiosflags(std::ios::left) << " ... " << std::flush;
     auto a = now();
     operation();
     auto b = now();
     auto time = duration(a, b);
     std::cout << " done [" << std::setw(5) << time << "ms]\n";
     return time;
 }