souffle: souffle::ast::analysis Namespace Reference
souffle::ast::analysis Namespace Reference
Namespaces
detail
Data Structures
class AlgebraicDataType
Aggregates types using sums and products.
class Analysis
Abstract class for a AST Analysis.
class Assignment
An assignment maps a list of variables to values of their respective property space.
class AuxiliaryArityAnalysis
Determine the auxiliary arity for relations.
class ClauseNormalisationAnalysis
class ComponentLookupAnalysis
class ConstantType
Representing the type assigned to a constant.
class Constraint
A generic base class for constraints on variables.
class ConstraintAnalysis
A base class for ConstraintAnalysis collecting constraints for an analysis by visiting every node of a given AST.
struct ConstraintAnalysisVar
A variable type to be utilized by AST constraint analysis.
class IOTypeAnalysis
class NormalisedClause
class PrecedenceGraphAnalysis
Analysis pass computing the precedence graph of the relations of the datalog progam.
class PrimitiveType
PrimitiveType = Number/Unsigned/Float/Symbol The class representing pre-built, concrete types.
class Problem
A problem is a list of constraints for which a solution is desired.
class ProfileUseAnalysis
Analysis that loads profile data and has a profile query interface.
struct property_space
A MPL type for defining a property space.
struct RecordType
A record type combining a list of fields into a new, aggregated type.
class RecursiveClausesAnalysis
Analysis pass identifying clauses which are recursive.
class RedundantRelationsAnalysis
Analysis pass identifying relations which do not contribute to the computation of the output relations.
class RelationDetailCacheAnalysis
Analysis pass mapping identifiers with relations and clauses.
class RelationScheduleAnalysis
Analysis pass computing a schedule for computing relations.
class RelationScheduleAnalysisStep
A single step in a relation schedule, consisting of the relations computed in the step and the relations that are no longer required at that step.
class SCCGraphAnalysis
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
struct set_property_space
A property space for set-based properties based on sub-set lattices.
struct SubsetRecordType
Type representing a subset type derived from the record type.
class SubsetType
A type being a subset of another type.
class SumTypeBranchesAnalysis
class TopologicallySortedSCCGraphAnalysis
Analysis pass computing a topologically sorted strongly connected component (SCC) graph.
class Type
An abstract base class for types to be covered within a type environment.
class TypeAnalysis
class TypeBinding
Class that encapsulates std::map of types binding that comes from .init c = Comp<MyType> Type binding in this example would be T->MyType if the component code is .comp Comp<T> ...
class TypeConstraintsAnalysis
Constraint analysis framework for types.
class TypeEnvironment
A type environment is a set of types.
class TypeEnvironmentAnalysis
struct TypeSet
A collection to represent sets of types.
struct TypeVisitor
A visitor for Types.
class UnionType
A union type combining a list of types into a new, aggregated type.
struct Variable
A variable to be utilized within constraints to be handled by the constraint solver.
class VisitOnceTypeVisitor
A visitor for types visiting each type only once (effectively breaking recursive cycles).
Functions
bool areEquivalentTypes (const Type &a, const Type &b)
Determine if two types are equivalent.
Own< Clause > createAnnotatedClause (const Clause *clause, const std::map< const Argument *, TypeSet > argumentTypes)
TypeSet getGreatestCommonSubtypes (const Type &a, const Type &b)
Computes the greatest common sub types of the two given types.
TypeSet getGreatestCommonSubtypes (const TypeSet &set)
Computes the greatest common sub types of all the types in the given set.
TypeSet getGreatestCommonSubtypes (const TypeSet &a, const TypeSet &b)
The set of pair-wise greatest common sub types of the types in the two given sets.
template<typename... Types>
TypeSet getGreatestCommonSubtypes (const Types &... types)
Computes the greatest common sub types of the given types.
std::map< const Argument *, bool > getGroundedTerms (const TranslationUnit &tu, const Clause &clause)
Analyse the given clause and computes for each contained argument whether it is a grounded value or not.
TypeAttribute getTypeAttribute (const Type &type)
std::optional< TypeAttribute > getTypeAttribute (const TypeSet &type)
std::string getTypeQualifier (const Type &type)
Returns full type qualifier for a given type.
bool haveCommonSupertype (const Type &a, const Type &b)
Determine if there exist a type t such that a <: t and b <: t.
bool isNumericType (const TypeSet &type)
bool isOfKind (const Type &type, TypeAttribute kind)
Check if the type is of a kind corresponding to the TypeAttribute.
bool isOfKind (const TypeSet &typeSet, TypeAttribute kind)
bool isOfRootType (const Type &type, const Type &root)
Determines whether the given type is a sub-type of the given root type.
bool isOrderableType (const TypeSet &type)
bool isSubtypeOf (const Type &a, const Type &b)
Determines whether type a is a subtype of type b.
template<typename Var >
std::shared_ptr< Constraint< Var > > sub (const Var &a, const Var &b, const std::string &symbol="⊑")
A generic factory for constraints of the form.
template<typename Var , typename Val = typename Var::property_space::value_type>
std::shared_ptr< Constraint< Var > > sub (const Val &a, const Var &b, const std::string &symbol="⊑")
A generic factory for constraints of the form.
Function Documentation
areEquivalentTypes()
bool souffle::ast::analysis::areEquivalentTypes (const Type & a, const Type & b)
Determine if two types are equivalent.
That is, check if a <: b and b <: a
Definition at line 388 of file TypeSystem.cpp.
References isSubtypeOf().
Referenced by getGreatestCommonSubtypes(), souffle::ast::test::TEST(), and souffle::ast::transform::TypeChecker::visitBinaryConstraint().
{
     return isSubtypeOf(a, b) && isSubtypeOf(b, a);
 }
createAnnotatedClause()
Own<Clause> souffle::ast::analysis::createAnnotatedClause (const Clause * clause, const std::map< const Argument *, TypeSet > argumentTypes)
Definition at line 488 of file Type.cpp.
References souffle::clone(), i, types, and souffle::ast::visitDepthFirst().
Referenced by souffle::ast::analysis::TypeAnalysis::run().
{
     // Annotates each variable with its type based on a given type analysis result
     struct TypeAnnotator : public NodeMapper {
         const std::map<const Argument*, TypeSet>& types;
         TypeAnnotator(const std::map<const Argument*, TypeSet>& types) : types(types) {}
         Own<Node> operator()(Own<Node> node) const override {
             if (auto* var = dynamic_cast<ast::Variable*>(node.get())) {
                 std::stringstream newVarName;
                 newVarName << var->getName() << "&isin;" << types.find(var)->second;
                 return mk<ast::Variable>(newVarName.str());
             } else if (auto* var = dynamic_cast<UnnamedVariable*>(node.get())) {
                 std::stringstream newVarName;
                 newVarName << "_"
                            << "&isin;" << types.find(var)->second;
                 return mk<ast::Variable>(newVarName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     /* Note:
      * Because the type of each argument is stored in the form [address -> type-set],
      * the type-analysis result does not immediately apply to the clone due to differing
      * addresses.
      * Two ways around this:
      *  (1) Perform the type-analysis again for the cloned clause
      *  (2) Keep track of the addresses of equivalent arguments in the cloned clause
      * Method (2) was chosen to avoid having to recompute the analysis each time.
      */
     auto annotatedClause = souffle::clone(clause);
     // Maps x -> y, where x is the address of an argument in the original clause, and y
     // is the address of the equivalent argument in the clone.
     std::map<const Argument*, const Argument*> memoryMap;
     std::vector<const Argument*> originalAddresses;
     visitDepthFirst(*clause, [&](const Argument& arg) { originalAddresses.push_back(&arg); });
     std::vector<const Argument*> cloneAddresses;
     visitDepthFirst(*annotatedClause, [&](const Argument& arg) { cloneAddresses.push_back(&arg); });
     assert(cloneAddresses.size() == originalAddresses.size());
     for (size_t i = 0; i < originalAddresses.size(); i++) {
         memoryMap[originalAddresses[i]] = cloneAddresses[i];
     }
     // Map the types to the clause clone
     std::map<const Argument*, TypeSet> cloneArgumentTypes;
     for (auto& pair : argumentTypes) {
         cloneArgumentTypes[memoryMap[pair.first]] = pair.second;
     }
     // Create the type-annotated clause
     TypeAnnotator annotator(cloneArgumentTypes);
     annotatedClause->apply(annotator);
     return annotatedClause;
 }
getGreatestCommonSubtypes() [1/4]
TypeSet souffle::ast::analysis::getGreatestCommonSubtypes (const Type & a, const Type & b)
Computes the greatest common sub types of the two given types.
Definition at line 269 of file TypeSystem.cpp.
References b, souffle::ast::analysis::UnionType::getElementTypes(), souffle::ast::analysis::Type::getTypeEnvironment(), souffle::ast::analysis::TypeSet::insert(), isSubtypeOf(), and souffle::ast::analysis::TypeVisitor< R >::visit().
Referenced by getGreatestCommonSubtypes(), isOrderableType(), and souffle::ast::test::TEST().
{
     assert(&a.getTypeEnvironment() == &b.getTypeEnvironment() &&
             "Types must be in the same type environment");
     if (isSubtypeOf(a, b)) {
         return TypeSet(a);
     }
     if (isSubtypeOf(b, a)) {
         return TypeSet(b);
     }
     TypeSet res;
     if (isA<UnionType>(a) && isA<UnionType>(b)) {
         // collect common sub-types of union types
         struct collector : public TypeVisitor<void> {
             const Type& b;
             TypeSet& res;
             collector(const Type& b, TypeSet& res) : b(b), res(res) {}
             void visit(const Type& type) const override {
                 if (isSubtypeOf(type, b)) {
                     res.insert(type);
                 } else {
                     TypeVisitor<void>::visit(type);
                 }
             }
             void visitUnionType(const UnionType& type) const override {
                 for (const auto& cur : type.getElementTypes()) {
                     visit(*cur);
                 }
             }
         };
         // collect all common sub-types
         collector(b, res).visit(a);
     }
     // otherwise there is no common super type
     return res;
 }
getGreatestCommonSubtypes() [2/4]
TypeSet souffle::ast::analysis::getGreatestCommonSubtypes (const TypeSet & set)
Computes the greatest common sub types of all the types in the given set.
Definition at line 310 of file TypeSystem.cpp.
References getGreatestCommonSubtypes(), and souffle::ast::analysis::TypeSet::insert().
{
     // Edge cases.
     if (set.empty() || set.isAll()) {
         return TypeSet();
     }
     TypeSet greatestCommonSubtypes;
     greatestCommonSubtypes.insert(*set.begin());
     for (auto& type : set) {
         greatestCommonSubtypes = getGreatestCommonSubtypes(TypeSet(type), greatestCommonSubtypes);
     }
     return greatestCommonSubtypes;
 }
getGreatestCommonSubtypes() [3/4]
TypeSet souffle::ast::analysis::getGreatestCommonSubtypes (const TypeSet & a, const TypeSet & b)
The set of pair-wise greatest common sub types of the types in the two given sets.
Definition at line 326 of file TypeSystem.cpp.
References b, souffle::ast::analysis::TypeSet::empty(), getGreatestCommonSubtypes(), souffle::ast::analysis::TypeSet::insert(), and souffle::ast::analysis::TypeSet::isAll().
{
     // special cases
     if (a.empty()) {
         return a;
     }
     if (b.empty()) {
         return b;
     }
     if (a.isAll()) {
         return b;
     }
     if (b.isAll()) {
         return a;
     }
     // compute pairwise greatest common sub types
     TypeSet res;
     for (const Type& x : a) {
         for (const Type& y : b) {
             res.insert(getGreatestCommonSubtypes(x, y));
         }
     }
     return res;
 }
getGreatestCommonSubtypes() [4/4]
template<typename... Types> TypeSet souffle::ast::analysis::getGreatestCommonSubtypes (const Types &... types)
Computes the greatest common sub types of the given types.
Definition at line 559 of file TypeSystem.h.
References areEquivalentTypes(), getGreatestCommonSubtypes(), and haveCommonSupertype().
{
     return getGreatestCommonSubtypes(TypeSet(types...));
 }
getGroundedTerms()
std::map< const Argument *, bool > souffle::ast::analysis::getGroundedTerms (const TranslationUnit & tu, const Clause & clause)
Analyse the given clause and computes for each contained argument whether it is a grounded value or not.
Parameters
tu the translation unit containing the clause
clause the clause to be analyzed
Returns
a map mapping each contained argument to a boolean indicating whether the argument represents a grounded value or not
Definition at line 272 of file Ground.cpp.
Referenced by souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::findVariablesRecordMapping(), souffle::ast::transform::SemanticCheckerImpl::isDependent(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::test::TEST(), souffle::ast::transform::usesInvalidWitness(), and souffle::ast::transform::GroundedTermsChecker::verify().
{
     // run analysis on given clause
     return GroundednessAnalysis(tu).analyse(clause);
 }
getTypeAttribute() [1/2]
TypeAttribute souffle::ast::analysis::getTypeAttribute (const Type & type)
Definition at line 368 of file TypeSystem.cpp.
References souffle::fatal(), souffle::Float, isOfKind(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by souffle::ast::validOverloads().
{
     for (auto typeAttribute : {TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float,
                  TypeAttribute::Record, TypeAttribute::Symbol}) {
         if (isOfKind(type, typeAttribute)) {
             return typeAttribute;
         }
     }
     fatal("Unknown type class");
 }
getTypeAttribute() [2/2]
std::optional< TypeAttribute > souffle::ast::analysis::getTypeAttribute (const TypeSet & type)
Definition at line 378 of file TypeSystem.cpp.
References souffle::Float, isOfKind(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
{
     for (auto typeAttribute : {TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float,
                  TypeAttribute::Record, TypeAttribute::Symbol}) {
         if (isOfKind(type, typeAttribute)) {
             return typeAttribute;
         }
     }
     return {};
 }
getTypeQualifier()
std::string souffle::ast::analysis::getTypeQualifier (const Type & type)
Returns full type qualifier for a given type.
Definition at line 198 of file TypeSystem.cpp.
References souffle::ADT, souffle::fatal(), souffle::Float, tinyformat::format(), souffle::ast::analysis::UnionType::getElementTypes(), souffle::ast::analysis::RecordType::getFields(), souffle::ast::analysis::Type::getName(), isOfKind(), souffle::join(), souffle::Record, souffle::Signed, str, souffle::Symbol, souffle::toString(), and souffle::Unsigned.
Referenced by souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes(), souffle::ast::transform::IOAttributesTransformer::getRecordsTypes(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), and souffle::AstToRamTranslator::translateProgram().
{
     struct visitor : public VisitOnceTypeVisitor<std::string> {
         std::string visitUnionType(const UnionType& type) const override {
             return tfm::format("%s[%s]", visitType(type),
                     join(type.getElementTypes(), ", ",
                             [&](std::ostream& out, const auto* elementType) { out << visit(*elementType); }));
         }
         std::string visitRecordType(const RecordType& type) const override {
             return tfm::format("%s{%s}", visitType(type),
                     join(type.getFields(), ", ",
                             [&](std::ostream& out, const auto* field) { out << visit(*field); }));
         }
         std::string visitType(const Type& type) const override {
             std::string str;
             if (isOfKind(type, TypeAttribute::Signed)) {
                 str.append("i");
             } else if (isOfKind(type, TypeAttribute::Unsigned)) {
                 str.append("u");
             } else if (isOfKind(type, TypeAttribute::Float)) {
                 str.append("f");
             } else if (isOfKind(type, TypeAttribute::Symbol)) {
                 str.append("s");
             } else if (isOfKind(type, TypeAttribute::Record)) {
                 str.append("r");
             } else if (isOfKind(type, TypeAttribute::ADT)) {
                 str.append("+");
             } else {
                 fatal("Unsupported kind");
             }
             str.append(":");
             str.append(toString(type.getName()));
             seen[&type] = str;
             return str;
         }
     };
     return visitor().visit(type);
 }
haveCommonSupertype()
bool souffle::ast::analysis::haveCommonSupertype (const Type & a, const Type & b)
Determine if there exist a type t such that a <: t and b <: t.
Definition at line 352 of file TypeSystem.cpp.
References souffle::any_of(), souffle::ast::analysis::Type::getTypeEnvironment(), souffle::ast::analysis::TypeEnvironment::getTypes(), and isSubtypeOf().
Referenced by getGreatestCommonSubtypes().
{
     assert(&a.getTypeEnvironment() == &b.getTypeEnvironment() &&
             "Types must be in the same type environment");
     if (a == b) {
         return true;
     }
     if (isSubtypeOf(a, b) || isSubtypeOf(b, a)) {
         return true;
     }
     return any_of(a.getTypeEnvironment().getTypes(),
             [&](const Type& type) { return isSubtypeOf(a, type) && isSubtypeOf(b, type); });
 }
isNumericType()
bool souffle::ast::analysis::isNumericType (const TypeSet & type) inline
Definition at line 529 of file TypeSystem.h.
References souffle::Float, isOfKind(), souffle::Signed, and souffle::Unsigned.
Referenced by isOrderableType().
{
     return isOfKind(type, TypeAttribute::Signed) || isOfKind(type, TypeAttribute::Unsigned) ||
            isOfKind(type, TypeAttribute::Float);
 }
isOfKind() [1/2]
bool souffle::ast::analysis::isOfKind (const Type & type, TypeAttribute kind)
Check if the type is of a kind corresponding to the TypeAttribute.
Definition at line 183 of file TypeSystem.cpp.
References souffle::ADT, souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::ast::analysis::Type::getTypeEnvironment(), isOfRootType(), and souffle::Record.
Referenced by getTypeAttribute(), getTypeQualifier(), isNumericType(), isOfKind(), isOrderableType(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::test::TEST(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), souffle::ast::transform::TypeChecker::visitAggregator(), souffle::ast::transform::TypeChecker::visitBinaryConstraint(), souffle::ast::transform::TypeChecker::visitBranchInit(), souffle::ast::transform::TypeChecker::visitNilConstant(), souffle::ast::transform::TypeChecker::visitNumericConstant(), souffle::ast::transform::TypeChecker::visitRecordInit(), souffle::ast::transform::TypeChecker::visitStringConstant(), and souffle::ast::transform::TypeChecker::visitUserDefinedFunctor().
{
     if (kind == TypeAttribute::Record) {
         return isA<RecordType>(type);
     } else if (kind == TypeAttribute::ADT) {
         return isA<AlgebraicDataType>(type);
     }
     return isOfRootType(type, type.getTypeEnvironment().getConstantType(kind));
 }
isOfKind() [2/2]
bool souffle::ast::analysis::isOfKind (const TypeSet & typeSet, TypeAttribute kind)
Definition at line 193 of file TypeSystem.cpp.
References souffle::all_of(), souffle::ast::analysis::TypeSet::empty(), souffle::ast::analysis::TypeSet::isAll(), and isOfKind().
{
     return !typeSet.empty() && !typeSet.isAll() &&
            all_of(typeSet, [&](const Type& type) { return isOfKind(type, kind); });
 }
isOfRootType()
bool souffle::ast::analysis::isOfRootType (const Type & type, const Type & root)
Determines whether the given type is a sub-type of the given root type.
Definition at line 149 of file TypeSystem.cpp.
References souffle::all_of(), souffle::ast::analysis::SubsetType::getBaseType(), and souffle::ast::analysis::UnionType::getElementTypes().
Referenced by isOfKind(), and isSubtypeOf().
{
     struct visitor : public VisitOnceTypeVisitor<bool> {
         const Type& root;
         explicit visitor(const Type& root) : root(root) {}
         bool visitConstantType(const ConstantType& type) const override {
             return type == root;
         }
         bool visitSubsetType(const SubsetType& type) const override {
             return type == root || isOfRootType(type.getBaseType(), root);
         }
         bool visitAlgebraicDataType(const AlgebraicDataType& type) const override {
             return type == root;
         }
         bool visitUnionType(const UnionType& type) const override {
             return type == root ||
                    all_of(type.getElementTypes(), [&](const Type* cur) { return this->visit(*cur); });
         }
         bool visitRecordType(const RecordType& type) const override {
             return type == root;
         }
         bool visitType(const Type& /*unused*/) const override {
             return false;
         }
     };
     return visitor(root).visit(type);
 }
isOrderableType()
bool souffle::ast::analysis::isOrderableType (const TypeSet & type) inline
Definition at line 534 of file TypeSystem.h.
References b, getGreatestCommonSubtypes(), isNumericType(), isOfKind(), and souffle::Symbol.
{
     return isNumericType(type) || isOfKind(type, TypeAttribute::Symbol);
 }
isSubtypeOf()
bool souffle::ast::analysis::isSubtypeOf (const Type & a, const Type & b)
Determines whether type a is a subtype of type b.
Definition at line 241 of file TypeSystem.cpp.
References souffle::all_of(), souffle::any_of(), souffle::ast::analysis::Type::getTypeEnvironment(), and isOfRootType().
Referenced by areEquivalentTypes(), getGreatestCommonSubtypes(), haveCommonSupertype(), souffle::ast::test::isNotSubtypeOf(), souffle::ast::test::TEST(), souffle::ast::analysis::TypeConstraintsAnalysis::visitAggregator(), souffle::ast::transform::TypeChecker::visitAtom(), souffle::ast::analysis::TypeConstraintsAnalysis::visitAtom(), souffle::ast::analysis::TypeConstraintsAnalysis::visitBinaryConstraint(), souffle::ast::transform::TypeChecker::visitBranchInit(), souffle::ast::analysis::TypeConstraintsAnalysis::visitBranchInit(), souffle::ast::analysis::TypeConstraintsAnalysis::visitCounter(), souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor(), souffle::ast::analysis::TypeConstraintsAnalysis::visitSink(), souffle::ast::analysis::TypeConstraintsAnalysis::visitStringConstant(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitTypeCast().
{
     assert(&a.getTypeEnvironment() == &b.getTypeEnvironment() &&
             "Types must be in the same type environment");
     if (isOfRootType(a, b)) {
         return true;
     }
     if (isA<UnionType>(a)) {
         return all_of(static_cast<const UnionType&>(a).getElementTypes(),
                 [&b](const Type* type) { return isSubtypeOf(*type, b); });
     }
     if (isA<UnionType>(b)) {
         return any_of(static_cast<const UnionType&>(b).getElementTypes(),
                 [&a](const Type* type) { return isSubtypeOf(a, *type); });
     }
     return false;
 }
sub() [1/2]
template<typename Var > std::shared_ptr<Constraint<Var> > souffle::ast::analysis::sub (const Var & a, const Var & b, const std::string & symbol = "⊑")
A generic factory for constraints of the form.
a ⊑ b
where a and b are variables and ⊑ is the order relation induced by their associated property space.
Definition at line 222 of file ConstraintSystem.h.
References b.
Referenced by souffle::ram::Program::apply(), souffle::ast::transform::SemanticCheckerImpl::checkUnionType(), souffle::ram::Program::clone(), souffle::findTool(), souffle::synthesiser::Synthesiser::generateCode(), souffle::InterpreterEngine::generateIR(), souffle::ram::Program::getChildNodes(), souffle::ram::Program::getSubroutines(), souffle::detail::fix_lower_bound< Pos, Dim >::operator()(), souffle::detail::fix_upper_bound< Pos, Dim >::operator()(), souffle::ram::Program::print(), souffle::ram::Program::Program(), souffle::ast::transform::reduceSubstitution(), souffle::ast::test::TEST(), and souffle::which().
{
     struct Sub : public Constraint<Var> {
         Var a, b;
         std::string symbol;
         Sub(Var a, Var b, std::string symbol) : a(std::move(a)), b(std::move(b)), symbol(std::move(symbol)) {}
         bool update(Assignment<Var>& ass) const override {
             typename Var::property_space::meet_assign_op_type meet_assign;
             return meet_assign(ass[b], ass[a]);
         }
         void print(std::ostream& out) const override {
             out << a << " " << symbol << " " << b;
         }
     };
     return std::make_shared<Sub>(a, b, symbol);
 }
sub() [2/2]
template<typename Var , typename Val = typename Var::property_space::value_type> std::shared_ptr<Constraint<Var> > souffle::ast::analysis::sub (const Val & a, const Var & b, const std::string & symbol = "⊑")
A generic factory for constraints of the form.
a ⊑ b
where b is a variables, a is a value of b's property space, and ⊑ is the order relation induced by b's property space.
Definition at line 251 of file ConstraintSystem.h.
References b.
{
     struct Sub : public Constraint<Var> {
         Val a;
         Var b;
         std::string symbol;
         Sub(Val a, Var b, std::string symbol) : a(std::move(a)), b(std::move(b)), symbol(std::move(symbol)) {}
         bool update(Assignment<Var>& ass) const override {
             typename Var::property_space::meet_assign_op_type meet_assign;
             return meet_assign(ass[b], a);
         }
         void print(std::ostream& out) const override {
             out << a << " " << symbol << " " << b;
         }
     };
     return std::make_shared<Sub>(a, b, symbol);
 }