souffle: souffle Namespace Reference
souffle Namespace Reference
Namespaces
ast
detail
evaluator
gzfstream
index_utils
A namespace enclosing utilities required by indices.
profile
ram
synthesiser
Souffle - A Datalog Compiler Copyright (c) 2013, 2015, Oracle and/or its affiliates.
test
Data Structures
class AstToRamTranslator
Main class for AST Translator.
class BaseTable
class BrieIndex
A index adapter for Bries, using the generic index adapter.
class btree_multiset
A b-tree based multi-set implementation.
class btree_set
A b-tree based set implementation.
class BTreeIndex
A index adapter for B-trees, using the generic index adapter.
class BTreeProvenanceIndex
Btree index for provenance relation.
class CacheAccessCounter
cache hits/misses.
class CmdOptions
A utility class for parsing command line arguments within generated query programs.
struct comp_deref
A functor class supporting the values pointers are pointing to.
class ConstConstraint
Constant constraints for values in query command.
class DebugReport
Class representing a HTML report, consisting of a list of sections.
class DebugReportSection
Class representing a section of a HTML report.
struct deref
A functor dereferencing a given type.
struct deref_less
A functor comparing the dereferenced value of a pointer type utilizing a given comparator.
class Diagnostic
class DiagnosticMessage
class DisjointSet
Structure that emulates a Disjoint Set, i.e.
class DynTuple
A construction-time sized tuple instance easing tuple handling in non-compiled contexts.
class EqrelIndex
A index adapter for EquivalenceRelation, using the generic index adapter.
struct EqrelMapComparator
class Equivalence
Equivalence class for variables in query command.
class EquivalenceRelation
class ErrorReport
class Explain
class ExplainConfig
class ExplainProvenance
class ExplainProvenanceImpl
class GenericIndex
A generic data structure index adapter handling the boundary level order conversion as well as iteration through nested data structures.
class Global
class Graph
A simple graph structure for graph-based operations.
struct id
A functor representing the identity function for a generic type T.
struct index
The index class is utilized as a template-meta-programming structure to specify and realize indices.
class IndexView
A view on a relation caching local access patterns (not thread safe!).
class IndirectIndex
class InnerNode
class InterpreterAbstractParallel
Interpreter node that utilizes parallel execution should inherit from this class.
class InterpreterAggregate
class InterpreterAutoIncrement
class InterpreterBinaryNode
Binary node represents interpreter node with two children.
class InterpreterBinRelOperation
Interpreter operation that involves with two relations should inherit from this class.
class InterpreterBreak
class InterpreterCall
class InterpreterChoice
class InterpreterClear
class InterpreterCompoundNode
Compound node represents interpreter node with a list of children.
class InterpreterConditionalOperation
Encode a conditional operation for the interpreter node.
class InterpreterConjunction
class InterpreterConstant
class InterpreterConstraint
class InterpreterContext
Evaluation context for Interpreter operations.
class InterpreterDebugInfo
class InterpreterEmptinessCheck
class InterpreterEngine
This class translate the RAM Program into executable format and interpreter it.
class InterpreterEqRelation
Interpreter Equivalence Relation.
class InterpreterExistenceCheck
class InterpreterExit
class InterpreterExtend
class InterpreterFalse
class InterpreterFilter
class InterpreterIndex
An index is an abstraction of a data structure.
class InterpreterIndexAggregate
class InterpreterIndexChoice
class InterpreterIndexScan
class InterpreterIndirectRelation
Interpreter Indirect Relation.
class InterpreterIntrinsicOperator
class InterpreterIO
class InterpreterLogRelationTimer
class InterpreterLogSize
class InterpreterLogTimer
class InterpreterLoop
class InterpreterNegation
class InterpreterNestedIntrinsicOperator
class InterpreterNestedOperation
Encode a nested operation for the interpreter node.
class InterpreterNode
This is a shadow node for a ram::Node that is enriched for with local information so that the interpreter is executing quickly.
class InterpreterPackRecord
class InterpreterParallel
class InterpreterParallelAggregate
class InterpreterParallelChoice
class InterpreterParallelIndexAggregate
class InterpreterParallelIndexChoice
class InterpreterParallelIndexScan
class InterpreterParallelScan
class InterpreterProgInterface
Implementation of SouffleProgram interface for an interpreter instance.
class InterpreterProject
class InterpreterProvenanceExistenceCheck
struct InterpreterProvenanceUpdater
class InterpreterQuery
class InterpreterRelation
A relation, composed of a collection of indexes.
class InterpreterRelationSize
class InterpreterRelInterface
Wrapper class for interpreter relations.
class InterpreterScan
class InterpreterSequence
class InterpreterSubroutineArgument
class InterpreterSubroutineReturn
class InterpreterSuperInstruction
This class encodes information for a super-instruction, which is used to eliminate Number and TupleElement in index/project/existence operation.
class InterpreterSuperOperation
Interpreter node that utilizes the super instruction optimization should inherit from this class.
class InterpreterSwap
class InterpreterTrue
class InterpreterTupleElement
class InterpreterTupleOperation
class InterpreterUnaryNode
Unary node represents interpreter node with a single child.
class InterpreterUnpackRecord
class InterpreterUserDefinedOperator
class InterpreterViewContext
This class contains information for views (Hints) creation for ram::Query and ram::Parallel operation.
class InterpreterViewOperation
Interpreter operation that utilizes the index view from underlying relation should inherit from this class.
struct IntrinsicFunctorInfo
class IOSystem
struct IsPtrLike
struct IsPtrLike< Own< A > >
struct IsPtrLike< std::shared_ptr< A > >
struct IsPtrLike< std::weak_ptr< A > >
struct IterDerefWrapper
A wrapper for an iterator obtaining pointers of a certain type, dereferencing values before forwarding them to the consumer.
struct lambda_traits
A type trait enabling the deduction of type properties of lambdas.
class LambdaBTreeSet
A b-tree based set implementation.
class LeafNode
struct Lock
A small utility class for implementing simple locks.
class Logger
The class utilized to times for the souffle profiling tool.
class LogStatement
class LRUCache
An Least-Recently-Used cache for arbitrary element types.
class LRUCache< T, 0 >
class LRUCache< T, 1 >
class MainConfig
struct MainOption
class NodeGenerator
class NullaryIndex
An index wrapper for nullary indexes.
class OptimisticReadWriteLock
A 'sequential' non-locking implementation for an optimistic r/w lock.
class Order
An order to be enforced for storing tuples within indexes.
class ParserDriver
class PartitionedStream
A partitioned stream is a list of streams each covering a disjoint subset of a specific range.
class PiggyList
struct print_deref
A functor printing elements after dereferencing it.
class ProfileEventSingleton
Profile Event Singleton.
class ProgramFactory
Abstract program factory class.
class RandomInsertPiggyList
A PiggyList that allows insertAt functionality.
struct range
A utility class enabling representation of ranges by pairing two iterator instances marking lower and upper boundaries.
class ReadCinCSVFactory
class ReadCinJSONFactory
class ReadFileCSV
class ReadFileCSVFactory
class ReadFileJSON
class ReadFileJSONFactory
class ReadSQLiteFactory
class ReadStream
class ReadStreamCSV
class ReadStreamFactory
class ReadStreamJSON
class ReadStreamSQLite
class ReadWriteLock
class RecordMap
Bidirectional mappping between records and record references.
class RecordTable
class Relation
Object-oriented wrapper class for Souffle's templatized relations.
class RelationWrapper
Relation wrapper used internally in the generated Datalog program.
struct reverse
Use to range-for iterate in reverse.
class RuleBody
struct scanner_data
class ScreenBuffer
class SerialisationStream
class SignalHandler
Class SignalHandler captures signals and reports the context where the signal occurs.
class SingleValueIterator
An iterator to be utilized if there is only a single element to iterate over.
class SouffleProgram
Abstract base class for generated Datalog programs.
class SparseArray
A sparse array simulates an array associating to every element of uint32_t an element of a generic type T.
class SparseBitMap
A sparse bit-map is a bit map virtually assigning a bit value to every value if the uint32_t domain.
class SparseDisjointSet
class SpinLock
A 'sequential' non-locking implementation for a spin lock.
class SrcLocation
A class describing a range in an input file.
class Stream
An abstract perspective on a data range.
class SymbolTable
Global pool of re-usable strings.
class t_info
info relations
class t_nullaries
Nullary relations.
class Table
class TempFileStream
class TestMaxMatching
class TreeNode
class Trie
The most generic implementation of a Trie forming the top-level of any Trie storing tuples of arity > 1.
class Trie< 1u >
A template specialization for tries representing a set.
struct Tuple
The type of object stored within relations representing the actual tuple value.
class tuple
Defines a tuple for the OO interface such that relations with varying columns can be accessed.
class TupleRef
A type-erased reference to tuples.
class WriteCoutCSV
class WriteCoutCSVFactory
class WriteCoutJSON
class WriteCoutJSONFactory
class WriteCoutPrintSize
class WriteCoutPrintSizeFactory
class WriteFileCSV
class WriteFileCSVFactory
class WriteFileJSON
class WriteFileJSONFactory
class WriteSQLiteFactory
class WriteStream
class WriteStreamCSV
class WriteStreamFactory
class WriteStreamJSON
class WriteStreamSQLite
Typedefs
using block_t = uint64_t
template<std::size_t Arity>
using comparator = typename index_utils::get_full_index< Arity >::type::comparator
template<typename A , typename B >
using copy_const_t = std::conditional_t< std::is_const_v< A >, const B, B >
using IndexFactory = Own< InterpreterIndex >(*)(const Order &)
using IndexViewPtr = Own< IndexView >
using IntrinsicFunctors = std::vector< std::reference_wrapper< const IntrinsicFunctorInfo > >
using Nodes = std::set< SearchSignature >
template<typename A >
using Own = std::unique_ptr< A >
using parent_t = uint64_t
using RamDomain = int32_t
using RamFloat = float
using RamSigned = RamDomain
using RamUnsigned = uint32_t
using rank_t = uint8_t
template<std::size_t Arity>
using t_tuple = typename souffle::Tuple< RamDomain, Arity >
using time_point = std::chrono::high_resolution_clock::time_point
template<typename A >
using VecOwn = std::vector< Own< A > >
using yyscan_t = void *
Enumerations
enum AggregateOp {
AggregateOp::MAX, AggregateOp::MIN, AggregateOp::SUM, AggregateOp::FMAX,
AggregateOp::FMIN, AggregateOp::FSUM, AggregateOp::MEAN, AggregateOp::UMAX,
AggregateOp::UMIN, AggregateOp::USUM, AggregateOp::COUNT
}
Types of aggregation functions.
enum BinaryConstraintOp {
BinaryConstraintOp::EQ, BinaryConstraintOp::FEQ, BinaryConstraintOp::NE, BinaryConstraintOp::FNE,
BinaryConstraintOp::LT, BinaryConstraintOp::ULT, BinaryConstraintOp::FLT, BinaryConstraintOp::SLT,
BinaryConstraintOp::LE, BinaryConstraintOp::ULE, BinaryConstraintOp::FLE, BinaryConstraintOp::SLE,
BinaryConstraintOp::GT, BinaryConstraintOp::UGT, BinaryConstraintOp::FGT, BinaryConstraintOp::SGT,
BinaryConstraintOp::GE, BinaryConstraintOp::UGE, BinaryConstraintOp::FGE, BinaryConstraintOp::SGE,
BinaryConstraintOp::MATCH, BinaryConstraintOp::CONTAINS, BinaryConstraintOp::NOT_MATCH, BinaryConstraintOp::NOT_CONTAINS
}
Binary Constraint Operators.
enum FunctorOp {
FunctorOp::ORD, FunctorOp::STRLEN, FunctorOp::NEG, FunctorOp::FNEG,
FunctorOp::BNOT, FunctorOp::UBNOT, FunctorOp::LNOT, FunctorOp::ULNOT,
FunctorOp::F2I, FunctorOp::F2S, FunctorOp::F2U, FunctorOp::I2F,
FunctorOp::I2S, FunctorOp::I2U, FunctorOp::S2F, FunctorOp::S2I,
FunctorOp::S2U, FunctorOp::U2F, FunctorOp::U2I, FunctorOp::U2S,
FunctorOp::ADD, FunctorOp::SUB, FunctorOp::MUL, FunctorOp::DIV,
FunctorOp::EXP, FunctorOp::MAX, FunctorOp::MIN, FunctorOp::MOD,
FunctorOp::BAND, FunctorOp::BOR, FunctorOp::BXOR, FunctorOp::BSHIFT_L,
FunctorOp::BSHIFT_R, FunctorOp::BSHIFT_R_UNSIGNED, FunctorOp::LAND, FunctorOp::LOR,
FunctorOp::LXOR, FunctorOp::UADD, FunctorOp::USUB, FunctorOp::UMUL,
FunctorOp::UDIV, FunctorOp::UEXP, FunctorOp::UMAX, FunctorOp::UMIN,
FunctorOp::UMOD, FunctorOp::UBAND, FunctorOp::UBOR, FunctorOp::UBXOR,
FunctorOp::UBSHIFT_L, FunctorOp::UBSHIFT_R, FunctorOp::UBSHIFT_R_UNSIGNED, FunctorOp::ULAND,
FunctorOp::ULOR, FunctorOp::ULXOR, FunctorOp::FADD, FunctorOp::FSUB,
FunctorOp::FMUL, FunctorOp::FDIV, FunctorOp::FEXP, FunctorOp::FMAX,
FunctorOp::FMIN, FunctorOp::SMAX, FunctorOp::SMIN, FunctorOp::RANGE,
FunctorOp::URANGE, FunctorOp::FRANGE, FunctorOp::CAT, FunctorOp::SUBSTR
}
enum InterpreterNodeType {
I_Constant, I_TupleElement, I_AutoIncrement, I_IntrinsicOperator,
I_UserDefinedOperator, I_NestedIntrinsicOperator, I_PackRecord, I_SubroutineArgument,
I_True, I_False, I_Conjunction, I_Negation,
I_EmptinessCheck, I_RelationSize, I_ExistenceCheck, I_ProvenanceExistenceCheck,
I_Constraint, I_TupleOperation, I_Scan, I_ParallelScan,
I_IndexScan, I_ParallelIndexScan, I_Choice, I_ParallelChoice,
I_IndexChoice, I_ParallelIndexChoice, I_UnpackRecord, I_Aggregate,
I_ParallelAggregate, I_IndexAggregate, I_ParallelIndexAggregate, I_Break,
I_Filter, I_Project, I_SubroutineReturn, I_Sequence,
I_Parallel, I_Loop, I_Exit, I_LogRelationTimer,
I_LogTimer, I_DebugInfo, I_Clear, I_LogSize,
I_IO, I_Query, I_Extend, I_Swap,
I_Call
}
enum RelationQualifier {
RelationQualifier::INPUT, RelationQualifier::OUTPUT, RelationQualifier::PRINTSIZE, RelationQualifier::OVERRIDABLE,
RelationQualifier::INLINE, RelationQualifier::MAGIC, RelationQualifier::SUPPRESSED
}
Space of qualifiers that a relation can have.
enum RelationRepresentation {
RelationRepresentation::DEFAULT, RelationRepresentation::BRIE, RelationRepresentation::BTREE, RelationRepresentation::EQREL,
RelationRepresentation::INFO
}
Space of internal representations that a relation can have.
enum RelationTag {
RelationTag::INPUT, RelationTag::OUTPUT, RelationTag::PRINTSIZE, RelationTag::OVERRIDABLE,
RelationTag::INLINE, RelationTag::MAGIC, RelationTag::SUPPRESSED, RelationTag::BRIE,
RelationTag::BTREE, RelationTag::EQREL
}
Space of user-chosen tags that a relation can have.
enum TypeAttribute {
TypeAttribute::Symbol, TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float,
TypeAttribute::Record, TypeAttribute::ADT
}
Functions
std::string absPath (const std::string &path)
C++-style realpath.
std::pair< uint8_t, uint8_t > aggregateArity (AggregateOp op)
template<typename Container , typename UnaryPredicate >
bool all_of (const Container &c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
template<typename Container , typename UnaryPredicate >
bool any_of (const Container &c, UnaryPredicate p)
A generic test checking whether any elements within a container satisfy a certain predicate.
void appendStmt (VecOwn< ram::Statement > &stmtList, Own< ram::Statement > stmt)
append statement to a list of statements
template<typename B , typename A >
auto as (A *x)
Helpers for dynamic_casting without having to specify redundant type qualifiers.
template<typename B , typename A >
std::enable_if_t< std::is_base_of_v< A, B >, copy_const_t< A, B > * > as (A &x)
template<typename B , typename A >
B * as (const std::unique_ptr< A > &x)
std::string baseName (const std::string &filename)
bool canBeParsedAsRamFloat (const std::string &string)
Can a string be parsed as RamFloat.
bool canBeParsedAsRamSigned (const std::string &string)
Can a string be parsed as RamSigned.
bool canBeParsedAsRamUnsigned (const std::string &string)
Can a string be parsed as RamUnsigned.
template<typename toType , typename baseType >
bool castEq (const baseType *left, const baseType *right)
Cast the values, from baseType to toType and compare using ==.
template<typename A >
std::unique_ptr< A > clone (const A *node)
template<typename A >
std::unique_ptr< A > clone (const std::unique_ptr< A > &node)
template<typename A , typename B >
auto clone (const std::pair< A, B > &p)
template<typename A >
auto clone (const std::vector< A *> &xs)
template<typename A >
auto clone (const std::vector< std::unique_ptr< A >> &xs)
void compileToBinary (std::string compileCmd, const std::string &sourceFilename)
Compiles the given source file to a binary file.
template<typename C >
bool contains (const C &container, const typename C::value_type &element)
A utility to check generically whether a given element is contained in a given container.
template<typename A >
bool contains (const std::set< A > &container, const A &element)
template<typename C >
bool contains (const C &container, const typename C::value_type::first_type &element)
Version of contains specialised for maps.
std::string convertDotToSVG (const std::string &dotSpec)
AggregateOp convertOverloadedAggregator (const AggregateOp op, const TypeAttribute type)
Convert aggregator to a give type.
BinaryConstraintOp convertOverloadedConstraint (const BinaryConstraintOp constraintOp, const TypeAttribute toType)
Convert Constraint to work with requested type.
BinaryConstraintOp convertStrictToNotEqualConstraint (const BinaryConstraintOp constraintOp)
BinaryConstraintOp convertStrictToWeakIneqConstraint (const BinaryConstraintOp constraintOp)
Own< InterpreterIndex > createBrieIndex (const Order &order)
Own< InterpreterIndex > createBTreeIndex (const Order &order)
Own< InterpreterIndex > createBTreeProvenanceIndex (const Order &)
Own< InterpreterIndex > createEqrelIndex (const Order &order)
Own< InterpreterIndex > createIndirectIndex (const Order &)
template<typename Iter >
IterDerefWrapper< Iter > derefIter (const Iter &iter)
A factory function enabling the construction of a dereferencing iterator utilizing the automated deduction of template parameters.
std::string dirName (const std::string &name)
C++-style dirname.
long duration_in_ns (const time_point &start, const time_point &end)
long duration_in_us (const time_point &start, const time_point &end)
bool endsWith (const std::string &value, const std::string &ending)
Determines whether the given value string ends with the given end string.
template<typename T >
bool equal_ptr (const T *a, const T *b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
template<typename T >
bool equal_ptr (const std::unique_ptr< T > &a, const std::unique_ptr< T > &b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
template<typename Container , typename Comparator >
bool equal_targets (const Container &a, const Container &b, const Comparator &comp)
A function testing whether two containers are equal with the given Comparator.
template<typename T , template< typename... > class Container>
bool equal_targets (const Container< T *> &a, const Container< T *> &b)
A function testing whether two containers of pointers are referencing equivalent targets.
template<typename T , template< typename... > class Container>
bool equal_targets (const Container< std::unique_ptr< T >> &a, const Container< std::unique_ptr< T >> &b)
A function testing whether two containers of unique pointers are referencing equivalent targets.
template<typename Key , typename Value >
bool equal_targets (const std::map< Key, std::unique_ptr< Value >> &a, const std::map< Key, std::unique_ptr< Value >> &b)
A function testing whether two maps of unique pointers are referencing to equivalent targets.
std::string escape (const std::string &inputString, const std::string &needle, const std::string &replacement)
std::string escape (const std::string &inputString)
std::string escapeJSONstring (const std::string &JSONstr)
Escape JSON string.
std::stringstream execStdOut (char const *cmd)
std::stringstream execStdOut (std::string const &cmd)
void executeBinary (const std::string &binaryFilename)
Executes a binary file.
bool existDir (const std::string &name)
Check whether a directory exists in the file system.
bool existFile (const std::string &name)
Check whether a file exists in the file system.
void explain (SouffleProgram &prog, bool ncurses)
template<typename... Args>
void fatal (const char *format, const Args &... args)
std::string fileExtension (const std::string &path)
File extension, with all else removed.
template<typename A , typename F >
std::vector< A > filter (std::vector< A > xs, F &&f)
Filter a vector to include certain elements.
template<typename A , typename F >
std::vector< A > filterNot (std::vector< A > xs, F &&f)
Filter a vector to exclude certain elements.
std::string findTool (const std::string &tool, const std::string &base, const std::string &path)
IntrinsicFunctors functorBuiltIn (FunctorOp op)
IntrinsicFunctors functorBuiltIn (std::string_view symbol)
IntrinsicFunctors functorBuiltIn (std::string_view symbol, const std::vector< TypeAttribute > &params)
std::stringstream & genJsonRules (std::stringstream &ss, const std::string &name, size_t maxRows)
std::vector< TypeAttribute > getBinaryConstraintTypes (const BinaryConstraintOp op)
Get type binary constraint operates on.
std::string getCurrentFilename (const std::vector< std::string > &filenames)
BinaryConstraintOp getEqConstraint (const std::string &type)
BinaryConstraintOp getGreaterEqualConstraint (const std::string &type)
BinaryConstraintOp getGreaterThanConstraint (const std::string &type)
template<typename C >
C::value_type getIf (const C &container, std::function< bool(const typename C::value_type)> pred)
Returns the first element in a container that satisfies a given predicate, nullptr otherwise.
souffle::SouffleProgram * getInstance (const char *p)
BinaryConstraintOp getLessEqualConstraint (const std::string &type)
BinaryConstraintOp getLessThanConstraint (const std::string &type)
FunctorOp getMaxOp (const std::string &type)
FunctorOp getMinOp (const std::string &type)
Given a type of an an attribute it returns the appropriate min/max functor operation.
template<typename C >
C::mapped_type const & getOr (const C &container, typename C::key_type key, const typename C::mapped_type &defaultValue)
Get value for a given key; if not found, return default value.
Lock & getOutputLock ()
Obtains a reference to the lock synchronizing output operations.
RelationQualifier getRelationQualifierFromTag (const RelationTag &tag)
Get the corresponding RelationQualifier for a valid RelationTag.
RelationRepresentation getRelationRepresentationFromTag (const RelationTag &tag)
Get the corresponding RelationRepresentation for a valid RelationTag.
ss<< R"_("code": [)_";bool firstCol=true;while(getline(source_file, str)) { comma(firstCol, ",\");ss<< '"' << Tools::cleanJsonOut(str) << '"';} ss<< "],\";source_file.close();} auto usages=getUsageStats(100);auto beginTime=run-> getStarttime ()
TypeAttribute getTypeAttributeAggregate (const AggregateOp op)
Get return type of the aggregate.
std::string identifier (std::string id)
Valid C++ identifier, note that this does not ensure the uniqueness of identifiers returned.
template<typename B , typename A >
bool isA (A *x)
Checks if the object of type Source can be casted to type Destination.
template<typename B , typename A >
std::enable_if_t< std::is_base_of_v< A, B >, bool > isA (A &x)
template<typename B , typename A >
bool isA (const std::unique_ptr< A > &x)
bool isEqConstraint (const BinaryConstraintOp constraintOp)
bool isExecutable (const std::string &name)
Check whether a given file exists and it is an executable.
bool isFunctorMultiResult (FunctorOp op)
bool isGreaterEqual (const BinaryConstraintOp constraintOp)
bool isGreaterThan (const BinaryConstraintOp constraintOp)
bool isInfixFunctorOp (std::string_view symbol)
Determines whether a functor should be written using infix notation (e.g.
bool isInfixFunctorOp (const FunctorOp op)
bool isLessEqual (const BinaryConstraintOp constraintOp)
bool isLessThan (const BinaryConstraintOp constraintOp)
bool isNumber (const char *str)
Check whether a string is a sequence of digits.
bool isOrderedBinaryConstraintOp (const BinaryConstraintOp op)
Determines whether arguments of constraint are orderable.
bool isOverloaded (const BinaryConstraintOp constraintOp)
Utility function, informing whether constraint is overloaded.
bool isOverloadedAggregator (const AggregateOp op)
bool isOverloadedFunctor (std::string_view symbol)
Indicate whether a functor is overloaded.
bool isPrefix (const std::string &prefix, const std::string &element)
Determine if one string is a prefix of another.
bool isRelationQualifierTag (const RelationTag &tag)
Check if a given relation tag is a relation qualifier.
bool isRelationRepresentationTag (const RelationTag &tag)
Check if a given relation tag sets a relation representation.
bool isStrictIneqConstraint (const BinaryConstraintOp constraintOp)
bool isValidFunctorOpArity (std::string_view symbol, size_t arity)
bool isWeakIneqConstraint (const BinaryConstraintOp constraintOp)
template<typename Iter , typename Printer >
detail::joined_sequence< Iter, Printer > join (const Iter &a, const Iter &b, const std::string &sep, const Printer &p)
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
template<typename Iter , typename T = typename Iter::value_type>
detail::joined_sequence< Iter, detail::print< id< T > > > join (const Iter &a, const Iter &b, const std::string &sep=",")
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
template<typename Container , typename Printer , typename Iter = typename Container::const_iterator>
detail::joined_sequence< Iter, Printer > join (const Container &c, const std::string &sep, const Printer &p)
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
template<typename Container , typename Iter = typename Container::const_iterator, typename T = typename Iter::value_type>
std::enable_if_t<!JoinShouldDeref< T >, detail::joined_sequence< Iter, detail::print< id< T > > > > join (const Container &c, const std::string &sep=",")
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
template<typename Container , typename Iter = typename Container::const_iterator, typename T = typename Iter::value_type>
std::enable_if_t< JoinShouldDeref< T >, detail::joined_sequence< Iter, detail::print< deref< T > > > > join (const Container &c, const std::string &sep=",")
int main (int argc, char **argv)
template<typename Iter >
range< Iter > make_range (const Iter &a, const Iter &b)
A utility function enabling the construction of ranges without explicitly specifying the iterator type.
template<typename A , typename F >
auto map (const std::vector< A > &xs, F &&f)
Applies a function to each element of a vector and returns the results.
template<typename A , typename B = A, typename... Args>
Own< A > mk (Args &&... xs)
BinaryConstraintOp negatedConstraintOp (const BinaryConstraintOp op)
Negated Constraint Operator Each operator requires a negated operator which is necessary for the expansion of complex rule bodies with disjunction and negation.
template<typename Container , typename UnaryPredicate >
bool none_of (const Container &c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
time_point now ()
std::ostream & operator<< (std::ostream &os, TypeAttribute T)
std::ostream & operator<< (std::ostream &os, AggregateOp op)
std::ostream & operator<< (std::ostream &os, BinaryConstraintOp x)
std::ostream & operator<< (std::ostream &out, const Order &order)
std::ostream & operator<< (std::ostream &out, TupleRef ref)
std::ostream & operator<< (std::ostream &os, RelationTag qualifier)
std::ostream & operator<< (std::ostream &os, RelationQualifier qualifier)
template<typename T , unsigned size>
std::ostream & operator<< (std::ostream &out, const LRUCache< T, size > &cache)
std::ostream & operator<< (std::ostream &out, const RuleBody &body)
std::ostream & operator<< (std::ostream &os, RelationRepresentation representation)
std::ostream & operator<< (std::ostream &os, FunctorOp op)
template<std::size_t Arity>
RamDomain pack (RecordTable &recordTab, Tuple< RamDomain, Arity > tuple)
helper to convert tuple to record reference for the synthesiser
std::string pathJoin (const std::string &first, const std::string &second)
Join two paths together; note that this does not resolve overlaps or relative paths.
void printHTMLGraph (std::ostream &out, const std::string &dotSpec, const std::string &id)
template<typename To = RamDomain, typename From >
To ramBitCast (From source)
In C++20 there will be a new way to cast between types by reinterpreting bits (std::bit_cast), but as of January 2020 it is not yet supported.
RamFloat RamFloatFromString (const std::string &str, std::size_t *position=nullptr)
Converts a string to a RamFloat.
RamSigned RamSignedFromString (const std::string &str, std::size_t *position=nullptr, const int base=10)
Converts a string to a RamSigned.
RamUnsigned RamUnsignedFromString (const std::string &str, std::size_t *position=nullptr, const int base=10)
Converts a string to a RamUnsigned.
std::string simpleName (const std::string &path)
File name, with extension removed.
std::vector< std::string > split (const std::string &s, char delim, int times=-1)
utility function to split a string
std::vector< std::string > splitString (const std::string &str, char delimiter)
Splits a string given a delimiter.
std::string stringify (const std::string &input)
Stringify a string using escapes for escape, newline, tab, double-quotes and semicolons.
std::string tempFile ()
Generate temporary file.
TEST (Matching, StaticTest_1)
TEST (SparseArray, Basic)
TEST (Matching, StaticTest_2)
TEST (SparseArray, Limits)
TEST (SparseArray, Iterator)
TEST (SparseArray, IteratorStress)
TEST (SparseArray, IteratorStress2)
TEST (SparseArray, Find)
TEST (SparseArray, Find2)
TEST (SparseArray, Copy)
TEST (SparseArray, Merge)
TEST (SparseArray, LowerBound)
TEST (SparseArray, LowerBound2)
TEST (SparseArray, UpperBound)
TEST (SparseArray, UpperBound2)
TEST (SparseArray, MemoryUsage)
TEST (SparseBitMap, Basic)
TEST (SparseBitMap, Stress)
TEST (SparseBitMap, Iterator)
TEST (SparseBitMap, IteratorStress2)
TEST (SparseBitMap, Find)
TEST (SparseBitMap, Size)
TEST (SparseBitMap, CopyAndMerge)
TEST (Trie, Basic)
TEST (Trie, Iterator)
TEST (Trie, IteratorStress_1D)
TEST (Trie, IteratorStress_2D)
TEST (Trie, IteratorStress_3D)
TEST (Trie, IteratorStress_4D)
TEST (Trie, BoundaryTest_1D)
TEST (Trie, BoundaryTest_1D_2)
TEST (Trie, BoundaryTest_1D_Stress)
TEST (Trie, BoundaryTest_1D_Stress_Dense)
TEST (Trie, BoundaryTest_2D)
TEST (Trie, BoundaryTest_2D_2)
TEST (Trie, BoundaryTest_2D_Stress)
TEST (Trie, BoundaryTest_2D_Stress_Dense)
TEST (Trie, BoundaryTest_3D)
TEST (Trie, BoundaryTest_3D_2)
TEST (Trie, BoundaryTest_3D_Stress)
TEST (Trie, RangeQuery)
TEST (Trie, RangeQuery_1D)
TEST (Trie, RangeQuery_2D)
TEST (Trie, RangeQuery_3D)
TEST (Trie, RangeQueryStress)
TEST (Trie, Merge_1D)
TEST (Trie, Merge_2D)
TEST (Trie, Merge_3D)
TEST (Trie, Merge_Stress)
TEST (Trie, Merge_Bug)
TEST (Trie, Size)
TEST (Trie, Limits)
TEST (Trie, Parallel)
template<typename T >
detail::multiplying_printer< T > times (const T &value, unsigned num)
A utility printing a given value multiple times.
std::string toBase64 (const std::string &data)
BinaryConstraintOp toBinaryConstraintOp (const std::string &symbol)
Converts symbolic representation of an operator to the operator.
char const * toBinaryConstraintSymbol (const BinaryConstraintOp op)
Converts operator to its symbolic representation.
template<typename T >
std::vector< T * > toPtrVector (const std::vector< std::unique_ptr< T >> &v)
A utility function enabling the creation of a vector of pointers.
const std::string & toString (const std::string &str)
A generic function converting strings into strings (trivial case).
template<typename T >
std::enable_if< detail::is_printable< T >::value, std::string >::type toString (const T &value)
A generic function converting arbitrary objects to strings by utilizing their print capability.
template<typename T >
std::enable_if<!detail::is_printable< T >::value, std::string >::type toString (const T &)
A fallback for the to-string function in case an unprintable object is supposed to be printed.
template<typename T >
std::vector< T > toVector ()
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
template<typename T , typename... R>
std::vector< T > toVector (const T &first, const R &... rest)
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
std::string unescape (const std::string &inputString, const std::string &needle, const std::string &replacement)
std::string unescape (const std::string &inputString)
std::string which (const std::string &name)
Simple implementation of a which tool.
Variables
else
constexpr char FUNCTOR_INTRINSIC_PREFIX_NEGATE_NAME [] = "negate"
ss<< R"_("usage": [)_";bool firstRow=true;Usage previousUsage=*usages.begin();previousUsage.time=beginTime;for(auto usage :usages) { comma(firstRow);ss<< '[';ss<<(usage.time - beginTime).count()/1000000.0<< ", ";ss<< 100.0 *(usage.usertime - previousUsage.usertime)/(usage.time - previousUsage.time)<< ", ";ss<< 100.0 *(usage.systemtime - previousUsage.systemtime)/(usage.time - previousUsage.time)<< ", ";ss<< usage.maxRSS *1024<< ", ";ss<< '"'; bool firstCol = true; for (auto& cur : out.getProgramRun()->getRelationsAtTime(previousUsage.time, usage.time)) { comma(firstCol); ss << cur-> getName ()
template<typename T >
constexpr bool isRamType
template<typename A >
constexpr bool JoinShouldDeref = IsPtrLike<A>::value && !std::is_same_v<A, char const*>
constexpr RamFloat MAX_RAM_FLOAT = std::numeric_limits<RamFloat>::max()
constexpr RamSigned MAX_RAM_SIGNED = std::numeric_limits<RamSigned>::max()
constexpr RamUnsigned MAX_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::max()
constexpr RamFloat MIN_RAM_FLOAT = std::numeric_limits<RamFloat>::lowest()
constexpr RamSigned MIN_RAM_SIGNED = std::numeric_limits<RamSigned>::min()
lower and upper boundaries for the ram types
constexpr RamUnsigned MIN_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::min()
constexpr block_t rank_mask = (1ul << split_size) - 1
constexpr uint8_t split_size = 8u
Typedef Documentation
block_t
using souffle::block_t = typedef uint64_t
Definition at line 41 of file UnionFind.h.
comparator
template<std::size_t Arity> using souffle::comparator = typedef typename index_utils::get_full_index<Arity>::type::comparator
Definition at line 32 of file InterpreterBTreeIndex.cpp.
copy_const_t
template<typename A , typename B > using souffle::copy_const_t = typedef std::conditional_t<std::is_const_v<A>, const B, B>
Definition at line 144 of file MiscUtil.h.
IndexFactory
using souffle::IndexFactory = typedef Own<InterpreterIndex> (*)(const Order&)
Definition at line 856 of file InterpreterIndex.h.
IndexViewPtr
using souffle::IndexViewPtr = typedef Own<IndexView>
Definition at line 390 of file InterpreterIndex.h.
IntrinsicFunctors
using souffle::IntrinsicFunctors = typedef std::vector<std::reference_wrapper<const IntrinsicFunctorInfo> >
Definition at line 123 of file FunctorOps.h.
Nodes
using souffle::Nodes = typedef std::set<SearchSignature>
Definition at line 31 of file max_matching_test.cpp.
Own
template<typename A > using souffle::Own = typedef std::unique_ptr<A>
Definition at line 36 of file ContainerUtil.h.
parent_t
using souffle::parent_t = typedef uint64_t
Definition at line 35 of file UnionFind.h.
RamDomain
using souffle::RamDomain = typedef int32_t
Definition at line 45 of file RamTypes.h.
RamFloat
using souffle::RamFloat = typedef float
Definition at line 49 of file RamTypes.h.
RamSigned
using souffle::RamSigned = typedef RamDomain
Definition at line 46 of file RamTypes.h.
RamUnsigned
using souffle::RamUnsigned = typedef uint32_t
Definition at line 47 of file RamTypes.h.
rank_t
using souffle::rank_t = typedef uint8_t
Definition at line 33 of file UnionFind.h.
t_tuple
template<std::size_t Arity> using souffle::t_tuple = typedef typename souffle::Tuple<RamDomain, Arity>
Definition at line 36 of file InterpreterBTreeIndex.cpp.
time_point
using souffle::time_point = typedef std::chrono::high_resolution_clock::time_point
Definition at line 79 of file MiscUtil.h.
VecOwn
template<typename A > using souffle::VecOwn = typedef std::vector<Own<A> >
Definition at line 39 of file ContainerUtil.h.
yyscan_t
using souffle::yyscan_t = typedef void*
Definition at line 42 of file ParserDriver.h.
Enumeration Type Documentation
AggregateOp
enum souffle::AggregateOp strong
Types of aggregation functions.
Enumerator
MAX
MIN
SUM
FMAX
FMIN
FSUM
MEAN
UMAX
UMIN
USUM
COUNT
Definition at line 28 of file AggregateOp.h.
{
     MAX,
     MIN,
     SUM,
     FMAX,
     FMIN,
     FSUM,
     MEAN,
     UMAX,
     UMIN,
     USUM,
     COUNT,
 };
BinaryConstraintOp
enum souffle::BinaryConstraintOp strong
Binary Constraint Operators.
Enumerator
EQ
FEQ
NE
FNE
LT
ULT
FLT
SLT
LE
ULE
FLE
SLE
GT
UGT
FGT
SGT
GE
UGE
FGE
SGE
MATCH
CONTAINS
NOT_MATCH
NOT_CONTAINS
Definition at line 35 of file BinaryConstraintOps.h.
{
     EQ,           // equivalence of two values
     FEQ,          // float equiv; b/c NaNs are never equiv
     NE,           // whether two values are different
     FNE,          // float diff; b/c NaNs are always different
     LT,           // signed <
     ULT,          // Unsigned <
     FLT,          // Float <
     SLT,          // Symbol <
     LE,           // signed
     ULE,          // Unsigned
     FLE,          // Float
     SLE,          // Symbol
     GT,           // signed >
     UGT,          // unsigned >
     FGT,          // float >
     SGT,          // Symbol >
     GE,           // signed
     UGE,          // Unsigned
     FGE,          // Float
     SGE,          // Symbol
     MATCH,        // matching string
     CONTAINS,     // whether a sub-string is contained in a string
     NOT_MATCH,    // not matching string
     NOT_CONTAINS  // whether a sub-string is not contained in a string
 };
FunctorOp
enum souffle::FunctorOp strong
Enumerator
ORD
Unary Functor Operators.
STRLEN
NEG
FNEG
BNOT
UBNOT
LNOT
ULNOT
F2I
F2S
F2U
I2F
I2S
I2U
S2F
S2I
S2U
U2F
U2I
U2S
ADD
Binary Functor Operators.
SUB
MUL
DIV
EXP
MAX
MIN
MOD
BAND
BOR
BXOR
BSHIFT_L
BSHIFT_R
BSHIFT_R_UNSIGNED
LAND
LOR
LXOR
UADD
USUB
UMUL
UDIV
UEXP
UMAX
UMIN
UMOD
UBAND
UBOR
UBXOR
UBSHIFT_L
UBSHIFT_R
UBSHIFT_R_UNSIGNED
ULAND
ULOR
ULXOR
FADD
FSUB
FMUL
FDIV
FEXP
FMAX
FMIN
SMAX
SMIN
RANGE
URANGE
FRANGE
CAT
SUBSTR
Ternary Functor Operators.
Definition at line 29 of file FunctorOps.h.
                      {
     /** Unary Functor Operators */
     ORD,     // ordinal number of a string
     STRLEN,  // length of a string
     NEG,     // Signed numeric negation
     FNEG,    // Float numeric negation
     BNOT,    // Signed bitwise negation
     UBNOT,   // Unsigned bitwise negation
     LNOT,    // Signed logical negation
     ULNOT,   // Unsigned logical negation
     F2I,  // float     to signed
     F2S,  // float     to symbol
     F2U,  // float     to unsigned
     I2F,  // signed    to signed
     I2S,  // signed    to symbol     (overload base case)
     I2U,  // signed    to unsigned
     S2F,  // symbol    to float      (overload base case)
     S2I,  // symbol    to signed     (overload base case)
     S2U,  // symbol    to unsigned   (overload base case)
     U2F,  // unsigned  to float
     U2I,  // unsigned  to signed
     U2S,  // unsigned  to symbol
     /** Binary Functor Operators */
     ADD,                 // addition
     SUB,                 // subtraction
     MUL,                 // multiplication
     DIV,                 // division
     EXP,                 // exponent
     MAX,                 // max of two numbers
     MIN,                 // min of two numbers
     MOD,                 // modulus
     BAND,                // bitwise and
     BOR,                 // bitwise or
     BXOR,                // bitwise exclusive or
     BSHIFT_L,            // bitwise shift left
     BSHIFT_R,            // bitwise shift right
     BSHIFT_R_UNSIGNED,   // bitwise shift right (unsigned)
     LAND,                // logical and
     LOR,                 // logical or
     LXOR,                // logical xor
     UADD,                // addition
     USUB,                // subtraction
     UMUL,                // multiplication
     UDIV,                // division
     UEXP,                // exponent
     UMAX,                // max of two numbers
     UMIN,                // min of two numbers
     UMOD,                // modulus
     UBAND,               // bitwise and
     UBOR,                // bitwise or
     UBXOR,               // bitwise exclusive or
     UBSHIFT_L,           // bitwise shift right
     UBSHIFT_R,           // bitwise shift right
     UBSHIFT_R_UNSIGNED,  // bitwise shift right (unsigned)
     ULAND,               // logical and
     ULOR,                // logical or
     ULXOR,               // logical xor
     FADD,                // addition
     FSUB,                // subtraction
     FMUL,                // multiplication
     FDIV,                // division
     FEXP,                // exponent
     FMAX,                // max of two floats
     FMIN,                // min of two floats
     SMAX,                // max of two symbols
     SMIN,                // min of two symbols
     // Produces values within a numeric range. Format is `range(bgn, endExcl, step = 1)`.
     // e.g. `range(0, 5)` produces the sequence `0, 1, 2, 3, 4`.
     //      `range(5, 3.75, -0.5)` produces the sequence `5, 4.5, 4`.
     //      `range(5, x, 0)` produces the sequence `5` iff `x` != 5.
     RANGE,
     URANGE,
     FRANGE,
     CAT,  // string concatenation
     /** Ternary Functor Operators */
     SUBSTR,  // substring
 };
InterpreterNodeType
enum souffle::InterpreterNodeType
Enumerator
I_Constant
I_TupleElement
I_AutoIncrement
I_IntrinsicOperator
I_UserDefinedOperator
I_NestedIntrinsicOperator
I_PackRecord
I_SubroutineArgument
I_True
I_False
I_Conjunction
I_Negation
I_EmptinessCheck
I_RelationSize
I_ExistenceCheck
I_ProvenanceExistenceCheck
I_Constraint
I_TupleOperation
I_Scan
I_ParallelScan
I_IndexScan
I_ParallelIndexScan
I_Choice
I_ParallelChoice
I_IndexChoice
I_ParallelIndexChoice
I_UnpackRecord
I_Aggregate
I_ParallelAggregate
I_IndexAggregate
I_ParallelIndexAggregate
I_Break
I_Filter
I_Project
I_SubroutineReturn
I_Sequence
I_Parallel
I_Loop
I_Exit
I_LogRelationTimer
I_LogTimer
I_DebugInfo
I_Clear
I_LogSize
I_IO
I_Query
I_Extend
I_Swap
I_Call
Definition at line 43 of file InterpreterNode.h.
{
     I_Constant,
     I_TupleElement,
     I_AutoIncrement,
     I_IntrinsicOperator,
     I_UserDefinedOperator,
     I_NestedIntrinsicOperator,
     I_PackRecord,
     I_SubroutineArgument,
     I_True,
     I_False,
     I_Conjunction,
     I_Negation,
     I_EmptinessCheck,
     I_RelationSize,
     I_ExistenceCheck,
     I_ProvenanceExistenceCheck,
     I_Constraint,
     I_TupleOperation,
     I_Scan,
     I_ParallelScan,
     I_IndexScan,
     I_ParallelIndexScan,
     I_Choice,
     I_ParallelChoice,
     I_IndexChoice,
     I_ParallelIndexChoice,
     I_UnpackRecord,
     I_Aggregate,
     I_ParallelAggregate,
     I_IndexAggregate,
     I_ParallelIndexAggregate,
     I_Break,
     I_Filter,
     I_Project,
     I_SubroutineReturn,
     I_Sequence,
     I_Parallel,
     I_Loop,
     I_Exit,
     I_LogRelationTimer,
     I_LogTimer,
     I_DebugInfo,
     I_Clear,
     I_LogSize,
     I_IO,
     I_Query,
     I_Extend,
     I_Swap,
     I_Call
 };
RelationQualifier
enum souffle::RelationQualifier strong
Space of qualifiers that a relation can have.
Enumerator
INPUT
OUTPUT
PRINTSIZE
OVERRIDABLE
INLINE
MAGIC
SUPPRESSED
Definition at line 39 of file RelationTag.h.
{
     INPUT,        // relation read from csv
     OUTPUT,       // relation written to csv
     PRINTSIZE,    // number of tuples written to stdout
     OVERRIDABLE,  // rules defined in component can be overwritten by sub-component
     INLINE,       // inlined
     MAGIC,        // enable magic-set on this relation
     SUPPRESSED,   // warnings suppressed
 };
RelationRepresentation
enum souffle::RelationRepresentation strong
Space of internal representations that a relation can have.
Enumerator
DEFAULT
BRIE
BTREE
EQREL
INFO
Definition at line 50 of file RelationTag.h.
{
     DEFAULT,  // use default data-structure
     BRIE,     // use brie data-structure
     BTREE,    // use btree data-structure
     EQREL,    // use union data-structure
     INFO,     // info relation for provenance
 };
RelationTag
enum souffle::RelationTag strong
Space of user-chosen tags that a relation can have.
Enumerator
INPUT
OUTPUT
PRINTSIZE
OVERRIDABLE
INLINE
MAGIC
SUPPRESSED
BRIE
BTREE
EQREL
Definition at line 25 of file RelationTag.h.
{
     INPUT,        // relation read from csv
     OUTPUT,       // relation written to csv
     PRINTSIZE,    // number of tuples written to stdout
     OVERRIDABLE,  // rules defined in component can be overwritten by sub-component
     INLINE,       // inlined
     MAGIC,        // enable magic-set on this relation
     SUPPRESSED,   // warnings suppressed
     BRIE,         // use brie data-structure
     BTREE,        // use btree data-structure
     EQREL,        // use union data-structure
 };
TypeAttribute
enum souffle::TypeAttribute strong
Enumerator
Symbol
Signed
Unsigned
Float
Record
ADT
Definition at line 28 of file TypeAttribute.h.
{
     Symbol,    // Symbol
     Signed,    // Signed number
     Unsigned,  // Unsigned number
     Float,     // Floating point number.
     Record,    // Record
     ADT,       // ADT
 };
Function Documentation
absPath()
std::string souffle::absPath (const std::string & path) inline
C++-style realpath.
Definition at line 150 of file FileUtil.h.
Referenced by findTool().
{
     char buf[PATH_MAX];
     char* res = realpath(path.c_str(), buf);
     return (res == nullptr) ? "" : std::string(buf);
 }
aggregateArity()
std::pair<uint8_t, uint8_t> souffle::aggregateArity (AggregateOp op) inline
Definition at line 68 of file AggregateOp.h.
References COUNT, FMAX, FMIN, FSUM, MAX, MEAN, MIN, SUM, UMAX, UMIN, UNREACHABLE_BAD_CASE_ANALYSIS, and USUM.
{
     switch (op) {
         case AggregateOp::COUNT: return {0, 0};
         case AggregateOp::FMAX:
         case AggregateOp::FMIN:
         case AggregateOp::FSUM:
         case AggregateOp::MAX:
         case AggregateOp::MEAN:
         case AggregateOp::MIN:
         case AggregateOp::SUM:
         case AggregateOp::UMAX:
         case AggregateOp::UMIN:
         case AggregateOp::USUM: return {1, 1};
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
all_of()
template<typename Container , typename UnaryPredicate > bool souffle::all_of (const Container & c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
Parameters
c the container
p the predicate
Returns
true if for all elements x in c the predicate p(x) is true, false otherwise; for empty containers the result is always true
Definition at line 104 of file FunctionalUtil.h.
References p.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkArgument(), functorBuiltIn(), souffle::ast::analysis::isOfKind(), souffle::ast::analysis::isOfRootType(), souffle::ast::analysis::TypeSet::isSubsetOf(), souffle::ast::analysis::isSubtypeOf(), souffle::ConstConstraint::verify(), souffle::ast::transform::TypeChecker::visitAtom(), and souffle::ast::transform::TypeChecker::visitBranchInit().
{
     return std::all_of(c.begin(), c.end(), p);
 }
any_of()
template<typename Container , typename UnaryPredicate > bool souffle::any_of (const Container & c, UnaryPredicate p)
A generic test checking whether any elements within a container satisfy a certain predicate.
Parameters
c the container
p the predicate
Returns
true if there is an element x in c such that predicate p(x) is true, false otherwise; for empty containers the result is always false
Definition at line 118 of file FunctionalUtil.h.
References p.
Referenced by souffle::ParserDriver::addTag(), souffle::AstToRamTranslator::ClauseTranslator::createValueIndex(), souffle::ast::analysis::haveCommonSupertype(), souffle::AstToRamTranslator::ValueIndex::isGenerator(), souffle::ast::analysis::isSubtypeOf(), isValidFunctorOpArity(), souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), and souffle::ast::transform::TypeChecker::visitBinaryConstraint().
{
     return std::any_of(c.begin(), c.end(), p);
 }
appendStmt()
void souffle::appendStmt (VecOwn< ram::Statement > & stmtList, Own< ram::Statement > stmt) inline
append statement to a list of statements
Definition at line 134 of file AstToRamTranslator.cpp.
Referenced by souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), souffle::AstToRamTranslator::translateProgram(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
     if (stmt) {
         stmtList.push_back(std::move(stmt));
     }
 }
as() [1/3]
template<typename B , typename A > auto souffle::as (A * x)
Helpers for dynamic_casting without having to specify redundant type qualifiers.
e.g. as<AstLiteral>(p) instead of dynamic_cast<const AstLiteral*>(p.get()).
Definition at line 151 of file MiscUtil.h.
               {
     static_assert(std::is_base_of_v<A, B>,
             "`as<B, A>` does not allow cross-type dyn casts. "
             "(i.e. `as<B, A>` where `B <: A` is not true.) "
             "Such a cast is likely a mistake or typo.");
     return dynamic_cast<copy_const_t<A, B>*>(x);
 }
as() [2/3]
template<typename B , typename A > std::enable_if_t<std::is_base_of_v<A, B>, copy_const_t<A, B>*> souffle::as (A & x)
Definition at line 160 of file MiscUtil.h.
{
     return as<B>(&x);
 }
as() [3/3]
template<typename B , typename A > B* souffle::as (const std::unique_ptr< A > & x)
Definition at line 165 of file MiscUtil.h.
{
     return as<B>(x.get());
 }
baseName()
std::string souffle::baseName (const std::string & filename) inline
Definition at line 193 of file FileUtil.h.
Referenced by souffle::SrcLocation::extloc(), getCurrentFilename(), main(), souffle::ReadFileCSV::ReadFileCSV(), souffle::ReadFileJSON::ReadFileJSON(), souffle::ReadFileCSV::readNextTuple(), and simpleName().
{
     if (filename.empty()) {
         return ".";
     }
     size_t lastNotSlash = filename.find_last_not_of('/');
     if (lastNotSlash == std::string::npos) {
         return "/";
     }
     size_t lastSlashBeforeBasename = filename.find_last_of('/', lastNotSlash - 1);
     if (lastSlashBeforeBasename == std::string::npos) {
         lastSlashBeforeBasename = static_cast<size_t>(-1);
     }
     return filename.substr(lastSlashBeforeBasename + 1, lastNotSlash - lastSlashBeforeBasename);
 }
canBeParsedAsRamFloat()
bool souffle::canBeParsedAsRamFloat (const std::string & string) inline
Can a string be parsed as RamFloat.
Definition at line 186 of file StringUtil.h.
References base, RamFloatFromString(), and str.
Referenced by souffle::ExplainProvenanceImpl::queryProcess(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
{
     size_t charactersRead = 0;
     try {
         RamFloatFromString(string, &charactersRead);
     } catch (...) {
         return false;
     }
     return charactersRead == string.size();
 }
canBeParsedAsRamSigned()
bool souffle::canBeParsedAsRamSigned (const std::string & string) inline
Can a string be parsed as RamSigned.
Souffle (parser, not fact file readers) accepts: hex, binary and base 10. Integer can be negative, in all 3 formats this means that it starts with minus (c++ default semantics).
Definition at line 156 of file StringUtil.h.
References RamSignedFromString().
Referenced by souffle::ExplainProvenanceImpl::queryProcess(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
{
     size_t charactersRead = 0;
     try {
         RamSignedFromString(string, &charactersRead, 0);
     } catch (...) {
         return false;
     }
     return charactersRead == string.size();
 }
canBeParsedAsRamUnsigned()
bool souffle::canBeParsedAsRamUnsigned (const std::string & string) inline
Can a string be parsed as RamUnsigned.
Souffle accepts: hex, binary and base 10.
Definition at line 173 of file StringUtil.h.
References RamUnsignedFromString().
Referenced by souffle::ExplainProvenanceImpl::queryProcess(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
{
     size_t charactersRead = 0;
     try {
         RamUnsignedFromString(string, &charactersRead, 0);
     } catch (...) {
         return false;
     }
     return charactersRead == string.size();
 }
castEq()
template<typename toType , typename baseType > bool souffle::castEq (const baseType * left, const baseType * right)
Cast the values, from baseType to toType and compare using ==.
(if casting fails -> return false.)
Template Parameters
baseType,initial Type of values
toType,type where equality comparison takes place.
Definition at line 398 of file ContainerUtil.h.
{
     if (auto castedLeft = dynamic_cast<const toType*>(left)) {
         if (auto castedRight = dynamic_cast<const toType*>(right)) {
             return castedLeft == castedRight;
         }
     }
     return false;
 }
clone() [1/5]
template<typename A > std::unique_ptr<A> souffle::clone (const A * node)
Definition at line 102 of file MiscUtil.h.
{
     return node ? std::unique_ptr<A>(node->clone()) : nullptr;
 }
clone() [2/5]
template<typename A > std::unique_ptr<A> souffle::clone (const std::unique_ptr< A > & node)
Definition at line 107 of file MiscUtil.h.
{
     return node ? std::unique_ptr<A>(node->clone()) : nullptr;
 }
clone() [3/5]
template<typename A , typename B > auto souffle::clone (const std::pair< A, B > & p)
Definition at line 112 of file MiscUtil.h.
References clone().
{
     return std::make_pair(clone(p.first), clone(p.second));
 }
clone() [4/5]
template<typename A > auto souffle::clone (const std::vector< A *> & xs)
Definition at line 166 of file ContainerUtil.h.
Referenced by souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem(), souffle::ast::ProvenanceNegation::clone(), souffle::ram::ProvenanceExistenceCheck::clone(), souffle::ast::RecordInit::clone(), souffle::ram::Sequence::clone(), souffle::ram::LogSize::clone(), souffle::ram::Swap::clone(), souffle::ram::Clear::clone(), souffle::ram::ExistenceCheck::clone(), souffle::ram::Scan::clone(), souffle::ram::Break::clone(), souffle::ram::Filter::clone(), souffle::ram::DebugInfo::clone(), souffle::ram::ParallelScan::clone(), souffle::ast::BranchInit::clone(), souffle::ram::Extend::clone(), souffle::ast::Negation::clone(), souffle::ram::IO::clone(), souffle::ram::Parallel::clone(), souffle::ram::ParallelChoice::clone(), souffle::ast::BranchDeclaration::clone(), souffle::ram::IndexScan::clone(), souffle::ram::ParallelIndexAggregate::clone(), souffle::ram::ParallelAggregate::clone(), souffle::ram::Negation::clone(), souffle::ram::RelationSize::clone(), souffle::ram::Exit::clone(), souffle::ram::Loop::clone(), souffle::ram::LogTimer::clone(), souffle::ram::ParallelIndexScan::clone(), souffle::ram::EmptinessCheck::clone(), souffle::ram::IndexAggregate::clone(), souffle::ram::Query::clone(), souffle::ram::LogRelationTimer::clone(), souffle::ram::ParallelIndexChoice::clone(), souffle::ram::Aggregate::clone(), souffle::ast::AlgebraicDataType::clone(), souffle::ast::RecordType::clone(), souffle::ram::Choice::clone(), souffle::ast::TypeCast::clone(), souffle::ast::transform::DebugReporter::clone(), souffle::ast::ComponentInit::clone(), souffle::RuleBody::literal::clone(), souffle::ram::Conjunction::clone(), souffle::ram::UnpackRecord::clone(), souffle::ast::BinaryConstraint::clone(), souffle::ast::transform::FixpointTransformer::clone(), souffle::ast::transform::WhileTransformer::clone(), souffle::ast::Atom::clone(), souffle::ram::Project::clone(), souffle::ram::Constraint::clone(), souffle::ast::transform::ConditionalTransformer::clone(), souffle::ram::NestedIntrinsicOperator::clone(), souffle::ast::UserDefinedFunctor::clone(), souffle::ram::IndexChoice::clone(), souffle::ast::IntrinsicFunctor::clone(), souffle::ast::Aggregator::clone(), souffle::ast::transform::PipelineTransformer::clone(), souffle::ast::Clause::clone(), souffle::ram::IndexOperation::clone(), souffle::ram::Program::clone(), souffle::ast::Relation::clone(), clone(), souffle::ast::Program::clone(), souffle::ast::Component::clone(), souffle::SparseArray< value_t, BITS, merge_op >::clone(), souffle::ast::cloneHead(), souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::ram::transform::MakeIndexTransformer::constructPattern(), souffle::ast::Component::copyBaseComponents(), souffle::ast::analysis::createAnnotatedClause(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::createMagicAtom(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::createMagicClause(), souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::ExpandFilterTransformer::expandFilters(), souffle::ast::transform::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ram::transform::MakeIndexTransformer::getExpressionPair(), souffle::ast::transform::getInlinedArgument(), souffle::ast::transform::getInlinedAtom(), souffle::ast::transform::getInlinedClause(), souffle::ast::transform::getInlinedLiteral(), souffle::ram::transform::MakeIndexTransformer::getLowerUpperExpression(), souffle::ram::transform::HoistAggregateTransformer::hoistAggregate(), souffle::ram::transform::HoistConditionsTransformer::hoistConditions(), souffle::AstToRamTranslator::ClauseTranslator::indexValues(), souffle::ast::transform::inlineBodyLiterals(), souffle::AstToRamTranslator::Location::Location(), main(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::makeSubproofSubroutine(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::SparseArray< value_t, BITS, merge_op >::merge(), souffle::RuleBody::negated(), souffle::ast::transform::negateLiteral(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::normaliseArguments(), souffle::ast::transform::normaliseInlinedHeads(), souffle::SparseArray< value_t, BITS, merge_op >::operator=(), souffle::ram::transform::ParallelTransformer::parallelizeOperations(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceClauseBodies(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ast::transform::MinimiseProgramTransformer::removeRedundantClauses(), souffle::ast::transform::ResolveAliasesTransformer::removeTrivialEquality(), souffle::ast::renameAtoms(), souffle::ast::transform::renameVariables(), souffle::ast::reorderAtoms(), souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::replaceNamedVariables(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), souffle::ram::transform::MakeIndexTransformer::rewriteScan(), souffle::ast::Type::setQualifiedName(), souffle::SparseArray< value_t, BITS, merge_op >::SparseArray(), souffle::RuleBody::toClauseBodies(), souffle::ram::toCondition(), souffle::ast::transform::RemoveTypecastsTransformer::transform(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::RemoveRedundantSumsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::NormaliseConstraintsTransformer::transform(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform(), souffle::ast::transform::FoldAnonymousRecords::transformClause(), souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), souffle::AstToRamTranslator::translateRecursiveRelation(), and souffle::ast::transform::usesInvalidWitness().
{
     std::vector<std::unique_ptr<A>> ys;
     ys.reserve(xs.size());
     for (auto&& x : xs) {
         ys.emplace_back(x ? std::unique_ptr<A>(x->clone()) : nullptr);
     }
     return ys;
 }
clone() [5/5]
template<typename A > auto souffle::clone (const std::vector< std::unique_ptr< A >> & xs)
Definition at line 176 of file ContainerUtil.h.
{
     std::vector<std::unique_ptr<A>> ys;
     ys.reserve(xs.size());
     for (auto&& x : xs) {
         ys.emplace_back(x ? std::unique_ptr<A>(x->clone()) : nullptr);
     }
     return ys;
 }
compileToBinary()
void souffle::compileToBinary (std::string compileCmd, const std::string & sourceFilename)
Compiles the given source file to a binary file.
Definition at line 160 of file main.cpp.
References souffle::Global::config(), and splitString().
Referenced by main().
{
     // add source code
     compileCmd += ' ';
     for (const std::string& path : splitString(Global::config().get("library-dir"), ' ')) {
         // The first entry may be blank
         if (path.empty()) {
             continue;
         }
         compileCmd += "-L" + path + ' ';
     }
     for (const std::string& library : splitString(Global::config().get("libraries"), ' ')) {
         // The first entry may be blank
         if (library.empty()) {
             continue;
         }
         compileCmd += "-l" + library + ' ';
     }
     compileCmd += sourceFilename;
     // run executable
     if (system(compileCmd.c_str()) != 0) {
         throw std::invalid_argument("failed to compile C++ source <" + sourceFilename + ">");
     }
 }
contains() [1/3]
template<typename C > bool souffle::contains (const C & container, const typename C::value_type & element)
A utility to check generically whether a given element is contained in a given container.
Definition at line 69 of file ContainerUtil.h.
Referenced by souffle::ast::BindingStore::addBindingDependency(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::addRelevantVariables(), souffle::ParserDriver::addTag(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::adornClause(), souffle::ast::transform::SemanticCheckerImpl::checkBranchInits(), souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::transform::SemanticCheckerImpl::checkLiteral(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::contains(), souffle::Trie< Arity >::contains(), souffle::Trie< 1u >::contains(), souffle::ast::transform::FoldAnonymousRecords::containsValidRecordConstraint(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::createMagicClause(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainNegationGetVariables(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::analysis::ClauseNormalisationAnalysis::getNormalisation(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getSplitPoint(), souffle::ast::analysis::SumTypeBranchesAnalysis::getType(), souffle::WriteFileCSVFactory::getWriter(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::grow_parent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::insert_inner(), souffle::ast::BindingStore::isBound(), souffle::ast::analysis::TypeEnvironmentAnalysis::isCyclic(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::operator==(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::queueAdornment(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::rebalance_or_split(), souffle::ast::transform::MinimiseProgramTransformer::reduceClauseBodies(), souffle::ast::BindingStore::reduceDependencies(), souffle::ast::BindingStore::reduceDependency(), souffle::ast::renameAtoms(), souffle::ast::analysis::ClauseNormalisationAnalysis::run(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::split(), TEST(), souffle::ast::transform::test::TEST(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::validOverloads(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitAtom().
{
     return std::find(container.begin(), container.end(), element) != container.end();
 }
contains() [2/3]
template<typename A > bool souffle::contains (const std::set< A > & container, const A & element)
Definition at line 75 of file ContainerUtil.h.
{
     return container.find(element) != container.end();
 }
contains() [3/3]
template<typename C > bool souffle::contains (const C & container, const typename C::value_type::first_type & element)
Version of contains specialised for maps.
This workaround is needed because of set container, for which value_type == key_type, which is ambiguous in this context.
Definition at line 86 of file ContainerUtil.h.
{
     return container.find(element) != container.end();
 }
convertDotToSVG()
std::string souffle::convertDotToSVG (const std::string & dotSpec) inline
Definition at line 207 of file GraphUtils.h.
References execStdOut(), souffle::TempFileStream::getFileName(), isExecutable(), str, and which().
Referenced by printHTMLGraph().
{
     // Check if dot is present
     std::string cmd = which("dot");
     if (!isExecutable(cmd)) {
         return "";
     }
     TempFileStream dotFile;
     dotFile << dotSpec;
     dotFile.flush();
     return execStdOut("dot -Tsvg < " + dotFile.getFileName()).str();
 }
convertOverloadedAggregator()
AggregateOp souffle::convertOverloadedAggregator (const AggregateOp op, const TypeAttribute type) inline
Convert aggregator to a give type.
Eg. sum, float fsum.
Definition at line 127 of file AggregateOp.h.
References CASE_NUMERIC, fatal(), MAX, MIN, and SUM.
Referenced by souffle::ast::transform::PolymorphicObjectsTransformer::transform().
{
 #define CASE_NUMERIC(op)                                                \
     case AggregateOp::op:                                               \
         if (type == TypeAttribute::Signed) return AggregateOp::op;      \
         if (type == TypeAttribute::Unsigned) return AggregateOp::U##op; \
         if (type == TypeAttribute::Float) return AggregateOp::F##op;    \
         fatal("invalid overload");
     switch (op) {
         default:
             fatal("agg op is not overloadable");
             // clang-format off
         CASE_NUMERIC(MAX)
         CASE_NUMERIC(MIN)
         CASE_NUMERIC(SUM)
             // clang-format on
     }
 #undef CASE_NUMERIC
 }
convertOverloadedConstraint()
BinaryConstraintOp souffle::convertOverloadedConstraint (const BinaryConstraintOp constraintOp, const TypeAttribute toType) inline
Convert Constraint to work with requested type.
Example: constraintOp = LT, toType = Float -> FLT (less-than working on floats).
Definition at line 242 of file BinaryConstraintOps.h.
References COMPARE_CONSTRAINT, COMPARE_CONSTRAINT_FLOAT_OR_RAW, EQ, fatal(), GE, GT, LE, LT, NE, and UNREACHABLE_BAD_CASE_ANALYSIS.
Referenced by souffle::ast::transform::PolymorphicObjectsTransformer::transform().
{
     auto FAIL = [&]() -> BinaryConstraintOp {
         fatal("invalid binary constraint overload: op = %s; type = %s", constraintOp, toType);
     };
     // clang-format off
 #define COMPARE_CONSTRAINT_FLOAT_OR_RAW(op)                             \
     case BinaryConstraintOp::op:                                        \
         switch (toType) {                                               \
         default                     : return BinaryConstraintOp::   op; \
         case TypeAttribute::Float   : return BinaryConstraintOp::F##op; \
         }
 #define COMPARE_CONSTRAINT(op)                                          \
     case BinaryConstraintOp::op:                                        \
         switch (toType) {                                               \
         case TypeAttribute::Signed  : return BinaryConstraintOp::   op; \
         case TypeAttribute::Unsigned: return BinaryConstraintOp::U##op; \
         case TypeAttribute::Float   : return BinaryConstraintOp::F##op; \
         case TypeAttribute::Symbol  : return BinaryConstraintOp::S##op; \
         case TypeAttribute::ADT     :                                   \
         case TypeAttribute::Record  : return FAIL();                    \
         }                                                               \
         break; /* HACK: GCC-9 is incorrectly reporting a case fallthru */
     // clang-format on
     switch (constraintOp) {
         COMPARE_CONSTRAINT_FLOAT_OR_RAW(EQ)
         COMPARE_CONSTRAINT_FLOAT_OR_RAW(NE)
         COMPARE_CONSTRAINT(LT)
         COMPARE_CONSTRAINT(LE)
         COMPARE_CONSTRAINT(GT)
         COMPARE_CONSTRAINT(GE)
         default: fatal("invalid constraint conversion: constraint = %s", constraintOp);
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 #undef COMPARE_CONSTRAINT_FLOAT_OR_RAW
 #undef COMPARE_CONSTRAINT
 }
convertStrictToNotEqualConstraint()
BinaryConstraintOp souffle::convertStrictToNotEqualConstraint (const BinaryConstraintOp constraintOp) inline
Definition at line 167 of file BinaryConstraintOps.h.
References FGT, FLT, FNE, GT, isStrictIneqConstraint(), LT, NE, UGT, and ULT.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern().
{
     assert(isStrictIneqConstraint(constraintOp));
     switch (constraintOp) {
         case BinaryConstraintOp::LT: return BinaryConstraintOp::NE;
         case BinaryConstraintOp::GT: return BinaryConstraintOp::NE;
         case BinaryConstraintOp::ULT: return BinaryConstraintOp::NE;
         case BinaryConstraintOp::UGT: return BinaryConstraintOp::NE;
         case BinaryConstraintOp::FLT: return BinaryConstraintOp::FNE;
         case BinaryConstraintOp::FGT: return BinaryConstraintOp::FNE;
         default: break;
     }
     return constraintOp;
 }
convertStrictToWeakIneqConstraint()
BinaryConstraintOp souffle::convertStrictToWeakIneqConstraint (const BinaryConstraintOp constraintOp) inline
Definition at line 153 of file BinaryConstraintOps.h.
References FGE, FGT, FLE, FLT, GE, GT, isStrictIneqConstraint(), LE, LT, UGE, UGT, ULE, and ULT.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern().
{
     assert(isStrictIneqConstraint(constraintOp));
     switch (constraintOp) {
         case BinaryConstraintOp::LT: return BinaryConstraintOp::LE;
         case BinaryConstraintOp::GT: return BinaryConstraintOp::GE;
         case BinaryConstraintOp::ULT: return BinaryConstraintOp::ULE;
         case BinaryConstraintOp::UGT: return BinaryConstraintOp::UGE;
         case BinaryConstraintOp::FLT: return BinaryConstraintOp::FLE;
         case BinaryConstraintOp::FGT: return BinaryConstraintOp::FGE;
         default: break;
     }
     return constraintOp;
 }
createBrieIndex()
Own< InterpreterIndex > souffle::createBrieIndex (const Order & order)
Definition at line 36 of file InterpreterBrieIndex.cpp.
References fatal(), souffle::GenericIndex< Trie< Arity > >::order, and souffle::Order::size().
{
     switch (order.size()) {
         case 0: return mk<NullaryIndex>();
         case 1: return mk<BrieIndex<1>>(order);
         case 2: return mk<BrieIndex<2>>(order);
         case 3: return mk<BrieIndex<3>>(order);
         case 4: return mk<BrieIndex<4>>(order);
         case 5: return mk<BrieIndex<5>>(order);
         case 6: return mk<BrieIndex<6>>(order);
         case 7: return mk<BrieIndex<7>>(order);
         case 8: return mk<BrieIndex<8>>(order);
         case 9: return mk<BrieIndex<9>>(order);
         case 10: return mk<BrieIndex<10>>(order);
         case 11: return mk<BrieIndex<11>>(order);
         case 12: return mk<BrieIndex<12>>(order);
         case 13: return mk<BrieIndex<13>>(order);
         case 14: return mk<BrieIndex<14>>(order);
         case 15: return mk<BrieIndex<15>>(order);
         case 16: return mk<BrieIndex<16>>(order);
         case 17: return mk<BrieIndex<17>>(order);
         case 18: return mk<BrieIndex<18>>(order);
         case 19: return mk<BrieIndex<19>>(order);
         case 20: return mk<BrieIndex<20>>(order);
     }
     fatal("Requested arity not yet supported. Feel free to add it.");
 }
createBTreeIndex()
Own< InterpreterIndex > souffle::createBTreeIndex (const Order & order)
Definition at line 47 of file InterpreterBTreeIndex.cpp.
References fatal(), souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >::order, and souffle::Order::size().
{
     switch (order.size()) {
         case 0: return mk<NullaryIndex>();
         case 1: return mk<BTreeIndex<1>>(order);
         case 2: return mk<BTreeIndex<2>>(order);
         case 3: return mk<BTreeIndex<3>>(order);
         case 4: return mk<BTreeIndex<4>>(order);
         case 5: return mk<BTreeIndex<5>>(order);
         case 6: return mk<BTreeIndex<6>>(order);
         case 7: return mk<BTreeIndex<7>>(order);
         case 8: return mk<BTreeIndex<8>>(order);
         case 9: return mk<BTreeIndex<9>>(order);
         case 10: return mk<BTreeIndex<10>>(order);
         case 11: return mk<BTreeIndex<11>>(order);
         case 12: return mk<BTreeIndex<12>>(order);
         case 13: return mk<BTreeIndex<13>>(order);
         case 14: return mk<BTreeIndex<14>>(order);
         case 15: return mk<BTreeIndex<15>>(order);
         case 16: return mk<BTreeIndex<16>>(order);
         case 17: return mk<BTreeIndex<17>>(order);
         case 18: return mk<BTreeIndex<18>>(order);
         case 19: return mk<BTreeIndex<19>>(order);
         case 20: return mk<BTreeIndex<20>>(order);
     }
     fatal("Requested arity not yet supported. Feel free to add it.");
 }
createBTreeProvenanceIndex()
Own< InterpreterIndex > souffle::createBTreeProvenanceIndex (const Order & order)
Definition at line 60 of file InterpreterProvenanceIndex.cpp.
References fatal(), and souffle::Order::size().
Referenced by souffle::NodeGenerator::createRelation().
{
     switch (order.size()) {
         case 0:
         case 1: fatal("Provenance relation with arity < 2.");
         case 2: return mk<BTreeProvenanceIndex<2>>(order);
         case 3: return mk<BTreeProvenanceIndex<3>>(order);
         case 4: return mk<BTreeProvenanceIndex<4>>(order);
         case 5: return mk<BTreeProvenanceIndex<5>>(order);
         case 6: return mk<BTreeProvenanceIndex<6>>(order);
         case 7: return mk<BTreeProvenanceIndex<7>>(order);
         case 8: return mk<BTreeProvenanceIndex<8>>(order);
         case 9: return mk<BTreeProvenanceIndex<9>>(order);
         case 10: return mk<BTreeProvenanceIndex<10>>(order);
         case 11: return mk<BTreeProvenanceIndex<11>>(order);
         case 12: return mk<BTreeProvenanceIndex<12>>(order);
         case 13: return mk<BTreeProvenanceIndex<13>>(order);
         case 14: return mk<BTreeProvenanceIndex<14>>(order);
         case 15: return mk<BTreeProvenanceIndex<15>>(order);
         case 16: return mk<BTreeProvenanceIndex<16>>(order);
         case 17: return mk<BTreeProvenanceIndex<17>>(order);
         case 18: return mk<BTreeProvenanceIndex<18>>(order);
         case 19: return mk<BTreeProvenanceIndex<19>>(order);
         case 20: return mk<BTreeProvenanceIndex<20>>(order);
         case 21: return mk<BTreeProvenanceIndex<21>>(order);
         case 22: return mk<BTreeProvenanceIndex<22>>(order);
         case 23: return mk<BTreeProvenanceIndex<23>>(order);
         case 24: return mk<BTreeProvenanceIndex<24>>(order);
         case 25: return mk<BTreeProvenanceIndex<25>>(order);
         case 26: return mk<BTreeProvenanceIndex<26>>(order);
         case 27: return mk<BTreeProvenanceIndex<27>>(order);
         case 28: return mk<BTreeProvenanceIndex<28>>(order);
         case 29: return mk<BTreeProvenanceIndex<29>>(order);
         case 30: return mk<BTreeProvenanceIndex<30>>(order);
     }
     fatal("Requested arity not yet supported. Feel free to add it.");
 }
createEqrelIndex()
Own< InterpreterIndex > souffle::createEqrelIndex (const Order & order)
Definition at line 49 of file InterpreterEqrelIndex.cpp.
References souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >::order, and souffle::Order::size().
{
     assert(order.size() == 2 && "Eqrel index must have tuple of 2 arities");
     return mk<EqrelIndex>(order);
 }
createIndirectIndex()
Own< InterpreterIndex > souffle::createIndirectIndex (const Order & order)
Definition at line 219 of file InterpreterIndirectIndex.cpp.
References souffle::Order::getOrder(), and souffle::Order::size().
{
     assert(order.size() != 0 && "IndirectIndex does not work with nullary relation\n");
     return mk<IndirectIndex>(order.getOrder());
 }
derefIter()
template<typename Iter > IterDerefWrapper<Iter> souffle::derefIter (const Iter & iter)
A factory function enabling the construction of a dereferencing iterator utilizing the automated deduction of template parameters.
Definition at line 246 of file ContainerUtil.h.
Referenced by souffle::ast::analysis::TypeSet::begin(), and souffle::ast::analysis::TypeSet::end().
{
     return IterDerefWrapper<Iter>(iter);
 }
dirName()
std::string souffle::dirName (const std::string & name) inline
C++-style dirname.
Definition at line 126 of file FileUtil.h.
Referenced by findTool(), and getCurrentFilename().
{
     if (name.empty()) {
         return ".";
     }
     size_t lastNotSlash = name.find_last_not_of('/');
     // All '/'
     if (lastNotSlash == std::string::npos) {
         return "/";
     }
     size_t leadingSlash = name.find_last_of('/', lastNotSlash);
     // No '/'
     if (leadingSlash == std::string::npos) {
         return ".";
     }
     // dirname is '/'
     if (leadingSlash == 0) {
         return "/";
     }
     return name.substr(0, leadingSlash);
 }
duration_in_ns()
long souffle::duration_in_ns (const time_point & start, const time_point & end) inline
Definition at line 93 of file MiscUtil.h.
References souffle::test::count().
Referenced by souffle::test::TEST().
{
     return static_cast<long>(std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count());
 }
duration_in_us()
long souffle::duration_in_us (const time_point & start, const time_point & end) inline
Definition at line 88 of file MiscUtil.h.
References souffle::test::count().
{
     return static_cast<long>(std::chrono::duration_cast<std::chrono::microseconds>(end - start).count());
 }
endsWith()
bool souffle::endsWith (const std::string & value, const std::string & ending) inline
Determines whether the given value string ends with the given end string.
Definition at line 305 of file StringUtil.h.
{
     if (value.size() < ending.size()) {
         return false;
     }
     return std::equal(ending.rbegin(), ending.rend(), value.rbegin());
 }
equal_ptr() [1/2]
template<typename T > bool souffle::equal_ptr (const T * a, const T * b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
Definition at line 124 of file MiscUtil.h.
References b.
Referenced by souffle::ram::RelationStatement::equal(), souffle::ram::AbstractChoice::equal(), souffle::ram::AbstractLog::equal(), souffle::ram::AbstractConditional::equal(), souffle::ram::RelationOperation::equal(), souffle::ram::Negation::equal(), souffle::ast::Negation::equal(), souffle::ram::RelationSize::equal(), souffle::ram::BinRelationStatement::equal(), souffle::ram::Exit::equal(), souffle::ram::EmptinessCheck::equal(), souffle::ram::Loop::equal(), souffle::ram::Query::equal(), souffle::ast::TypeCast::equal(), souffle::ram::NestedOperation::equal(), souffle::ram::Conjunction::equal(), souffle::ram::UnpackRecord::equal(), souffle::ast::BinaryConstraint::equal(), souffle::ram::AbstractAggregate::equal(), souffle::ram::Constraint::equal(), souffle::ram::AbstractExistenceCheck::equal(), souffle::ram::Project::equal(), souffle::ast::Aggregator::equal(), souffle::ast::Clause::equal(), souffle::ram::Program::equal(), souffle::ram::RelationReference::equal(), souffle::ast::Component::equal(), and equal_ptr().
{
     if (a == nullptr && b == nullptr) {
         return true;
     }
     if (a != nullptr && b != nullptr) {
         return *a == *b;
     }
     return false;
 }
equal_ptr() [2/2]
template<typename T > bool souffle::equal_ptr (const std::unique_ptr< T > & a, const std::unique_ptr< T > & b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
Definition at line 139 of file MiscUtil.h.
References equal_ptr().
{
     return equal_ptr(a.get(), b.get());
 }
equal_targets() [1/4]
template<typename Container , typename Comparator > bool souffle::equal_targets (const Container & a, const Container & b, const Comparator & comp)
A function testing whether two containers are equal with the given Comparator.
Definition at line 427 of file ContainerUtil.h.
Referenced by souffle::ast::BranchInit::equal(), souffle::ram::AbstractOperator::equal(), souffle::ram::ListStatement::equal(), souffle::ast::RecordType::equal(), souffle::ast::Term::equal(), souffle::ram::PackRecord::equal(), souffle::ram::SubroutineReturn::equal(), souffle::ast::ExecutionPlan::equal(), souffle::ram::AbstractExistenceCheck::equal(), souffle::ram::Project::equal(), souffle::ast::Atom::equal(), souffle::ram::NestedIntrinsicOperator::equal(), souffle::ast::Aggregator::equal(), souffle::ast::Clause::equal(), souffle::ast::Relation::equal(), souffle::ram::IndexOperation::equal(), souffle::ram::Program::equal(), souffle::ast::Program::equal(), souffle::ast::Component::equal(), equal_targets(), and souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies().
{
     // check reference
     if (&a == &b) {
         return true;
     }
     // check size
     if (a.size() != b.size()) {
         return false;
     }
     // check content
     return std::equal(a.begin(), a.end(), b.begin(), comp);
 }
equal_targets() [2/4]
template<typename T , template< typename... > class Container> bool souffle::equal_targets (const Container< T *> & a, const Container< T *> & b)
A function testing whether two containers of pointers are referencing equivalent targets.
Definition at line 447 of file ContainerUtil.h.
References equal_targets().
{
     return equal_targets(a, b, comp_deref<T*>());
 }
equal_targets() [3/4]
template<typename T , template< typename... > class Container> bool souffle::equal_targets (const Container< std::unique_ptr< T >> & a, const Container< std::unique_ptr< T >> & b)
A function testing whether two containers of unique pointers are referencing equivalent targets.
Definition at line 456 of file ContainerUtil.h.
References b, and equal_targets().
{
     return equal_targets(a, b, comp_deref<std::unique_ptr<T>>());
 }
equal_targets() [4/4]
template<typename Key , typename Value > bool souffle::equal_targets (const std::map< Key, std::unique_ptr< Value >> & a, const std::map< Key, std::unique_ptr< Value >> & b)
A function testing whether two maps of unique pointers are referencing to equivalent targets.
Definition at line 465 of file ContainerUtil.h.
References b, and equal_targets().
{
     auto comp = comp_deref<std::unique_ptr<Value>>();
     return equal_targets(
             a, b, [&comp](auto& a, auto& b) { return a.first == b.first && comp(a.second, b.second); });
 }
escape() [1/2]
std::string souffle::escape (const std::string & inputString, const std::string & needle, const std::string & replacement) inline
Definition at line 411 of file StringUtil.h.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::synthesiser::Synthesiser::generateCode(), souffle::ram::IO::print(), and souffle::profile::EventProcessorSingleton::process().
{
     std::string result = inputString;
     size_t pos = 0;
     while ((pos = result.find(needle, pos)) != std::string::npos) {
         result = result.replace(pos, needle.length(), replacement);
         pos += replacement.length();
     }
     return result;
 }
escape() [2/2]
std::string souffle::escape (const std::string & inputString) inline
Definition at line 422 of file StringUtil.h.
{
     std::string escaped = escape(inputString, "\"", "\\\"");
     escaped = escape(escaped, "\t", "\\t");
     escaped = escape(escaped, "\r", "\\r");
     escaped = escape(escaped, "\n", "\\n");
     return escaped;
 }
escapeJSONstring()
std::string souffle::escapeJSONstring (const std::string & JSONstr) inline
Escape JSON string.
Definition at line 367 of file StringUtil.h.
Referenced by souffle::synthesiser::Synthesiser::generateCode().
{
     std::ostringstream destination;
     // Iterate over all characters except first and last
     for (char c : JSONstr) {
         if (c == '\"') {
             destination << "\\";
         }
         destination << c;
     }
     return destination.str();
 }
execStdOut() [1/2]
std::stringstream souffle::execStdOut (char const * cmd) inline
Definition at line 268 of file FileUtil.h.
Referenced by convertDotToSVG(), and execStdOut().
{
     FILE* in = popen(cmd, "r");
     std::stringstream data;
     while (in != nullptr) {
         int c = fgetc(in);
         if (feof(in) != 0) {
             break;
         }
         data << c;
     }
     pclose(in);
     return data;
 }
execStdOut() [2/2]
std::stringstream souffle::execStdOut (std::string const & cmd) inline
Definition at line 282 of file FileUtil.h.
References execStdOut().
{
     return execStdOut(cmd.c_str());
 }
executeBinary()
void souffle::executeBinary (const std::string & binaryFilename)
Executes a binary file.
Definition at line 119 of file main.cpp.
References souffle::Global::config(), isExecutable(), and splitString().
Referenced by main().
{
     assert(!binaryFilename.empty() && "binary filename cannot be blank");
     // check whether the executable exists
     if (!isExecutable(binaryFilename)) {
         throw std::invalid_argument("Generated executable <" + binaryFilename + "> could not be found");
     }
     std::string ldPath;
     // run the executable
     if (Global::config().has("library-dir")) {
         for (const std::string& library : splitString(Global::config().get("library-dir"), ' ')) {
             ldPath += library + ':';
         }
         ldPath.pop_back();
         setenv("LD_LIBRARY_PATH", ldPath.c_str(), 1);
     }
     std::string exePath;
 #ifdef __APPLE__
     // OSX does not pass on the environment from setenv so add it to the command line
     exePath = "DYLD_LIBRARY_PATH=\"" + ldPath + "\" ";
 #endif
     exePath += binaryFilename;
     int exitCode = system(exePath.c_str());
     if (Global::config().get("dl-program").empty()) {
         remove(binaryFilename.c_str());
         remove((binaryFilename + ".cpp").c_str());
     }
     // exit with same code as executable
     if (exitCode != EXIT_SUCCESS) {
         exit(exitCode);
     }
 }
existDir()
bool souffle::existDir (const std::string & name) inline
Check whether a directory exists in the file system.
Definition at line 78 of file FileUtil.h.
Referenced by main(), and which().
{
     struct stat buffer = {};
     if (stat(name.c_str(), &buffer) == 0) {
         if ((buffer.st_mode & S_IFDIR) != 0) {
             return true;
         }
     }
     return false;
 }
existFile()
bool souffle::existFile (const std::string & name) inline
Check whether a file exists in the file system.
Definition at line 65 of file FileUtil.h.
Referenced by getCurrentFilename(), isExecutable(), and main().
{
     struct stat buffer = {};
     if (stat(name.c_str(), &buffer) == 0) {
         if ((buffer.st_mode & S_IFMT) != 0) {
             return true;
         }
     }
     return false;
 }
explain()
void souffle::explain (SouffleProgram & prog, bool ncurses) inline
Definition at line 627 of file Explain.h.
Referenced by souffle::ExplainProvenance::ExplainProvenance(), main(), souffle::Explain::parseTuple(), souffle::Explain::printError(), and souffle::Explain::processCommand().
{
     ExplainProvenanceImpl prov(prog);
     if (ncurses) {
 #ifdef USE_NCURSES
         ExplainNcurses exp(prov);
         exp.explain();
 #else
         std::cout << "The ncurses-based interface is not enabled\n";
 #endif
     } else {
         ExplainConsole exp(prov);
         exp.explain();
     }
 }
fatal()
template<typename... Args> void souffle::fatal (const char * format, const Args &... args)
Definition at line 192 of file MiscUtil.h.
References tinyformat::format().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkArgument(), souffle::ast::transform::SemanticCheckerImpl::checkTypesDeclarations(), souffle::IndirectIndex::IndirectIndexView::contains(), convertOverloadedAggregator(), convertOverloadedConstraint(), createBrieIndex(), createBTreeIndex(), createBTreeProvenanceIndex(), souffle::ast::analysis::TypeEnvironmentAnalysis::createType(), souffle::synthesiser::Synthesiser::emitCode(), souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeAggregate(), souffle::SouffleProgram::executeSubroutine(), souffle::ExplainProvenanceImpl::findQuerySolution(), souffle::synthesiser::Synthesiser::generateCode(), souffle::AstToRamTranslator::ClauseTranslator::getArgList(), souffle::ast::getClauseNum(), souffle::AstToRamTranslator::getConstantRamRepresentation(), souffle::ast::analysis::TypeEnvironment::getConstantType(), souffle::AstToRamTranslator::ValueIndex::getDefinitionPoint(), souffle::AstToRamTranslator::ValueIndex::getGeneratorLoc(), souffle::ast::transform::getInlinedArgument(), souffle::ram::analysis::LevelAnalysis::getLevel(), getRelationQualifierFromTag(), souffle::NodeGenerator::getRelationRefForView(), getRelationRepresentationFromTag(), souffle::ast::analysis::getTypeAttribute(), souffle::ast::analysis::getTypeQualifier(), souffle::SymbolTable::lookupExisting(), souffle::ast::transform::makeInfoRelation(), souffle::ram::analysis::MinIndexSelection::map(), souffle::ast::negateConstraintInPlace(), souffle::ast::transform::negateLiteral(), operator<<(), souffle::ram::operator<<(), souffle::WriteStream::outputADT(), souffle::WriteStream::outputRecord(), souffle::ast::FunctorDeclaration::print(), souffle::profile::EventProcessor::process(), souffle::ReadStream::readADT(), souffle::profile::Reader::Reader(), souffle::ReadStreamJSON::readNextElementList(), souffle::ReadStreamJSON::readNextElementObject(), souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamJSON::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStreamJSON::readNextTupleList(), souffle::ReadStreamJSON::readNextTupleObject(), souffle::ReadStream::readRecord(), souffle::ReadStreamJSON::ReadStreamJSON(), souffle::SymbolTable::resolve(), toBinaryConstraintOp(), souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::AstToRamTranslator::translateRecursiveRelation(), souffle::AstToRamTranslator::translateValue(), souffle::ExplainProvenance::valueRead(), souffle::ExplainProvenance::valueShow(), souffle::ast::analysis::TypeVisitor< R >::visit(), souffle::ast::Visitor< void >::visit(), souffle::ram::Visitor< Own< InterpreterNode > >::visit(), souffle::NodeGenerator::visitNode(), souffle::ast::transform::TypeChecker::visitUserDefinedFunctor(), souffle::WriteCoutPrintSize::writeNextTuple(), souffle::WriteStreamCSV::writeNextTupleElement(), souffle::WriteStreamJSON::writeNextTupleList(), souffle::WriteStreamJSON::writeNextTupleObject(), souffle::WriteCoutPrintSize::writeNullary(), souffle::WriteStream::writeSize(), and souffle::WriteStreamJSON::WriteStreamJSON().
{
     tfm::format(std::cerr, format, args...);
     std::cerr << "\n";
     assert(false && "fatal error; see std err");
     abort();
 }
fileExtension()
std::string souffle::fileExtension (const std::string & path) inline
File extension, with all else removed.
Definition at line 232 of file FileUtil.h.
Referenced by souffle::synthesiser::Synthesiser::emitCode().
{
     std::string name = path;
     const size_t lastDot = name.find_last_of('.');
     // file has no extension
     if (lastDot == std::string::npos) {
         return std::string();
     }
     const size_t lastSlash = name.find_last_of('/');
     // last slash occurs after last dot, so no extension
     if (lastSlash != std::string::npos && lastSlash > lastDot) {
         return std::string();
     }
     // last dot after last slash, or no slash
     return name.substr(lastDot + 1);
 }
filter()
template<typename A , typename F > std::vector<A> souffle::filter (std::vector< A > xs, F && f)
Filter a vector to include certain elements.
Definition at line 149 of file FunctionalUtil.h.
References filterNot().
Referenced by souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::ExpandFilterTransformer::expandFilters(), souffle::ram::analysis::LevelAnalysis::getLevel(), souffle::ram::transform::HoistConditionsTransformer::hoistConditions(), souffle::InterpreterEngine::InterpreterEngine(), souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), souffle::ram::transform::MakeIndexTransformer::rewriteScan(), souffle::test::TEST(), TEST(), souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter(), souffle::NodeGenerator::visitFilter(), and souffle::NodeGenerator::visitQuery().
{
     return filterNot(std::move(xs), [&](auto&& x) { return !f(x); });
 }
filterNot()
template<typename A , typename F > std::vector<A> souffle::filterNot (std::vector< A > xs, F && f)
Filter a vector to exclude certain elements.
Definition at line 140 of file FunctionalUtil.h.
Referenced by filter(), and souffle::ast::validOverloads().
{
     xs.erase(std::remove_if(xs.begin(), xs.end(), std::forward<F>(f)), xs.end());
     return xs;
 }
findTool()
std::string souffle::findTool (const std::string & tool, const std::string & base, const std::string & path) inline
Definition at line 176 of file FileUtil.h.
References absPath(), dirName(), isExecutable(), and souffle::ast::analysis::sub().
Referenced by main().
{
     std::string dir = dirName(base);
     std::stringstream sstr(path);
     std::string sub;
     while (std::getline(sstr, sub, ':')) {
         std::string subpath = dir + "/" + sub + '/' + tool;
         if (isExecutable(subpath)) {
             return absPath(subpath);
         }
     }
     return "";
 }
functorBuiltIn() [1/3]
IntrinsicFunctors souffle::functorBuiltIn (FunctorOp op)
Definition at line 224 of file FunctorOps.cpp.
Referenced by isFunctorMultiResult(), isInfixFunctorOp(), souffle::ast::validOverloads(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor().
{
     return pickFunctors([&](auto&& x) { return x.op == op; });
 }
functorBuiltIn() [2/3]
IntrinsicFunctors souffle::functorBuiltIn (std::string_view symbol)
Definition at line 228 of file FunctorOps.cpp.
{
     return pickFunctors([&](auto&& x) { return x.symbol == symbol; });
 }
functorBuiltIn() [3/3]
IntrinsicFunctors souffle::functorBuiltIn (std::string_view symbol, const std::vector< TypeAttribute > & params)
Definition at line 232 of file FunctorOps.cpp.
References all_of().
{
     return pickFunctors([&](auto&& x) {
         auto paramsOk =
                 x.variadic ? all_of(params, [&](auto t) { return t == x.params[0]; }) : x.params == params;
         return x.symbol == symbol && paramsOk;
     });
 }
genJsonRules()
std::stringstream& souffle::genJsonRules (std::stringstream & ss, const std::string & name, size_t maxRows)
Definition at line 339 of file Tui.h.
References souffle::profile::Tools::cleanJsonOut(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Table::getRows(), souffle::profile::OutputProcessor::getVersions(), i, souffle::Table< T, blockSize >::size(), souffle::profile::Tools::split(), souffle::profile::ss, and toString().
Referenced by genJsonAtoms().
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         ss << '"' << name << R"_(":{)_";
         bool firstRow = true;
         auto rows = ruleTable.getRows();
         std::stable_sort(rows.begin(), rows.end(), [](std::shared_ptr<Row> left, std::shared_ptr<Row> right) {
             return (*left)[0]->getDoubleVal() > (*right)[0]->getDoubleVal();
         });
         maxRows = std::min(rows.size(), maxRows);
         for (size_t i = 0; i < maxRows; ++i) {
             Row& row = *rows[i];
             std::vector<std::string> part = Tools::split(row[6]->toString(0), ".");
             std::string strRel = "R" + part[0].substr(1);
             Table versionTable = out.getVersions(strRel, row[6]->toString(0));
             std::string src;
             if (versionTable.rows.size() > 0) {
                 if (versionTable.rows[0]->cells[9] != nullptr) {
                     src = (*versionTable.rows[0])[9]->toString(0);
                 } else {
                     src = "-";
                 }
             } else {
                 src = row[10]->toString(-1);
             }
             comma(firstRow);
             ss << "\n ";
             ss << '"' << row[6]->toString(0) << R"_(": [)_";
             ss << '"' << Tools::cleanJsonOut(row[5]->toString(0)) << R"_(", )_";
             ss << '"' << Tools::cleanJsonOut(row[6]->toString(0)) << R"_(", )_";
             ss << row[0]->getDoubleVal() << ", ";
             ss << row[1]->getDoubleVal() << ", ";
             ss << row[2]->getDoubleVal() << ", ";
             ss << row[4]->getLongVal() << ", ";
             ss << '"' << src << R"_(", )_";
             ss << "[";
             bool has_ver = false;
             bool firstCol = true;
             for (auto& _ver_row : versionTable.getRows()) {
                 comma(firstCol);
                 has_ver = true;
                 Row ver_row = *_ver_row;
                 ss << '[';
                 ss << '"' << Tools::cleanJsonOut(ver_row[5]->toString(0)) << R"_(", )_";
                 ss << '"' << Tools::cleanJsonOut(ver_row[6]->toString(0)) << R"_(", )_";
                 ss << ver_row[0]->getDoubleVal() << ", ";
                 ss << ver_row[1]->getDoubleVal() << ", ";
                 ss << ver_row[2]->getDoubleVal() << ", ";
                 ss << ver_row[4]->getLongVal() << ", ";
                 ss << '"' << src << R"_(", )_";
                 ss << ver_row[8]->getLongVal();
                 ss << ']';
             }
             ss << "], ";
             if (row[6]->toString(0).at(0) != 'C') {
                 ss << "{}, {}]";
             } else {
                 ss << R"_({"tot_t": [)_";
                 std::vector<uint64_t> iteration_tuples;
                 bool firstCol = true;
                 for (auto& i : run->getRelation(row[7]->toString(0))->getIterations()) {
                     bool add = false;
                     std::chrono::microseconds totalTime{};
                     uint64_t totalSize = 0L;
                     for (auto& rul : i->getRules()) {
                         if (rul.second->getId() == row[6]->toString(0)) {
                             totalTime += rul.second->getRuntime();
                             totalSize += rul.second->size();
                             add = true;
                         }
                     }
                     if (add) {
                         comma(firstCol);
                         ss << totalTime.count();
                         iteration_tuples.push_back(totalSize);
                     }
                 }
                 ss << R"_(], "tuples": [)_";
                 firstCol = true;
                 for (auto& i : iteration_tuples) {
                     comma(firstCol);
                     ss << i;
                 }
                 ss << "]}, {";
                 if (has_ver) {
                     ss << R"_("tot_t": [)_";
                     firstCol = true;
                     for (auto& row : versionTable.rows) {
                         comma(firstCol);
                         ss << (*row)[0]->getDoubleVal();
                     }
                     ss << R"_(], "tuples": [)_";
                     firstCol = true;
                     for (auto& row : versionTable.rows) {
                         comma(firstCol);
                         ss << (*row)[4]->getLongVal();
                     }
                     ss << ']';
                 }
                 ss << "}]";
             }
         }
         ss << "\n}";
         return ss;
     }
     std::stringstream& genJsonUsage(std::stringstream& ss) {
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         std::string source_loc = (*relationTable.getRows()[0])[7]->getStringVal();
         std::string source_file_loc = Tools::split(source_loc, " ").at(0);
         std::ifstream source_file(source_file_loc);
         if (!source_file.is_open()) {
             std::cout << "Error opening \"" << source_file_loc << "\", creating GUI without source locator."
                       << std::endl;
         } else {
getBinaryConstraintTypes()
std::vector<TypeAttribute> souffle::getBinaryConstraintTypes (const BinaryConstraintOp op) inline
Get type binary constraint operates on.
Definition at line 418 of file BinaryConstraintOps.h.
References COMPARE_EQUALS, COMPARE_OP, CONTAINS, EQ, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, Symbol, and UNREACHABLE_BAD_CASE_ANALYSIS.
Referenced by souffle::ast::transform::TypeChecker::visitBinaryConstraint().
{
     // clang-format off
 #define COMPARE_EQUALS(op)                                                             \
     case BinaryConstraintOp::F##op: return { TypeAttribute::Float };                   \
     case BinaryConstraintOp::   op:                                                    \
         return { TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float, \
                  TypeAttribute::Symbol, TypeAttribute::Record, TypeAttribute::ADT};
 #define COMPARE_OP(op)                                                  \
     case BinaryConstraintOp::   op: return { TypeAttribute::Signed   }; \
     case BinaryConstraintOp::U##op: return { TypeAttribute::Unsigned }; \
     case BinaryConstraintOp::F##op: return { TypeAttribute::Float    }; \
     case BinaryConstraintOp::S##op: return { TypeAttribute::Symbol   };
     // clang-format on
     switch (op) {
         COMPARE_EQUALS(EQ)
         COMPARE_EQUALS(NE)
         COMPARE_OP(LT)
         COMPARE_OP(LE)
         COMPARE_OP(GT)
         COMPARE_OP(GE)
         case BinaryConstraintOp::MATCH:
         case BinaryConstraintOp::NOT_MATCH:
         case BinaryConstraintOp::CONTAINS:
         case BinaryConstraintOp::NOT_CONTAINS: return {TypeAttribute::Symbol};
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 #undef COMPARE_EQUALS
 #undef COMPARE_OP
 }
getCurrentFilename()
std::string souffle::getCurrentFilename (const std::vector< std::string > & filenames)
Definition at line 27 of file SrcLocation.cpp.
References baseName(), dirName(), and existFile().
Referenced by souffle::SrcLocation::extloc(), souffle::SrcLocation::operator<(), and souffle::SrcLocation::print().
{
     if (filenames.empty()) {
         return "";
     }
     std::string path = ".";
     for (std::string filename : filenames) {
         if (!filename.empty() && filename[0] == '/') {
             path = dirName(filename);
         } else if (existFile(path + "/" + filename)) {
             path = dirName(path + "/" + filename);
         } else if (existFile(filename)) {
             path = dirName(filename);
         } else {
             path = ".";
         }
     }
     return path + "/" + baseName(filenames.back());
 }
getEqConstraint()
BinaryConstraintOp souffle::getEqConstraint (const std::string & type) inline
Definition at line 68 of file BinaryConstraintOps.h.
References EQ, and FEQ.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern().
{
     switch (type[0]) {
         case 'f': return BinaryConstraintOp::FEQ;
         case 'u': return BinaryConstraintOp::EQ;
         case 'i': return BinaryConstraintOp::EQ;
         default: return BinaryConstraintOp::EQ;
     }
 }
getGreaterEqualConstraint()
BinaryConstraintOp souffle::getGreaterEqualConstraint (const std::string & type) inline
Definition at line 88 of file BinaryConstraintOps.h.
References FGE, GE, and UGE.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern(), and souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter().
{
     switch (type[0]) {
         case 'f': return BinaryConstraintOp::FGE;
         case 'u': return BinaryConstraintOp::UGE;
         case 'i': return BinaryConstraintOp::GE;
         default: return BinaryConstraintOp::GE;
     }
 }
getGreaterThanConstraint()
BinaryConstraintOp souffle::getGreaterThanConstraint (const std::string & type) inline
Definition at line 108 of file BinaryConstraintOps.h.
References FGT, GT, and UGT.
{
     switch (type[0]) {
         case 'f': return BinaryConstraintOp::FGT;
         case 'u': return BinaryConstraintOp::UGT;
         case 'i': return BinaryConstraintOp::GT;
         default: return BinaryConstraintOp::GT;
     }
 }
getIf()
template<typename C > C::value_type souffle::getIf (const C & container, std::function< bool(const typename C::value_type)> pred)
Returns the first element in a container that satisfies a given predicate, nullptr otherwise.
Definition at line 95 of file ContainerUtil.h.
Referenced by souffle::ParserDriver::addFunctorDeclaration(), souffle::ast::Program::addFunctorDeclaration(), souffle::ast::Program::addRelation(), souffle::ParserDriver::addType(), souffle::ast::Program::addType(), souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration(), souffle::ast::transform::SemanticCheckerImpl::checkUnionType(), souffle::ast::getRelation(), and souffle::ast::transform::UserDefinedFunctorsTransformer::transform().
{
     auto res = std::find_if(container.begin(), container.end(),
             [&](const typename C::value_type item) { return pred(item); });
     return res == container.end() ? nullptr : *res;
 }
getInstance()
souffle::SouffleProgram* souffle::getInstance (const char * p) inline
Definition at line 66 of file CompiledSouffle.h.
References souffle::ProgramFactory::newInstance().
{
     return souffle::ProgramFactory::newInstance(p);
 }
getLessEqualConstraint()
BinaryConstraintOp souffle::getLessEqualConstraint (const std::string & type) inline
Definition at line 78 of file BinaryConstraintOps.h.
References FLE, LE, and ULE.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern(), and souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter().
{
     switch (type[0]) {
         case 'f': return BinaryConstraintOp::FLE;
         case 'u': return BinaryConstraintOp::ULE;
         case 'i': return BinaryConstraintOp::LE;
         default: return BinaryConstraintOp::LE;
     }
 }
getLessThanConstraint()
BinaryConstraintOp souffle::getLessThanConstraint (const std::string & type) inline
Definition at line 98 of file BinaryConstraintOps.h.
References FLT, LT, and ULT.
{
     switch (type[0]) {
         case 'f': return BinaryConstraintOp::FLT;
         case 'u': return BinaryConstraintOp::ULT;
         case 'i': return BinaryConstraintOp::LT;
         default: return BinaryConstraintOp::LT;
     }
 }
getMaxOp()
FunctorOp souffle::getMaxOp (const std::string & type)
Definition at line 276 of file FunctorOps.cpp.
References FMAX, MAX, and UMAX.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern().
{
     switch (type[0]) {
         case 'f': return FunctorOp::FMAX;
         case 'u': return FunctorOp::UMAX;
         case 'i': return FunctorOp::MAX;
         default: return FunctorOp::MAX;
     }
 }
getMinOp()
FunctorOp souffle::getMinOp (const std::string & type)
Given a type of an an attribute it returns the appropriate min/max functor operation.
Definition at line 267 of file FunctorOps.cpp.
References FMIN, MIN, and UMIN.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern().
{
     switch (type[0]) {
         case 'f': return FunctorOp::FMIN;
         case 'u': return FunctorOp::UMIN;
         case 'i': return FunctorOp::MIN;
         default: return FunctorOp::MIN;
     }
 }
getOr()
template<typename C > C::mapped_type const& souffle::getOr (const C & container, typename C::key_type key, const typename C::mapped_type & defaultValue)
Get value for a given key; if not found, return default value.
Definition at line 105 of file ContainerUtil.h.
Referenced by souffle::WriteFileCSV::getFileName(), souffle::ReadStreamSQLite::getFileName(), souffle::WriteFileJSON::getFileName(), souffle::WriteStreamSQLite::getFileName(), souffle::ReadFileCSV::getFileName(), souffle::ReadFileJSON::getFileName(), souffle::ReadStreamCSV::getInputColumnMap(), souffle::ReadFileCSV::ReadFileCSV(), souffle::WriteCoutCSV::WriteCoutCSV(), and souffle::WriteFileCSV::WriteFileCSV().
{
     auto it = container.find(key);
     if (it != container.end()) {
         return it->second;
     } else {
         return defaultValue;
     }
 }
getOutputLock()
Lock& souffle::getOutputLock () inline
Obtains a reference to the lock synchronizing output operations.
Definition at line 568 of file ParallelUtil.h.
Referenced by souffle::WriteCoutPrintSize::WriteCoutPrintSize().
{
     static Lock outputLock;
     return outputLock;
 }
getRelationQualifierFromTag()
RelationQualifier souffle::getRelationQualifierFromTag (const RelationTag & tag) inline
Get the corresponding RelationQualifier for a valid RelationTag.
Definition at line 89 of file RelationTag.h.
References fatal(), INLINE, INPUT, MAGIC, OUTPUT, OVERRIDABLE, PRINTSIZE, and SUPPRESSED.
{
     switch (tag) {
         case RelationTag::INPUT: return RelationQualifier::INPUT;
         case RelationTag::OUTPUT: return RelationQualifier::OUTPUT;
         case RelationTag::PRINTSIZE: return RelationQualifier::PRINTSIZE;
         case RelationTag::OVERRIDABLE: return RelationQualifier::OVERRIDABLE;
         case RelationTag::INLINE: return RelationQualifier::INLINE;
         case RelationTag::MAGIC: return RelationQualifier::MAGIC;
         case RelationTag::SUPPRESSED: return RelationQualifier::SUPPRESSED;
         default: fatal("invalid relation tag");
     }
 }
getRelationRepresentationFromTag()
RelationRepresentation souffle::getRelationRepresentationFromTag (const RelationTag & tag) inline
Get the corresponding RelationRepresentation for a valid RelationTag.
Definition at line 105 of file RelationTag.h.
References BRIE, BTREE, EQREL, fatal(), and UNREACHABLE_BAD_CASE_ANALYSIS.
{
     switch (tag) {
         case RelationTag::BRIE: return RelationRepresentation::BRIE;
         case RelationTag::BTREE: return RelationRepresentation::BTREE;
         case RelationTag::EQREL: return RelationRepresentation::EQREL;
         default: fatal("invalid relation tag");
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
getStarttime()
ss<< R"_("code": [)_"; bool firstCol = true; while (getline(source_file, str)) { comma(firstCol, ",\n"); ss << '"' << Tools::cleanJsonOut(str) << '"'; } ss << "],\n"; source_file.close(); } auto usages = getUsageStats(100); auto beginTime = run-> souffle::getStarttime ()
getTypeAttributeAggregate()
TypeAttribute souffle::getTypeAttributeAggregate (const AggregateOp op) inline
Get return type of the aggregate.
Definition at line 90 of file AggregateOp.h.
References COUNT, Float, FMAX, FMIN, FSUM, MAX, MEAN, MIN, Signed, SUM, UMAX, UMIN, UNREACHABLE_BAD_CASE_ANALYSIS, Unsigned, and USUM.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), and souffle::ast::transform::TypeChecker::visitAggregator().
{
     switch (op) {
         case AggregateOp::COUNT:
         case AggregateOp::MAX:
         case AggregateOp::MIN:
         case AggregateOp::SUM: return TypeAttribute::Signed;
         case AggregateOp::MEAN:
         case AggregateOp::FMAX:
         case AggregateOp::FMIN:
         case AggregateOp::FSUM: return TypeAttribute::Float;
         case AggregateOp::UMAX:
         case AggregateOp::UMIN:
         case AggregateOp::USUM: return TypeAttribute::Unsigned;
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
identifier()
std::string souffle::identifier (std::string id) inline
Valid C++ identifier, note that this does not ensure the uniqueness of identifiers returned.
Definition at line 381 of file StringUtil.h.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::MakeIndexTransformer::getExpressionPair(), souffle::ram::transform::MakeIndexTransformer::getLowerUpperExpression(), main(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteScan().
{
     for (size_t i = 0; i < id.length(); i++) {
         if (((isalpha(id[i]) == 0) && i == 0) || ((isalnum(id[i]) == 0) && id[i] != '_')) {
             id[i] = '_';
         }
     }
     return id;
 }
isA() [1/3]
template<typename B , typename A > bool souffle::isA (A * x)
Checks if the object of type Source can be casted to type Destination.
Definition at line 173 of file MiscUtil.h.
                {
     return dynamic_cast<copy_const_t<A, B>*>(x) != nullptr;
 }
isA() [2/3]
template<typename B , typename A > std::enable_if_t<std::is_base_of_v<A, B>, bool> souffle::isA (A & x)
Definition at line 178 of file MiscUtil.h.
{
     return isA<B>(&x);
 }
isA() [3/3]
template<typename B , typename A > bool souffle::isA (const std::unique_ptr< A > & x)
Definition at line 183 of file MiscUtil.h.
{
     return isA<B>(x.get());
 }
isEqConstraint()
bool souffle::isEqConstraint (const BinaryConstraintOp constraintOp) inline
Definition at line 118 of file BinaryConstraintOps.h.
References EQ, and FEQ.
Referenced by souffle::ast::transform::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::findVariablesRecordMapping(), souffle::ram::transform::MakeIndexTransformer::getLowerUpperExpression(), souffle::ast::transform::FoldAnonymousRecords::isValidRecordConstraint(), souffle::ast::transform::ResolveAliasesTransformer::removeTrivialEquality(), souffle::ast::transform::ResolveAnonymousRecordAliasesTransformer::replaceUnnamedVariable(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), and souffle::ast::transform::FoldAnonymousRecords::transformClause().
{
     switch (constraintOp) {
         case BinaryConstraintOp::EQ:
         case BinaryConstraintOp::FEQ: return true;
         default: break;
     }
     return false;
 }
isExecutable()
bool souffle::isExecutable (const std::string & name) inline
Check whether a given file exists and it is an executable.
Definition at line 91 of file FileUtil.h.
References existFile().
Referenced by convertDotToSVG(), executeBinary(), findTool(), main(), and which().
{
     return existFile(name) && (access(name.c_str(), X_OK) == 0);
 }
isFunctorMultiResult()
bool souffle::isFunctorMultiResult (FunctorOp op)
Definition at line 247 of file FunctorOps.cpp.
References functorBuiltIn().
{
     auto&& xs = functorBuiltIn(op);
     return xs.front().get().multipleResults;
 }
isGreaterEqual()
bool souffle::isGreaterEqual (const BinaryConstraintOp constraintOp) inline
Definition at line 211 of file BinaryConstraintOps.h.
References FGE, GE, and UGE.
Referenced by souffle::ram::transform::MakeIndexTransformer::getExpressionPair().
{
     switch (constraintOp) {
         case BinaryConstraintOp::GE:
         case BinaryConstraintOp::UGE:
         case BinaryConstraintOp::FGE: return true;
         default: break;
     }
     return false;
 }
isGreaterThan()
bool souffle::isGreaterThan (const BinaryConstraintOp constraintOp) inline
Definition at line 191 of file BinaryConstraintOps.h.
References FGT, GT, and UGT.
{
     switch (constraintOp) {
         case BinaryConstraintOp::GT:
         case BinaryConstraintOp::UGT:
         case BinaryConstraintOp::FGT: return true;
         default: break;
     }
     return false;
 }
isInfixFunctorOp() [1/2]
bool souffle::isInfixFunctorOp (std::string_view symbol)
Determines whether a functor should be written using infix notation (e.g.
a + b + c) or prefix notation (e.g. +(a,b,c))
Generally follow Haskell convention: functions w/ symbolic names are infix, otherwise prefix. NOTE: The surface syntax occasionally uses alpha infix operators For backwards compatibility we translate these into symbolic ops.
Definition at line 252 of file FunctorOps.cpp.
References FUNCTOR_INTRINSIC_PREFIX_NEGATE_NAME.
Referenced by isInfixFunctorOp(), souffle::ram::IntrinsicOperator::print(), souffle::ast::IntrinsicFunctor::print(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor().
{
     assert(!symbol.empty() && "no functors have an empty name");
     // arithmetic/bitwise/logical negation are prefix ops
     if (symbol == FUNCTOR_INTRINSIC_PREFIX_NEGATE_NAME) return false;
     if (symbol == "!") return false;
     if (symbol == "~") return false;
     auto alphaUnderscore = symbol == "_" || isalpha(symbol.at(0));
     return !alphaUnderscore;
 }
isInfixFunctorOp() [2/2]
bool souffle::isInfixFunctorOp (const FunctorOp op)
Definition at line 262 of file FunctorOps.cpp.
References functorBuiltIn(), and isInfixFunctorOp().
{
     auto&& xs = functorBuiltIn(op);
     return isInfixFunctorOp(xs.front().get().symbol);
 }
isLessEqual()
bool souffle::isLessEqual (const BinaryConstraintOp constraintOp) inline
Definition at line 201 of file BinaryConstraintOps.h.
References FLE, LE, and ULE.
Referenced by souffle::ram::transform::MakeIndexTransformer::getExpressionPair().
{
     switch (constraintOp) {
         case BinaryConstraintOp::LE:
         case BinaryConstraintOp::ULE:
         case BinaryConstraintOp::FLE: return true;
         default: break;
     }
     return false;
 }
isLessThan()
bool souffle::isLessThan (const BinaryConstraintOp constraintOp) inline
Definition at line 181 of file BinaryConstraintOps.h.
References FLT, LT, and ULT.
{
     switch (constraintOp) {
         case BinaryConstraintOp::LT:
         case BinaryConstraintOp::ULT:
         case BinaryConstraintOp::FLT: return true;
         default: break;
     }
     return false;
 }
isNumber()
bool souffle::isNumber (const char * str) inline
Check whether a string is a sequence of digits.
Definition at line 211 of file StringUtil.h.
Referenced by souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainNegationGetVariables(), and main().
{
     if (str == nullptr) {
         return false;
     }
     while (*str != 0) {
         if (isdigit(*str) == 0) {
             return false;
         }
         str++;
     }
     return true;
 }
isOrderedBinaryConstraintOp()
bool souffle::isOrderedBinaryConstraintOp (const BinaryConstraintOp op) inline
Determines whether arguments of constraint are orderable.
Definition at line 383 of file BinaryConstraintOps.h.
References CONTAINS, EQ, FEQ, FGE, FGT, FLE, FLT, FNE, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, SGE, SGT, SLE, SLT, UGE, UGT, ULE, ULT, and UNREACHABLE_BAD_CASE_ANALYSIS.
Referenced by souffle::ExplainProvenanceImpl::explain(), and souffle::ast::transform::TypeChecker::visitBinaryConstraint().
{
     switch (op) {
         case BinaryConstraintOp::EQ:
         case BinaryConstraintOp::FEQ:
         case BinaryConstraintOp::NE:
         case BinaryConstraintOp::FNE:
         case BinaryConstraintOp::LT:
         case BinaryConstraintOp::ULT:
         case BinaryConstraintOp::FLT:
         case BinaryConstraintOp::LE:
         case BinaryConstraintOp::ULE:
         case BinaryConstraintOp::FLE:
         case BinaryConstraintOp::GE:
         case BinaryConstraintOp::UGE:
         case BinaryConstraintOp::FGE:
         case BinaryConstraintOp::GT:
         case BinaryConstraintOp::UGT:
         case BinaryConstraintOp::FGT:
         case BinaryConstraintOp::SLT:
         case BinaryConstraintOp::SLE:
         case BinaryConstraintOp::SGE:
         case BinaryConstraintOp::SGT: return true;
         case BinaryConstraintOp::MATCH:
         case BinaryConstraintOp::NOT_MATCH:
         case BinaryConstraintOp::CONTAINS:
         case BinaryConstraintOp::NOT_CONTAINS: return false;
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
isOverloaded()
bool souffle::isOverloaded (const BinaryConstraintOp constraintOp) inline
Utility function, informing whether constraint is overloaded.
Only the signed version's are treated as overloaded (as they are returned by the parser).
Definition at line 225 of file BinaryConstraintOps.h.
References EQ, GE, GT, LE, LT, and NE.
Referenced by souffle::ast::transform::PolymorphicObjectsTransformer::transform().
{
     switch (constraintOp) {
         case BinaryConstraintOp::EQ:
         case BinaryConstraintOp::NE:
         case BinaryConstraintOp::LT:
         case BinaryConstraintOp::LE:
         case BinaryConstraintOp::GT:
         case BinaryConstraintOp::GE: return true;
         default: break;
     }
     return false;
 }
isOverloadedAggregator()
bool souffle::isOverloadedAggregator (const AggregateOp op) inline
Definition at line 110 of file AggregateOp.h.
References COUNT, MAX, MEAN, MIN, and SUM.
Referenced by souffle::ast::transform::PolymorphicObjectsTransformer::transform().
{
     switch (op) {
         case AggregateOp::MAX:
         case AggregateOp::MIN:
         case AggregateOp::SUM: return true;
         case AggregateOp::MEAN:
         case AggregateOp::COUNT: return false;
         default: return false;
     }
 }
isOverloadedFunctor()
bool souffle::isOverloadedFunctor (std::string_view symbol)
Indicate whether a functor is overloaded.
At the moment, the signed versions are treated as representatives (because parser always returns a signed version).
isPrefix()
bool souffle::isPrefix (const std::string & prefix, const std::string & element) inline
Determine if one string is a prefix of another.
Definition at line 286 of file StringUtil.h.
Referenced by RamSignedFromString(), RamUnsignedFromString(), and souffle::ReadStreamCSV::readRamUnsigned().
{
     auto itPrefix = prefix.begin();
     auto itElement = element.begin();
     while (itPrefix != prefix.end() && itElement != element.end()) {
         if (*itPrefix != *itElement) {
             break;
         }
         ++itPrefix;
         ++itElement;
     }
     return itPrefix == prefix.end();
 }
isRelationQualifierTag()
bool souffle::isRelationQualifierTag (const RelationTag & tag) inline
Check if a given relation tag is a relation qualifier.
Definition at line 73 of file RelationTag.h.
References INLINE, INPUT, MAGIC, OUTPUT, OVERRIDABLE, PRINTSIZE, and SUPPRESSED.
{
     switch (tag) {
         case RelationTag::INPUT:
         case RelationTag::OUTPUT:
         case RelationTag::PRINTSIZE:
         case RelationTag::OVERRIDABLE:
         case RelationTag::INLINE:
         case RelationTag::MAGIC:
         case RelationTag::SUPPRESSED: return true;
         default: return false;
     }
 }
isRelationRepresentationTag()
bool souffle::isRelationRepresentationTag (const RelationTag & tag) inline
Check if a given relation tag sets a relation representation.
Definition at line 61 of file RelationTag.h.
References BRIE, BTREE, and EQREL.
{
     switch (tag) {
         case RelationTag::BRIE:
         case RelationTag::BTREE:
         case RelationTag::EQREL: return true;
         default: return false;
     }
 }
isStrictIneqConstraint()
bool souffle::isStrictIneqConstraint (const BinaryConstraintOp constraintOp) inline
Definition at line 127 of file BinaryConstraintOps.h.
References FGT, FLT, GT, LT, UGT, and ULT.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern(), convertStrictToNotEqualConstraint(), and convertStrictToWeakIneqConstraint().
{
     switch (constraintOp) {
         case BinaryConstraintOp::LT:
         case BinaryConstraintOp::GT:
         case BinaryConstraintOp::ULT:
         case BinaryConstraintOp::UGT:
         case BinaryConstraintOp::FLT:
         case BinaryConstraintOp::FGT: return true;
         default: break;
     }
     return false;
 }
isValidFunctorOpArity()
bool souffle::isValidFunctorOpArity (std::string_view symbol, size_t arity)
Definition at line 240 of file FunctorOps.cpp.
References any_of().
Referenced by souffle::ast::transform::TypeChecker::visitIntrinsicFunctor().
{
     return any_of(FUNCTOR_INTRINSICS, [&](auto&& x) {
         auto arityOk = x.params.size() == arity || x.variadic;
         return x.symbol == symbol && arityOk;
     });
 }
isWeakIneqConstraint()
bool souffle::isWeakIneqConstraint (const BinaryConstraintOp constraintOp) inline
Definition at line 140 of file BinaryConstraintOps.h.
References FGE, FLE, GE, LE, UGE, and ULE.
Referenced by souffle::ram::transform::MakeIndexTransformer::getLowerUpperExpression().
{
     switch (constraintOp) {
         case BinaryConstraintOp::LE:
         case BinaryConstraintOp::GE:
         case BinaryConstraintOp::ULE:
         case BinaryConstraintOp::UGE:
         case BinaryConstraintOp::FLE:
         case BinaryConstraintOp::FGE: return true;
         default: break;
     }
     return false;
 }
join() [1/5]
template<typename Iter , typename Printer > detail::joined_sequence<Iter, Printer> souffle::join (const Iter & a, const Iter & b, const std::string & sep, const Printer & p)
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 149 of file StreamUtil.h.
References b, and p.
Referenced by souffle::ParserDriver::addTag(), souffle::ast::transform::SemanticCheckerImpl::checkUnionType(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::synthesiser::Synthesiser::generateCode(), souffle::synthesiser::DirectRelation::generateTypeStruct(), souffle::synthesiser::IndirectRelation::generateTypeStruct(), souffle::synthesiser::BrieRelation::generateTypeStruct(), souffle::ast::transform::IODefaultsTransformer::getRelationName(), souffle::ast::transform::IOAttributesTransformer::getRelationName(), souffle::AstToRamTranslator::getRelationName(), souffle::synthesiser::DirectRelation::getTypeName(), souffle::synthesiser::IndirectRelation::getTypeName(), souffle::synthesiser::BrieRelation::getTypeName(), souffle::ast::analysis::getTypeQualifier(), join(), main(), souffle::ast::transform::makeInfoRelation(), operator<<(), std::operator<<(), souffle::ast::analysis::IOTypeAnalysis::print(), souffle::ast::RecordInit::print(), souffle::ast::ExecutionOrder::print(), souffle::ast::BranchInit::print(), souffle::ram::IntrinsicOperator::print(), souffle::ram::IO::print(), souffle::ast::BranchDeclaration::print(), souffle::ast::AlgebraicDataType::print(), souffle::ast::ComponentType::print(), souffle::ast::UnionType::print(), souffle::ast::RecordType::print(), souffle::ast::analysis::TopologicallySortedSCCGraphAnalysis::print(), souffle::ram::PackRecord::print(), souffle::ram::UserDefinedOperator::print(), souffle::ram::AbstractExistenceCheck::print(), souffle::ast::FunctorDeclaration::print(), souffle::ast::ExecutionPlan::print(), souffle::ast::QualifiedName::print(), souffle::ast::UserDefinedFunctor::print(), souffle::ram::Project::print(), souffle::ram::NestedIntrinsicOperator::print(), souffle::ast::Atom::print(), souffle::ast::IntrinsicFunctor::print(), souffle::ast::Aggregator::print(), souffle::ast::Directive::print(), souffle::ast::Clause::print(), souffle::ast::Relation::print(), souffle::ast::analysis::UnionType::print(), souffle::ast::analysis::RecordType::print(), souffle::ast::Program::print(), souffle::SymbolTable::print(), souffle::ast::analysis::SCCGraphAnalysis::print(), souffle::ast::Component::print(), souffle::ast::analysis::AlgebraicDataType::Branch::print(), souffle::ast::analysis::AlgebraicDataType::print(), souffle::AstToRamTranslator::ValueIndex::print(), souffle::ast::analysis::TypeSet::print(), souffle::ram::analysis::IndexAnalysis::print(), souffle::ast::analysis::Problem< TypeVar >::print(), souffle::profile::EventProcessor::process(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::QualifiedName::toString(), and souffle::ast::transform::TypeChecker::visitBinaryConstraint().
{
     return souffle::detail::joined_sequence<Iter, Printer>(a, b, sep, p);
 }
join() [2/5]
template<typename Iter , typename T = typename Iter::value_type> detail::joined_sequence<Iter, detail::print<id<T> > > souffle::join (const Iter & a, const Iter & b, const std::string & sep = ",")
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 161 of file StreamUtil.h.
References join().
{
     return join(a, b, sep, detail::print<id<T>>());
 }
join() [3/5]
template<typename Container , typename Printer , typename Iter = typename Container::const_iterator> detail::joined_sequence<Iter, Printer> souffle::join (const Container & c, const std::string & sep, const Printer & p)
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 173 of file StreamUtil.h.
References join(), and p.
{
     return join(c.begin(), c.end(), sep, p);
 }
join() [4/5]
template<typename Container , typename Iter = typename Container::const_iterator, typename T = typename Iter::value_type> std::enable_if_t<!JoinShouldDeref<T>, detail::joined_sequence<Iter, detail::print<id<T> > > > souffle::join (const Container & c, const std::string & sep = ",")
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 190 of file StreamUtil.h.
References join().
{
     return join(c.begin(), c.end(), sep, detail::print<id<T>>());
 }
join() [5/5]
template<typename Container , typename Iter = typename Container::const_iterator, typename T = typename Iter::value_type> std::enable_if_t<JoinShouldDeref<T>, detail::joined_sequence<Iter, detail::print<deref<T> > > > souffle::join (const Container & c, const std::string & sep = ",")
Definition at line 197 of file StreamUtil.h.
References join().
{
     return join(c.begin(), c.end(), sep, detail::print<deref<T>>());
 }
main()
int souffle::main (int argc, char ** argv)
Ensure that code generation is enabled if using SWIG interface option.
Definition at line 186 of file main.cpp.
References souffle::DebugReport::addSection(), baseName(), clone(), compileToBinary(), souffle::Global::config(), souffle::test::count(), e, souffle::DebugReport::endSection(), executeBinary(), existDir(), existFile(), explain(), findTool(), souffle::MainConfig::help(), identifier(), isExecutable(), isNumber(), join(), now(), PACKAGE_VERSION, souffle::ParserDriver::parseTranslationUnit(), souffle::MainConfig::processArgs(), RAM_DOMAIN_SIZE, souffle::profile::Tui::runProf(), simpleName(), splitString(), souffle::profile::ss, souffle::DebugReport::startSection(), tempFile(), souffle::test::time(), souffle::AstToRamTranslator::translateUnit(), and which().
Referenced by souffle::InterpreterEngine::executeMain(), souffle::InterpreterEngine::generateIR(), main(), souffle::ram::test::TEST(), and souffle::ram::test::testInterpreterStore().
{
     /* Time taking for overall runtime */
     auto souffle_start = std::chrono::high_resolution_clock::now();
     /* have all to do with command line arguments in its own scope, as these are accessible through the global
      * configuration only */
     try {
         std::stringstream header;
         header << "============================================================================" << std::endl;
         header << "souffle -- A datalog engine." << std::endl;
         header << "Usage: souffle [OPTION] FILE." << std::endl;
         header << "----------------------------------------------------------------------------" << std::endl;
         header << "Options:" << std::endl;
         std::stringstream footer;
         footer << "----------------------------------------------------------------------------" << std::endl;
         footer << "Version: " << PACKAGE_VERSION << "" << std::endl;
         footer << "----------------------------------------------------------------------------" << std::endl;
         footer << "Copyright (c) 2016-20 The Souffle Developers." << std::endl;
         footer << "Copyright (c) 2013-16 Oracle and/or its affiliates." << std::endl;
         footer << "All rights reserved." << std::endl;
         footer << "============================================================================" << std::endl;
         // command line options, the environment will be filled with the arguments passed to them, or
         // the empty string if they take none
         // main option, the datalog program itself, has an empty key
         std::vector<MainOption> options{{"", 0, "", "", false, ""},
                 {"fact-dir", 'F', "DIR", ".", false, "Specify directory for fact files."},
                 {"include-dir", 'I', "DIR", ".", true, "Specify directory for include files."},
                 {"output-dir", 'D', "DIR", ".", false,
                         "Specify directory for output files. If <DIR> is `-` then stdout is used."},
                 {"jobs", 'j', "N", "1", false,
                         "Run interpreter/compiler in parallel using N threads, N=auto for system "
                         "default."},
                 {"compile", 'c', "", "", false,
                         "Generate C++ source code, compile to a binary executable, then run this "
                         "executable."},
                 {"generate", 'g', "FILE", "", false,
                         "Generate C++ source code for the given Datalog program and write it to "
                         "<FILE>. If <FILE> is `-` then stdout is used."},
                 {"swig", 's', "LANG", "", false,
                         "Generate SWIG interface for given language. The values <LANG> accepts is java and "
                         "python. "},
                 {"library-dir", 'L', "DIR", "", false, "Specify directory for library files."},
                 {"libraries", 'l', "FILE", "", false, "Specify libraries."},
                 {"no-warn", 'w', "", "", false, "Disable warnings."},
                 {"magic-transform", 'm', "RELATIONS", "", false,
                         "Enable magic set transformation changes on the given relations, use '*' "
                         "for all."},
                 {"macro", 'M', "MACROS", "", false, "Set macro definitions for the pre-processor"},
                 {"disable-transformers", 'z', "TRANSFORMERS", "", false,
                         "Disable the given AST transformers."},
                 {"dl-program", 'o', "FILE", "", false,
                         "Generate C++ source code, written to <FILE>, and compile this to a "
                         "binary executable (without executing it)."},
                 {"live-profile", '\2', "", "", false, "Enable live profiling."},
                 {"profile", 'p', "FILE", "", false, "Enable profiling, and write profile data to <FILE>."},
                 {"profile-use", 'u', "FILE", "", false,
                         "Use profile log-file <FILE> for profile-guided optimization."},
                 {"debug-report", 'r', "FILE", "", false, "Write HTML debug report to <FILE>."},
                 {"pragma", 'P', "OPTIONS", "", false, "Set pragma options."},
                 {"provenance", 't', "[ none | explain | explore ]", "", false,
                         "Enable provenance instrumentation and interaction."},
                 {"verbose", 'v', "", "", false, "Verbose output."},
                 {"version", '\3', "", "", false, "Version."},
                 {"show", '\4',
                         "[ parse-errors | precedence-graph | scc-graph | transformed-datalog | "
                         "transformed-ram | type-analysis ]",
                         "", false, "Print selected program information."},
                 {"parse-errors", '\5', "", "", false, "Show parsing errors, if any, then exit."},
                 {"help", 'h', "", "", false, "Display this help message."},
                 {"legacy", '\6', "", "", false, "Enable legacy support."}};
         Global::config().processArgs(argc, argv, header.str(), footer.str(), options);
         // ------ command line arguments -------------
         // Take in pragma options from the command line
         if (Global::config().has("pragma")) {
             std::vector<std::string> configOptions = splitString(Global::config().get("pragma"), ';');
             for (const std::string& option : configOptions) {
                 size_t splitPoint = option.find(':');
                 std::string optionName = option.substr(0, splitPoint);
                 std::string optionValue = (splitPoint == std::string::npos)
                                                   ? ""
                                                   : option.substr(splitPoint + 1, option.length());
                 if (!Global::config().has(optionName)) {
                     Global::config().set(optionName, optionValue);
                 }
             }
         }
         /* for the version option, if given print the version text then exit */
         if (Global::config().has("version")) {
             std::cout << "Souffle: " << PACKAGE_VERSION;
             std::cout << "(" << RAM_DOMAIN_SIZE << "bit Domains)";
             std::cout << std::endl;
             std::cout << "Copyright (c) 2016-19 The Souffle Developers." << std::endl;
             std::cout << "Copyright (c) 2013-16 Oracle and/or its affiliates." << std::endl;
             return 0;
         }
         Global::config().set("version", PACKAGE_VERSION);
         /* for the help option, if given simply print the help text then exit */
         if (!Global::config().has("") || Global::config().has("help")) {
             std::cout << Global::config().help();
             return 0;
         }
         /* check that datalog program exists */
         if (!existFile(Global::config().get(""))) {
             throw std::runtime_error("cannot open file " + std::string(Global::config().get("")));
         }
         /* for the jobs option, to determine the number of threads used */
 #ifdef _OPENMP
         if (isNumber(Global::config().get("jobs").c_str())) {
             if (std::stoi(Global::config().get("jobs")) < 1) {
                 throw std::runtime_error("-j/--jobs may only be set to 'auto' or an integer greater than 0.");
             }
         } else {
             if (!Global::config().has("jobs", "auto")) {
                 throw std::runtime_error("-j/--jobs may only be set to 'auto' or an integer greater than 0.");
             }
             Global::config().set("jobs", "0");
         }
 #else
         // Check that -j option has not been changed from the default
         if (Global::config().get("jobs") != "1" && !Global::config().has("no-warn")) {
             std::cerr << "\nThis installation of Souffle does not support concurrent jobs.\n";
         }
 #endif
         /* if an output directory is given, check it exists */
         if (Global::config().has("output-dir") && !Global::config().has("output-dir", "-") &&
                 !existDir(Global::config().get("output-dir")) &&
                 !(Global::config().has("generate") ||
                         (Global::config().has("dl-program") && !Global::config().has("compile")))) {
             throw std::runtime_error(
                     "output directory " + Global::config().get("output-dir") + " does not exists");
         }
         /* collect all input directories for the c pre-processor */
         if (Global::config().has("include-dir")) {
             std::string currentInclude = "";
             std::string allIncludes = "";
             for (const char& ch : Global::config().get("include-dir")) {
                 if (ch == ' ') {
                     if (!existDir(currentInclude)) {
                         throw std::runtime_error("include directory " + currentInclude + " does not exists");
                     } else {
                         allIncludes += " -I";
                         allIncludes += currentInclude;
                         currentInclude = "";
                     }
                 } else {
                     currentInclude += ch;
                 }
             }
             allIncludes += " -I" + currentInclude;
             Global::config().set("include-dir", allIncludes);
         }
         /* collect all macro definitions for the pre-processor */
         if (Global::config().has("macro")) {
             std::string currentMacro = "";
             std::string allMacros = "";
             for (const char& ch : Global::config().get("macro")) {
                 if (ch == ' ') {
                     allMacros += " -D";
                     allMacros += currentMacro;
                     currentMacro = "";
                 } else {
                     currentMacro += ch;
                 }
             }
             allMacros += " -D" + currentMacro;
             Global::config().set("macro", allMacros);
         }
         /* turn on compilation of executables */
         if (Global::config().has("dl-program")) {
             Global::config().set("compile");
         }
         if (Global::config().has("live-profile") && !Global::config().has("profile")) {
             Global::config().set("profile");
         }
     } catch (std::exception& e) {
         std::cerr << e.what() << std::endl;
         exit(EXIT_FAILURE);
     }
     /**
      * Ensure that code generation is enabled if using SWIG interface option.
      */
     if (Global::config().has("swig") && !Global::config().has("generate")) {
         Global::config().set("generate", simpleName(Global::config().get("")));
     }
     // ------ start souffle -------------
     std::string souffleExecutable = which(argv[0]);
     if (souffleExecutable.empty()) {
         throw std::runtime_error("failed to determine souffle executable path");
     }
     /* Create the pipe to establish a communication between cpp and souffle */
     std::string cmd = ::which("mcpp");
     if (!isExecutable(cmd)) {
         throw std::runtime_error("failed to locate mcpp pre-processor");
     }
     cmd += " -e utf8 -W0 " + Global::config().get("include-dir");
     if (Global::config().has("macro")) {
         cmd += " " + Global::config().get("macro");
     }
     // Add RamDomain size as a macro
     cmd += " -DRAM_DOMAIN_SIZE=" + std::to_string(RAM_DOMAIN_SIZE);
     cmd += " " + Global::config().get("");
     FILE* in = popen(cmd.c_str(), "r");
     /* Time taking for parsing */
     auto parser_start = std::chrono::high_resolution_clock::now();
     // ------- parse program -------------
     // parse file
     ErrorReport errReport(Global::config().has("no-warn"));
     DebugReport debugReport;
     Own<ast::TranslationUnit> astTranslationUnit =
             ParserDriver::parseTranslationUnit("<stdin>", in, errReport, debugReport);
     // close input pipe
     int preprocessor_status = pclose(in);
     if (preprocessor_status == -1) {
         perror(nullptr);
         throw std::runtime_error("failed to close pre-processor pipe");
     }
     /* Report run-time of the parser if verbose flag is set */
     if (Global::config().has("verbose")) {
         auto parser_end = std::chrono::high_resolution_clock::now();
         std::cout << "Parse Time: " << std::chrono::duration<double>(parser_end - parser_start).count()
                   << "sec\n";
     }
     if (Global::config().get("show") == "parse-errors") {
         std::cout << astTranslationUnit->getErrorReport();
         return astTranslationUnit->getErrorReport().getNumErrors();
     }
     // ------- check for parse errors -------------
     astTranslationUnit->getErrorReport().exitIfErrors();
     // ------- rewriting / optimizations -------------
     /* set up additional global options based on pragma declaratives */
     (mk<ast::transform::PragmaChecker>())->apply(*astTranslationUnit);
     /* construct the transformation pipeline */
     // Equivalence pipeline
     auto equivalencePipeline =
             mk<ast::transform::PipelineTransformer>(mk<ast::transform::NameUnnamedVariablesTransformer>(),
                     mk<ast::transform::FixpointTransformer>(mk<ast::transform::MinimiseProgramTransformer>()),
                     mk<ast::transform::ReplaceSingletonVariablesTransformer>(),
                     mk<ast::transform::RemoveRelationCopiesTransformer>(),
                     mk<ast::transform::RemoveEmptyRelationsTransformer>(),
                     mk<ast::transform::RemoveRedundantRelationsTransformer>());
     // Magic-Set pipeline
     auto magicPipeline = mk<ast::transform::PipelineTransformer>(mk<ast::transform::MagicSetTransformer>(),
             mk<ast::transform::ResolveAliasesTransformer>(),
             mk<ast::transform::RemoveRelationCopiesTransformer>(),
             mk<ast::transform::RemoveEmptyRelationsTransformer>(),
             mk<ast::transform::RemoveRedundantRelationsTransformer>(), souffle::clone(equivalencePipeline));
     // Partitioning pipeline
     auto partitionPipeline =
             mk<ast::transform::PipelineTransformer>(mk<ast::transform::NameUnnamedVariablesTransformer>(),
                     mk<ast::transform::PartitionBodyLiteralsTransformer>(),
                     mk<ast::transform::ReplaceSingletonVariablesTransformer>());
     // Provenance pipeline
     auto provenancePipeline = mk<ast::transform::ConditionalTransformer>(Global::config().has("provenance"),
             mk<ast::transform::PipelineTransformer>(mk<ast::transform::ProvenanceTransformer>(),
                     mk<ast::transform::PolymorphicObjectsTransformer>()));
     // Main pipeline
     auto pipeline = mk<ast::transform::PipelineTransformer>(mk<ast::transform::ComponentChecker>(),
             mk<ast::transform::ComponentInstantiationTransformer>(),
             mk<ast::transform::IODefaultsTransformer>(),
             mk<ast::transform::UniqueAggregationVariablesTransformer>(),
             mk<ast::transform::UserDefinedFunctorsTransformer>(),
             mk<ast::transform::FixpointTransformer>(mk<ast::transform::PipelineTransformer>(
                     mk<ast::transform::ResolveAnonymousRecordAliasesTransformer>(),
                     mk<ast::transform::FoldAnonymousRecords>())),
             mk<ast::transform::PolymorphicObjectsTransformer>(), mk<ast::transform::SemanticChecker>(),
             mk<ast::transform::ADTtoRecordsTransformer>(),
             mk<ast::transform::MaterializeSingletonAggregationTransformer>(),
             mk<ast::transform::FixpointTransformer>(
                     mk<ast::transform::MaterializeAggregationQueriesTransformer>()),
             mk<ast::transform::ResolveAliasesTransformer>(), mk<ast::transform::RemoveTypecastsTransformer>(),
             mk<ast::transform::RemoveBooleanConstraintsTransformer>(),
             mk<ast::transform::ResolveAliasesTransformer>(), mk<ast::transform::MinimiseProgramTransformer>(),
             mk<ast::transform::InlineRelationsTransformer>(),
             mk<ast::transform::PolymorphicObjectsTransformer>(), mk<ast::transform::GroundedTermsChecker>(),
             mk<ast::transform::ResolveAliasesTransformer>(),
             mk<ast::transform::RemoveRedundantRelationsTransformer>(),
             mk<ast::transform::RemoveRelationCopiesTransformer>(),
             mk<ast::transform::RemoveEmptyRelationsTransformer>(),
             mk<ast::transform::ReplaceSingletonVariablesTransformer>(),
             mk<ast::transform::FixpointTransformer>(mk<ast::transform::PipelineTransformer>(
                     mk<ast::transform::ReduceExistentialsTransformer>(),
                     mk<ast::transform::RemoveRedundantRelationsTransformer>())),
             mk<ast::transform::RemoveRelationCopiesTransformer>(), std::move(partitionPipeline),
             std::move(equivalencePipeline), mk<ast::transform::RemoveRelationCopiesTransformer>(),
             std::move(magicPipeline), mk<ast::transform::ReorderLiteralsTransformer>(),
             mk<ast::transform::RemoveRedundantSumsTransformer>(),
             mk<ast::transform::RemoveEmptyRelationsTransformer>(),
             mk<ast::transform::AddNullariesToAtomlessAggregatesTransformer>(),
             mk<ast::transform::PolymorphicObjectsTransformer>(),
             mk<ast::transform::ReorderLiteralsTransformer>(), mk<ast::transform::ExecutionPlanChecker>(),
             std::move(provenancePipeline), mk<ast::transform::IOAttributesTransformer>());
     // Disable unwanted transformations
     if (Global::config().has("disable-transformers")) {
         std::vector<std::string> givenTransformers =
                 splitString(Global::config().get("disable-transformers"), ',');
         pipeline->disableTransformers(
                 std::set<std::string>(givenTransformers.begin(), givenTransformers.end()));
     }
     // Set up the debug report if necessary
     if (Global::config().has("debug-report")) {
         auto parser_end = std::chrono::high_resolution_clock::now();
         std::stringstream ss;
         // Add current time
         std::time_t time = std::time(nullptr);
         ss << "Executed at ";
         ss << std::put_time(std::localtime(&time), "%F %T") << "\n";
         // Add config
         ss << "(\n";
         ss << join(Global::config().data(), ",\n", [](std::ostream& out, const auto& arg) {
             out << "  \"" << arg.first << "\" -> \"" << arg.second << '"';
         });
         ss << "\n)";
         debugReport.addSection("Configuration", "Configuration", ss.str());
         // Add parsing runtime
         std::string runtimeStr =
                 "(" + std::to_string(std::chrono::duration<double>(parser_end - parser_start).count()) + "s)";
         debugReport.addSection("Parsing", "Parsing " + runtimeStr, "");
         pipeline->setDebugReport();
     }
     // Toggle pipeline verbosity
     pipeline->setVerbosity(Global::config().has("verbose"));
     // Apply all the transformations
     pipeline->apply(*astTranslationUnit);
     if (Global::config().has("show")) {
         // Output the transformed datalog and return
         if (Global::config().get("show") == "transformed-datalog") {
             std::cout << astTranslationUnit->getProgram() << std::endl;
             return 0;
         }
         // Output the precedence graph in graphviz dot format and return
         if (Global::config().get("show") == "precedence-graph") {
             astTranslationUnit->getAnalysis<ast::analysis::PrecedenceGraphAnalysis>()->print(std::cout);
             std::cout << std::endl;
             return 0;
         }
         // Output the scc graph in graphviz dot format and return
         if (Global::config().get("show") == "scc-graph") {
             astTranslationUnit->getAnalysis<ast::analysis::SCCGraphAnalysis>()->print(std::cout);
             std::cout << std::endl;
             return 0;
         }
         // Output the type analysis
         if (Global::config().get("show") == "type-analysis") {
             astTranslationUnit->getAnalysis<ast::analysis::TypeAnalysis>()->print(std::cout);
             std::cout << std::endl;
             return 0;
         }
     }
     // ------- execution -------------
     /* translate AST to RAM */
     debugReport.startSection();
     Own<ram::TranslationUnit> ramTranslationUnit = AstToRamTranslator().translateUnit(*astTranslationUnit);
     debugReport.endSection("ast-to-ram", "Translate AST to RAM");
     // Apply RAM transforms
     {
         using namespace ram::transform;
         Own<Transformer> ramTransform = mk<TransformerSequence>(
                 mk<LoopTransformer>(mk<TransformerSequence>(mk<ExpandFilterTransformer>(),
                         mk<HoistConditionsTransformer>(), mk<MakeIndexTransformer>())),
                 mk<LoopTransformer>(mk<IndexedInequalityTransformer>()), mk<IfConversionTransformer>(),
                 mk<ChoiceConversionTransformer>(), mk<CollapseFiltersTransformer>(), mk<TupleIdTransformer>(),
                 mk<LoopTransformer>(
                         mk<TransformerSequence>(mk<HoistAggregateTransformer>(), mk<TupleIdTransformer>())),
                 mk<ExpandFilterTransformer>(), mk<HoistConditionsTransformer>(),
                 mk<CollapseFiltersTransformer>(), mk<EliminateDuplicatesTransformer>(),
                 mk<ReorderConditionsTransformer>(), mk<LoopTransformer>(mk<ReorderFilterBreak>()),
                 mk<ConditionalTransformer>(
                         // job count of 0 means all cores are used.
                         []() -> bool { return std::stoi(Global::config().get("jobs")) != 1; },
                         mk<ParallelTransformer>()),
                 mk<ReportIndexTransformer>());
         ramTransform->apply(*ramTranslationUnit);
     }
     if (ramTranslationUnit->getErrorReport().getNumIssues() != 0) {
         std::cerr << ramTranslationUnit->getErrorReport();
     }
     // Output the transformed RAM program and return
     if (Global::config().get("show") == "transformed-ram") {
         std::cout << ramTranslationUnit->getProgram();
         return 0;
     }
     try {
         if (!Global::config().has("compile") && !Global::config().has("dl-program") &&
                 !Global::config().has("generate") && !Global::config().has("swig")) {
             // ------- interpreter -------------
             std::thread profiler;
             // Start up profiler if needed
             if (Global::config().has("live-profile") && !Global::config().has("compile")) {
                 profiler = std::thread([]() { profile::Tui().runProf(); });
             }
             // configure and execute interpreter
             Own<InterpreterEngine> interpreter(mk<InterpreterEngine>(*ramTranslationUnit));
             interpreter->executeMain();
             // If the profiler was started, join back here once it exits.
             if (profiler.joinable()) {
                 profiler.join();
             }
             if (Global::config().has("provenance")) {
                 // only run explain interface if interpreted
                 InterpreterProgInterface interface(*interpreter);
                 if (Global::config().get("provenance") == "explain") {
                     explain(interface, false);
                 } else if (Global::config().get("provenance") == "explore") {
                     explain(interface, true);
                 }
             }
         } else {
             // ------- compiler -------------
             auto synthesiser = mk<synthesiser::Synthesiser>(*ramTranslationUnit);
             // Find the base filename for code generation and execution
             std::string baseFilename;
             if (Global::config().has("dl-program")) {
                 baseFilename = Global::config().get("dl-program");
             } else if (Global::config().has("generate")) {
                 baseFilename = Global::config().get("generate");
                 // trim .cpp extension if it exists
                 if (baseFilename.size() >= 4 && baseFilename.substr(baseFilename.size() - 4) == ".cpp") {
                     baseFilename = baseFilename.substr(0, baseFilename.size() - 4);
                 }
             } else {
                 baseFilename = tempFile();
             }
             if (baseName(baseFilename) == "/" || baseName(baseFilename) == ".") {
                 baseFilename = tempFile();
             }
             std::string baseIdentifier = identifier(simpleName(baseFilename));
             std::string sourceFilename = baseFilename + ".cpp";
             bool withSharedLibrary;
             const bool emitToStdOut = Global::config().has("generate", "-");
             if (emitToStdOut)
                 synthesiser->generateCode(std::cout, baseIdentifier, withSharedLibrary);
             else {
                 std::ofstream os{sourceFilename};
                 synthesiser->generateCode(os, baseIdentifier, withSharedLibrary);
             }
             if (withSharedLibrary) {
                 if (!Global::config().has("libraries")) {
                     Global::config().set("libraries", "functors");
                 }
                 if (!Global::config().has("library-dir")) {
                     Global::config().set("library-dir", ".");
                 }
             }
             auto findCompileCmd = [&] {
                 auto cmd = ::findTool("souffle-compile", souffleExecutable, ".");
                 /* Fail if a souffle-compile executable is not found */
                 if (!isExecutable(cmd)) {
                     throw std::runtime_error("failed to locate souffle-compile");
                 }
                 return cmd;
             };
             if (Global::config().has("swig")) {
                 auto compileCmd = findCompileCmd() + " -s " + Global::config().get("swig") + " ";
                 compileToBinary(compileCmd, sourceFilename);
             } else if (Global::config().has("compile")) {
                 auto start = std::chrono::high_resolution_clock::now();
                 compileToBinary(findCompileCmd(), sourceFilename);
                 /* Report overall run-time in verbose mode */
                 if (Global::config().has("verbose")) {
                     auto end = std::chrono::high_resolution_clock::now();
                     std::cout << "Compilation Time: " << std::chrono::duration<double>(end - start).count()
                               << "sec\n";
                 }
                 // run compiled C++ program if requested.
                 if (!Global::config().has("dl-program") && !Global::config().has("swig")) {
                     executeBinary(baseFilename);
                 }
             }
         }
     } catch (std::exception& e) {
         std::cerr << e.what() << std::endl;
         std::exit(EXIT_FAILURE);
     }
     /* Report overall run-time in verbose mode */
     if (Global::config().has("verbose")) {
         auto souffle_end = std::chrono::high_resolution_clock::now();
         std::cout << "Total Time: " << std::chrono::duration<double>(souffle_end - souffle_start).count()
                   << "sec\n";
     }
     return 0;
 }
make_range()
template<typename Iter > range<Iter> souffle::make_range (const Iter & a, const Iter & b)
A utility function enabling the construction of ranges without explicitly specifying the iterator type.
Template Parameters
Iter .. the iterator type
Parameters
a .. the lower boundary
b .. the upper boundary
Definition at line 383 of file ContainerUtil.h.
References b.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::Trie< Arity >::getBoundaries(), souffle::Trie< 1u >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), souffle::Trie< Arity >::partition(), souffle::Trie< 1u >::partition(), and TEST().
{
     return range<Iter>(a, b);
 }
map()
template<typename A , typename F > auto souffle::map (const std::vector< A > & xs, F && f)
Applies a function to each element of a vector and returns the results.
Definition at line 152 of file ContainerUtil.h.
Referenced by souffle::ram::AbstractChoice::apply(), souffle::ram::RelationStatement::apply(), souffle::ram::RelationOperation::apply(), souffle::ram::AbstractLog::apply(), souffle::ram::AbstractOperator::apply(), souffle::ram::AbstractConditional::apply(), souffle::ast::Negation::apply(), souffle::ram::ListStatement::apply(), souffle::ram::Negation::apply(), souffle::ram::RelationSize::apply(), souffle::ram::Exit::apply(), souffle::ram::Loop::apply(), souffle::ram::EmptinessCheck::apply(), souffle::ram::IndexChoice::apply(), souffle::ram::PackRecord::apply(), souffle::ram::Query::apply(), souffle::ram::BinRelationStatement::apply(), souffle::ast::Term::apply(), souffle::ram::Aggregate::apply(), souffle::ast::TypeCast::apply(), souffle::ast::ExecutionPlan::apply(), souffle::ram::NestedOperation::apply(), souffle::ram::SubroutineReturn::apply(), souffle::ram::Conjunction::apply(), souffle::ram::AbstractExistenceCheck::apply(), souffle::ram::IndexAggregate::apply(), souffle::ast::BinaryConstraint::apply(), souffle::ram::UnpackRecord::apply(), souffle::ast::Atom::apply(), souffle::ram::Constraint::apply(), souffle::ram::IndexOperation::apply(), souffle::ram::Project::apply(), souffle::ram::NestedIntrinsicOperator::apply(), souffle::ast::Aggregator::apply(), souffle::ast::Clause::apply(), souffle::ast::Relation::apply(), souffle::ram::Program::apply(), souffle::ast::Program::apply(), souffle::synthesiser::Synthesiser::generateCode(), souffle::ram::analysis::MinIndexSelection::getLexOrder(), souffle::ram::analysis::MinIndexSelection::getLexOrderNum(), souffle::Trie< 1u >::getStore(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::ram::analysis::MinIndexSelection::isSubset(), souffle::ast::analysis::TypeConstraintsAnalysis::iterateOverAtom(), souffle::ast::FunctorDeclaration::print(), souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ram::analysis::MinIndexSelection::solve(), TEST(), souffle::ast::transform::transformEqrelRelation(), souffle::ast::validOverloads(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor().
{
     std::vector<decltype(f(xs[0]))> ys;
     ys.reserve(xs.size());
     for (auto&& x : xs) {
         ys.emplace_back(f(x));
     }
     return ys;
 }
mk()
template<typename A , typename B = A, typename... Args> Own<A> souffle::mk (Args &&... xs)
Definition at line 42 of file ContainerUtil.h.
{
     return Own<A>(new B(std::forward<Args>(xs)...));
 }
negatedConstraintOp()
BinaryConstraintOp souffle::negatedConstraintOp (const BinaryConstraintOp op) inline
Negated Constraint Operator Each operator requires a negated operator which is necessary for the expansion of complex rule bodies with disjunction and negation.
Definition at line 291 of file BinaryConstraintOps.h.
References CONTAINS, EQ, FEQ, FGE, FGT, FLE, FLT, FNE, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, SGE, SGT, SLE, SLT, UGE, UGT, ULE, ULT, and UNREACHABLE_BAD_CASE_ANALYSIS.
Referenced by souffle::ast::transform::FoldAnonymousRecords::isValidRecordConstraint(), and souffle::ast::negateConstraintInPlace().
{
     switch (op) {
         case BinaryConstraintOp::EQ: return BinaryConstraintOp::NE;
         case BinaryConstraintOp::FEQ: return BinaryConstraintOp::FNE;
         case BinaryConstraintOp::NE: return BinaryConstraintOp::EQ;
         case BinaryConstraintOp::FNE: return BinaryConstraintOp::FEQ;
         case BinaryConstraintOp::LT: return BinaryConstraintOp::GE;
         case BinaryConstraintOp::ULT: return BinaryConstraintOp::UGE;
         case BinaryConstraintOp::FLT: return BinaryConstraintOp::FGE;
         case BinaryConstraintOp::SLT: return BinaryConstraintOp::SGE;
         case BinaryConstraintOp::LE: return BinaryConstraintOp::GT;
         case BinaryConstraintOp::ULE: return BinaryConstraintOp::UGT;
         case BinaryConstraintOp::FLE: return BinaryConstraintOp::FGT;
         case BinaryConstraintOp::SLE: return BinaryConstraintOp::SGT;
         case BinaryConstraintOp::GE: return BinaryConstraintOp::LT;
         case BinaryConstraintOp::UGE: return BinaryConstraintOp::ULT;
         case BinaryConstraintOp::FGE: return BinaryConstraintOp::FLT;
         case BinaryConstraintOp::SGE: return BinaryConstraintOp::SLT;
         case BinaryConstraintOp::GT: return BinaryConstraintOp::LE;
         case BinaryConstraintOp::UGT: return BinaryConstraintOp::ULE;
         case BinaryConstraintOp::FGT: return BinaryConstraintOp::FLE;
         case BinaryConstraintOp::SGT: return BinaryConstraintOp::SLE;
         case BinaryConstraintOp::MATCH: return BinaryConstraintOp::NOT_MATCH;
         case BinaryConstraintOp::NOT_MATCH: return BinaryConstraintOp::MATCH;
         case BinaryConstraintOp::CONTAINS: return BinaryConstraintOp::NOT_CONTAINS;
         case BinaryConstraintOp::NOT_CONTAINS: return BinaryConstraintOp::CONTAINS;
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
none_of()
template<typename Container , typename UnaryPredicate > bool souffle::none_of (const Container & c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
Parameters
c the container
p the predicate
Returns
true if for all elements x in c the predicate p(x) is true, false otherwise; for empty containers the result is always true
Definition at line 132 of file FunctionalUtil.h.
References p.
{
     return std::none_of(c.begin(), c.end(), p);
 }
now()
time_point souffle::now () inline
Definition at line 83 of file MiscUtil.h.
Referenced by souffle::ram::transform::Transformer::apply(), souffle::ast::transform::MetaTransformer::applySubtransformer(), main(), souffle::ProfileEventSingleton::makeTimeEvent(), souffle::ProfileEventSingleton::makeUtilisationEvent(), souffle::ExplainProvenanceImpl::measureRelation(), souffle::profile::Reader::processFile(), souffle::test::TEST(), souffle::ast::transform::DebugReporter::transform(), souffle::AstToRamTranslator::translateUnit(), souffle::profile::Tui::Tui(), and souffle::Logger::~Logger().
{
     return std::chrono::high_resolution_clock::now();
 }
operator<<() [1/11]
std::ostream& souffle::operator<< (std::ostream & os, TypeAttribute T) inline
Definition at line 38 of file TypeAttribute.h.
References ADT, fatal(), Float, Record, Signed, Symbol, and Unsigned.
{
     switch (T) {
         case TypeAttribute::Symbol: return os << "TypeAttribute::Symbol";
         case TypeAttribute::Signed: return os << "TypeAttribute::Signed";
         case TypeAttribute::Float: return os << "TypeAttribute::Float";
         case TypeAttribute::Unsigned: return os << "TypeAttribute::Unsigned";
         case TypeAttribute::Record: return os << "TypeAttribute::Record";
         case TypeAttribute::ADT: return os << "TypeAttribute::ADT";
     }
     fatal("unhandled `TypeAttribute`");
 }
operator<<() [2/11]
std::ostream& souffle::operator<< (std::ostream & os, AggregateOp op) inline
Definition at line 45 of file AggregateOp.h.
References COUNT, FMAX, FMIN, FSUM, MAX, MEAN, MIN, SUM, UMAX, UMIN, UNREACHABLE_BAD_CASE_ANALYSIS, and USUM.
Referenced by souffle::Order::getOrder(), and souffle::TupleRef::operator==().
{
     switch (op) {
         case AggregateOp::COUNT: return os << "count";
         case AggregateOp::MEAN: return os << "mean";
         case AggregateOp::MAX:
         case AggregateOp::UMAX:
         case AggregateOp::FMAX: return os << "max";
         case AggregateOp::MIN:
         case AggregateOp::UMIN:
         case AggregateOp::FMIN: return os << "min";
         case AggregateOp::SUM:
         case AggregateOp::USUM:
         case AggregateOp::FSUM: return os << "sum";
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
operator<<() [3/11]
std::ostream& souffle::operator<< (std::ostream & os, BinaryConstraintOp x) inline
Definition at line 64 of file BinaryConstraintOps.h.
References toBinaryConstraintSymbol().
{
     return os << toBinaryConstraintSymbol(x);
 }
operator<<() [4/11]
std::ostream& souffle::operator<< (std::ostream & out, const Order & order)
Definition at line 66 of file InterpreterIndex.cpp.
References join(), and souffle::Order::order.
{
     return out << "[" << join(order.order) << "]";
 }
operator<<() [5/11]
std::ostream& souffle::operator<< (std::ostream & out, TupleRef ref)
Definition at line 70 of file InterpreterIndex.cpp.
References i, and souffle::TupleRef::size().
{
     out << "[";
     for (std::size_t i = 0; i < ref.size(); i++) {
         if (i > 0) {
             out << ',';
         }
         out << ref[i];
     }
     return out << "]";
 }
operator<<() [6/11]
std::ostream& souffle::operator<< (std::ostream & os, RelationTag qualifier) inline
Definition at line 116 of file RelationTag.h.
References BRIE, BTREE, EQREL, INLINE, INPUT, MAGIC, OUTPUT, OVERRIDABLE, PRINTSIZE, SUPPRESSED, and UNREACHABLE_BAD_CASE_ANALYSIS.
{
     switch (qualifier) {
         case RelationTag::INPUT: return os << "input";
         case RelationTag::OUTPUT: return os << "output";
         case RelationTag::PRINTSIZE: return os << "printsize";
         case RelationTag::OVERRIDABLE: return os << "overridable";
         case RelationTag::INLINE: return os << "inline";
         case RelationTag::MAGIC: return os << "magic";
         case RelationTag::SUPPRESSED: return os << "suppressed";
         case RelationTag::BRIE: return os << "brie";
         case RelationTag::BTREE: return os << "btree";
         case RelationTag::EQREL: return os << "eqrel";
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
operator<<() [7/11]
std::ostream& souffle::operator<< (std::ostream & os, RelationQualifier qualifier) inline
Definition at line 133 of file RelationTag.h.
References INLINE, INPUT, MAGIC, OUTPUT, OVERRIDABLE, PRINTSIZE, SUPPRESSED, and UNREACHABLE_BAD_CASE_ANALYSIS.
{
     switch (qualifier) {
         case RelationQualifier::INPUT: return os << "input";
         case RelationQualifier::OUTPUT: return os << "output";
         case RelationQualifier::PRINTSIZE: return os << "printsize";
         case RelationQualifier::OVERRIDABLE: return os << "overridable";
         case RelationQualifier::INLINE: return os << "inline";
         case RelationQualifier::MAGIC: return os << "magic";
         case RelationQualifier::SUPPRESSED: return os << "suppressed";
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
operator<<() [8/11]
template<typename T , unsigned size> std::ostream& souffle::operator<< (std::ostream & out, const LRUCache< T, size > & cache)
Definition at line 136 of file CacheUtil.h.
References souffle::LRUCache< T, size >::first.
{
     bool first = true;
     cache.forEachInOrder([&](const T& val) {
         if (!first) {
             out << ",";
         }
         first = false;
         out << val;
         return false;
     });
     return out;
 }
operator<<() [9/11]
std::ostream& souffle::operator<< (std::ostream & out, const RuleBody & body)
Definition at line 147 of file ParserUtils.cpp.
References souffle::RuleBody::dnf, and join().
{
     return out << join(body.dnf, ";", [](std::ostream& out, const RuleBody::clause& cur) {
         out << join(cur, ",", [](std::ostream& out, const RuleBody::literal& l) {
             if (l.negated) {
                 out << "!";
             }
             out << *l.atom;
         });
     });
 }
operator<<() [10/11]
std::ostream& souffle::operator<< (std::ostream & os, RelationRepresentation representation) inline
Definition at line 147 of file RelationTag.h.
References BRIE, BTREE, DEFAULT, EQREL, INFO, and UNREACHABLE_BAD_CASE_ANALYSIS.
{
     switch (representation) {
         case RelationRepresentation::BTREE: return os << "btree";
         case RelationRepresentation::BRIE: return os << "brie";
         case RelationRepresentation::EQREL: return os << "eqrel";
         case RelationRepresentation::INFO: return os << "info";
         case RelationRepresentation::DEFAULT: return os;
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
operator<<() [11/11]
std::ostream & souffle::operator<< (std::ostream & os, FunctorOp op)
Definition at line 285 of file FunctorOps.cpp.
{
     return os << functorOpNameLegacy(op);
 }
pack()
template<std::size_t Arity> RamDomain souffle::pack (RecordTable & recordTab, Tuple< RamDomain, Arity > tuple) inline
helper to convert tuple to record reference for the synthesiser
Definition at line 148 of file RecordTable.h.
References souffle::Tuple< Domain, _arity >::data, and souffle::RecordTable::pack().
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::analysis::LevelAnalysis::getLevel(), and souffle::test::TEST().
{
     return recordTab.pack(static_cast<RamDomain*>(tuple.data), Arity);
 }
pathJoin()
std::string souffle::pathJoin (const std::string & first, const std::string & second) inline
Join two paths together; note that this does not resolve overlaps or relative paths.
Definition at line 159 of file FileUtil.h.
{
     unsigned firstPos = static_cast<unsigned>(first.size()) - 1;
     while (first.at(firstPos) == '/') {
         firstPos--;
     }
     unsigned secondPos = 0;
     while (second.at(secondPos) == '/') {
         secondPos++;
     }
     return first.substr(0, firstPos + 1) + '/' + second.substr(secondPos);
 }
printHTMLGraph()
void souffle::printHTMLGraph (std::ostream & out, const std::string & dotSpec, const std::string & id) inline
Definition at line 220 of file GraphUtils.h.
References convertDotToSVG(), and toBase64().
Referenced by souffle::ast::analysis::PrecedenceGraphAnalysis::print(), and souffle::ast::analysis::SCCGraphAnalysis::print().
{
     std::string data = convertDotToSVG(dotSpec);
     if (data.find("<svg") != std::string::npos) {
         out << "<img alt='graph image' src='data:image/svg+xml;base64," << toBase64(data) << "'><br/>\n";
     } else {
         out << "<div class='" << id << "-source"
             << "'>\n<pre>" << dotSpec << "</pre>\n";
         out << "</div>\n";
     }
 }
ramBitCast()
template<typename To = RamDomain, typename From > To souffle::ramBitCast (From source)
In C++20 there will be a new way to cast between types by reinterpreting bits (std::bit_cast), but as of January 2020 it is not yet supported.
Cast a type by reinterpreting its bits. Domain is restricted to Ram Types only. Template takes two types (second type is never necessary because it can be deduced from the argument) The following always holds For type T and a : T ramBitCast<T>(ramBitCast<RamDomain>(a)) == a
Definition at line 76 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeAggregate(), souffle::ExplainProvenanceImpl::findTuple(), souffle::ExplainProvenanceImpl::measureRelation(), souffle::tuple::operator<<(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStream::readADT(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStream::readRecord(), souffle::ram::test::TEST(), and souffle::ExplainProvenance::valueRead().
{
     static_assert(isRamType<From> && isRamType<To>, "Bit casting should only be used on Ram Types.");
     static_assert(sizeof(To) == sizeof(From), "Can't bit cast types with different size.");
     To destination;
     memcpy(&destination, &source, sizeof(destination));
     return destination;
 }
RamFloatFromString()
RamFloat souffle::RamFloatFromString (const std::string & str, std::size_t * position = nullptr) inline
Converts a string to a RamFloat.
Definition at line 87 of file StringUtil.h.
Referenced by canBeParsedAsRamFloat(), souffle::AstToRamTranslator::getConstantRamRepresentation(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStream::readADT(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStream::readRecord(), souffle::evaluator::symbol2numeric(), souffle::AstToRamTranslator::translateValue(), and souffle::ExplainProvenance::valueRead().
{
     RamFloat val;
 #if RAM_DOMAIN_SIZE == 64
     val = std::stod(str, position);
 #else
     val = std::stof(str, position);
 #endif
     return static_cast<RamFloat>(val);
 }
RamSignedFromString()
RamSigned souffle::RamSignedFromString (const std::string & str, std::size_t * position = nullptr, const int base = 10) inline
Converts a string to a RamSigned.
This procedure has similar behaviour to std::stoi/stoll.
The procedure accepts prefixes 0b (if base = 2) and 0x (if base = 16) If base = 0, the procedure will try to infer the base from the prefix, if present.
Definition at line 45 of file StringUtil.h.
References base, isPrefix(), and str.
Referenced by canBeParsedAsRamSigned(), souffle::AstToRamTranslator::getConstantRamRepresentation(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStream::readADT(), souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStream::readRecord(), souffle::evaluator::symbol2numeric(), souffle::AstToRamTranslator::translateValue(), and souffle::ExplainProvenance::valueRead().
{
     RamSigned val;
     if (base == 0) {
         if (isPrefix("-0b", str) || isPrefix("0b", str)) {
             return RamSignedFromString(str, position, 2);
         } else if (isPrefix("-0x", str) || isPrefix("0x", str)) {
             return RamSignedFromString(str, position, 16);
         } else {
             return RamSignedFromString(str, position);
         }
     }
     std::string binaryNumber;
     bool parsingBinary = base == 2;
     // stoi/stoll can't handle base 2 prefix by default.
     if (parsingBinary) {
         if (isPrefix("-0b", str)) {
             binaryNumber = "-" + str.substr(3);
         } else if (isPrefix("0b", str)) {
             binaryNumber = str.substr(2);
         }
     }
     const std::string& tmp = parsingBinary ? binaryNumber : str;
 #if RAM_DOMAIN_SIZE == 64
     val = std::stoll(tmp, position, base);
 #else
     val = std::stoi(tmp, position, base);
 #endif
     if (parsingBinary && position != nullptr) {
         *position += 2;
     }
     return val;
 }
RamUnsignedFromString()
RamUnsigned souffle::RamUnsignedFromString (const std::string & str, std::size_t * position = nullptr, const int base = 10) inline
Converts a string to a RamUnsigned.
This procedure has similar behaviour to std::stoul/stoull.
The procedure accepts prefixes 0b (if base = 2) and 0x (if base = 16) If base = 0, the procedure will try to infer the base from the prefix, if present.
Definition at line 104 of file StringUtil.h.
References base, isPrefix(), and str.
Referenced by canBeParsedAsRamUnsigned(), souffle::AstToRamTranslator::getConstantRamRepresentation(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStream::readADT(), souffle::ReadStreamCSV::readRamUnsigned(), souffle::ReadStream::readRecord(), souffle::evaluator::symbol2numeric(), souffle::AstToRamTranslator::translateValue(), and souffle::ExplainProvenance::valueRead().
{
     // Be default C++ (stoul) allows unsigned numbers starting with "-".
     if (isPrefix("-", str)) {
         throw std::invalid_argument("Unsigned number can't start with minus.");
     }
     if (base == 0) {
         if (isPrefix("0b", str)) {
             return RamUnsignedFromString(str, position, 2);
         } else if (isPrefix("0x", str)) {
             return RamUnsignedFromString(str, position, 16);
         } else {
             return RamUnsignedFromString(str, position);
         }
     }
     // stoul/stoull can't handle binary prefix by default.
     std::string binaryNumber;
     bool parsingBinary = false;
     if (base == 2 && isPrefix("0b", str)) {
         binaryNumber = str.substr(2);
         parsingBinary = true;
     }
     const std::string& tmp = parsingBinary ? binaryNumber : str;
     RamUnsigned val;
 #if RAM_DOMAIN_SIZE == 64
     val = std::stoull(tmp, position, base);
 #else
     val = std::stoul(tmp, position, base);
 #endif
     if (parsingBinary && position != nullptr) {
         *position += 2;
     }
     // check if it's safe to cast (stoul returns unsigned long)
     if (val > std::numeric_limits<RamUnsigned>::max()) {
         throw std::invalid_argument("Unsigned number of of bounds");
     }
     return static_cast<RamUnsigned>(val);
 }
simpleName()
std::string souffle::simpleName (const std::string & path) inline
File name, with extension removed.
Definition at line 213 of file FileUtil.h.
References baseName().
Referenced by main().
{
     std::string name = baseName(path);
     const size_t lastDot = name.find_last_of('.');
     // file has no extension
     if (lastDot == std::string::npos) {
         return name;
     }
     const size_t lastSlash = name.find_last_of('/');
     // last slash occurs after last dot, so no extension
     if (lastSlash != std::string::npos && lastSlash > lastDot) {
         return name;
     }
     // last dot after last slash, or no slash
     return name.substr(0, lastDot);
 }
split()
std::vector<std::string> souffle::split (const std::string & s, char delim, int times = -1) inline
utility function to split a string
Definition at line 140 of file ExplainProvenance.h.
References souffle::profile::ss, and times().
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getSplitPoint(), souffle::Explain::processCommand(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::rebalance_or_split(), and souffle::profile::EventProcessorSingleton::splitSignature().
{
     std::vector<std::string> v;
     std::stringstream ss(s);
     std::string item;
     while ((times > 0 || times <= -1) && std::getline(ss, item, delim)) {
         v.push_back(item);
         times--;
     }
     if (ss.peek() != EOF) {
         std::string remainder;
         std::getline(ss, remainder);
         v.push_back(remainder);
     }
     return v;
 }
splitString()
std::vector<std::string> souffle::splitString (const std::string & str, char delimiter) inline
Splits a string given a delimiter.
Definition at line 315 of file StringUtil.h.
Referenced by compileToBinary(), executeBinary(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainNegationGetVariables(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::InterpreterEngine::loadDLL(), main(), and souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
     std::vector<std::string> parts;
     std::stringstream strstr(str);
     std::string token;
     while (std::getline(strstr, token, delimiter)) {
         parts.push_back(token);
     }
     return parts;
 }
stringify()
std::string souffle::stringify (const std::string & input) inline
Stringify a string using escapes for escape, newline, tab, double-quotes and semicolons.
Definition at line 328 of file StringUtil.h.
Referenced by souffle::ram::LogSize::print(), souffle::ram::DebugInfo::print(), souffle::ram::LogTimer::print(), souffle::ram::LogRelationTimer::print(), souffle::InnerNode::printJSON(), souffle::LeafNode::printJSON(), souffle::ExplainProvenanceImpl::printRulesJSON(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
     std::string str(input);
     // replace escapes with double escape sequence
     size_t start_pos = 0;
     while ((start_pos = str.find('\\', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\\\");
         start_pos += 2;
     }
     // replace semicolons with escape sequence
     start_pos = 0;
     while ((start_pos = str.find(';', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\;");
         start_pos += 2;
     }
     // replace double-quotes with escape sequence
     start_pos = 0;
     while ((start_pos = str.find('"', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\\"");
         start_pos += 2;
     }
     // replace newline with escape sequence
     start_pos = 0;
     while ((start_pos = str.find('\n', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\n");
         start_pos += 2;
     }
     // replace tab with escape sequence
     start_pos = 0;
     while ((start_pos = str.find('\t', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\t");
         start_pos += 2;
     }
     return str;
 }
tempFile()
std::string souffle::tempFile () inline
Generate temporary file.
Definition at line 251 of file FileUtil.h.
Referenced by main().
{
 #ifdef _WIN32
     std::string templ;
     std::FILE* f = nullptr;
     while (f == nullptr) {
         templ = std::tmpnam(nullptr);
         f = fopen(templ.c_str(), "wx");
     }
     fclose(f);
     return templ;
 #else
     char templ[40] = "./souffleXXXXXX";
     close(mkstemp(templ));
     return std::string(templ);
 #endif
 }
TEST() [1/53]
souffle::TEST (Matching , StaticTest_1)
Definition at line 33 of file max_matching_test.cpp.
References souffle::ram::analysis::MaxMatching::addEdge(), EXPECT_EQ, souffle::ram::analysis::MaxMatching::getNumMatchings(), souffle::ram::analysis::MaxMatching::match, and souffle::ram::analysis::MaxMatching::solve().
{
     TestMaxMatching match;
     match.addEdge(1, 7);
     match.addEdge(1, 8);
     match.addEdge(3, 7);
     match.addEdge(3, 10);
     match.addEdge(4, 9);
     match.addEdge(5, 9);
     match.addEdge(5, 10);
     match.addEdge(6, 12);
     match.solve();
     int num = match.getNumMatchings();
     EXPECT_EQ(num, 5);
 }
TEST() [2/53]
souffle::TEST (SparseArray , Basic)
Definition at line 40 of file brie_test.cpp.
References EXPECT_EQ, map(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> map;
     EXPECT_EQ(0, map[10]);
     EXPECT_EQ(0, map[12]);
     EXPECT_EQ(0, map[14]);
     EXPECT_EQ(0, map[120]);
     EXPECT_EQ(0, map[10]);
     EXPECT_EQ(0, map[12]);
     EXPECT_EQ(0, map[14]);
     EXPECT_EQ(0, map[120]);
     map.update(12, 1);
     EXPECT_EQ(0, map[10]);
     EXPECT_EQ(1, map[12]);
     EXPECT_EQ(0, map[14]);
     EXPECT_EQ(0, map[120]);
     map.update(14, 8);
     EXPECT_EQ(0, map[10]);
     EXPECT_EQ(1, map[12]);
     EXPECT_EQ(8, map[14]);
     EXPECT_EQ(0, map[120]);
     map.update(120, 4);
     EXPECT_EQ(0, map[10]);
     EXPECT_EQ(1, map[12]);
     EXPECT_EQ(8, map[14]);
     EXPECT_EQ(4, map[120]);
 }
TEST() [3/53]
souffle::TEST (Matching , StaticTest_2)
Definition at line 51 of file max_matching_test.cpp.
References souffle::ram::analysis::MaxMatching::addEdge(), EXPECT_EQ, souffle::ram::analysis::MaxMatching::getNumMatchings(), souffle::ram::analysis::MaxMatching::match, and souffle::ram::analysis::MaxMatching::solve().
{
     TestMaxMatching match;
     match.addEdge(1, 6);
     match.addEdge(1, 7);
     match.addEdge(2, 6);
     match.addEdge(2, 10);
     match.addEdge(3, 8);
     match.addEdge(3, 9);
     match.addEdge(4, 6);
     match.addEdge(4, 10);
     match.addEdge(5, 7);
     match.addEdge(5, 9);
     match.solve();
     int num = match.getNumMatchings();
     EXPECT_EQ(num, 5);
 }
TEST() [4/53]
souffle::TEST (SparseArray , Limits)
Definition at line 75 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::dump(), EXPECT_EQ, map(), toString(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> map;
     map.update(std::numeric_limits<typename SparseArray<int>::index_type>::min(), 10);
     map.update(std::numeric_limits<typename SparseArray<int>::index_type>::max(), 20);
     map.dump();
     std::vector<std::pair<uint32_t, int>> present;
     for (const auto& cur : map) {
         present.push_back(cur);
     }
     EXPECT_EQ("[(0,10),(4294967295,20)]", toString(present));
 }
TEST() [5/53]
souffle::TEST (SparseArray , Iterator)
Definition at line 91 of file brie_test.cpp.
References EXPECT_EQ, map(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> map;
     std::set<std::pair<int, int>> should;
     should.insert(std::make_pair(14, 4));
     should.insert(std::make_pair(0, 1));
     should.insert(std::make_pair(4, 2));
     should.insert(std::make_pair(38, 5));
     should.insert(std::make_pair(12, 3));
     should.insert(std::make_pair(120, 6));
     for (const auto& cur : should) {
         map.update(cur.first, cur.second);
     }
     std::set<std::pair<int, int>> is;
     for (const auto& cur : map) {
         is.insert(cur);
     }
     EXPECT_EQ(should, is);
 }
TEST() [6/53]
souffle::TEST (SparseArray , IteratorStress)
Definition at line 114 of file brie_test.cpp.
References ASSERT_TRUE, contains(), EXPECT_EQ, i, map(), n, and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     const static int N = 10000;
     SparseArray<int> map;
     std::vector<int> pos;
     while (pos.size() < N) {
         int n = random() % (N * 10);
         if (!contains(pos, n)) {
             pos.push_back(n);
         }
     }
     std::set<std::pair<int, int>> should;
     for (int i = 0; i < N; i++) {
         should.insert(std::make_pair(pos[i], i + 1));
     }
     for (const auto& cur : should) {
         map.update(cur.first, cur.second);
         ASSERT_TRUE(map[cur.first] == cur.second);
     }
     std::set<std::pair<int, int>> is;
     for (const auto& cur : map) {
         is.insert(cur);
     }
     EXPECT_EQ(should, is);
 }
TEST() [7/53]
souffle::TEST (SparseArray , IteratorStress2)
Definition at line 145 of file brie_test.cpp.
References ASSERT_LE, ASSERT_TRUE, contains(), EXPECT_EQ, i, j, map(), n, and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     const static int N = 1000;
     bool log = false;
     for (unsigned j = 0; j < N; j++) {
         SparseArray<int> map;
         if (log) std::cout << "Creating " << j << " random numbers ..\n";
         std::vector<int> pos;
         while (pos.size() < j) {
             int n = random() % (N * 10);
             if (!contains(pos, n)) {
                 pos.push_back(n);
             }
         }
         if (log) std::cout << "Creating input list ..\n";
         std::set<std::pair<int, int>> should;
         for (unsigned i = 0; i < j; i++) {
             should.insert(std::make_pair(pos[i], i + 1));
         }
         if (log) std::cout << "Filling in input list ..\n";
         for (const auto& cur : should) {
             map.update(cur.first, cur.second);
             ASSERT_TRUE(map[cur.first] == cur.second);
         }
         if (log) std::cout << "Sort should list ..\n";
         if (log) std::cout << "Collect is list ..\n";
         std::set<std::pair<int, int>> is;
         unsigned i = 0;
         for (const auto& cur : map) {
             is.insert(cur);
             i++;
             ASSERT_LE(i, j);
         }
         if (log) std::cout << "Comparing lists ..\n";
         EXPECT_EQ(should, is);
         if (log) std::cout << "Done\n\n";
     }
 }
TEST() [8/53]
souffle::TEST (SparseArray , Find)
Definition at line 191 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::end(), EXPECT_EQ, EXPECT_NE, souffle::SparseArray< T, BITS, merge_op, copy_op >::find(), map(), toString(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> map;
     EXPECT_EQ(map.end(), map.find(1));
     EXPECT_EQ(map.end(), map.find(12));
     EXPECT_EQ(map.end(), map.find(1400));
     map.update(1400, 1);
     EXPECT_EQ(map.end(), map.find(1));
     EXPECT_EQ(map.end(), map.find(12));
     EXPECT_NE(map.end(), map.find(1400));
     EXPECT_EQ("(1400,1)", toString(*map.find(1400)));
     map.update(12, 2);
     EXPECT_EQ(map.end(), map.find(1));
     EXPECT_NE(map.end(), map.find(12));
     EXPECT_NE(map.end(), map.find(1400));
     EXPECT_EQ("(12,2)", toString(*map.find(12)));
     EXPECT_EQ("(1400,1)", toString(*map.find(1400)));
     auto it = map.find(12);
     EXPECT_EQ("(12,2)", toString(*it));
     ++it;
     EXPECT_EQ("(1400,1)", toString(*it));
 }
TEST() [9/53]
souffle::TEST (SparseArray , Find2)
Definition at line 221 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::end(), EXPECT_EQ, EXPECT_NE, souffle::SparseArray< T, BITS, merge_op, copy_op >::find(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> a;
     EXPECT_EQ(a.end(), a.find(12));
     EXPECT_EQ(a.end(), a.find(14));
     EXPECT_EQ(a.end(), a.find(16));
     a.update(14, 4);
     EXPECT_EQ(a.end(), a.find(12));
     EXPECT_NE(a.end(), a.find(14));
     EXPECT_EQ(a.end(), a.find(16));
     a.update(16, 6);
     EXPECT_EQ(a.end(), a.find(12));
     EXPECT_NE(a.end(), a.find(14));
     EXPECT_NE(a.end(), a.find(16));
 }
TEST() [10/53]
souffle::TEST (SparseArray , Copy)
Definition at line 241 of file brie_test.cpp.
References EXPECT_EQ, m, and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> m;
     m.update(12, 1);
     m.update(14, 2);
     m.update(16, 3);
     auto a = m;
     EXPECT_EQ(1, m[12]);
     EXPECT_EQ(2, m[14]);
     EXPECT_EQ(3, m[16]);
     EXPECT_EQ(1, a[12]);
     EXPECT_EQ(2, a[14]);
     EXPECT_EQ(3, a[16]);
     m = a;
     EXPECT_EQ(1, m[12]);
     EXPECT_EQ(2, m[14]);
     EXPECT_EQ(3, m[16]);
     EXPECT_EQ(1, a[12]);
     EXPECT_EQ(2, a[14]);
     EXPECT_EQ(3, a[16]);
 }
TEST() [11/53]
souffle::TEST (SparseArray , Merge)
Definition at line 269 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::addAll(), EXPECT_EQ, toString(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     // tests whether the first reference is properly updated while merging sets
     SparseArray<int> m1;
     SparseArray<int> m2;
     m1.update(500, 2);
     m2.update(100, 1);
     m1.addAll(m2);
     std::vector<std::pair<int, int>> data;
     for (const auto& it : m1) {
         data.push_back(it);
     }
     EXPECT_EQ("[(100,1),(500,2)]", toString(data));
 }
TEST() [12/53]
souffle::TEST (SparseArray , LowerBound)
Definition at line 287 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::begin(), souffle::SparseArray< T, BITS, merge_op, copy_op >::dump(), souffle::SparseArray< T, BITS, merge_op, copy_op >::end(), EXPECT_EQ, souffle::SparseArray< T, BITS, merge_op, copy_op >::find(), souffle::SparseArray< T, BITS, merge_op, copy_op >::lowerBound(), m, and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     SparseArray<int> m;
     EXPECT_EQ(m.end(), m.lowerBound(0));
     EXPECT_EQ(m.end(), m.lowerBound(10));
     EXPECT_EQ(m.end(), m.lowerBound(12));
     EXPECT_EQ(m.end(), m.lowerBound(14));
     EXPECT_EQ(m.end(), m.lowerBound(400));
     EXPECT_EQ(m.end(), m.lowerBound(500));
     m.update(11, 120);
     m.dump();
     EXPECT_EQ(m.begin(), m.lowerBound(0));
     EXPECT_EQ(m.find(11), m.lowerBound(10));
     EXPECT_EQ(m.end(), m.lowerBound(12));
     EXPECT_EQ(m.end(), m.lowerBound(14));
     EXPECT_EQ(m.end(), m.lowerBound(400));
     EXPECT_EQ(m.end(), m.lowerBound(500));
     m.update(12, 140);
     m.dump();
     EXPECT_EQ(m.begin(), m.lowerBound(0));
     EXPECT_EQ(m.find(11), m.lowerBound(10));
     EXPECT_EQ(m.find(12), m.lowerBound(12));
     EXPECT_EQ(m.end(), m.lowerBound(14));
     EXPECT_EQ(m.end(), m.lowerBound(400));
     EXPECT_EQ(m.end(), m.lowerBound(500));
     m.update(300, 150);
     m.dump();
     EXPECT_EQ(m.begin(), m.lowerBound(0));
     EXPECT_EQ(m.find(11), m.lowerBound(10));
     EXPECT_EQ(m.find(12), m.lowerBound(12));
     EXPECT_EQ(m.find(300), m.lowerBound(14));
     EXPECT_EQ(m.end(), m.lowerBound(400));
     EXPECT_EQ(m.end(), m.lowerBound(500));
     m.update(450, 160);
     m.dump();
     EXPECT_EQ(m.begin(), m.lowerBound(0));
     EXPECT_EQ(m.find(11), m.lowerBound(10));
     EXPECT_EQ(m.find(12), m.lowerBound(12));
     EXPECT_EQ(m.find(300), m.lowerBound(14));
     std::cout << "\n";
     EXPECT_EQ(m.find(450), m.lowerBound(400));
     EXPECT_EQ(m.end(), m.lowerBound(500));
 }
TEST() [13/53]
souffle::TEST (SparseArray , LowerBound2)
Definition at line 335 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::end(), EXPECT_EQ, i, souffle::SparseArray< T, BITS, merge_op, copy_op >::lowerBound(), m, and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     for (uint32_t m = 0; m < 256; ++m) {
         SparseArray<uint32_t> a;
         std::set<uint32_t> r;
         for (uint32_t i = 0; i < 8; i++) {
             if (!(m & (1 << i))) {
                 continue;
             }
             a.update(i * 100, 10);
             r.insert(i * 100);
         }
         for (uint32_t i = 0; i < 10; i++) {
             auto a_res = a.lowerBound(i * 100);
             auto r_res = r.lower_bound(i * 100);
             EXPECT_EQ(a_res == a.end(), r_res == r.end()) << "\nm=" << std::bitset<8>(m) << "\ni=" << i;
             if (a_res == a.end()) {
                 continue;
             }
             EXPECT_EQ(a_res->first, *r_res) << "\nm=" << std::bitset<8>(m) << "\ni=" << i;
         }
     }
 }
TEST() [14/53]
souffle::TEST (SparseArray , UpperBound)
Definition at line 363 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::begin(), souffle::SparseArray< T, BITS, merge_op, copy_op >::dump(), souffle::SparseArray< T, BITS, merge_op, copy_op >::end(), EXPECT_EQ, souffle::SparseArray< T, BITS, merge_op, copy_op >::find(), m, souffle::SparseArray< T, BITS, merge_op, copy_op >::update(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::upperBound().
{
     SparseArray<int> m;
     EXPECT_EQ(m.end(), m.upperBound(0));
     EXPECT_EQ(m.end(), m.upperBound(10));
     EXPECT_EQ(m.end(), m.upperBound(12));
     EXPECT_EQ(m.end(), m.upperBound(14));
     EXPECT_EQ(m.end(), m.upperBound(400));
     EXPECT_EQ(m.end(), m.upperBound(500));
     m.update(11, 120);
     m.dump();
     EXPECT_EQ(m.begin(), m.upperBound(0));
     EXPECT_EQ(m.find(11), m.upperBound(10));
     EXPECT_EQ(m.end(), m.upperBound(11));
     EXPECT_EQ(m.end(), m.upperBound(12));
     EXPECT_EQ(m.end(), m.upperBound(14));
     EXPECT_EQ(m.end(), m.upperBound(400));
     EXPECT_EQ(m.end(), m.upperBound(500));
     m.update(12, 140);
     m.dump();
     EXPECT_EQ(m.begin(), m.upperBound(0));
     EXPECT_EQ(m.find(11), m.upperBound(10));
     EXPECT_EQ(m.find(12), m.upperBound(11));
     EXPECT_EQ(m.end(), m.upperBound(12));
     EXPECT_EQ(m.end(), m.upperBound(14));
     EXPECT_EQ(m.end(), m.upperBound(400));
     EXPECT_EQ(m.end(), m.upperBound(500));
     m.update(300, 150);
     m.dump();
     EXPECT_EQ(m.begin(), m.upperBound(0));
     EXPECT_EQ(m.find(11), m.upperBound(10));
     EXPECT_EQ(m.find(12), m.upperBound(11));
     EXPECT_EQ(m.find(300), m.upperBound(12));
     EXPECT_EQ(m.find(300), m.upperBound(14));
     EXPECT_EQ(m.end(), m.upperBound(400));
     EXPECT_EQ(m.end(), m.upperBound(500));
     m.update(450, 160);
     m.dump();
     EXPECT_EQ(m.begin(), m.upperBound(0));
     EXPECT_EQ(m.find(11), m.upperBound(10));
     EXPECT_EQ(m.find(12), m.upperBound(11));
     EXPECT_EQ(m.find(300), m.upperBound(12));
     EXPECT_EQ(m.find(300), m.upperBound(14));
     std::cout << "\n";
     EXPECT_EQ(m.find(450), m.upperBound(400));
     EXPECT_EQ(m.end(), m.upperBound(500));
 }
TEST() [15/53]
souffle::TEST (SparseArray , UpperBound2)
Definition at line 415 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::end(), EXPECT_EQ, i, m, souffle::SparseArray< T, BITS, merge_op, copy_op >::update(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::upperBound().
{
     for (uint32_t m = 0; m < 256; ++m) {
         SparseArray<uint32_t> a;
         std::set<uint32_t> r;
         for (uint32_t i = 0; i < 8; i++) {
             if (!(m & (1 << i))) {
                 continue;
             }
             a.update(i * 100, 10);
             r.insert(i * 100);
         }
         for (uint32_t i = 0; i < 10; i++) {
             auto a_res = a.upperBound(i * 100);
             auto r_res = r.upper_bound(i * 100);
             EXPECT_EQ(a_res == a.end(), r_res == r.end()) << "\nm=" << std::bitset<8>(m) << "\ni=" << i;
             if (a_res == a.end()) {
                 continue;
             }
             EXPECT_EQ(a_res->first, *r_res) << "\nm=" << std::bitset<8>(m) << "\ni=" << i;
         }
     }
 }
TEST() [16/53]
souffle::TEST (SparseArray , MemoryUsage)
Definition at line 443 of file brie_test.cpp.
References souffle::SparseArray< T, BITS, merge_op, copy_op >::empty(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::SparseArray< T, BITS, merge_op, copy_op >::getMemoryUsage(), and souffle::SparseArray< T, BITS, merge_op, copy_op >::update().
{
     if (sizeof(void*) > 4) {
         SparseArray<int> a;
         // an empty one should be small
         EXPECT_TRUE(a.empty());
         // EXPECT_EQ(56, a.getMemoryUsage());
         EXPECT_EQ(40, a.getMemoryUsage());
         // a single element should have the same size as an empty one
         a.update(12, 15);
         EXPECT_FALSE(a.empty());
         // EXPECT_EQ(56, a.getMemoryUsage());
         EXPECT_EQ(560, a.getMemoryUsage());
         // more than one => there are nodes
         a.update(14, 18);
         EXPECT_FALSE(a.empty());
         // EXPECT_EQ(576, a.getMemoryUsage());
         EXPECT_EQ(560, a.getMemoryUsage());
     } else {
         SparseArray<int> a;
         // an empty one should be small
         EXPECT_TRUE(a.empty());
         EXPECT_EQ(28, a.getMemoryUsage());
         // a single element should have the same size as an empty one
         a.update(12, 15);
         EXPECT_FALSE(a.empty());
         EXPECT_EQ(288, a.getMemoryUsage());
         // more than one => there are nodes
         a.update(14, 18);
         EXPECT_FALSE(a.empty());
         EXPECT_EQ(288, a.getMemoryUsage());
     }
 }
TEST() [17/53]
souffle::TEST (SparseBitMap , Basic)
Definition at line 483 of file brie_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, map(), and souffle::SparseBitMap< BITS >::set().
{
     SparseBitMap<> map;
     EXPECT_EQ(sizeof(std::bitset<sizeof(void*) * 8>), sizeof(void*));
     EXPECT_FALSE(map[12]);
     EXPECT_FALSE(map[120]);
     EXPECT_FALSE(map[84]);
     map.set(12);
     EXPECT_TRUE(map[12]);
     EXPECT_FALSE(map[120]);
     EXPECT_FALSE(map[84]);
     map.set(120);
     EXPECT_TRUE(map[12]);
     EXPECT_TRUE(map[120]);
     EXPECT_FALSE(map[84]);
     map.set(84);
     EXPECT_TRUE(map[12]);
     EXPECT_TRUE(map[120]);
     EXPECT_TRUE(map[84]);
 }
TEST() [18/53]
souffle::TEST (SparseBitMap , Stress)
Definition at line 511 of file brie_test.cpp.
References ASSERT_TRUE, contains(), EXPECT_EQ, i, map(), n, and souffle::SparseBitMap< BITS >::set().
{
     const static int N = 10000;
     SparseBitMap<> map;
     std::vector<int> should;
     while (should.size() < N) {
         int n = random() % (N * 10);
         if (!contains(should, n)) {
             should.push_back(n);
         }
     }
     for (const auto& cur : should) {
         map.set(cur);
         ASSERT_TRUE(map[cur]);
     }
     // check all the entries
     for (int i = 0; i < N * 10; i++) {
         EXPECT_EQ(map[i], contains(should, i));
     }
 }
TEST() [19/53]
souffle::TEST (SparseBitMap , Iterator)
Definition at line 535 of file brie_test.cpp.
References EXPECT_EQ, map(), and toString().
{
     SparseBitMap<> map;
     std::set<int> vals;
     for (const auto& cur : map) {
         vals.insert(cur);
     }
     EXPECT_EQ("{}", toString(vals));
     map.set(12);
     vals.clear();
     for (const auto& cur : map) {
         vals.insert(cur);
     }
     EXPECT_EQ("{12}", toString(vals));
     map.set(12);
     map.set(120);
     vals.clear();
     for (const auto& cur : map) {
         vals.insert(cur);
     }
     EXPECT_EQ("{12,120}", toString(vals));
     map.set(1234);
     vals.clear();
     for (const auto& cur : map) {
         vals.insert(cur);
     }
     EXPECT_EQ("{12,120,1234}", toString(vals));
 }
TEST() [20/53]
souffle::TEST (SparseBitMap , IteratorStress2)
Definition at line 574 of file brie_test.cpp.
References ASSERT_LE, ASSERT_TRUE, contains(), EXPECT_EQ, i, j, map(), n, and souffle::SparseBitMap< BITS >::set().
{
     const static int N = 1000;
     bool log = false;
     for (unsigned j = 0; j < N; j++) {
         SparseBitMap<> map;
         if (log) std::cout << "Creating " << j << " random numbers ..\n";
         std::set<int> should;
         while (should.size() < j) {
             int n = random() % (N * 10);
             if (!contains(should, n)) {
                 should.insert(n);
             }
         }
         if (log) std::cout << "Filling in input list ..\n";
         for (const auto& cur : should) {
             map.set(cur);
             ASSERT_TRUE(map[cur]);
         }
         if (log) std::cout << "Collect is list ..\n";
         std::set<int> is;
         unsigned i = 0;
         for (const auto& cur : map) {
             is.insert(cur);
             i++;
             if (i > j) {
                 map.dump();
                 std::cout << "Should: " << should << "\n";
                 std::cout << "    Is: " << is << "\n";
             }
             ASSERT_LE(i, j);
         }
         if (log) std::cout << "Comparing lists ..\n";
         EXPECT_EQ(should, is);
         if (log) std::cout << "Done\n\n";
     }
 }
TEST() [21/53]
souffle::TEST (SparseBitMap , Find)
Definition at line 619 of file brie_test.cpp.
References souffle::SparseBitMap< BITS >::end(), EXPECT_EQ, EXPECT_NE, souffle::SparseBitMap< BITS >::find(), map(), souffle::SparseBitMap< BITS >::set(), and toString().
{
     SparseBitMap<> map;
     EXPECT_EQ(map.end(), map.find(1));
     EXPECT_EQ(map.end(), map.find(12));
     EXPECT_EQ(map.end(), map.find(1400));
     map.set(1400);
     EXPECT_EQ(map.end(), map.find(1));
     EXPECT_EQ(map.end(), map.find(12));
     EXPECT_NE(map.end(), map.find(1400));
     EXPECT_EQ("1400", toString(*map.find(1400)));
     map.set(12);
     EXPECT_EQ(map.end(), map.find(1));
     EXPECT_NE(map.end(), map.find(12));
     EXPECT_NE(map.end(), map.find(1400));
     EXPECT_EQ("12", toString(*map.find(12)));
     EXPECT_EQ("1400", toString(*map.find(1400)));
     auto it = map.find(12);
     EXPECT_EQ("12", toString(*it));
     ++it;
     EXPECT_EQ("1400", toString(*it));
 }
TEST() [22/53]
souffle::TEST (SparseBitMap , Size)
Definition at line 649 of file brie_test.cpp.
References EXPECT_EQ, map(), souffle::SparseBitMap< BITS >::set(), and souffle::SparseBitMap< BITS >::size().
{
     SparseBitMap<> map;
     EXPECT_EQ(0, map.size());
     map.set(3);
     EXPECT_EQ(1, map.size());
     map.set(5);
     EXPECT_EQ(2, map.size());
     map.set(3);
     EXPECT_EQ(2, map.size());
     map.set(1000);
     EXPECT_EQ(3, map.size());
 }
TEST() [23/53]
souffle::TEST (SparseBitMap , CopyAndMerge)
Definition at line 662 of file brie_test.cpp.
References EXPECT_EQ, EXPECT_TRUE, m, souffle::SparseBitMap< BITS >::set(), and souffle::SparseBitMap< BITS >::test().
{
     SparseBitMap<> mapA;
     SparseBitMap<> mapB;
     SparseBitMap<> mapC;
     mapA.set(3);
     mapA.set(4);
     mapA.set(5);
     mapB.set(10000000);
     mapB.set(10000001);
     mapB.set(10000002);
     mapC.set(3);
     mapC.set(7);
     mapC.set(10000000);
     mapC.set(10000007);
     auto m = mapA;
     EXPECT_EQ(3, m.size());
     for (const auto& cur : m) {
         EXPECT_TRUE(mapA.test(cur));
     }
     m.addAll(mapA);
     EXPECT_EQ(3, m.size());
     for (const auto& cur : m) {
         EXPECT_TRUE(mapA.test(cur));
     }
     m.addAll(mapB);
     EXPECT_EQ(6, m.size());
     for (const auto& cur : m) {
         EXPECT_TRUE(mapA.test(cur) || mapB.test(cur));
     }
     m.addAll(mapC);
     EXPECT_EQ(8, m.size());
     for (const auto& cur : m) {
         EXPECT_TRUE(mapA.test(cur) || mapB.test(cur) || mapC.test(cur));
     }
 }
TEST() [24/53]
souffle::TEST (Trie , Basic)
Definition at line 709 of file brie_test.cpp.
References souffle::range< Iter >::begin(), contains(), souffle::range< Iter >::end(), EXPECT_FALSE, EXPECT_TRUE, and make_range().
                   {
     Trie<1> set;
     EXPECT_TRUE(set.empty());
     EXPECT_FALSE(set.contains(1));
     EXPECT_FALSE(set.contains(2));
     EXPECT_FALSE(set.contains(3));
     set.insert(1);
     EXPECT_TRUE(set.contains(1));
     EXPECT_FALSE(set.contains(2));
     EXPECT_FALSE(set.contains(3));
     set.insert(2);
     EXPECT_TRUE(set.contains(1));
     EXPECT_TRUE(set.contains(2));
     EXPECT_FALSE(set.contains(3));
 }
TEST() [25/53]
souffle::TEST (Trie , Iterator)
Definition at line 747 of file brie_test.cpp.
References EXPECT_EQ, and EXPECT_NE.
                      {
     Trie<2> set;
     EXPECT_EQ(set.begin(), set.end());
     set.insert(1, 2);
     EXPECT_NE(set.begin(), set.end());
     set.insert(4, 3);
     set.insert(5, 2);
     EXPECT_NE(set.begin(), set.end());
     EXPECT_EQ(3, card(set));
 }
TEST() [26/53]
souffle::TEST (Trie , IteratorStress_1D)
Definition at line 771 of file brie_test.cpp.
References contains(), EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
{
     using tuple = typename souffle::Tuple<RamDomain, 1>;
     const int N = 10000;
     Trie<1> set;
     std::set<tuple> data;
     while (data.size() < N) {
         tuple cur = tuple({{(RamDomain)(rand(N * 10))}});
         if (data.insert(cur).second) {
             EXPECT_FALSE(set.contains(cur));
             set.insert(cur);
             EXPECT_TRUE(set.contains(cur));
         }
     }
     std::set<tuple> is;
     for (const auto& cur : set) {
         is.insert(cur);
     }
     EXPECT_EQ(N, set.size());
     EXPECT_EQ(data, is);
 }
TEST() [27/53]
souffle::TEST (Trie , IteratorStress_2D)
Definition at line 797 of file brie_test.cpp.
References contains(), EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
{
     using tuple = typename souffle::Tuple<RamDomain, 2>;
     const int N = 10000;
     Trie<2> set;
     std::set<tuple> data;
     while (data.size() < N) {
         tuple cur;
         cur[0] = (RamDomain)(rand(N * 10));
         cur[1] = (RamDomain)(rand(N * 10));
         if (data.insert(cur).second) {
             EXPECT_FALSE(set.contains(cur));
             set.insert(cur);
             EXPECT_TRUE(set.contains(cur));
         }
     }
     std::set<tuple> is;
     for (const auto& cur : set) {
         is.insert(cur);
     }
     EXPECT_EQ(N, set.size());
     EXPECT_EQ(data, is);
 }
TEST() [28/53]
souffle::TEST (Trie , IteratorStress_3D)
Definition at line 825 of file brie_test.cpp.
References contains(), EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
{
     using tuple = typename souffle::Tuple<RamDomain, 3>;
     const int N = 10000;
     Trie<3> set;
     std::set<tuple> data;
     while (data.size() < N) {
         tuple cur;
         cur[0] = (RamDomain)(rand(N * 10));
         cur[1] = (RamDomain)(rand(N * 10));
         cur[2] = (RamDomain)(rand(N * 10));
         if (data.insert(cur).second) {
             EXPECT_FALSE(set.contains(cur));
             set.insert(cur);
             EXPECT_TRUE(set.contains(cur));
         }
     }
     std::set<tuple> is;
     for (const auto& cur : set) {
         is.insert(cur);
     }
     EXPECT_EQ(N, set.size());
     EXPECT_EQ(data, is);
 }
TEST() [29/53]
souffle::TEST (Trie , IteratorStress_4D)
Definition at line 854 of file brie_test.cpp.
References contains(), EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
{
     using tuple = typename souffle::Tuple<RamDomain, 4>;
     const int N = 10000;
     Trie<4> set;
     std::set<tuple> data;
     while (data.size() < N) {
         tuple cur;
         cur[0] = (RamDomain)(rand(N * 10));
         cur[1] = (RamDomain)(rand(N * 10));
         cur[2] = (RamDomain)(rand(N * 10));
         cur[3] = (RamDomain)(rand(N * 10));
         if (data.insert(cur).second) {
             EXPECT_FALSE(set.contains(cur));
             set.insert(cur);
             EXPECT_TRUE(set.contains(cur));
         }
     }
     std::set<tuple> is;
     for (const auto& cur : set) {
         is.insert(cur);
     }
     EXPECT_EQ(N, set.size());
     EXPECT_EQ(data, is);
 }
TEST() [30/53]
souffle::TEST (Trie , BoundaryTest_1D)
Definition at line 884 of file brie_test.cpp.
References b, EXPECT_EQ, i, and souffle::Trie< Dim >::insert().
{
     using test_set = Trie<1>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     auto a = t.lower_bound({5});
     EXPECT_EQ(5, (*a)[0]);
     auto b = t.upper_bound({5});
     EXPECT_EQ(6, (*b)[0]);
     // add duplicates
     t.insert(5);
     t.insert(5);
     t.insert(5);
     // test again ..
     a = t.lower_bound({5});
     EXPECT_EQ(5, (*a)[0]);
     b = t.upper_bound({5});
     EXPECT_EQ(6, (*b)[0]);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [31/53]
souffle::TEST (Trie , BoundaryTest_1D_2)
Definition at line 916 of file brie_test.cpp.
References b, EXPECT_EQ, i, and souffle::Trie< Dim >::insert().
{
     using test_set = Trie<1>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i * 100);
     }
     auto a = t.lower_bound({500});
     EXPECT_EQ(500, (*a)[0]);
     auto b = t.upper_bound({500});
     EXPECT_EQ(600, (*b)[0]);
     // add duplicates
     t.insert(500);
     t.insert(500);
     t.insert(500);
     // test again ..
     a = t.lower_bound({500});
     EXPECT_EQ(500, (*a)[0]);
     b = t.upper_bound({500});
     EXPECT_EQ(600, (*b)[0]);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [32/53]
souffle::TEST (Trie , BoundaryTest_1D_Stress)
Definition at line 948 of file brie_test.cpp.
References EXPECT_EQ, i, and souffle::Trie< Dim >::insert().
{
     using value_type = typename Trie<1>::element_type;
     using test_set = Trie<1>;
     using ref_set = std::set<value_type>;
     test_set t;
     ref_set r;
     for (int i = 5; i < 10; i++) {
         t.insert(i * 100);
         r.insert({i * 100});
     }
     // Check various lookup points
     for (int i = 0; i < 30; i++) {
         value_type key{i * 50};
         auto t_lb = t.lower_bound(key);
         auto r_lb = r.lower_bound(key);
         EXPECT_EQ(t_lb == t.end(), r_lb == r.end());
         if (t_lb != t.end() && r_lb != r.end()) {
             EXPECT_EQ(*t_lb, *r_lb);
         }
         auto t_ub = t.upper_bound(key);
         auto r_ub = r.upper_bound(key);
         EXPECT_EQ(t_ub == t.end(), r_ub == r.end());
         if (t_ub != t.end() && r_ub != r.end()) {
             EXPECT_EQ(*t_ub, *r_ub);
         }
     }
 }
TEST() [33/53]
souffle::TEST (Trie , BoundaryTest_1D_Stress_Dense)
Definition at line 983 of file brie_test.cpp.
References EXPECT_EQ, i, and souffle::Trie< Dim >::insert().
{
     using value_type = typename Trie<1>::element_type;
     using test_set = Trie<1>;
     using ref_set = std::set<value_type>;
     test_set t;
     ref_set r;
     for (int i = 100; i < 2000; i++) {
         t.insert(i);
         r.insert({i});
     }
     // Check various lookup points
     for (int i = 0; i < 2500; i++) {
         value_type key{i};
         auto t_lb = t.lower_bound(key);
         auto r_lb = r.lower_bound(key);
         EXPECT_EQ(t_lb == t.end(), r_lb == r.end());
         if (t_lb != t.end() && r_lb != r.end()) {
             EXPECT_EQ(*t_lb, *r_lb);
         }
         auto t_ub = t.upper_bound(key);
         auto r_ub = r.upper_bound(key);
         EXPECT_EQ(t_ub == t.end(), r_ub == r.end());
         if (t_ub != t.end() && r_ub != r.end()) {
             EXPECT_EQ(*t_ub, *r_ub);
         }
     }
 }
TEST() [34/53]
souffle::TEST (Trie , BoundaryTest_2D)
Definition at line 1018 of file brie_test.cpp.
References b, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), and j.
{
     using test_set = Trie<2>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         for (int j = 0; j < 10; j++) {
             t.insert(i, j);
         }
     }
     auto a = t.lower_bound({5, 5});
     EXPECT_EQ(5, (*a)[0]);
     EXPECT_EQ(5, (*a)[1]);
     auto b = t.upper_bound({5, 5});
     EXPECT_EQ(5, (*b)[0]);
     EXPECT_EQ(6, (*b)[1]);
     // add duplicates
     t.insert(5, 5);
     t.insert(5, 5);
     t.insert(5, 5);
     // test again ..
     a = t.lower_bound({5, 5});
     EXPECT_EQ(5, (*a)[0]);
     EXPECT_EQ(5, (*a)[1]);
     b = t.upper_bound({5, 5});
     EXPECT_EQ(5, (*b)[0]);
     EXPECT_EQ(6, (*b)[1]);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [35/53]
souffle::TEST (Trie , BoundaryTest_2D_2)
Definition at line 1056 of file brie_test.cpp.
References b, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), and j.
{
     using test_set = Trie<2>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         for (int j = 0; j < 10; j++) {
             t.insert(i * 100, j * 100);
         }
     }
     auto a = t.lower_bound({500, 500});
     EXPECT_EQ(500, (*a)[0]);
     EXPECT_EQ(500, (*a)[1]);
     auto b = t.upper_bound({500, 500});
     EXPECT_EQ(500, (*b)[0]);
     EXPECT_EQ(600, (*b)[1]);
     // add duplicates
     t.insert(500, 500);
     t.insert(500, 500);
     t.insert(500, 500);
     // test again ..
     a = t.lower_bound({500, 500});
     EXPECT_EQ(500, (*a)[0]);
     EXPECT_EQ(500, (*a)[1]);
     b = t.upper_bound({500, 500});
     EXPECT_EQ(500, (*b)[0]);
     EXPECT_EQ(600, (*b)[1]);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [36/53]
souffle::TEST (Trie , BoundaryTest_2D_Stress)
Definition at line 1094 of file brie_test.cpp.
References EXPECT_EQ, i, souffle::Trie< Dim >::insert(), and j.
{
     using value_type = typename Trie<2>::element_type;
     using test_set = Trie<2>;
     using ref_set = std::set<value_type>;
     test_set t;
     ref_set r;
     for (int i = 5; i < 10; i++) {
         for (int j = 5; j < 10; j++) {
             t.insert(i * 100, j * 100);
             r.insert({i * 100, j * 100});
         }
     }
     // Check various lookup points
     for (int i = 0; i < 30; i++) {
         for (int j = 0; j < 30; j++) {
             value_type key{i * 50, j * 50};
             auto t_lb = t.lower_bound(key);
             auto r_lb = r.lower_bound(key);
             EXPECT_EQ(t_lb == t.end(), r_lb == r.end());
             if (t_lb != t.end() && r_lb != r.end()) {
                 EXPECT_EQ(*t_lb, *r_lb);
             }
             auto t_ub = t.upper_bound(key);
             auto r_ub = r.upper_bound(key);
             EXPECT_EQ(t_ub == t.end(), r_ub == r.end());
             if (t_ub != t.end() && r_ub != r.end()) {
                 EXPECT_EQ(*t_ub, *r_ub);
             }
         }
     }
 }
TEST() [37/53]
souffle::TEST (Trie , BoundaryTest_2D_Stress_Dense)
Definition at line 1133 of file brie_test.cpp.
References EXPECT_EQ, i, souffle::Trie< Dim >::insert(), and j.
{
     using value_type = typename Trie<2>::element_type;
     using test_set = Trie<2>;
     using ref_set = std::set<value_type>;
     test_set t;
     ref_set r;
     for (int i = 100; i < 200; i++) {
         for (int j = 50; j < 250; j++) {
             t.insert(i, j);
             r.insert({i, j});
         }
     }
     // Check various lookup points
     for (int i = 0; i < 250; i++) {
         for (int j = 0; j < 300; j++) {
             value_type key{i, j};
             auto t_lb = t.lower_bound(key);
             auto r_lb = r.lower_bound(key);
             EXPECT_EQ(t_lb == t.end(), r_lb == r.end());
             if (t_lb != t.end() && r_lb != r.end()) {
                 EXPECT_EQ(*t_lb, *r_lb);
             }
             auto t_ub = t.upper_bound(key);
             auto r_ub = r.upper_bound(key);
             EXPECT_EQ(t_ub == t.end(), r_ub == r.end());
             if (t_ub != t.end() && r_ub != r.end()) {
                 EXPECT_EQ(*t_ub, *r_ub);
             }
         }
     }
 }
TEST() [38/53]
souffle::TEST (Trie , BoundaryTest_3D)
Definition at line 1172 of file brie_test.cpp.
References b, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), j, and k.
{
     using test_set = Trie<3>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         for (int j = 0; j < 10; j++) {
             for (int k = 0; k < 10; k++) {
                 t.insert(i, j, k);
             }
         }
     }
     auto a = t.lower_bound({5, 5, 5});
     EXPECT_EQ(5, (*a)[0]);
     EXPECT_EQ(5, (*a)[1]);
     EXPECT_EQ(5, (*a)[2]);
     auto b = t.upper_bound({5, 5, 5});
     EXPECT_EQ(5, (*b)[0]);
     EXPECT_EQ(5, (*b)[1]);
     EXPECT_EQ(6, (*b)[2]);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [39/53]
souffle::TEST (Trie , BoundaryTest_3D_2)
Definition at line 1199 of file brie_test.cpp.
References b, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), j, and k.
{
     using test_set = Trie<3>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         for (int j = 0; j < 10; j++) {
             for (int k = 0; k < 10; k++) {
                 t.insert(i * 100, j * 100, k * 100);
             }
         }
     }
     auto a = t.lower_bound({500, 500, 500});
     EXPECT_EQ(500, (*a)[0]);
     EXPECT_EQ(500, (*a)[1]);
     EXPECT_EQ(500, (*a)[2]);
     auto b = t.upper_bound({500, 500, 500});
     EXPECT_EQ(500, (*b)[0]);
     EXPECT_EQ(500, (*b)[1]);
     EXPECT_EQ(600, (*b)[2]);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [40/53]
souffle::TEST (Trie , BoundaryTest_3D_Stress)
Definition at line 1226 of file brie_test.cpp.
References EXPECT_EQ, i, souffle::Trie< Dim >::insert(), j, and k.
{
     using value_type = typename Trie<3>::element_type;
     using test_set = Trie<3>;
     using ref_set = std::set<value_type>;
     test_set t;
     ref_set r;
     for (int i = 5; i < 10; i++) {
         for (int j = 5; j < 10; j++) {
             for (int k = 5; k < 10; k++) {
                 t.insert(i * 100, j * 100, k * 100);
                 r.insert({i * 100, j * 100, k * 100});
             }
         }
     }
     // Check various lookup points
     for (int i = 0; i < 30; i++) {
         for (int j = 0; j < 30; j++) {
             for (int k = 0; k < 30; k++) {
                 value_type key{i * 50, j * 50, k * 50};
                 auto t_lb = t.lower_bound(key);
                 auto r_lb = r.lower_bound(key);
                 EXPECT_EQ(t_lb == t.end(), r_lb == r.end());
                 if (t_lb != t.end() && r_lb != r.end()) {
                     EXPECT_EQ(*t_lb, *r_lb);
                 }
                 auto t_ub = t.upper_bound(key);
                 auto r_ub = r.upper_bound(key);
                 EXPECT_EQ(t_ub == t.end(), r_ub == r.end());
                 if (t_ub != t.end() && r_ub != r.end()) {
                     EXPECT_EQ(*t_ub, *r_ub);
                 }
             }
         }
     }
 }
TEST() [41/53]
souffle::TEST (Trie , RangeQuery)
Definition at line 1269 of file brie_test.cpp.
References EXPECT_EQ, i, souffle::Trie< Dim >::insert(), j, and k.
{
     using tuple = typename souffle::Tuple<RamDomain, 3>;
     Trie<3> set;
     for (int i = 0; i < 10; i++) {
         for (int j = 0; j < 10; j++) {
             for (int k = 0; k < 10; k++) {
                 set.insert(i, j, k);
             }
         }
     }
     EXPECT_EQ(1000, set.size());
     // Range [*,*,*]
     EXPECT_EQ(1000, card(set.getBoundaries<0>(tuple({{3, 4, 5}}))));
     // Range [3,*,*]
     EXPECT_EQ(100, card(set.getBoundaries<1>(tuple({{3, 4, 5}}))));
     // Range [3,4,*]
     EXPECT_EQ(10, card(set.getBoundaries<2>(tuple({{3, 4, 5}}))));
     // Range [3,4,5]
     EXPECT_EQ(1, card(set.getBoundaries<3>(tuple({{3, 4, 5}}))));
 }
TEST() [42/53]
souffle::TEST (Trie , RangeQuery_1D)
Definition at line 1297 of file brie_test.cpp.
References EXPECT_EQ, and i.
{
     using tuple = typename souffle::Tuple<RamDomain, 1>;
     Trie<1> set;
     // empty set
     EXPECT_EQ(0, card(set.getBoundaries<0>(tuple({{3}}))));
     EXPECT_EQ(0, card(set.getBoundaries<1>(tuple({{3}}))));
     // add some elements
     for (int i = 0; i < 5; i++) {
         set.insert(i);
     }
     EXPECT_EQ(5, card(set.getBoundaries<0>(tuple({{3}}))));
     EXPECT_EQ(5, card(set.getBoundaries<0>(tuple({{7}}))));
     EXPECT_EQ(1, card(set.getBoundaries<1>(tuple({{3}}))));
     EXPECT_EQ(0, card(set.getBoundaries<1>(tuple({{7}}))));
 }
TEST() [43/53]
souffle::TEST (Trie , RangeQuery_2D)
Definition at line 1318 of file brie_test.cpp.
References EXPECT_EQ, i, and j.
{
     using tuple = typename souffle::Tuple<RamDomain, 2>;
     Trie<2> set;
     // empty set
     EXPECT_EQ(0, card(set.getBoundaries<0>(tuple({{3, 4}}))));
     EXPECT_EQ(0, card(set.getBoundaries<1>(tuple({{3, 4}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{3, 4}}))));
     // add some elements
     for (int i = 0; i < 5; i++) {
         for (int j = 0; j < 5; j++) {
             set.insert(i, j);
         }
     }
     EXPECT_EQ(25, card(set.getBoundaries<0>(tuple({{3, 4}}))));
     EXPECT_EQ(25, card(set.getBoundaries<0>(tuple({{7, 4}}))));
     EXPECT_EQ(25, card(set.getBoundaries<0>(tuple({{3, 7}}))));
     EXPECT_EQ(5, card(set.getBoundaries<1>(tuple({{3, 4}}))));
     EXPECT_EQ(0, card(set.getBoundaries<1>(tuple({{7, 4}}))));
     EXPECT_EQ(5, card(set.getBoundaries<1>(tuple({{3, 7}}))));
     EXPECT_EQ(1, card(set.getBoundaries<2>(tuple({{3, 4}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{7, 4}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{3, 7}}))));
 }
TEST() [44/53]
souffle::TEST (Trie , RangeQuery_3D)
Definition at line 1348 of file brie_test.cpp.
References EXPECT_EQ, i, j, and k.
{
     using tuple = typename souffle::Tuple<RamDomain, 3>;
     Trie<3> set;
     // empty set
     EXPECT_EQ(0, card(set.getBoundaries<0>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<1>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<3>(tuple({{3, 4, 2}}))));
     // add some elements
     for (int i = 0; i < 5; i++) {
         for (int j = 0; j < 5; j++) {
             for (int k = 0; k < 5; k++) {
                 set.insert(i, j, k);
             }
         }
     }
     EXPECT_EQ(125, card(set.getBoundaries<0>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(125, card(set.getBoundaries<0>(tuple({{7, 4, 2}}))));
     EXPECT_EQ(125, card(set.getBoundaries<0>(tuple({{3, 7, 2}}))));
     EXPECT_EQ(125, card(set.getBoundaries<0>(tuple({{3, 7, 8}}))));
     EXPECT_EQ(25, card(set.getBoundaries<1>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<1>(tuple({{7, 4, 2}}))));
     EXPECT_EQ(25, card(set.getBoundaries<1>(tuple({{3, 7, 2}}))));
     EXPECT_EQ(25, card(set.getBoundaries<1>(tuple({{3, 7, 8}}))));
     EXPECT_EQ(5, card(set.getBoundaries<2>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{7, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{3, 7, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<2>(tuple({{3, 7, 8}}))));
     EXPECT_EQ(5, card(set.getBoundaries<2>(tuple({{3, 2, 8}}))));
     EXPECT_EQ(1, card(set.getBoundaries<3>(tuple({{3, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<3>(tuple({{7, 4, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<3>(tuple({{3, 7, 2}}))));
     EXPECT_EQ(0, card(set.getBoundaries<3>(tuple({{3, 7, 8}}))));
 }
TEST() [45/53]
souffle::TEST (Trie , RangeQueryStress)
Definition at line 1390 of file brie_test.cpp.
References EXPECT_EQ, i, souffle::Trie< Dim >::insert(), j, and k.
{
     using tuple = typename souffle::Tuple<RamDomain, 3>;
     Trie<3> set;
     for (int i = 0; i < 10; i++) {
         for (int j = 0; j < 10; j++) {
             for (int k = 0; k < 10; k++) {
                 set.insert(i, j, k);
             }
         }
     }
     EXPECT_EQ(1000, set.size());
     // Range [*,*,*]
     EXPECT_EQ(1000, card(set.getBoundaries<0>(tuple({{3, 4, 5}}))));
     // Range [x,*,*]
     for (RamDomain x = 0; x < 10; x++) {
         EXPECT_EQ(100, card(set.getBoundaries<1>(tuple({{x, 4, 5}}))));
     }
     // Range [x,y,*]
     for (RamDomain x = 0; x < 10; x++) {
         for (RamDomain y = 0; y < 10; y++) {
             EXPECT_EQ(10, card(set.getBoundaries<2>(tuple({{x, y, 5}}))));
         }
     }
     // Range [x,y,*]
     for (RamDomain x = 0; x < 10; x++) {
         for (RamDomain y = 0; y < 10; y++) {
             for (RamDomain z = 0; z < 10; z++) {
                 EXPECT_EQ(1, card(set.getBoundaries<3>(tuple({{x, y, z}}))));
             }
         }
     }
 }
TEST() [46/53]
souffle::TEST (Trie , Merge_1D)
Definition at line 1430 of file brie_test.cpp.
References b, souffle::Trie< Dim >::contains(), e, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), and souffle::Trie< Dim >::insertAll().
                      {
     Trie<1> e;
     Trie<1> a;
     Trie<1> b;
     for (int i = 0; i < 5; i++) {
         a.insert(i);
         b.insert(i + 5);
     }
     {
         Trie<1> c = e;
         c.insertAll(a);
         for (int i = 0; i < 10; i++) {
             EXPECT_EQ(a.contains(i), c.contains(i));
         }
     }
     {
         Trie<1> c = e;
         c.insertAll(b);
         for (int i = 0; i < 10; i++) {
             EXPECT_EQ(b.contains(i), c.contains(i));
         }
     }
     {
         Trie<1> c = e;
         c.insertAll(a);
         c.insertAll(b);
         for (int i = 0; i < 10; i++) {
             EXPECT_EQ(a.contains(i) || b.contains(i), c.contains(i));
         }
     }
 }
TEST() [47/53]
souffle::TEST (Trie , Merge_2D)
Definition at line 1466 of file brie_test.cpp.
References b, souffle::Trie< Dim >::contains(), e, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), souffle::Trie< Dim >::insertAll(), and j.
                      {
     Trie<2> e;
     Trie<2> a;
     Trie<2> b;
     for (int i = 0; i < 5; i++) {
         for (int j = 0; j < 5; j++) {
             a.insert(i, j);
             b.insert(i + 5, j + 5);
         }
     }
     {
         Trie<2> c = e;
         c.insertAll(a);
         for (int i = 0; i < 10; i++) {
             for (int j = 0; j < 10; j++) {
                 EXPECT_EQ(a.contains(i, j), c.contains(i, j));
             }
         }
     }
     {
         Trie<2> c = e;
         c.insertAll(b);
         for (int i = 0; i < 10; i++) {
             for (int j = 0; j < 10; j++) {
                 EXPECT_EQ(b.contains(i, j), c.contains(i, j));
             }
         }
     }
     {
         Trie<2> c = e;
         c.insertAll(a);
         c.insertAll(b);
         for (int i = 0; i < 10; i++) {
             for (int j = 0; j < 10; j++) {
                 EXPECT_EQ(a.contains(i, j) || b.contains(i, j), c.contains(i, j));
             }
         }
     }
 }
TEST() [48/53]
souffle::TEST (Trie , Merge_3D)
Definition at line 1510 of file brie_test.cpp.
References b, souffle::Trie< Dim >::contains(), e, EXPECT_EQ, i, souffle::Trie< Dim >::insert(), souffle::Trie< Dim >::insertAll(), j, and k.
                      {
     Trie<3> e;
     Trie<3> a;
     Trie<3> b;
     for (int i = 0; i < 5; i++) {
         for (int j = 0; j < 5; j++) {
             for (int k = 0; k < 5; k++) {
                 a.insert(i, j, k);
                 b.insert(i + 5, j + 5, k + 5);
             }
         }
     }
     {
         Trie<3> c = e;
         c.insertAll(a);
         for (int i = 0; i < 10; i++) {
             for (int j = 0; j < 10; j++) {
                 for (int k = 0; k < 5; k++) {
                     EXPECT_EQ(a.contains(i, j, k), c.contains(i, j, k));
                 }
             }
         }
     }
     {
         Trie<3> c = e;
         c.insertAll(b);
         for (int i = 0; i < 10; i++) {
             for (int j = 0; j < 10; j++) {
                 for (int k = 0; k < 5; k++) {
                     EXPECT_EQ(b.contains(i, j, k), c.contains(i, j, k));
                 }
             }
         }
     }
     {
         Trie<3> c = e;
         c.insertAll(a);
         c.insertAll(b);
         for (int i = 0; i < 10; i++) {
             for (int j = 0; j < 10; j++) {
                 for (int k = 0; k < 5; k++) {
                     EXPECT_EQ(a.contains(i, j, k) || b.contains(i, j, k), c.contains(i, j, k));
                 }
             }
         }
     }
 }
TEST() [49/53]
souffle::TEST (Trie , Merge_Stress)
Definition at line 1562 of file brie_test.cpp.
References b, souffle::Trie< Dim >::begin(), souffle::Trie< Dim >::contains(), souffle::Trie< Dim >::end(), EXPECT_EQ, i, souffle::Trie< Dim >::insert(), and souffle::Trie< Dim >::insertAll().
{
     using entry_t = typename Trie<2>::entry_type;
     const int N = 1000;
     const int M = 100;
     std::set<entry_t> ref;
     Trie<2> a;
     for (int i = 0; i < M; i++) {
         Trie<2> b;
         for (int i = 0; i < N; i++) {
             RamDomain x = rand(N / 2);
             RamDomain y = rand(N / 2);
             if (!a.contains(x, y)) {
                 b.insert(x, y);
                 ref.insert(entry_t({{x, y}}));
             }
         }
         a.insertAll(b);
         std::set<entry_t> is(a.begin(), a.end());
         std::set<entry_t> should(ref.begin(), ref.end());
         EXPECT_EQ(should, is);
     }
 }
TEST() [50/53]
souffle::TEST (Trie , Merge_Bug)
Definition at line 1590 of file brie_test.cpp.
References b, souffle::Trie< Dim >::begin(), souffle::test::count(), souffle::Trie< Dim >::end(), EXPECT_EQ, souffle::Trie< Dim >::insert(), and souffle::Trie< Dim >::insertAll().
                       {
     // having this set ...
     Trie<2> a;
     a.insert(25129, 67714);
     a.insert(25132, 67714);
     a.insert(84808, 68457);
     //    a.getStore().dump();
     // ... merged with an empty set ...
     Trie<2> b;
     a.insertAll(b);
     //    a.getStore().dump();
     // and later on merged with a third set
     Trie<2> c;
     c.insert(133, 455);
     c.insert(10033, 455);
     a.insertAll(c);
     //    a.getStore().dump();
     // ... caused the first element to be missing in the iterator
     int count = 0;
     for (auto it = a.begin(); it != a.end(); ++it) {
         count++;
     }
     // if there are 5 elements, everything is fine
     EXPECT_EQ(5, count);
 }
TEST() [51/53]
souffle::TEST (Trie , Size)
Definition at line 1623 of file brie_test.cpp.
References souffle::Trie< Dim >::empty(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::Trie< Dim >::insert(), souffle::Trie< Dim >::insertAll(), and souffle::Trie< Dim >::size().
                  {
     Trie<2> t;
     EXPECT_TRUE(t.empty());
     EXPECT_EQ(0, t.size());
     t.insert(1, 2);
     EXPECT_FALSE(t.empty());
     EXPECT_EQ(1, t.size());
     t.insert(1, 2);
     EXPECT_FALSE(t.empty());
     EXPECT_EQ(1, t.size());
     t.insert(2, 1);
     EXPECT_FALSE(t.empty());
     EXPECT_EQ(2, t.size());
     Trie<2> t2;
     t2.insert(1, 2);
     t2.insert(1, 3);
     t2.insert(1, 4);
     t2.insert(3, 2);
     EXPECT_EQ(4, t2.size());
     t.insertAll(t2);
     EXPECT_FALSE(t.empty());
     EXPECT_EQ(5, t.size());
 }
TEST() [52/53]
souffle::TEST (Trie , Limits)
Definition at line 1658 of file brie_test.cpp.
References b, souffle::Trie< Dim >::begin(), souffle::Trie< Dim >::end(), EXPECT_EQ, souffle::Trie< Dim >::insert(), souffle::Trie< Dim >::insertAll(), and souffle::Trie< Dim >::size().
                    {
     Trie<2> data;
     EXPECT_EQ(0, data.size());
     data.insert(10, 15);
     EXPECT_EQ(1, data.size());
     data.insert((1 << 31) + (1 << 30), 18);
     EXPECT_EQ(2, data.size());
     Trie<2> a;
     a.insert(140, 15);
     Trie<2> b;
     b.insert(25445, 18);
     b.insertAll(a);
     EXPECT_EQ(2, b.size());
     int counter = 0;
     for (auto it = b.begin(); it != b.end(); ++it) {
         counter++;
     }
     EXPECT_EQ(2, counter);
 }
TEST() [53/53]
souffle::TEST (Trie , Parallel)
Definition at line 1685 of file brie_test.cpp.
References EXPECT_EQ, EXPECT_TRUE, filter(), i, souffle::Trie< Dim >::insert(), and souffle::Trie< Dim >::size().
                      {
     const int N = 10000;
     // get a unordered list of test data
     using entry_t = typename Trie<2>::entry_type;
     std::vector<entry_t> list;
     Trie<2> filter;
     while (filter.size() < N) {
         entry_t entry({{(RamDomain)(random() % N), (RamDomain)(random() % N)}});
         if (filter.insert(entry)) {
             list.push_back(entry);
         }
     }
     // the number of times duplicates show up in the input set
     for (int dup = 1; dup < 4; dup++) {
         // now duplicate this list
         std::vector<entry_t> full;
         for (int i = 0; i < dup; i++) {
             for (const auto& cur : list) {
                 full.push_back(cur);
             }
         }
         // shuffle data
         std::random_device rd;
         std::mt19937 generator(rd());
         std::shuffle(full.begin(), full.end(), generator);
         // now insert all those values into a new set - in parallel
         Trie<2> res;
 #pragma omp parallel for
         for (auto it = full.begin(); it < full.end(); ++it) {
             res.insert(*it);
         }
         // check resulting values
         EXPECT_EQ(N, res.size());
         std::set<entry_t> should(full.begin(), full.end());
         std::set<entry_t> is(res.begin(), res.end());
         for (const auto& cur : should) {
             EXPECT_TRUE(res.contains(cur)) << "Missing: " << cur << "\n";
         }
         for (const auto& cur : res) {
             EXPECT_TRUE(should.find(cur) != should.end()) << "Additional: " << cur << "\n"
                                                           << "Contained: " << res.contains(cur) << "\n";
         }
         std::vector<entry_t> extra;
         for (const auto& cur : is) {
             if (should.find(cur) == should.end()) extra.push_back(cur);
         }
         EXPECT_TRUE(extra.empty()) << "Extra elments: " << extra << "\n";
         std::vector<entry_t> missing;
         for (const auto& cur : should) {
             if (is.find(cur) == is.end()) missing.push_back(cur);
         }
         EXPECT_TRUE(missing.empty()) << "Missing elments: " << missing << "\n"
                                      << "All Elements: " << should << "\n";
         EXPECT_EQ(N, should.size());
         EXPECT_EQ(N, is.size());
         EXPECT_EQ(should, is);
     }
 }
times()
template<typename T > detail::multiplying_printer<T> souffle::times (const T & value, unsigned num)
A utility printing a given value multiple times.
Definition at line 284 of file StreamUtil.h.
Referenced by souffle::SparseArray< value_t, BITS, merge_op >::dump(), souffle::ram::LogSize::print(), souffle::ram::Swap::print(), souffle::ram::Clear::print(), souffle::ram::Call::print(), souffle::ram::Scan::print(), souffle::ram::Break::print(), souffle::ram::Filter::print(), souffle::ram::ParallelScan::print(), souffle::ram::Extend::print(), souffle::ram::IO::print(), souffle::ram::ParallelChoice::print(), souffle::ram::DebugInfo::print(), souffle::ram::Parallel::print(), souffle::ram::ParallelAggregate::print(), souffle::ram::Exit::print(), souffle::ram::LogTimer::print(), souffle::ram::Loop::print(), souffle::ram::IndexScan::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::Query::print(), souffle::ram::LogRelationTimer::print(), souffle::ram::ParallelIndexScan::print(), souffle::ram::Aggregate::print(), souffle::ram::Choice::print(), souffle::ram::ParallelIndexChoice::print(), souffle::ram::SubroutineReturn::print(), souffle::ram::IndexAggregate::print(), souffle::ram::UnpackRecord::print(), souffle::ram::Project::print(), souffle::ram::NestedIntrinsicOperator::print(), souffle::ram::IndexChoice::print(), and split().
{
     return detail::multiplying_printer<T>(value, num);
 }
toBase64()
std::string souffle::toBase64 (const std::string & data) inline
Definition at line 167 of file GraphUtils.h.
References i.
Referenced by printHTMLGraph().
{
     static const std::vector<char> table = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
             'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
             'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
             'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '+', '/'};
     std::string result;
     std::string tmp = data;
     unsigned int padding = 0;
     if (data.size() % 3 == 2) {
         padding = 1;
     } else if (data.size() % 3 == 1) {
         padding = 2;
     }
     for (unsigned int i = 0; i < padding; i++) {
         tmp.push_back(0);
     }
     for (unsigned int i = 0; i < tmp.size(); i += 3) {
         auto c1 = static_cast<unsigned char>(tmp[i]);
         auto c2 = static_cast<unsigned char>(tmp[i + 1]);
         auto c3 = static_cast<unsigned char>(tmp[i + 2]);
         unsigned char index1 = c1 >> 2;
         unsigned char index2 = ((c1 & 0x03) << 4) | (c2 >> 4);
         unsigned char index3 = ((c2 & 0x0F) << 2) | (c3 >> 6);
         unsigned char index4 = c3 & 0x3F;
         result.push_back(table[index1]);
         result.push_back(table[index2]);
         result.push_back(table[index3]);
         result.push_back(table[index4]);
     }
     if (padding == 1) {
         result[result.size() - 1] = '=';
     } else if (padding == 2) {
         result[result.size() - 1] = '=';
         result[result.size() - 2] = '=';
     }
     return result;
 }
toBinaryConstraintOp()
BinaryConstraintOp souffle::toBinaryConstraintOp (const std::string & symbol) inline
Converts symbolic representation of an operator to the operator.
Note that this won't tell you which polymorphic overload is actually used.
Definition at line 365 of file BinaryConstraintOps.h.
References CONTAINS, EQ, fatal(), GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, and NOT_MATCH.
Referenced by souffle::ExplainProvenanceImpl::explain().
{
     if (symbol == "=") return BinaryConstraintOp::EQ;
     if (symbol == "!=") return BinaryConstraintOp::NE;
     if (symbol == "<") return BinaryConstraintOp::LT;
     if (symbol == "<=") return BinaryConstraintOp::LE;
     if (symbol == ">=") return BinaryConstraintOp::GE;
     if (symbol == ">") return BinaryConstraintOp::GT;
     if (symbol == "match") return BinaryConstraintOp::MATCH;
     if (symbol == "contains") return BinaryConstraintOp::CONTAINS;
     if (symbol == "not_match") return BinaryConstraintOp::NOT_MATCH;
     if (symbol == "not_contains") return BinaryConstraintOp::NOT_CONTAINS;
     fatal("unrecognised binary operator: symbol = `%s`", symbol);
 }
toBinaryConstraintSymbol()
char const * souffle::toBinaryConstraintSymbol (const BinaryConstraintOp op) inline
Converts operator to its symbolic representation.
Definition at line 330 of file BinaryConstraintOps.h.
References CONTAINS, EQ, FEQ, FGE, FGT, FLE, FLT, FNE, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, SGE, SGT, SLE, SLT, UGE, UGT, ULE, ULT, and UNREACHABLE_BAD_CASE_ANALYSIS.
Referenced by souffle::ast::analysis::NormalisedClause::addClauseBodyLiteral(), souffle::ast::transform::makeInfoRelation(), operator<<(), and souffle::ram::Constraint::print().
{
     switch (op) {
         case BinaryConstraintOp::FEQ:
         case BinaryConstraintOp::EQ: return "=";
         case BinaryConstraintOp::FNE:
         case BinaryConstraintOp::NE: return "!=";
         case BinaryConstraintOp::SLT:
         case BinaryConstraintOp::ULT:
         case BinaryConstraintOp::FLT:
         case BinaryConstraintOp::LT: return "<";
         case BinaryConstraintOp::SLE:
         case BinaryConstraintOp::ULE:
         case BinaryConstraintOp::FLE:
         case BinaryConstraintOp::LE: return "<=";
         case BinaryConstraintOp::SGT:
         case BinaryConstraintOp::UGT:
         case BinaryConstraintOp::FGT:
         case BinaryConstraintOp::GT: return ">";
         case BinaryConstraintOp::SGE:
         case BinaryConstraintOp::UGE:
         case BinaryConstraintOp::FGE:
         case BinaryConstraintOp::GE: return ">=";
         case BinaryConstraintOp::MATCH: return "match";
         case BinaryConstraintOp::CONTAINS: return "contains";
         case BinaryConstraintOp::NOT_MATCH: return "not_match";
         case BinaryConstraintOp::NOT_CONTAINS: return "not_contains";
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
toPtrVector()
template<typename T > std::vector<T*> souffle::toPtrVector (const std::vector< std::unique_ptr< T >> & v)
A utility function enabling the creation of a vector of pointers.
Definition at line 140 of file ContainerUtil.h.
References e.
Referenced by souffle::ram::AbstractOperator::getArguments(), souffle::ram::PackRecord::getArguments(), souffle::ast::Term::getArguments(), souffle::ram::NestedIntrinsicOperator::getArguments(), souffle::ast::Atom::getArguments(), souffle::ast::Relation::getAttributes(), souffle::ast::Component::getBaseComponents(), souffle::ast::Aggregator::getBodyLiterals(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::AlgebraicDataType::getBranches(), souffle::ast::Program::getClauses(), souffle::ast::Component::getClauses(), souffle::ast::Program::getComponentInstantiations(), souffle::ast::Program::getComponents(), souffle::ast::Component::getComponents(), souffle::ast::Program::getDirectives(), souffle::ast::Component::getDirectives(), souffle::ast::BranchDeclaration::getFields(), souffle::ast::RecordType::getFields(), souffle::ast::Program::getFunctorDeclarations(), souffle::ast::Component::getInstantiations(), souffle::ram::IndexOperation::getRangePattern(), souffle::ast::Program::getRelations(), souffle::ram::Program::getRelations(), souffle::ast::Component::getRelations(), souffle::ram::ListStatement::getStatements(), souffle::ast::transform::PipelineTransformer::getSubtransformers(), souffle::ast::Program::getTypes(), souffle::ast::Component::getTypes(), souffle::ram::SubroutineReturn::getValues(), souffle::ram::AbstractExistenceCheck::getValues(), and souffle::ram::Project::getValues().
{
     std::vector<T*> res;
     for (auto& e : v) {
         res.push_back(e.get());
     }
     return res;
 }
toString() [1/3]
const std::string& souffle::toString (const std::string & str) inline
A generic function converting strings into strings (trivial case).
Definition at line 228 of file StringUtil.h.
References str.
Referenced by souffle::ast::analysis::NormalisedClause::addClauseBodyLiteral(), souffle::ParserDriver::addDirective(), souffle::ParserDriver::addFunctorDeclaration(), souffle::ParserDriver::addRelation(), souffle::ParserDriver::addType(), souffle::ram::transform::Transformer::apply(), souffle::ast::transform::SemanticCheckerImpl::checkAtom(), souffle::ast::transform::ComponentChecker::checkComponentNamespaces(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkIO(), souffle::ast::transform::SemanticCheckerImpl::checkNamespaces(), souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::SemanticCheckerImpl::checkUnionType(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::findUniqueAggregateRelationName(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::findUniqueVariableName(), genJsonAtoms(), souffle::profile::Tui::genJsonRelations(), genJsonRules(), souffle::ast::analysis::ComponentLookupAnalysis::getComponent(), souffle::ast::transform::IODefaultsTransformer::getRelationName(), souffle::ast::transform::IOAttributesTransformer::getRelationName(), souffle::AstToRamTranslator::getRelationName(), souffle::ast::analysis::getTypeQualifier(), souffle::ast::transform::makeInfoRelation(), souffle::ast::transform::makeRelationName(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::AstToRamTranslator::nameUnnamedVariables(), souffle::ast::pprint(), souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::test::TEST(), TEST(), souffle::ast::test::TEST(), souffle::ast::transform::test::TEST(), TEST(), souffle::ast::transform::UniqueAggregationVariablesTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), souffle::AstToRamTranslator::translateProgram(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
     return str;
 }
toString() [2/3]
template<typename T > std::enable_if<detail::is_printable<T>::value, std::string>::type souffle::toString (const T & value)
A generic function converting arbitrary objects to strings by utilizing their print capability.
This function is mainly intended for implementing test cases and debugging operations.
Definition at line 259 of file StringUtil.h.
{
     // write value into stream and return result
     std::stringstream ss;
     ss << value;
     return ss.str();
 }
toString() [3/3]
template<typename T > std::enable_if<!detail::is_printable<T>::value, std::string>::type souffle::toString (const T &)
A fallback for the to-string function in case an unprintable object is supposed to be printed.
Definition at line 271 of file StringUtil.h.
{
     std::stringstream ss;
     ss << "(print for type ";
     ss << typeid(T).name();
     ss << " not supported)";
     return ss.str();
 }
toVector() [1/2]
template<typename T > std::vector<T> souffle::toVector ()
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
This is the base case covering empty vectors.
Definition at line 122 of file ContainerUtil.h.
Referenced by souffle::ast::test::TEST(), and TEST().
{
     return std::vector<T>();
 }
toVector() [2/2]
template<typename T , typename... R> std::vector<T> souffle::toVector (const T & first, const R &... rest)
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
This is the step case covering vectors of arbitrary length.
Definition at line 132 of file ContainerUtil.h.
{
     return {first, rest...};
 }
unescape() [1/2]
std::string souffle::unescape (const std::string & inputString, const std::string & needle, const std::string & replacement) inline
Definition at line 392 of file StringUtil.h.
Referenced by souffle::AstToRamTranslator::getInputDirectives(), and souffle::AstToRamTranslator::getOutputDirectives().
{
     std::string result = inputString;
     size_t pos = 0;
     while ((pos = result.find(needle, pos)) != std::string::npos) {
         result = result.replace(pos, needle.length(), replacement);
         pos += replacement.length();
     }
     return result;
 }
unescape() [2/2]
std::string souffle::unescape (const std::string & inputString) inline
Definition at line 403 of file StringUtil.h.
{
     std::string unescaped = unescape(inputString, "\\\"", "\"");
     unescaped = unescape(unescaped, "\\t", "\t");
     unescaped = unescape(unescaped, "\\r", "\r");
     unescaped = unescape(unescaped, "\\n", "\n");
     return unescaped;
 }
which()
std::string souffle::which (const std::string & name) inline
Simple implementation of a which tool.
Definition at line 98 of file FileUtil.h.
References existDir(), isExecutable(), and souffle::ast::analysis::sub().
Referenced by convertDotToSVG(), and main().
{
     // Check if name has path components in it and if so return it immediately
     if (name.find('/') != std::string::npos) {
         return name;
     }
     // Get PATH from environment, if it exists.
     const char* syspath = ::getenv("PATH");
     if (syspath == nullptr) {
         return "";
     }
     char buf[PATH_MAX];
     std::stringstream sstr;
     sstr << syspath;
     std::string sub;
     // Check for existence of a binary called 'name' in PATH
     while (std::getline(sstr, sub, ':')) {
         std::string path = sub + "/" + name;
         if ((::realpath(path.c_str(), buf) != nullptr) && isExecutable(path) && !existDir(path)) {
             return buf;
         }
     }
     return "";
 }
Variable Documentation
else
souffle::else
Initial value:
{
            std::string str
Definition at line 485 of file Tui.h.
FUNCTOR_INTRINSIC_PREFIX_NEGATE_NAME
constexpr char souffle::FUNCTOR_INTRINSIC_PREFIX_NEGATE_NAME[] = "negate"
Definition at line 141 of file FunctorOps.h.
Referenced by isInfixFunctorOp().
getName
ss<< R"_("usage": [)_"; bool firstRow = true; Usage previousUsage = *usages.begin(); previousUsage.time = beginTime; for (auto usage : usages) { comma(firstRow); ss << '['; ss << (usage.time - beginTime).count() / 1000000.0 << ", "; ss << 100.0 * (usage.usertime - previousUsage.usertime) / (usage.time - previousUsage.time) << ", "; ss << 100.0 * (usage.systemtime - previousUsage.systemtime) / (usage.time - previousUsage.time) << ", "; ss << usage.maxRSS * 1024 << ", "; ss << '"'; bool firstCol = true; for (auto& cur : out.getProgramRun()->getRelationsAtTime(previousUsage.time, usage.time)) { comma(firstCol); ss << cur-> souffle::getName()
Definition at line 518 of file Tui.h.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkRecordType(), souffle::AstToRamTranslator::translateProgram(), and souffle::AstToRamTranslator::translateRecursiveRelation().
isRamType
template<typename T > constexpr bool souffle::isRamType
Initial value:
= (std::is_same<T, RamDomain>::value || std::is_same<T, RamSigned>::value ||
                            std::is_same<T, RamUnsigned>::value || std::is_same<T, RamFloat>::value)
Definition at line 61 of file RamTypes.h.
JoinShouldDeref
template<typename A > constexpr bool souffle::JoinShouldDeref = IsPtrLike<A>::value && !std::is_same_v<A, char const*>
Definition at line 180 of file StreamUtil.h.
MAX_RAM_FLOAT
constexpr RamFloat souffle::MAX_RAM_FLOAT = std::numeric_limits<RamFloat>::max()
Definition at line 92 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
MAX_RAM_SIGNED
constexpr RamSigned souffle::MAX_RAM_SIGNED = std::numeric_limits<RamSigned>::max()
Definition at line 86 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeAggregate(), souffle::NodeGenerator::getExistenceSuperInstInfo(), and souffle::NodeGenerator::getIndexSuperInstInfo().
MAX_RAM_UNSIGNED
constexpr RamUnsigned souffle::MAX_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::max()
Definition at line 89 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
MIN_RAM_FLOAT
constexpr RamFloat souffle::MIN_RAM_FLOAT = std::numeric_limits<RamFloat>::lowest()
Definition at line 91 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
MIN_RAM_SIGNED
constexpr RamSigned souffle::MIN_RAM_SIGNED = std::numeric_limits<RamSigned>::min()
lower and upper boundaries for the ram types
Definition at line 85 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeAggregate(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::NodeGenerator::getIndexSuperInstInfo(), and souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound().
MIN_RAM_UNSIGNED
constexpr RamUnsigned souffle::MIN_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::min()
Definition at line 88 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
rank_mask
constexpr block_t souffle::rank_mask = (1ul << split_size) - 1
Definition at line 43 of file UnionFind.h.
Referenced by souffle::DisjointSet::b2r().
split_size
constexpr uint8_t souffle::split_size = 8u
Definition at line 38 of file UnionFind.h.
Referenced by souffle::DisjointSet::b2p().