souffle: souffle::ast Namespace Reference
souffle::ast Namespace Reference
Namespaces
analysis
detail
test
transform
Data Structures
class Aggregator
Defines the aggregator class.
class AlgebraicDataType
Combination of types using sums and products.
class AllBoundSips
Goal: Prioritise atoms with all arguments bound.
class Argument
An abstract class for arguments.
struct ast_visitor_tag
A tag type required for the is_ast_visitor type trait to identify AstVisitors.
class Atom
An atom class.
class Attribute
Attribute class.
class BinaryConstraint
Binary constraint class.
class BindingStore
class BooleanConstraint
Boolean constraint class.
class BranchDeclaration
Wrapper for the single branch declaration (product type) inside ADT declaration.
class BranchInit
Initialization of ADT instance.
class Clause
Intermediate representation of a horn clause.
class Component
Component class.
class ComponentInit
Component initialization class.
class ComponentType
Component type of a component.
class Constant
Abstract constant class.
class Constraint
Abstract class for AST constraints.
class Counter
counter functor (incrementing a value after each invocation)
class Directive
a directive has a type (e.g.
class ExecutionOrder
An execution order for atoms within a clause; one or more execution orders form a plan.
class ExecutionPlan
class Functor
Abstract functor class.
class FunctorDeclaration
User-defined functor declaration.
class IntrinsicFunctor
Intrinsic Functor class for functors are in-built.
class LeastFreeSips
Goal: choose the atom with the least number of unbound arguments.
class LeastFreeVarsSips
Goal: choose the atom with the least amount of unbound variables.
class Literal
Defines an abstract class for literals in a horn clause.
class MaxBoundSips
Goal: prioritise (1) all-bound, then (2) max number of bound vars, then (3) left-most.
class MaxRatioSips
Goal: prioritise max ratio of bound args.
class NaiveSips
Goal: Prioritise (1) all bound, then (2) atoms with at least one bound argument, then (3) left-most.
class NameComparison
Comparator for relations.
class Negation
Negation of an atom negated atom.
class NilConstant
Defines the nil constant.
class Node
Abstract class for syntactic elements in an input program.
class NodeMapper
An abstract class for manipulating AST Nodes by substitution.
class NumericConstant
Numeric Constant.
class Pragma
Representation of a global option.
class ProfileUseSips
Goal: reorder based on the given profiling information Metric: cost(atom_R) = log(|atom_R|) * #free/#args.
class Program
The program class consists of relations, clauses and types.
class ProvenanceNegation
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
class QualifiedName
Qualified Name class defines fully/partially qualified names to identify objects in components.
class RecordInit
Defines a record initialization class.
class RecordType
Record type class for record type declarations.
class Relation
Defines a relation with a name, attributes, qualifiers, and internal representation.
class SipsMetric
Class for SIPS cost-metric functions Each subclass represents a different heuristic used for evaluating the cost of choosing an atom next in the schedule.
class StrictSips
Goal: Always choose the left-most atom.
class StringConstant
String constant class.
class SubroutineArgument
Defines the argument class for subrountines.
class SubsetType
Defines subset type class.
class Term
Defines an abstract term class used for functors and other constructors.
class TranslationUnit
Translation unit class for the translation pipeline.
class Type
An abstract base class for types.
class TypeCast
Defines a type cast class for expressions.
class UnionType
The union type class.
class UnnamedVariable
Unnamed variable class.
class UserDefinedFunctor
User-Defined functor class.
class Variable
Named variable class.
struct Visitor
The generic base type of all AstVisitors realizing the dispatching of visitor calls.
Typedefs
using RelationSet = std::set< const Relation *, NameComparison >
Relation set.
Enumerations
enum DirectiveType { DirectiveType::input, DirectiveType::output, DirectiveType::printsize, DirectiveType::limitsize }
Functions
Clause * cloneHead (const Clause *clause)
Returns a clause which contains head of the given clause.
const Relation * getAtomRelation (const Atom *atom, const Program *program)
Returns the relation referenced by the given atom.
template<typename T , typename C >
std::vector< T * > getBodyLiterals (const C &clause)
Returns literals of a particular type in the body of a clause.
std::set< const Relation * > getBodyRelations (const Clause *clause, const Program *program)
Returns the relations referenced in the body of the given clause.
size_t getClauseNum (const Program *program, const Clause *clause)
Returns the index of a clause within its relation, ignoring facts.
std::vector< Clause * > getClauses (const Program &program, const QualifiedName &relationName)
Returns a vector of clauses in the program describing the relation with the given name.
std::vector< Clause * > getClauses (const Program &program, const Relation &rel)
Returns a vector of clauses in the program describing the given relation.
std::vector< Directive * > getDirectives (const Program &program, const QualifiedName &relationName)
const Relation * getHeadRelation (const Clause *clause, const Program *program)
Returns the relation referenced by the head of the given clause.
std::vector< const RecordInit * > getRecords (const Node &root)
Obtains a list of all records referenced within the AST rooted by the given root node.
Relation * getRelation (const Program &program, const QualifiedName &name)
Returns the relation with the given name in the program.
std::vector< const Variable * > getVariables (const Node &root)
Obtains a list of all variables referenced within the AST rooted by the given root node.
bool hasClauseWithAggregatedRelation (const Relation *relation, const Relation *aggRelation, const Program *program, const Literal *&foundLiteral)
Returns whether the given relation has any clauses which contain an aggregation over of a specific relation.
bool hasClauseWithNegatedRelation (const Relation *relation, const Relation *negRelation, const Program *program, const Literal *&foundLiteral)
Returns whether the given relation has any clauses which contain a negation of a specific relation.
bool isFact (const Clause &clause)
Returns whether the given clause is a fact.
bool isProposition (const Atom *atom)
Returns whether the given atom is a propositon.
bool isRecursiveClause (const Clause &clause)
Returns whether the given clause is recursive.
bool isRule (const Clause &clause)
Returns whether the given clause is a rule.
template<typename Lambda >
detail::LambdaNodeMapper< Lambda > makeLambdaAstMapper (const Lambda &lambda)
Creates a node mapper based on a corresponding lambda expression.
void negateConstraintInPlace (Constraint &constraint)
Negate an ast constraint.
QualifiedName operator+ (const std::string &name, const QualifiedName &id)
std::ostream & operator<< (std::ostream &os, DirectiveType e)
std::string pprint (const Node &node)
void removeRelation (TranslationUnit &tu, const QualifiedName &name)
Remove relation and all its clauses from the program.
void removeRelationClauses (TranslationUnit &tu, const QualifiedName &name)
Removes the set of clauses with the given relation name.
void removeRelationIOs (TranslationUnit &tu, const QualifiedName &name)
Removes the set of IOs with the given relation name.
bool renameAtoms (Node &node, const std::map< QualifiedName, QualifiedName > &oldToNew)
Rename all atoms hat appear in a node to a given name.
Clause * reorderAtoms (const Clause *clause, const std::vector< unsigned int > &newOrder)
Reorders the atoms of a clause to be in the given order.
IntrinsicFunctors validOverloads (const analysis::TypeAnalysis &, const IntrinsicFunctor &)
Pick valid overloads for a functor, sorted by some measure of "preference".
template<typename R , typename... Ps, typename... Args>
void visitDepthFirst (const Node &root, Visitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
template<typename R , typename N >
void visitDepthFirst (const Node &root, const std::function< R(const N &)> &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type>
std::enable_if<!detail::is_ast_visitor< Lambda >::value, void >::type visitDepthFirst (const Node &root, const Lambda &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename T , typename Lambda >
void visitDepthFirst (const std::vector< T *> &list, const Lambda &fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename T , typename Lambda >
void visitDepthFirst (const VecOwn< T > &list, const Lambda &fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirstPostOrder (const Node &root, Visitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given visitor to each encountered node.
template<typename R , typename N >
void visitDepthFirstPostOrder (const Node &root, const std::function< R(const N &)> &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type>
std::enable_if<!detail::is_ast_visitor< Lambda >::value, void >::type visitDepthFirstPostOrder (const Node &root, const Lambda &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirstPreOrder (const Node &root, Visitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Typedef Documentation
RelationSet
using souffle::ast::RelationSet = typedef std::set<const Relation*, NameComparison>
Relation set.
Definition at line 174 of file Relation.h.
Enumeration Type Documentation
DirectiveType
enum souffle::ast::DirectiveType strong
Enumerator
input
output
printsize
limitsize
Definition at line 31 of file Directive.h.
 { input, output, printsize, limitsize };
Function Documentation
cloneHead()
Clause * souffle::ast::cloneHead (const Clause * clause)
Returns a clause which contains head of the given clause.
Parameters
clause the clause which head to be cloned
Returns
pointer to clause which has head cloned from given clause
Definition at line 241 of file Utils.cpp.
References souffle::clone(), souffle::ast::Clause::getExecutionPlan(), souffle::ast::Clause::getHead(), and souffle::ast::Node::getSrcLoc().
Referenced by getBodyLiterals(), souffle::ast::transform::getInlinedClause(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ast::transform::ResolveAliasesTransformer::removeTrivialEquality(), reorderAtoms(), and souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform().
{
     auto* clone = new Clause();
     clone->setSrcLoc(clause->getSrcLoc());
     clone->setHead(souffle::clone(clause->getHead()));
     if (clause->getExecutionPlan() != nullptr) {
         clone->setExecutionPlan(souffle::clone(clause->getExecutionPlan()));
     }
     return clone;
 }
getAtomRelation()
const Relation * souffle::ast::getAtomRelation (const Atom * atom, const Program * program)
Returns the relation referenced by the given atom.
Parameters
atom the atom
program the program containing the relations
Returns
relation referenced by the atom
Definition at line 122 of file Utils.cpp.
References souffle::ast::Atom::getQualifiedName(), and getRelation().
Referenced by getBodyLiterals(), getBodyRelations(), getHeadRelation(), hasClauseWithAggregatedRelation(), hasClauseWithNegatedRelation(), souffle::ast::analysis::TypeConstraintsAnalysis::iterateOverAtom(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::ExecutionPlanChecker::transform(), souffle::AstToRamTranslator::translateRecursiveRelation(), and souffle::ast::transform::TypeChecker::visitAtom().
{
     return getRelation(*program, atom->getQualifiedName());
 }
getBodyLiterals()
template<typename T , typename C > std::vector<T*> souffle::ast::getBodyLiterals (const C & clause)
Returns literals of a particular type in the body of a clause.
Parameters
the clause
Returns
vector of body literals of the specified type
Definition at line 81 of file Utils.h.
References cloneHead(), getAtomRelation(), getBodyRelations(), getClauseNum(), getClauses(), getHeadRelation(), getRelation(), hasClauseWithAggregatedRelation(), hasClauseWithNegatedRelation(), isFact(), isProposition(), isRecursiveClause(), isRule(), negateConstraintInPlace(), relation, removeRelation(), removeRelationClauses(), removeRelationIOs(), renameAtoms(), reorderAtoms(), and validOverloads().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkComplexRule().
{
     std::vector<T*> res;
     for (auto& lit : clause.getBodyLiterals()) {
         if (T* t = dynamic_cast<T*>(lit)) {
             res.push_back(t);
         }
     }
     return res;
 }
getBodyRelations()
std::set< const Relation * > souffle::ast::getBodyRelations (const Clause * clause, const Program * program)
Returns the relations referenced in the body of the given clause.
Parameters
clause the clause
program the program containing the relations
Returns
relation referenced in the clause body
Definition at line 130 of file Utils.cpp.
References souffle::ast::Atom::getArguments(), getAtomRelation(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), and visitDepthFirst().
Referenced by getBodyLiterals().
{
     std::set<const Relation*> bodyRelations;
     for (const auto& lit : clause->getBodyLiterals()) {
         visitDepthFirst(
                 *lit, [&](const Atom& atom) { bodyRelations.insert(getAtomRelation(&atom, program)); });
     }
     for (const auto& arg : clause->getHead()->getArguments()) {
         visitDepthFirst(
                 *arg, [&](const Atom& atom) { bodyRelations.insert(getAtomRelation(&atom, program)); });
     }
     return bodyRelations;
 }
getClauseNum()
size_t souffle::ast::getClauseNum (const Program * program, const Clause * clause)
Returns the index of a clause within its relation, ignoring facts.
Used in provenance as a unique ID for clauses within their relations.
Parameters
program the program
clause the clause to get the index of
Returns
the index of the clause ignoring facts; 0 for facts
Definition at line 143 of file Utils.cpp.
References souffle::fatal(), getClauses(), souffle::ast::Clause::getHead(), souffle::ast::Atom::getQualifiedName(), getRelation(), and isFact().
Referenced by getBodyLiterals(), souffle::ast::transform::ProvenanceTransformer::transformMaxHeight(), and souffle::AstToRamTranslator::translateProgram().
{
     // TODO (azreika): This number might change between the provenance transformer and the AST->RAM
     // translation. Might need a better way to assign IDs to clauses... (see PR #1288).
     const Relation* rel = getRelation(*program, clause->getHead()->getQualifiedName());
     assert(rel != nullptr && "clause relation does not exist");
     size_t clauseNum = 1;
     for (const auto* cur : getClauses(*program, *rel)) {
         bool isFact = cur->getBodyLiterals().empty();
         if (cur == clause) {
             return isFact ? 0 : clauseNum;
         }
         if (!isFact) {
             clauseNum++;
         }
     }
     fatal("clause does not exist");
 }
getClauses() [1/2]
std::vector< Clause * > souffle::ast::getClauses (const Program & program, const QualifiedName & relationName)
Returns a vector of clauses in the program describing the relation with the given name.
Parameters
program the program
name the name of the relation to search for
Returns
vector of clauses describing the relation with the given name
Definition at line 70 of file Utils.cpp.
References clauses, and souffle::ast::Program::getClauses().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkRelation(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::formNegatedLiterals(), getBodyLiterals(), getClauseNum(), getClauses(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), souffle::ast::transform::getInlinedLiteral(), hasClauseWithAggregatedRelation(), hasClauseWithNegatedRelation(), souffle::ast::transform::normaliseInlinedHeads(), souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::transform::test::TEST(), souffle::ast::test::TEST(), souffle::ast::transform::ExecutionPlanChecker::transform(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::ReplaceSingletonVariablesTransformer::transform(), souffle::ast::transform::InlineRelationsTransformer::transform(), souffle::ast::transform::NormaliseConstraintsTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::NameUnnamedVariablesTransformer::transform(), souffle::ast::transform::ResolveAliasesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast::transform::ProvenanceTransformer::transformMaxHeight(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
     std::vector<Clause*> clauses;
     for (Clause* clause : program.getClauses()) {
         if (clause->getHead()->getQualifiedName() == relationName) {
             clauses.push_back(clause);
         }
     }
     return clauses;
 }
getClauses() [2/2]
std::vector< Clause * > souffle::ast::getClauses (const Program & program, const Relation & rel)
Returns a vector of clauses in the program describing the given relation.
Parameters
program the program
rel the relation to search for
Returns
vector of clauses describing the given relation
Definition at line 80 of file Utils.cpp.
References getClauses(), and souffle::ast::Relation::getQualifiedName().
{
     return getClauses(program, rel.getQualifiedName());
 }
getDirectives()
std::vector<Directive*> souffle::ast::getDirectives (const Program & program, const QualifiedName & relationName)
Definition at line 84 of file Utils.cpp.
References directives, and souffle::ast::Program::getDirectives().
Referenced by removeRelationIOs().
{
     std::vector<Directive*> directives;
     for (Directive* dir : program.getDirectives()) {
         if (dir->getQualifiedName() == relationName) {
             directives.push_back(dir);
         }
     }
     return directives;
 }
getHeadRelation()
const Relation * souffle::ast::getHeadRelation (const Clause * clause, const Program * program)
Returns the relation referenced by the head of the given clause.
Parameters
clause the clause
program the program containing the relations
Returns
relation referenced by the clause head
Definition at line 126 of file Utils.cpp.
References getAtomRelation(), and souffle::ast::Clause::getHead().
Referenced by souffle::ast::analysis::RecursiveClausesAnalysis::computeIsRecursive(), and getBodyLiterals().
{
     return getAtomRelation(clause->getHead(), program);
 }
getRecords()
std::vector< const RecordInit * > souffle::ast::getRecords (const Node & root)
Obtains a list of all records referenced within the AST rooted by the given root node.
Parameters
root the root of the AST to be searched
Returns
a list of all records referenced within
Definition at line 63 of file Utils.cpp.
References visitDepthFirst().
{
     // simply collect the list of all records by visiting all records
     std::vector<const RecordInit*> recs;
     visitDepthFirst(root, [&](const RecordInit& rec) { recs.push_back(&rec); });
     return recs;
 }
getRelation()
Relation * souffle::ast::getRelation (const Program & program, const QualifiedName & name)
Returns the relation with the given name in the program.
Parameters
program the program
name the name of the relation to search for
Returns
the relation if it exists; nullptr otherwise
Definition at line 94 of file Utils.cpp.
References souffle::getIf(), and souffle::ast::Program::getRelations().
Referenced by souffle::ParserDriver::addRelation(), souffle::ast::transform::SemanticCheckerImpl::checkAtom(), souffle::ast::transform::SemanticCheckerImpl::checkFact(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkIO(), souffle::ast::transform::containsInlinedAtom(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::findUniqueAggregateRelationName(), souffle::ast::transform::formNegatedLiterals(), souffle::ast::analysis::AuxiliaryArityAnalysis::getArity(), getAtomRelation(), getBodyLiterals(), getClauseNum(), souffle::AstToRamTranslator::getEvaluationArity(), souffle::ast::transform::getInlinedLiteral(), souffle::SouffleProgram::getRelationName(), souffle::SouffleProgram::getRelationSize(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), removeRelation(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::analysis::IOTypeAnalysis::run(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), souffle::ast::transform::IOAttributesTransformer::setAttributeNames(), souffle::ast::transform::IOAttributesTransformer::setAttributeParams(), souffle::ast::transform::IOAttributesTransformer::setAttributeTypes(), souffle::ast::test::TEST(), souffle::ast::transform::test::TEST(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), and souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::transform().
{
     return getIf(program.getRelations(), [&](const Relation* r) { return r->getQualifiedName() == name; });
 }
getVariables()
std::vector< const Variable * > souffle::ast::getVariables (const Node & root)
Obtains a list of all variables referenced within the AST rooted by the given root node.
Parameters
root the root of the AST to be searched
Returns
a list of all variables referenced within
Definition at line 56 of file Utils.cpp.
References visitDepthFirst().
Referenced by souffle::ast::transform::GroundedTermsChecker::verify().
{
     // simply collect the list of all variables by visiting all variables
     std::vector<const Variable*> vars;
     visitDepthFirst(root, [&](const Variable& var) { vars.push_back(&var); });
     return vars;
 }
hasClauseWithAggregatedRelation()
bool souffle::ast::hasClauseWithAggregatedRelation (const Relation * relation, const Relation * aggRelation, const Program * program, const Literal *& foundLiteral)
Returns whether the given relation has any clauses which contain an aggregation over of a specific relation.
Parameters
relation the relation to search the clauses of
aggRelation the relation to search for in aggregations in clause bodies
program the program containing the relations
foundLiteral set to the literal found in an aggregation
Definition at line 177 of file Utils.cpp.
References getAtomRelation(), getClauses(), and visitDepthFirst().
Referenced by getBodyLiterals(), and souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
     for (const Clause* cl : getClauses(*program, *relation)) {
         bool hasAgg = false;
         visitDepthFirst(*cl, [&](const Aggregator& cur) {
             visitDepthFirst(cur, [&](const Atom& atom) {
                 if (aggRelation == getAtomRelation(&atom, program)) {
                     foundLiteral = &atom;
                     hasAgg = true;
                 }
             });
         });
         if (hasAgg) {
             return true;
         }
     }
     return false;
 }
hasClauseWithNegatedRelation()
bool souffle::ast::hasClauseWithNegatedRelation (const Relation * relation, const Relation * negRelation, const Program * program, const Literal *& foundLiteral)
Returns whether the given relation has any clauses which contain a negation of a specific relation.
Parameters
relation the relation to search the clauses of
negRelation the relation to search for negations of in clause bodies
program the program containing the relations
foundLiteral set to the negation literal that was found
Definition at line 164 of file Utils.cpp.
References getAtomRelation(), and getClauses().
Referenced by getBodyLiterals(), and souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl().
{
     for (const Clause* cl : getClauses(*program, *relation)) {
         for (const auto* neg : getBodyLiterals<Negation>(*cl)) {
             if (negRelation == getAtomRelation(neg->getAtom(), program)) {
                 foundLiteral = neg;
                 return true;
             }
         }
     }
     return false;
 }
isFact()
bool souffle::ast::isFact (const Clause & clause)
Returns whether the given clause is a fact.
Returns
true iff the clause is a fact
Definition at line 207 of file Utils.cpp.
References souffle::ast::Clause::getBodyLiterals(), souffle::ast::IntrinsicFunctor::getFunctionInfo(), souffle::ast::Clause::getHead(), and visitDepthFirst().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::transform::SemanticCheckerImpl::checkFact(), getBodyLiterals(), getClauseNum(), isRule(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::transform::NormaliseConstraintsTransformer::transform(), souffle::ast::transform::ProvenanceTransformer::transformMaxHeight(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and souffle::ast::transform::GroundedTermsChecker::verify().
{
     // there must be a head
     if (clause.getHead() == nullptr) {
         return false;
     }
     // there must not be any body clauses
     if (!clause.getBodyLiterals().empty()) {
         return false;
     }
     // and there are no aggregates
     bool hasAggregatesOrMultiResultFunctor = false;
     visitDepthFirst(*clause.getHead(), [&](const Argument& arg) {
         if (dynamic_cast<const Aggregator*>(&arg)) {
             hasAggregatesOrMultiResultFunctor = true;
         }
         auto func = dynamic_cast<const IntrinsicFunctor*>(&arg);
         auto info = func ? func->getFunctionInfo() : nullptr;
         if (info && info->multipleResults) {
             hasAggregatesOrMultiResultFunctor = true;
         }
     });
     return !hasAggregatesOrMultiResultFunctor;
 }
isProposition()
bool souffle::ast::isProposition (const Atom * atom)
Returns whether the given atom is a propositon.
Returns
true iff the atom has no arguments
Definition at line 237 of file Utils.cpp.
References souffle::ast::Atom::getArguments().
Referenced by getBodyLiterals().
{
     return atom->getArguments().empty();
 }
isRecursiveClause()
bool souffle::ast::isRecursiveClause (const Clause & clause)
Returns whether the given clause is recursive.
Parameters
clause the clause to check
Returns
true iff the clause is recursive
Definition at line 196 of file Utils.cpp.
References souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), souffle::ast::Atom::getQualifiedName(), and visitDepthFirst().
Referenced by getBodyLiterals(), and souffle::ast::transform::ReduceExistentialsTransformer::transform().
{
     QualifiedName relationName = clause.getHead()->getQualifiedName();
     bool recursive = false;
     visitDepthFirst(clause.getBodyLiterals(), [&](const Atom& atom) {
         if (atom.getQualifiedName() == relationName) {
             recursive = true;
         }
     });
     return recursive;
 }
isRule()
bool souffle::ast::isRule (const Clause & clause)
Returns whether the given clause is a rule.
Returns
true iff the clause is a rule
Definition at line 233 of file Utils.cpp.
References souffle::ast::Clause::getHead(), and isFact().
Referenced by getBodyLiterals(), and souffle::AstToRamTranslator::ClauseTranslator::translateClause().
{
     return (clause.getHead() != nullptr) && !isFact(clause);
 }
makeLambdaAstMapper()
template<typename Lambda > detail::LambdaNodeMapper<Lambda> souffle::ast::makeLambdaAstMapper (const Lambda & lambda)
Creates a node mapper based on a corresponding lambda expression.
Definition at line 47 of file LambdaNodeMapper.h.
References souffle::ast::detail::LambdaNodeMapper< Lambda >::lambda.
Referenced by souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries().
{
     return detail::LambdaNodeMapper<Lambda>(lambda);
 }
negateConstraintInPlace()
void souffle::ast::negateConstraintInPlace (Constraint & constraint)
Negate an ast constraint.
Parameters
constraint constraint that will be negated
Definition at line 284 of file Utils.cpp.
References souffle::fatal(), and souffle::negatedConstraintOp().
Referenced by getBodyLiterals(), souffle::ast::transform::negateLiteral(), and souffle::RuleBody::toClauseBodies().
{
     if (auto* bcstr = dynamic_cast<BooleanConstraint*>(&constraint)) {
         bcstr->set(!bcstr->isTrue());
     } else if (auto* cstr = dynamic_cast<BinaryConstraint*>(&constraint)) {
         cstr->setOperator(souffle::negatedConstraintOp(cstr->getOperator()));
     } else {
         fatal("Unknown ast-constraint type");
     }
 }
operator+()
QualifiedName souffle::ast::operator+ (const std::string & name, const QualifiedName & id) inline
Definition at line 99 of file QualifiedName.h.
References souffle::ast::QualifiedName::prepend().
{
     QualifiedName res = id;
     res.prepend(name);
     return res;
 }
operator<<()
std::ostream& souffle::ast::operator<< (std::ostream & os, DirectiveType e) inline
Definition at line 34 of file Directive.h.
References input, limitsize, output, printsize, and UNREACHABLE_BAD_CASE_ANALYSIS.
{
     switch (e) {
         case DirectiveType::input: return os << "input";
         case DirectiveType::output: return os << "output";
         case DirectiveType::printsize: return os << "printsize";
         case DirectiveType::limitsize: return os << "limitsize";
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 }
pprint()
std::string souffle::ast::pprint (const Node & node)
Definition at line 52 of file Utils.cpp.
References souffle::toString().
Referenced by souffle::ast::transform::DebugReporter::generateDebugReport(), and souffle::ast::transform::DebugReporter::transform().
{
     return toString(node);
 }
removeRelation()
void souffle::ast::removeRelation (TranslationUnit & tu, const QualifiedName & name)
Remove relation and all its clauses from the program.
Parameters
tu the translation unit
name the name of the relation to delete
Definition at line 98 of file Utils.cpp.
References souffle::ast::TranslationUnit::getProgram(), getRelation(), removeRelationClauses(), souffle::ast::Program::removeRelationDecl(), and removeRelationIOs().
Referenced by getBodyLiterals(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), and souffle::ast::transform::RemoveRedundantRelationsTransformer::transform().
{
     Program& program = tu.getProgram();
     if (getRelation(program, name) != nullptr) {
         removeRelationClauses(tu, name);
         removeRelationIOs(tu, name);
         program.removeRelationDecl(name);
     }
 }
removeRelationClauses()
void souffle::ast::removeRelationClauses (TranslationUnit & tu, const QualifiedName & name)
Removes the set of clauses with the given relation name.
Parameters
tu the translation unit
name the name of the relation to search for
Definition at line 107 of file Utils.cpp.
References souffle::ast::TranslationUnit::getAnalysis(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::Program::removeClause().
Referenced by getBodyLiterals(), and removeRelation().
{
     Program& program = tu.getProgram();
     const auto& relDetail = *tu.getAnalysis<analysis::RelationDetailCacheAnalysis>();
     for (const auto* clause : relDetail.getClauses(name)) {
         program.removeClause(clause);
     }
 }
removeRelationIOs()
void souffle::ast::removeRelationIOs (TranslationUnit & tu, const QualifiedName & name)
Removes the set of IOs with the given relation name.
Parameters
tu the translation unit
name the name of the relation to search for
Definition at line 115 of file Utils.cpp.
References getDirectives(), souffle::ast::TranslationUnit::getProgram(), and souffle::ast::Program::removeDirective().
Referenced by getBodyLiterals(), and removeRelation().
{
     Program& program = tu.getProgram();
     for (const auto* directive : getDirectives(program, name)) {
         program.removeDirective(directive);
     }
 }
renameAtoms()
bool souffle::ast::renameAtoms (Node & node, const std::map< QualifiedName, QualifiedName > & oldToNew)
Rename all atoms hat appear in a node to a given name.
Parameters
node node to alter the children of
oldToNew map from old atom names to new atom names
Returns
true if the node was changed
Definition at line 329 of file Utils.cpp.
References souffle::ast::Node::apply(), souffle::clone(), and souffle::contains().
Referenced by souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), getBodyLiterals(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), and souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform().
{
     struct rename_atoms : public NodeMapper {
         mutable bool changed{false};
         const std::map<QualifiedName, QualifiedName>& oldToNew;
         rename_atoms(const std::map<QualifiedName, QualifiedName>& oldToNew) : oldToNew(oldToNew) {}
         Own<Node> operator()(Own<Node> node) const override {
             node->apply(*this);
             if (auto* atom = dynamic_cast<Atom*>(node.get())) {
                 if (contains(oldToNew, atom->getQualifiedName())) {
                     auto renamedAtom = souffle::clone(atom);
                     renamedAtom->setQualifiedName(oldToNew.at(atom->getQualifiedName()));
                     changed = true;
                     return renamedAtom;
                 }
             }
             return node;
         }
     };
     rename_atoms update(oldToNew);
     node.apply(update);
     return update.changed;
 }
reorderAtoms()
Clause * souffle::ast::reorderAtoms (const Clause * clause, const std::vector< unsigned int > & newOrder)
Reorders the atoms of a clause to be in the given order.
Remaining body literals remain in the same order.
E.g. if atoms are [a,b,c] and given order is [1,2,0], then the final atom order will be [b,c,a].
Parameters
clause clause to reorder atoms in
newOrder new order of atoms; atoms[i] = atoms[newOrder[i]]
Definition at line 251 of file Utils.cpp.
References souffle::ast::Clause::addToBody(), souffle::clone(), cloneHead(), souffle::ast::Clause::getBodyLiterals(), and i.
Referenced by getBodyLiterals(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), souffle::ast::transform::ReorderLiteralsTransformer::reorderClauseWithSips(), and souffle::ast::test::TEST().
{
     // Find all atom positions
     std::vector<unsigned int> atomPositions;
     std::vector<Literal*> bodyLiterals = clause->getBodyLiterals();
     for (unsigned int i = 0; i < bodyLiterals.size(); i++) {
         if (isA<Atom>(bodyLiterals[i])) {
             atomPositions.push_back(i);
         }
     }
     // Validate given order
     assert(newOrder.size() == atomPositions.size());
     std::vector<unsigned int> nopOrder;
     for (unsigned int i = 0; i < atomPositions.size(); i++) {
         nopOrder.push_back(i);
     }
     assert(std::is_permutation(nopOrder.begin(), nopOrder.end(), newOrder.begin()));
     // Create a new clause with the given atom order, leaving the rest unchanged
     Clause* newClause = cloneHead(clause);
     unsigned int currentAtom = 0;
     for (unsigned int currentLiteral = 0; currentLiteral < bodyLiterals.size(); currentLiteral++) {
         Literal* literalToAdd = bodyLiterals[currentLiteral];
         if (isA<Atom>(literalToAdd)) {
             // Atoms should be reordered
             literalToAdd = bodyLiterals[atomPositions[newOrder[currentAtom++]]];
         }
         newClause->addToBody(souffle::clone(literalToAdd));
     }
     return newClause;
 }
validOverloads()
IntrinsicFunctors souffle::ast::validOverloads (const analysis::TypeAnalysis & typing, const ast::IntrinsicFunctor & func)
Pick valid overloads for a functor, sorted by some measure of "preference".
Definition at line 294 of file Utils.cpp.
References b, souffle::contains(), souffle::filterNot(), souffle::Float, souffle::functorBuiltIn(), souffle::ast::Term::getArguments(), souffle::ast::IntrinsicFunctor::getFunction(), souffle::ast::analysis::getTypeAttribute(), souffle::ast::analysis::TypeAnalysis::getTypes(), i, souffle::map(), souffle::IntrinsicFunctorInfo::params, souffle::Record, souffle::IntrinsicFunctorInfo::result, souffle::Signed, souffle::Symbol, types, souffle::Unsigned, and souffle::IntrinsicFunctorInfo::variadic.
Referenced by getBodyLiterals(), souffle::ast::transform::PolymorphicObjectsTransformer::transform(), and souffle::ast::transform::TypeChecker::visitIntrinsicFunctor().
{
     auto typeAttrs = [&](const Argument* arg) -> std::set<TypeAttribute> {
         auto&& types = typing.getTypes(arg);
         if (types.isAll())
             return {TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float,
                     TypeAttribute::Symbol, TypeAttribute::Record};
         std::set<TypeAttribute> tyAttrs;
         for (auto&& ty : types)
             tyAttrs.insert(getTypeAttribute(ty));
         return tyAttrs;
     };
     auto retTys = typeAttrs(&func);
     auto argTys = map(func.getArguments(), typeAttrs);
     auto candidates =
             filterNot(functorBuiltIn(func.getFunction()), [&](const IntrinsicFunctorInfo& x) -> bool {
                 if (!x.variadic && argTys.size() != x.params.size()) return true;  // arity mismatch?
                 for (size_t i = 0; i < argTys.size(); ++i)
                     if (!contains(argTys[i], x.params[x.variadic ? 0 : i])) return true;
                 return !contains(retTys, x.result);
             });
     std::sort(candidates.begin(), candidates.end(),
             [&](const IntrinsicFunctorInfo& a, const IntrinsicFunctorInfo& b) {
                 if (a.result != b.result) return a.result < b.result;
                 if (a.variadic != b.variadic) return a.variadic < b.variadic;
                 return std::lexicographical_compare(
                         a.params.begin(), a.params.end(), b.params.begin(), b.params.end());
             });
     return candidates;
 }
visitDepthFirst() [1/5]
template<typename R , typename... Ps, typename... Args> void souffle::ast::visitDepthFirst (const Node & root, Visitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the AST to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 267 of file Visitor.h.
References visitDepthFirstPreOrder().
Referenced by souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::addRelevantVariables(), souffle::ast::analysis::ConstraintAnalysis< TypeVar >::analyse(), souffle::ast::transform::SemanticCheckerImpl::checkAggregator(), souffle::ast::transform::SemanticCheckerImpl::checkBranchInits(), souffle::ast::transform::SemanticCheckerImpl::checkClause(), souffle::ast::transform::SemanticCheckerImpl::checkComplexRule(), souffle::ast::transform::SemanticCheckerImpl::checkInlining(), souffle::ast::transform::SemanticCheckerImpl::checkLiteral(), souffle::ast::transform::SemanticCheckerImpl::checkTypesDeclarations(), souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem(), souffle::ast::transform::containsInlinedAtom(), souffle::ast::transform::FoldAnonymousRecords::containsValidRecordConstraint(), souffle::ast::analysis::createAnnotatedClause(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::createMagicClause(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ast::LeastFreeVarsSips::evaluateCosts(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::extractIDB(), souffle::NodeGenerator::findAllViews(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::findUniqueVariableName(), souffle::ast::BindingStore::generateBindingDependencies(), souffle::synthesiser::Synthesiser::generateCode(), souffle::NodeGenerator::generateTree(), souffle::ast::transform::IOAttributesTransformer::getAlgebraicDataTypes(), souffle::ast::transform::MagicSetTransformer::MagicSetCoreTransformer::getBindingEqualityConstraints(), getBodyRelations(), souffle::ast::transform::MagicSetTransformer::getIgnoredRelations(), getRecords(), souffle::synthesiser::Synthesiser::getReferencedRelations(), getVariables(), hasClauseWithAggregatedRelation(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::ast::transform::SemanticCheckerImpl::isDependent(), isFact(), isRecursiveClause(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::isSingleValued(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::normaliseArguments(), souffle::ast::BindingStore::processEqualityBindings(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::querifyOutputRelations(), souffle::ast::transform::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ast::transform::ResolveAliasesTransformer::resolveAliases(), souffle::ast::analysis::SumTypeBranchesAnalysis::run(), souffle::ast::analysis::IOTypeAnalysis::run(), souffle::ast::analysis::PrecedenceGraphAnalysis::run(), souffle::ast::analysis::RecursiveClausesAnalysis::run(), souffle::ast::analysis::ComponentLookupAnalysis::run(), souffle::ast::transform::PragmaChecker::transform(), souffle::ast::transform::UniqueAggregationVariablesTransformer::transform(), souffle::ast::transform::RemoveBooleanConstraintsTransformer::transform(), souffle::ast::transform::ReplaceSingletonVariablesTransformer::transform(), souffle::ast::transform::ReduceExistentialsTransformer::transform(), souffle::ast::transform::MaterializeSingletonAggregationTransformer::transform(), souffle::ast::transform::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::ast::transform::PartitionBodyLiteralsTransformer::transform(), souffle::ast::transform::ResolveAliasesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::AstToRamTranslator::translateProgram(), souffle::ast::transform::usesInvalidWitness(), souffle::ast::transform::GroundedTermsChecker::verify(), visitDepthFirst(), and souffle::NodeGenerator::visitQuery().
{
     visitDepthFirstPreOrder(root, visitor, args...);
 }
visitDepthFirst() [2/5]
template<typename R , typename N > void souffle::ast::visitDepthFirst (const Node & root, const std::function< R(const N &)> & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 321 of file Visitor.h.
References souffle::ast::detail::makeLambdaVisitor().
{
     auto visitor = detail::makeLambdaVisitor(fun);
     visitDepthFirst<void>(root, visitor);
 }
visitDepthFirst() [3/5]
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type> std::enable_if<!detail::is_ast_visitor<Lambda>::value, void>::type souffle::ast::visitDepthFirst (const Node & root, const Lambda & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 337 of file Visitor.h.
References visitDepthFirst().
{
     visitDepthFirst(root, std::function<R(const N&)>(fun));
 }
visitDepthFirst() [4/5]
template<typename T , typename Lambda > void souffle::ast::visitDepthFirst (const std::vector< T *> & list, const Lambda & fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
list the list of roots of the ASTs to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 352 of file Visitor.h.
References visitDepthFirst().
{
     for (const auto& cur : list) {
         visitDepthFirst(*cur, fun);
     }
 }
visitDepthFirst() [5/5]
template<typename T , typename Lambda > void souffle::ast::visitDepthFirst (const VecOwn< T > & list, const Lambda & fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
list the list of roots of the ASTs to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 368 of file Visitor.h.
References visitDepthFirst().
{
     for (const auto& cur : list) {
         visitDepthFirst(*cur, fun);
     }
 }
visitDepthFirstPostOrder() [1/3]
template<typename R , typename... Ps, typename... Args> void souffle::ast::visitDepthFirstPostOrder (const Node & root, Visitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the AST to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 248 of file Visitor.h.
References souffle::ast::Node::getChildNodes().
Referenced by souffle::AstToRamTranslator::ClauseTranslator::createValueIndex(), souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ast::transform::UniqueAggregationVariablesTransformer::transform(), and visitDepthFirstPostOrder().
{
     for (const Node* cur : root.getChildNodes()) {
         if (cur != nullptr) {
             visitDepthFirstPostOrder(*cur, visitor, args...);
         }
     }
     visitor(root, args...);
 }
visitDepthFirstPostOrder() [2/3]
template<typename R , typename N > void souffle::ast::visitDepthFirstPostOrder (const Node & root, const std::function< R(const N &)> & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 384 of file Visitor.h.
References souffle::ast::detail::makeLambdaVisitor().
{
     auto visitor = detail::makeLambdaVisitor(fun);
     visitDepthFirstPostOrder<void>(root, visitor);
 }
visitDepthFirstPostOrder() [3/3]
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type> std::enable_if<!detail::is_ast_visitor<Lambda>::value, void>::type souffle::ast::visitDepthFirstPostOrder (const Node & root, const Lambda & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 400 of file Visitor.h.
References visitDepthFirstPostOrder().
{
     visitDepthFirstPostOrder(root, std::function<R(const N&)>(fun));
 }
visitDepthFirstPreOrder()
template<typename R , typename... Ps, typename... Args> void souffle::ast::visitDepthFirstPreOrder (const Node & root, Visitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the AST to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 229 of file Visitor.h.
References souffle::ast::Node::getChildNodes().
Referenced by souffle::ast::analysis::ConstraintAnalysis< TypeVar >::collectConstraints(), souffle::ast::analysis::TypeConstraintsAnalysis::collectConstraints(), souffle::ast::transform::TypeChecker::run(), and visitDepthFirst().
{
     visitor(root, args...);
     for (const Node* cur : root.getChildNodes()) {
         if (cur != nullptr) {
             visitDepthFirstPreOrder(*cur, visitor, args...);
         }
     }
 }