souffle: souffle::ast::transform Namespace Reference
souffle::ast::transform Namespace Reference
Namespaces
test
Data Structures
class AddNullariesToAtomlessAggregatesTransformer
Transformation pass to add artificial nullary atom (+Tautology()) to aggregate bodies that have no atoms.
class ADTtoRecordsTransformer
class ComponentChecker
class ComponentInstantiationTransformer
class ConditionalTransformer
Transformer that executes a sub-transformer iff a condition holds.
class DebugReporter
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
class ExecutionPlanChecker
class FixpointTransformer
Transformer that repeatedly executes a sub-transformer until no changes are made.
class FoldAnonymousRecords
Transformation pass that removes (binary) constraints on the anonymous records.
class GroundedTermsChecker
class InlineRelationsTransformer
Transformation pass to inline marked relations.
class IOAttributesTransformer
Transformation pass to set attribute names and types in IO operations.
class IODefaultsTransformer
Transformation pass to set defaults for IO operations.
class MagicSetTransformer
Magic Set Transformation.
class MaterializeAggregationQueriesTransformer
Transformation pass to create artificial relations for bodies of aggregation functions consisting of more than a single atom.
class MaterializeSingletonAggregationTransformer
Replaces literals containing single-valued aggregates with a synthesised relation.
class MetaTransformer
Transformer that coordinates other sub-transformations.
class MinimiseProgramTransformer
Transformation pass to remove equivalent rules.
class NameUnnamedVariablesTransformer
Transformation pass to replace unnamed variables with singletons.
class NormaliseConstraintsTransformer
Transformation pass to normalise constraints.
class NullableVector
class NullTransformer
Transformer that does absolutely nothing.
class PartitionBodyLiteralsTransformer
Transformation pass to move literals into new clauses if they are independent of remaining literals.
class PipelineTransformer
Transformer that holds an arbitrary number of sub-transformations.
class PolymorphicObjectsTransformer
Transformation pass to determine instances of polymorphic object objects = Functors (plus, minus...) ∪ binary constraints (>, ≥ ...) ∪ aggregation ∪ numeric constants.
class PragmaChecker
class ProvenanceTransformer
Transformation pass to add provenance information.
class ReduceExistentialsTransformer
Transformation pass to reduce unnecessary computation for relations that only appear in the form A(_,...,_).
class RemoveBooleanConstraintsTransformer
Transformation pass to remove constant boolean constraints Should be called after any transformation that may generate boolean constraints.
class RemoveEmptyRelationsTransformer
Transformation pass to remove all empty relations and rules that use empty relations.
class RemoveRedundantRelationsTransformer
Transformation pass to remove relations which are redundant (do not contribute to output).
class RemoveRedundantSumsTransformer
Transformation pass to remove expressions of the form sum k : { ...
class RemoveRelationCopiesTransformer
Transformation pass to replaces copy of relations by their origin.
class RemoveTypecastsTransformer
Transformation to remove typecasts.
class ReorderLiteralsTransformer
Transformation pass to reorder body literals.
class ReplaceSingletonVariablesTransformer
Transformation pass to replace singleton variables with unnamed variables.
class ResolveAliasesTransformer
Transformation pass to eliminate grounded aliases.
class ResolveAnonymousRecordAliasesTransformer
Transformer resolving aliases for anonymous records.
class SemanticChecker
struct SemanticCheckerImpl
class Transformer
class TypeChecker
class UniqueAggregationVariablesTransformer
Transformation pass to rename aggregation variables to make them unique.
class UserDefinedFunctorsTransformer
Transformation that passes the type information from user functors declaration to functors instances.
class WhileTransformer
Transformer that repeatedly executes a sub-transformer while a condition is met.
Typedefs
typedef MagicSetTransformer::AdornDatabaseTransformer AdornDatabaseTransformer
typedef MagicSetTransformer::LabelDatabaseTransformer LabelDatabaseTransformer
typedef MagicSetTransformer::MagicSetCoreTransformer MagicSetCoreTransformer
typedef MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer NegativeLabellingTransformer
typedef MagicSetTransformer::NormaliseDatabaseTransformer NormaliseDatabaseTransformer
typedef MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer PositiveLabellingTransformer
Functions
Argument * combineAggregators (std::vector< Aggregator *> aggrs, std::string fun)
std::vector< std::vector< Literal * > > combineNegatedLiterals (std::vector< std::vector< Literal *>> litGroups)
Return the negated version of a disjunction of conjunctions.
bool containsInlinedAtom (const Program &program, const Clause &clause)
Checks if a given clause contains an atom that should be inlined.
std::vector< QualifiedName > findInlineCycle (const PrecedenceGraphAnalysis &precedenceGraph, std::map< const Relation *, const Relation *> &origins, const Relation *current, RelationSet &unvisited, RelationSet &visiting, RelationSet &visited)
Find a cycle consisting entirely of inlined relations.
std::vector< std::vector< Literal * > > formNegatedLiterals (Program &program, Atom *atom)
Forms the bodies that will replace the negation of a given inlined atom.
NullableVector< Argument * > getInlinedArgument (Program &program, const Argument *arg)
Returns a vector of arguments that should replace the given argument after one step of inlining.
NullableVector< Atom * > getInlinedAtom (Program &program, Atom &atom)
Returns a vector of atoms that should replace the given atom after one step of inlining.
std::vector< Clause * > getInlinedClause (Program &program, const Clause &clause)
Returns a list of clauses that should replace the given clause after one step of inlining.
NullableVector< std::vector< Literal * > > getInlinedLiteral (Program &program, Literal *lit)
Tries to perform a single step of inlining on the given literal.
std::pair< NullableVector< Literal * >, std::vector< BinaryConstraint * > > inlineBodyLiterals (Atom *atom, Clause *atomInlineClause)
Inlines the given atom based on a given clause.
Own< Relation > makeInfoRelation (Clause &originalClause, size_t originalClauseNum, TranslationUnit &translationUnit)
QualifiedName makeRelationName (const QualifiedName &orig, const std::string &type, int num=-1)
Helper functions.
void nameInlinedUnderscores (Program &program)
Removes all underscores in all atoms of inlined relations.
Literal * negateLiteral (Literal *lit)
Returns the negated version of a given literal.
void normaliseInlinedHeads (Program &program)
Replace constants in the head of inlined clauses with (constrained) variables.
bool reduceSubstitution (std::vector< std::pair< Argument *, Argument *>> &sub)
Reduces a vector of substitutions.
void renameVariables (Argument *arg)
Renames all variables in a given argument uniquely.
void transformEqrelRelation (Program &program, Relation &rel)
Transform eqrel relations to explicitly define equivalence relations.
NullableVector< std::pair< Argument *, Argument * > > unifyAtoms (Atom *first, Atom *second)
Returns the nullable vector of substitutions needed to unify the two given atoms.
static const std::vector< SrcLocation > usesInvalidWitness (TranslationUnit &tu, const std::vector< Literal *> &literals, const std::set< Own< Argument >> &groundedArguments)
Typedef Documentation
AdornDatabaseTransformer
typedef MagicSetTransformer::AdornDatabaseTransformer souffle::ast::transform::AdornDatabaseTransformer
Definition at line 54 of file MagicSet.cpp.
LabelDatabaseTransformer
typedef MagicSetTransformer::LabelDatabaseTransformer souffle::ast::transform::LabelDatabaseTransformer
Definition at line 53 of file MagicSet.cpp.
MagicSetCoreTransformer
typedef MagicSetTransformer::MagicSetCoreTransformer souffle::ast::transform::MagicSetCoreTransformer
Definition at line 55 of file MagicSet.cpp.
NegativeLabellingTransformer
typedef MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer souffle::ast::transform::NegativeLabellingTransformer
Definition at line 58 of file MagicSet.cpp.
NormaliseDatabaseTransformer
typedef MagicSetTransformer::NormaliseDatabaseTransformer souffle::ast::transform::NormaliseDatabaseTransformer
Definition at line 52 of file MagicSet.cpp.
PositiveLabellingTransformer
typedef MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer souffle::ast::transform::PositiveLabellingTransformer
Definition at line 60 of file MagicSet.cpp.
Function Documentation
combineAggregators()
Argument* souffle::ast::transform::combineAggregators (std::vector< Aggregator *> aggrs, std::string fun)
Definition at line 512 of file InlineRelations.cpp.
References renameVariables(), and rhs.
Referenced by getInlinedArgument().
{
     // Due to variable scoping issues with aggregators, we rename all variables uniquely in the
     // added aggregator
     renameVariables(aggrs[0]);
     if (aggrs.size() == 1) {
         return aggrs[0];
     }
     Argument* rhs = combineAggregators(std::vector<Aggregator*>(aggrs.begin() + 1, aggrs.end()), fun);
     Argument* result = new IntrinsicFunctor(std::move(fun), Own<Argument>(aggrs[0]), Own<Argument>(rhs));
     return result;
 }
combineNegatedLiterals()
std::vector<std::vector<Literal*> > souffle::ast::transform::combineNegatedLiterals (std::vector< std::vector< Literal *>> litGroups)
Return the negated version of a disjunction of conjunctions.
E.g. (a1(x) ^ a2(x) ^ ...) v (b1(x) ^ b2(x) ^ ...) –into-> (!a1(x) ^ !b1(x)) v (!a2(x) ^ !b2(x)) v ...
Definition at line 376 of file InlineRelations.cpp.
References i, and negateLiteral().
Referenced by formNegatedLiterals().
{
     std::vector<std::vector<Literal*>> negation;
     // Corner case: !() = ()
     if (litGroups.empty()) {
         return negation;
     }
     std::vector<Literal*> litGroup = litGroups[0];
     if (litGroups.size() == 1) {
         // !(a1 ^ a2 ^ a3 ^ ...) --into-> !a1 v !a2 v !a3 v ...
         for (auto& i : litGroup) {
             std::vector<Literal*> newVec;
             newVec.push_back(negateLiteral(i));
             negation.push_back(newVec);
         }
         // Done!
         return negation;
     }
     // Produce the negated versions of all disjunctions ignoring the first recursively
     std::vector<std::vector<Literal*>> combinedRHS = combineNegatedLiterals(
             std::vector<std::vector<Literal*>>(litGroups.begin() + 1, litGroups.end()));
     // We now just need to add the negation of a single literal from the untouched LHS
     // to every single conjunction on the RHS to finalise creating every possible combination
     for (Literal* lhsLit : litGroup) {
         for (std::vector<Literal*> rhsVec : combinedRHS) {
             std::vector<Literal*> newVec;
             newVec.push_back(negateLiteral(lhsLit));
             for (Literal* lit : rhsVec) {
                 newVec.push_back(lit->clone());
             }
             negation.push_back(newVec);
         }
     }
     for (std::vector<Literal*> rhsVec : combinedRHS) {
         for (Literal* lit : rhsVec) {
             delete lit;
         }
     }
     return negation;
 }
containsInlinedAtom()
bool souffle::ast::transform::containsInlinedAtom (const Program & program, const Clause & clause)
Checks if a given clause contains an atom that should be inlined.
Definition at line 193 of file InlineRelations.cpp.
References souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::Relation::hasQualifier(), souffle::INLINE, and souffle::ast::visitDepthFirst().
Referenced by souffle::ast::transform::InlineRelationsTransformer::transform().
{
     bool foundInlinedAtom = false;
     visitDepthFirst(clause, [&](const Atom& atom) {
         Relation* rel = getRelation(program, atom.getQualifiedName());
         if (rel->hasQualifier(RelationQualifier::INLINE)) {
             foundInlinedAtom = true;
         }
     });
     return foundInlinedAtom;
 }
findInlineCycle()
std::vector<QualifiedName> souffle::ast::transform::findInlineCycle (const PrecedenceGraphAnalysis & precedenceGraph, std::map< const Relation *, const Relation *> & origins, const Relation * current, RelationSet & unvisited, RelationSet & visiting, RelationSet & visited)
Find a cycle consisting entirely of inlined relations.
If no cycle exists, then an empty vector is returned.
Definition at line 973 of file SemanticChecker.cpp.
References souffle::ast::Relation::getQualifiedName(), souffle::ast::analysis::PrecedenceGraphAnalysis::graph(), and souffle::INLINE.
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkInlining().
{
     std::vector<QualifiedName> result;
     if (current == nullptr) {
         // Not looking at any nodes at the moment, so choose any node from the unvisited list
         if (unvisited.empty()) {
             // Nothing left to visit - so no cycles exist!
             return result;
         }
         // Choose any element from the unvisited set
         current = *unvisited.begin();
         origins[current] = nullptr;
         // Move it to "currently visiting"
         unvisited.erase(current);
         visiting.insert(current);
         // Check if we can find a cycle beginning from this node
         std::vector<QualifiedName> subresult =
                 findInlineCycle(precedenceGraph, origins, current, unvisited, visiting, visited);
         if (subresult.empty()) {
             // No cycle found, try again from another node
             return findInlineCycle(precedenceGraph, origins, nullptr, unvisited, visiting, visited);
         } else {
             // Cycle found! Return it
             return subresult;
         }
     }
     // Check neighbours
     const RelationSet& successors = precedenceGraph.graph().successors(current);
     for (const Relation* successor : successors) {
         // Only care about inlined neighbours in the graph
         if (successor->hasQualifier(RelationQualifier::INLINE)) {
             if (visited.find(successor) != visited.end()) {
                 // The neighbour has already been visited, so move on
                 continue;
             }
             if (visiting.find(successor) != visiting.end()) {
                 // Found a cycle!!
                 // Construct the cycle in reverse
                 while (current != nullptr) {
                     result.push_back(current->getQualifiedName());
                     current = origins[current];
                 }
                 return result;
             }
             // Node has not been visited yet
             origins[successor] = current;
             // Move from unvisited to visiting
             unvisited.erase(successor);
             visiting.insert(successor);
             // Visit recursively and check if a cycle is formed
             std::vector<QualifiedName> subgraphCycle =
                     findInlineCycle(precedenceGraph, origins, successor, unvisited, visiting, visited);
             if (!subgraphCycle.empty()) {
                 // Found a cycle!
                 return subgraphCycle;
             }
         }
     }
     // Visited all neighbours with no cycle found, so done visiting this node.
     visiting.erase(current);
     visited.insert(current);
     return result;
 }
formNegatedLiterals()
std::vector<std::vector<Literal*> > souffle::ast::transform::formNegatedLiterals (Program & program, Atom * atom)
Forms the bodies that will replace the negation of a given inlined atom.
E.g. a(x) <- (a11(x), a12(x)) ; (a21(x), a22(x)) => !a(x) <- (!a11(x), !a21(x)) ; (!a11(x), !a22(x)) ; ... Essentially, produce every combination (m_1 ^ m_2 ^ ...) where m_i is the negation of a literal in the ith rule of a.
Definition at line 431 of file InlineRelations.cpp.
References combineNegatedLiterals(), souffle::ast::getClauses(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::transform::NullableVector< T >::getVector(), inlineBodyLiterals(), and souffle::ast::transform::NullableVector< T >::isValid().
Referenced by getInlinedLiteral().
{
     // Constraints added to unify atoms should not be negated and should be added to
     // all the final rule combinations produced, and so should be stored separately.
     std::vector<std::vector<Literal*>> addedBodyLiterals;
     std::vector<std::vector<BinaryConstraint*>> addedConstraints;
     // Go through every possible clause associated with the given atom
     for (Clause* inClause : getClauses(program, *getRelation(program, atom->getQualifiedName()))) {
         // Form the replacement clause by inlining based on the current clause
         std::pair<NullableVector<Literal*>, std::vector<BinaryConstraint*>> inlineResult =
                 inlineBodyLiterals(atom, inClause);
         NullableVector<Literal*> replacementBodyLiterals = inlineResult.first;
         std::vector<BinaryConstraint*> currConstraints = inlineResult.second;
         if (!replacementBodyLiterals.isValid()) {
             // Failed to unify, so just move on
             continue;
         }
         addedBodyLiterals.push_back(replacementBodyLiterals.getVector());
         addedConstraints.push_back(currConstraints);
     }
     // We now have a list of bodies needed to inline the given atom.
     // We want to inline the negated version, however, which is done using De Morgan's Law.
     std::vector<std::vector<Literal*>> negatedAddedBodyLiterals = combineNegatedLiterals(addedBodyLiterals);
     // Add in the necessary constraints to all the body literals
     for (auto& negatedAddedBodyLiteral : negatedAddedBodyLiterals) {
         for (std::vector<BinaryConstraint*> constraintGroup : addedConstraints) {
             for (BinaryConstraint* constraint : constraintGroup) {
                 negatedAddedBodyLiteral.push_back(constraint->clone());
             }
         }
     }
     // Free up the old body literals and constraints
     for (std::vector<Literal*> litGroup : addedBodyLiterals) {
         for (Literal* lit : litGroup) {
             delete lit;
         }
     }
     for (std::vector<BinaryConstraint*> consGroup : addedConstraints) {
         for (Constraint* cons : consGroup) {
             delete cons;
         }
     }
     return negatedAddedBodyLiterals;
 }
getInlinedArgument()
NullableVector<Argument*> souffle::ast::transform::getInlinedArgument (Program & program, const Argument * arg)
Returns a vector of arguments that should replace the given argument after one step of inlining.
Note: This function is currently generalised to perform any required inlining within aggregators as well, making it simple to extend to this later on if desired (and the semantic check is removed).
Definition at line 534 of file InlineRelations.cpp.
References souffle::clone(), combineAggregators(), souffle::COUNT, souffle::fatal(), souffle::FMAX, souffle::FMIN, souffle::FSUM, getInlinedLiteral(), souffle::ast::transform::NullableVector< T >::getVector(), i, souffle::ast::transform::NullableVector< T >::isValid(), j, souffle::MAX, souffle::MEAN, souffle::MIN, souffle::ast::Aggregator::setBody(), souffle::ast::Node::setSrcLoc(), souffle::SUM, souffle::UMAX, souffle::UMIN, UNREACHABLE_BAD_CASE_ANALYSIS, and souffle::USUM.
Referenced by getInlinedAtom(), and getInlinedLiteral().
{
     bool changed = false;
     std::vector<Argument*> versions;
     // Each argument has to be handled differently - essentially, want to go down to
     // nested aggregators, and inline their bodies if needed.
     if (const auto* aggr = dynamic_cast<const Aggregator*>(arg)) {
         // First try inlining the target expression if necessary
         if (aggr->getTargetExpression() != nullptr) {
             NullableVector<Argument*> argumentVersions =
                     getInlinedArgument(program, aggr->getTargetExpression());
             if (argumentVersions.isValid()) {
                 // An element in the target expression can be inlined!
                 changed = true;
                 // Create a new aggregator per version of the target expression
                 for (Argument* newArg : argumentVersions.getVector()) {
                     auto* newAggr = new Aggregator(aggr->getOperator(), Own<Argument>(newArg));
                     VecOwn<Literal> newBody;
                     for (Literal* lit : aggr->getBodyLiterals()) {
                         newBody.push_back(souffle::clone(lit));
                     }
                     newAggr->setBody(std::move(newBody));
                     versions.push_back(newAggr);
                 }
             }
         }
         // Try inlining body arguments if the target expression has not been changed.
         // (At this point we only handle one step of inlining at a time)
         if (!changed) {
             std::vector<Literal*> bodyLiterals = aggr->getBodyLiterals();
             for (size_t i = 0; i < bodyLiterals.size(); i++) {
                 Literal* currLit = bodyLiterals[i];
                 NullableVector<std::vector<Literal*>> literalVersions = getInlinedLiteral(program, currLit);
                 if (literalVersions.isValid()) {
                     // Literal can be inlined!
                     changed = true;
                     AggregateOp op = aggr->getOperator();
                     // Create an aggregator (with the same operation) for each possible body
                     std::vector<Aggregator*> aggrVersions;
                     for (std::vector<Literal*> inlineVersions : literalVersions.getVector()) {
                         Own<Argument> target;
                         if (aggr->getTargetExpression() != nullptr) {
                             target = souffle::clone(aggr->getTargetExpression());
                         }
                         auto* newAggr = new Aggregator(aggr->getOperator(), std::move(target));
                         VecOwn<Literal> newBody;
                         // Add in everything except the current literal being replaced
                         for (size_t j = 0; j < bodyLiterals.size(); j++) {
                             if (i != j) {
                                 newBody.push_back(souffle::clone(bodyLiterals[j]));
                             }
                         }
                         // Add in everything new that replaces that literal
                         for (Literal* addedLit : inlineVersions) {
                             newBody.push_back(Own<Literal>(addedLit));
                         }
                         newAggr->setBody(std::move(newBody));
                         aggrVersions.push_back(newAggr);
                     }
                     // Utility lambda: get functor used to tie aggregators together.
                     auto aggregateToFunctor = [](AggregateOp op) {
                         switch (op) {
                             case AggregateOp::MIN:
                             case AggregateOp::FMIN:
                             case AggregateOp::UMIN: return "min";
                             case AggregateOp::MAX:
                             case AggregateOp::FMAX:
                             case AggregateOp::UMAX: return "max";
                             case AggregateOp::SUM:
                             case AggregateOp::FSUM:
                             case AggregateOp::USUM:
                             case AggregateOp::COUNT: return "+";
                             case AggregateOp::MEAN: fatal("no translation");
                         }
                         UNREACHABLE_BAD_CASE_ANALYSIS
                     };
                     // Create the actual overall aggregator that ties the replacement aggregators together.
                     // example: min x : { a(x) }. <=> min ( min x : { a1(x) }, min x : { a2(x) }, ... )
                     if (op != AggregateOp::MEAN) {
                         versions.push_back(combineAggregators(aggrVersions, aggregateToFunctor(op)));
                     }
                 }
                 // Only perform one stage of inlining at a time.
                 if (changed) {
                     break;
                 }
             }
         }
     } else if (const auto* functor = dynamic_cast<const Functor*>(arg)) {
         size_t i = 0;
         for (auto funArg : functor->getArguments()) {
             // TODO (azreika): use unique pointers
             // try inlining each argument from left to right
             NullableVector<Argument*> argumentVersions = getInlinedArgument(program, funArg);
             if (argumentVersions.isValid()) {
                 changed = true;
                 for (Argument* newArgVersion : argumentVersions.getVector()) {
                     // same functor but with new argument version
                     VecOwn<Argument> argsCopy;
                     size_t j = 0;
                     for (auto& functorArg : functor->getArguments()) {
                         if (j == i) {
                             argsCopy.emplace_back(newArgVersion);
                         } else {
                             argsCopy.emplace_back(functorArg->clone());
                         }
                         ++j;
                     }
                     if (const auto* intrFunc = dynamic_cast<const IntrinsicFunctor*>(arg)) {
                         auto* newFunctor = new IntrinsicFunctor(intrFunc->getFunction(), std::move(argsCopy));
                         newFunctor->setSrcLoc(functor->getSrcLoc());
                         versions.push_back(newFunctor);
                     } else if (const auto* userFunc = dynamic_cast<const UserDefinedFunctor*>(arg)) {
                         auto* newFunctor = new UserDefinedFunctor(userFunc->getName(), std::move(argsCopy));
                         newFunctor->setSrcLoc(userFunc->getSrcLoc());
                         versions.push_back(newFunctor);
                     }
                 }
                 // only one step at a time
                 break;
             }
             ++i;
         }
     } else if (const auto* cast = dynamic_cast<const ast::TypeCast*>(arg)) {
         NullableVector<Argument*> argumentVersions = getInlinedArgument(program, cast->getValue());
         if (argumentVersions.isValid()) {
             changed = true;
             for (Argument* newArg : argumentVersions.getVector()) {
                 Argument* newTypeCast = new ast::TypeCast(Own<Argument>(newArg), cast->getType());
                 versions.push_back(newTypeCast);
             }
         }
     } else if (const auto* record = dynamic_cast<const RecordInit*>(arg)) {
         std::vector<Argument*> recordArguments = record->getArguments();
         for (size_t i = 0; i < recordArguments.size(); i++) {
             Argument* currentRecArg = recordArguments[i];
             NullableVector<Argument*> argumentVersions = getInlinedArgument(program, currentRecArg);
             if (argumentVersions.isValid()) {
                 changed = true;
                 for (Argument* newArgumentVersion : argumentVersions.getVector()) {
                     auto* newRecordArg = new RecordInit();
                     for (size_t j = 0; j < recordArguments.size(); j++) {
                         if (i == j) {
                             newRecordArg->addArgument(Own<Argument>(newArgumentVersion));
                         } else {
                             newRecordArg->addArgument(souffle::clone(recordArguments[j]));
                         }
                     }
                     versions.push_back(newRecordArg);
                 }
             }
             // Only perform one stage of inlining at a time.
             if (changed) {
                 break;
             }
         }
     }
     if (changed) {
         // Return a valid vector - replacements need to be made!
         return NullableVector<Argument*>(versions);
     } else {
         // Return an invalid vector - no inlining has occurred
         return NullableVector<Argument*>();
     }
 }
getInlinedAtom()
NullableVector<Atom*> souffle::ast::transform::getInlinedAtom (Program & program, Atom & atom)
Returns a vector of atoms that should replace the given atom after one step of inlining.
Assumes the relation the atom belongs to is not inlined itself.
Definition at line 719 of file InlineRelations.cpp.
References souffle::clone(), souffle::ast::Atom::getArguments(), getInlinedArgument(), souffle::ast::Atom::getQualifiedName(), souffle::ast::Node::getSrcLoc(), souffle::ast::transform::NullableVector< T >::getVector(), i, souffle::ast::transform::NullableVector< T >::isValid(), and j.
Referenced by getInlinedClause(), and getInlinedLiteral().
{
     bool changed = false;
     std::vector<Atom*> versions;
     // Try to inline each of the atom's arguments
     std::vector<Argument*> arguments = atom.getArguments();
     for (size_t i = 0; i < arguments.size(); i++) {
         Argument* arg = arguments[i];
         NullableVector<Argument*> argumentVersions = getInlinedArgument(program, arg);
         if (argumentVersions.isValid()) {
             // Argument has replacements
             changed = true;
             // Create a new atom per new version of the argument
             for (Argument* newArgument : argumentVersions.getVector()) {
                 auto args = atom.getArguments();
                 VecOwn<Argument> newArgs;
                 for (size_t j = 0; j < args.size(); j++) {
                     if (j == i) {
                         newArgs.emplace_back(newArgument);
                     } else {
                         newArgs.emplace_back(args[j]->clone());
                     }
                 }
                 auto* newAtom = new Atom(atom.getQualifiedName(), std::move(newArgs), atom.getSrcLoc());
                 versions.push_back(newAtom);
             }
         }
         // Only perform one stage of inlining at a time.
         if (changed) {
             break;
         }
     }
     if (changed) {
         // Return a valid vector - replacements need to be made!
         return NullableVector<Atom*>(versions);
     } else {
         // Return an invalid vector - no replacements need to be made
         return NullableVector<Atom*>();
     }
 }
getInlinedClause()
std::vector<Clause*> souffle::ast::transform::getInlinedClause (Program & program, const Clause & clause)
Returns a list of clauses that should replace the given clause after one step of inlining.
If no inlining can occur, the list will only contain a clone of the original clause.
Definition at line 901 of file InlineRelations.cpp.
References souffle::ast::Clause::addToBody(), souffle::ast::Clause::clone(), souffle::clone(), souffle::ast::cloneHead(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), getInlinedAtom(), getInlinedLiteral(), souffle::ast::Node::getSrcLoc(), souffle::ast::transform::NullableVector< T >::getVector(), i, and souffle::ast::transform::NullableVector< T >::isValid().
Referenced by souffle::ast::transform::InlineRelationsTransformer::transform().
{
     bool changed = false;
     std::vector<Clause*> versions;
     // Try to inline things contained in the arguments of the head first.
     // E.g. `a(x, max y : { b(y) }) :- c(x).`, where b should be inlined.
     Atom* head = clause.getHead();
     NullableVector<Atom*> headVersions = getInlinedAtom(program, *head);
     if (headVersions.isValid()) {
         // The head atom can be inlined!
         changed = true;
         // Produce the new clauses with the replacement head atoms
         for (Atom* newHead : headVersions.getVector()) {
             auto* newClause = new Clause();
             newClause->setSrcLoc(clause.getSrcLoc());
             newClause->setHead(Own<Atom>(newHead));
             // The body will remain unchanged
             for (Literal* lit : clause.getBodyLiterals()) {
                 newClause->addToBody(souffle::clone(lit));
             }
             versions.push_back(newClause);
         }
     }
     // Only perform one stage of inlining at a time.
     // If the head atoms did not need inlining, try inlining atoms nested in the body.
     if (!changed) {
         std::vector<Literal*> bodyLiterals = clause.getBodyLiterals();
         for (size_t i = 0; i < bodyLiterals.size(); i++) {
             Literal* currLit = bodyLiterals[i];
             // Three possible cases when trying to inline a literal:
             //  1) The literal itself may be directly inlined. In this case, the atom can be replaced
             //    with multiple different bodies, as the inlined atom may have several rules.
             //  2) Otherwise, the literal itself may not need to be inlined, but a subnode (e.g. an argument)
             //    may need to be inlined. In this case, an altered literal must replace the original.
             //    Again, several possible versions may exist, as the inlined relation may have several rules.
             //  3) The literal does not depend on any inlined relations, and so does not need to be changed.
             NullableVector<std::vector<Literal*>> litVersions = getInlinedLiteral(program, currLit);
             if (litVersions.isValid()) {
                 // Case 1 and 2: Inlining has occurred!
                 changed = true;
                 // The literal may be replaced with several different bodies.
                 // Create a new clause for each possible version.
                 std::vector<std::vector<Literal*>> bodyVersions = litVersions.getVector();
                 // Create the base clause with the current literal removed
                 auto baseClause = Own<Clause>(cloneHead(&clause));
                 for (Literal* oldLit : bodyLiterals) {
                     if (currLit != oldLit) {
                         baseClause->addToBody(souffle::clone(oldLit));
                     }
                 }
                 for (std::vector<Literal*> body : bodyVersions) {
                     Clause* replacementClause = baseClause->clone();
                     // Add in the current set of literals replacing the inlined literal
                     // In Case 2, each body contains exactly one literal
                     for (Literal* newLit : body) {
                         replacementClause->addToBody(Own<Literal>(newLit));
                     }
                     versions.push_back(replacementClause);
                 }
             }
             // Only replace at most one literal per iteration
             if (changed) {
                 break;
             }
         }
     }
     if (!changed) {
         // Case 3: No inlining changes, so a clone of the original should be returned
         std::vector<Clause*> ret;
         ret.push_back(clause.clone());
         return ret;
     } else {
         // Inlining changes, so return the replacement clauses.
         return versions;
     }
 }
getInlinedLiteral()
NullableVector< std::vector< Literal * > > souffle::ast::transform::getInlinedLiteral (Program & program, Literal * lit)
Tries to perform a single step of inlining on the given literal.
Returns a pair of nullable vectors (v, w) such that:
v is valid if and only if the literal can be directly inlined, whereby it contains the bodies that replace it
if v is not valid, then w is valid if and only if the literal cannot be inlined directly, but contains a subargument that can be. In this case, it will contain the versions that will replace it.
If both are invalid, then no more inlining can occur on this literal and we are done.
Definition at line 775 of file InlineRelations.cpp.
References souffle::clone(), formNegatedLiterals(), souffle::ast::getClauses(), getInlinedArgument(), getInlinedAtom(), souffle::ast::getRelation(), souffle::ast::transform::NullableVector< T >::getVector(), souffle::ast::Relation::hasQualifier(), souffle::INLINE, inlineBodyLiterals(), and souffle::ast::transform::NullableVector< T >::isValid().
Referenced by getInlinedArgument(), getInlinedClause(), and souffle::ast::transform::NullableVector< T >::getVector().
{
     bool inlined = false;
     bool changed = false;
     std::vector<std::vector<Literal*>> addedBodyLiterals;
     std::vector<Literal*> versions;
     if (auto* atom = dynamic_cast<Atom*>(lit)) {
         // Check if this atom is meant to be inlined
         Relation* rel = getRelation(program, atom->getQualifiedName());
         if (rel->hasQualifier(RelationQualifier::INLINE)) {
             // We found an atom in the clause that needs to be inlined!
             // The clause needs to be replaced
             inlined = true;
             // N new clauses should be formed, where N is the number of clauses
             // associated with the inlined relation
             for (Clause* inClause : getClauses(program, *rel)) {
                 // Form the replacement clause
                 std::pair<NullableVector<Literal*>, std::vector<BinaryConstraint*>> inlineResult =
                         inlineBodyLiterals(atom, inClause);
                 NullableVector<Literal*> replacementBodyLiterals = inlineResult.first;
                 std::vector<BinaryConstraint*> currConstraints = inlineResult.second;
                 if (!replacementBodyLiterals.isValid()) {
                     // Failed to unify the atoms! We can skip this one...
                     continue;
                 }
                 // Unification successful - the returned vector of literals represents one possible body
                 // replacement We can add in the unification constraints as part of these literals.
                 std::vector<Literal*> bodyResult = replacementBodyLiterals.getVector();
                 for (BinaryConstraint* cons : currConstraints) {
                     bodyResult.push_back(cons);
                 }
                 addedBodyLiterals.push_back(bodyResult);
             }
         } else {
             // Not meant to be inlined, but a subargument may be
             NullableVector<Atom*> atomVersions = getInlinedAtom(program, *atom);
             if (atomVersions.isValid()) {
                 // Subnode needs to be inlined, so we have a vector of replacement atoms
                 changed = true;
                 for (Atom* newAtom : atomVersions.getVector()) {
                     versions.push_back(newAtom);
                 }
             }
         }
     } else if (auto neg = dynamic_cast<Negation*>(lit)) {
         // For negations, check the corresponding atom
         Atom* atom = neg->getAtom();
         NullableVector<std::vector<Literal*>> atomVersions = getInlinedLiteral(program, atom);
         if (atomVersions.isValid()) {
             // The atom can be inlined
             inlined = true;
             if (atomVersions.getVector().empty()) {
                 // No clauses associated with the atom, so just becomes a true literal
                 addedBodyLiterals.push_back({new BooleanConstraint(true)});
             } else {
                 // Suppose an atom a(x) is inlined and has the following rules:
                 //  - a(x) :- a11(x), a12(x).
                 //  - a(x) :- a21(x), a22(x).
                 // Then, a(x) <- (a11(x) ^ a12(x)) v (a21(x) ^ a22(x))
                 //  => !a(x) <- (!a11(x) v !a12(x)) ^ (!a21(x) v !a22(x))
                 //  => !a(x) <- (!a11(x) ^ !a21(x)) v (!a11(x) ^ !a22(x)) v ...
                 // Essentially, produce every combination (m_1 ^ m_2 ^ ...) where m_i is a
                 // negated literal in the ith rule of a.
                 addedBodyLiterals = formNegatedLiterals(program, atom);
             }
         }
         if (atomVersions.isValid()) {
             for (const auto& curVec : atomVersions.getVector()) {
                 for (auto* cur : curVec) {
                     delete cur;
                 }
             }
         }
     } else if (auto* constraint = dynamic_cast<BinaryConstraint*>(lit)) {
         NullableVector<Argument*> lhsVersions = getInlinedArgument(program, constraint->getLHS());
         if (lhsVersions.isValid()) {
             changed = true;
             for (Argument* newLhs : lhsVersions.getVector()) {
                 Literal* newLit = new BinaryConstraint(constraint->getOperator(), Own<Argument>(newLhs),
                         souffle::clone(constraint->getRHS()));
                 versions.push_back(newLit);
             }
         } else {
             NullableVector<Argument*> rhsVersions = getInlinedArgument(program, constraint->getRHS());
             if (rhsVersions.isValid()) {
                 changed = true;
                 for (Argument* newRhs : rhsVersions.getVector()) {
                     Literal* newLit = new BinaryConstraint(constraint->getOperator(),
                             souffle::clone(constraint->getLHS()), Own<Argument>(newRhs));
                     versions.push_back(newLit);
                 }
             }
         }
     }
     if (changed) {
         // Not inlined directly but found replacement literals
         // Rewrite these as single-literal bodies
         for (Literal* version : versions) {
             std::vector<Literal*> newBody;
             newBody.push_back(version);
             addedBodyLiterals.push_back(newBody);
         }
         inlined = true;
     }
     if (inlined) {
         return NullableVector<std::vector<Literal*>>(addedBodyLiterals);
     } else {
         return NullableVector<std::vector<Literal*>>();
     }
 }
inlineBodyLiterals()
std::pair<NullableVector<Literal*>, std::vector<BinaryConstraint*> > souffle::ast::transform::inlineBodyLiterals (Atom * atom, Clause * atomInlineClause)
Inlines the given atom based on a given clause.
Returns the vector of replacement literals and the necessary constraints. If unification is unsuccessful, the vector of literals is marked as invalid.
Definition at line 295 of file InlineRelations.cpp.
References souffle::clone(), souffle::EQ, souffle::ast::transform::NullableVector< T >::getVector(), souffle::ast::transform::NullableVector< T >::isValid(), and unifyAtoms().
Referenced by formNegatedLiterals(), and getInlinedLiteral().
{
     bool changed = false;
     std::vector<Literal*> addedLits;
     std::vector<BinaryConstraint*> constraints;
     // Rename the variables in the inlined clause to avoid conflicts when unifying multiple atoms
     // - particularly when an inlined relation appears twice in a clause.
     static int inlineCount = 0;
     // Make a temporary clone so we can rename variables without fear
     auto atomClause = souffle::clone(atomInlineClause);
     struct VariableRenamer : public NodeMapper {
         int varnum;
         VariableRenamer(int varnum) : varnum(varnum) {}
         Own<Node> operator()(Own<Node> node) const override {
             if (auto* var = dynamic_cast<ast::Variable*>(node.get())) {
                 // Rename the variable
                 auto newVar = souffle::clone(var);
                 std::stringstream newName;
                 newName << "<inlined_" << var->getName() << "_" << varnum << ">";
                 newVar->setName(newName.str());
                 return newVar;
             }
             node->apply(*this);
             return node;
         }
     };
     VariableRenamer update(inlineCount);
     atomClause->apply(update);
     inlineCount++;
     // Get the constraints needed to unify the two atoms
     NullableVector<std::pair<Argument*, Argument*>> res = unifyAtoms(atomClause->getHead(), atom);
     if (res.isValid()) {
         changed = true;
         for (std::pair<Argument*, Argument*> pair : res.getVector()) {
             // FIXME: float equiv (`FEQ`)
             constraints.push_back(new BinaryConstraint(
                     BinaryConstraintOp::EQ, souffle::clone(pair.first), souffle::clone(pair.second)));
         }
         // Add in the body of the current clause of the inlined atom
         for (Literal* lit : atomClause->getBodyLiterals()) {
             addedLits.push_back(lit->clone());
         }
     }
     if (changed) {
         return std::make_pair(NullableVector<Literal*>(addedLits), constraints);
     } else {
         return std::make_pair(NullableVector<Literal*>(), constraints);
     }
 }
makeInfoRelation()
Own<Relation> souffle::ast::transform::makeInfoRelation (Clause & originalClause, size_t originalClauseNum, TranslationUnit & translationUnit)
Definition at line 72 of file Provenance.cpp.
References souffle::ast::Program::addClause(), souffle::fatal(), tinyformat::format(), souffle::ast::Atom::getArguments(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Atom::getQualifiedName(), i, souffle::INFO, souffle::join(), makeRelationName(), souffle::toBinaryConstraintSymbol(), and souffle::toString().
Referenced by souffle::ast::transform::ProvenanceTransformer::transformMaxHeight().
{
     QualifiedName name =
             makeRelationName(originalClause.getHead()->getQualifiedName(), "@info", originalClauseNum);
     // initialise info relation
     auto infoRelation = new Relation();
     infoRelation->setQualifiedName(name);
     // set qualifier to INFO_RELATION
     infoRelation->setRepresentation(RelationRepresentation::INFO);
     // create new clause containing a single fact
     auto infoClause = new Clause();
     auto infoClauseHead = new Atom();
     infoClauseHead->setQualifiedName(name);
     // (darth_tytus): Can this be unsigned?
     infoRelation->addAttribute(mk<Attribute>("clause_num", QualifiedName("number")));
     infoClauseHead->addArgument(mk<NumericConstant>(originalClauseNum));
     // add head relation as meta info
     std::vector<std::string> headVariables;
     // a method to stringify an Argument, translating functors and aggregates
     // keep a global counter of functor and aggregate numbers, which increment for each unique
     // functor/aggregate
     int functorNumber = 0;
     int aggregateNumber = 0;
     auto getArgInfo = [&](Argument* arg) -> std::string {
         if (auto* var = dynamic_cast<ast::Variable*>(arg)) {
             return toString(*var);
         } else if (auto* constant = dynamic_cast<Constant*>(arg)) {
             return toString(*constant);
         }
         if (isA<UnnamedVariable>(arg)) {
             return "_";
         }
         if (isA<Functor>(arg)) {
             return tfm::format("functor_%d", functorNumber++);
         }
         if (isA<Aggregator>(arg)) {
             return tfm::format("agg_%d", aggregateNumber++);
         }
         fatal("Unhandled argument type");
     };
     // add head arguments
     for (auto& arg : originalClause.getHead()->getArguments()) {
         headVariables.push_back(getArgInfo(arg));
     }
     // join variables in the head with commas
     std::stringstream headVariableString;
     headVariableString << join(headVariables, ",");
     // add an attribute to infoRelation for the head of clause
     infoRelation->addAttribute(mk<Attribute>(std::string("head_vars"), QualifiedName("symbol")));
     infoClauseHead->addArgument(mk<StringConstant>(toString(join(headVariables, ","))));
     // visit all body literals and add to info clause head
     for (size_t i = 0; i < originalClause.getBodyLiterals().size(); i++) {
         auto lit = originalClause.getBodyLiterals()[i];
         const Atom* atom = nullptr;
         if (isA<Atom>(lit)) {
             atom = static_cast<Atom*>(lit);
         } else if (isA<Negation>(lit)) {
             atom = static_cast<Negation*>(lit)->getAtom();
         } else if (isA<ProvenanceNegation>(lit)) {
             atom = static_cast<ProvenanceNegation*>(lit)->getAtom();
         }
         // add an attribute for atoms and binary constraints
         if (atom != nullptr || isA<BinaryConstraint>(lit)) {
             infoRelation->addAttribute(
                     mk<Attribute>(std::string("rel_") + std::to_string(i), QualifiedName("symbol")));
         }
         if (atom != nullptr) {
             std::string relName = toString(atom->getQualifiedName());
             // for an atom, add its name and variables (converting aggregates to variables)
             if (isA<Atom>(lit)) {
                 std::string atomDescription = relName;
                 for (auto& arg : atom->getArguments()) {
                     atomDescription.append("," + getArgInfo(arg));
                 }
                 infoClauseHead->addArgument(mk<StringConstant>(atomDescription));
                 // for a negation, add a marker with the relation name
             } else if (isA<Negation>(lit)) {
                 infoClauseHead->addArgument(mk<StringConstant>("!" + relName));
             }
         }
     }
     // visit all body constraints and add to info clause head
     for (size_t i = 0; i < originalClause.getBodyLiterals().size(); i++) {
         auto lit = originalClause.getBodyLiterals()[i];
         if (auto con = dynamic_cast<BinaryConstraint*>(lit)) {
             // for a constraint, add the constraint symbol and LHS and RHS
             std::string constraintDescription = toBinaryConstraintSymbol(con->getOperator());
             constraintDescription.append("," + getArgInfo(con->getLHS()));
             constraintDescription.append("," + getArgInfo(con->getRHS()));
             infoClauseHead->addArgument(mk<StringConstant>(constraintDescription));
         }
     }
     infoRelation->addAttribute(mk<Attribute>("clause_repr", QualifiedName("symbol")));
     infoClauseHead->addArgument(mk<StringConstant>(toString(originalClause)));
     // set clause head and add clause to info relation
     infoClause->setHead(Own<Atom>(infoClauseHead));
     Program& program = translationUnit.getProgram();
     program.addClause(Own<Clause>(infoClause));
     return Own<Relation>(infoRelation);
 }
makeRelationName()
QualifiedName souffle::ast::transform::makeRelationName (const QualifiedName & orig, const std::string & type, int num = -1) inline
Helper functions.
Definition at line 62 of file Provenance.cpp.
References souffle::ast::QualifiedName::append(), and souffle::toString().
Referenced by makeInfoRelation().
{
     QualifiedName newName(toString(orig));
     newName.append(type);
     if (num != -1) {
         newName.append((const std::string&)std::to_string(num));
     }
     return newName;
 }
nameInlinedUnderscores()
void souffle::ast::transform::nameInlinedUnderscores (Program & program)
Removes all underscores in all atoms of inlined relations.
Definition at line 141 of file InlineRelations.cpp.
References souffle::ast::Program::apply(), souffle::ast::Program::getRelations(), and souffle::INLINE.
Referenced by souffle::ast::transform::InlineRelationsTransformer::transform().
{
     struct M : public NodeMapper {
         const std::set<QualifiedName> inlinedRelations;
         bool replaceUnderscores;
         M(std::set<QualifiedName> inlinedRelations, bool replaceUnderscores)
                 : inlinedRelations(std::move(inlinedRelations)), replaceUnderscores(replaceUnderscores) {}
         Own<Node> operator()(Own<Node> node) const override {
             static int underscoreCount = 0;
             if (!replaceUnderscores) {
                 // Check if we should start replacing underscores for this node's subnodes
                 if (auto* atom = dynamic_cast<Atom*>(node.get())) {
                     if (inlinedRelations.find(atom->getQualifiedName()) != inlinedRelations.end()) {
                         // Atom associated with an inlined relation, so replace the underscores
                         // in all of its subnodes with named variables.
                         M replace(inlinedRelations, true);
                         node->apply(replace);
                         return node;
                     }
                 }
             } else if (isA<UnnamedVariable>(node.get())) {
                 // Give a unique name to the underscored variable
                 // TODO (azreika): need a more consistent way of handling internally generated variables in
                 // general
                 std::stringstream newVarName;
                 newVarName << "<underscore_" << underscoreCount++ << ">";
                 return mk<ast::Variable>(newVarName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     // Store the names of all relations to be inlined
     std::set<QualifiedName> inlinedRelations;
     for (Relation* rel : program.getRelations()) {
         if (rel->hasQualifier(RelationQualifier::INLINE)) {
             inlinedRelations.insert(rel->getQualifiedName());
         }
     }
     // Apply the renaming procedure to the entire program
     M update(inlinedRelations, false);
     program.apply(update);
 }
negateLiteral()
Literal* souffle::ast::transform::negateLiteral (Literal * lit)
Returns the negated version of a given literal.
Definition at line 356 of file InlineRelations.cpp.
References souffle::ast::Atom::clone(), souffle::clone(), souffle::fatal(), and souffle::ast::negateConstraintInPlace().
Referenced by combineNegatedLiterals().
{
     if (auto* atom = dynamic_cast<Atom*>(lit)) {
         auto* neg = new Negation(souffle::clone(atom));
         return neg;
     } else if (auto* neg = dynamic_cast<Negation*>(lit)) {
         Atom* atom = neg->getAtom()->clone();
         return atom;
     } else if (auto* cons = dynamic_cast<Constraint*>(lit)) {
         Constraint* newCons = cons->clone();
         negateConstraintInPlace(*newCons);
         return newCons;
     }
     fatal("unsupported literal type: %s", *lit);
 }
normaliseInlinedHeads()
void souffle::ast::transform::normaliseInlinedHeads (Program & program)
Replace constants in the head of inlined clauses with (constrained) variables.
Definition at line 86 of file InlineRelations.cpp.
References souffle::ast::Program::addClause(), souffle::clone(), souffle::EQ, souffle::FEQ, souffle::ast::NumericConstant::Float, souffle::ast::getClauses(), souffle::ast::Program::getRelations(), souffle::INLINE, and souffle::ast::Program::removeClause().
Referenced by souffle::ast::transform::InlineRelationsTransformer::transform().
{
     static int newVarCount = 0;
     // Go through the clauses of all inlined relations
     for (Relation* rel : program.getRelations()) {
         if (!rel->hasQualifier(RelationQualifier::INLINE)) {
             continue;
         }
         for (Clause* clause : getClauses(program, *rel)) {
             // Set up the new clause with an empty body and no arguments in the head
             auto newClause = mk<Clause>();
             newClause->setSrcLoc(clause->getSrcLoc());
             auto clauseHead = mk<Atom>(clause->getHead()->getQualifiedName());
             // Add in everything in the original body
             for (Literal* lit : clause->getBodyLiterals()) {
                 newClause->addToBody(souffle::clone(lit));
             }
             // Set up the head arguments in the new clause
             for (Argument* arg : clause->getHead()->getArguments()) {
                 if (auto* constant = dynamic_cast<Constant*>(arg)) {
                     // Found a constant in the head, so replace it with a variable
                     std::stringstream newVar;
                     newVar << "<new_var_" << newVarCount++ << ">";
                     clauseHead->addArgument(mk<ast::Variable>(newVar.str()));
                     auto* const c_num = dynamic_cast<const NumericConstant*>(constant);
                     assert((!c_num || c_num->getType()) && "numeric constant wasn't bound to a type");
                     auto opEq = c_num && *c_num->getType() == NumericConstant::Type::Float
                                         ? BinaryConstraintOp::FEQ
                                         : BinaryConstraintOp::EQ;
                     // Add a body constraint to set the variable's value to be the original constant
                     newClause->addToBody(mk<BinaryConstraint>(
                             opEq, mk<ast::Variable>(newVar.str()), souffle::clone(constant)));
                 } else {
                     // Already a variable
                     clauseHead->addArgument(souffle::clone(arg));
                 }
             }
             newClause->setHead(std::move(clauseHead));
             // Replace the old clause with this one
             program.addClause(std::move(newClause));
             program.removeClause(clause);
         }
     }
 }
reduceSubstitution()
bool souffle::ast::transform::reduceSubstitution (std::vector< std::pair< Argument *, Argument *>> & sub)
Reduces a vector of substitutions.
Returns false only if matched argument pairs are found to be incompatible.
Definition at line 210 of file InlineRelations.cpp.
References i, lhs, rhs, and souffle::ast::analysis::sub().
Referenced by unifyAtoms().
{
     // Keep trying to reduce the substitutions until we reach a fixed point.
     // Note that at this point no underscores ('_') or counters ('$') should appear.
     bool done = false;
     while (!done) {
         done = true;
         // Try reducing each pair by one step
         for (size_t i = 0; i < sub.size(); i++) {
             auto currPair = sub[i];
             Argument* lhs = currPair.first;
             Argument* rhs = currPair.second;
             // Start trying to reduce the substitution
             // Note: Can probably go further with this substitution reduction
             if (*lhs == *rhs) {
                 // Get rid of redundant `x = x`
                 sub.erase(sub.begin() + i);
                 done = false;
             } else if (isA<Constant>(lhs) && isA<Constant>(rhs)) {
                 // Both are constants but not equal (prev case => !=)
                 // Failed to unify!
                 return false;
             } else if (isA<RecordInit>(lhs) && isA<RecordInit>(rhs)) {
                 // Note: we will not deal with the case where only one side is
                 // a record and the other is a variable, as variables can be records
                 // on a deeper level.
                 std::vector<Argument*> lhsArgs = static_cast<RecordInit*>(lhs)->getArguments();
                 std::vector<Argument*> rhsArgs = static_cast<RecordInit*>(rhs)->getArguments();
                 if (lhsArgs.size() != rhsArgs.size()) {
                     // Records of unequal size can't be equated
                     return false;
                 }
                 // Equate all corresponding arguments
                 for (size_t i = 0; i < lhsArgs.size(); i++) {
                     sub.push_back(std::make_pair(lhsArgs[i], rhsArgs[i]));
                 }
                 // Get rid of the record equality
                 sub.erase(sub.begin() + i);
                 done = false;
             } else if ((isA<RecordInit>(lhs) && isA<Constant>(rhs)) ||
                        (isA<Constant>(lhs) && isA<RecordInit>(rhs))) {
                 // A record =/= a constant
                 return false;
             }
         }
     }
     return true;
 }
renameVariables()
void souffle::ast::transform::renameVariables (Argument * arg)
Renames all variables in a given argument uniquely.
Definition at line 485 of file InlineRelations.cpp.
References souffle::ast::Node::apply(), and souffle::clone().
Referenced by combineAggregators().
{
     static int varCount = 0;
     varCount++;
     struct M : public NodeMapper {
         int varnum;
         M(int varnum) : varnum(varnum) {}
         Own<Node> operator()(Own<Node> node) const override {
             if (auto* var = dynamic_cast<ast::Variable*>(node.get())) {
                 auto newVar = souffle::clone(var);
                 std::stringstream newName;
                 newName << var->getName() << "-v" << varnum;
                 newVar->setName(newName.str());
                 return newVar;
             }
             node->apply(*this);
             return node;
         }
     };
     M update(varCount);
     arg->apply(update);
 }
transformEqrelRelation()
void souffle::ast::transform::transformEqrelRelation (Program & program, Relation & rel)
Transform eqrel relations to explicitly define equivalence relations.
Definition at line 197 of file Provenance.cpp.
References souffle::ast::Atom::addArgument(), souffle::ast::Program::addClause(), souffle::BTREE, souffle::EQREL, souffle::ast::Relation::getArity(), souffle::ast::Relation::getQualifiedName(), souffle::ast::Relation::getRepresentation(), souffle::map(), and souffle::ast::Relation::setRepresentation().
Referenced by souffle::ast::transform::ProvenanceTransformer::transformMaxHeight().
{
     assert(rel.getRepresentation() == RelationRepresentation::EQREL &&
             "attempting to transform non-eqrel relation");
     assert(rel.getArity() == 2 && "eqrel relation not binary");
     rel.setRepresentation(RelationRepresentation::BTREE);
     // transitivity
     // transitive clause: A(x, z) :- A(x, y), A(y, z).
     auto transitiveClause = new Clause();
     auto transitiveClauseHead = new Atom(rel.getQualifiedName());
     transitiveClauseHead->addArgument(mk<ast::Variable>("x"));
     transitiveClauseHead->addArgument(mk<ast::Variable>("z"));
     auto transitiveClauseBody = new Atom(rel.getQualifiedName());
     transitiveClauseBody->addArgument(mk<ast::Variable>("x"));
     transitiveClauseBody->addArgument(mk<ast::Variable>("y"));
     auto transitiveClauseBody2 = new Atom(rel.getQualifiedName());
     transitiveClauseBody2->addArgument(mk<ast::Variable>("y"));
     transitiveClauseBody2->addArgument(mk<ast::Variable>("z"));
     transitiveClause->setHead(Own<Atom>(transitiveClauseHead));
     transitiveClause->addToBody(Own<Literal>(transitiveClauseBody));
     transitiveClause->addToBody(Own<Literal>(transitiveClauseBody2));
     program.addClause(Own<Clause>(transitiveClause));
     // symmetric
     // symmetric clause: A(x, y) :- A(y, x).
     auto symClause = new Clause();
     auto symClauseHead = new Atom(rel.getQualifiedName());
     symClauseHead->addArgument(mk<ast::Variable>("x"));
     symClauseHead->addArgument(mk<ast::Variable>("y"));
     auto symClauseBody = new Atom(rel.getQualifiedName());
     symClauseBody->addArgument(mk<ast::Variable>("y"));
     symClauseBody->addArgument(mk<ast::Variable>("x"));
     symClause->setHead(Own<Atom>(symClauseHead));
     symClause->addToBody(Own<Literal>(symClauseBody));
     program.addClause(Own<Clause>(symClause));
     // reflexivity
     // reflexive clause: A(x, x) :- A(x, _).
     auto reflexiveClause = new Clause();
     auto reflexiveClauseHead = new Atom(rel.getQualifiedName());
     reflexiveClauseHead->addArgument(mk<ast::Variable>("x"));
     reflexiveClauseHead->addArgument(mk<ast::Variable>("x"));
     auto reflexiveClauseBody = new Atom(rel.getQualifiedName());
     reflexiveClauseBody->addArgument(mk<ast::Variable>("x"));
     reflexiveClauseBody->addArgument(mk<UnnamedVariable>());
     reflexiveClause->setHead(Own<Atom>(reflexiveClauseHead));
     reflexiveClause->addToBody(Own<Literal>(reflexiveClauseBody));
     program.addClause(Own<Clause>(reflexiveClause));
 }
unifyAtoms()
NullableVector<std::pair<Argument*, Argument*> > souffle::ast::transform::unifyAtoms (Atom * first, Atom * second)
Returns the nullable vector of substitutions needed to unify the two given atoms.
If unification is not successful, the returned vector is marked as invalid. Assumes that the atoms are both of the same relation.
Definition at line 269 of file InlineRelations.cpp.
References souffle::ast::Atom::getArguments(), i, and reduceSubstitution().
Referenced by inlineBodyLiterals().
{
     std::vector<std::pair<Argument*, Argument*>> substitution;
     std::vector<Argument*> firstArgs = first->getArguments();
     std::vector<Argument*> secondArgs = second->getArguments();
     // Create the initial unification equalities
     for (size_t i = 0; i < firstArgs.size(); i++) {
         substitution.push_back(std::make_pair(firstArgs[i], secondArgs[i]));
     }
     // Reduce the substitutions
     bool success = reduceSubstitution(substitution);
     if (success) {
         return NullableVector<std::pair<Argument*, Argument*>>(substitution);
     } else {
         // Failed to unify the two atoms
         return NullableVector<std::pair<Argument*, Argument*>>();
     }
 }
usesInvalidWitness()
static const std::vector<SrcLocation> souffle::ast::transform::usesInvalidWitness (TranslationUnit & tu, const std::vector< Literal *> & literals, const std::set< Own< Argument >> & groundedArguments) static
Definition at line 824 of file SemanticChecker.cpp.
References souffle::clone(), souffle::ast::Aggregator::getBodyLiterals(), souffle::ast::analysis::getGroundedTerms(), i, str, and souffle::ast::visitDepthFirst().
Referenced by souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem().
{
     // Node-mapper that replaces aggregators with new (unique) variables
     struct M : public NodeMapper {
         // Variables introduced to replace aggregators
         mutable std::set<std::string> aggregatorVariables;
         const std::set<std::string>& getAggregatorVariables() {
             return aggregatorVariables;
         }
         Own<Node> operator()(Own<Node> node) const override {
             static int numReplaced = 0;
             if (isA<Aggregator>(node.get())) {
                 // Replace the aggregator with a variable
                 std::stringstream newVariableName;
                 newVariableName << "+aggr_var_" << numReplaced++;
                 // Keep track of which variables are bound to aggregators
                 aggregatorVariables.insert(newVariableName.str());
                 return mk<ast::Variable>(newVariableName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     std::vector<SrcLocation> result;
     // Create two versions of the original clause
     // Clause 1 - will remain equivalent to the original clause in terms of variable groundedness
     auto originalClause = mk<Clause>();
     originalClause->setHead(mk<Atom>("*"));
     // Clause 2 - will have aggregators replaced with intrinsically grounded variables
     auto aggregatorlessClause = mk<Clause>();
     aggregatorlessClause->setHead(mk<Atom>("*"));
     // Construct both clauses in the same manner to match the original clause
     // Must keep track of the subnode in Clause 1 that each subnode in Clause 2 matches to
     std::map<const Argument*, const Argument*> identicalSubnodeMap;
     for (const Literal* lit : literals) {
         auto firstClone = souffle::clone(lit);
         auto secondClone = souffle::clone(lit);
         // Construct the mapping between equivalent literal subnodes
         std::vector<const Argument*> firstCloneArguments;
         visitDepthFirst(*firstClone, [&](const Argument& arg) { firstCloneArguments.push_back(&arg); });
         std::vector<const Argument*> secondCloneArguments;
         visitDepthFirst(*secondClone, [&](const Argument& arg) { secondCloneArguments.push_back(&arg); });
         for (size_t i = 0; i < firstCloneArguments.size(); i++) {
             identicalSubnodeMap[secondCloneArguments[i]] = firstCloneArguments[i];
         }
         // Actually add the literal clones to each clause
         originalClause->addToBody(std::move(firstClone));
         aggregatorlessClause->addToBody(std::move(secondClone));
     }
     // Replace the aggregators in Clause 2 with variables
     M update;
     aggregatorlessClause->apply(update);
     // Create a dummy atom to force certain arguments to be grounded in the aggregatorlessClause
     auto groundingAtomAggregatorless = mk<Atom>("grounding_atom");
     auto groundingAtomOriginal = mk<Atom>("grounding_atom");
     // Force the new aggregator variables to be grounded in the aggregatorless clause
     const std::set<std::string>& aggregatorVariables = update.getAggregatorVariables();
     for (const std::string& str : aggregatorVariables) {
         groundingAtomAggregatorless->addArgument(mk<ast::Variable>(str));
     }
     // Force the given grounded arguments to be grounded in both clauses
     for (const Own<Argument>& arg : groundedArguments) {
         groundingAtomAggregatorless->addArgument(souffle::clone(arg));
         groundingAtomOriginal->addArgument(souffle::clone(arg));
     }
     aggregatorlessClause->addToBody(std::move(groundingAtomAggregatorless));
     originalClause->addToBody(std::move(groundingAtomOriginal));
     // Compare the grounded analysis of both generated clauses
     // All added arguments in Clause 2 were forced to be grounded, so if an ungrounded argument
     // appears in Clause 2, it must also appear in Clause 1. Consequently, have two cases:
     //   - The argument is also ungrounded in Clause 1 - handled by another check
     //   - The argument is grounded in Clause 1 => the argument was grounded in the
     //     first clause somewhere along the line by an aggregator-body - not allowed!
     std::set<Own<Argument>> newlyGroundedArguments;
     auto originalGrounded = getGroundedTerms(tu, *originalClause);
     for (auto&& pair : getGroundedTerms(tu, *aggregatorlessClause)) {
         if (!pair.second && originalGrounded[identicalSubnodeMap[pair.first]]) {
             result.push_back(pair.first->getSrcLoc());
         }
         // Otherwise, it can now be considered grounded
         newlyGroundedArguments.insert(souffle::clone(pair.first));
     }
     // All previously grounded are still grounded
     for (const Own<Argument>& arg : groundedArguments) {
         newlyGroundedArguments.insert(souffle::clone(arg));
     }
     // Everything on this level is fine, check subaggregators of each literal
     for (const Literal* lit : literals) {
         visitDepthFirst(*lit, [&](const Aggregator& aggr) {
             // Check recursively if an invalid witness is used
             for (auto&& argloc : usesInvalidWitness(tu, aggr.getBodyLiterals(), newlyGroundedArguments)) {
                 result.push_back(argloc);
             }
         });
     }
     return result;
 }