souffle: souffle::ast::test Namespace Reference
souffle::ast::test Namespace Reference
Functions
bool isNotSubtypeOf (const analysis::Type &a, const analysis::Type &b)
Own< TranslationUnit > makeATU (std::string program=".decl A,B,C(x:number)")
Own< Clause > makeClause (std::string name, Own< Argument > headArgument)
Own< Clause > makeClauseA (Own< Argument > headArgument)
Own< TranslationUnit > makePrintedATU (Own< TranslationUnit > &tu)
TEST (TypeSystem, Basic)
TEST (Constraints, Basic)
TEST (RuleBody, Basic)
TEST (RuleBody, Negation)
TEST (TypeSystem, isNumberType)
TEST (AstUtils, Grounded)
TEST (Program, Parse)
TEST (AstPrint, NilConstant)
TEST (AstPrint, NumberConstant)
TEST (RuleBody, ClauseBodyExtraction)
TEST (AstPrint, StringConstant)
TEST (TypeSystem, isSubtypeOf_Basic)
TEST (AstPrint, Variable)
TEST (AstUtils, GroundedRecords)
TEST (AstPrint, UnnamedVariable)
TEST (AstPrint, Counter)
TEST (Program, RemoveClause)
test removeClause, addRelation and removeRelation
TEST (AstPrint, AggregatorMin)
TEST (AstUtils, ReorderClauseAtoms)
TEST (TypeSystem, isSubtypeOf_Records)
TEST (Program, AppendRelation)
TEST (AstPrint, AggregatorMax)
TEST (Program, RemoveRelation)
TEST (AstPrint, AggregatorCount)
TEST (TypeSystem, GreatestCommonSubtype)
TEST (AstPrint, AggregatorSum)
TEST (TypeSystem, complexSubsetTypes)
TEST (TypeSystem, RecordSubsets)
TEST (TypeSystem, EquivTypes)
TEST (TypeSystem, AlgebraicDataType)
TESTASTCLONEANDEQUAL (Program, R"(.decl r(a:number,b:number,c:number,d:number) .decl s(x:symbol) .decl a(x:number) s("xxx"). r(X,Y,Z,W) :- a(X), 10 = Y, Y = Z, 8 + W = 12 + 14. r(z + 2, x, y, a) :- s(b), b = to_string(a), z = x, a = y, x = 2, a = 2 + x.)")
TESTASTCLONEANDEQUAL (Record, R"(.type N <: symbol .type R = [ a : N, B : N ] .decl r (r : R) .decl s (r : N) s(x) :- r([x,y]).)")
TESTASTCLONEANDEQUAL (SimpleTypes, R"(.type A <: symbol .type B <: symbol .type U = A | B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- u(X). b(X) :- u(X). u(X) :- u(X). a(X) :- b(X). a(X) :- b(Y).)")
TESTASTCLONEANDEQUAL (ComplexTypes, R"(.type A <: symbol .type B <: number .type U = B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- X < 10. b(X) :- X < 10. u(X) :- X < 10.)")
TESTASTCLONEANDEQUAL (ChainedTypes, R"(.type D <: symbol .type C = D .type B = C .type A = B .decl R1(x:A,y:B) .decl R2(x:C,y:D) .decl R4(x:A) output R4(x) :- R2(x,x),R1(x,x).)")
TESTASTCLONEANDEQUAL (NestedAggregates, R"(.type D <: symbol .decl r(x:D) r(x) :- r(y), x=cat(cat(x,x),x).)")
TESTASTCLONEANDEQUAL (RelationCopies, R"(.type D = number .decl a(a:D,b:D) .decl b(a:D,b:D) .decl c(a:D,b:D) .decl d(a:D,b:D) a(1,2). b(x,y) :- a(x,y). c(x,y) :- b(x,y). d(x,y) :- b(x,y), c(y,x).)")
Function Documentation
isNotSubtypeOf()
bool souffle::ast::test::isNotSubtypeOf (const analysis::Type & a, const analysis::Type & b)
Definition at line 84 of file type_system_test.cpp.
References souffle::ast::analysis::isSubtypeOf().
Referenced by TEST().
{
     return !isSubtypeOf(a, b);
 }
makeATU()
Own< TranslationUnit > souffle::ast::test::makeATU (std::string program = ".decl A,B,C(x:number)") inline
Definition at line 46 of file ast_print_test.cpp.
References d, e, and souffle::ParserDriver::parseTranslationUnit().
Referenced by makePrintedATU(), and TEST().
                                                                       :number)") {
     ErrorReport e;
     DebugReport d;
     return ParserDriver::parseTranslationUnit(program, e, d);
 }
makeClause()
Own<Clause> souffle::ast::test::makeClause (std::string name, Own< Argument > headArgument) inline
Definition at line 50 of file ast_program_test.cpp.
{
     auto headAtom = mk<Atom>(name);
     headAtom->addArgument(std::move(headArgument));
     auto clause = mk<Clause>();
     clause->setHead(std::move(headAtom));
     return clause;
 }
makeClauseA()
Own<Clause> souffle::ast::test::makeClauseA (Own< Argument > headArgument) inline
Definition at line 58 of file ast_print_test.cpp.
Referenced by TEST().
{
     auto headAtom = mk<Atom>("A");
     headAtom->addArgument(std::move(headArgument));
     auto clause = mk<Clause>();
     clause->setHead(std::move(headAtom));
     return clause;
 }
makePrintedATU()
Own<TranslationUnit> souffle::ast::test::makePrintedATU (Own< TranslationUnit > & tu) inline
Definition at line 52 of file ast_print_test.cpp.
References makeATU(), and souffle::profile::ss.
Referenced by TEST().
{
     std::stringstream ss;
     ss << tu->getProgram();
     return makeATU(ss.str());
 }
TEST() [1/30]
souffle::ast::test::TEST (TypeSystem , Basic)
Definition at line 31 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_EQ, souffle::ast::analysis::TypeEnvironment::getType(), souffle::toString(), and souffle::toVector().
{
     TypeEnvironment env;
     const analysis::Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const analysis::Type& B = env.createType<SubsetType>("B", env.getType("symbol"));
     auto& U = env.createType<UnionType>("U", toVector(&A, &B));
     auto& R = env.createType<RecordType>("R");
     R.setFields(toVector(&A, &B));
     EXPECT_EQ("A <: number", toString(A));
     EXPECT_EQ("B <: symbol", toString(B));
     EXPECT_EQ("U = A | B", toString(U));
     EXPECT_EQ("R = (A, B)", toString(R));
 }
TEST() [2/30]
souffle::ast::test::TEST (Constraints , Basic)
Definition at line 32 of file constraints_test.cpp.
References souffle::ast::analysis::Problem< Var >::add(), EXPECT_EQ, p, souffle::ast::analysis::Problem< Var >::solve(), souffle::ast::analysis::sub(), and souffle::toString().
{
     using Vars = Variable<std::string, set_property_space<int>>;
     Vars A("A");
     Vars B("B");
     Problem<Vars> p;
     // check empty problem
     EXPECT_EQ("{}", toString(p));
     EXPECT_EQ("{}", toString(p.solve()));
     // add a constraint
     p.add(sub(A, B));
     EXPECT_EQ("{\n\tA  B\n}", toString(p));
     EXPECT_EQ("{A->{},B->{}}", toString(p.solve()));
     // add another constraints
     std::set<int> s = {1, 2};
     p.add(sub(s, A));
     EXPECT_EQ("{\n\tA  B,\n\t{1,2}  A\n}", toString(p));
     EXPECT_EQ("{A->{1,2},B->{1,2}}", toString(p.solve()));
     // and one more
     std::set<int> s2 = {3};
     p.add(sub(s2, B));
     EXPECT_EQ("{\n\tA  B,\n\t{1,2}  A,\n\t{3}  B\n}", toString(p));
     EXPECT_EQ("{A->{1,2},B->{1,2,3}}", toString(p.solve()));
 }
TEST() [3/30]
souffle::ast::test::TEST (RuleBody , Basic)
Definition at line 34 of file ast_parser_utils_test.cpp.
References souffle::RuleBody::atom(), EXPECT_EQ, and souffle::toString().
                       {
     RuleBody body;
     // start with an A
     auto a = RuleBody::atom(mk<Atom>("A"));
     EXPECT_EQ("A()", toString(a));
     a.conjunct(RuleBody::atom(mk<Atom>("B")));
     EXPECT_EQ("A(),B()", toString(a));
     a.disjunct(RuleBody::atom(mk<Atom>("C")));
     EXPECT_EQ("A(),B();C()", toString(a));
 }
TEST() [4/30]
souffle::ast::test::TEST (RuleBody , Negation)
Definition at line 48 of file ast_parser_utils_test.cpp.
References souffle::RuleBody::atom(), souffle::RuleBody::conjunct(), souffle::RuleBody::disjunct(), EXPECT_EQ, souffle::RuleBody::getFalse(), souffle::RuleBody::getTrue(), souffle::RuleBody::negated(), and souffle::toString().
{
     RuleBody body = RuleBody::getTrue();
     RuleBody AB = RuleBody::getTrue();
     AB.conjunct(RuleBody::atom(mk<Atom>("A")));
     AB.conjunct(RuleBody::atom(mk<Atom>("B")));
     EXPECT_EQ("A(),B()", toString(AB));
     RuleBody CD = RuleBody::getTrue();
     CD.conjunct(RuleBody::atom(mk<Atom>("C")));
     CD.conjunct(RuleBody::atom(mk<Atom>("D")));
     EXPECT_EQ("C(),D()", toString(CD));
     RuleBody EF = RuleBody::getTrue();
     EF.conjunct(RuleBody::atom(mk<Atom>("E")));
     EF.conjunct(RuleBody::atom(mk<Atom>("F")));
     EXPECT_EQ("E(),F()", toString(EF));
     RuleBody full = RuleBody::getFalse();
     full.disjunct(std::move(AB));
     full.disjunct(std::move(CD));
     full.disjunct(std::move(EF));
     EXPECT_EQ("A(),B();C(),D();E(),F()", toString(full));
     full = full.negated();
     EXPECT_EQ(
             "!A(),!C(),!E();!A(),!C(),!F();!A(),!D(),!E();!A(),!D(),!F();!B(),!C(),!E();!B(),!C(),!F();!B(),!"
             "D(),!E();!B(),!D(),!F()",
             toString(full));
     full = full.negated();
     EXPECT_EQ("A(),B();C(),D();E(),F()", toString(full));
 }
TEST() [5/30]
souffle::ast::test::TEST (TypeSystem , isNumberType)
Definition at line 49 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_FALSE, EXPECT_TRUE, souffle::ast::analysis::TypeEnvironment::getType(), souffle::ast::analysis::isOfKind(), souffle::Signed, souffle::Symbol, and souffle::toVector().
{
     TypeEnvironment env;
     const analysis::Type& N = env.getType("number");
     const analysis::Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const analysis::Type& B = env.createType<SubsetType>("B", env.getType("number"));
     const analysis::Type& C = env.createType<SubsetType>("C", env.getType("symbol"));
     EXPECT_TRUE(isOfKind(N, TypeAttribute::Signed));
     EXPECT_TRUE(isOfKind(A, TypeAttribute::Signed));
     EXPECT_TRUE(isOfKind(B, TypeAttribute::Signed));
     EXPECT_TRUE(isOfKind(C, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(N, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(A, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(B, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(C, TypeAttribute::Signed));
     // check the union type
     {
         const analysis::Type& U = env.createType<UnionType>("U", toVector(&A, &B));
         EXPECT_TRUE(isOfKind(U, TypeAttribute::Signed));
         EXPECT_FALSE(isOfKind(U, TypeAttribute::Symbol));
         const analysis::Type& U2 = env.createType<UnionType>("U2", toVector(&A, &B, &C));
         EXPECT_FALSE(isOfKind(U2, TypeAttribute::Signed));
         EXPECT_FALSE(isOfKind(U2, TypeAttribute::Symbol));
     }
     {
         const analysis::Type& U3 = env.createType<UnionType>("U3", toVector(&A));
         EXPECT_TRUE(isOfKind(U3, TypeAttribute::Signed));
     }
 }
TEST() [6/30]
souffle::ast::test::TEST (AstUtils , Grounded)
Definition at line 49 of file ast_utils_test.cpp.
References b, souffle::EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::ast::analysis::getGroundedTerms(), and souffle::toString().
{
     // create an example clause:
     auto clause = mk<Clause>();
     // something like:
     //   r(X,Y,Z) :- a(X), X = Y, !b(Z).
     // r(X,Y,Z)
     auto* head = new Atom("r");
     head->addArgument(Own<Argument>(new Variable("X")));
     head->addArgument(Own<Argument>(new Variable("Y")));
     head->addArgument(Own<Argument>(new Variable("Z")));
     clause->setHead(Own<Atom>(head));
     // a(X)
     auto* a = new Atom("a");
     a->addArgument(Own<Argument>(new Variable("X")));
     clause->addToBody(Own<Literal>(a));
     // X = Y
     Literal* e1 = new BinaryConstraint(
             BinaryConstraintOp::EQ, Own<Argument>(new Variable("X")), Own<Argument>(new Variable("Y")));
     clause->addToBody(Own<Literal>(e1));
     // !b(Z)
     auto* b = new Atom("b");
     b->addArgument(Own<Argument>(new Variable("Z")));
     auto* neg = new Negation(Own<Atom>(b));
     clause->addToBody(Own<Literal>(neg));
     // check construction
     EXPECT_EQ("r(X,Y,Z) :- \n   a(X),\n   X = Y,\n   !b(Z).", toString(*clause));
     auto program = mk<Program>();
     program->addClause(std::move(clause));
     DebugReport dbgReport;
     ErrorReport errReport;
     TranslationUnit tu{std::move(program), errReport, dbgReport};
     // obtain groundness
     auto isGrounded = analysis::getGroundedTerms(tu, *tu.getProgram().getClauses()[0]);
     auto args = head->getArguments();
     // check selected sub-terms
     EXPECT_TRUE(isGrounded[args[0]]);   // X
     EXPECT_TRUE(isGrounded[args[1]]);   // Y
     EXPECT_FALSE(isGrounded[args[2]]);  // Z
 }
TEST() [7/30]
souffle::ast::test::TEST (Program , Parse)
Definition at line 58 of file ast_program_test.cpp.
References d, e, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::ast::getRelation(), and souffle::ParserDriver::parseTranslationUnit().
                      {
     ErrorReport e;
     DebugReport d;
     // check the empty program
     Own<TranslationUnit> empty = ParserDriver::parseTranslationUnit("", e, d);
     EXPECT_TRUE(empty->getProgram().getTypes().empty());
     EXPECT_TRUE(empty->getProgram().getRelations().empty());
     // check something simple
     Own<TranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                    .type Node <: symbol
                    .decl e ( a : Node , b : Node )
                    .decl r ( from : Node , to : Node )
                    r(X,Y) :- e(X,Y).
                    r(X,Z) :- r(X,Y), r(Y,Z).
             )",
             e, d);
     auto& prog = tu->getProgram();
     std::cout << prog << "\n";
     EXPECT_EQ(1, prog.getTypes().size());
     EXPECT_EQ(2, prog.getRelations().size());
     EXPECT_TRUE(getRelation(prog, "e"));
     EXPECT_TRUE(getRelation(prog, "r"));
     EXPECT_FALSE(getRelation(prog, "n"));
 }
TEST() [8/30]
souffle::ast::test::TEST (AstPrint , NilConstant)
Definition at line 66 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = mk<NilConstant>();
     auto tu1 = makeATU();
     tu1->getProgram().addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [9/30]
souffle::ast::test::TEST (AstPrint , NumberConstant)
Definition at line 75 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = mk<NumericConstant>("2");
     EXPECT_EQ(testArgument, testArgument);
     auto tu1 = makeATU();
     tu1->getProgram().addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [10/30]
souffle::ast::test::TEST (RuleBody , ClauseBodyExtraction)
Definition at line 82 of file ast_parser_utils_test.cpp.
References souffle::RuleBody::atom(), souffle::RuleBody::conjunct(), souffle::RuleBody::disjunct(), EXPECT_EQ, souffle::RuleBody::getFalse(), souffle::RuleBody::getTrue(), souffle::RuleBody::toClauseBodies(), and souffle::toString().
{
     RuleBody body = RuleBody::getTrue();
     RuleBody AB = RuleBody::getTrue();
     AB.conjunct(RuleBody::atom(mk<Atom>("A")));
     AB.conjunct(RuleBody::atom(mk<Atom>("B")));
     EXPECT_EQ("A(),B()", toString(AB));
     RuleBody CD = RuleBody::getTrue();
     CD.conjunct(RuleBody::atom(mk<Atom>("C")));
     CD.conjunct(RuleBody::atom(mk<Atom>("D")));
     EXPECT_EQ("C(),D()", toString(CD));
     RuleBody EF = RuleBody::getTrue();
     EF.conjunct(RuleBody::atom(mk<Atom>("E")));
     EF.conjunct(RuleBody::atom(mk<Atom>("F")));
     EXPECT_EQ("E(),F()", toString(EF));
     RuleBody full = RuleBody::getFalse();
     full.disjunct(std::move(AB));
     full.disjunct(std::move(CD));
     full.disjunct(std::move(EF));
     EXPECT_EQ("A(),B();C(),D();E(),F()", toString(full));
     // extract the clause
     auto list = full.toClauseBodies();
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(" :- \n   A(),\n   B().", toString(*list[0]));
     EXPECT_EQ(" :- \n   C(),\n   D().", toString(*list[1]));
     EXPECT_EQ(" :- \n   E(),\n   F().", toString(*list[2]));
 }
TEST() [11/30]
souffle::ast::test::TEST (AstPrint , StringConstant)
Definition at line 86 of file ast_print_test.cpp.
References d, e, EXPECT_EQ, makeClauseA(), makePrintedATU(), and souffle::ParserDriver::parseTranslationUnit().
{
     ErrorReport e;
     DebugReport d;
     auto testArgument = mk<StringConstant>("test string");
     auto tu1 = ParserDriver::parseTranslationUnit(".decl A,B,C(x:number)", e, d);
     tu1->getProgram().addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [12/30]
souffle::ast::test::TEST (TypeSystem , isSubtypeOf_Basic)
Definition at line 88 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_PRED2, souffle::ast::analysis::TypeEnvironment::getType(), isNotSubtypeOf(), souffle::ast::analysis::isSubtypeOf(), S, and souffle::toVector().
{
     TypeEnvironment env;
     // start with the two predefined types
     const analysis::Type& N = env.getType("number");
     const analysis::Type& S = env.getType("symbol");
     EXPECT_PRED2(isSubtypeOf, N, N);
     EXPECT_PRED2(isSubtypeOf, S, S);
     EXPECT_PRED2(isNotSubtypeOf, N, S);
     EXPECT_PRED2(isNotSubtypeOf, S, N);
     // check primitive type
     const analysis::Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const analysis::Type& B = env.createType<SubsetType>("B", env.getType("number"));
     EXPECT_PRED2(isSubtypeOf, A, A);
     EXPECT_PRED2(isSubtypeOf, B, B);
     EXPECT_PRED2(isNotSubtypeOf, A, B);
     EXPECT_PRED2(isNotSubtypeOf, B, A);
     EXPECT_PRED2(isSubtypeOf, A, N);
     EXPECT_PRED2(isSubtypeOf, B, N);
     EXPECT_PRED2(isNotSubtypeOf, A, S);
     EXPECT_PRED2(isNotSubtypeOf, B, S);
     // check union types
     const analysis::Type& U = env.createType<UnionType>("U", toVector(&A, &B));
     EXPECT_PRED2(isSubtypeOf, U, U);
     EXPECT_PRED2(isSubtypeOf, A, U);
     EXPECT_PRED2(isSubtypeOf, B, U);
     EXPECT_PRED2(isSubtypeOf, U, N);
     EXPECT_PRED2(isNotSubtypeOf, U, A);
     EXPECT_PRED2(isNotSubtypeOf, U, B);
     EXPECT_PRED2(isNotSubtypeOf, N, U);
     auto& V = env.createType<UnionType>("V", toVector(&A, &B, &U));
     EXPECT_PRED2(isSubtypeOf, V, U);
     EXPECT_PRED2(isSubtypeOf, U, V);
 }
TEST() [13/30]
souffle::ast::test::TEST (AstPrint , Variable)
Definition at line 97 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = mk<Variable>("testVar");
     auto tu1 = makeATU();
     tu1->getProgram().addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [14/30]
souffle::ast::test::TEST (AstUtils , GroundedRecords)
Definition at line 98 of file ast_utils_test.cpp.
References d, e, EXPECT_EQ, EXPECT_TRUE, souffle::ast::Atom::getArguments(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::getClauses(), souffle::ast::analysis::getGroundedTerms(), souffle::ast::Clause::getHead(), souffle::ParserDriver::parseTranslationUnit(), and souffle::toString().
{
     ErrorReport e;
     DebugReport d;
     Own<TranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                  .type N <: symbol
                  .type R = [ a : N, B : N ]
                  .decl r ( r : R )
                  .decl s ( r : N )
                  s(x) :- r([x,y]).
             )",
             e, d);
     Program& program = tu->getProgram();
     Clause* clause = getClauses(program, "s")[0];
     // check construction
     EXPECT_EQ("s(x) :- \n   r([x,y]).", toString(*clause));
     // obtain groundness
     auto isGrounded = analysis::getGroundedTerms(*tu, *clause);
     const Atom* s = clause->getHead();
     const auto* r = dynamic_cast<const Atom*>(clause->getBodyLiterals()[0]);
     EXPECT_TRUE(s);
     EXPECT_TRUE(r);
     // check selected sub-terms
     EXPECT_TRUE(isGrounded[s->getArguments()[0]]);
     EXPECT_TRUE(isGrounded[r->getArguments()[0]]);
 }
TEST() [15/30]
souffle::ast::test::TEST (AstPrint , UnnamedVariable)
Definition at line 106 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = mk<UnnamedVariable>();
     auto tu1 = makeATU();
     tu1->getProgram().addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [16/30]
souffle::ast::test::TEST (AstPrint , Counter)
Definition at line 115 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = mk<Counter>();
     auto tu1 = makeATU();
     tu1->getProgram().addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [17/30]
souffle::ast::test::TEST (Program , RemoveClause)
test removeClause, addRelation and removeRelation
Definition at line 124 of file ast_program_test.cpp.
                           : symbol
                  .type B <: symbol
                  .type U = A | B
                  .decl a ( x : A )
                  .decl b ( x : B )
                  .decl u ( x : U )
                  a(X) :- u(X).
                  b(X) :- u(X).
                  u(X) :- u(X).
                  a(X) :- b(X).
TEST() [18/30]
souffle::ast::test::TEST (AstPrint , AggregatorMin)
Definition at line 124 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), makePrintedATU(), and souffle::MIN.
{
     auto atom = mk<Atom>("B");
     atom->addArgument(mk<Variable>("x"));
     auto min = mk<Aggregator>(AggregateOp::MIN, mk<Variable>("x"));
     VecOwn<Literal> body;
     body.push_back(mk<Atom>("B"));
     min->setBody(std::move(body));
     auto tu1 = makeATU();
     auto& prog1 = tu1->getProgram();
     prog1.addClause(makeClauseA(std::move(min)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [19/30]
souffle::ast::test::TEST (AstUtils , ReorderClauseAtoms)
Definition at line 135 of file ast_utils_test.cpp.
References clauses, d, e, EXPECT_EQ, EXPECT_NE, souffle::ast::getClauses(), souffle::ast::getRelation(), souffle::ast::Program::getRelations(), souffle::ParserDriver::parseTranslationUnit(), souffle::ast::reorderAtoms(), and souffle::toString().
{
     ErrorReport e;
     DebugReport d;
     Own<TranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .decl a,b,c,d,e(x:number)
                 a(x) :- b(x), c(x), 1 != 2, d(y), !e(z), c(z), e(x).
                 .output a()
             )",
             e, d);
     Program& program = tu->getProgram();
     EXPECT_EQ(5, program.getRelations().size());
     Relation* a = getRelation(program, "a");
     EXPECT_NE(a, nullptr);
     const auto& clauses = getClauses(program, *a);
     EXPECT_EQ(1, clauses.size());
     Clause* clause = clauses[0];
     EXPECT_EQ("a(x) :- \n   b(x),\n   c(x),\n   1 != 2,\n   d(y),\n   !e(z),\n   c(z),\n   e(x).",
             toString(*clause));
     // Check trivial permutation
     Own<Clause> reorderedClause0 =
             Own<Clause>(reorderAtoms(clause, std::vector<unsigned int>({0, 1, 2, 3, 4})));
     EXPECT_EQ("a(x) :- \n   b(x),\n   c(x),\n   1 != 2,\n   d(y),\n   !e(z),\n   c(z),\n   e(x).",
             toString(*reorderedClause0));
     // Check more complex permutation
     Own<Clause> reorderedClause1 =
             Own<Clause>(reorderAtoms(clause, std::vector<unsigned int>({2, 3, 4, 1, 0})));
     EXPECT_EQ("a(x) :- \n   d(y),\n   c(z),\n   1 != 2,\n   e(x),\n   !e(z),\n   c(x),\n   b(x).",
             toString(*reorderedClause1));
 }
TEST() [20/30]
souffle::ast::test::TEST (TypeSystem , isSubtypeOf_Records)
Definition at line 138 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_FALSE, souffle::ast::analysis::TypeEnvironment::getType(), souffle::ast::analysis::isSubtypeOf(), souffle::ast::analysis::RecordType::setFields(), and souffle::toVector().
{
     TypeEnvironment env;
     const analysis::Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const analysis::Type& B = env.createType<SubsetType>("B", env.getType("number"));
     auto& R1 = env.createType<RecordType>("R1");
     auto& R2 = env.createType<RecordType>("R2");
     EXPECT_FALSE(isSubtypeOf(R1, R2));
     EXPECT_FALSE(isSubtypeOf(R2, R1));
     R1.setFields(toVector(&A));
     R2.setFields(toVector(&B));
     EXPECT_FALSE(isSubtypeOf(R1, R2));
     EXPECT_FALSE(isSubtypeOf(R2, R1));
 }
TEST() [21/30]
souffle::ast::test::TEST (Program , AppendRelation)
Definition at line 140 of file ast_program_test.cpp.
                           : symbol
                  .type B <: number
                  .type U = B
                  .decl a ( x : A )
TEST() [22/30]
souffle::ast::test::TEST (AstPrint , AggregatorMax)
Definition at line 141 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), makePrintedATU(), and souffle::MAX.
{
     auto atom = mk<Atom>("B");
     atom->addArgument(mk<Variable>("x"));
     auto max = mk<Aggregator>(AggregateOp::MAX, mk<Variable>("x"));
     VecOwn<Literal> body;
     body.push_back(std::move(atom));
     max->setBody(std::move(body));
     auto tu1 = makeATU();
     auto& prog1 = tu1->getProgram();
     prog1.addClause(makeClauseA(std::move(max)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [23/30]
souffle::ast::test::TEST (Program , RemoveRelation)
Definition at line 151 of file ast_program_test.cpp.
                              : U )
                  a(X) :- X < 10.
                  b(X) :- X < 10.
                  u(X) :- X < 10.
TEST() [24/30]
souffle::ast::test::TEST (AstPrint , AggregatorCount)
Definition at line 157 of file ast_print_test.cpp.
References souffle::test::count(), souffle::COUNT, EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto atom = mk<Atom>("B");
     atom->addArgument(mk<Variable>("x"));
     auto count = mk<Aggregator>(AggregateOp::COUNT);
     VecOwn<Literal> body;
     body.push_back(std::move(atom));
     count->setBody(std::move(body));
     auto tu1 = makeATU();
     auto& prog1 = tu1->getProgram();
     prog1.addClause(makeClauseA(std::move(count)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [25/30]
souffle::ast::test::TEST (TypeSystem , GreatestCommonSubtype)
Definition at line 157 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_EQ, souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::TypeEnvironment::getType(), S, souffle::ast::analysis::UnionType::setElements(), souffle::toString(), and souffle::toVector().
{
     TypeEnvironment env;
     const analysis::Type& N = env.getType("number");
     const analysis::Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const analysis::Type& B = env.createType<SubsetType>("B", env.getType("number"));
     const analysis::Type& C = env.createType<SubsetType>("C", env.getType("symbol"));
     EXPECT_EQ("{number}", toString(getGreatestCommonSubtypes(N, N)));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, A)));
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(B, B)));
     EXPECT_EQ("{C}", toString(getGreatestCommonSubtypes(C, C)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, B)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, C)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(B, C)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, B, C)));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, N)));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(N, A)));
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(B, N)));
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(N, B)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(C, N)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(N, C)));
     // // bring in unions
     auto& U = env.createType<UnionType>("U");
     auto& S = env.createType<UnionType>("S");
     U.setElements(toVector(&A));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(U, S)));
     S.setElements(toVector(&A));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, S)));
     U.setElements(toVector(&A, &B));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(U, S)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(U, S, N)));
     S.setElements(toVector(&A, &B));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, S)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, S, N)));
     // bring in a union of unions
     auto& R = env.createType<UnionType>("R");
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(U, R)));
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(S, R)));
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(U, R, N)));
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(S, R, N)));
     R.setElements(toVector(static_cast<const analysis::Type*>(&U)));  // R = U = S
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R, N)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R, N)));
     R.setElements(toVector(static_cast<const analysis::Type*>(&U), static_cast<const analysis::Type*>(&S)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R, N)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R, N)));
 }
TEST() [26/30]
souffle::ast::test::TEST (AstPrint , AggregatorSum)
Definition at line 173 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), makePrintedATU(), and souffle::SUM.
{
     auto atom = mk<Atom>("B");
     atom->addArgument(mk<Variable>("x"));
     auto sum = mk<Aggregator>(AggregateOp::SUM, mk<Variable>("x"));
     VecOwn<Literal> body;
     body.push_back(std::move(atom));
     sum->setBody(std::move(body));
     auto tu1 = makeATU();
     auto& prog1 = tu1->getProgram();
     prog1.addClause(makeClauseA(std::move(sum)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(tu1->getProgram(), tu2->getProgram());
 }
TEST() [27/30]
souffle::ast::test::TEST (TypeSystem , complexSubsetTypes)
Definition at line 232 of file type_system_test.cpp.
References base, souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_EQ, EXPECT_PRED2, souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::TypeEnvironment::getType(), i, souffle::ast::analysis::isSubtypeOf(), and souffle::toString().
{
     TypeEnvironment env;
     auto& A = env.createType<SubsetType>("A", env.getType("number"));
     auto& BfromA = env.createType<SubsetType>("B", A);
     auto& CfromA = env.createType<SubsetType>("C", A);
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(A, BfromA)));
     EXPECT_EQ("{C}", toString(getGreatestCommonSubtypes(A, CfromA)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, BfromA, CfromA)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(BfromA, CfromA)));
     auto* base = &env.createType<SubsetType>("B0", BfromA);
     for (size_t i = 1; i <= 10; ++i) {
         base = &env.createType<SubsetType>("B" + std::to_string(i), *base);
         EXPECT_PRED2(isSubtypeOf, *base, A);
     }
 }
TEST() [28/30]
souffle::ast::test::TEST (TypeSystem , RecordSubsets)
Definition at line 251 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_EQ, EXPECT_PRED2, souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::isSubtypeOf(), and souffle::toString().
{
     TypeEnvironment env;
     auto& R = env.createType<RecordType>("R");
     auto& A = env.createType<SubsetType>("A", R);
     EXPECT_PRED2(isSubtypeOf, A, R);
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, R)));
 }
TEST() [29/30]
souffle::ast::test::TEST (TypeSystem , EquivTypes)
Definition at line 262 of file type_system_test.cpp.
References souffle::ast::analysis::areEquivalentTypes(), souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_TRUE, souffle::ast::analysis::TypeEnvironment::getType(), and souffle::toVector().
{
     TypeEnvironment env;
     auto& A = env.createType<SubsetType>("A", env.getType("number"));
     auto& U = env.createType<UnionType>("U", toVector(dynamic_cast<const analysis::Type*>(&A)));
     EXPECT_TRUE(areEquivalentTypes(A, U));
 }
TEST() [30/30]
souffle::ast::test::TEST (TypeSystem , AlgebraicDataType)
Definition at line 271 of file type_system_test.cpp.
References souffle::ast::analysis::TypeEnvironment::createType(), EXPECT_EQ, EXPECT_TRUE, souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::isSubtypeOf(), and souffle::toString().
{
     TypeEnvironment env;
     auto& A = env.createType<AlgebraicDataType>("A");
     EXPECT_TRUE(isSubtypeOf(A, A));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, A)));
 }
TESTASTCLONEANDEQUAL() [1/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (Program , R"(.decl r(a:number,b:number,c:number,d:number) .decl s(x:symbol) .decl a(x:number) s("xxx"). r(X,Y,Z,W) :- a(X), 10 = Y, Y = Z, 8 + W = 12 + 14. r(z + 2, x, y, a) :- s(b), b = to_string(a), z = x, a = y, x = 2, a = 2 + x.)")
TESTASTCLONEANDEQUAL() [2/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (Record , R"(.type N <: symbol .type R = [ a : N, B : N ] .decl r (r : R) .decl s (r : N) s(x) :- r([x,y]).)")
TESTASTCLONEANDEQUAL() [3/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (SimpleTypes , R"(.type A <: symbol .type B <: symbol .type U = A | B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- u(X). b(X) :- u(X). u(X) :- u(X). a(X) :- b(X). a(X) :- b(Y).)")
TESTASTCLONEANDEQUAL() [4/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (ComplexTypes , R"(.type A <: symbol .type B <: number .type U = B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- X < 10. b(X) :- X < 10. u(X) :- X < 10.)")
TESTASTCLONEANDEQUAL() [5/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (ChainedTypes , R"(.type D <: symbol .type C = D .type B = C .type A = B .decl R1(x:A,y:B) .decl R2(x:C,y:D) .decl R4(x:A) output R4(x) :- R2(x,x),R1(x,x).)")
TESTASTCLONEANDEQUAL() [6/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (NestedAggregates , R"(.type D <: symbol .decl r(x:D) r(x) :- r(y), x=cat(cat(x,x),x).)")
TESTASTCLONEANDEQUAL() [7/7]
souffle::ast::test::TESTASTCLONEANDEQUAL (RelationCopies , R"(.type D = number .decl a(a:D,b:D) .decl b(a:D,b:D) .decl c(a:D,b:D) .decl d(a:D,b:D) a(1,2). b(x,y) :- a(x,y). c(x,y) :- b(x,y). d(x,y) :- b(x,y), c(y,x).)")