souffle: souffle::ram::test Namespace Reference
souffle::ram::test Namespace Reference
Functions
RamDomain evalBinary (FunctorOp functor, RamDomain arg1, RamDomain arg2)
Evaluate a binary operator.
RamDomain evalExpression (Own< Expression > expression, SymbolTable &symTab)
Function to evaluate a single Expression.
RamDomain evalExpression (Own< Expression > expression)
Function to evaluate a single Expression.
RamDomain evalMultiArg (FunctorOp functor, VecOwn< Expression > args, SymbolTable &symTab)
RamDomain evalMultiArg (FunctorOp functor, VecOwn< Expression > args)
RamDomain evalUnary (FunctorOp functor, RamDomain arg1)
Evaluate a single argument expression.
TEST (Relation, CloneAndEquals)
TEST (randomConversions, RamSigned)
TEST (RelationRepresentation, CloneAndEquals)
TEST (IntrinsicOperator, CloneAndEquals)
TEST (True, CloneAndEquals)
TEST (randomConversions, RamUnsigned)
TEST (False, CloneAndEquals)
TEST (randomConversions, RamFloat)
TEST (RamScan, CloneAndEquals)
TEST (IO1, CloneAndEquals)
TEST (Conjunction, CloneAndEquals)
TEST (UserDefinedOperator, CloneAndEquals)
TEST (RamParallelScan, CloneAndEquals)
TEST (Clear, CloneAndEquals)
TEST (Extend, CloneAndEquals)
TEST (TupleElement, CloneAndEquals)
TEST (RamIndexScan, CloneAndEquals)
TEST (IO_store, FloatSimple)
TEST (Negation, CloneAndEquals)
TEST (Swap, CloneAndEquals)
TEST (SignedConstant, CloneAndEquals)
TEST (SignedConstant, ArithmeticEvaluation)
TEST (Unary, Neg)
TEST (Constraint, CloneAndEquals)
TEST (IO_store, Signed)
TEST (AutoIncrement, CloneAndEquals)
TEST (Unary, FloatNeg)
TEST (Query, CloneAndEquals)
TEST (Unary, BinaryNot)
TEST (UndefValue, CloneAndEquals)
TEST (RamParallelIndexScan, CloneAndEquals)
TEST (Unary, UnsignedBinaryNot)
TEST (PackRecord, CloneAndEquals)
TEST (Unary, LogicalNeg)
TEST (ExistenceCheck, CloneAndEquals)
TEST (IO_store, Float)
TEST (Unary, UnsignedLogicalNeg)
TEST (Unary, SingedTpUnsigned)
TEST (Unary, UnsignedToSigned)
TEST (RamChoice, CloneAndEquals)
TEST (Unary, SignedToFloat)
TEST (Sequence, CloneAndEquals)
TEST (Unary, FloatToSigned)
TEST (RamProvenanceExistCheck, CloneAndEquals)
TEST (IO_store, Unsigned)
TEST (RamSubrountineArgument, CloneAndEquals)
TEST (Unary, UnsignedToFloat)
TEST (Unary, FloatToUnsigned)
TEST (RamParallelChoice, CloneAndEquals)
TEST (Binary, SignedAdd)
TEST (Parallel, CloneAndEquals)
TEST (IO_store, SignedChangedDelimiter)
TEST (Binary, UnsignedAdd)
TEST (EmptinessCheck, CloneAndEquals)
TEST (Binary, FloatAdd)
TEST (Binary, SignedSub)
TEST (RamIndexChoice, CloneAndEquals)
TEST (Loop, CloneAndEquals)
TEST (Binary, UnsignedSub)
TEST (Binary, FloatSub)
TEST (RamiParallelIndexChoice, CloneAndEquals)
TEST (Binary, SignedMul)
TEST (Exit, CloneAndEquals)
TEST (IO_store, MixedTypes)
TEST (Binary, UnsignedMul)
TEST (LogRelationTimer, CloneAndEquals)
TEST (Binary, FloatMul)
TEST (LogTimer, CloneAndEquals)
TEST (RamAggregate, CloneAndEquals)
TEST (Binary, SignedDiv)
TEST (Binary, UnsignedDiv)
TEST (DebugInfo, CloneAndEquals)
TEST (RamIndexAggregate, CloneAndEquals)
TEST (Binary, FloatDiv)
TEST (IO_load, Signed)
TEST (Binary, SignedExp)
TEST (RamUnpackedRecord, CloneAndEquals)
TEST (Binary, UnsignedExp)
TEST (Binary, FloatExp)
TEST (LogSize, CloneAndEquals)
TEST (RamFilter, CloneAndEquals)
TEST (Binary, SignedMod)
TEST (IO_load, Float)
TEST (Binary, UnsignedMod)
TEST (RamBreak, CloneAndEquals)
TEST (Binary, SignedBinaryAnd)
TEST (Binary, UnsignedBinaryAnd)
TEST (RamProject, CloneAndEquals)
TEST (Binary, SignedBinaryOr)
TEST (RamSubroutineReturn, CloneAndEquals)
TEST (Binary, UnsignedBinaryOr)
TEST (IO_load, Unsigned)
TEST (Binary, SignedBinaryXor)
TEST (Binary, UnsignedBinaryXor)
TEST (Binary, SignedLogicalAnd)
TEST (Binary, UnsignedLogicalAnd)
TEST (IO_load, MixedTypesLoad)
TEST (Binary, SignedLogicalOr)
TEST (Binary, UnsignedLogicalOr)
TEST (MultiArg, Max)
TEST (MultiArg, UnsignedMax)
TEST (MultiArg, FloatMax)
TEST (MultiArg, SymbolMax)
TEST (MultiArg, Min)
TEST (MultiArg, UnsignedMin)
TEST (MultiArg, FloatMin)
TEST (MultiArg, SymbolMin)
const std::string testInterpreterStore (std::vector< std::string > attribs, std::vector< std::string > attribsTypes, VecOwn< Expression > exprs)
Function Documentation
evalBinary()
RamDomain souffle::ram::test::evalBinary (FunctorOp functor, RamDomain arg1, RamDomain arg2)
Evaluate a binary operator.
Definition at line 104 of file ram_arithmetic_test.cpp.
References evalMultiArg().
Referenced by TEST().
{
     VecOwn<Expression> args;
     args.push_back(mk<SignedConstant>(arg1));
     args.push_back(mk<SignedConstant>(arg2));
     return evalMultiArg(functor, std::move(args));
 }
evalExpression() [1/2]
RamDomain souffle::ram::test::evalExpression (Own< Expression > expression, SymbolTable & symTab)
Function to evaluate a single Expression.
Definition at line 51 of file ram_arithmetic_test.cpp.
References souffle::Global::config().
Referenced by evalExpression(), evalMultiArg(), and TEST().
{
     // Set up Program and translation unit
     VecOwn<Expression> returnValues;
     returnValues.emplace_back(std::move(expression));
     Global::config().set("jobs", "1");
     Own<Statement> query = mk<Query>(mk<SubroutineReturn>(std::move(returnValues)));
     std::map<std::string, Own<Statement>> subs;
     subs.insert(std::make_pair("test", std::move(query)));
     VecOwn<Relation> rels;
     Own<Program> prog = mk<Program>(std::move(rels), mk<Sequence>(), std::move(subs));
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::string name("test");
     std::vector<RamDomain> ret;
     interpreter->executeSubroutine(name, {}, ret);
     return ret.at(0);
 }
evalExpression() [2/2]
RamDomain souffle::ram::test::evalExpression (Own< Expression > expression)
Function to evaluate a single Expression.
Definition at line 81 of file ram_arithmetic_test.cpp.
References evalExpression().
{
     SymbolTable symTab;
     return evalExpression(std::move(expression), symTab);
 }
evalMultiArg() [1/2]
RamDomain souffle::ram::test::evalMultiArg (FunctorOp functor, VecOwn< Expression > args, SymbolTable & symTab)
Definition at line 86 of file ram_arithmetic_test.cpp.
References evalExpression().
Referenced by evalBinary(), evalMultiArg(), evalUnary(), and TEST().
{
     return evalExpression(mk<IntrinsicOperator>(functor, std::move(args)), symTab);
 }
evalMultiArg() [2/2]
RamDomain souffle::ram::test::evalMultiArg (FunctorOp functor, VecOwn< Expression > args)
Definition at line 90 of file ram_arithmetic_test.cpp.
References evalMultiArg().
{
     SymbolTable symTab;
     return evalMultiArg(functor, std::move(args), symTab);
 }
evalUnary()
RamDomain souffle::ram::test::evalUnary (FunctorOp functor, RamDomain arg1)
Evaluate a single argument expression.
Definition at line 96 of file ram_arithmetic_test.cpp.
References evalMultiArg().
Referenced by TEST().
{
     VecOwn<Expression> args;
     args.push_back(mk<SignedConstant>(arg1));
     return evalMultiArg(functor, std::move(args));
 }
TEST() [1/107]
souffle::ram::test::TEST (Relation , CloneAndEquals)
Definition at line 27 of file ram_relation_equal_clone_test.cpp.
References b, souffle::ram::Relation::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation a("A", 4, 1, {"a", "b", "c", "d"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     Relation b("A", 4, 1, {"a", "b", "c", "d"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Relation* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [2/107]
souffle::ram::test::TEST (randomConversions , RamSigned)
Definition at line 27 of file ram_type_conversion_test.cpp.
References EXPECT_EQ, i, NUMBER_OF_CONVERSION_TESTS, and souffle::ramBitCast().
{
     std::mt19937 randomGenerator(3);
     std::uniform_int_distribution<RamDomain> dist(-100, 100);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
         RamDomain randomNumber = dist(randomGenerator);
         // Test float casting
         EXPECT_EQ(randomNumber, ramBitCast(ramBitCast<RamFloat>(randomNumber)));
         // Test signed casting
         EXPECT_EQ(randomNumber, ramBitCast(ramBitCast<RamUnsigned>(randomNumber)));
     }
 }
TEST() [3/107]
souffle::ram::test::TEST (RelationRepresentation , CloneAndEquals)
Definition at line 39 of file ram_relation_equal_clone_test.cpp.
References b, souffle::ram::RelationReference::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     RelationReference a(&A);
     RelationReference b(&A);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RelationReference* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [4/107]
souffle::ram::test::TEST (IntrinsicOperator , CloneAndEquals)
Definition at line 39 of file ram_expression_equal_clone_test.cpp.
References souffle::ADD, b, souffle::ram::IntrinsicOperator::clone(), d, e, EXPECT_EQ, EXPECT_NE, and souffle::NEG.
{
     // ADD(number(1), number(2))
     VecOwn<Expression> a_args;
     a_args.emplace_back(new SignedConstant(1));
     a_args.emplace_back(new SignedConstant(2));
     IntrinsicOperator a(FunctorOp::ADD, std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new SignedConstant(1));
     b_args.emplace_back(new SignedConstant(2));
     IntrinsicOperator b(FunctorOp::ADD, std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     IntrinsicOperator* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
     // NEG(number(1))
     VecOwn<Expression> d_args;
     d_args.emplace_back(new SignedConstant(1));
     IntrinsicOperator d(FunctorOp::NEG, std::move(d_args));
     VecOwn<Expression> e_args;
     e_args.emplace_back(new SignedConstant(1));
     IntrinsicOperator e(FunctorOp::NEG, std::move(e_args));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     IntrinsicOperator* dClone = d.clone();
     EXPECT_EQ(d, *dClone);
     EXPECT_NE(&d, dClone);
     delete dClone;
 }
TEST() [5/107]
souffle::ram::test::TEST (True , CloneAndEquals)
Definition at line 42 of file ram_condition_equal_clone_test.cpp.
References b, souffle::ram::True::clone(), EXPECT_EQ, and EXPECT_NE.
{
     True a;
     True b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     True* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [6/107]
souffle::ram::test::TEST (randomConversions , RamUnsigned)
Definition at line 42 of file ram_type_conversion_test.cpp.
References EXPECT_EQ, i, and NUMBER_OF_CONVERSION_TESTS.
{
     std::mt19937 randomGenerator(3);
     std::uniform_int_distribution<RamUnsigned> dist(0, 1000);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
         RamUnsigned randomNumber = dist(randomGenerator);
         // Test float casting
         EXPECT_EQ(randomNumber, ramBitCast<RamUnsigned>(ramBitCast<RamFloat>(randomNumber)));
         // Test signed casting
         EXPECT_EQ(randomNumber, ramBitCast<RamUnsigned>(ramBitCast<RamDomain>(randomNumber)));
     }
 }
TEST() [7/107]
souffle::ram::test::TEST (False , CloneAndEquals)
Definition at line 54 of file ram_condition_equal_clone_test.cpp.
References b, souffle::ram::False::clone(), EXPECT_EQ, and EXPECT_NE.
{
     False a;
     False b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     False* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [8/107]
souffle::ram::test::TEST (randomConversions , RamFloat)
Definition at line 57 of file ram_type_conversion_test.cpp.
References EXPECT_EQ, i, and NUMBER_OF_CONVERSION_TESTS.
{
     std::mt19937 randomGenerator(3);
     std::uniform_real_distribution<RamFloat> dist(-100.0, 100.0);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
         RamFloat randomNumber = dist(randomGenerator);
         // Test signed casting
         EXPECT_EQ(randomNumber, ramBitCast<RamFloat>(ramBitCast<RamDomain>(randomNumber)));
         // Test unsigned casting
         EXPECT_EQ(randomNumber, ramBitCast<RamFloat>(ramBitCast<RamUnsigned>(randomNumber)));
     }
 }
TEST() [9/107]
souffle::ram::test::TEST (RamScan , CloneAndEquals)
Definition at line 58 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::Scan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // FOR t0 in A
     //  RETURN number(0)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new SignedConstant(0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     Scan a(mk<RelationReference>(&A), 0, std::move(a_return), "Scan test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new SignedConstant(0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     Scan b(mk<RelationReference>(&A), 0, std::move(b_return), "Scan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Scan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [10/107]
souffle::ram::test::TEST (IO1 , CloneAndEquals)
Definition at line 65 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::IO::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // IO A ()
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     std::map<std::string, std::string> ioEmptyA;
     std::map<std::string, std::string> ioEmptyB;
     IO a(mk<RelationReference>(&A), std::move(ioEmptyA));
     IO b(mk<RelationReference>(&A), std::move(ioEmptyB));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     IO* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [11/107]
souffle::ram::test::TEST (Conjunction , CloneAndEquals)
Definition at line 66 of file ram_condition_equal_clone_test.cpp.
References b, d, e, EXPECT_EQ, and EXPECT_NE.
{
     // true /\ false
     auto a = mk<Conjunction>(mk<True>(), mk<False>());
     auto b = mk<Conjunction>(mk<True>(), mk<False>());
     EXPECT_EQ(*a, *b);
     EXPECT_NE(a, b);
     Own<Conjunction> c(a->clone());
     EXPECT_EQ(*a, *c);
     EXPECT_NE(a, c);
     // true /\ (false /\ true)
     auto d = mk<Conjunction>(mk<True>(), mk<Conjunction>(mk<False>(), mk<True>()));
     auto e = mk<Conjunction>(mk<True>(), mk<Conjunction>(mk<False>(), mk<True>()));
     EXPECT_EQ(*d, *e);
     EXPECT_NE(d, e);
     Own<Conjunction> f(d->clone());
     EXPECT_EQ(*d, *f);
     EXPECT_NE(d, f);
     // (true /\ false) /\ (true /\ (false /\ true))
     auto a_conj_d = mk<Conjunction>(std::move(a), std::move(d));
     auto b_conj_e = mk<Conjunction>(std::move(b), std::move(e));
     EXPECT_EQ(*a_conj_d, *b_conj_e);
     EXPECT_NE(a_conj_d, b_conj_e);
     auto c_conj_f = mk<Conjunction>(std::move(c), std::move(f));
     EXPECT_EQ(*c_conj_f, *a_conj_d);
     EXPECT_EQ(*c_conj_f, *b_conj_e);
     EXPECT_NE(c_conj_f, a_conj_d);
     EXPECT_NE(c_conj_f, b_conj_e);
     Own<Conjunction> a_conj_d_copy(a_conj_d->clone());
     EXPECT_EQ(*a_conj_d, *a_conj_d_copy);
     EXPECT_NE(a_conj_d, a_conj_d_copy);
 }
TEST() [12/107]
souffle::ram::test::TEST (UserDefinedOperator , CloneAndEquals)
Definition at line 75 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::UserDefinedOperator::clone(), EXPECT_EQ, EXPECT_NE, and souffle::Signed.
{
     // define binary functor NE check if two Expressions are not equal
     // NE(number(1), number(10))
     VecOwn<Expression> a_args;
     a_args.emplace_back(new SignedConstant(1));
     a_args.emplace_back(new SignedConstant(10));
     UserDefinedOperator a("NE", {TypeAttribute::Signed, TypeAttribute::Signed}, TypeAttribute::Signed, false,
             std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new SignedConstant(1));
     b_args.emplace_back(new SignedConstant(10));
     UserDefinedOperator b("NE", {TypeAttribute::Signed, TypeAttribute::Signed}, TypeAttribute::Signed, false,
             std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     UserDefinedOperator* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [13/107]
souffle::ram::test::TEST (RamParallelScan , CloneAndEquals)
Definition at line 81 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::ParallelScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // PARALLEL FOR t0 in A
     //  RETURN number(0)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new SignedConstant(0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     ParallelScan a(mk<RelationReference>(&A), 0, std::move(a_return), "ParallelScan test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new SignedConstant(0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     ParallelScan b(mk<RelationReference>(&A), 0, std::move(b_return), "ParallelScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     ParallelScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [14/107]
souffle::ram::test::TEST (Clear , CloneAndEquals)
Definition at line 81 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Clear::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // CLEAR A
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Clear a(mk<RelationReference>(&A));
     Clear b(mk<RelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Clear* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [15/107]
souffle::ram::test::TEST (Extend , CloneAndEquals)
Definition at line 95 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Extend::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // MERGE B WITH A
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Extend a(mk<RelationReference>(&B), mk<RelationReference>(&A));
     Extend b(mk<RelationReference>(&B), mk<RelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Extend* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [16/107]
souffle::ram::test::TEST (TupleElement , CloneAndEquals)
Definition at line 98 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::TupleElement::clone(), EXPECT_EQ, and EXPECT_NE.
{
     // t0.1
     TupleElement a(0, 1);
     TupleElement b(0, 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     TupleElement* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [17/107]
souffle::ram::test::TEST (RamIndexScan , CloneAndEquals)
Definition at line 104 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::IndexScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     Relation vertex("vertex", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // get vertices contain self loop
     // FOR t1 IN edge ON INDEX t1.x = t1.1 AND t1.y =
     //  PROJECT (t1.0) INTO vertex
     VecOwn<Expression> a_project_args;
     a_project_args.emplace_back(new TupleElement(1, 0));
     auto a_project = mk<Project>(mk<RelationReference>(&vertex), std::move(a_project_args));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new TupleElement(1, 1));
     a_criteria.first.emplace_back(new UndefValue);
     a_criteria.second.emplace_back(new TupleElement(1, 1));
     a_criteria.second.emplace_back(new UndefValue);
     IndexScan a(
             mk<RelationReference>(&edge), 1, std::move(a_criteria), std::move(a_project), "IndexScan test");
     VecOwn<Expression> b_project_args;
     b_project_args.emplace_back(new TupleElement(1, 0));
     auto b_project = mk<Project>(mk<RelationReference>(&vertex), std::move(b_project_args));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new TupleElement(1, 1));
     b_criteria.first.emplace_back(new UndefValue);
     b_criteria.second.emplace_back(new TupleElement(1, 1));
     b_criteria.second.emplace_back(new UndefValue);
     IndexScan b(
             mk<RelationReference>(&edge), 1, std::move(b_criteria), std::move(b_project), "IndexScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     IndexScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [18/107]
souffle::ram::test::TEST (IO_store , FloatSimple)
Definition at line 104 of file ram_relation_test.cpp.
References EXPECT_EQ, souffle::ramBitCast(), and testInterpreterStore().
{
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"f", "f"};
     VecOwn<Expression> exprs;
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(0.5))));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(0.5))));
     std::string expected = R"(---------------
 test
 ===============
 0.5 0.5
 ===============
 )";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected, result);
 }
TEST() [19/107]
souffle::ram::test::TEST (Negation , CloneAndEquals)
Definition at line 104 of file ram_condition_equal_clone_test.cpp.
References b, d, EXPECT_EQ, and EXPECT_NE.
{
     auto a = mk<True>();
     auto neg_a = mk<Negation>(std::move(a));
     auto b = mk<True>();
     auto neg_b = mk<Negation>(std::move(b));
     EXPECT_EQ(*neg_a, *neg_b);
     EXPECT_NE(neg_a, neg_b);
     auto c = mk<False>();
     auto neg_neg_c = mk<Negation>(mk<Negation>(std::move(c)));
     auto d = mk<False>();
     auto neg_neg_d = mk<Negation>(mk<Negation>(std::move(d)));
     EXPECT_EQ(*neg_neg_c, *neg_neg_d);
     EXPECT_NE(neg_neg_c, neg_neg_d);
 }
TEST() [20/107]
souffle::ram::test::TEST (Swap , CloneAndEquals)
Definition at line 110 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Swap::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // SWAP(A,B)
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Swap a(mk<RelationReference>(&A), mk<RelationReference>(&B));
     Swap b(mk<RelationReference>(&A), mk<RelationReference>(&B));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Swap* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [21/107]
souffle::ram::test::TEST (SignedConstant , CloneAndEquals)
Definition at line 111 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::SignedConstant::clone(), EXPECT_EQ, and EXPECT_NE.
{
     // number(5)
     SignedConstant a(5);
     SignedConstant b(5);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     SignedConstant* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [22/107]
souffle::ram::test::TEST (SignedConstant , ArithmeticEvaluation)
Definition at line 112 of file ram_arithmetic_test.cpp.
References evalExpression(), and EXPECT_EQ.
{
     RamDomain num = 42;
     Own<Expression> expression = mk<SignedConstant>(num);
     RamDomain result = evalExpression(std::move(expression));
     EXPECT_EQ(result, num);
 }
TEST() [23/107]
souffle::ram::test::TEST (Unary , Neg)
Definition at line 119 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::NEG, and TESTS_PER_OPERATION.
                  {
     for (RamDomain randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(FunctorOp::NEG, randomNumber), -randomNumber);
     }
 }
TEST() [24/107]
souffle::ram::test::TEST (Constraint , CloneAndEquals)
Definition at line 120 of file ram_condition_equal_clone_test.cpp.
References b, d, e, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     // constraint t0.1 = t1.0
     Own<Expression> a_lhs(new TupleElement(0, 1));
     Own<Expression> a_rhs(new TupleElement(1, 0));
     Own<Constraint> a(new Constraint(BinaryConstraintOp::EQ, std::move(a_lhs), std::move(a_rhs)));
     Own<Expression> b_lhs(new TupleElement(0, 1));
     Own<Expression> b_rhs(new TupleElement(1, 0));
     Own<Constraint> b(new Constraint(BinaryConstraintOp::EQ, std::move(b_lhs), std::move(b_rhs)));
     EXPECT_EQ(*a, *b);
     EXPECT_NE(a, b);
     Own<Constraint> c(a->clone());
     EXPECT_EQ(*a, *c);
     EXPECT_EQ(*b, *c);
     EXPECT_NE(a, c);
     EXPECT_NE(b, c);
     // constraint t2.0 >= 5
     Own<Expression> d_lhs(new TupleElement(2, 0));
     Own<Expression> d_rhs(new SignedConstant(5));
     Own<Constraint> d(new Constraint(BinaryConstraintOp::EQ, std::move(d_lhs), std::move(d_rhs)));
     Own<Expression> e_lhs(new TupleElement(2, 0));
     Own<Expression> e_rhs(new SignedConstant(5));
     Own<Constraint> e(new Constraint(BinaryConstraintOp::EQ, std::move(e_lhs), std::move(e_rhs)));
     EXPECT_EQ(*d, *e);
     EXPECT_NE(d, e);
     Own<Constraint> f(d->clone());
     EXPECT_EQ(*d, *f);
     EXPECT_EQ(*e, *f);
     EXPECT_NE(d, f);
     EXPECT_NE(e, f);
 }
TEST() [25/107]
souffle::ram::test::TEST (IO_store , Signed)
Definition at line 123 of file ram_relation_test.cpp.
References EXPECT_EQ, i, RANDOM_TESTS, and testInterpreterStore().
{
     std::vector<RamDomain> randomNumbers = testutil::generateRandomVector<RamDomain>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "i");
     VecOwn<Expression> exprs;
     for (RamDomain i : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(i));
     }
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
TEST() [26/107]
souffle::ram::test::TEST (AutoIncrement , CloneAndEquals)
Definition at line 124 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::AutoIncrement::clone(), EXPECT_EQ, and EXPECT_NE.
{
     AutoIncrement a;
     AutoIncrement b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     AutoIncrement* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [27/107]
souffle::ram::test::TEST (Unary , FloatNeg)
Definition at line 125 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::FNEG, souffle::ramBitCast(), and TESTS_PER_OPERATION.
                       {
     FunctorOp functor = FunctorOp::FNEG;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         auto result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamFloat>(result), -randomNumber);
     }
 }
TEST() [28/107]
souffle::ram::test::TEST (Query , CloneAndEquals)
Definition at line 125 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Query::clone(), d, souffle::DEFAULT, e, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 3, 1, {"a", "b", "c"}, {"i", "s", "i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 2, 1, {"a", "c"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     /*
      * QUERY
      *  FOR t0 IN A
      *   PROJECT (t0.0, t0.2) INTO B
      */
     VecOwn<Expression> a_expressions;
     a_expressions.emplace_back(new TupleElement(0, 0));
     a_expressions.emplace_back(new TupleElement(0, 2));
     auto a_project = mk<Project>(mk<RelationReference>(&B), std::move(a_expressions));
     auto a_scan = mk<Scan>(mk<RelationReference>(&A), 0, std::move(a_project), "");
     VecOwn<Expression> b_expressions;
     b_expressions.emplace_back(new TupleElement(0, 0));
     b_expressions.emplace_back(new TupleElement(0, 2));
     auto b_project = mk<Project>(mk<RelationReference>(&B), std::move(b_expressions));
     auto b_scan = mk<Scan>(mk<RelationReference>(&A), 0, std::move(b_project), "");
     Query a(std::move(a_scan));
     Query b(std::move(b_scan));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Query* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
     /*
      * QUERY
      *  PARALLEL CHOICE t1 IN A WHERE (t1.0 = 0)
      *   RETURN (t1.2)
      */
     VecOwn<Expression> d_return_value;
     d_return_value.emplace_back(new TupleElement(1, 0));
     auto d_return = mk<SubroutineReturn>(std::move(d_return_value));
     // condition t1.0 = 0
     auto d_cond = mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 0), mk<SignedConstant>(0));
     auto d_parallel_choice =
             mk<ParallelChoice>(mk<RelationReference>(&A), 1, std::move(d_cond), std::move(d_return), "");
     VecOwn<Expression> e_return_value;
     e_return_value.emplace_back(new TupleElement(1, 0));
     auto e_return = mk<SubroutineReturn>(std::move(e_return_value));
     // condition t1.0 = 0
     auto e_cond = mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 0), mk<SignedConstant>(0));
     auto e_parallel_choice =
             mk<ParallelChoice>(mk<RelationReference>(&A), 1, std::move(e_cond), std::move(e_return), "");
     Query d(std::move(d_parallel_choice));
     Query e(std::move(e_parallel_choice));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     Query* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
 }
TEST() [29/107]
souffle::ram::test::TEST (Unary , BinaryNot)
Definition at line 134 of file ram_arithmetic_test.cpp.
References souffle::BNOT, evalUnary(), EXPECT_EQ, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(functor, randomNumber), ~randomNumber);
     }
 }
TEST() [30/107]
souffle::ram::test::TEST (UndefValue , CloneAndEquals)
Definition at line 136 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::UndefValue::clone(), EXPECT_EQ, and EXPECT_NE.
{
     UndefValue a;
     UndefValue b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     UndefValue* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [31/107]
souffle::ram::test::TEST (RamParallelIndexScan , CloneAndEquals)
Definition at line 142 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::ParallelIndexScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     Relation new_edge("new_edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // get edges direct to vertex 5
     // PARALLEL FOR t1 IN edge ON INDEX t1.x =  AND t1.y = 5
     //  PROJECT (t1.0, t1.1) INTO new_edge
     VecOwn<Expression> a_project_args;
     a_project_args.emplace_back(new TupleElement(1, 0));
     a_project_args.emplace_back(new TupleElement(1, 1));
     auto a_project = mk<Project>(mk<RelationReference>(&new_edge), std::move(a_project_args));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new UndefValue);
     a_criteria.first.emplace_back(new SignedConstant(5));
     a_criteria.second.emplace_back(new UndefValue);
     a_criteria.second.emplace_back(new SignedConstant(5));
     ParallelIndexScan a(mk<RelationReference>(&edge), 1, std::move(a_criteria), std::move(a_project),
             "ParallelIndexScan test");
     VecOwn<Expression> b_project_args;
     b_project_args.emplace_back(new TupleElement(1, 0));
     b_project_args.emplace_back(new TupleElement(1, 1));
     auto b_project = mk<Project>(mk<RelationReference>(&new_edge), std::move(b_project_args));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new UndefValue);
     b_criteria.first.emplace_back(new SignedConstant(5));
     b_criteria.second.emplace_back(new UndefValue);
     b_criteria.second.emplace_back(new SignedConstant(5));
     ParallelIndexScan b(mk<RelationReference>(&edge), 1, std::move(b_criteria), std::move(b_project),
             "ParallelIndexScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     ParallelIndexScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [32/107]
souffle::ram::test::TEST (Unary , UnsignedBinaryNot)
Definition at line 142 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBNOT.
{
     FunctorOp functor = FunctorOp::UBNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), ~randomNumber);
     }
 }
TEST() [33/107]
souffle::ram::test::TEST (PackRecord , CloneAndEquals)
Definition at line 148 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::PackRecord::clone(), d, e, EXPECT_EQ, and EXPECT_NE.
{
     // {number{10), number(5), , }
     VecOwn<Expression> a_args;
     a_args.emplace_back(new SignedConstant(10));
     a_args.emplace_back(new SignedConstant(5));
     a_args.emplace_back(new UndefValue);
     a_args.emplace_back(new UndefValue);
     PackRecord a(std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new SignedConstant(10));
     b_args.emplace_back(new SignedConstant(5));
     b_args.emplace_back(new UndefValue);
     b_args.emplace_back(new UndefValue);
     PackRecord b(std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     PackRecord* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
     // {, {argument(1), number(0)}, t1.3}
     VecOwn<Expression> d_args;
     d_args.emplace_back(new UndefValue);
     VecOwn<Expression> d_record;
     d_record.emplace_back(new SubroutineArgument(1));
     d_record.emplace_back(new SignedConstant(5));
     d_args.emplace_back(new PackRecord(std::move(d_record)));
     d_args.emplace_back(new TupleElement(1, 3));
     PackRecord d(std::move(d_args));
     VecOwn<Expression> e_args;
     e_args.emplace_back(new UndefValue);
     VecOwn<Expression> e_record;
     e_record.emplace_back(new SubroutineArgument(1));
     e_record.emplace_back(new SignedConstant(5));
     e_args.emplace_back(new PackRecord(std::move(e_record)));
     e_args.emplace_back(new TupleElement(1, 3));
     PackRecord e(std::move(e_args));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     PackRecord* dClone = d.clone();
     EXPECT_EQ(d, *dClone);
     EXPECT_NE(&d, dClone);
     delete dClone;
 }
TEST() [34/107]
souffle::ram::test::TEST (Unary , LogicalNeg)
Definition at line 151 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::LNOT, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::LNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(functor, randomNumber), !randomNumber);
     }
 }
TEST() [35/107]
souffle::ram::test::TEST (ExistenceCheck , CloneAndEquals)
Definition at line 154 of file ram_condition_equal_clone_test.cpp.
References b, souffle::BRIE, souffle::ram::ExistenceCheck::clone(), d, souffle::DEFAULT, e, EXPECT_EQ, and EXPECT_NE.
{
     // N(1) in relation N(x:number)
     Relation N("N", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     VecOwn<Expression> tuple_a;
     tuple_a.emplace_back(new SignedConstant(1));
     ExistenceCheck a(mk<RelationReference>(&N), std::move(tuple_a));
     VecOwn<Expression> tuple_b;
     tuple_b.emplace_back(new SignedConstant(1));
     ExistenceCheck b(mk<RelationReference>(&N), std::move(tuple_b));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     ExistenceCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
     EXPECT_NE(&b, c);
     delete c;
     // edge(1,2) in relation edge(x:number,y:number)
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::BRIE);
     VecOwn<Expression> tuple_d;
     tuple_d.emplace_back(new SignedConstant(1));
     tuple_d.emplace_back(new SignedConstant(2));
     ExistenceCheck d(mk<RelationReference>(&edge), std::move(tuple_d));
     VecOwn<Expression> tuple_e;
     tuple_e.emplace_back(new SignedConstant(1));
     tuple_e.emplace_back(new SignedConstant(2));
     ExistenceCheck e(mk<RelationReference>(&edge), std::move(tuple_e));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     ExistenceCheck* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_EQ(e, *f);
     EXPECT_NE(&d, f);
     EXPECT_NE(&e, f);
     delete f;
 }
TEST() [36/107]
souffle::ram::test::TEST (IO_store , Float)
Definition at line 159 of file ram_relation_test.cpp.
References EXPECT_EQ, i, souffle::ramBitCast(), RANDOM_TESTS, and testInterpreterStore().
                       {
     std::vector<RamFloat> randomNumbers = testutil::generateRandomVector<RamFloat>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "f");
     VecOwn<Expression> exprs;
     for (RamFloat f : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(ramBitCast(f)));
     }
     std::stringstream expected;
     expected << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
TEST() [37/107]
souffle::ram::test::TEST (Unary , UnsignedLogicalNeg)
Definition at line 159 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::ULNOT.
{
     FunctorOp functor = FunctorOp::ULNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(!randomNumber));
     }
 }
TEST() [38/107]
souffle::ram::test::TEST (Unary , SingedTpUnsigned)
Definition at line 168 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::I2U, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::I2U;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, randomNumber);
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(randomNumber));
     }
 }
TEST() [39/107]
souffle::ram::test::TEST (Unary , UnsignedToSigned)
Definition at line 177 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::U2I.
{
     FunctorOp functor = FunctorOp::U2I;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(result, static_cast<RamDomain>(randomNumber));
     }
 }
TEST() [40/107]
souffle::ram::test::TEST (RamChoice , CloneAndEquals)
Definition at line 182 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::Choice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // choose an edge not adjcent to vertex 5
     // CHOICE t1 IN edge WHERE NOT t1.0 = 5 AND NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new TupleElement(1, 0));
     a_return_args.emplace_back(new TupleElement(1, 1));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     auto a_constraint1 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 0), mk<SignedConstant>(5));
     auto a_neg1 = mk<Negation>(std::move(a_constraint1));
     auto a_constraint2 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto a_neg2 = mk<Negation>(std::move(a_constraint2));
     auto a_cond = mk<Conjunction>(std::move(a_neg1), std::move(a_neg2));
     Choice a(mk<RelationReference>(&edge), 1, std::move(a_cond), std::move(a_return), "Choice test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new TupleElement(1, 0));
     b_return_args.emplace_back(new TupleElement(1, 1));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     auto b_constraint1 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 0), mk<SignedConstant>(5));
     auto b_neg1 = mk<Negation>(std::move(b_constraint1));
     auto b_constraint2 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto b_neg2 = mk<Negation>(std::move(b_constraint2));
     auto b_cond = mk<Conjunction>(std::move(b_neg1), std::move(b_neg2));
     Choice b(mk<RelationReference>(&edge), 1, std::move(b_cond), std::move(b_return), "Choice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Choice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [41/107]
souffle::ram::test::TEST (Unary , SignedToFloat)
Definition at line 186 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::I2F, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::I2F;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(randomNumber));
     }
 }
TEST() [42/107]
souffle::ram::test::TEST (Sequence , CloneAndEquals)
Definition at line 186 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Sequence::clone(), d, souffle::DEFAULT, e, EXPECT_EQ, EXPECT_NE, and i.
{
     // no statements in the sequence
     Sequence a;
     Sequence b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Sequence* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // one statement in the sequence
     // CLEAR A
     Sequence d(mk<Clear>(mk<RelationReference>(&A)));
     Sequence e(mk<Clear>(mk<RelationReference>(&A)));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     Sequence* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
     // multiple statements in the sequence
     // IO A ()
     // CLEAR A
     std::map<std::string, std::string> g_load_IODir;
     std::map<std::string, std::string> h_load_IODir;
     Sequence g(
             mk<IO>(mk<RelationReference>(&A), std::move(g_load_IODir)), mk<Clear>(mk<RelationReference>(&A)));
     Sequence h(
             mk<IO>(mk<RelationReference>(&A), std::move(h_load_IODir)), mk<Clear>(mk<RelationReference>(&A)));
     EXPECT_EQ(g, h);
     EXPECT_NE(&g, &h);
     Sequence* i = g.clone();
     EXPECT_EQ(g, *i);
     EXPECT_NE(&g, i);
     delete i;
 }
TEST() [43/107]
souffle::ram::test::TEST (Unary , FloatToSigned)
Definition at line 195 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::F2I, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::F2I;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(result, static_cast<RamDomain>(randomNumber));
     }
 }
TEST() [44/107]
souffle::ram::test::TEST (RamProvenanceExistCheck , CloneAndEquals)
Definition at line 196 of file ram_condition_equal_clone_test.cpp.
References b, souffle::ram::ProvenanceExistenceCheck::clone(), souffle::ram::ExistenceCheck::clone(), d, souffle::DEFAULT, e, EXPECT_EQ, and EXPECT_NE.
{
     Relation N("N", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     VecOwn<Expression> tuple_a;
     tuple_a.emplace_back(new SignedConstant(1));
     ExistenceCheck a(mk<RelationReference>(&N), std::move(tuple_a));
     VecOwn<Expression> tuple_b;
     tuple_b.emplace_back(new SignedConstant(1));
     ExistenceCheck b(mk<RelationReference>(&N), std::move(tuple_b));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     ExistenceCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
     EXPECT_NE(&b, c);
     delete c;
     // address(state:symbol, postCode:number, street:symbol)
     Relation address("address", 3, 1, {"state", "postCode", "street"}, {"s", "i", "s"},
             RelationRepresentation::DEFAULT);
     VecOwn<Expression> tuple_d;
     tuple_d.emplace_back(new SignedConstant(0));
     tuple_d.emplace_back(new SignedConstant(2000));
     tuple_d.emplace_back(new SignedConstant(0));
     ProvenanceExistenceCheck d(mk<RelationReference>(&address), std::move(tuple_d));
     VecOwn<Expression> tuple_e;
     tuple_e.emplace_back(new SignedConstant(0));
     tuple_e.emplace_back(new SignedConstant(2000));
     tuple_e.emplace_back(new SignedConstant(0));
     ProvenanceExistenceCheck e(mk<RelationReference>(&address), std::move(tuple_e));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     ProvenanceExistenceCheck* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_EQ(e, *f);
     EXPECT_NE(&d, f);
     EXPECT_NE(&e, f);
     delete f;
 }
TEST() [45/107]
souffle::ram::test::TEST (IO_store , Unsigned)
Definition at line 197 of file ram_relation_test.cpp.
References EXPECT_EQ, i, souffle::ramBitCast(), RANDOM_TESTS, and testInterpreterStore().
{
     std::vector<RamUnsigned> randomNumbers = testutil::generateRandomVector<RamUnsigned>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "u");
     VecOwn<Expression> exprs;
     for (RamUnsigned u : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(ramBitCast(u)));
     }
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
TEST() [46/107]
souffle::ram::test::TEST (RamSubrountineArgument , CloneAndEquals)
Definition at line 200 of file ram_expression_equal_clone_test.cpp.
References b, souffle::ram::SubroutineArgument::clone(), EXPECT_EQ, and EXPECT_NE.
{
     SubroutineArgument a(2);
     SubroutineArgument b(2);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     SubroutineArgument* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [47/107]
souffle::ram::test::TEST (Unary , UnsignedToFloat)
Definition at line 204 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::U2F.
{
     FunctorOp functor = FunctorOp::U2F;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(randomNumber));
     }
 }
TEST() [48/107]
souffle::ram::test::TEST (Unary , FloatToUnsigned)
Definition at line 213 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::F2U, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::F2U;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(randomNumber));
     }
 }
TEST() [49/107]
souffle::ram::test::TEST (RamParallelChoice , CloneAndEquals)
Definition at line 222 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::ParallelChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // parallel choose an edge not adjcent to vertex 5
     // PARALLEL CHOICE t1 IN edge WHERE NOT t1.0 = 5 AND NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new TupleElement(1, 0));
     a_return_args.emplace_back(new TupleElement(1, 1));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     auto a_constraint1 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 0), mk<SignedConstant>(5));
     auto a_neg1 = mk<Negation>(std::move(a_constraint1));
     auto a_constraint2 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto a_neg2 = mk<Negation>(std::move(a_constraint2));
     auto a_cond = mk<Conjunction>(std::move(a_neg1), std::move(a_neg2));
     ParallelChoice a(
             mk<RelationReference>(&edge), 1, std::move(a_cond), std::move(a_return), "ParallelChoice test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new TupleElement(1, 0));
     b_return_args.emplace_back(new TupleElement(1, 1));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     auto b_constraint1 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 0), mk<SignedConstant>(5));
     auto b_neg1 = mk<Negation>(std::move(b_constraint1));
     auto b_constraint2 =
             mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto b_neg2 = mk<Negation>(std::move(b_constraint2));
     auto b_cond = mk<Conjunction>(std::move(b_neg1), std::move(b_neg2));
     ParallelChoice b(
             mk<RelationReference>(&edge), 1, std::move(b_cond), std::move(b_return), "ParallelChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     ParallelChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [50/107]
souffle::ram::test::TEST (Binary , SignedAdd)
Definition at line 222 of file ram_arithmetic_test.cpp.
References souffle::ADD, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::ADD;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (size_t i = 0; i < TESTS_PER_OPERATION; ++i) {
         RamDomain arg1 = vecArg1[i];
         RamDomain arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 + arg2);
     }
 }
TEST() [51/107]
souffle::ram::test::TEST (Parallel , CloneAndEquals)
Definition at line 229 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Parallel::clone(), souffle::DEFAULT, EXPECT_EQ, EXPECT_NE, and souffle::GE.
{
     Relation A("A", 3, 1, {"a", "b", "c"}, {"i", "s", "i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 2, 1, {"a", "c"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     /* PARALLEL
      *  QUERY
      *   FOR t0 IN A
      *    IF (t0.0 > 0)
      *     PROJECT (t0.0, t0.2) INTO B
      * END PARALLEL
      * */
     VecOwn<Expression> a_expressions;
     a_expressions.emplace_back(new TupleElement(0, 0));
     a_expressions.emplace_back(new TupleElement(0, 2));
     auto a_project = mk<Project>(mk<RelationReference>(&B), std::move(a_expressions));
     auto a_cond =
             mk<Filter>(mk<Constraint>(BinaryConstraintOp::GE, mk<TupleElement>(0, 0), mk<SignedConstant>(0)),
                     std::move(a_project), "");
     auto a_scan = mk<Scan>(mk<RelationReference>(&A), 0, std::move(a_cond), "");
     auto a_query = mk<Query>(std::move(a_scan));
     Parallel a(std::move(a_query));
     VecOwn<Expression> b_expressions;
     b_expressions.emplace_back(new TupleElement(0, 0));
     b_expressions.emplace_back(new TupleElement(0, 2));
     auto b_project = mk<Project>(mk<RelationReference>(&B), std::move(b_expressions));
     auto b_cond =
             mk<Filter>(mk<Constraint>(BinaryConstraintOp::GE, mk<TupleElement>(0, 0), mk<SignedConstant>(0)),
                     std::move(b_project), "");
     auto b_scan = mk<Scan>(mk<RelationReference>(&A), 0, std::move(b_cond), "");
     auto b_query = mk<Query>(std::move(b_scan));
     Parallel b(std::move(b_query));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Parallel* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [52/107]
souffle::ram::test::TEST (IO_store , SignedChangedDelimiter)
Definition at line 234 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, i, souffle::main(), RANDOM_TESTS, and types.
{
     std::vector<RamDomain> randomNumbers = testutil::generateRandomVector<RamDomain>(RANDOM_TESTS);
     const std::string delimiter{", "};
     Global::config().set("jobs", "1");
     VecOwn<Relation> rels;
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "i");
     Own<Relation> myrel =
             mk<Relation>("test", RANDOM_TESTS, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"delimiter", delimiter}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     VecOwn<Expression> exprs;
     for (RamDomain i : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(i));
     }
     Own<Statement> main = mk<Sequence>(
             mk<Query>(mk<Project>(std::move(ref1), std::move(exprs))), mk<IO>(std::move(ref2), ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << delimiter << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     EXPECT_EQ(expected.str(), sout.str());
 }
TEST() [53/107]
souffle::ram::test::TEST (Binary , UnsignedAdd)
Definition at line 236 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UADD.
{
     FunctorOp functor = FunctorOp::UADD;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         RamUnsigned arg1 = vecArg1[i];
         RamUnsigned arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 + arg2);
     }
 }
TEST() [54/107]
souffle::ram::test::TEST (EmptinessCheck , CloneAndEquals)
Definition at line 240 of file ram_condition_equal_clone_test.cpp.
References b, souffle::ram::EmptinessCheck::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // Check A(x:number)
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     EmptinessCheck a(mk<RelationReference>(&A));
     EmptinessCheck b(mk<RelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     EmptinessCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
     EXPECT_NE(&b, c);
     delete c;
 }
TEST() [55/107]
souffle::ram::test::TEST (Binary , FloatAdd)
Definition at line 250 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FADD, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FADD;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 + arg2);
     }
 }
TEST() [56/107]
souffle::ram::test::TEST (Binary , SignedSub)
Definition at line 264 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::SUB, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::SUB;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 - arg2);
     }
 }
TEST() [57/107]
souffle::ram::test::TEST (RamIndexChoice , CloneAndEquals)
Definition at line 264 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::IndexChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // FOR t1 IN edge ON INDEX t1.x = 5 AND t1.y =
     // WHERE NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new TupleElement(1, 0));
     a_return_args.emplace_back(new TupleElement(1, 1));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     auto a_constraint = mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto a_neg = mk<Negation>(std::move(a_constraint));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new SignedConstant(5));
     a_criteria.first.emplace_back(new UndefValue);
     a_criteria.second.emplace_back(new SignedConstant(5));
     a_criteria.second.emplace_back(new UndefValue);
     IndexChoice a(mk<RelationReference>(&edge), 1, std::move(a_neg), std::move(a_criteria),
             std::move(a_return), "IndexChoice test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new TupleElement(1, 0));
     b_return_args.emplace_back(new TupleElement(1, 1));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     auto b_constraint = mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto b_neg = mk<Negation>(std::move(b_constraint));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new SignedConstant(5));
     b_criteria.first.emplace_back(new UndefValue);
     b_criteria.second.emplace_back(new SignedConstant(5));
     b_criteria.second.emplace_back(new UndefValue);
     IndexChoice b(mk<RelationReference>(&edge), 1, std::move(b_neg), std::move(b_criteria),
             std::move(b_return), "IndexChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     IndexChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [58/107]
souffle::ram::test::TEST (Loop , CloneAndEquals)
Definition at line 271 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Loop::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * LOOP
      *  QUERY
      *   FOR t0 IN A
      *    IF t0.0 = 4 BREAK
      *    PROJECT (t0.0) INTO B
      * END LOOP
      * */
     VecOwn<Expression> a_expressions;
     a_expressions.emplace_back(new TupleElement(0, 0));
     auto a_project = mk<Project>(mk<RelationReference>(&B), std::move(a_expressions));
     auto a_break =
             mk<Break>(mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(0, 0), mk<SignedConstant>(4)),
                     std::move(a_project), "");
     auto a_scan = mk<Scan>(mk<RelationReference>(&A), 0, std::move(a_break), "");
     auto a_query = mk<Query>(std::move(a_scan));
     Loop a(std::move(a_query));
     VecOwn<Expression> b_expressions;
     b_expressions.emplace_back(new TupleElement(0, 0));
     auto b_project = mk<Project>(mk<RelationReference>(&B), std::move(b_expressions));
     auto b_break =
             mk<Break>(mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(0, 0), mk<SignedConstant>(4)),
                     std::move(b_project), "");
     auto b_scan = mk<Scan>(mk<RelationReference>(&A), 0, std::move(b_break), "");
     auto b_query = mk<Query>(std::move(b_scan));
     Loop b(std::move(b_query));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Loop* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [59/107]
souffle::ram::test::TEST (Binary , UnsignedSub)
Definition at line 278 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::USUB.
{
     FunctorOp functor = FunctorOp::USUB;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 - arg2);
     }
 }
TEST() [60/107]
souffle::ram::test::TEST (Binary , FloatSub)
Definition at line 292 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FSUB, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FSUB;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 - arg2);
     }
 }
TEST() [61/107]
souffle::ram::test::TEST (RamiParallelIndexChoice , CloneAndEquals)
Definition at line 305 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::ParallelIndexChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // PARALLEL FOR t1 IN edge ON INDEX t1.x = 5 AND t1.y =
     // WHERE NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new TupleElement(1, 0));
     a_return_args.emplace_back(new TupleElement(1, 1));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     auto a_constraint = mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto a_neg = mk<Negation>(std::move(a_constraint));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new SignedConstant(5));
     a_criteria.first.emplace_back(new UndefValue);
     a_criteria.second.emplace_back(new SignedConstant(5));
     a_criteria.second.emplace_back(new UndefValue);
     ParallelIndexChoice a(mk<RelationReference>(&edge), 1, std::move(a_neg), std::move(a_criteria),
             std::move(a_return), "IndexChoice test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new TupleElement(1, 0));
     b_return_args.emplace_back(new TupleElement(1, 1));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     auto b_constraint = mk<Constraint>(BinaryConstraintOp::EQ, mk<TupleElement>(1, 1), mk<SignedConstant>(5));
     auto b_neg = mk<Negation>(std::move(b_constraint));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new SignedConstant(5));
     b_criteria.first.emplace_back(new UndefValue);
     b_criteria.second.emplace_back(new SignedConstant(5));
     b_criteria.second.emplace_back(new UndefValue);
     ParallelIndexChoice b(mk<RelationReference>(&edge), 1, std::move(b_neg), std::move(b_criteria),
             std::move(b_return), "IndexChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     ParallelIndexChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [62/107]
souffle::ram::test::TEST (Binary , SignedMul)
Definition at line 306 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::MUL, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::MUL;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 * arg2);
     }
 }
TEST() [63/107]
souffle::ram::test::TEST (Exit , CloneAndEquals)
Definition at line 309 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::Exit::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // EXIT (A = )
     Exit a(mk<EmptinessCheck>(mk<RelationReference>(&A)));
     Exit b(mk<EmptinessCheck>(mk<RelationReference>(&A)));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Exit* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [64/107]
souffle::ram::test::TEST (IO_store , MixedTypes)
Definition at line 313 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), souffle::ramBitCast(), and types.
{
     Global::config().set("jobs", "1");
     VecOwn<Relation> rels;
     std::vector<std::string> attribs{"t", "o", "s", "i", "a"};
     std::vector<std::string> attribsTypes{"i", "u", "f", "f", "s"};
     Own<Relation> myrel = mk<Relation>("test", 5, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     SymbolTable symbolTable;
     ErrorReport errReport;
     DebugReport debugReport;
     VecOwn<Expression> exprs;
     RamFloat floatValue = 27.75;
     exprs.push_back(mk<SignedConstant>(3));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamUnsigned>(27))));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(floatValue))));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(floatValue))));
     exprs.push_back(mk<SignedConstant>(symbolTable.lookup("meow")));
     Own<Statement> main = mk<Sequence>(
             mk<Query>(mk<Project>(std::move(ref1), std::move(exprs))), mk<IO>(std::move(ref2), ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     TranslationUnit translationUnit(std::move(prog), symbolTable, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::stringstream expected;
     expected << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << 3 << "\t" << 27 << "\t" << floatValue << "\t" << floatValue << "\t"
              << "meow"
              << "\n"
              << "==============="
              << "\n";
     EXPECT_EQ(expected.str(), sout.str());
 }
TEST() [65/107]
souffle::ram::test::TEST (Binary , UnsignedMul)
Definition at line 320 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UMUL.
{
     FunctorOp functor = FunctorOp::UMUL;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 * arg2);
     }
 }
TEST() [66/107]
souffle::ram::test::TEST (LogRelationTimer , CloneAndEquals)
Definition at line 323 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::LogRelationTimer::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * START_TIMER ON A "file.dl [8:1-8:8]"
      *   IO A()
      * END_TIMER
      * */
     std::map<std::string, std::string> a_IODir;
     std::map<std::string, std::string> b_IODir;
     LogRelationTimer a(mk<IO>(mk<RelationReference>(&A), std::move(a_IODir)), "file.dl [8:1-8:8]",
             mk<RelationReference>(&A));
     LogRelationTimer b(mk<IO>(mk<RelationReference>(&A), std::move(b_IODir)), "file.dl [8:1-8:8]",
             mk<RelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     LogRelationTimer* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [67/107]
souffle::ram::test::TEST (Binary , FloatMul)
Definition at line 334 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FMUL, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FMUL;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 * arg2);
     }
 }
TEST() [68/107]
souffle::ram::test::TEST (LogTimer , CloneAndEquals)
Definition at line 345 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::LogTimer::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * START_TIMER "@runtime"
      *   IO .. (..)
      * END_TIMER
      * */
     std::map<std::string, std::string> a_IODir;
     std::map<std::string, std::string> b_IODir;
     LogTimer a(mk<IO>(mk<RelationReference>(&A), std::move(a_IODir)), "@runtime");
     LogTimer b(mk<IO>(mk<RelationReference>(&A), std::move(a_IODir)), "@runtime");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     LogTimer* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [69/107]
souffle::ram::test::TEST (RamAggregate , CloneAndEquals)
Definition at line 346 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::Aggregate::clone(), souffle::COUNT, souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // t0.0 = COUNT FOR ALL t1 IN edge
     //  RETURN t0.0
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new TupleElement(0, 0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     Aggregate a(std::move(a_return), AggregateOp::COUNT, mk<RelationReference>(&edge), mk<TupleElement>(0, 0),
             mk<True>(), 1);
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new TupleElement(0, 0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     Aggregate b(std::move(b_return), AggregateOp::COUNT, mk<RelationReference>(&edge), mk<TupleElement>(0, 0),
             mk<True>(), 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Aggregate* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [70/107]
souffle::ram::test::TEST (Binary , SignedDiv)
Definition at line 348 of file ram_arithmetic_test.cpp.
References souffle::DIV, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::DIV;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, arg1, arg2);
             EXPECT_EQ(result, arg1 / arg2);
         }
     }
 }
TEST() [71/107]
souffle::ram::test::TEST (Binary , UnsignedDiv)
Definition at line 364 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UDIV.
{
     FunctorOp functor = FunctorOp::UDIV;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
             EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 / arg2);
         }
     }
 }
TEST() [72/107]
souffle::ram::test::TEST (DebugInfo , CloneAndEquals)
Definition at line 365 of file ram_statement_equal_clone_test.cpp.
References souffle::ADD, b, souffle::ram::DebugInfo::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation edge(
             "edge", 4, 1, {"src", "dest", "a", "b"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     Relation path(
             "path", 4, 1, {"src", "dest", "a", "b"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     /* BEGIN_DEBUG "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl
      * [17:1-17:26];" QUERY FOR t0 IN edge IF (NOT (edge = )) IF (NOT (t0.0,t0.1,,)  path) PROJECT (t0.0,
      * t0.1, number(1), (t0.3+number(1))) INTO path END DEBUG
      * */
     VecOwn<Expression> a_project_list;
     a_project_list.emplace_back(new TupleElement(0, 0));
     a_project_list.emplace_back(new TupleElement(0, 1));
     a_project_list.emplace_back(new SignedConstant(1));
     VecOwn<Expression> a_project_add;
     a_project_add.emplace_back(new TupleElement(0, 3));
     a_project_add.emplace_back(new SignedConstant(1));
     a_project_list.emplace_back(new IntrinsicOperator(FunctorOp::ADD, std::move(a_project_add)));
     auto a_project = mk<Project>(mk<RelationReference>(&path), std::move(a_project_list));
     VecOwn<Expression> a_filter1_list;
     a_filter1_list.emplace_back(new TupleElement(0, 0));
     a_filter1_list.emplace_back(new TupleElement(0, 1));
     a_filter1_list.emplace_back(new UndefValue);
     a_filter1_list.emplace_back(new UndefValue);
     auto a_existence_check1 = mk<ExistenceCheck>(mk<RelationReference>(&path), std::move(a_filter1_list));
     auto a_cond1 = mk<Negation>(std::move(a_existence_check1));
     auto a_filter1 = mk<Filter>(std::move(a_cond1), std::move(a_project), "");
     auto a_cond2 = mk<Negation>(mk<EmptinessCheck>(mk<RelationReference>(&edge)));
     auto a_filter2 = mk<Filter>(std::move(a_cond2), std::move(a_filter1), "");
     auto a_scan = mk<Scan>(mk<RelationReference>(&edge), 0, std::move(a_filter2), "");
     auto a_query = mk<Query>(std::move(a_scan));
     DebugInfo a(std::move(a_query),
             "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl [17:1-17:26];");
     VecOwn<Expression> b_project_list;
     b_project_list.emplace_back(new TupleElement(0, 0));
     b_project_list.emplace_back(new TupleElement(0, 1));
     b_project_list.emplace_back(new SignedConstant(1));
     VecOwn<Expression> b_project_add;
     b_project_add.emplace_back(new TupleElement(0, 3));
     b_project_add.emplace_back(new SignedConstant(1));
     b_project_list.emplace_back(new IntrinsicOperator(FunctorOp::ADD, std::move(b_project_add)));
     auto b_project = mk<Project>(mk<RelationReference>(&path), std::move(b_project_list));
     VecOwn<Expression> b_filter1_list;
     b_filter1_list.emplace_back(new TupleElement(0, 0));
     b_filter1_list.emplace_back(new TupleElement(0, 1));
     b_filter1_list.emplace_back(new UndefValue);
     b_filter1_list.emplace_back(new UndefValue);
     auto b_existence_check1 = mk<ExistenceCheck>(mk<RelationReference>(&path), std::move(b_filter1_list));
     auto b_cond1 = mk<Negation>(std::move(b_existence_check1));
     auto b_filter1 = mk<Filter>(std::move(b_cond1), std::move(b_project), "");
     auto b_cond2 = mk<Negation>(mk<EmptinessCheck>(mk<RelationReference>(&edge)));
     auto b_filter2 = mk<Filter>(std::move(b_cond2), std::move(b_filter1), "");
     auto b_scan = mk<Scan>(mk<RelationReference>(&edge), 0, std::move(b_filter2), "");
     auto b_query = mk<Query>(std::move(b_scan));
     DebugInfo b(std::move(b_query),
             "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl [17:1-17:26];");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     DebugInfo* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [73/107]
souffle::ram::test::TEST (RamIndexAggregate , CloneAndEquals)
Definition at line 370 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::IndexAggregate::clone(), souffle::DEFAULT, EXPECT_EQ, EXPECT_NE, souffle::GE, and souffle::MIN.
{
     Relation sqrt("sqrt", 2, 1, {"nth", "value"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // t0.0 = MIN t1.1 SEARCH t1 IN sqrt ON INDEX t1.0 =  AND t1.1 =
     // WHERE t1.1 > 80
     //  RETURN t0.0
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new TupleElement(0, 0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     auto a_cond = mk<Constraint>(BinaryConstraintOp::GE, mk<TupleElement>(1, 1), mk<SignedConstant>(80));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new UndefValue);
     a_criteria.first.emplace_back(new UndefValue);
     a_criteria.second.emplace_back(new UndefValue);
     a_criteria.second.emplace_back(new UndefValue);
     IndexAggregate a(std::move(a_return), AggregateOp::MIN, mk<RelationReference>(&sqrt),
             mk<TupleElement>(1, 1), std::move(a_cond), std::move(a_criteria), 1);
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new TupleElement(0, 0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     auto b_cond = mk<Constraint>(BinaryConstraintOp::GE, mk<TupleElement>(1, 1), mk<SignedConstant>(80));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new UndefValue);
     b_criteria.first.emplace_back(new UndefValue);
     b_criteria.second.emplace_back(new UndefValue);
     b_criteria.second.emplace_back(new UndefValue);
     IndexAggregate b(std::move(b_return), AggregateOp::MIN, mk<RelationReference>(&sqrt),
             mk<TupleElement>(1, 1), std::move(b_cond), std::move(b_criteria), 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     IndexAggregate* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [74/107]
souffle::ram::test::TEST (Binary , FloatDiv)
Definition at line 380 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FDIV, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FDIV;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
             EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 / arg2);
         }
     }
 }
TEST() [75/107]
souffle::ram::test::TEST (IO_load , Signed)
Definition at line 384 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
                       {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("5 3");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     VecOwn<Relation> rels;
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"i", "i"};
     Own<Relation> myrel = mk<Relation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<Statement> main =
             mk<Sequence>(mk<IO>(std::move(ref1), readIoDirs), mk<IO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 5   3
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [76/107]
souffle::ram::test::TEST (Binary , SignedExp)
Definition at line 396 of file ram_arithmetic_test.cpp.
References evalBinary(), souffle::EXP, EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::EXP;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, static_cast<RamDomain>(std::pow(arg1, arg2)));
     }
 }
TEST() [77/107]
souffle::ram::test::TEST (RamUnpackedRecord , CloneAndEquals)
Definition at line 407 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::UnpackRecord::clone(), EXPECT_EQ, and EXPECT_NE.
{
     // UNPACK (t0.0, t0.2) INTO t1
     // RETURN number(0)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new SignedConstant(0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     VecOwn<Expression> a_record_args;
     a_record_args.emplace_back(new TupleElement(0, 0));
     a_record_args.emplace_back(new TupleElement(0, 2));
     auto a_record = mk<PackRecord>(std::move(a_record_args));
     UnpackRecord a(std::move(a_return), 1, std::move(a_record), 2);
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new SignedConstant(0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     VecOwn<Expression> b_record_args;
     b_record_args.emplace_back(new TupleElement(0, 0));
     b_record_args.emplace_back(new TupleElement(0, 2));
     auto b_record = mk<PackRecord>(std::move(b_record_args));
     UnpackRecord b(std::move(b_return), 1, std::move(b_record), 2);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     UnpackRecord* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [78/107]
souffle::ram::test::TEST (Binary , UnsignedExp)
Definition at line 410 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UEXP.
{
     FunctorOp functor = FunctorOp::UEXP;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(std::pow(arg1, arg2)));
     }
 }
TEST() [79/107]
souffle::ram::test::TEST (Binary , FloatExp)
Definition at line 424 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_TRUE, souffle::FEXP, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FEXP;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         auto result = ramBitCast<RamFloat>(evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2)));
         auto expected = static_cast<RamFloat>(std::pow(arg1, arg2));
         EXPECT_TRUE((std::isnan(result) && std::isnan(expected)) || result == expected);
     }
 }
TEST() [80/107]
souffle::ram::test::TEST (LogSize , CloneAndEquals)
Definition at line 431 of file ram_statement_equal_clone_test.cpp.
References b, souffle::ram::LogSize::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     LogSize a(mk<RelationReference>(&A), "Log message");
     LogSize b(mk<RelationReference>(&A), "Log message");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     LogSize* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [81/107]
souffle::ram::test::TEST (RamFilter , CloneAndEquals)
Definition at line 436 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::Filter::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     // IF (NOT t0.1 in A)
     // RETURN number(0)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new SignedConstant(0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     VecOwn<Expression> a_existence_check_args;
     a_existence_check_args.emplace_back(new TupleElement(0, 1));
     auto a_existence_check = mk<ExistenceCheck>(mk<RelationReference>(&A), std::move(a_existence_check_args));
     Filter a(mk<Negation>(std::move(a_existence_check)), std::move(a_return), "Filter test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new SignedConstant(0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     VecOwn<Expression> b_existence_check_args;
     b_existence_check_args.emplace_back(new TupleElement(0, 1));
     auto b_existence_check = mk<ExistenceCheck>(mk<RelationReference>(&A), std::move(b_existence_check_args));
     Filter b(mk<Negation>(std::move(b_existence_check)), std::move(b_return), "Filter test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Filter* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [82/107]
souffle::ram::test::TEST (Binary , SignedMod)
Definition at line 439 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::MOD, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::MOD;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 % arg2);
     }
 }
TEST() [83/107]
souffle::ram::test::TEST (IO_load , Float)
Definition at line 447 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
                      {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("0.5   0.5");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     VecOwn<Relation> rels;
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"f", "f"};
     Own<Relation> myrel = mk<Relation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<Statement> main =
             mk<Sequence>(mk<IO>(std::move(ref1), readIoDirs), mk<IO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 0.5 0.5
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [84/107]
souffle::ram::test::TEST (Binary , UnsignedMod)
Definition at line 453 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UMOD.
{
     FunctorOp functor = FunctorOp::UMOD;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 % arg2);
     }
 }
TEST() [85/107]
souffle::ram::test::TEST (RamBreak , CloneAndEquals)
Definition at line 464 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::Break::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     // IF (A = ) BREAK
     // RETURN number(0)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new SignedConstant(0));
     auto a_return = mk<SubroutineReturn>(std::move(a_return_args));
     Break a(mk<EmptinessCheck>(mk<RelationReference>(&A)), std::move(a_return), "Break test");
     VecOwn<Expression> b_return_args;
     b_return_args.emplace_back(new SignedConstant(0));
     auto b_return = mk<SubroutineReturn>(std::move(b_return_args));
     Break b(mk<EmptinessCheck>(mk<RelationReference>(&A)), std::move(b_return), "Break test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Break* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [86/107]
souffle::ram::test::TEST (Binary , SignedBinaryAnd)
Definition at line 467 of file ram_arithmetic_test.cpp.
References souffle::BAND, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BAND;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 & arg2);
     }
 }
TEST() [87/107]
souffle::ram::test::TEST (Binary , UnsignedBinaryAnd)
Definition at line 481 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBAND.
{
     FunctorOp functor = FunctorOp::UBAND;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 & arg2);
     }
 }
TEST() [88/107]
souffle::ram::test::TEST (RamProject , CloneAndEquals)
Definition at line 486 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::Project::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     Relation A("A", 2, 1, {"a", "b"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // PROJECT (t0.1, t0.3) INTO A
     VecOwn<Expression> a_args;
     a_args.emplace_back(new TupleElement(0, 1));
     a_args.emplace_back(new TupleElement(0, 3));
     Project a(mk<RelationReference>(&A), std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new TupleElement(0, 1));
     b_args.emplace_back(new TupleElement(0, 3));
     Project b(mk<RelationReference>(&A), std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Project* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [89/107]
souffle::ram::test::TEST (Binary , SignedBinaryOr)
Definition at line 495 of file ram_arithmetic_test.cpp.
References souffle::BOR, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 | arg2);
     }
 }
TEST() [90/107]
souffle::ram::test::TEST (RamSubroutineReturn , CloneAndEquals)
Definition at line 507 of file ram_operation_equal_clone_test.cpp.
References b, souffle::ram::SubroutineReturn::clone(), d, e, EXPECT_EQ, and EXPECT_NE.
{
     // RETURN (t0.1, t0.2)
     VecOwn<Expression> a_args;
     a_args.emplace_back(new TupleElement(0, 1));
     a_args.emplace_back(new TupleElement(0, 2));
     SubroutineReturn a(std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new TupleElement(0, 1));
     b_args.emplace_back(new TupleElement(0, 2));
     SubroutineReturn b(std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     SubroutineReturn* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
     // RETURN (number(0))
     VecOwn<Expression> d_args;
     d_args.emplace_back(new SignedConstant(0));
     SubroutineReturn d(std::move(d_args));
     VecOwn<Expression> e_args;
     e_args.emplace_back(new SignedConstant(0));
     SubroutineReturn e(std::move(e_args));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     SubroutineReturn* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
 }
TEST() [91/107]
souffle::ram::test::TEST (Binary , UnsignedBinaryOr)
Definition at line 509 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBOR.
{
     FunctorOp functor = FunctorOp::UBOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 | arg2);
     }
 }
TEST() [92/107]
souffle::ram::test::TEST (IO_load , Unsigned)
Definition at line 510 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
{
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("6 6");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     VecOwn<Relation> rels;
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"u", "u"};
     Own<Relation> myrel = mk<Relation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<Statement> main =
             mk<Sequence>(mk<IO>(std::move(ref1), readIoDirs), mk<IO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 6   6
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [93/107]
souffle::ram::test::TEST (Binary , SignedBinaryXor)
Definition at line 523 of file ram_arithmetic_test.cpp.
References souffle::BXOR, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BXOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 ^ arg2);
     }
 }
TEST() [94/107]
souffle::ram::test::TEST (Binary , UnsignedBinaryXor)
Definition at line 537 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBXOR.
{
     FunctorOp functor = FunctorOp::UBXOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 ^ arg2);
     }
 }
TEST() [95/107]
souffle::ram::test::TEST (Binary , SignedLogicalAnd)
Definition at line 551 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::LAND, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::LAND;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 || arg2);
     }
 }
TEST() [96/107]
souffle::ram::test::TEST (Binary , UnsignedLogicalAnd)
Definition at line 565 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::ULAND.
{
     FunctorOp functor = FunctorOp::ULAND;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 || arg2);
     }
 }
TEST() [97/107]
souffle::ram::test::TEST (IO_load , MixedTypesLoad)
Definition at line 573 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
{
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("meow  -3  3   0.5");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     VecOwn<Relation> rels;
     std::vector<std::string> attribs = {"l", "u", "b", "a"};
     std::vector<std::string> attribsTypes = {"s", "i", "u", "f"};
     Own<Relation> myrel = mk<Relation>("test", 4, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<Statement> main =
             mk<Sequence>(mk<IO>(std::move(ref1), readIoDirs), mk<IO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 meow    -3  3   0.5
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [98/107]
souffle::ram::test::TEST (Binary , SignedLogicalOr)
Definition at line 579 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::LOR, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::LOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 || arg2);
     }
 }
TEST() [99/107]
souffle::ram::test::TEST (Binary , UnsignedLogicalOr)
Definition at line 593 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::ULOR.
{
     FunctorOp functor = FunctorOp::ULOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 || arg2);
     }
 }
TEST() [100/107]
souffle::ram::test::TEST (MultiArg , Max)
Definition at line 607 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, and souffle::MAX.
                     {
     FunctorOp functor = FunctorOp::MAX;
     VecOwn<Expression> args;
     for (RamDomain i = 0; i <= 50; ++i) {
         args.push_back(mk<SignedConstant>(i));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(result, 50);
 }
TEST() [101/107]
souffle::ram::test::TEST (MultiArg , UnsignedMax)
Definition at line 620 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::ramBitCast(), and souffle::UMAX.
{
     FunctorOp functor = FunctorOp::UMAX;
     VecOwn<Expression> args;
     for (RamUnsigned i = 0; i <= 100; ++i) {
         args.push_back(mk<SignedConstant>(ramBitCast(i)));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamUnsigned>(result), 100);
 }
TEST() [102/107]
souffle::ram::test::TEST (MultiArg , FloatMax)
Definition at line 633 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, souffle::FMAX, i, and souffle::ramBitCast().
{
     FunctorOp functor = FunctorOp::FMAX;
     VecOwn<Expression> args;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(i))));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(100));
 }
TEST() [103/107]
souffle::ram::test::TEST (MultiArg , SymbolMax)
Definition at line 646 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::SymbolTable::lookup(), souffle::SymbolTable::resolve(), and souffle::SMAX.
{
     FunctorOp functor = FunctorOp::SMAX;
     VecOwn<Expression> args;
     SymbolTable symTab;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(mk<SignedConstant>(symTab.lookup(std::to_string(i))));
     }
     auto&& result = symTab.resolve(evalMultiArg(functor, std::move(args), symTab));
     EXPECT_EQ(result, "99");
 }
TEST() [104/107]
souffle::ram::test::TEST (MultiArg , Min)
Definition at line 661 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, and souffle::MIN.
                     {
     FunctorOp functor = FunctorOp::MIN;
     VecOwn<Expression> args;
     for (RamDomain i = 0; i <= 50; ++i) {
         args.push_back(mk<SignedConstant>(i));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(result, 0);
 }
TEST() [105/107]
souffle::ram::test::TEST (MultiArg , UnsignedMin)
Definition at line 674 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::ramBitCast(), and souffle::UMIN.
{
     FunctorOp functor = FunctorOp::UMIN;
     VecOwn<Expression> args;
     for (RamUnsigned i = 0; i <= 100; ++i) {
         args.push_back(mk<SignedConstant>(ramBitCast(i)));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamUnsigned>(result), 0);
 }
TEST() [106/107]
souffle::ram::test::TEST (MultiArg , FloatMin)
Definition at line 687 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, souffle::FMIN, i, and souffle::ramBitCast().
{
     FunctorOp functor = FunctorOp::FMIN;
     VecOwn<Expression> args;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(i))));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(-100));
 }
TEST() [107/107]
souffle::ram::test::TEST (MultiArg , SymbolMin)
Definition at line 700 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::SymbolTable::lookup(), souffle::SymbolTable::resolve(), and souffle::SMIN.
{
     FunctorOp functor = FunctorOp::SMIN;
     VecOwn<Expression> args;
     SymbolTable symTab;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(mk<SignedConstant>(symTab.lookup(std::to_string(i))));
     }
     auto&& result = symTab.resolve(evalMultiArg(functor, std::move(args), symTab));
     EXPECT_EQ(result, "-1");
 }
testInterpreterStore()
const std::string souffle::ram::test::testInterpreterStore (std::vector< std::string > attribs, std::vector< std::string > attribsTypes, VecOwn< Expression > exprs)
Definition at line 55 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), souffle::main(), and types.
Referenced by TEST().
{
     Global::config().set("jobs", "1");
     const size_t arity = attribs.size();
     VecOwn<Relation> rels;
     Own<Relation> myrel =
             mk<Relation>("test", arity, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Own<RelationReference> ref1 = mk<RelationReference>(myrel.get());
     Own<RelationReference> ref2 = mk<RelationReference>(myrel.get());
     Json types = Json::object{{"relation",
             Json::object{{"arity", static_cast<long long>(arity)}, {"auxArity", static_cast<long long>(0)},
                     {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     Own<Statement> main = mk<Sequence>(
             mk<Query>(mk<Project>(std::move(ref1), std::move(exprs))), mk<IO>(std::move(ref2), ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<InterpreterEngine> interpreter = mk<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     return sout.str();
 }