souffle: souffle::ram Namespace Reference
souffle::ram Namespace Reference
Namespaces
analysis
detail
test
transform
Data Structures
class AbstractAggregate
Abstract class for aggregation.
class AbstractChoice
Abstract class for a choice operation.
class AbstractConditional
Abstract conditional statement.
class AbstractExistenceCheck
Abstract existence check for a tuple in a relation.
class AbstractLog
Abstract class for logging.
class AbstractOperator
Abstract class for an operator/functor.
class AbstractParallel
Abstract class for parallel operation.
class Aggregate
Aggregation function applied on some relation.
class AutoIncrement
Increment a counter and return its value.
class BinRelationStatement
Abstract class for a binary relation.
class Break
Breaks out of the loop if a condition holds.
class Call
Call a subroutine.
class Choice
Find a tuple in a relation such that a given condition holds.
class Clear
Delete tuples of a relation.
class Condition
Abstract class for conditions and boolean values in RAM.
class Conjunction
A conjunction of conditions.
class Constant
Represents a Ram Constant.
class Constraint
Evaluates a binary constraint with respect to two Expressions.
class DebugInfo
Debug statement.
class EmptinessCheck
Emptiness check for a relation.
class ExistenceCheck
Existence check for a tuple(-pattern) in a relation.
class Exit
Exit statement for a loop.
class Expression
Abstract class for describing scalar values in RAM.
class Extend
Extend equivalence relation.
class False
class Filter
Checks whether a given condition holds.
class FloatConstant
Represents a float constant.
class IndexAggregate
Indexed aggregation on a relation.
class IndexChoice
Use an index to find a tuple in a relation such that a given condition holds.
class IndexOperation
class IndexScan
Search for tuples of a relation matching a criteria.
class IntrinsicOperator
Operator that represents an intrinsic (built-in) functor.
class IO
I/O statement for a relation.
class LambdaNodeMapper
A special NodeMapper wrapping a lambda conducting node transformations.
class ListStatement
Abstract class for a list of RAM statements.
class LogRelationTimer
Execution time logger for a statement.
class LogSize
Log relation size and a logging message.
class LogTimer
Execution time logger for a statement.
class Loop
Execute statement until statement terminates loop via an exit statement.
class Negation
Negates a given condition.
class NestedIntrinsicOperator
Effectively identical to IntrinsicOperator, except it can produce multiple results.
class NestedOperation
Abstract class for a nesting operations in a loop-nest.
class Node
Node is a superclass for all RAM IR classes.
class NodeMapper
An abstract class for manipulating RAM Nodes by substitution.
class Operation
Abstract class for a relational algebra operation.
class PackRecord
Packs a record's arguments into a reference.
class Parallel
Parallel block of statements.
class ParallelAggregate
Parallel Aggregation function applied on some relation.
class ParallelChoice
Find a tuple in a relation such that a given condition holds in parallel.
class ParallelIndexAggregate
Aggregate over values of a relation using an index in parallel.
class ParallelIndexChoice
Use an index to find a tuple in a relation such that a given condition holds in parallel.
class ParallelIndexScan
Search for tuples of a relation matching a criteria.
class ParallelScan
Iterate all tuples of a relation in parallel.
class Program
RAM program relation declaration and functions.
class Project
Project a result into the target relation.
class ProvenanceExistenceCheck
Provenance Existence check for a relation.
class Query
A relational algebra query.
struct ram_visitor_tag
A tag type required for the is_ram_visitor type trait to identify RamVisitors.
class Relation
Index.
class RelationOperation
Abstract class for operations on relations.
class RelationReference
A RAM Relation in the RAM intermediate representation.
class RelationSize
Returns the numbers of tuples in a relation.
class RelationStatement
RAM Statements with a single relation.
class Scan
Iterate all tuples of a relation.
class Sequence
Sequence of RAM statements.
class SignedConstant
Represents a signed constant.
class Statement
Abstract class for RAM statements.
class SubroutineArgument
Access argument of a subroutine.
class SubroutineReturn
A statement for returning from a ram subroutine.
class Swap
Swap operation with respect to two relations.
class TestAutoIndex
class TranslationUnit
Translating a RAM program.
class True
False value condition.
class TupleElement
Access element from the current tuple in a tuple environment.
class TupleOperation
Abstract class for relation searches and lookups.
class UndefValue
An undefined expression.
class UnpackRecord
Record lookup.
class UnsignedConstant
Represents a unsigned constant.
class UserDefinedOperator
Operator that represents an extrinsic (user-defined) functor.
struct Visitor
The generic base type of all RamVisitors realizing the dispatching of visitor calls.
Typedefs
using Nodes = MinIndexSelection::SearchSet
using RamBound = VecOwn< Expression >
Pattern type for lower/upper bound.
using RamPattern = std::pair< RamBound, RamBound >
Enumerations
enum NestedIntrinsicOp { NestedIntrinsicOp::RANGE, NestedIntrinsicOp::URANGE, NestedIntrinsicOp::FRANGE }
Functions
bool isTrue (const Condition *cond)
Determines if a condition represents true.
bool isUndefValue (const Expression *expr)
Determines if an expression represents an undefined value.
template<typename Lambda >
LambdaNodeMapper< Lambda > makeLambdaRamMapper (const Lambda &lambda)
Creates a node mapper based on a corresponding lambda expression.
std::ostream & operator<< (std::ostream &os, NestedIntrinsicOp e)
SearchSignature setBits (size_t arity, uint64_t mask)
TEST (Tuple, Basic)
TEST (Tuple, Assign)
TEST (Matching, StaticTest_1)
TEST (Tuple, Compare)
TEST (Tuple, CompareSpeed)
TEST (Matching, StaticTest_2)
TEST (Matching, TestOver64BitSignature)
Own< Condition > toCondition (const VecOwn< Condition > &conds)
Convert list of conditions to a conjunction.
VecOwn< Condition > toConjunctionList (const Condition *condition)
Convert terms of a conjunction to a list.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirst (const Node &root, Visitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the RAM fragments rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
template<typename R , typename N >
void visitDepthFirst (const Node &root, const std::function< R(const N &)> &fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type>
std::enable_if<!detail::is_ram_visitor< Lambda >::value, void >::type visitDepthFirst (const Node &root, const Lambda &fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirstPreOrder (const Node &root, Visitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Typedef Documentation
Nodes
using souffle::ram::Nodes = typedef MinIndexSelection::SearchSet
Definition at line 36 of file matching_test.cpp.
RamBound
typedef VecOwn< Expression > souffle::ram::RamBound
Pattern type for lower/upper bound.
Definition at line 37 of file IndexOperation.h.
RamPattern
typedef std::pair< RamBound, RamBound > souffle::ram::RamPattern
Definition at line 38 of file IndexOperation.h.
Enumeration Type Documentation
NestedIntrinsicOp
enum souffle::ram::NestedIntrinsicOp strong
Enumerator
RANGE
URANGE
FRANGE
Definition at line 34 of file NestedIntrinsicOperator.h.
{
     RANGE,
     URANGE,
     FRANGE,
 };
Function Documentation
isTrue()
bool souffle::ram::isTrue (const Condition * cond) inline
Determines if a condition represents true.
Definition at line 39 of file Utils.h.
Referenced by souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::ParallelAggregate::print(), souffle::ram::ParallelIndexAggregate::print(), souffle::ram::Aggregate::print(), souffle::ram::IndexAggregate::print(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteScan().
{
     return isA<True>(cond);
 }
isUndefValue()
bool souffle::ram::isUndefValue (const Expression * expr) inline
Determines if an expression represents an undefined value.
Definition at line 34 of file Utils.h.
Referenced by souffle::ram::transform::MakeIndexTransformer::constructPattern(), souffle::synthesiser::Synthesiser::emitCode(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::ram::analysis::IndexAnalysis::getSearchSignature(), souffle::ram::analysis::IndexAnalysis::isTotalSignature(), souffle::ram::analysis::IndexAnalysis::print(), souffle::ram::IndexOperation::printIndex(), souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and souffle::NodeGenerator::visitExistenceCheck().
{
     return isA<UndefValue>(expr);
 }
makeLambdaRamMapper()
template<typename Lambda > LambdaNodeMapper<Lambda> souffle::ram::makeLambdaRamMapper (const Lambda & lambda)
Creates a node mapper based on a corresponding lambda expression.
Definition at line 61 of file LambdaNodeMapper.h.
References souffle::ram::LambdaNodeMapper< Lambda >::lambda.
Referenced by souffle::ram::Program::clone(), souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::ram::transform::IfConversionTransformer::convertIndexScans(), souffle::ram::transform::ChoiceConversionTransformer::convertScans(), souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::ram::transform::ExpandFilterTransformer::expandFilters(), souffle::ram::transform::HoistAggregateTransformer::hoistAggregate(), souffle::ram::transform::HoistConditionsTransformer::hoistConditions(), souffle::ram::transform::MakeIndexTransformer::makeIndex(), souffle::ram::transform::ParallelTransformer::parallelizeOperations(), souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak(), souffle::ram::transform::TupleIdTransformer::reorderOperations(), souffle::ram::Node::rewrite(), and souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter().
{
     return LambdaNodeMapper<Lambda>(lambda);
 }
operator<<()
std::ostream& souffle::ram::operator<< (std::ostream & os, NestedIntrinsicOp e) inline
Definition at line 40 of file NestedIntrinsicOperator.h.
References souffle::fatal(), FRANGE, RANGE, and URANGE.
{
     switch (e) {
         case NestedIntrinsicOp::RANGE: return os << "RANGE";
         case NestedIntrinsicOp::URANGE: return os << "URANGE";
         case NestedIntrinsicOp::FRANGE: return os << "FRANGE";
         default: fatal("invalid Operation");
     }
 }
setBits()
SearchSignature souffle::ram::setBits (size_t arity, uint64_t mask)
Definition at line 38 of file matching_test.cpp.
References souffle::ram::analysis::Equal, and i.
Referenced by TEST().
{
     SearchSignature search(arity);
     for (size_t i = 0; i < arity; ++i) {
         if (mask % 2) {
             search[i] = AttributeConstraint::Equal;
         }
         mask /= 2;
     }
     return search;
 }
TEST() [1/7]
souffle::ram::TEST (Tuple , Basic)
Definition at line 28 of file compiled_tuple_test.cpp.
References EXPECT_EQ.
                    {
     Tuple<int, 3> t = {{1, 3, 2}};
     EXPECT_EQ(3 * sizeof(int), sizeof(t));
     std::cout << t << "\n";
     Tuple<int, 2> t2 = {{1, 5}};
     EXPECT_EQ(2 * sizeof(int), sizeof(t2));
     std::cout << t2 << "\n";
 }
TEST() [2/7]
souffle::ram::TEST (Tuple , Assign)
Definition at line 40 of file compiled_tuple_test.cpp.
References EXPECT_EQ, and EXPECT_NE.
                     {
     Tuple<int, 3> t1 = {{1, 2, 3}};
     Tuple<int, 3> t2 = {{3, 2, 1}};
     Tuple<int, 3> t3 = t1;
     EXPECT_NE(t1, t2);
     EXPECT_EQ(t1, t3);
     EXPECT_NE(t2, t3);
     t3 = t2;
     EXPECT_NE(t1, t2);
     EXPECT_NE(t1, t3);
     EXPECT_EQ(t2, t3);
 }
TEST() [3/7]
souffle::ram::TEST (Matching , StaticTest_1)
Definition at line 49 of file matching_test.cpp.
References souffle::ram::analysis::MinIndexSelection::addSearch(), EXPECT_EQ, souffle::ram::TestAutoIndex::getNumMatchings(), setBits(), and souffle::ram::analysis::MinIndexSelection::solve().
{
     TestAutoIndex order;
     Nodes nodes;
     size_t arity = 5;
     uint64_t patterns[] = {1, 3, 5, 7, 15, 23, 31};
     for (auto pattern : patterns) {
         SearchSignature search = setBits(arity, pattern);
         order.addSearch(search);
         nodes.insert(search);
     }
     order.solve();
     int num = order.getNumMatchings();
     EXPECT_EQ(num, 5);
 }
TEST() [4/7]
souffle::ram::TEST (Tuple , Compare)
Definition at line 57 of file compiled_tuple_test.cpp.
References EXPECT_LT.
                      {
     Tuple<int, 2> t1 = {{1, 2}};
     Tuple<int, 2> t2 = {{2, 1}};
     EXPECT_LT(t1, t2);
 }
TEST() [5/7]
souffle::ram::TEST (Tuple , CompareSpeed)
Definition at line 64 of file compiled_tuple_test.cpp.
References EXPECT_EQ.
{
     // was used to evaluate various implementations of the == operator
     Tuple<int, 2> t1 = {{1, 2}};
     Tuple<int, 2> t2 = {{2, 1}};
     uint32_t res = 0;
     while (true) {
         res += !(t1 == t2);
         if (res & 0x10000000llu) break;
     }
     EXPECT_EQ(268435456llu, res);
 }
TEST() [6/7]
souffle::ram::TEST (Matching , StaticTest_2)
Definition at line 67 of file matching_test.cpp.
References souffle::ram::analysis::MinIndexSelection::addSearch(), EXPECT_EQ, souffle::ram::TestAutoIndex::getNumMatchings(), setBits(), and souffle::ram::analysis::MinIndexSelection::solve().
{
     TestAutoIndex order;
     Nodes nodes;
     size_t arity = 7;
     uint64_t patterns[] = {7, 11, 23, 32, 33, 39, 49, 53, 104, 121};
     for (auto pattern : patterns) {
         SearchSignature search = setBits(arity, pattern);
         order.addSearch(search);
         nodes.insert(search);
     }
     order.solve();
     int num = order.getNumMatchings();
     EXPECT_EQ(num, 5);
 }
TEST() [7/7]
souffle::ram::TEST (Matching , TestOver64BitSignature)
Definition at line 86 of file matching_test.cpp.
References souffle::ram::analysis::MinIndexSelection::addSearch(), souffle::ram::analysis::Equal, EXPECT_EQ, souffle::ram::TestAutoIndex::getNumMatchings(), and souffle::ram::analysis::MinIndexSelection::solve().
{
     TestAutoIndex order;
     Nodes nodes;
     size_t arity = 100;
     SearchSignature first(arity);
     first[99] = AttributeConstraint::Equal;
     first[75] = AttributeConstraint::Equal;
     first[50] = AttributeConstraint::Equal;
     first[25] = AttributeConstraint::Equal;
     first[0] = AttributeConstraint::Equal;
     SearchSignature second(arity);
     second[99] = AttributeConstraint::Equal;
     second[75] = AttributeConstraint::Equal;
     second[50] = AttributeConstraint::Equal;
     SearchSignature third(arity);
     third[99] = AttributeConstraint::Equal;
     third[75] = AttributeConstraint::Equal;
     SearchSignature fourth(arity);
     fourth[99] = AttributeConstraint::Equal;
     SearchSignature fifth(arity);
     fifth[25] = AttributeConstraint::Equal;
     fifth[0] = AttributeConstraint::Equal;
     nodes.insert(first);
     nodes.insert(second);
     nodes.insert(third);
     nodes.insert(fourth);
     nodes.insert(fifth);
     order.addSearch(first);
     order.addSearch(second);
     order.addSearch(third);
     order.addSearch(fourth);
     order.addSearch(fifth);
     order.solve();
     int num = order.getNumMatchings();
     EXPECT_EQ(num, 3);
 }
toCondition()
Own<Condition> souffle::ram::toCondition (const VecOwn< Condition > & conds) inline
Convert list of conditions to a conjunction.
Parameters
A list of RAM conditions
A RAM condition
Convert a list {C1, C2, ..., Cn} to a condition of the format C1 /\ C2 /\ ... /\ Cn.
Definition at line 78 of file Utils.h.
References souffle::clone().
Referenced by souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::synthesiser::Synthesiser::emitCode(), and souffle::ram::transform::ReorderConditionsTransformer::reorderConditions().
{
     Own<Condition> result;
     for (auto const& cur : conds) {
         if (result == nullptr) {
             result = souffle::clone(cur);
         } else {
             result = mk<Conjunction>(std::move(result), souffle::clone(cur));
         }
     }
     return result;
 }
toConjunctionList()
VecOwn<Condition> souffle::ram::toConjunctionList (const Condition * condition) inline
Convert terms of a conjunction to a list.
Parameters
conds A RAM condition
Returns
A list of RAM conditions
Convert a condition of the format C1 /\ C2 /\ ... /\ Cn to a list {C1, C2, ..., Cn}.
Definition at line 51 of file Utils.h.
References souffle::ram::Condition::clone().
Referenced by souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::synthesiser::Synthesiser::emitCode(), souffle::ram::transform::ExpandFilterTransformer::expandFilters(), souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), souffle::ram::transform::MakeIndexTransformer::rewriteAggregate(), souffle::ram::transform::MakeIndexTransformer::rewriteIndexScan(), and souffle::ram::transform::MakeIndexTransformer::rewriteScan().
{
     VecOwn<Condition> conditionList;
     std::queue<const Condition*> conditionsToProcess;
     if (condition != nullptr) {
         conditionsToProcess.push(condition);
         while (!conditionsToProcess.empty()) {
             condition = conditionsToProcess.front();
             conditionsToProcess.pop();
             if (const auto* ramConj = dynamic_cast<const Conjunction*>(condition)) {
                 conditionsToProcess.push(&ramConj->getLHS());
                 conditionsToProcess.push(&ramConj->getRHS());
             } else {
                 conditionList.emplace_back(condition->clone());
             }
         }
     }
     return conditionList;
 }
visitDepthFirst() [1/3]
template<typename R , typename... Ps, typename... Args> void souffle::ram::visitDepthFirst (const Node & root, Visitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the RAM fragments rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the RAM fragments to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 352 of file Visitor.h.
References visitDepthFirstPreOrder().
Referenced by souffle::ram::transform::CollapseFiltersTransformer::collapseFilters(), souffle::ram::transform::IfConversionTransformer::convertIndexScans(), souffle::ram::transform::ChoiceConversionTransformer::convertScans(), souffle::ram::transform::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::InterpreterEngine::executeMain(), souffle::ram::transform::ExpandFilterTransformer::expandFilters(), souffle::ram::transform::HoistAggregateTransformer::hoistAggregate(), souffle::ram::transform::HoistConditionsTransformer::hoistConditions(), souffle::ram::transform::MakeIndexTransformer::makeIndex(), souffle::ram::transform::ParallelTransformer::parallelizeOperations(), souffle::ram::transform::ReorderConditionsTransformer::reorderConditions(), souffle::ram::transform::ReorderFilterBreak::reorderFilterBreak(), souffle::ram::transform::TupleIdTransformer::reorderOperations(), souffle::ram::transform::IfConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ram::transform::ChoiceConversionTransformer::rewriteScan(), souffle::ram::analysis::IndexAnalysis::run(), souffle::ram::transform::IndexedInequalityTransformer::transformIndexToFilter(), and visitDepthFirst().
{
     visitDepthFirstPreOrder(root, visitor, args...);
 }
visitDepthFirst() [2/3]
template<typename R , typename N > void souffle::ram::visitDepthFirst (const Node & root, const std::function< R(const N &)> & fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the RAM fragment to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 406 of file Visitor.h.
References souffle::ram::detail::makeLambdaVisitor().
{
     auto visitor = detail::makeLambdaVisitor(fun);
     visitDepthFirst<void>(root, visitor);
 }
visitDepthFirst() [3/3]
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type> std::enable_if<!detail::is_ram_visitor<Lambda>::value, void>::type souffle::ram::visitDepthFirst (const Node & root, const Lambda & fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the RAM fragment to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 422 of file Visitor.h.
References visitDepthFirst().
{
     visitDepthFirst(root, std::function<R(const N&)>(fun));
 }
visitDepthFirstPreOrder()
template<typename R , typename... Ps, typename... Args> void souffle::ram::visitDepthFirstPreOrder (const Node & root, Visitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the RAM fragment to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 333 of file Visitor.h.
References souffle::ram::Node::getChildNodes().
Referenced by visitDepthFirst().
{
     visitor(root, args...);
     for (const Node* cur : root.getChildNodes()) {
         if (cur != nullptr) {
             visitDepthFirstPreOrder(*cur, visitor, args...);
         }
     }
 }