souffle: souffle::detail::fix_upper_bound< Pos, Dim > Struct Template Reference
souffle::detail::fix_upper_bound< Pos, Dim > Struct Template Reference
A functor initializing an iterator upon creation to reference the first element within a given Trie being greater than a given value .
#include <Brie.h>
Public Member Functions
template<unsigned bits, typename iterator , typename entry_type >
bool operator() (const SparseBitMap< bits > &store, iterator &iter, const entry_type &entry) const
template<typename Store , typename iterator , typename entry_type >
bool operator() (const Store &store, iterator &iter, const entry_type &entry) const
Detailed Description
template<unsigned Pos, unsigned Dim>
struct souffle::detail::fix_upper_bound< Pos, Dim >
A functor initializing an iterator upon creation to reference the first element within a given Trie being greater than a given value .
Definition at line 2215 of file Brie.h.
Member Function Documentation
operator()() [1/2]
template<unsigned Pos, unsigned Dim> template<unsigned bits, typename iterator , typename entry_type > bool souffle::detail::fix_upper_bound< Pos, Dim >::operator() (const SparseBitMap< bits > & store, iterator & iter, const entry_type & entry) const inline
Definition at line 2217 of file Brie.h.
References souffle::SparseBitMap< BITS >::end(), and souffle::SparseBitMap< BITS >::upper_bound().
{
         // search in current level
         auto cur = store.upper_bound(entry[Pos]);
         if (cur == store.end()) {
             return false;
         }
         get_nested_iter_core<Pos>()(iter.iter_core).setIterator(cur);
         assert(entry[Pos] <= RamDomain(*cur));
         iter.value[Pos] = *cur;
         // no more remaining levels to fix
         return true;
     }
operator()() [2/2]
template<unsigned Pos, unsigned Dim> template<typename Store , typename iterator , typename entry_type > bool souffle::detail::fix_upper_bound< Pos, Dim >::operator() (const Store & store, iterator & iter, const entry_type & entry) const inline
Definition at line 2235 of file Brie.h.
References i, and souffle::ast::analysis::sub().
{
         // search in current level (if it is not the last level, we need a lower bound)
         auto cur = store.lowerBound(entry[Pos]);
         // if no lower boundary is found, be done
         if (cur == store.end()) {
             return false;
         }
         assert(RamDomain(cur->first) >= entry[Pos]);
         // if the lower bound is higher than the requested value, go to first in subtree
         if (RamDomain(cur->first) > entry[Pos]) {
             get_nested_iter_core<Pos>()(iter.iter_core).setIterator(cur);
             iter.value[Pos] = cur->first;
             fix_first<Pos + 1, Dim>()(cur->second->getStore(), iter);
             return true;
         }
         // attempt to fix the rest
         if (!fix_upper_bound<Pos + 1, Dim>()(cur->second->getStore(), iter, entry)) {
             // if it does not work, since there are no matching elements in this branch, go to next
             entry_type sub = entry;
             sub[Pos] += 1;
             for (size_t i = Pos + 1; i < Dim; ++i) {
                 sub[i] = 0;
             }
             return (*this)(store, iter, sub);
         }
         // remember result
         get_nested_iter_core<Pos>()(iter.iter_core).setIterator(cur);
         // update iterator value
         iter.value[Pos] = cur->first;
         // done!
         return true;
     }
The documentation for this struct was generated from the following file:
include/souffle/datastructure/Brie.h