souffle: souffle::ast::transform::SemanticCheckerImpl Struct Reference
souffle::ast::transform::SemanticCheckerImpl Struct Reference
Public Member Functions
SemanticCheckerImpl (TranslationUnit &tu)
Data Fields
TranslationUnit & tu
Private Member Functions
void checkADT (const ast::AlgebraicDataType &type)
void checkAggregator (const Aggregator &aggregator)
void checkArgument (const Argument &arg)
void checkAtom (const Atom &atom)
void checkBranchInits ()
check if all the branches refer to the existing types.
void checkClause (const Clause &clause)
void checkComplexRule (std::set< const Clause *> multiRule)
void checkConstant (const Argument &argument)
void checkFact (const Clause &fact)
void checkInlining ()
void checkIO ()
void checkLiteral (const Literal &literal)
void checkNamespaces ()
void checkRecordType (const ast::RecordType &type)
void checkRelation (const Relation &relation)
void checkRelationDeclaration (const Relation &relation)
void checkSubsetType (const ast::SubsetType &type)
void checkTypesDeclarations ()
void checkUnionType (const ast::UnionType &type)
void checkWitnessProblem ()
bool isDependent (const Clause &agg1, const Clause &agg2)
agg1, agg2 are clauses which contain no head, and consist of a single literal that contains an aggregate.
Private Attributes
const IOTypeAnalysis & ioTypes = *tu.getAnalysis<IOTypeAnalysis>()
const PrecedenceGraphAnalysis & precedenceGraph = *tu.getAnalysis<PrecedenceGraphAnalysis>()
const Program & program = tu.getProgram()
const RecursiveClausesAnalysis & recursiveClauses = *tu.getAnalysis<RecursiveClausesAnalysis>()
ErrorReport & report = tu.getErrorReport()
const SCCGraphAnalysis & sccGraph = *tu.getAnalysis<SCCGraphAnalysis>()
const SumTypeBranchesAnalysis & sumTypesBranches = *tu.getAnalysis<SumTypeBranchesAnalysis>()
const TypeEnvironment & typeEnv = typeEnvAnalysis.getTypeEnvironment()
const TypeEnvironmentAnalysis & typeEnvAnalysis = *tu.getAnalysis<TypeEnvironmentAnalysis>()
Detailed Description
Definition at line 99 of file SemanticChecker.cpp.
Constructor & Destructor Documentation
SemanticCheckerImpl()
souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl (TranslationUnit & tu)
Definition at line 180 of file SemanticChecker.cpp.
References souffle::ErrorReport::addDiagnostic(), souffle::ast::QualifiedName::append(), checkBranchInits(), checkClause(), checkComplexRule(), checkInlining(), checkIO(), checkNamespaces(), checkRelation(), checkTypesDeclarations(), checkWitnessProblem(), souffle::Global::config(), souffle::Diagnostic::ERROR, souffle::ast::Program::getClauses(), souffle::ast::analysis::SCCGraphAnalysis::getInternalRelations(), souffle::ast::Relation::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::Program::getRelations(), souffle::ast::analysis::SCCGraphAnalysis::getSCC(), souffle::ast::Node::getSrcLoc(), souffle::ast::hasClauseWithAggregatedRelation(), souffle::ast::hasClauseWithNegatedRelation(), i, souffle::ast::analysis::SCCGraphAnalysis::isRecursive(), souffle::join(), souffle::splitString(), souffle::SUPPRESSED, souffle::toString(), and souffle::ast::transform::GroundedTermsChecker::verify().
                                                             : tu(tu) {
     // suppress warnings for given relations
     if (Global::config().has("suppress-warnings")) {
         std::vector<std::string> suppressedRelations =
                 splitString(Global::config().get("suppress-warnings"), ',');
         if (std::find(suppressedRelations.begin(), suppressedRelations.end(), "*") !=
                 suppressedRelations.end()) {
             // mute all relations
             for (Relation* rel : program.getRelations()) {
                 rel->addQualifier(RelationQualifier::SUPPRESSED);
             }
         } else {
             // mute only the given relations (if they exist)
             for (auto& relname : suppressedRelations) {
                 const std::vector<std::string> comps = splitString(relname, '.');
                 if (!comps.empty()) {
                     // generate the relation identifier
                     QualifiedName relid(comps[0]);
                     for (size_t i = 1; i < comps.size(); i++) {
                         relid.append(comps[i]);
                     }
                     // update suppressed qualifier if the relation is found
                     if (Relation* rel = getRelation(program, relid)) {
                         rel->addQualifier(RelationQualifier::SUPPRESSED);
                     }
                 }
             }
         }
     }
     checkTypesDeclarations();
     checkBranchInits();
     // check rules
     for (auto* rel : program.getRelations()) {
         checkRelation(*rel);
     }
     for (auto* clause : program.getClauses()) {
         checkClause(*clause);
     }
     // Group clauses that stem from a single complex rule
     // with multiple headers/disjunction etc. The grouping
     // is performed via their source-location.
     std::map<SrcLocation, std::set<const Clause*>> multiRuleMap;
     for (auto* clause : program.getClauses()) {
         // collect clauses of a multi rule, i.e., they have the same source locator
         multiRuleMap[clause->getSrcLoc()].insert(clause);
     }
     // check complex rule
     for (const auto& multiRule : multiRuleMap) {
         checkComplexRule(multiRule.second);
     }
     checkNamespaces();
     checkIO();
     checkWitnessProblem();
     checkInlining();
     // Run grounded terms checker
     GroundedTermsChecker().verify(tu);
     // Check types
     TypeChecker{tu}.run();
     // - stratification --
     // check for cyclic dependencies
     for (Relation* cur : program.getRelations()) {
         size_t scc = sccGraph.getSCC(cur);
         if (sccGraph.isRecursive(scc)) {
             for (const Relation* cyclicRelation : sccGraph.getInternalRelations(scc)) {
                 // Negations and aggregations need to be stratified
                 const Literal* foundLiteral = nullptr;
                 bool hasNegation = hasClauseWithNegatedRelation(cyclicRelation, cur, &program, foundLiteral);
                 if (hasNegation ||
                         hasClauseWithAggregatedRelation(cyclicRelation, cur, &program, foundLiteral)) {
                     auto const& relSet = sccGraph.getInternalRelations(scc);
                     std::set<const Relation*, NameComparison> sortedRelSet(relSet.begin(), relSet.end());
                     // Negations and aggregations need to be stratified
                     std::string relationsListStr = toString(join(sortedRelSet, ",",
                             [](std::ostream& out, const Relation* r) { out << r->getQualifiedName(); }));
                     std::vector<DiagnosticMessage> messages;
                     messages.push_back(DiagnosticMessage(
                             "Relation " + toString(cur->getQualifiedName()), cur->getSrcLoc()));
                     std::string negOrAgg = hasNegation ? "negation" : "aggregation";
                     messages.push_back(
                             DiagnosticMessage("has cyclic " + negOrAgg, foundLiteral->getSrcLoc()));
                     report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR,
                             DiagnosticMessage("Unable to stratify relation(s) {" + relationsListStr + "}"),
                             messages));
                     break;
                 }
             }
         }
     }
 }
Member Function Documentation
checkADT()
void souffle::ast::transform::SemanticCheckerImpl::checkADT (const ast::AlgebraicDataType & type) private
Definition at line 724 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::ast::AlgebraicDataType::getBranches(), and souffle::ast::analysis::TypeEnvironment::isType().
Referenced by checkTypesDeclarations().
{
     // check if all branches contain properly defined types.
     for (auto* branch : type.getBranches()) {
         for (auto* field : branch->getFields()) {
             if (!typeEnv.isType(field->getTypeName())) {
                 report.addError(tfm::format("Undefined type %s in definition of branch %s",
                                         field->getTypeName(), branch->getConstructor()),
                         field->getSrcLoc());
             }
         }
     }
 }
checkAggregator()
void souffle::ast::transform::SemanticCheckerImpl::checkAggregator (const Aggregator & aggregator) private
Definition at line 404 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Clause::addToBody(), checkLiteral(), souffle::clone(), souffle::ast::Aggregator::getBodyLiterals(), souffle::ast::TranslationUnit::getErrorReport(), souffle::ast::TranslationUnit::getProgram(), souffle::ast::Node::getSrcLoc(), isDependent(), and souffle::ast::visitDepthFirst().
Referenced by checkArgument().
{
     auto& report = tu.getErrorReport();
     const Program& program = tu.getProgram();
     Clause dummyClauseAggregator;
     visitDepthFirst(program, [&](const Literal& parentLiteral) {
         visitDepthFirst(parentLiteral, [&](const Aggregator& candidateAggregate) {
             if (candidateAggregate != aggregator) {
                 return;
             }
             // Get the literal containing the aggregator and put it into a dummy clause
             // so we can get information about groundedness
             dummyClauseAggregator.addToBody(souffle::clone(&parentLiteral));
         });
     });
     visitDepthFirst(program, [&](const Literal& parentLiteral) {
         visitDepthFirst(parentLiteral, [&](const Aggregator& /* otherAggregate */) {
             // Create the other aggregate's dummy clause
             Clause dummyClauseOther;
             dummyClauseOther.addToBody(souffle::clone(&parentLiteral));
             // Check dependency between the aggregator and this one
             if (isDependent(dummyClauseAggregator, dummyClauseOther) &&
                     isDependent(dummyClauseOther, dummyClauseAggregator)) {
                 report.addError("Mutually dependent aggregate", aggregator.getSrcLoc());
             }
         });
     });
     for (Literal* literal : aggregator.getBodyLiterals()) {
         checkLiteral(*literal);
     }
 }
checkArgument()
void souffle::ast::transform::SemanticCheckerImpl::checkArgument (const Argument & arg) private
Definition at line 438 of file SemanticChecker.cpp.
References souffle::all_of(), checkAggregator(), and souffle::fatal().
Referenced by checkAtom(), and checkLiteral().
{
     if (const auto* agg = dynamic_cast<const Aggregator*>(&arg)) {
         checkAggregator(*agg);
     } else if (const auto* func = dynamic_cast<const Functor*>(&arg)) {
         for (auto arg : func->getArguments()) {
             checkArgument(*arg);
         }
     }
 }
checkAtom()
void souffle::ast::transform::SemanticCheckerImpl::checkAtom (const Atom & atom) private
Definition at line 281 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkArgument(), souffle::ast::Atom::getArguments(), souffle::ast::Atom::getArity(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::Node::getSrcLoc(), and souffle::toString().
Referenced by checkClause(), and checkLiteral().
{
     // check existence of relation
     auto* r = getRelation(program, atom.getQualifiedName());
     if (r == nullptr) {
         report.addError("Undefined relation " + toString(atom.getQualifiedName()), atom.getSrcLoc());
         return;
     }
     if (r->getArity() != atom.getArity()) {
         report.addError(
                 "Mismatching arity of relation " + toString(atom.getQualifiedName()), atom.getSrcLoc());
     }
     for (const Argument* arg : atom.getArguments()) {
         checkArgument(*arg);
     }
 }
checkBranchInits()
void souffle::ast::transform::SemanticCheckerImpl::checkBranchInits () private
check if all the branches refer to the existing types.
Definition at line 299 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::contains(), tinyformat::format(), souffle::ast::Program::getClauses(), souffle::ast::analysis::SumTypeBranchesAnalysis::getType(), and souffle::ast::visitDepthFirst().
Referenced by SemanticCheckerImpl().
{
     visitDepthFirst(program.getClauses(), [&](const BranchInit& adt) {
         auto* type = sumTypesBranches.getType(adt.getConstructor());
         if (type == nullptr) {
             report.addError("Undeclared branch", adt.getSrcLoc());
             return;
         }
         size_t declaredArity =
                 as<analysis::AlgebraicDataType>(type)->getBranchTypes(adt.getConstructor()).size();
         size_t branchArity = adt.getArguments().size();
         if (declaredArity != branchArity) {
             report.addError(tfm::format("Invalid arity, the declared arity of %s is %s", adt.getConstructor(),
                                     declaredArity),
                     adt.getSrcLoc());
             return;
         }
     });
 }
checkClause()
void souffle::ast::transform::SemanticCheckerImpl::checkClause (const Clause & clause) private
Definition at line 499 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ErrorReport::addWarning(), checkAtom(), checkFact(), checkLiteral(), souffle::contains(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getExecutionPlan(), souffle::ast::Clause::getHead(), souffle::ast::ExecutionPlan::getOrders(), souffle::ast::Node::getSrcLoc(), i, souffle::ast::isFact(), souffle::ast::analysis::RecursiveClausesAnalysis::recursive(), and souffle::ast::visitDepthFirst().
Referenced by SemanticCheckerImpl().
{
     // check head atom
     checkAtom(*clause.getHead());
     // Check for absence of underscores in head
     for (auto* unnamed : getUnnamedVariables(*clause.getHead())) {
         report.addError("Underscore in head of rule", unnamed->getSrcLoc());
     }
     // check body literals
     for (Literal* lit : clause.getBodyLiterals()) {
         checkLiteral(*lit);
     }
     // check facts
     if (isFact(clause)) {
         checkFact(clause);
     }
     // check whether named unnamed variables of the form _<ident>
     // are only used once in a clause; if not, warnings will be
     // issued.
     std::map<std::string, int> var_count;
     std::map<std::string, const ast::Variable*> var_pos;
     visitDepthFirst(clause, [&](const ast::Variable& var) {
         var_count[var.getName()]++;
         var_pos[var.getName()] = &var;
     });
     for (const auto& cur : var_count) {
         int numAppearances = cur.second;
         const auto& varName = cur.first;
         const auto& varLocation = var_pos[varName]->getSrcLoc();
         if (varName[0] == '_') {
             assert(varName.size() > 1 && "named variable should not be a single underscore");
             if (numAppearances > 1) {
                 report.addWarning("Variable " + varName + " marked as singleton but occurs more than once",
                         varLocation);
             }
         }
     }
     // check execution plan
     if (clause.getExecutionPlan() != nullptr) {
         auto numAtoms = getBodyLiterals<Atom>(clause).size();
         for (const auto& cur : clause.getExecutionPlan()->getOrders()) {
             bool isComplete = true;
             auto order = cur.second->getOrder();
             for (unsigned i = 1; i <= order.size(); i++) {
                 if (!contains(order, i)) {
                     isComplete = false;
                     break;
                 }
             }
             if (order.size() != numAtoms || !isComplete) {
                 report.addError("Invalid execution order in plan", cur.second->getSrcLoc());
             }
         }
     }
     // check auto-increment
     if (recursiveClauses.recursive(&clause)) {
         visitDepthFirst(clause, [&](const Counter& ctr) {
             report.addError("Auto-increment functor in a recursive rule", ctr.getSrcLoc());
         });
     }
 }
checkComplexRule()
void souffle::ast::transform::SemanticCheckerImpl::checkComplexRule (std::set< const Clause *> multiRule) private
Definition at line 566 of file SemanticChecker.cpp.
References souffle::ErrorReport::addWarning(), souffle::ast::getBodyLiterals(), and souffle::ast::visitDepthFirst().
Referenced by SemanticCheckerImpl().
{
     std::map<std::string, int> var_count;
     std::map<std::string, const ast::Variable*> var_pos;
     // Count the variable occurrence for the body of a
     // complex rule only once.
     // TODO (b-scholz): for negation / disjunction this is not quite
     // right; we would need more semantic information here.
     for (auto literal : (*multiRule.begin())->getBodyLiterals()) {
         visitDepthFirst(*literal, [&](const ast::Variable& var) {
             var_count[var.getName()]++;
             var_pos[var.getName()] = &var;
         });
     }
     // Count variable occurrence for each head separately
     for (auto clause : multiRule) {
         visitDepthFirst(*(clause->getHead()), [&](const ast::Variable& var) {
             var_count[var.getName()]++;
             var_pos[var.getName()] = &var;
         });
     }
     // Check that a variables occurs more than once
     for (const auto& cur : var_count) {
         int numAppearances = cur.second;
         const auto& varName = cur.first;
         const auto& varLocation = var_pos[varName]->getSrcLoc();
         if (varName[0] != '_' && numAppearances == 1) {
             report.addWarning("Variable " + varName + " only occurs once", varLocation);
         }
     }
 }
checkConstant()
void souffle::ast::transform::SemanticCheckerImpl::checkConstant (const Argument & argument) private
checkFact()
void souffle::ast::transform::SemanticCheckerImpl::checkFact (const Clause & fact) private
Definition at line 478 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Atom::getArguments(), souffle::ast::Clause::getHead(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), and souffle::ast::isFact().
Referenced by checkClause().
{
     assert(isFact(fact));
     Atom* head = fact.getHead();
     if (head == nullptr) {
         return;  // checked by clause
     }
     Relation* rel = getRelation(program, head->getQualifiedName());
     if (rel == nullptr) {
         return;  // checked by clause
     }
     // facts must only contain constants
     for (auto* arg : head->getArguments()) {
         if (!isConstantArgument(arg)) {
             report.addError("Argument in fact is not constant", arg->getSrcLoc());
         }
     }
 }
checkInlining()
void souffle::ast::transform::SemanticCheckerImpl::checkInlining () private
Definition at line 1051 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::transform::findInlineCycle(), souffle::ast::Negation::getAtom(), souffle::ast::Node::getChildNodes(), souffle::ast::getClauses(), souffle::ast::Relation::getQualifiedName(), souffle::ast::Atom::getQualifiedName(), souffle::ast::getRelation(), souffle::ast::Program::getRelations(), souffle::ast::Node::getSrcLoc(), i, souffle::INLINE, souffle::ast::analysis::IOTypeAnalysis::isIO(), relation, souffle::toString(), and souffle::ast::visitDepthFirst().
Referenced by SemanticCheckerImpl().
{
     auto isInline = [&](const Relation* rel) { return rel->hasQualifier(RelationQualifier::INLINE); };
     // Find all inlined relations
     RelationSet inlinedRelations;
     for (const auto& relation : program.getRelations()) {
         if (isInline(relation)) {
             inlinedRelations.insert(relation);
             if (ioTypes.isIO(relation)) {
                 report.addError(
                         "IO relation " + toString(relation->getQualifiedName()) + " cannot be inlined",
                         relation->getSrcLoc());
             }
         }
     }
     // Check 1:
     // Let G' be the subgraph of the precedence graph G containing only those nodes
     // which are marked with the inline directive.
     // If G' contains a cycle, then inlining cannot be performed.
     RelationSet unvisited;  // nodes that have not been visited yet
     RelationSet visiting;   // nodes that we are currently visiting
     RelationSet visited;    // nodes that have been completely explored
     // All nodes are initially unvisited
     for (const Relation* rel : inlinedRelations) {
         unvisited.insert(rel);
     }
     // Remember the parent node of each visited node to construct the found cycle
     std::map<const Relation*, const Relation*> origins;
     std::vector<QualifiedName> result =
             findInlineCycle(precedenceGraph, origins, nullptr, unvisited, visiting, visited);
     // If the result contains anything, then a cycle was found
     if (!result.empty()) {
         Relation* cycleOrigin = getRelation(program, result[result.size() - 1]);
         // Construct the string representation of the cycle
         std::stringstream cycle;
         cycle << "{" << cycleOrigin->getQualifiedName();
         // Print it backwards to preserve the initial cycle order
         for (int i = result.size() - 2; i >= 0; i--) {
             cycle << ", " << result[i];
         }
         cycle << "}";
         report.addError(
                 "Cannot inline cyclically dependent relations " + cycle.str(), cycleOrigin->getSrcLoc());
     }
     // Check 2:
     // Cannot use the counter argument ('$') in inlined relations
     // Check if an inlined literal ever takes in a $
     visitDepthFirst(program, [&](const Atom& atom) {
         Relation* associatedRelation = getRelation(program, atom.getQualifiedName());
         if (associatedRelation != nullptr && isInline(associatedRelation)) {
             visitDepthFirst(atom, [&](const Argument& arg) {
                 if (isA<Counter>(&arg)) {
                     report.addError(
                             "Cannot inline literal containing a counter argument '$'", arg.getSrcLoc());
                 }
             });
         }
     });
     // Check if an inlined clause ever contains a $
     for (const Relation* rel : inlinedRelations) {
         for (Clause* clause : getClauses(program, *rel)) {
             visitDepthFirst(*clause, [&](const Argument& arg) {
                 if (isA<Counter>(&arg)) {
                     report.addError(
                             "Cannot inline clause containing a counter argument '$'", arg.getSrcLoc());
                 }
             });
         }
     }
     // Check 3:
     // Suppose the relation b is marked with the inline directive, but appears negated
     // in a clause. Then, if b introduces a new variable in its body, we cannot inline
     // the relation b.
     // Find all relations with the inline declarative that introduce new variables in their bodies
     RelationSet nonNegatableRelations;
     for (const Relation* rel : inlinedRelations) {
         bool foundNonNegatable = false;
         for (const Clause* clause : getClauses(program, *rel)) {
             // Get the variables in the head
             std::set<std::string> headVariables;
             visitDepthFirst(*clause->getHead(),
                     [&](const ast::Variable& var) { headVariables.insert(var.getName()); });
             // Get the variables in the body
             std::set<std::string> bodyVariables;
             visitDepthFirst(clause->getBodyLiterals(),
                     [&](const ast::Variable& var) { bodyVariables.insert(var.getName()); });
             // Check if all body variables are in the head
             // Do this separately to the above so only one error is printed per variable
             for (const std::string& var : bodyVariables) {
                 if (headVariables.find(var) == headVariables.end()) {
                     nonNegatableRelations.insert(rel);
                     foundNonNegatable = true;
                     break;
                 }
             }
             if (foundNonNegatable) {
                 break;
             }
         }
     }
     // Check that these relations never appear negated
     visitDepthFirst(program, [&](const Negation& neg) {
         Relation* associatedRelation = getRelation(program, neg.getAtom()->getQualifiedName());
         if (associatedRelation != nullptr &&
                 nonNegatableRelations.find(associatedRelation) != nonNegatableRelations.end()) {
             report.addError(
                     "Cannot inline negated relation which may introduce new variables", neg.getSrcLoc());
         }
     });
     // Check 4:
     // Don't support inlining atoms within aggregators at this point.
     // Reasoning: Suppose we have an aggregator like `max X: a(X)`, where `a` is inlined to `a1` and `a2`.
     // Then, `max X: a(X)` will become `max( max X: a1(X),  max X: a2(X) )`. Suppose further that a(X) has
     // values X where it is true, while a2(X) does not. Then, the produced argument
     // `max( max X: a1(X),  max X: a2(X) )` will not return anything (as one of its arguments fails), while
     // `max X: a(X)` will.
     // Can work around this with emptiness checks (e.g. `!a1(_), ... ; !a2(_), ... ; ...`)
     // This corner case prevents generalising aggregator inlining with the current set up.
     visitDepthFirst(program, [&](const Aggregator& aggr) {
         visitDepthFirst(aggr, [&](const Atom& subatom) {
             const Relation* rel = getRelation(program, subatom.getQualifiedName());
             if (rel != nullptr && isInline(rel)) {
                 report.addError("Cannot inline relations that appear in aggregator", subatom.getSrcLoc());
             }
         });
     });
     // Check 5:
     // Suppose a relation `a` is inlined, appears negated in a clause, and contains a
     // (possibly nested) unnamed variable in its arguments. Then, the atom can't be
     // inlined, as unnamed variables are named during inlining (since they may appear
     // multiple times in an inlined-clause's body) => ungroundedness!
     // Exception: It's fine if the unnamed variable appears in a nested aggregator, as
     // the entire aggregator will automatically be grounded.
     // TODO (azreika): special case where all rules defined for `a` use the
     // underscored-argument exactly once: can workaround by remapping the variable
     // back to an underscore - involves changes to the actual inlining algo, though
     // Returns the pair (isValid, lastSrcLoc) where:
     //  - isValid is true if and only if the node contains an invalid underscore, and
     //  - lastSrcLoc is the source location of the last visited node
     std::function<std::pair<bool, SrcLocation>(const Node*)> checkInvalidUnderscore = [&](const Node* node) {
         if (isA<UnnamedVariable>(node)) {
             // Found an invalid underscore
             return std::make_pair(true, node->getSrcLoc());
         } else if (isA<Aggregator>(node)) {
             // Don't care about underscores within aggregators
             return std::make_pair(false, node->getSrcLoc());
         }
         // Check if any children nodes use invalid underscores
         for (const Node* child : node->getChildNodes()) {
             std::pair<bool, SrcLocation> childStatus = checkInvalidUnderscore(child);
             if (childStatus.first) {
                 // Found an invalid underscore
                 return childStatus;
             }
         }
         return std::make_pair(false, node->getSrcLoc());
     };
     // Perform the check
     visitDepthFirst(program, [&](const Negation& negation) {
         const Atom* associatedAtom = negation.getAtom();
         const Relation* associatedRelation = getRelation(program, associatedAtom->getQualifiedName());
         if (associatedRelation != nullptr && isInline(associatedRelation)) {
             std::pair<bool, SrcLocation> atomStatus = checkInvalidUnderscore(associatedAtom);
             if (atomStatus.first) {
                 report.addError(
                         "Cannot inline negated atom containing an unnamed variable unless the variable is "
                         "within an aggregator",
                         atomStatus.second);
             }
         }
     });
 }
checkIO()
void souffle::ast::transform::SemanticCheckerImpl::checkIO () private
Definition at line 811 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Program::getDirectives(), souffle::ast::getRelation(), and souffle::toString().
Referenced by SemanticCheckerImpl().
{
     auto checkIO = [&](const Directive* directive) {
         auto* r = getRelation(program, directive->getQualifiedName());
         if (r == nullptr) {
             report.addError(
                     "Undefined relation " + toString(directive->getQualifiedName()), directive->getSrcLoc());
         }
     };
     for (const auto* directive : program.getDirectives()) {
         checkIO(directive);
     }
 }
checkLiteral()
void souffle::ast::transform::SemanticCheckerImpl::checkLiteral (const Literal & literal) private
Definition at line 342 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkArgument(), checkAtom(), souffle::contains(), souffle::ast::Term::getArguments(), and souffle::ast::visitDepthFirst().
Referenced by checkAggregator(), and checkClause().
{
     // check potential nested atom
     if (const auto* atom = as<Atom>(literal)) {
         checkAtom(*atom);
     }
     if (const auto* neg = as<Negation>(literal)) {
         checkAtom(*neg->getAtom());
     }
     if (const auto* constraint = as<BinaryConstraint>(literal)) {
         checkArgument(*constraint->getLHS());
         checkArgument(*constraint->getRHS());
         std::set<const UnnamedVariable*> unnamedInRecord;
         visitDepthFirst(*constraint, [&](const RecordInit& record) {
             for (auto* arg : record.getArguments()) {
                 if (auto* unnamed = as<UnnamedVariable>(arg)) {
                     unnamedInRecord.insert(unnamed);
                 }
             }
         });
         // Check if constraint contains unnamed variables.
         for (auto* unnamed : getUnnamedVariables(*constraint)) {
             if (!contains(unnamedInRecord, unnamed)) {
                 report.addError("Underscore in binary relation", unnamed->getSrcLoc());
             }
         }
     }
 }
checkNamespaces()
void souffle::ast::transform::SemanticCheckerImpl::checkNamespaces () private
Definition at line 1255 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ast::Program::getRelations(), souffle::ast::Program::getTypes(), and souffle::toString().
Referenced by SemanticCheckerImpl().
{
     std::map<std::string, SrcLocation> names;
     // Find all names and report redeclarations as we go.
     for (const auto& type : program.getTypes()) {
         const std::string name = toString(type->getQualifiedName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on type " + name, type->getSrcLoc());
         } else {
             names[name] = type->getSrcLoc();
         }
     }
     for (const auto& rel : program.getRelations()) {
         const std::string name = toString(rel->getQualifiedName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on relation " + name, rel->getSrcLoc());
         } else {
             names[name] = rel->getSrcLoc();
         }
     }
 }
checkRecordType()
void souffle::ast::transform::SemanticCheckerImpl::checkRecordType (const ast::RecordType & type) private
Definition at line 700 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::ast::analysis::RecordType::getFields(), souffle::getName, i, souffle::ast::analysis::TypeEnvironment::isType(), and j.
Referenced by checkTypesDeclarations().
{
     auto&& fields = type.getFields();
     // check proper definition of all field types
     for (auto&& field : fields) {
         if (!typeEnv.isType(field->getTypeName())) {
             report.addError(tfm::format("Undefined type %s in definition of field %s", field->getTypeName(),
                                     field->getName()),
                     field->getSrcLoc());
         }
     }
     // check that field names are unique
     for (std::size_t i = 0; i < fields.size(); i++) {
         auto&& cur_name = fields[i]->getName();
         for (std::size_t j = 0; j < i; j++) {
             if (fields[j]->getName() == cur_name) {
                 report.addError(tfm::format("Doubly defined field name %s in definition of type %s", cur_name,
                                         type.getQualifiedName()),
                         fields[i]->getSrcLoc());
             }
         }
     }
 }
checkRelation()
void souffle::ast::transform::SemanticCheckerImpl::checkRelation (const Relation & relation) private
Definition at line 624 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ErrorReport::addWarning(), checkRelationDeclaration(), souffle::EQREL, souffle::ast::Relation::getArity(), souffle::ast::Relation::getAttributes(), souffle::ast::getClauses(), souffle::ast::Relation::getQualifiedName(), souffle::ast::Relation::getRepresentation(), souffle::ast::Node::getSrcLoc(), souffle::ast::Relation::hasQualifier(), souffle::ast::analysis::IOTypeAnalysis::isInput(), souffle::SUPPRESSED, and souffle::toString().
Referenced by SemanticCheckerImpl().
{
     if (relation.getRepresentation() == RelationRepresentation::EQREL) {
         if (relation.getArity() == 2) {
             const auto& attributes = relation.getAttributes();
             assert(attributes.size() == 2 && "mismatching attribute size and arity");
             if (attributes[0]->getTypeName() != attributes[1]->getTypeName()) {
                 report.addError("Domains of equivalence relation " + toString(relation.getQualifiedName()) +
                                         " are different",
                         relation.getSrcLoc());
             }
         } else {
             report.addError(
                     "Equivalence relation " + toString(relation.getQualifiedName()) + " is not binary",
                     relation.getSrcLoc());
         }
     }
     // start with declaration
     checkRelationDeclaration(relation);
     // check whether this relation is empty
     if (getClauses(program, relation).empty() && !ioTypes.isInput(&relation) &&
             !relation.hasQualifier(RelationQualifier::SUPPRESSED)) {
         report.addWarning("No rules/facts defined for relation " + toString(relation.getQualifiedName()),
                 relation.getSrcLoc());
     }
 }
checkRelationDeclaration()
void souffle::ast::transform::SemanticCheckerImpl::checkRelationDeclaration (const Relation & relation) private
Definition at line 600 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::ast::Relation::getArity(), souffle::ast::Relation::getAttributes(), souffle::getIf(), souffle::ast::Attribute::getName(), souffle::ast::Node::getSrcLoc(), souffle::ast::Attribute::getTypeName(), souffle::ast::Program::getTypes(), i, souffle::ast::analysis::TypeEnvironment::isPrimitiveType(), and j.
Referenced by checkRelation().
{
     const auto& attributes = relation.getAttributes();
     assert(attributes.size() == relation.getArity() && "mismatching attribute size and arity");
     for (size_t i = 0; i < relation.getArity(); i++) {
         Attribute* attr = attributes[i];
         auto&& typeName = attr->getTypeName();
         auto* existingType = getIf(program.getTypes(),
                 [&](const ast::Type* type) { return type->getQualifiedName() == typeName; });
         /* check whether type exists */
         if (!typeEnv.isPrimitiveType(typeName) && nullptr == existingType) {
             report.addError(tfm::format("Undefined type in attribute %s", *attr), attr->getSrcLoc());
         }
         /* check whether name occurs more than once */
         for (size_t j = 0; j < i; j++) {
             if (attr->getName() == attributes[j]->getName()) {
                 report.addError(tfm::format("Doubly defined attribute name %s", *attr), attr->getSrcLoc());
             }
         }
     }
 }
checkSubsetType()
void souffle::ast::transform::SemanticCheckerImpl::checkSubsetType (const ast::SubsetType & type) private
Definition at line 737 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::ast::analysis::SubsetType::getBaseType(), souffle::ast::analysis::Type::getName(), souffle::ast::analysis::TypeEnvironment::getType(), souffle::ast::analysis::TypeEnvironmentAnalysis::isCyclic(), and souffle::ast::analysis::TypeEnvironment::isType().
Referenced by checkTypesDeclarations().
{
     if (typeEnvAnalysis.isCyclic(astType.getQualifiedName())) {
         report.addError(
                 tfm::format("Infinite descent in the definition of type %s", astType.getQualifiedName()),
                 astType.getSrcLoc());
         return;
     }
     if (!typeEnv.isType(astType.getBaseType())) {
         report.addError(tfm::format("Undefined base type %s in definition of type %s", astType.getBaseType(),
                                 astType.getQualifiedName()),
                 astType.getSrcLoc());
         return;
     }
     auto& rootType = typeEnv.getType(astType.getBaseType());
     if (isA<analysis::UnionType>(rootType)) {
         report.addError(tfm::format("Subset type %s can't be derived from union %s",
                                 astType.getQualifiedName(), rootType.getName()),
                 astType.getSrcLoc());
     }
 }
checkTypesDeclarations()
void souffle::ast::transform::SemanticCheckerImpl::checkTypesDeclarations () private
Definition at line 761 of file SemanticChecker.cpp.
References souffle::ErrorReport::addDiagnostic(), souffle::ErrorReport::addError(), checkADT(), checkRecordType(), checkSubsetType(), checkUnionType(), souffle::Diagnostic::ERROR, souffle::fatal(), tinyformat::format(), souffle::ast::Program::getTypes(), souffle::ast::analysis::TypeEnvironment::isPrimitiveType(), and souffle::ast::visitDepthFirst().
Referenced by SemanticCheckerImpl().
{
     // The redefinitions of types is checked by checkNamespaces
     for (auto* type : program.getTypes()) {
         if (typeEnv.isPrimitiveType(type->getQualifiedName())) {
             report.addError("Redefinition of the predefined type", type->getSrcLoc());
             continue;
         }
         if (isA<ast::UnionType>(type)) {
             checkUnionType(*as<ast::UnionType>(type));
         } else if (isA<ast::RecordType>(type)) {
             checkRecordType(*as<ast::RecordType>(type));
         } else if (isA<ast::SubsetType>(type)) {
             checkSubsetType(*as<ast::SubsetType>(type));
         } else if (isA<ast::AlgebraicDataType>(type)) {
             checkADT(*as<ast::AlgebraicDataType>(type));
         } else {
             fatal("unsupported type construct: %s", typeid(type).name());
         }
     }
     // Check if all the branch names are unique in sum types.
     std::map<std::string, std::vector<SrcLocation>> branchToLocation;
     visitDepthFirst(program.getTypes(), [&](const ast::AlgebraicDataType& type) {
         for (auto* branch : type.getBranches()) {
             branchToLocation[branch->getConstructor()].push_back(branch->getSrcLoc());
         }
     });
     for (auto& branchLocs : branchToLocation) {
         auto& branch = branchLocs.first;
         auto& locs = branchLocs.second;
         // If a branch is used only once, then everything is fine.
         if (locs.size() == 1) continue;
         auto primaryDiagnostic =
                 DiagnosticMessage(tfm::format("Branch %s is defined multiple times", branch));
         std::vector<DiagnosticMessage> branchDeclarations;
         for (auto& loc : locs) {
             branchDeclarations.push_back(DiagnosticMessage(tfm::format("Branch %s defined", branch), loc));
         }
         report.addDiagnostic(Diagnostic(
                 Diagnostic::Type::ERROR, std::move(primaryDiagnostic), std::move(branchDeclarations)));
     }
 }
checkUnionType()
void souffle::ast::transform::SemanticCheckerImpl::checkUnionType (const ast::UnionType & type) private
Definition at line 654 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::getIf(), souffle::ast::analysis::TypeEnvironmentAnalysis::getPrimitiveTypesInUnion(), souffle::ast::Program::getTypes(), souffle::ast::analysis::TypeEnvironmentAnalysis::isCyclic(), souffle::ast::analysis::TypeEnvironment::isPrimitiveType(), souffle::join(), souffle::ast::analysis::sub(), and souffle::toString().
Referenced by checkTypesDeclarations().
{
     // check presence of all the element types and that all element types are based off a primitive
     for (const QualifiedName& sub : type.getTypes()) {
         if (typeEnv.isPrimitiveType(sub)) {
             continue;
         }
         const ast::Type* subtype = getIf(
                 program.getTypes(), [&](const ast::Type* type) { return type->getQualifiedName() == sub; });
         if (subtype == nullptr) {
             report.addError(tfm::format("Undefined type %s in definition of union type %s", sub,
                                     type.getQualifiedName()),
                     type.getSrcLoc());
         } else if (!isA<ast::UnionType>(subtype) && !isA<ast::SubsetType>(subtype)) {
             report.addError(tfm::format("Union type %s contains the non-primitive type %s",
                                     type.getQualifiedName(), sub),
                     type.getSrcLoc());
         }
     }
     // Check if the union is recursive.
     if (typeEnvAnalysis.isCyclic(type.getQualifiedName())) {
         report.addError("Infinite descent in the definition of type " + toString(type.getQualifiedName()),
                 type.getSrcLoc());
     }
     /* check that union types do not mix different primitive types */
     for (const auto* type : program.getTypes()) {
         // We are only interested in unions here.
         if (!isA<ast::UnionType>(type)) {
             continue;
         }
         const auto& name = type->getQualifiedName();
         const auto& predefinedTypesInUnion = typeEnvAnalysis.getPrimitiveTypesInUnion(name);
         // Report error (if size == 0, then the union is cyclic)
         if (predefinedTypesInUnion.size() > 1) {
             report.addError(
                     tfm::format("Union type %s is defined over {%s} (multiple primitive types in union)",
                             name, join(predefinedTypesInUnion, ", ")),
                     type->getSrcLoc());
         }
     }
 }
checkWitnessProblem()
void souffle::ast::transform::SemanticCheckerImpl::checkWitnessProblem () private
Definition at line 945 of file SemanticChecker.cpp.
References souffle::ast::Atom::addArgument(), souffle::ErrorReport::addError(), souffle::clone(), souffle::ast::Clause::getBodyLiterals(), souffle::ast::Clause::getHead(), souffle::ast::transform::usesInvalidWitness(), and souffle::ast::visitDepthFirst().
Referenced by SemanticCheckerImpl().
{
     // Visit each clause to check if an invalid aggregator witness is used
     visitDepthFirst(program, [&](const Clause& clause) {
         // Body literals of the clause to check
         std::vector<Literal*> bodyLiterals = clause.getBodyLiterals();
         // Add in all head variables as new ungrounded body literals
         auto headVariables = mk<Atom>("*");
         visitDepthFirst(*clause.getHead(),
                 [&](const ast::Variable& var) { headVariables->addArgument(souffle::clone(&var)); });
         auto headNegation = mk<Negation>(std::move(headVariables));
         bodyLiterals.push_back(headNegation.get());
         // Perform the check
         std::set<Own<Argument>> groundedArguments;
         for (auto&& invalidArgument : usesInvalidWitness(tu, bodyLiterals, groundedArguments)) {
             report.addError(
                     "Witness problem: argument grounded by an aggregator's inner scope is used ungrounded in "
                     "outer scope",
                     invalidArgument);
         }
     });
 }
isDependent()
bool souffle::ast::transform::SemanticCheckerImpl::isDependent (const Clause & agg1, const Clause & agg2) private
agg1, agg2 are clauses which contain no head, and consist of a single literal that contains an aggregate.
agg1 is dependent on agg2 if agg1 contains a variable which is grounded by agg2, and not by agg1.
Definition at line 379 of file SemanticChecker.cpp.
References souffle::ast::analysis::getGroundedTerms(), and souffle::ast::visitDepthFirst().
Referenced by checkAggregator().
{
     auto groundedInAgg1 = getGroundedTerms(tu, agg1);
     auto groundedInAgg2 = getGroundedTerms(tu, agg2);
     bool dependent = false;
     // For each variable X in the first aggregate
     visitDepthFirst(agg1, [&](const ast::Variable& searchVar) {
         // Try to find the corresponding variable X in the second aggregate
         // by string comparison
         const ast::Variable* matchingVarPtr = nullptr;
         visitDepthFirst(agg2, [&](const ast::Variable& var) {
             if (var == searchVar) {
                 matchingVarPtr = &var;
                 return;
             }
         });
         // If the variable occurs in both clauses (a match was found)
         if (matchingVarPtr != nullptr) {
             if (!groundedInAgg1[&searchVar] && groundedInAgg2[matchingVarPtr]) {
                 dependent = true;
             }
         }
     });
     return dependent;
 }
Field Documentation
ioTypes
const IOTypeAnalysis& souffle::ast::transform::SemanticCheckerImpl::ioTypes = *tu.getAnalysis<IOTypeAnalysis>() private
Definition at line 104 of file SemanticChecker.cpp.
precedenceGraph
const PrecedenceGraphAnalysis& souffle::ast::transform::SemanticCheckerImpl::precedenceGraph = *tu.getAnalysis<PrecedenceGraphAnalysis>() private
Definition at line 105 of file SemanticChecker.cpp.
program
const Program& souffle::ast::transform::SemanticCheckerImpl::program = tu.getProgram() private
Definition at line 112 of file SemanticChecker.cpp.
recursiveClauses
const RecursiveClausesAnalysis& souffle::ast::transform::SemanticCheckerImpl::recursiveClauses = *tu.getAnalysis<RecursiveClausesAnalysis>() private
Definition at line 106 of file SemanticChecker.cpp.
report
ErrorReport& souffle::ast::transform::SemanticCheckerImpl::report = tu.getErrorReport() private
Definition at line 113 of file SemanticChecker.cpp.
sccGraph
const SCCGraphAnalysis& souffle::ast::transform::SemanticCheckerImpl::sccGraph = *tu.getAnalysis<SCCGraphAnalysis>() private
Definition at line 108 of file SemanticChecker.cpp.
sumTypesBranches
const SumTypeBranchesAnalysis& souffle::ast::transform::SemanticCheckerImpl::sumTypesBranches = *tu.getAnalysis<SumTypeBranchesAnalysis>() private
Definition at line 109 of file SemanticChecker.cpp.
tu
TranslationUnit& souffle::ast::transform::SemanticCheckerImpl::tu
Definition at line 100 of file SemanticChecker.cpp.
typeEnv
const TypeEnvironment& souffle::ast::transform::SemanticCheckerImpl::typeEnv = typeEnvAnalysis.getTypeEnvironment() private
Definition at line 111 of file SemanticChecker.cpp.
typeEnvAnalysis
const TypeEnvironmentAnalysis& souffle::ast::transform::SemanticCheckerImpl::typeEnvAnalysis = *tu.getAnalysis<TypeEnvironmentAnalysis>() private
Definition at line 107 of file SemanticChecker.cpp.
The documentation for this struct was generated from the following file:
ast/transform/SemanticChecker.cpp