souffle: souffle::ast::analysis::AlgebraicDataType::Branch Struct Reference
souffle::ast::analysis::AlgebraicDataType::Branch Struct Reference
#include <TypeSystem.h>
Public Member Functions
void print (std::ostream &out) const
Data Fields
std::string name
std::vector< const Type * > types
Detailed Description
Definition at line 218 of file TypeSystem.h.
Member Function Documentation
print()
void souffle::ast::analysis::AlgebraicDataType::Branch::print (std::ostream & out) const inline
Definition at line 222 of file TypeSystem.h.
References tinyformat::format(), souffle::ast::analysis::Type::getName(), and souffle::join().
Referenced by souffle::ast::analysis::AlgebraicDataType::print().
{
             out << tfm::format("%s {%s}", this->name,
                     join(types, ", ", [](std::ostream& out, const Type* t) { out << t->getName(); }));
         }
Field Documentation
name
std::string souffle::ast::analysis::AlgebraicDataType::Branch::name
Definition at line 219 of file TypeSystem.h.
Referenced by souffle::ast::analysis::AlgebraicDataType::setBranches().
types
std::vector<const Type*> souffle::ast::analysis::AlgebraicDataType::Branch::types
Definition at line 220 of file TypeSystem.h.
The documentation for this struct was generated from the following file:
ast/analysis/TypeSystem.h