souffle: souffle::ast::analysis::TypeSet Struct Reference
souffle::ast::analysis::TypeSet Struct Reference
A collection to represent sets of types.
#include <TypeSystem.h>
Public Types
using const_iterator = IterDerefWrapper< typename std::set< const Type * >::const_iterator >
Public Member Functions
const_iterator begin () const
Allows to iterate over the types contained in this set (only if not universal)
bool contains (const Type &type) const
Determines whether a given type is included or not.
bool empty () const
const_iterator end () const
Allows to iterate over the types contained in this set (only if not universal)
template<typename F >
TypeSet filter (TypeSet whenAll, F &&f) const
void insert (const Type &type)
Adds the given type to this set.
void insert (const TypeSet &set)
Inserts all the types of the given set into this set.
bool isAll () const
Universality check.
bool isSubsetOf (const TypeSet &b) const
Determines whether this set is a subset of the given set.
bool operator!= (const TypeSet &other) const
Determines inequality between type sets.
TypeSet & operator= (const TypeSet &other)=default
TypeSet & operator= (TypeSet &&other)=default
bool operator== (const TypeSet &other) const
Determines equality between type sets.
void print (std::ostream &out) const
Adds print support for type sets.
std::size_t size () const
Determines the size of this set unless it is the universal set.
TypeSet (bool all=false)
template<typename... Types>
TypeSet (const Types &... types)
TypeSet (const TypeSet &other)=default
TypeSet (TypeSet &&other)=default
Static Public Member Functions
static TypeSet intersection (const TypeSet &left, const TypeSet &right)
Calculate intersection of two TypeSet.
Private Attributes
bool all
True if it is the all-types set, false otherwise.
std::set< const Type *, deref_less< Type > > types
The enumeration of types in case it is not the all-types set.
Friends
std::ostream & operator<< (std::ostream &out, const TypeSet &set)
Detailed Description
A collection to represent sets of types.
In addition to ordinary set capabilities it may also represent the set of all types – without being capable of iterating over those.
It is the basic entity to conduct sub- and super-type computations.
Definition at line 266 of file TypeSystem.h.
Member Typedef Documentation
const_iterator
using souffle::ast::analysis::TypeSet::const_iterator = IterDerefWrapper<typename std::set<const Type*>::const_iterator>
Definition at line 268 of file TypeSystem.h.
Constructor & Destructor Documentation
TypeSet() [1/4]
souffle::ast::analysis::TypeSet::TypeSet (bool all = false) inline
Definition at line 270 of file TypeSystem.h.
 : all(all) {}
TypeSet() [2/4]
template<typename... Types> souffle::ast::analysis::TypeSet::TypeSet (const Types &... types) inline explicit
Definition at line 273 of file TypeSystem.h.
                                             : all(false) {
         for (const Type* cur : toVector<const Type*>(&types...)) {
             this->types.insert(cur);
         }
     }
TypeSet() [3/4]
souffle::ast::analysis::TypeSet::TypeSet (const TypeSet & other) default
TypeSet() [4/4]
souffle::ast::analysis::TypeSet::TypeSet (TypeSet && other) default
Member Function Documentation
begin()
const_iterator souffle::ast::analysis::TypeSet::begin () const inline
Allows to iterate over the types contained in this set (only if not universal)
Definition at line 360 of file TypeSystem.h.
References souffle::derefIter(), and types.
Referenced by souffle::ast::transform::TypeChecker::visitBinaryConstraint(), souffle::ast::transform::TypeChecker::visitBranchInit(), and souffle::ast::transform::TypeChecker::visitRecordInit().
{
         assert(!all && "Unable to enumerate universe.");
         return derefIter(types.begin());
     }
contains()
bool souffle::ast::analysis::TypeSet::contains (const Type & type) const inline
Determines whether a given type is included or not.
Definition at line 300 of file TypeSystem.h.
References types.
Referenced by intersection(), and isSubsetOf().
{
         return all || types.find(&type) != types.end();
     }
empty()
bool souffle::ast::analysis::TypeSet::empty () const inline
Definition at line 284 of file TypeSystem.h.
References types.
Referenced by souffle::ast::analysis::getGreatestCommonSubtypes(), souffle::ast::analysis::isOfKind(), and souffle::ast::transform::TypeChecker::visitVariable().
{
         return !all && types.empty();
     }
end()
const_iterator souffle::ast::analysis::TypeSet::end () const inline
Allows to iterate over the types contained in this set (only if not universal)
Definition at line 366 of file TypeSystem.h.
References souffle::derefIter(), and types.
{
         assert(!all && "Unable to enumerate universe.");
         return derefIter(types.end());
     }
filter()
template<typename F > TypeSet souffle::ast::analysis::TypeSet::filter (TypeSet whenAll, F && f) const inline
Definition at line 331 of file TypeSystem.h.
References insert().
{
         if (all) return whenAll;
         TypeSet cpy;
         for (auto&& t : *this)
             if (f(t)) cpy.insert(t);
         return cpy;
     }
insert() [1/2]
void souffle::ast::analysis::TypeSet::insert (const Type & type) inline
Adds the given type to this set.
Definition at line 305 of file TypeSystem.h.
References types.
Referenced by filter(), souffle::ast::analysis::getGreatestCommonSubtypes(), intersection(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
{
         if (!all) {
             types.insert(&type);
         }
     }
insert() [2/2]
void souffle::ast::analysis::TypeSet::insert (const TypeSet & set) inline
Inserts all the types of the given set into this set.
Definition at line 341 of file TypeSystem.h.
References types.
{
         if (all) {
             return;
         }
         // if the other set is universal => make this one universal
         if (set.isAll()) {
             all = true;
             types.clear();
             return;
         }
         // add types one by one
         for (const auto& t : set) {
             insert(t);
         }
     }
intersection()
static TypeSet souffle::ast::analysis::TypeSet::intersection (const TypeSet & left, const TypeSet & right) inline static
Calculate intersection of two TypeSet.
Definition at line 312 of file TypeSystem.h.
References contains(), insert(), and isAll().
{
         TypeSet result;
         if (left.isAll()) {
             return right;
         } else if (right.isAll()) {
             return left;
         }
         for (const auto& element : left) {
             if (right.contains(element)) {
                 result.insert(element);
             }
         }
         return result;
     }
isAll()
bool souffle::ast::analysis::TypeSet::isAll () const inline
Universality check.
Definition at line 289 of file TypeSystem.h.
Referenced by souffle::ast::analysis::getGreatestCommonSubtypes(), intersection(), souffle::ast::analysis::isOfKind(), isSubsetOf(), and souffle::ast::transform::TypeChecker::visitBranchInit().
{
         return all;
     }
isSubsetOf()
bool souffle::ast::analysis::TypeSet::isSubsetOf (const TypeSet & b) const inline
Determines whether this set is a subset of the given set.
Definition at line 372 of file TypeSystem.h.
References souffle::all_of(), contains(), and isAll().
{
         if (all) {
             return b.isAll();
         }
         return all_of(*this, [&](const Type& cur) { return b.contains(cur); });
     }
operator!=()
bool souffle::ast::analysis::TypeSet::operator!= (const TypeSet & other) const inline
Determines inequality between type sets.
Definition at line 385 of file TypeSystem.h.
{
         return !(*this == other);
     }
operator=() [1/2]
TypeSet& souffle::ast::analysis::TypeSet::operator= (const TypeSet & other) default
operator=() [2/2]
TypeSet& souffle::ast::analysis::TypeSet::operator= (TypeSet && other) default
operator==()
bool souffle::ast::analysis::TypeSet::operator== (const TypeSet & other) const inline
Determines equality between type sets.
Definition at line 380 of file TypeSystem.h.
References all, types, and types.
{
         return all == other.all && types == other.types;
     }
print()
void souffle::ast::analysis::TypeSet::print (std::ostream & out) const inline
Adds print support for type sets.
Definition at line 390 of file TypeSystem.h.
References souffle::ast::analysis::Type::getName(), souffle::join(), and types.
{
         if (all) {
             out << "{ - all types - }";
         } else {
             out << "{"
                 << join(types, ",", [](std::ostream& out, const Type* type) { out << type->getName(); })
                 << "}";
         }
     }
size()
std::size_t souffle::ast::analysis::TypeSet::size () const inline
Determines the size of this set unless it is the universal set.
Definition at line 294 of file TypeSystem.h.
References types.
Referenced by souffle::ast::transform::TypeChecker::visitBranchInit(), and souffle::ast::transform::TypeChecker::visitRecordInit().
{
         assert(!all && "Unable to give size of universe.");
         return types.size();
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const TypeSet & set) friend
Definition at line 400 of file TypeSystem.h.
{
         set.print(out);
         return out;
     }
Field Documentation
all
bool souffle::ast::analysis::TypeSet::all private
True if it is the all-types set, false otherwise.
Definition at line 407 of file TypeSystem.h.
Referenced by operator==().
types
std::set<const Type*, deref_less<Type> > souffle::ast::analysis::TypeSet::types private
The enumeration of types in case it is not the all-types set.
Definition at line 410 of file TypeSystem.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
ast/analysis/TypeSystem.h